# Pipeline Logging Demo

This script demonstrates the user-facing logging added by #14. It requires a
running NDD/DataDesigner backend. Run cells individually in VS Code or PyCharm.

In [1]:
from anonymizer.logging import LoggingConfig, configure_logging  # noqa: F401

configure_logging()  # default: anonymizer INFO, DD suppressed
# configure_logging(LoggingConfig.verbose())  # anonymizer INFO + DD progress
# configure_logging(LoggingConfig.debug())    # everything DEBUG

/Users/amanoel/Code/Anonymizer/checkouts/feat-pipeline-logging/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import tempfile
from pathlib import Path

import pandas as pd

tmp_dir = tempfile.mkdtemp(prefix="logging_demo_")
csv_path = Path(tmp_dir) / "sample.csv"

pd.DataFrame(
    {
        "text": [
            "Alice Johnson works at Acme Corp in Portland, Oregon.",
            "Contact Bob Smith at bob.smith@example.com or 555-0123.",
            "Dr. Carol Lee treated patient #12345 on 2024-03-15.",
        ]
    }
).to_csv(csv_path, index=False)

print(f"Sample data saved to {csv_path}")

Sample data saved to /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv

## Scenario 1: Full run with Redact replacement

In [3]:
from anonymizer.config.anonymizer_config import AnonymizerConfig, AnonymizerInput
from anonymizer.config.replace_strategies import Redact
from anonymizer.interface.anonymizer import Anonymizer

anonymizer = Anonymizer()
result = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result.dataframe

[19:05:43] [INFO] 🔧 Anonymizer initialized with 3 model configs

[19:05:43] [INFO]   |-- 🔎 detector:  gliner-pii-detector

[19:05:43] [INFO]   |-- ✅ validator: gpt-oss-120b

[19:05:43] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

[19:05:43] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv (column: 'text')

[19:05:43] [INFO] 🔍 Running entity detection on 3 records

[19:05:54] [INFO]   |-- 📋 Detection complete — 3 entities found across 3 records (0 failed) [10.9s]

[19:05:54] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, date=1

[19:05:54] [INFO] 🔄 Running Redact replacement

[19:05:54] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[19:05:54] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,Dr. <first_name>Carol</first_name> <last_name>...,"{'entities': [{'id': 'first_name_4_9', 'value'...",Dr. [REDACTED_FIRST_NAME] [REDACTED_LAST_NAME]...

## Scenario 2: Preview mode

In [4]:
preview = anonymizer.preview(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
    num_records=2,
)
preview.dataframe

[19:05:54] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv (column: 'text')

[19:05:54] [INFO]   |-- 👀 Preview mode: processing 2 of 3 records

[19:05:54] [INFO] 🔍 Running entity detection on 3 records

[19:06:01] [INFO]   |-- 📋 Detection complete — 2 entities found across 2 records (0 failed) [6.5s]

[19:06:01] [INFO]   |-- labels: first_name=2, last_name=2, company_name=1, city=1, state=1, email=1, phone_number=1

[19:06:01] [INFO] 🔄 Running Redact replacement

[19:06:01] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[19:06:01] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...

## Scenario 3: Detection only (no replacement)

In [5]:
from anonymizer.config.anonymizer_config import Rewrite

result_detect_only = anonymizer.run(
    config=AnonymizerConfig(rewrite=Rewrite()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_detect_only.dataframe

[19:06:01] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv (column: 'text')

[19:06:01] [INFO] 🔍 Running entity detection on 3 records

[19:06:16] [INFO]   |-- 📋 Detection complete — 3 entities found across 3 records (0 failed) [15.5s]

[19:06:16] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, occupation=1, date=1

[19:06:16] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'..."
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value..."
2,Dr. Carol Lee treated patient #12345 on 2024-0...,<occupation>Dr.</occupation> <first_name>Carol...,"{'entities': [{'id': 'occupation_0_3', 'value'..."

## Scenario 4: Verbose mode (surfaces DataDesigner progress)

In [6]:
configure_logging(LoggingConfig.verbose())

result_verbose = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_verbose.dataframe

[19:06:16] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv (column: 'text')

[19:06:16] [INFO] 🔍 Running entity detection on 3 records

[19:06:16] [INFO] 🎨 Creating Data Designer dataset

[19:06:16] [INFO] ✅ Validation passed

[19:06:16] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[19:06:16] [INFO] 🩺 Running health checks for models...

[19:06:16] [INFO]   |-- ⏭️  Skipping health check for model alias 'gliner-pii-detector' (skip_health_check=True)

[19:06:16] [INFO]   |-- 👀 Checking 'nvdev/openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[19:06:17] [INFO]   |-- ✅ Passed!

[19:06:17] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-06-2026_190617' instead.

[19:06:17] [INFO] ⏳ Processing batch 1 of 1

[19:06:17] [INFO] 🌱 Sampling 3 records from seed dataset

[19:06:17] [INFO]   |-- seed dataset size: 3 records

[19:06:17] [INFO]   |-- sampling strategy: ordered

[19:06:17] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[19:06:17] [INFO]   |-- model: 'nvidia/gliner-pii'

[19:06:17] [INFO]   |-- model alias: 'gliner-pii-detector'

[19:06:17] [INFO]   |-- model provider: 'nvidia'

[19:06:17] [INFO]   |-- inference parameters:

[19:06:17] [INFO]   |  |-- generation_type=chat-completion

[19:06:17] [INFO]   |  |-- max_parallel_requests=16

[19:06:17] [INFO]   |  |-- timeout=120

[19:06:17] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[19:06:17] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers

[19:06:17] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record

[19:06:18] [INFO]   |-- 🥱 llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.67 rec/s, eta 1.2s

[19:06:18] [INFO]   |-- 😐 llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 3.28 rec/s, eta 0.3s

[19:06:18] [INFO]   |-- 🤩 llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 4.91 rec/s, eta 0.0s

[19:06:18] [INFO] 🔧 Custom column config for column '_seed_entities'

[19:06:18] [INFO]   |-- generator_function: 'parse_detected_entities'

[19:06:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:18] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[19:06:18] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[19:06:18] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[19:06:18] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record

[19:06:18] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 888.20 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1261.47 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🚀 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1277.64 rec/s, eta 0.0s

[19:06:18] [INFO] 🔧 Custom column config for column '_validation_candidates'

[19:06:18] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[19:06:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:18] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[19:06:18] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[19:06:18] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[19:06:18] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record

[19:06:18] [INFO]   |-- 🐣 custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1281.09 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🐥 custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1729.29 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🐔 custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1762.50 rec/s, eta 0.0s

[19:06:18] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[19:06:18] [INFO]   |-- generator_function: 'build_validation_skeleton'

[19:06:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:18] [INFO]   |-- required_columns: ['_validation_candidates']

[19:06:18] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[19:06:18] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record

[19:06:18] [INFO]   |-- 🐣 custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1491.42 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🐥 custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1976.77 rec/s, eta 0.0s

[19:06:18] [INFO]   |-- 🐔 custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2009.60 rec/s, eta 0.0s

[19:06:18] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[19:06:18] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[19:06:18] [INFO]   |-- model alias: 'gpt-oss-120b'

[19:06:18] [INFO]   |-- model provider: 'nvidia'

[19:06:18] [INFO]   |-- inference parameters:

[19:06:18] [INFO]   |  |-- generation_type=chat-completion

[19:06:18] [INFO]   |  |-- max_parallel_requests=16

[19:06:18] [INFO]   |  |-- timeout=300

[19:06:18] [INFO]   |  |-- temperature=0.30

[19:06:18] [INFO]   |  |-- top_p=0.95

[19:06:18] [INFO]   |  |-- max_tokens=16384

[19:06:18] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers

[19:06:18] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record

[19:06:21] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.32 rec/s, eta 6.3s

[19:06:21] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.53 rec/s, eta 1.9s

[19:06:21] [INFO]   |-- 🚀 llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.80 rec/s, eta 0.0s

[19:06:21] [INFO] 🔧 Custom column config for column '_validated_entities'

[19:06:21] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[19:06:21] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:21] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[19:06:21] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[19:06:21] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record

[19:06:21] [INFO]   |-- 🥱 custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1277.68 rec/s, eta 0.0s

[19:06:21] [INFO]   |-- 😐 custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1808.11 rec/s, eta 0.0s

[19:06:21] [INFO]   |-- 🤩 custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1800.18 rec/s, eta 0.0s

[19:06:21] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[19:06:21] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[19:06:21] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:21] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[19:06:21] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[19:06:21] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[19:06:21] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record

[19:06:21] [INFO]   |-- 🌦️ custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1561.99 rec/s, eta 0.0s

[19:06:21] [INFO]   |-- ⛅ custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1881.98 rec/s, eta 0.0s

[19:06:21] [INFO]   |-- ☀️ custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1831.59 rec/s, eta 0.0s

[19:06:21] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[19:06:21] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[19:06:21] [INFO]   |-- model alias: 'gpt-oss-120b'

[19:06:21] [INFO]   |-- model provider: 'nvidia'

[19:06:21] [INFO]   |-- inference parameters:

[19:06:21] [INFO]   |  |-- generation_type=chat-completion

[19:06:21] [INFO]   |  |-- max_parallel_requests=16

[19:06:21] [INFO]   |  |-- timeout=300

[19:06:21] [INFO]   |  |-- temperature=0.30

[19:06:22] [INFO]   |  |-- top_p=0.95

[19:06:22] [INFO]   |  |-- max_tokens=16384

[19:06:22] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers

[19:06:22] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record

[19:06:22] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.27 rec/s, eta 1.6s

[19:06:22] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.48 rec/s, eta 0.4s

[19:06:22] [INFO]   |-- 🚀 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 3.56 rec/s, eta 0.0s

[19:06:22] [INFO] 🔧 Custom column config for column '_merged_entities'

[19:06:22] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[19:06:22] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:22] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[19:06:22] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[19:06:22] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[19:06:22] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record

[19:06:22] [INFO]   |-- 🐴 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1521.11 rec/s, eta 0.0s

[19:06:22] [INFO]   |-- 🚗 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2145.16 rec/s, eta 0.0s

[19:06:22] [INFO]   |-- 🚀 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2021.85 rec/s, eta 0.0s

[19:06:22] [INFO] 🔧 Custom column config for column '_detected_entities'

[19:06:22] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[19:06:22] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[19:06:22] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[19:06:22] [INFO]   |-- side_effect_columns: ['tagged_text', '_entities_by_value']

[19:06:22] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[19:06:22] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record

[19:06:22] [INFO]   |-- 🐣 custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 2380.95 rec/s, eta 0.0s

[19:06:22] [INFO]   |-- 🐥 custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2943.16 rec/s, eta 0.0s

[19:06:22] [INFO]   |-- 🐔 custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2736.29 rec/s, eta 0.0s

[19:06:23] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[19:06:23] [INFO] 📊 Model usage summary:

[19:06:23] [INFO]   |-- model: nvdev/openai/gpt-oss-120b

[19:06:23] [INFO]   |-- tokens: input=12415, output=2759, total=15174, tps=2460

[19:06:23] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=58

[19:06:23] [INFO]   |--

[19:06:23] [INFO]   |-- model: nvidia/gliner-pii

[19:06:23] [INFO]   |-- tokens: input=24, output=207, total=231, tps=37

[19:06:23] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=29

[19:06:23] [INFO] 📐 Measuring dataset column statistics:

[19:06:23] [INFO]   |-- 📝 column: '_raw_detected_entities'

[19:06:23] [INFO]   |-- 🔧 column: '_seed_entities'

[19:06:23] [INFO]   |-- 🔧 column: '_validation_candidates'

[19:06:23] [INFO]   |-- 🔧 column: '_validated_entities'

[19:06:23] [INFO]   |-- 🔧 column: '_seed_entities_json'

[19:06:23] [INFO]   |-- 🗂️ column: '_augmented_entities'

[19:06:23] [INFO]   |-- 🔧 column: '_merged_entities'

[19:06:23] [INFO]   |-- 🔧 column: '_detected_entities'

[19:06:23] [INFO]   |-- 📋 Detection complete — 3 entities found across 3 records (0 failed) [7.0s]

[19:06:23] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, occupation=1, date=1

[19:06:23] [INFO] 🔄 Running Redact replacement

[19:06:23] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[19:06:23] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,<occupation>Dr.</occupation> <first_name>Carol...,"{'entities': [{'id': 'occupation_0_3', 'value'...",[REDACTED_OCCUPATION] [REDACTED_FIRST_NAME] [R...

## Scenario 5: Debug mode (fine-grained Anonymizer diagnostics)

In [7]:
configure_logging(LoggingConfig.debug())

result_debug = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_debug.dataframe

[19:06:23] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_wct5is0u/sample.csv (column: 'text')

[19:06:23] [INFO] 🔍 Running entity detection on 3 records

[19:06:23] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[19:06:23] [DEBUG] NDD workflow 'entity-detection' starting with 3 records

[19:06:23] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[19:06:30] [DEBUG] NDD workflow 'entity-detection' returned 3 records

[19:06:30] [INFO]   |-- 📋 Detection complete — 3 entities found across 3 records (0 failed) [7.0s]

[19:06:30] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, date=1

[19:06:30] [DEBUG] entities per record: min=1, max=1, mean=1.0

[19:06:30] [DEBUG]   record 0: 5 entities — first_name=1, last_name=1, company_name=1, city=1, state=1

[19:06:30] [DEBUG]   record 1: 4 entities — first_name=1, last_name=1, email=1, phone_number=1

[19:06:30] [DEBUG]   record 2: 3 entities — first_name=1, last_name=1, date=1

[19:06:30] [INFO] 🔄 Running Redact replacement

[19:06:30] [DEBUG] replacement strategy: Redact on 3 records

[19:06:30] [DEBUG]   record 0: 5 replacements — first_name=1, last_name=1, company_name=1, city=1, state=1

[19:06:30] [DEBUG]   record 1: 4 replacements — first_name=1, last_name=1, email=1, phone_number=1

[19:06:30] [DEBUG]   record 2: 3 replacements — first_name=1, last_name=1, date=1

[19:06:30] [DEBUG] replacement stats: 12 unique entities replaced (first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, date=1)

[19:06:30] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[19:06:30] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,Dr. <first_name>Carol</first_name> <last_name>...,"{'entities': [{'id': 'first_name_4_9', 'value'...",Dr. [REDACTED_FIRST_NAME] [REDACTED_LAST_NAME]...

## Cleanup

This file is temporary and should be removed before merging.