# Pipeline Logging Demo

This script demonstrates the user-facing logging added by #14. It requires a
running NDD/DataDesigner backend. Run cells individually in VS Code or PyCharm.

In [1]:
from anonymizer.logging import LoggingConfig, configure_logging  # noqa: F401

configure_logging()  # default: anonymizer INFO, DD suppressed
# configure_logging(LoggingConfig.verbose())  # anonymizer INFO + DD progress
# configure_logging(LoggingConfig.debug())    # anonymizer DEBUG + DD INFO

/Users/amanoel/Code/Anonymizer/checkouts/feat-pipeline-logging/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import tempfile
from pathlib import Path

import pandas as pd

tmp_dir = tempfile.mkdtemp(prefix="logging_demo_")
csv_path = Path(tmp_dir) / "sample.csv"

pd.DataFrame(
    {
        "text": [
            "Alice Johnson works at Acme Corp in Portland, Oregon.",
            "Contact Bob Smith at bob.smith@example.com or 555-0123.",
            "Dr. Carol Lee treated patient #12345 on 2024-03-15.",
        ]
    }
).to_csv(csv_path, index=False)

print(f"Sample data saved to {csv_path}")

Sample data saved to /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv

## Scenario 1: Full run with Redact replacement

In [3]:
from anonymizer.config.anonymizer_config import AnonymizerConfig, AnonymizerInput
from anonymizer.config.replace_strategies import Redact
from anonymizer.interface.anonymizer import Anonymizer

anonymizer = Anonymizer()
result = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result.dataframe

[15:46:59] [INFO] 🔧 Anonymizer initialized with 3 model configs

[15:46:59] [INFO]   |-- 🔎 detector:  gliner-pii-detector

[15:46:59] [INFO]   |-- ✅ validator: gpt-oss-120b

[15:46:59] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

[15:46:59] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv (column: 'text')

[15:46:59] [INFO] 🔍 Running entity detection on 3 records

[15:47:09] [INFO]   |-- 📋 Detection complete — 12 entities found across 3 records (0 failed) [10.3s]

[15:47:09] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, date=1

[15:47:09] [INFO] 🔄 Running Redact replacement

[15:47:09] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[15:47:09] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,Dr. <first_name>Carol</first_name> <last_name>...,"{'entities': [{'id': 'first_name_4_9', 'value'...",Dr. [REDACTED_FIRST_NAME] [REDACTED_LAST_NAME]...

## Scenario 2: Preview mode

In [4]:
preview = anonymizer.preview(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
    num_records=2,
)
preview.dataframe

[15:47:09] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv (column: 'text')

[15:47:09] [INFO]   |-- 👀 Preview mode: processing 2 of 3 records

[15:47:09] [INFO] 🔍 Running entity detection on 3 records

[15:47:15] [INFO]   |-- 📋 Detection complete — 9 entities found across 2 records (0 failed) [6.4s]

[15:47:15] [INFO]   |-- labels: first_name=2, last_name=2, company_name=1, city=1, state=1, email=1, phone_number=1

[15:47:15] [INFO] 🔄 Running Redact replacement

[15:47:15] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[15:47:15] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...

## Scenario 3: Detection only (no replacement)

In [5]:
from anonymizer.config.anonymizer_config import Rewrite

result_detect_only = anonymizer.run(
    config=AnonymizerConfig(rewrite=Rewrite()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_detect_only.dataframe

[15:47:15] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv (column: 'text')

[15:47:15] [INFO] 🔍 Running entity detection on 3 records

[15:47:34] [INFO]   |-- 📋 Detection complete — 13 entities found across 3 records (0 failed) [18.8s]

[15:47:34] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, occupation=1, date=1

[15:47:34] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'..."
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value..."
2,Dr. Carol Lee treated patient #12345 on 2024-0...,<occupation>Dr.</occupation> <first_name>Carol...,"{'entities': [{'id': 'occupation_0_3', 'value'..."

## Scenario 4: Verbose mode (surfaces DataDesigner progress)

In [6]:
configure_logging(LoggingConfig.verbose())

result_verbose = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_verbose.dataframe

[15:47:34] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv (column: 'text')

[15:47:34] [INFO] 🔍 Running entity detection on 3 records

[15:47:34] [INFO] 🎨 Creating Data Designer dataset

[15:47:34] [INFO] ✅ Validation passed

[15:47:34] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:47:34] [INFO] 🩺 Running health checks for models...

[15:47:34] [INFO]   |-- ⏭️  Skipping health check for model alias 'gliner-pii-detector' (skip_health_check=True)

[15:47:34] [INFO]   |-- 👀 Checking 'nvdev/openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:47:35] [INFO]   |-- ✅ Passed!

[15:47:35] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-09-2026_154735' instead.

[15:47:35] [INFO] ⏳ Processing batch 1 of 1

[15:47:35] [INFO] 🌱 Sampling 3 records from seed dataset

[15:47:35] [INFO]   |-- seed dataset size: 3 records

[15:47:35] [INFO]   |-- sampling strategy: ordered

[15:47:35] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:47:35] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:47:35] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:47:35] [INFO]   |-- model provider: 'nvidia'

[15:47:35] [INFO]   |-- inference parameters:

[15:47:35] [INFO]   |  |-- generation_type=chat-completion

[15:47:35] [INFO]   |  |-- max_parallel_requests=16

[15:47:35] [INFO]   |  |-- timeout=120

[15:47:35] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:47:35] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers

[15:47:35] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record

[15:47:35] [INFO]   |-- 🐴 llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.75 rec/s, eta 1.1s

[15:47:35] [INFO]   |-- 🚗 llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 3.48 rec/s, eta 0.3s

[15:47:38] [INFO]   |-- 🚀 llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1.05 rec/s, eta 0.0s

[15:47:38] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:47:38] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:47:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:38] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:47:38] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:47:38] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:47:38] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record

[15:47:38] [INFO]   |-- 😺 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1085.33 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 😸 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1541.28 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 🦁 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1333.06 rec/s, eta 0.0s

[15:47:38] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:47:38] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:47:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:38] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:47:38] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:47:38] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:47:38] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record

[15:47:38] [INFO]   |-- 🐴 custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1708.79 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 🚗 custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2107.76 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 🚀 custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1881.86 rec/s, eta 0.0s

[15:47:38] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:47:38] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:47:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:38] [INFO]   |-- required_columns: ['_validation_candidates']

[15:47:38] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:47:38] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record

[15:47:38] [INFO]   |-- 😺 custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 580.93 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 😸 custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 869.12 rec/s, eta 0.0s

[15:47:38] [INFO]   |-- 🦁 custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 929.03 rec/s, eta 0.0s

[15:47:38] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:47:38] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[15:47:38] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:47:38] [INFO]   |-- model provider: 'nvidia'

[15:47:38] [INFO]   |-- inference parameters:

[15:47:38] [INFO]   |  |-- generation_type=chat-completion

[15:47:38] [INFO]   |  |-- max_parallel_requests=16

[15:47:38] [INFO]   |  |-- timeout=300

[15:47:38] [INFO]   |  |-- temperature=0.30

[15:47:38] [INFO]   |  |-- top_p=0.95

[15:47:38] [INFO]   |  |-- max_tokens=16384

[15:47:38] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers

[15:47:38] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record

[15:47:41] [INFO]   |-- 🌘 llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.37 rec/s, eta 5.5s

[15:47:41] [INFO]   |-- 🌗 llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.56 rec/s, eta 1.8s

[15:47:42] [INFO]   |-- 🌕 llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.75 rec/s, eta 0.0s

[15:47:42] [INFO] 🔧 Custom column config for column '_validated_entities'

[15:47:42] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[15:47:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:42] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[15:47:42] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[15:47:42] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record

[15:47:42] [INFO]   |-- 😺 custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 921.52 rec/s, eta 0.0s

[15:47:42] [INFO]   |-- 😸 custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1276.43 rec/s, eta 0.0s

[15:47:42] [INFO]   |-- 🦁 custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1364.85 rec/s, eta 0.0s

[15:47:42] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[15:47:42] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[15:47:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:42] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[15:47:42] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[15:47:42] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[15:47:42] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record

[15:47:42] [INFO]   |-- 🥱 custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 967.90 rec/s, eta 0.0s

[15:47:42] [INFO]   |-- 😐 custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1132.88 rec/s, eta 0.0s

[15:47:42] [INFO]   |-- 🤩 custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1241.14 rec/s, eta 0.0s

[15:47:42] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[15:47:42] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[15:47:42] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:47:42] [INFO]   |-- model provider: 'nvidia'

[15:47:42] [INFO]   |-- inference parameters:

[15:47:42] [INFO]   |  |-- generation_type=chat-completion

[15:47:42] [INFO]   |  |-- max_parallel_requests=16

[15:47:42] [INFO]   |  |-- timeout=300

[15:47:42] [INFO]   |  |-- temperature=0.30

[15:47:42] [INFO]   |  |-- top_p=0.95

[15:47:42] [INFO]   |  |-- max_tokens=16384

[15:47:42] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers

[15:47:42] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record

[15:47:43] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.39 rec/s, eta 1.4s

[15:47:43] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.69 rec/s, eta 0.4s

[15:47:43] [INFO]   |-- 🚀 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 3.88 rec/s, eta 0.0s

[15:47:43] [INFO] 🔧 Custom column config for column '_merged_entities'

[15:47:43] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[15:47:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:43] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[15:47:43] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:47:43] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[15:47:43] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record

[15:47:43] [INFO]   |-- 😺 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1375.83 rec/s, eta 0.0s

[15:47:43] [INFO]   |-- 😸 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1890.73 rec/s, eta 0.0s

[15:47:43] [INFO]   |-- 🦁 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1735.57 rec/s, eta 0.0s

[15:47:43] [INFO] 🔧 Custom column config for column '_detected_entities'

[15:47:43] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[15:47:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:43] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[15:47:43] [INFO]   |-- side_effect_columns: ['tagged_text', '_entities_by_value']

[15:47:43] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[15:47:43] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record

[15:47:43] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1596.81 rec/s, eta 0.0s

[15:47:43] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2072.18 rec/s, eta 0.0s

[15:47:43] [INFO]   |-- 🚀 custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2161.77 rec/s, eta 0.0s

[15:47:43] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[15:47:43] [INFO] 📊 Model usage summary:

[15:47:43] [INFO]   |-- model: nvdev/openai/gpt-oss-120b

[15:47:43] [INFO]   |-- tokens: input=12359, output=2706, total=15065, tps=1761

[15:47:43] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=42

[15:47:43] [INFO]   |--

[15:47:43] [INFO]   |-- model: nvidia/gliner-pii

[15:47:43] [INFO]   |-- tokens: input=24, output=207, total=231, tps=27

[15:47:43] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=21

[15:47:43] [INFO] 📐 Measuring dataset column statistics:

[15:47:43] [INFO]   |-- 📝 column: '_raw_detected_entities'

[15:47:43] [INFO]   |-- 🔧 column: '_seed_entities'

[15:47:43] [INFO]   |-- 🔧 column: '_validation_candidates'

[15:47:43] [INFO]   |-- 🔧 column: '_validated_entities'

[15:47:43] [INFO]   |-- 🔧 column: '_seed_entities_json'

[15:47:43] [INFO]   |-- 🗂️ column: '_augmented_entities'

[15:47:43] [INFO]   |-- 🔧 column: '_merged_entities'

[15:47:43] [INFO]   |-- 🔧 column: '_detected_entities'

[15:47:43] [INFO]   |-- 📋 Detection complete — 12 entities found across 3 records (0 failed) [9.3s]

[15:47:43] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, date=1

[15:47:43] [INFO] 🔄 Running Redact replacement

[15:47:43] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[15:47:43] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,Dr. <first_name>Carol</first_name> <last_name>...,"{'entities': [{'id': 'first_name_4_9', 'value'...",Dr. [REDACTED_FIRST_NAME] [REDACTED_LAST_NAME]...

## Scenario 5: Debug mode (fine-grained Anonymizer diagnostics)

In [7]:
configure_logging(LoggingConfig.debug())

result_debug = anonymizer.run(
    config=AnonymizerConfig(replace=Redact()),
    data=AnonymizerInput(source=str(csv_path)),
)
result_debug.dataframe

[15:47:43] [INFO] 📂 Loaded 3 records from /var/folders/66/lhpfpgl94z33ykf1njyb9y080000gp/T/logging_demo_h5_etsex/sample.csv (column: 'text')

[15:47:43] [DEBUG] input text lengths: min=51, max=55, mean=53 chars (3 records)

[15:47:43] [DEBUG] detection config: threshold=0.30, labels=(default)

[15:47:43] [INFO] 🔍 Running entity detection on 3 records

[15:47:43] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[15:47:44] [DEBUG] NDD workflow 'entity-detection' starting with 3 records

[15:47:44] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[15:47:44] [INFO] 🎨 Creating Data Designer dataset

[15:47:44] [INFO] ✅ Validation passed

[15:47:44] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:47:44] [INFO] 🩺 Running health checks for models...

[15:47:44] [INFO]   |-- ⏭️  Skipping health check for model alias 'gliner-pii-detector' (skip_health_check=True)

[15:47:44] [INFO]   |-- 👀 Checking 'nvdev/openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:47:44] [INFO]   |-- ✅ Passed!

[15:47:44] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-09-2026_154744' instead.

[15:47:44] [INFO] ⏳ Processing batch 1 of 1

[15:47:44] [INFO] 🌱 Sampling 3 records from seed dataset

[15:47:44] [INFO]   |-- seed dataset size: 3 records

[15:47:44] [INFO]   |-- sampling strategy: ordered

[15:47:44] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:47:44] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:47:44] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:47:44] [INFO]   |-- model provider: 'nvidia'

[15:47:44] [INFO]   |-- inference parameters:

[15:47:44] [INFO]   |  |-- generation_type=chat-completion

[15:47:44] [INFO]   |  |-- max_parallel_requests=16

[15:47:44] [INFO]   |  |-- timeout=120

[15:47:44] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:47:44] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers

[15:47:44] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record

[15:47:45] [INFO]   |-- 🥱 llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.74 rec/s, eta 1.2s

[15:47:45] [INFO]   |-- 😐 llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 3.44 rec/s, eta 0.3s

[15:47:47] [INFO]   |-- 🤩 llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1.21 rec/s, eta 0.0s

[15:47:47] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:47:47] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:47:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:47] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:47:47] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:47:47] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:47:47] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record

[15:47:47] [INFO]   |-- 🐣 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1339.81 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- 🐥 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1652.04 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- 🐔 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1704.14 rec/s, eta 0.0s

[15:47:47] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:47:47] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:47:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:47] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:47:47] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:47:47] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:47:47] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record

[15:47:47] [INFO]   |-- 🌦️ custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1303.22 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- ⛅ custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1673.12 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- ☀️ custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1277.50 rec/s, eta 0.0s

[15:47:47] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:47:47] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:47:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:47] [INFO]   |-- required_columns: ['_validation_candidates']

[15:47:47] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:47:47] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record

[15:47:47] [INFO]   |-- 🌦️ custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1622.39 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- ⛅ custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2186.29 rec/s, eta 0.0s

[15:47:47] [INFO]   |-- ☀️ custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2026.23 rec/s, eta 0.0s

[15:47:47] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:47:47] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[15:47:47] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:47:47] [INFO]   |-- model provider: 'nvidia'

[15:47:47] [INFO]   |-- inference parameters:

[15:47:47] [INFO]   |  |-- generation_type=chat-completion

[15:47:47] [INFO]   |  |-- max_parallel_requests=16

[15:47:47] [INFO]   |  |-- timeout=300

[15:47:47] [INFO]   |  |-- temperature=0.30

[15:47:47] [INFO]   |  |-- top_p=0.95

[15:47:47] [INFO]   |  |-- max_tokens=16384

[15:47:47] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers

[15:47:47] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record

[15:47:50] [INFO]   |-- 🐣 llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.35 rec/s, eta 5.8s

[15:47:51] [INFO]   |-- 🐥 llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.48 rec/s, eta 2.1s

[15:47:51] [INFO]   |-- 🐔 llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.71 rec/s, eta 0.0s

[15:47:51] [INFO] 🔧 Custom column config for column '_validated_entities'

[15:47:51] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[15:47:51] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:51] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[15:47:51] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[15:47:51] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record

[15:47:51] [INFO]   |-- 😺 custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1281.57 rec/s, eta 0.0s

[15:47:51] [INFO]   |-- 😸 custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1747.49 rec/s, eta 0.0s

[15:47:51] [INFO]   |-- 🦁 custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1809.50 rec/s, eta 0.0s

[15:47:51] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[15:47:51] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[15:47:51] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:51] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[15:47:51] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[15:47:51] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[15:47:51] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record

[15:47:51] [INFO]   |-- 🌦️ custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1089.27 rec/s, eta 0.0s

[15:47:51] [INFO]   |-- ⛅ custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1261.03 rec/s, eta 0.0s

[15:47:51] [INFO]   |-- ☀️ custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1175.36 rec/s, eta 0.0s

[15:47:51] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[15:47:51] [INFO]   |-- model: 'nvdev/openai/gpt-oss-120b'

[15:47:51] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:47:51] [INFO]   |-- model provider: 'nvidia'

[15:47:51] [INFO]   |-- inference parameters:

[15:47:51] [INFO]   |  |-- generation_type=chat-completion

[15:47:51] [INFO]   |  |-- max_parallel_requests=16

[15:47:51] [INFO]   |  |-- timeout=300

[15:47:51] [INFO]   |  |-- temperature=0.30

[15:47:51] [INFO]   |  |-- top_p=0.95

[15:47:51] [INFO]   |  |-- max_tokens=16384

[15:47:51] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers

[15:47:51] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record

[15:47:52] [INFO]   |-- 🐣 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.39 rec/s, eta 1.4s

[15:47:52] [INFO]   |-- 🐥 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.75 rec/s, eta 0.4s

[15:47:52] [INFO]   |-- 🐔 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 4.10 rec/s, eta 0.0s

[15:47:52] [INFO] 🔧 Custom column config for column '_merged_entities'

[15:47:52] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[15:47:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:52] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[15:47:52] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:47:52] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[15:47:52] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record

[15:47:52] [INFO]   |-- 🥱 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1245.91 rec/s, eta 0.0s

[15:47:52] [INFO]   |-- 😐 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1626.68 rec/s, eta 0.0s

[15:47:52] [INFO]   |-- 🤩 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1390.50 rec/s, eta 0.0s

[15:47:52] [INFO] 🔧 Custom column config for column '_detected_entities'

[15:47:52] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[15:47:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:52] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[15:47:52] [INFO]   |-- side_effect_columns: ['tagged_text', '_entities_by_value']

[15:47:52] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[15:47:52] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record

[15:47:52] [INFO]   |-- 🥱 custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1034.08 rec/s, eta 0.0s

[15:47:52] [INFO]   |-- 😐 custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1239.38 rec/s, eta 0.0s

[15:47:52] [INFO]   |-- 🤩 custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1304.32 rec/s, eta 0.0s

[15:47:53] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[15:47:53] [INFO] 📊 Model usage summary:

[15:47:53] [INFO]   |-- model: nvdev/openai/gpt-oss-120b

[15:47:53] [INFO]   |-- tokens: input=12415, output=2945, total=15360, tps=1823

[15:47:53] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=42

[15:47:53] [INFO]   |--

[15:47:53] [INFO]   |-- model: nvidia/gliner-pii

[15:47:53] [INFO]   |-- tokens: input=24, output=207, total=231, tps=27

[15:47:53] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=21

[15:47:53] [INFO] 📐 Measuring dataset column statistics:

[15:47:53] [INFO]   |-- 📝 column: '_raw_detected_entities'

[15:47:53] [INFO]   |-- 🔧 column: '_seed_entities'

[15:47:53] [INFO]   |-- 🔧 column: '_validation_candidates'

[15:47:53] [INFO]   |-- 🔧 column: '_validated_entities'

[15:47:53] [INFO]   |-- 🔧 column: '_seed_entities_json'

[15:47:53] [INFO]   |-- 🗂️ column: '_augmented_entities'

[15:47:53] [INFO]   |-- 🔧 column: '_merged_entities'

[15:47:53] [INFO]   |-- 🔧 column: '_detected_entities'

[15:47:53] [DEBUG] NDD workflow 'entity-detection' returned 3 records

[15:47:53] [INFO]   |-- 📋 Detection complete — 13 entities found across 3 records (0 failed) [9.2s]

[15:47:53] [INFO]   |-- labels: first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, occupation=1, date=1

[15:47:53] [INFO] 🔄 Running Redact replacement

[15:47:53] [DEBUG] replacement strategy: Redact on 3 records

[15:47:53] [DEBUG]   record 0: 5 replacements — first_name=1, last_name=1, company_name=1, city=1, state=1

[15:47:53] [DEBUG]   record 1: 4 replacements — first_name=1, last_name=1, email=1, phone_number=1

[15:47:53] [DEBUG]   record 2: 4 replacements — occupation=1, first_name=1, last_name=1, date=1

[15:47:53] [DEBUG] replacement stats: 13 unique entities replaced (first_name=3, last_name=3, company_name=1, city=1, state=1, email=1, phone_number=1, occupation=1, date=1)

[15:47:53] [INFO]   |-- 📋 Replacement complete (0 failed) [0.0s]

[15:47:53] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

,text,text_with_spans,final_entities,text_replaced
0,"Alice Johnson works at Acme Corp in Portland, ...",<first_name>Alice</first_name> <last_name>John...,"{'entities': [{'id': 'first_name_0_5', 'value'...",[REDACTED_FIRST_NAME] [REDACTED_LAST_NAME] wor...
1,Contact Bob Smith at bob.smith@example.com or ...,Contact <first_name>Bob</first_name> <last_nam...,"{'entities': [{'id': 'first_name_8_11', 'value...",Contact [REDACTED_FIRST_NAME] [REDACTED_LAST_N...
2,Dr. Carol Lee treated patient #12345 on 2024-0...,<occupation>Dr.</occupation> <first_name>Carol...,"{'entities': [{'id': 'occupation_0_3', 'value'...",[REDACTED_OCCUPATION] [REDACTED_FIRST_NAME] [R...

## Cleanup

This file is temporary and should be removed before merging.