<!--
SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
-->
# 🕵️ Your First Anonymization

Detect sensitive entities and replace them with LLM-generated substitutes --
the simplest end-to-end example of Anonymizer.

#### 📚 What you'll learn

- Load a CSV dataset and configure Anonymizer in a few lines
- Preview anonymized results on a small sample before committing to a full run
- Inspect entity detection and replacement with `display_record()`
- Process the full dataset with `run()`

> **Tip:** First time running notebooks? Start with
> [setup instructions](https://nvidia-nemo.github.io/Anonymizer/latest/tutorials/).

## ⚙️ Setup

- Install the notebook extra, then provide credentials for the configured external LLM providers.
- `create_anonymizer()` starts pinned GLiNER2 locally and selects CUDA, MPS, or CPU automatically.
- The default external LLM models currently use [NVIDIA Build](https://build.nvidia.com); its terms and privacy practices apply.

> **Data boundary:** GLiNER2 detection runs locally in this notebook environment. LLM-assisted validation,
> augmentation, replacement, rewriting, repair, and evaluation use configured external hosts and may send
> them original or tagged input text. Do not treat this configuration as an all-local privacy boundary.
- `configure_logging(LoggingConfig.default())` keeps logs at INFO. Switch to `LoggingConfig.debug()` when troubleshooting.

In [1]:
import getpass
import os
import subprocess
import sys

package_spec = os.getenv("ANONYMIZER_NOTEBOOK_PACKAGE", "nemo-anonymizer[notebooks]")
subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", package_spec])

In [2]:
from anonymizer.notebooks import required_api_key_environment_variables

for variable in required_api_key_environment_variables():
    key = getpass.getpass(f"Enter {variable}: ").strip()
    if not key:
        raise RuntimeError(f"{variable} is required by the configured external model providers.")
    os.environ[variable] = key

In [3]:
from anonymizer import AnonymizerConfig, AnonymizerInput, LoggingConfig, Substitute, configure_logging
from anonymizer.notebooks import create_anonymizer, stop_local_runtime

configure_logging(LoggingConfig.default())

In [4]:
anonymizer = create_anonymizer()

[13:12:30] [INFO] 🔧 Anonymizer initialized with 5 model configs

[13:12:30] [INFO]   |-- 🔎 detector:  local-gliner2-pii

[13:12:30] [INFO]   |-- ✅ validator: gpt-oss-120b

[13:12:30] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

GLiNER2 ready: model=fastino/gliner2-privacy-filter-PII-multi revision=59894c087cb2923b01f337d4ee72f6ff84d5bdd6 device=mps endpoint=http://127.0.0.1:61983/v1

## 📦 Load data and configure

- `AnonymizerInput` points to your CSV and names the text column. `data_summary`
  gives the LLM context about the kind of text it will process.
- Records up to 2,000 tokens each work with the default model configs.
- `AnonymizerConfig` with `Substitute()` tells Anonymizer to replace detected
  entities with LLM-generated synthetic values for names, cities, dates, etc.

In [5]:
input_data = AnonymizerInput(
    source="https://raw.githubusercontent.com/NVIDIA-NeMo/Anonymizer/refs/heads/main/docs/data/NVIDIA_synthetic_biographies.csv",
    text_column="biography",
    data_summary="Biographical profiles of individuals",
)

config = AnonymizerConfig(replace=Substitute())

## 👁️ Preview

- `preview()` runs on a small sample so you can iterate quickly.
- Always preview before processing the full dataset -- it's the fastest way
  to catch prompt or config issues early.

In [6]:
preview = anonymizer.preview(config=config, data=input_data, num_records=3)

[13:12:31] [INFO] 👀 Preview mode: 📂 Loaded 3 records from https://raw.githubusercontent.com/NVIDIA-NeMo/Anonymizer/refs/heads/main/docs/data/NVIDIA_synthetic_biographies.csv (column: 'biography')

[13:12:31] [INFO] 🔍 Running entity detection on 3 records

[13:12:31] [INFO] detection labels in scope: (default: 65 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)

[13:12:46] [INFO]   |-- 📋 Detection complete — 84 entities found across 3 records (0 failed) [15.8s]

[13:12:46] [INFO]   |-- labels: first_name=23, occupation=6, organization_name=6, age=5, field_of_study=5, company_name=5, city=4, degree=4, university=4, last_name=3, state=3, language=3, political_view=2, place_name=2, race_ethnicity=2, street_address=2, religious_belief=2, nationality=1, date_of_birth=1, landmark=1

[13:12:46] [INFO] 🔄 Running Substitute replacement

[13:12:55] [INFO]   |-- 📋 Replacement complete (0 failed) [8.4s]

[13:12:55] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

## 🔍 Inspect

- `display_record()` shows the original text with highlighted entities,
  the replacement map, and the anonymized output -- all in one view.
- The result dataframe has original and substituted text side-by-side.

In [7]:
preview.display_record(0)

In [8]:
preview.display_record(1)

In [9]:
preview.dataframe

,biography,biography_with_spans,final_entities,biography_replaced
0,"Bobby Watford, a 40‑year‑old Mexican veterinar...",<first_name>Bobby</first_name> <last_name>Watf...,"{'entities': [{'id': 'first_name_0_5', 'value'...","Ethan Henderson, a 45‑year‑old Canadian zoolog..."
1,Idilio Bell is a 37‑year‑old astronomer living...,<first_name>Idilio</first_name> <last_name>Bel...,"{'entities': [{'id': 'first_name_0_6', 'value'...",Dario Rossi is a 36‑year‑old data scientist li...
2,"Jodi Allison, 36, lives at 204 Bluegrass in Cl...",<first_name>Jodi</first_name> <last_name>Allis...,"{'entities': [{'id': 'first_name_0_4', 'value'...","Tara Keller, 38, lives at 317 Riverbend in Wil..."

## 🚀 Full run

- `run()` processes the entire dataset with the same config you previewed.
- Access the output via `result.dataframe`.

In [10]:
result = anonymizer.run(config=config, data=input_data)
print(result)

[13:12:56] [INFO] 📂 Loaded 25 records from https://raw.githubusercontent.com/NVIDIA-NeMo/Anonymizer/refs/heads/main/docs/data/NVIDIA_synthetic_biographies.csv (column: 'biography')

[13:12:56] [INFO] 🔍 Running entity detection on 25 records

[13:12:56] [INFO] detection labels in scope: (default: 65 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)

[13:13:45] [INFO]   |-- 📋 Detection complete — 701 entities found across 25 records (0 failed) [48.4s]

[13:13:45] [INFO]   |-- labels: first_name=153, field_of_study=50, occupation=48, organization_name=45, company_name=44, city=40, university=35, degree=27, political_view=27, last_name=26, age=26, state=25, religious_belief=24, street_address=23, language=20, place_name=19, race_ethnicity=18, county=10, nationality=9, date_of_birth=9, education_level=6, employment_status=6, date=5, landmark=2, duration=1, country=1, sexuality=1, postcode=1

[13:13:45] [INFO] 🔄 Running Substitute replacement

[13:14:08] [INFO]   |-- 📋 Replacement complete (0 failed) [23.6s]

[13:14:08] [INFO] 🎉 Pipeline complete — 25 records processed, 0 total failures

AnonymizerResult(rows=25, columns=4, trace_columns=23, failed_records=0)

In [11]:
result.dataframe.head()

,biography,biography_with_spans,final_entities,biography_replaced
0,"Bobby Watford, a 40‑year‑old Mexican veterinar...",<first_name>Bobby</first_name> <last_name>Watf...,"{'entities': array([{'id': 'first_name_0_5', '...","Darius Hawthorne, a 45‑year‑old Canadian envir..."
1,Idilio Bell is a 37‑year‑old astronomer living...,<first_name>Idilio</first_name> <last_name>Bel...,"{'entities': array([{'id': 'first_name_0_6', '...",Santiago Hawthorne is a 34‑year‑old geophysici...
2,"Jodi Allison, 36, lives at 204 Bluegrass in Cl...",<first_name>Jodi</first_name> <last_name>Allis...,"{'entities': array([{'id': 'first_name_0_4', '...","Leah Kline, 42, lives at 317 Maple in Greenvil..."
3,James Mills is a 69‑year‑old paramedic who liv...,<first_name>James</first_name> <last_name>Mill...,"{'entities': array([{'id': 'first_name_0_5', '...",Michael Harper is a 74‑year‑old firefighter wh...
4,Nancy Burton is a 21‑year‑old cashier who live...,<first_name>Nancy</first_name> <last_name>Burt...,"{'entities': array([{'id': 'first_name_0_5', '...",Megan Hawkins is a 27‑year‑old stock clerk who...

## 📊 (Optional) Evaluate replacement quality

- `evaluate()` is a separate, opt-in step that scores the output with LLM-as-judge metrics.
- For Substitute, all four metrics run: **Detection Validity**, **Type Fidelity**, **Relational Consistency**, **Attribute Fidelity**.
- Skip it for routine runs; call it when you want LLM-side confidence on the output. Costs LLM calls per record, so try it on `preview` first.

In [12]:
evaluated = anonymizer.evaluate(preview)
evaluated.display_record(0)

[13:14:09] [INFO] 🧪 Running Substitute evaluation on 3 records

[13:14:09] [INFO]   |-- ⚖️ Running replace judges

[13:14:22] [INFO]   |-- 📋 Replace judges complete [13.4s]

[13:14:22] [INFO] 🎉 Evaluation complete — 3 records processed [13.4s]

## ⏭️ Next steps

- **[🔍 Inspecting Detected Entities](../02_inspecting_detected_entities/)** --
  dig into what the detection pipeline found and debug quality.
- **[🎯 Choosing a Replacement Strategy](../03_choosing_a_replacement_strategy/)** --
  compare Redact, Annotate, Hash, and Substitute side-by-side.
- **[✏️ Rewriting Biographies](../04_rewriting_biographies/)** --
  generate privacy-safe paraphrases instead of token-level replacements.

In [13]:
stop_local_runtime()