# Your First Anonymization

Detect sensitive entities and replace them with LLM-generated substitutes.
This is the simplest end-to-end example of Anonymizer.

## Setup

In [1]:
from anonymizer import Anonymizer, AnonymizerConfig, AnonymizerInput, Substitute

In [2]:
anonymizer = Anonymizer()

[17:08:36] [INFO] 🔧 Anonymizer initialized with 3 model configs
[17:08:36] [INFO]   |-- 🔎 detector:  gliner-pii-detector
[17:08:36] [INFO]   |-- ✅ validator: gpt-oss-120b
[17:08:36] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

## Load data and configure

In [ ]:
input_data = AnonymizerInput(
    source="../data/NVIDIA_synthetic_biographies.csv",
    text_column="biography",
    data_summary="Biographical profiles of individuals",
)

config = AnonymizerConfig(replace=Substitute())

## Preview

Run on a small sample first to check the results.

In [4]:
preview = anonymizer.preview(config=config, data=input_data, num_records=3)

[17:08:36] [INFO] 📂 Loaded 25 records from ../data/NVIDIA_synthetic_biographies.csv (column: 'biography')
[17:08:36] [INFO] detection labels in scope: (default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)
[17:08:36] [INFO]   |-- 👀 Preview mode: processing 3 of 25 records
[17:08:36] [INFO] 🔍 Running entity detection on 3 records
[17:09:21] [INFO]   |-- 📋 Detection complete — 68 entities found across 3 records (0 failed) [44.4s]
[17:09:21] [INFO]   |-- labels: first_name=21, state=8, city=6, age=5, occupation=5, education_level=4, last_name=3, race_ethnicity=3, language=3, company_name=3, political_view=2, street_address=2, date_of_birth=1, employment_status=1, religious_belief=1
[17:09:21] [INFO] 🔄 Running Substitute replacement
[17:09:41] [INFO]   |-- 📋 Replacement complete (0 failed) [19.7s]
[17:09:41] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

## Inspect

`display_record()` shows the original text with highlighted entities,
the replacement map, and the anonymized output.

In [11]:
preview.display_record(2)

In [6]:
preview.display_record(1)

The result dataframe has the original text and the substituted version.

In [7]:
preview.dataframe

,biography,biography_with_spans,final_entities,biography_replaced
0,"Bobby Watford, a 40‑year‑old Mexican veterinar...",<first_name>Bobby</first_name> <last_name>Watf...,"{'entities': [{'end_position': 5, 'id': 'first...","Joon Kim, a 47‑year‑old Korean zoologist livin..."
1,Idilio Bell is a 37‑year‑old astronomer living...,<first_name>Idilio</first_name> <last_name>Bel...,"{'entities': [{'end_position': 6, 'id': 'first...",Sanjay Kumar is a 35‑year‑old planetary scient...
2,"Jodi Allison, 36, lives at 204 Bluegrass in Cl...",<first_name>Jodi</first_name> <last_name>Allis...,"{'entities': [{'end_position': 4, 'id': 'first...","Leah Harper, 38, lives at 317 Maplewood in Gre..."

## Full run

Process the entire dataset.

In [8]:
result = anonymizer.run(config=config, data=input_data)
print(result)

[17:09:41] [INFO] 📂 Loaded 25 records from ../data/NVIDIA_synthetic_biographies.csv (column: 'biography')
[17:09:41] [INFO] detection labels in scope: (default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)
[17:09:41] [INFO] 🔍 Running entity detection on 25 records
[17:15:04] [INFO]   |-- 📋 Detection complete — 627 entities found across 25 records (0 failed) [323.2s]
[17:15:04] [INFO]   |-- labels: first_name=152, company_name=76, city=50, occupation=44, education_level=39, state=35, race_ethnicity=31, last_name=27, age=26, political_view=26, religious_belief=25, street_address=23, language=22, county=12, employment_status=10, date_of_birth=9, date=5, university_name=4, institution_name=3, region=2, school_name=1, geographic_location=1, country=1, organization_name=1, gender=1, postcode=1
[17:15:04] [INFO] 🔄 Running Substitute replacement
/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/replace/llm_replace_workflow.py:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([output_df, passthrough_rows], axis=0)
[17:17:34] [INFO]   |-- 📋 Replacement complete (0 failed) [150.1s]
[17:17:34] [INFO] 🎉 Pipeline complete — 25 records processed, 0 total failures

AnonymizerResult(rows=25, columns=4, trace_columns=21, failed_records=0)

In [9]:
result.dataframe.head()

,biography,biography_with_spans,final_entities,biography_replaced
0,"Bobby Watford, a 40‑year‑old Mexican veterinar...",<first_name>Bobby</first_name> <last_name>Watf...,"{'entities': array([{'end_position': 5, 'id': ...","Ethan Kline, a 45‑year‑old Filipino zoologist ..."
1,Idilio Bell is a 37‑year‑old astronomer living...,<first_name>Idilio</first_name> <last_name>Bel...,"{'entities': array([{'end_position': 6, 'id': ...",Santiago Hawthorne is a 35‑year‑old geophysici...
2,"Jodi Allison, 36, lives at 204 Bluegrass in Cl...",<first_name>Jodi</first_name> <last_name>Allis...,"{'entities': array([{'end_position': 4, 'id': ...","Sofia Kumar, 42, lives at 317 Cedar Lane in Me..."
3,James Mills is a 69‑year‑old paramedic who liv...,<first_name>James</first_name> <last_name>Mill...,"{'entities': array([{'end_position': 5, 'id': ...",Patrick O'Connor is a 72‑year‑old firefighter ...
4,Nancy Burton is a 21‑year‑old cashier who live...,<first_name>Nancy</first_name> <last_name>Burt...,"{'entities': array([{'end_position': 5, 'id': ...",Leah Hawthorne is a 34‑year‑old warehouse asso...