# Rewriting Biographies

Instead of replacing entities with tokens, rewrite mode generates a
privacy-safe paraphrase of the entire text. The pipeline:

1. Detects entities (same as replace mode)
2. Classifies the domain and assigns sensitivity dispositions
3. Generates a rewritten version that obscures sensitive entities
4. Evaluates quality (utility) and privacy (leakage) with an automated repair loop
5. Runs a final LLM judge for informational scores

The result includes **utility_score**, **leakage_mass**, and a
**needs_human_review** flag so you can triage records that need attention.

## Setup

In [1]:
from anonymizer import Anonymizer, AnonymizerConfig, AnonymizerInput, LoggingConfig, Rewrite, configure_logging
from anonymizer.config.rewrite import EvaluationCriteria, PrivacyGoal, RiskTolerance

configure_logging(LoggingConfig.debug())

In [2]:
anonymizer = Anonymizer()

[15:22:39] [INFO] 🔧 Anonymizer initialized with 3 model configs

[15:22:39] [INFO]   |-- 🔎 detector:  gliner-pii-detector

[15:22:39] [INFO]   |-- ✅ validator: gpt-oss-120b

[15:22:39] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

[15:22:39] [DEBUG] NDD adapter: artifact_path=.anonymizer-artifacts

## Input data

In [3]:
input_data = AnonymizerInput(
    source="../data/NVIDIA_synthetic_biographies.csv",
    text_column="biography",
    data_summary="Biographical profiles",
)

## Configure

Spell out what to protect and what to preserve. This gives the rewriter
clear guidance for your domain.

In [4]:
config = AnonymizerConfig(
    rewrite=Rewrite(
        privacy_goal=PrivacyGoal(
            protect="All direct identifiers and quasi-identifier combinations (names, locations, employers, dates)",
            preserve="Career trajectory, educational background, and professional accomplishments",
        ),
        evaluation=EvaluationCriteria(
            risk_tolerance=RiskTolerance.strict,
            max_repair_iterations=3,
        ),
    ),
)

## Preview

In [5]:
preview = anonymizer.preview(
    config=config,
    data=input_data,
    num_records=3,
)

preview.display_record(0)

[15:22:39] [INFO] 📂 Loaded 25 records from ../data/NVIDIA_synthetic_biographies.csv (column: 'biography')

[15:22:39] [DEBUG] input text lengths: min=934, max=1331, mean=1137 chars (25 records)

[15:22:39] [DEBUG] detection config: threshold=0.30, labels=(default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)

[15:22:39] [INFO]   |-- 👀 Preview mode: processing 3 of 25 records

[15:22:39] [INFO] 🔍 Running entity detection on 3 records

[15:22:39] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[15:22:39] [DEBUG] NDD workflow 'entity-detection' starting with 25 records

[15:22:39] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[15:22:39] [INFO] 🧐 Preview generation in progress

[15:22:47] [INFO] ✅ Validation passed

[15:22:47] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:22:47] [INFO] 🩺 Running health checks for models...

[15:22:47] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...

[15:22:49] [INFO]   |-- ✅ Passed!

[15:22:49] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:22:49] [INFO]   |-- ✅ Passed!

[15:22:49] [INFO] 🌱 Sampling 3 records from seed dataset

[15:22:49] [INFO]   |-- seed dataset size: 25 records

[15:22:49] [INFO]   |-- sampling strategy: ordered

[15:22:49] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:22:49] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:22:49] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:22:49] [INFO]   |-- model provider: 'nvidia'

[15:22:49] [INFO]   |-- inference parameters:

[15:22:49] [INFO]   |  |-- generation_type=chat-completion

[15:22:49] [INFO]   |  |-- max_parallel_requests=4

[15:22:49] [INFO]   |  |-- timeout=120

[15:22:49] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:22:49] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 4 concurrent workers

[15:22:49] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record

[15:22:50] [INFO]   |-- 🌦️ llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 2.60 rec/s, eta 0.8s

[15:22:50] [INFO]   |-- ⛅ llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 3.61 rec/s, eta 0.3s

[15:22:52] [INFO]   |-- ☀️ llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1.14 rec/s, eta 0.0s

[15:22:52] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:22:52] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:22:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:22:52] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:22:52] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:22:52] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:22:52] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record

[15:22:52] [INFO]   |-- 🥱 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 703.81 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- 😐 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 553.10 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- 🤩 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 635.22 rec/s, eta 0.0s

[15:22:52] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:22:52] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:22:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:22:52] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:22:52] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:22:52] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:22:52] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record

[15:22:52] [INFO]   |-- 🌘 custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 850.91 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- 🌗 custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1008.95 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- 🌕 custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 980.75 rec/s, eta 0.0s

[15:22:52] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:22:52] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:22:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:22:52] [INFO]   |-- required_columns: ['_validation_candidates']

[15:22:52] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:22:52] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record

[15:22:52] [INFO]   |-- 🌦️ custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1097.54 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- ⛅ custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1384.84 rec/s, eta 0.0s

[15:22:52] [INFO]   |-- ☀️ custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1311.88 rec/s, eta 0.0s

[15:22:52] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:22:52] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:22:52] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:22:52] [INFO]   |-- model provider: 'nvidia'

[15:22:52] [INFO]   |-- inference parameters:

[15:22:52] [INFO]   |  |-- generation_type=chat-completion

[15:22:52] [INFO]   |  |-- max_parallel_requests=2

[15:22:52] [INFO]   |  |-- timeout=300

[15:22:52] [INFO]   |  |-- temperature=0.30

[15:22:52] [INFO]   |  |-- top_p=0.95

[15:22:52] [INFO]   |  |-- max_tokens=16384

[15:22:52] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 2 concurrent workers

[15:22:52] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record

[15:23:06] [INFO]   |-- 🌘 llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.07 rec/s, eta 28.2s

[15:23:07] [INFO]   |-- 🌗 llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.13 rec/s, eta 7.8s

[15:23:24] [INFO]   |-- 🌕 llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 0.0s

[15:23:24] [INFO] 🔧 Custom column config for column '_validated_entities'

[15:23:24] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[15:23:24] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:24] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[15:23:24] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[15:23:24] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record

[15:23:24] [INFO]   |-- 😺 custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 827.84 rec/s, eta 0.0s

[15:23:24] [INFO]   |-- 😸 custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 993.95 rec/s, eta 0.0s

[15:23:24] [INFO]   |-- 🦁 custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1037.69 rec/s, eta 0.0s

[15:23:24] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[15:23:24] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[15:23:24] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:24] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[15:23:24] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[15:23:24] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[15:23:24] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record

[15:23:24] [INFO]   |-- 🥱 custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 654.43 rec/s, eta 0.0s

[15:23:24] [INFO]   |-- 😐 custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 840.20 rec/s, eta 0.0s

[15:23:24] [INFO]   |-- 🤩 custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 863.83 rec/s, eta 0.0s

[15:23:24] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[15:23:24] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:23:24] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:23:24] [INFO]   |-- model provider: 'nvidia'

[15:23:24] [INFO]   |-- inference parameters:

[15:23:24] [INFO]   |  |-- generation_type=chat-completion

[15:23:24] [INFO]   |  |-- max_parallel_requests=2

[15:23:24] [INFO]   |  |-- timeout=300

[15:23:24] [INFO]   |  |-- temperature=0.30

[15:23:24] [INFO]   |  |-- top_p=0.95

[15:23:24] [INFO]   |  |-- max_tokens=16384

[15:23:24] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 2 concurrent workers

[15:23:24] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record

[15:23:30] [INFO]   |-- 😺 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.17 rec/s, eta 11.8s

[15:23:31] [INFO]   |-- 😸 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.29 rec/s, eta 3.4s

[15:23:35] [INFO]   |-- 🦁 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.26 rec/s, eta 0.0s

[15:23:35] [INFO] 🔧 Custom column config for column '_merged_entities'

[15:23:35] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[15:23:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:35] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[15:23:35] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:23:35] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[15:23:35] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record

[15:23:35] [INFO]   |-- 🥱 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 369.15 rec/s, eta 0.0s

[15:23:35] [INFO]   |-- 😐 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 392.73 rec/s, eta 0.0s

[15:23:35] [INFO]   |-- 🤩 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 409.93 rec/s, eta 0.0s

[15:23:35] [INFO] 🔧 Custom column config for column '_detected_entities'

[15:23:35] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[15:23:36] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:36] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[15:23:36] [INFO]   |-- side_effect_columns: ['tagged_text']

[15:23:36] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[15:23:36] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record

[15:23:36] [INFO]   |-- 🌦️ custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 199.27 rec/s, eta 0.0s

[15:23:36] [INFO]   |-- ⛅ custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 178.40 rec/s, eta 0.0s

[15:23:36] [INFO]   |-- ☀️ custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 182.85 rec/s, eta 0.0s

[15:23:36] [INFO] 📊 Model usage summary:

[15:23:36] [INFO]   |-- model: nvidia/gliner-pii

[15:23:36] [INFO]   |-- tokens: input=506, output=1445, total=1951, tps=41

[15:23:36] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=3

[15:23:36] [INFO]   |--

[15:23:36] [INFO]   |-- model: openai/gpt-oss-120b

[15:23:36] [INFO]   |-- tokens: input=22414, output=13784, total=36198, tps=774

[15:23:36] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=7

[15:23:36] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[15:23:36] [INFO] 📐 Measuring dataset column statistics:

[15:23:36] [INFO]   |-- 📝 column: '_raw_detected_entities'

[15:23:36] [INFO]   |-- 🔧 column: '_seed_entities'

[15:23:36] [INFO]   |-- 🔧 column: '_validation_candidates'

[15:23:36] [INFO]   |-- 🔧 column: '_validated_entities'

[15:23:36] [INFO]   |-- 🔧 column: '_seed_entities_json'

[15:23:36] [INFO]   |-- 🗂️ column: '_augmented_entities'

[15:23:36] [INFO]   |-- 🔧 column: '_merged_entities'

[15:23:36] [INFO]   |-- 🔧 column: '_detected_entities'

[15:23:36] [INFO] 👏 Preview complete!

[15:23:36] [DEBUG] NDD workflow 'entity-detection' returned 3 records

[15:23:36] [DEBUG] NDD workflow 'latent-entity-detection' starting with 3 records

[15:23:36] [DEBUG] NDD workflow 'latent-entity-detection': 1 columns ['_latent_entities']

[15:23:36] [INFO] 🧐 Preview generation in progress

[15:23:36] [INFO] ✅ Validation passed

[15:23:36] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:23:36] [INFO] 🩺 Running health checks for models...

[15:23:36] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:23:41] [INFO]   |-- ✅ Passed!

[15:23:41] [INFO] 🌱 Sampling 3 records from seed dataset

[15:23:41] [INFO]   |-- seed dataset size: 3 records

[15:23:41] [INFO]   |-- sampling strategy: ordered

[15:23:41] [INFO] 🗂️ llm-structured model config for column '_latent_entities'

[15:23:41] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:23:41] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:23:41] [INFO]   |-- model provider: 'nvidia'

[15:23:41] [INFO]   |-- inference parameters:

[15:23:41] [INFO]   |  |-- generation_type=chat-completion

[15:23:41] [INFO]   |  |-- max_parallel_requests=16

[15:23:41] [INFO]   |  |-- timeout=300

[15:23:41] [INFO]   |  |-- temperature=0.40

[15:23:41] [INFO]   |  |-- top_p=1.00

[15:23:41] [INFO]   |  |-- max_tokens=8192

[15:23:41] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers

[15:23:41] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress after each record

[15:23:54] [INFO]   |-- 🐴 llm-structured column '_latent_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 26.6s

[15:24:02] [INFO]   |-- 🚗 llm-structured column '_latent_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.09 rec/s, eta 10.6s

[15:24:04] [INFO]   |-- 🚀 llm-structured column '_latent_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.13 rec/s, eta 0.0s

[15:24:04] [INFO] 📊 Model usage summary:

[15:24:04] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:24:04] [INFO]   |-- tokens: input=5553, output=13995, total=19548, tps=830

[15:24:04] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=7

[15:24:04] [INFO] 📐 Measuring dataset column statistics:

[15:24:04] [INFO]   |-- 🗂️ column: '_latent_entities'

[15:24:04] [INFO] 🏆 Preview complete!

[15:24:04] [DEBUG] NDD workflow 'latent-entity-detection' returned 3 records

[15:24:04] [INFO]   |-- 📋 Detection complete — 74 entities found across 3 records (0 failed) [85.4s]

[15:24:04] [INFO]   |-- labels: first_name=22, company_name=8, state=6, age=5, occupation=5, city=5, education_level=4, last_name=3, race_ethnicity=3, language=3, political_view=3, religious_belief=2, street_address=2, school_name=1, date_of_birth=1, employment_status=1

[15:24:04] [INFO] ✏️ Running rewrite pipeline

[15:24:04] [DEBUG] NDD workflow 'replace-map-generation' starting with 3 records

[15:24:04] [DEBUG] NDD workflow 'replace-map-generation': 1 columns ['_replacement_map']

[15:24:04] [INFO] 🎨 Creating Data Designer dataset

[15:24:04] [INFO] ✅ Validation passed

[15:24:04] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:24:04] [INFO] 🩺 Running health checks for models...

[15:24:04] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:24:05] [INFO]   |-- ✅ Passed!

[15:24:05] [INFO] 📂 Dataset path '.anonymizer-artifacts/replace-map-generation' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/replace-map-generation_03-31-2026_152405' instead.

[15:24:05] [INFO] ⏳ Processing batch 1 of 1

[15:24:05] [INFO] 🌱 Sampling 3 records from seed dataset

[15:24:05] [INFO]   |-- seed dataset size: 3 records

[15:24:05] [INFO]   |-- sampling strategy: ordered

[15:24:05] [INFO] 🗂️ llm-structured model config for column '_replacement_map'

[15:24:05] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:24:05] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:24:05] [INFO]   |-- model provider: 'nvidia'

[15:24:05] [INFO]   |-- inference parameters:

[15:24:05] [INFO]   |  |-- generation_type=chat-completion

[15:24:05] [INFO]   |  |-- max_parallel_requests=2

[15:24:05] [INFO]   |  |-- timeout=300

[15:24:05] [INFO]   |  |-- temperature=0.30

[15:24:05] [INFO]   |  |-- top_p=0.95

[15:24:05] [INFO]   |  |-- max_tokens=16384

[15:24:05] [INFO] ⚡️ Processing llm-structured column '_replacement_map' with 2 concurrent workers

[15:24:05] [INFO] ⏱️ llm-structured column '_replacement_map' will report progress after each record

[15:24:12] [INFO]   |-- 🥱 llm-structured column '_replacement_map' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.13 rec/s, eta 15.0s

[15:25:20] [INFO]   |-- 😐 llm-structured column '_replacement_map' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.03 rec/s, eta 37.7s

[15:25:27] [INFO]   |-- 🤩 llm-structured column '_replacement_map' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.04 rec/s, eta 0.0s

[15:25:27] [INFO] 📊 Model usage summary:

[15:25:27] [INFO]   |-- model: openai/gpt-oss-120b

[15:25:27] [INFO]   |-- tokens: input=5435, output=6134, total=11569, tps=140

[15:25:27] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=2

[15:25:27] [INFO] 📐 Measuring dataset column statistics:

[15:25:27] [INFO]   |-- 🗂️ column: '_replacement_map'

[15:25:27] [DEBUG] NDD workflow 'replace-map-generation' returned 3 records

[15:25:27] [DEBUG] Replacement map record 08e0bc93ea49595ea5d9cecdc30e2d34: requested=[('40', 'age'), ('Aria and Leo', 'first_name'), ('Bobby', 'first_name'), ('Christian Democrat', 'political_view'), ('Colorado', 'state'), ('Colorado Veterinary Clinic', 'company_name'), ('DVM', 'education_level'), ('Denver', 'city'), ('English', 'language'), ('Jefferson High', 'school_name'), ('Maya', 'first_name'), ('Mexican', 'race_ethnicity'), ('University of Colorado Boulder', 'company_name'), ('VCA Animal Hospital', 'company_name'), ('Watford', 'last_name'), ('veterinarian', 'occupation')] raw=[{'original': '40', 'label': 'age', 'synthetic': '45'}, {'original': 'Aria and Leo', 'label': 'first_name', 'synthetic': 'Mia and Noah'}, {'original': 'Bobby', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Christian Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Colorado', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Colorado Veterinary Clinic', 'label': 'company_name', 'synthetic': 'Oregon Animal Care Center'}, {'original': 'DVM', 'label': 'education_level', 'synthetic': 'PhD in Biology'}, {'original': 'Denver', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jefferson High', 'label': 'school_name', 'synthetic': 'Lincoln High'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'University of Colorado Boulder', 'label': 'company_name', 'synthetic': 'University of Oregon Eugene'}, {'original': 'VCA Animal Hospital', 'label': 'company_name', 'synthetic': 'Paws & Claws Clinic'}, {'original': 'Watford', 'label': 'last_name', 'synthetic': 'Kline'}, {'original': 'veterinarian', 'label': 'occupation', 'synthetic': 'zoologist'}] filtered=[{'original': '40', 'label': 'age', 'synthetic': '45'}, {'original': 'Aria and Leo', 'label': 'first_name', 'synthetic': 'Mia and Noah'}, {'original': 'Bobby', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Christian Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Colorado', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Colorado Veterinary Clinic', 'label': 'company_name', 'synthetic': 'Oregon Animal Care Center'}, {'original': 'DVM', 'label': 'education_level', 'synthetic': 'PhD in Biology'}, {'original': 'Denver', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jefferson High', 'label': 'school_name', 'synthetic': 'Lincoln High'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'University of Colorado Boulder', 'label': 'company_name', 'synthetic': 'University of Oregon Eugene'}, {'original': 'VCA Animal Hospital', 'label': 'company_name', 'synthetic': 'Paws & Claws Clinic'}, {'original': 'Watford', 'label': 'last_name', 'synthetic': 'Kline'}, {'original': 'veterinarian', 'label': 'occupation', 'synthetic': 'zoologist'}]

[15:25:27] [DEBUG] Replacement map record a280a834a8e6573eb1df009fd30503e1: requested=[('37', 'age'), ('Bell', 'last_name'), ('Edison', 'city'), ('Elena', 'first_name'), ('English', 'language'), ('Goddard Space Flight Center', 'company_name'), ('Idilio', 'first_name'), ('Italian', 'race_ethnicity'), ('Lina', 'first_name'), ('Marco', 'first_name'), ('Maya', 'first_name'), ('NASA', 'company_name'), ('New Jersey', 'state'), ('New\u202fJersey', 'state'), ('New\u202fYork', 'state'), ('November\u202f21,\u202f1988', 'date_of_birth'), ('PhD in astrophysics', 'education_level'), ('Princeton', 'city'), ('SpaceX', 'company_name'), ('West Roberts Drive', 'street_address'), ('Zara', 'first_name'), ('astronomer', 'occupation'), ('bachelor’s degree', 'education_level'), ('progressive', 'political_view'), ('retired', 'employment_status'), ('secular', 'religious_belief')] raw=[{'original': '37', 'label': 'age', 'synthetic': '40'}, {'original': 'Bell', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'Edison', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Giulia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Goddard Space Flight Center', 'label': 'company_name', 'synthetic': 'Jet Propulsion Laboratory'}, {'original': 'Idilio', 'label': 'first_name', 'synthetic': 'Santiago'}, {'original': 'Italian', 'label': 'race_ethnicity', 'synthetic': 'Greek'}, {'original': 'Lina', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Marco', 'label': 'first_name', 'synthetic': 'Lorenzo'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Nadia'}, {'original': 'NASA', 'label': 'company_name', 'synthetic': 'European Space Agency'}, {'original': 'New Jersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fJersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fYork', 'label': 'state', 'synthetic': 'Illinois'}, {'original': 'November\u202f21,\u202f1988', 'label': 'date_of_birth', 'synthetic': 'June\u202f5,\u202f1985'}, {'original': 'PhD in astrophysics', 'label': 'education_level', 'synthetic': 'PhD in planetary science'}, {'original': 'Princeton', 'label': 'city', 'synthetic': 'Fort Collins'}, {'original': 'SpaceX', 'label': 'company_name', 'synthetic': 'Blue Origin'}, {'original': 'West Roberts Drive', 'label': 'street_address', 'synthetic': 'North Carter Lane'}, {'original': 'Zara', 'label': 'first_name', 'synthetic': 'Mila'}, {'original': 'astronomer', 'label': 'occupation', 'synthetic': 'planetary geologist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'master’s degree'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'moderate'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'consultant'}, {'original': 'secular', 'label': 'religious_belief', 'synthetic': 'agnostic'}] filtered=[{'original': '37', 'label': 'age', 'synthetic': '40'}, {'original': 'Bell', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'Edison', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Giulia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Goddard Space Flight Center', 'label': 'company_name', 'synthetic': 'Jet Propulsion Laboratory'}, {'original': 'Idilio', 'label': 'first_name', 'synthetic': 'Santiago'}, {'original': 'Italian', 'label': 'race_ethnicity', 'synthetic': 'Greek'}, {'original': 'Lina', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Marco', 'label': 'first_name', 'synthetic': 'Lorenzo'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Nadia'}, {'original': 'NASA', 'label': 'company_name', 'synthetic': 'European Space Agency'}, {'original': 'New Jersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fJersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fYork', 'label': 'state', 'synthetic': 'Illinois'}, {'original': 'November\u202f21,\u202f1988', 'label': 'date_of_birth', 'synthetic': 'June\u202f5,\u202f1985'}, {'original': 'PhD in astrophysics', 'label': 'education_level', 'synthetic': 'PhD in planetary science'}, {'original': 'Princeton', 'label': 'city', 'synthetic': 'Fort Collins'}, {'original': 'SpaceX', 'label': 'company_name', 'synthetic': 'Blue Origin'}, {'original': 'West Roberts Drive', 'label': 'street_address', 'synthetic': 'North Carter Lane'}, {'original': 'Zara', 'label': 'first_name', 'synthetic': 'Mila'}, {'original': 'astronomer', 'label': 'occupation', 'synthetic': 'planetary geologist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'master’s degree'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'moderate'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'consultant'}, {'original': 'secular', 'label': 'religious_belief', 'synthetic': 'agnostic'}]

[15:25:27] [DEBUG] Replacement map record f73a93b8df4f5fa9aa8decab757b3851: requested=[('204\u202fBluegrass', 'street_address'), ('36', 'age'), ('4', 'age'), ('7', 'age'), ('Alex', 'first_name'), ('Allison', 'last_name'), ('BA', 'education_level'), ('Caucasian', 'race_ethnicity'), ('Clayton', 'city'), ('English', 'language'), ('Ethan', 'first_name'), ('Jodi', 'first_name'), ('Maya', 'first_name'), ('Methodist', 'religious_belief'), ('North\u202fCarolina', 'state'), ('Raleigh', 'city'), ('Southern\u202fPublishing', 'company_name'), ('Venture\u202fMedia', 'company_name'), ('copy chief', 'occupation'), ('editor', 'occupation'), ('moderate Democrat', 'political_view'), ('school counselor', 'occupation')] raw=[{'original': '204\u202fBluegrass', 'label': 'street_address', 'synthetic': '317 Oakridge'}, {'original': '36', 'label': 'age', 'synthetic': '42'}, {'original': '4', 'label': 'age', 'synthetic': '5'}, {'original': '7', 'label': 'age', 'synthetic': '9'}, {'original': 'Alex', 'label': 'first_name', 'synthetic': 'Dylan'}, {'original': 'Allison', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'BA', 'label': 'education_level', 'synthetic': 'associate degree'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Asian'}, {'original': 'Clayton', 'label': 'city', 'synthetic': 'Fredericksburg'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'Jodi', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Ava'}, {'original': 'Methodist', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Virginia'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Richmond'}, {'original': 'Southern\u202fPublishing', 'label': 'company_name', 'synthetic': 'Riverbend Press'}, {'original': 'Venture\u202fMedia', 'label': 'company_name', 'synthetic': 'Pioneer Studios'}, {'original': 'copy chief', 'label': 'occupation', 'synthetic': 'project coordinator'}, {'original': 'editor', 'label': 'occupation', 'synthetic': 'graphic designer'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'centrist Republican'}, {'original': 'school counselor', 'label': 'occupation', 'synthetic': 'career advisor'}] filtered=[{'original': '204\u202fBluegrass', 'label': 'street_address', 'synthetic': '317 Oakridge'}, {'original': '36', 'label': 'age', 'synthetic': '42'}, {'original': '4', 'label': 'age', 'synthetic': '5'}, {'original': '7', 'label': 'age', 'synthetic': '9'}, {'original': 'Alex', 'label': 'first_name', 'synthetic': 'Dylan'}, {'original': 'Allison', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'BA', 'label': 'education_level', 'synthetic': 'associate degree'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Asian'}, {'original': 'Clayton', 'label': 'city', 'synthetic': 'Fredericksburg'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'Jodi', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Ava'}, {'original': 'Methodist', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Virginia'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Richmond'}, {'original': 'Southern\u202fPublishing', 'label': 'company_name', 'synthetic': 'Riverbend Press'}, {'original': 'Venture\u202fMedia', 'label': 'company_name', 'synthetic': 'Pioneer Studios'}, {'original': 'copy chief', 'label': 'occupation', 'synthetic': 'project coordinator'}, {'original': 'editor', 'label': 'occupation', 'synthetic': 'graphic designer'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'centrist Republican'}, {'original': 'school counselor', 'label': 'occupation', 'synthetic': 'career advisor'}]

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/replace/llm_replace_workflow.py:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([output_df, passthrough_rows], axis=0)
[15:25:27] [DEBUG] NDD workflow 'rewrite-pipeline' starting with 3 records

[15:25:27] [DEBUG] NDD workflow 'rewrite-pipeline': 12 columns ['_domain', '_domain_supplement', '_sensitivity_disposition', '_sensitivity_disposition_block', '_meaning_units', '_meaning_units_serialized', '_quality_qa', '_privacy_qa', '_rewrite_disposition_block', '_replacement_map_for_prompt', '_full_rewrite', '_rewritten_text']

[15:25:27] [INFO] 🕵️ Preview generation in progress

[15:25:27] [INFO] ✅ Validation passed

[15:25:27] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:25:27] [INFO] 🩺 Running health checks for models...

[15:25:27] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:25:28] [INFO]   |-- ✅ Passed!

[15:25:28] [INFO] 🌱 Sampling 3 records from seed dataset

[15:25:28] [INFO]   |-- seed dataset size: 3 records

[15:25:28] [INFO]   |-- sampling strategy: ordered

[15:25:28] [INFO] 🗂️ llm-structured model config for column '_domain'

[15:25:28] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:25:28] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:25:28] [INFO]   |-- model provider: 'nvidia'

[15:25:28] [INFO]   |-- inference parameters:

[15:25:28] [INFO]   |  |-- generation_type=chat-completion

[15:25:28] [INFO]   |  |-- max_parallel_requests=2

[15:25:28] [INFO]   |  |-- timeout=300

[15:25:28] [INFO]   |  |-- temperature=0.30

[15:25:28] [INFO]   |  |-- top_p=0.95

[15:25:28] [INFO]   |  |-- max_tokens=16384

[15:25:28] [INFO] ⚡️ Processing llm-structured column '_domain' with 2 concurrent workers

[15:25:28] [INFO] ⏱️ llm-structured column '_domain' will report progress after each record

[15:25:28] [INFO]   |-- 🌘 llm-structured column '_domain' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.27 rec/s, eta 1.6s

[15:25:28] [INFO]   |-- 🌗 llm-structured column '_domain' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.52 rec/s, eta 0.4s

[15:25:29] [INFO]   |-- 🌕 llm-structured column '_domain' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2.09 rec/s, eta 0.0s

[15:25:29] [INFO] 🔧 Custom column config for column '_domain_supplement'

[15:25:29] [INFO]   |-- generator_function: '_enrich_domain'

[15:25:29] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:25:29] [INFO]   |-- required_columns: ['_domain']

[15:25:29] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers

[15:25:29] [INFO] ⏱️ custom column '_domain_supplement' will report progress after each record

[15:25:29] [INFO]   |-- 🐣 custom column '_domain_supplement' progress: 1/3 (33%) complete, 1 ok, 0 failed, 913.03 rec/s, eta 0.0s

[15:25:29] [INFO]   |-- 🐥 custom column '_domain_supplement' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1048.19 rec/s, eta 0.0s

[15:25:29] [INFO]   |-- 🐔 custom column '_domain_supplement' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1101.36 rec/s, eta 0.0s

[15:25:29] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'

[15:25:29] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:25:29] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:25:29] [INFO]   |-- model provider: 'nvidia'

[15:25:29] [INFO]   |-- inference parameters:

[15:25:29] [INFO]   |  |-- generation_type=chat-completion

[15:25:29] [INFO]   |  |-- max_parallel_requests=2

[15:25:29] [INFO]   |  |-- timeout=300

[15:25:29] [INFO]   |  |-- temperature=0.30

[15:25:29] [INFO]   |  |-- top_p=0.95

[15:25:29] [INFO]   |  |-- max_tokens=16384

[15:25:29] [INFO] ⚡️ Processing llm-structured column '_sensitivity_disposition' with 2 concurrent workers

[15:25:29] [INFO] ⏱️ llm-structured column '_sensitivity_disposition' will report progress after each record

[15:25:49] [INFO]   |-- 😺 llm-structured column '_sensitivity_disposition' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.05 rec/s, eta 40.1s

[15:25:59] [INFO]   |-- 😸 llm-structured column '_sensitivity_disposition' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.07 rec/s, eta 14.9s

[15:26:18] [INFO]   |-- 🦁 llm-structured column '_sensitivity_disposition' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.06 rec/s, eta 0.0s

[15:26:18] [INFO] 🔧 Custom column config for column '_sensitivity_disposition_block'

[15:26:18] [INFO]   |-- generator_function: '_format_disposition_block'

[15:26:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:26:18] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:26:18] [INFO] ⚡️ Processing custom column '_sensitivity_disposition_block' with 4 concurrent workers

[15:26:18] [INFO] ⏱️ custom column '_sensitivity_disposition_block' will report progress after each record

[15:26:18] [INFO]   |-- 😺 custom column '_sensitivity_disposition_block' progress: 1/3 (33%) complete, 1 ok, 0 failed, 793.68 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 😸 custom column '_sensitivity_disposition_block' progress: 2/3 (67%) complete, 2 ok, 0 failed, 974.44 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 🦁 custom column '_sensitivity_disposition_block' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1031.22 rec/s, eta 0.0s

[15:26:18] [INFO] 🔧 Custom column config for column '_privacy_qa'

[15:26:18] [INFO]   |-- generator_function: '_generate_privacy_qa_column'

[15:26:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:26:18] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:26:18] [INFO] ⚡️ Processing custom column '_privacy_qa' with 4 concurrent workers

[15:26:18] [INFO] ⏱️ custom column '_privacy_qa' will report progress after each record

[15:26:18] [INFO]   |-- 😺 custom column '_privacy_qa' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1090.86 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 😸 custom column '_privacy_qa' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1347.71 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 🦁 custom column '_privacy_qa' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1315.74 rec/s, eta 0.0s

[15:26:18] [INFO] 🔧 Custom column config for column '_rewrite_disposition_block'

[15:26:18] [INFO]   |-- generator_function: '_format_rewrite_disposition_block'

[15:26:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:26:18] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:26:18] [INFO] ⚡️ Processing custom column '_rewrite_disposition_block' with 4 concurrent workers

[15:26:18] [INFO] ⏱️ custom column '_rewrite_disposition_block' will report progress after each record

[15:26:18] [INFO]   |-- 🌘 custom column '_rewrite_disposition_block' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1326.92 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 🌗 custom column '_rewrite_disposition_block' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1585.68 rec/s, eta 0.0s

[15:26:18] [INFO]   |-- 🌕 custom column '_rewrite_disposition_block' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1504.83 rec/s, eta 0.0s

[15:26:18] [INFO] 🗂️ llm-structured model config for column '_meaning_units'

[15:26:18] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:26:18] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:26:18] [INFO]   |-- model provider: 'nvidia'

[15:26:18] [INFO]   |-- inference parameters:

[15:26:18] [INFO]   |  |-- generation_type=chat-completion

[15:26:18] [INFO]   |  |-- max_parallel_requests=2

[15:26:18] [INFO]   |  |-- timeout=300

[15:26:18] [INFO]   |  |-- temperature=0.30

[15:26:18] [INFO]   |  |-- top_p=0.95

[15:26:18] [INFO]   |  |-- max_tokens=16384

[15:26:18] [INFO] ⚡️ Processing llm-structured column '_meaning_units' with 2 concurrent workers

[15:26:18] [INFO] ⏱️ llm-structured column '_meaning_units' will report progress after each record

[15:26:26] [INFO]   |-- 🌦️ llm-structured column '_meaning_units' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.12 rec/s, eta 16.9s

[15:26:29] [INFO]   |-- ⛅ llm-structured column '_meaning_units' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.19 rec/s, eta 5.3s

[15:26:35] [INFO]   |-- ☀️ llm-structured column '_meaning_units' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.18 rec/s, eta 0.0s

[15:26:35] [INFO] 🔧 Custom column config for column '_replacement_map_for_prompt'

[15:26:35] [INFO]   |-- generator_function: '_filter_replacement_map_for_prompt'

[15:26:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:26:35] [INFO]   |-- required_columns: ['_replacement_map', '_rewrite_disposition_block']

[15:26:35] [INFO] ⚡️ Processing custom column '_replacement_map_for_prompt' with 4 concurrent workers

[15:26:35] [INFO] ⏱️ custom column '_replacement_map_for_prompt' will report progress after each record

[15:26:35] [INFO]   |-- 🐴 custom column '_replacement_map_for_prompt' progress: 1/3 (33%) complete, 1 ok, 0 failed, 863.68 rec/s, eta 0.0s

[15:26:35] [INFO]   |-- 🚗 custom column '_replacement_map_for_prompt' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1109.03 rec/s, eta 0.0s

[15:26:35] [INFO]   |-- 🚀 custom column '_replacement_map_for_prompt' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1051.96 rec/s, eta 0.0s

[15:26:35] [INFO] 🔧 Custom column config for column '_meaning_units_serialized'

[15:26:35] [INFO]   |-- generator_function: '_serialize_meaning_units'

[15:26:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:26:35] [INFO]   |-- required_columns: ['_meaning_units']

[15:26:35] [INFO] ⚡️ Processing custom column '_meaning_units_serialized' with 4 concurrent workers

[15:26:35] [INFO] ⏱️ custom column '_meaning_units_serialized' will report progress after each record

[15:26:35] [INFO]   |-- 🥱 custom column '_meaning_units_serialized' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1035.20 rec/s, eta 0.0s

[15:26:35] [INFO]   |-- 😐 custom column '_meaning_units_serialized' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1309.04 rec/s, eta 0.0s

[15:26:35] [INFO]   |-- 🤩 custom column '_meaning_units_serialized' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1275.51 rec/s, eta 0.0s

[15:26:35] [INFO] 🗂️ llm-structured model config for column '_full_rewrite'

[15:26:35] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:26:35] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:26:35] [INFO]   |-- model provider: 'nvidia'

[15:26:35] [INFO]   |-- inference parameters:

[15:26:35] [INFO]   |  |-- generation_type=chat-completion

[15:26:35] [INFO]   |  |-- max_parallel_requests=2

[15:26:35] [INFO]   |  |-- timeout=300

[15:26:35] [INFO]   |  |-- temperature=0.30

[15:26:35] [INFO]   |  |-- top_p=0.95

[15:26:35] [INFO]   |  |-- max_tokens=16384

[15:26:35] [INFO] ⚡️ Processing llm-structured column '_full_rewrite' with 2 concurrent workers

[15:26:35] [INFO] ⏱️ llm-structured column '_full_rewrite' will report progress after each record

[15:26:42] [INFO]   |-- 🐴 llm-structured column '_full_rewrite' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.13 rec/s, eta 15.2s

[15:26:43] [INFO]   |-- 🚗 llm-structured column '_full_rewrite' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 4.3s

[15:26:51] [INFO]   |-- 🚀 llm-structured column '_full_rewrite' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.18 rec/s, eta 0.0s

[15:26:51] [INFO] 🗂️ llm-structured model config for column '_quality_qa'

[15:26:51] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:26:51] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:26:51] [INFO]   |-- model provider: 'nvidia'

[15:26:51] [INFO]   |-- inference parameters:

[15:26:51] [INFO]   |  |-- generation_type=chat-completion

[15:26:51] [INFO]   |  |-- max_parallel_requests=2

[15:26:51] [INFO]   |  |-- timeout=300

[15:26:51] [INFO]   |  |-- temperature=0.30

[15:26:51] [INFO]   |  |-- top_p=0.95

[15:26:51] [INFO]   |  |-- max_tokens=16384

[15:26:51] [INFO] ⚡️ Processing llm-structured column '_quality_qa' with 2 concurrent workers

[15:26:51] [INFO] ⏱️ llm-structured column '_quality_qa' will report progress after each record

[15:26:56] [INFO]   |-- 🌘 llm-structured column '_quality_qa' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.21 rec/s, eta 9.5s

[15:26:59] [INFO]   |-- 🌗 llm-structured column '_quality_qa' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.25 rec/s, eta 4.0s

[15:27:02] [INFO]   |-- 🌕 llm-structured column '_quality_qa' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.26 rec/s, eta 0.0s

[15:27:02] [INFO] 🔧 Custom column config for column '_rewritten_text'

[15:27:02] [INFO]   |-- generator_function: '_extract_rewritten_text'

[15:27:02] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:02] [INFO]   |-- required_columns: ['_full_rewrite']

[15:27:02] [INFO] ⚡️ Processing custom column '_rewritten_text' with 4 concurrent workers

[15:27:02] [INFO] ⏱️ custom column '_rewritten_text' will report progress after each record

[15:27:02] [INFO]   |-- 🐣 custom column '_rewritten_text' progress: 1/3 (33%) complete, 1 ok, 0 failed, 849.32 rec/s, eta 0.0s

[15:27:02] [INFO]   |-- 🐥 custom column '_rewritten_text' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1148.33 rec/s, eta 0.0s

[15:27:02] [INFO]   |-- 🐔 custom column '_rewritten_text' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1136.45 rec/s, eta 0.0s

[15:27:02] [INFO] 📊 Model usage summary:

[15:27:02] [INFO]   |-- model: openai/gpt-oss-120b

[15:27:02] [INFO]   |-- tokens: input=30271, output=31909, total=62180, tps=655

[15:27:02] [INFO]   |-- requests: success=15, failed=0, total=15, rpm=9

[15:27:02] [INFO] 📐 Measuring dataset column statistics:

[15:27:02] [INFO]   |-- 🗂️ column: '_domain'

[15:27:02] [INFO]   |-- 🔧 column: '_domain_supplement'

[15:27:02] [INFO]   |-- 🗂️ column: '_sensitivity_disposition'

[15:27:02] [INFO]   |-- 🔧 column: '_sensitivity_disposition_block'

[15:27:02] [INFO]   |-- 🗂️ column: '_meaning_units'

[15:27:02] [INFO]   |-- 🔧 column: '_meaning_units_serialized'

[15:27:02] [INFO]   |-- 🗂️ column: '_quality_qa'

[15:27:02] [INFO]   |-- 🔧 column: '_privacy_qa'

[15:27:02] [INFO]   |-- 🔧 column: '_rewrite_disposition_block'

[15:27:02] [INFO]   |-- 🔧 column: '_replacement_map_for_prompt'

[15:27:02] [INFO]   |-- 🗂️ column: '_full_rewrite'

[15:27:02] [INFO]   |-- 🔧 column: '_rewritten_text'

[15:27:02] [INFO] 🎊 Preview complete!

[15:27:02] [DEBUG] NDD workflow 'rewrite-pipeline' returned 3 records

[15:27:02] [DEBUG] NDD workflow 'rewrite-evaluate-0' starting with 3 records

[15:27:02] [DEBUG] NDD workflow 'rewrite-evaluate-0': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:27:02] [INFO] 📺 Preview generation in progress

[15:27:02] [INFO] ✅ Validation passed

[15:27:02] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:27:02] [INFO] 🩺 Running health checks for models...

[15:27:02] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:27:04] [INFO]   |-- ✅ Passed!

[15:27:04] [INFO] 🌱 Sampling 3 records from seed dataset

[15:27:04] [INFO]   |-- seed dataset size: 3 records

[15:27:04] [INFO]   |-- sampling strategy: ordered

[15:27:04] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:27:04] [INFO]   |-- generator_function: '_quality_reanswer'

[15:27:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:04] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:27:04] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:04] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:27:04] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:27:08] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.22 rec/s, eta 9.3s

[15:27:11] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.28 rec/s, eta 3.5s

[15:27:11] [INFO]   |-- 🐔 custom column '_quality_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.41 rec/s, eta 0.0s

[15:27:11] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:27:11] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:27:11] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:11] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:27:11] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:11] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:27:11] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:27:15] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.28 rec/s, eta 7.0s

[15:27:16] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.40 rec/s, eta 2.5s

[15:27:17] [INFO]   |-- ☀️ custom column '_privacy_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.52 rec/s, eta 0.0s

[15:27:17] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:27:17] [INFO]   |-- generator_function: '_quality_compare'

[15:27:17] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:17] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:27:17] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:17] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:27:17] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:27:24] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.14 rec/s, eta 14.1s

[15:27:25] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 4.3s

[15:27:26] [INFO]   |-- 🌕 custom column '_quality_qa_compare' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.34 rec/s, eta 0.0s

[15:27:26] [INFO] 🔧 Custom column config for column 'utility_score'

[15:27:26] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:27:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:26] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:27:26] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:27:26] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:27:26] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:27:26] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:27:26] [INFO]   |-- 🐴 custom column 'utility_score' progress: 1/3 (33%) complete, 1 ok, 0 failed, 783.03 rec/s, eta 0.0s

[15:27:26] [INFO]   |-- 🚗 custom column 'utility_score' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1142.12 rec/s, eta 0.0s

[15:27:26] [INFO]   |-- 🚀 custom column 'utility_score' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1377.15 rec/s, eta 0.0s

[15:27:26] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:27:26] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:27:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:26] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:27:26] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:27:26] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:27:26] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:27:26] [INFO]   |-- 🐴 custom column '_needs_repair' progress: 1/3 (33%) complete, 1 ok, 0 failed, 2633.89 rec/s, eta 0.0s

[15:27:26] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 2/3 (67%) complete, 2 ok, 0 failed, 3369.60 rec/s, eta 0.0s

[15:27:26] [INFO]   |-- 🚀 custom column '_needs_repair' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2649.39 rec/s, eta 0.0s

[15:27:26] [INFO] 📊 Model usage summary:

[15:27:26] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:27:26] [INFO]   |-- tokens: input=10838, output=13363, total=24201, tps=1091

[15:27:26] [INFO]   |-- requests: success=9, failed=0, total=9, rpm=24

[15:27:26] [INFO] 📐 Measuring dataset column statistics:

[15:27:26] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:27:26] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:27:26] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:27:26] [INFO]   |-- 🔧 column: 'utility_score'

[15:27:26] [INFO]   |-- 🔧 column: '_needs_repair'

[15:27:26] [INFO] 🎉 Preview complete!

[15:27:26] [DEBUG] NDD workflow 'rewrite-evaluate-0' returned 3 records

[15:27:26] [INFO] Evaluate-repair loop iteration 0: 2/3 rows need repair

[15:27:26] [DEBUG] NDD workflow 'rewrite-repair-0' starting with 2 records

[15:27:26] [DEBUG] NDD workflow 'rewrite-repair-0': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:27:26] [INFO] 🕵️ Preview generation in progress

[15:27:26] [INFO] ✅ Validation passed

[15:27:26] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:27:26] [INFO] 🩺 Running health checks for models...

[15:27:26] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:27:26] [INFO]   |-- ✅ Passed!

[15:27:26] [INFO] 🌱 Sampling 2 records from seed dataset

[15:27:26] [INFO]   |-- seed dataset size: 2 records

[15:27:26] [INFO]   |-- sampling strategy: ordered

[15:27:26] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:27:26] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:27:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:26] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:27:26] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:27:26] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:27:26] [INFO]   |-- 🌗 custom column '_leaked_privacy_items' progress: 1/2 (50%) complete, 1 ok, 0 failed, 865.05 rec/s, eta 0.0s

[15:27:26] [INFO]   |-- 🌕 custom column '_leaked_privacy_items' progress: 2/2 (100%) complete, 2 ok, 0 failed, 1185.51 rec/s, eta 0.0s

[15:27:26] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:27:26] [INFO]   |-- generator_function: '_repair_column'

[15:27:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:26] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:27:26] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:27:26] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All direct identifiers and quasi-identifier combinations (names, locations, employers, dates)\nPRESERVE: Career trajectory, educational background, and professional accomplishments' max_privacy_leak=0.6

[15:27:26] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:27:26] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:27:31] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.23 rec/s, eta 4.3s

[15:27:33] [INFO]   |-- 🐔 custom column '_rewritten_text__next' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.30 rec/s, eta 0.0s

[15:27:33] [INFO] 📊 Model usage summary:

[15:27:33] [INFO]   |-- model: openai/gpt-oss-120b

[15:27:33] [INFO]   |-- tokens: input=3140, output=2076, total=5216, tps=750

[15:27:33] [INFO]   |-- requests: success=2, failed=0, total=2, rpm=17

[15:27:33] [INFO] 📐 Measuring dataset column statistics:

[15:27:33] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:27:33] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:27:33] [INFO] 🎉 Preview complete!

[15:27:33] [DEBUG] NDD workflow 'rewrite-repair-0' returned 2 records

[15:27:33] [DEBUG] NDD workflow 'rewrite-evaluate-1' starting with 2 records

[15:27:33] [DEBUG] NDD workflow 'rewrite-evaluate-1': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:27:33] [INFO] 🖼️ Preview generation in progress

[15:27:33] [INFO] ✅ Validation passed

[15:27:33] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:27:33] [INFO] 🩺 Running health checks for models...

[15:27:33] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:27:34] [INFO]   |-- ✅ Passed!

[15:27:34] [INFO] 🌱 Sampling 2 records from seed dataset

[15:27:34] [INFO]   |-- seed dataset size: 2 records

[15:27:34] [INFO]   |-- sampling strategy: ordered

[15:27:34] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:27:34] [INFO]   |-- generator_function: '_quality_reanswer'

[15:27:34] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:34] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:27:34] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:34] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:27:34] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:27:37] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.30 rec/s, eta 3.4s

[15:27:38] [INFO]   |-- 🐔 custom column '_quality_qa_reanswer' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.52 rec/s, eta 0.0s

[15:27:38] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:27:38] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:27:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:38] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:27:38] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:38] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:27:38] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:27:42] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.25 rec/s, eta 4.0s

[15:27:46] [INFO]   |-- 🌕 custom column '_privacy_qa_reanswer' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.25 rec/s, eta 0.0s

[15:27:46] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:27:46] [INFO]   |-- generator_function: '_quality_compare'

[15:27:46] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:46] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:27:46] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:27:46] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:27:46] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:27:52] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.16 rec/s, eta 6.4s

[15:27:57] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.18 rec/s, eta 0.0s

[15:27:57] [INFO] 🔧 Custom column config for column 'utility_score'

[15:27:57] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:27:57] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:57] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:27:57] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:27:57] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:27:57] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:27:57] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:27:57] [INFO]   |-- ⛅ custom column 'utility_score' progress: 1/2 (50%) complete, 1 ok, 0 failed, 737.33 rec/s, eta 0.0s

[15:27:57] [INFO]   |-- ☀️ custom column 'utility_score' progress: 2/2 (100%) complete, 2 ok, 0 failed, 887.64 rec/s, eta 0.0s

[15:27:57] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:27:57] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:27:57] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:27:57] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:27:57] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:27:57] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:27:57] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:27:57] [INFO]   |-- 😸 custom column '_needs_repair' progress: 1/2 (50%) complete, 1 ok, 0 failed, 1223.68 rec/s, eta 0.0s

[15:27:57] [INFO]   |-- 🦁 custom column '_needs_repair' progress: 2/2 (100%) complete, 2 ok, 0 failed, 1451.47 rec/s, eta 0.0s

[15:27:57] [INFO] 📊 Model usage summary:

[15:27:57] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:27:57] [INFO]   |-- tokens: input=6896, output=8729, total=15625, tps=673

[15:27:57] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=15

[15:27:57] [INFO] 📐 Measuring dataset column statistics:

[15:27:57] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:27:57] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:27:57] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:27:57] [INFO]   |-- 🔧 column: 'utility_score'

[15:27:57] [INFO]   |-- 🔧 column: '_needs_repair'

[15:27:57] [INFO] 🥳 Preview complete!

[15:27:57] [DEBUG] NDD workflow 'rewrite-evaluate-1' returned 2 records

[15:27:57] [INFO] Evaluate-repair loop: all rows pass at iteration 1

[15:27:57] [DEBUG] NDD workflow 'rewrite-final-judge' starting with 3 records

[15:27:57] [DEBUG] NDD workflow 'rewrite-final-judge': 2 columns ['_judge_evaluation', 'needs_human_review']

[15:27:57] [INFO] 🖼️ Preview generation in progress

[15:27:57] [INFO] ✅ Validation passed

[15:27:57] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:27:57] [INFO] 🩺 Running health checks for models...

[15:27:57] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:27:58] [INFO]   |-- ✅ Passed!

[15:27:58] [INFO] 🌱 Sampling 3 records from seed dataset

[15:27:58] [INFO]   |-- seed dataset size: 3 records

[15:27:58] [INFO]   |-- sampling strategy: ordered

[15:27:58] [INFO] ⚖️ llm-judge model config for column '_judge_evaluation'

[15:27:58] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:27:58] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:27:58] [INFO]   |-- model provider: 'nvidia'

[15:27:58] [INFO]   |-- inference parameters:

[15:27:58] [INFO]   |  |-- generation_type=chat-completion

[15:27:58] [INFO]   |  |-- max_parallel_requests=16

[15:27:58] [INFO]   |  |-- timeout=300

[15:27:58] [INFO]   |  |-- temperature=0.40

[15:27:58] [INFO]   |  |-- top_p=1.00

[15:27:58] [INFO]   |  |-- max_tokens=8192

[15:27:58] [INFO] ⚡️ Processing llm-judge column '_judge_evaluation' with 16 concurrent workers

[15:27:58] [INFO] ⏱️ llm-judge column '_judge_evaluation' will report progress after each record

[15:28:04] [INFO]   |-- 😺 llm-judge column '_judge_evaluation' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.17 rec/s, eta 12.1s

[15:28:04] [INFO]   |-- 😸 llm-judge column '_judge_evaluation' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.30 rec/s, eta 3.4s

[15:28:05] [INFO]   |-- 🦁 llm-judge column '_judge_evaluation' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.43 rec/s, eta 0.0s

[15:28:05] [INFO] 🔧 Custom column config for column 'needs_human_review'

[15:28:05] [INFO]   |-- generator_function: '_determine_needs_human_review'

[15:28:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:28:05] [INFO]   |-- required_columns: ['_rewritten_text', 'utility_score', 'leakage_mass', 'any_high_leaked']

[15:28:05] [INFO]   |-- generator_params: flag_utility_below=0.5 flag_leakage_mass_above=2.0

[15:28:05] [INFO] ⚡️ Processing custom column 'needs_human_review' with 4 concurrent workers

[15:28:05] [INFO] ⏱️ custom column 'needs_human_review' will report progress after each record

[15:28:05] [INFO]   |-- 🌦️ custom column 'needs_human_review' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1063.22 rec/s, eta 0.0s

[15:28:05] [INFO]   |-- ⛅ custom column 'needs_human_review' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1447.61 rec/s, eta 0.0s

[15:28:05] [INFO]   |-- ☀️ custom column 'needs_human_review' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1292.11 rec/s, eta 0.0s

[15:28:05] [INFO] 📊 Model usage summary:

[15:28:05] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:28:05] [INFO]   |-- tokens: input=4686, output=3963, total=8649, tps=1194

[15:28:05] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=24

[15:28:05] [INFO] 📐 Measuring dataset column statistics:

[15:28:05] [INFO]   |-- ⚖️ column: '_judge_evaluation'

[15:28:05] [INFO]   |-- 🔧 column: 'needs_human_review'

[15:28:05] [INFO] ✅ Preview complete!

[15:28:05] [DEBUG] NDD workflow 'rewrite-final-judge' returned 3 records

[15:28:05] [INFO]   |-- 📋 Rewrite complete (0 failed) [240.6s]

[15:28:05] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

In [6]:
preview.display_record(1)

## Full run

`result.dataframe` has user-facing columns only.
`result.trace_dataframe` has every intermediate column for debugging.

In [7]:
result = anonymizer.run(config=config, data=input_data)

print(result)
result.dataframe.head()

[15:28:05] [INFO] 📂 Loaded 25 records from ../data/NVIDIA_synthetic_biographies.csv (column: 'biography')

[15:28:05] [DEBUG] input text lengths: min=934, max=1331, mean=1137 chars (25 records)

[15:28:05] [DEBUG] detection config: threshold=0.30, labels=(default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)

[15:28:05] [INFO] 🔍 Running entity detection on 25 records

[15:28:05] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[15:28:05] [DEBUG] NDD workflow 'entity-detection' starting with 25 records

[15:28:05] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[15:28:05] [INFO] 🎨 Creating Data Designer dataset

[15:28:05] [INFO] ✅ Validation passed

[15:28:05] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:28:05] [INFO] 🩺 Running health checks for models...

[15:28:05] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...

[15:28:05] [INFO]   |-- ✅ Passed!

[15:28:05] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:28:06] [INFO]   |-- ✅ Passed!

[15:28:06] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-31-2026_152806' instead.

[15:28:06] [INFO] ⏳ Processing batch 1 of 1

[15:28:06] [INFO] 🌱 Sampling 25 records from seed dataset

[15:28:06] [INFO]   |-- seed dataset size: 25 records

[15:28:06] [INFO]   |-- sampling strategy: ordered

[15:28:06] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:28:06] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:28:06] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:28:06] [INFO]   |-- model provider: 'nvidia'

[15:28:06] [INFO]   |-- inference parameters:

[15:28:06] [INFO]   |  |-- generation_type=chat-completion

[15:28:06] [INFO]   |  |-- max_parallel_requests=4

[15:28:06] [INFO]   |  |-- timeout=120

[15:28:06] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:28:06] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 4 concurrent workers

[15:28:06] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress every 2 records

[15:28:07] [INFO]   |-- 🐱 llm-text column '_raw_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2.93 rec/s, eta 7.8s

[15:28:07] [INFO]   |-- 🐱 llm-text column '_raw_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 3.88 rec/s, eta 5.4s

[15:28:07] [INFO]   |-- 🐱 llm-text column '_raw_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 5.03 rec/s, eta 3.8s

[15:28:07] [INFO]   |-- 😺 llm-text column '_raw_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 5.55 rec/s, eta 3.1s

[15:28:08] [INFO]   |-- 😺 llm-text column '_raw_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 5.86 rec/s, eta 2.6s

[15:28:08] [INFO]   |-- 😺 llm-text column '_raw_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 6.20 rec/s, eta 2.1s

[15:28:10] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 3.70 rec/s, eta 3.0s

[15:28:15] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1.80 rec/s, eta 5.0s

[15:28:17] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1.57 rec/s, eta 4.5s

[15:28:22] [INFO]   |-- 😼 llm-text column '_raw_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1.28 rec/s, eta 3.9s

[15:28:26] [WARNING] ⚠️ Generation for record at index 16 failed. Will omit this record from the dataset.
  |----------
  | Cause: You have exceeded the rate limit for model 'nvidia/gliner-pii' while running generation for column '_raw_detected_entities'.
  | Solution: Wait and try again in a few moments.
  |----------

[15:28:26] [INFO]   |-- 😼 llm-text column '_raw_detected_entities' progress: 22/25 (88%) complete, 21 ok, 1 failed, 1.10 rec/s, eta 2.7s

[15:28:26] [WARNING] ⚠️ Generation for record at index 14 failed. Will omit this record from the dataset.
  |----------
  | Cause: You have exceeded the rate limit for model 'nvidia/gliner-pii' while running generation for column '_raw_detected_entities'.
  | Solution: Wait and try again in a few moments.
  |----------

[15:28:26] [INFO]   |-- 😼 llm-text column '_raw_detected_entities' progress: 24/25 (96%) complete, 22 ok, 2 failed, 1.19 rec/s, eta 0.8s

[15:28:29] [INFO]   |-- 🦁 llm-text column '_raw_detected_entities' progress: 25/25 (100%) complete, 23 ok, 2 failed, 1.11 rec/s, eta 0.0s

[15:28:29] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:28:29] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:28:29] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:28:29] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:28:29] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:28:29] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:28:29] [INFO] ⏱️ custom column '_seed_entities' will report progress every 2 records

[15:28:29] [INFO]   |-- 🐱 custom column '_seed_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 780.81 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🐱 custom column '_seed_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 991.31 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🐱 custom column '_seed_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1127.43 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_seed_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1183.08 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_seed_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1144.67 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_seed_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1224.12 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_seed_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1325.00 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_seed_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1101.83 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_seed_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1163.11 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_seed_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1239.96 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_seed_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 1310.40 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_seed_entities' progress: 23/25 (92%) complete, 23 ok, 0 failed, 1342.82 rec/s, eta 0.0s

[15:28:29] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:28:29] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:28:29] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:28:29] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:28:29] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:28:29] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:28:29] [INFO] ⏱️ custom column '_validation_candidates' will report progress every 2 records

[15:28:29] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2056.64 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2395.09 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2583.84 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2704.68 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2580.42 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2696.10 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2696.69 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2857.23 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2927.62 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2939.83 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 22/25 (88%) complete, 22 ok, 0 failed, 3049.54 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 23/25 (92%) complete, 23 ok, 0 failed, 3080.17 rec/s, eta 0.0s

[15:28:29] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:28:29] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:28:29] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:28:29] [INFO]   |-- required_columns: ['_validation_candidates']

[15:28:29] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:28:29] [INFO] ⏱️ custom column '_validation_skeleton' will report progress every 2 records

[15:28:29] [INFO]   |-- 🌑 custom column '_validation_skeleton' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2932.19 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌑 custom column '_validation_skeleton' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2953.12 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌑 custom column '_validation_skeleton' progress: 6/25 (24%) complete, 6 ok, 0 failed, 3387.92 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌘 custom column '_validation_skeleton' progress: 8/25 (32%) complete, 8 ok, 0 failed, 3715.67 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌘 custom column '_validation_skeleton' progress: 10/25 (40%) complete, 10 ok, 0 failed, 3908.73 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌘 custom column '_validation_skeleton' progress: 12/25 (48%) complete, 12 ok, 0 failed, 4114.11 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 14/25 (56%) complete, 14 ok, 0 failed, 4053.96 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 16/25 (64%) complete, 16 ok, 0 failed, 4159.04 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 18/25 (72%) complete, 18 ok, 0 failed, 4151.09 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌖 custom column '_validation_skeleton' progress: 20/25 (80%) complete, 20 ok, 0 failed, 4229.60 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌖 custom column '_validation_skeleton' progress: 22/25 (88%) complete, 22 ok, 0 failed, 4374.19 rec/s, eta 0.0s

[15:28:29] [INFO]   |-- 🌖 custom column '_validation_skeleton' progress: 23/25 (92%) complete, 23 ok, 0 failed, 4336.79 rec/s, eta 0.0s

[15:28:29] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:28:29] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:28:29] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:28:29] [INFO]   |-- model provider: 'nvidia'

[15:28:29] [INFO]   |-- inference parameters:

[15:28:29] [INFO]   |  |-- generation_type=chat-completion

[15:28:29] [INFO]   |  |-- max_parallel_requests=2

[15:28:29] [INFO]   |  |-- timeout=300

[15:28:29] [INFO]   |  |-- temperature=0.30

[15:28:29] [INFO]   |  |-- top_p=0.95

[15:28:29] [INFO]   |  |-- max_tokens=16384

[15:28:29] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 2 concurrent workers

[15:28:29] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress every 2 records

[15:28:41] [INFO]   |-- 🌑 llm-structured column '_validation_decisions' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.16 rec/s, eta 139.4s

[15:28:57] [INFO]   |-- 🌑 llm-structured column '_validation_decisions' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.14 rec/s, eta 148.3s

[15:29:10] [INFO]   |-- 🌑 llm-structured column '_validation_decisions' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.14 rec/s, eta 132.6s

[15:29:26] [INFO]   |-- 🌘 llm-structured column '_validation_decisions' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.14 rec/s, eta 122.1s

[15:29:42] [INFO]   |-- 🌘 llm-structured column '_validation_decisions' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.14 rec/s, eta 110.5s

[15:29:56] [INFO]   |-- 🌘 llm-structured column '_validation_decisions' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.14 rec/s, eta 94.2s

[15:30:12] [INFO]   |-- 🌗 llm-structured column '_validation_decisions' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.14 rec/s, eta 81.4s

[15:30:25] [INFO]   |-- 🌗 llm-structured column '_validation_decisions' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.14 rec/s, eta 65.5s

[15:30:43] [INFO]   |-- 🌗 llm-structured column '_validation_decisions' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.13 rec/s, eta 52.1s

[15:31:02] [INFO]   |-- 🌖 llm-structured column '_validation_decisions' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.13 rec/s, eta 38.2s

[15:31:20] [INFO]   |-- 🌖 llm-structured column '_validation_decisions' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.13 rec/s, eta 23.4s

[15:31:52] [INFO]   |-- 🌖 llm-structured column '_validation_decisions' progress: 23/25 (92%) complete, 23 ok, 0 failed, 0.11 rec/s, eta 17.7s

[15:31:52] [INFO] 🔧 Custom column config for column '_validated_entities'

[15:31:52] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[15:31:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:31:52] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[15:31:52] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[15:31:52] [INFO] ⏱️ custom column '_validated_entities' will report progress every 2 records

[15:31:52] [INFO]   |-- 🌧️ custom column '_validated_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1149.37 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌧️ custom column '_validated_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1496.73 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌧️ custom column '_validated_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1790.02 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_validated_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1888.95 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_validated_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1895.69 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_validated_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2037.29 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_validated_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2145.68 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_validated_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2234.57 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_validated_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2326.98 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_validated_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2452.71 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_validated_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2536.55 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_validated_entities' progress: 23/25 (92%) complete, 23 ok, 0 failed, 2558.47 rec/s, eta 0.0s

[15:31:52] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[15:31:52] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[15:31:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:31:52] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[15:31:52] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[15:31:52] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[15:31:52] [INFO] ⏱️ custom column '_seed_entities_json' will report progress every 2 records

[15:31:52] [INFO]   |-- 🌧️ custom column '_seed_entities_json' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2188.98 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌧️ custom column '_seed_entities_json' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2338.78 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌧️ custom column '_seed_entities_json' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2333.00 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_seed_entities_json' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2624.85 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_seed_entities_json' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2570.12 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌦️ custom column '_seed_entities_json' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2542.55 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_seed_entities_json' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2624.92 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_seed_entities_json' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2725.45 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- ⛅ custom column '_seed_entities_json' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2777.49 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_seed_entities_json' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2863.45 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_seed_entities_json' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2957.49 rec/s, eta 0.0s

[15:31:52] [INFO]   |-- 🌤️ custom column '_seed_entities_json' progress: 23/25 (92%) complete, 23 ok, 0 failed, 2985.83 rec/s, eta 0.0s

[15:31:52] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[15:31:52] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:31:52] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:31:52] [INFO]   |-- model provider: 'nvidia'

[15:31:52] [INFO]   |-- inference parameters:

[15:31:52] [INFO]   |  |-- generation_type=chat-completion

[15:31:52] [INFO]   |  |-- max_parallel_requests=2

[15:31:52] [INFO]   |  |-- timeout=300

[15:31:52] [INFO]   |  |-- temperature=0.30

[15:31:52] [INFO]   |  |-- top_p=0.95

[15:31:52] [INFO]   |  |-- max_tokens=16384

[15:31:52] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 2 concurrent workers

[15:31:52] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress every 2 records

[15:31:59] [INFO]   |-- 🌑 llm-structured column '_augmented_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.28 rec/s, eta 82.0s

[15:32:03] [INFO]   |-- 🌑 llm-structured column '_augmented_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.35 rec/s, eta 60.3s

[15:32:08] [INFO]   |-- 🌑 llm-structured column '_augmented_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.36 rec/s, eta 52.8s

[15:32:14] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.35 rec/s, eta 48.0s

[15:32:21] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.34 rec/s, eta 44.5s

[15:32:26] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.35 rec/s, eta 36.8s

[15:32:32] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.35 rec/s, eta 31.8s

[15:32:37] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.35 rec/s, eta 25.5s

[15:32:41] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.37 rec/s, eta 19.1s

[15:32:44] [INFO]   |-- 🌖 llm-structured column '_augmented_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.38 rec/s, eta 13.1s

[15:32:53] [INFO]   |-- 🌖 llm-structured column '_augmented_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.36 rec/s, eta 8.4s

[15:32:55] [INFO]   |-- 🌖 llm-structured column '_augmented_entities' progress: 23/25 (92%) complete, 23 ok, 0 failed, 0.37 rec/s, eta 5.5s

[15:32:55] [INFO] 🔧 Custom column config for column '_merged_entities'

[15:32:55] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[15:32:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:32:55] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[15:32:55] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:32:55] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[15:32:55] [INFO] ⏱️ custom column '_merged_entities' will report progress every 2 records

[15:32:55] [INFO]   |-- 🐱 custom column '_merged_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 954.54 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🐱 custom column '_merged_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1317.40 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🐱 custom column '_merged_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1250.97 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😺 custom column '_merged_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1507.68 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😺 custom column '_merged_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1403.71 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😺 custom column '_merged_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1334.45 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😸 custom column '_merged_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1388.39 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😸 custom column '_merged_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1454.21 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😸 custom column '_merged_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1443.86 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😼 custom column '_merged_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1409.37 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😼 custom column '_merged_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 1486.97 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 😼 custom column '_merged_entities' progress: 23/25 (92%) complete, 23 ok, 0 failed, 1511.88 rec/s, eta 0.0s

[15:32:55] [INFO] 🔧 Custom column config for column '_detected_entities'

[15:32:55] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[15:32:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:32:55] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[15:32:55] [INFO]   |-- side_effect_columns: ['tagged_text']

[15:32:55] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[15:32:55] [INFO] ⏱️ custom column '_detected_entities' will report progress every 2 records

[15:32:55] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1337.87 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 827.24 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 644.40 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 450.85 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 494.84 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 493.70 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 410.27 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 436.29 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 408.70 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 413.27 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 428.40 rec/s, eta 0.0s

[15:32:55] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 23/25 (92%) complete, 23 ok, 0 failed, 445.58 rec/s, eta 0.0s

[15:32:55] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[15:32:55] [INFO] 📊 Model usage summary:

[15:32:55] [INFO]   |-- model: nvidia/gliner-pii

[15:32:55] [INFO]   |-- tokens: input=4184, output=12222, total=16406, tps=56

[15:32:55] [INFO]   |-- requests: success=23, failed=0, total=23, rpm=4

[15:32:55] [INFO]   |--

[15:32:55] [INFO]   |-- model: openai/gpt-oss-120b

[15:32:55] [INFO]   |-- tokens: input=181391, output=103337, total=284728, tps=985

[15:32:55] [INFO]   |-- requests: success=47, failed=0, total=47, rpm=9

[15:32:55] [INFO] 📐 Measuring dataset column statistics:

[15:32:55] [INFO]   |-- 📝 column: '_raw_detected_entities'

[15:32:55] [INFO]   |-- 🔧 column: '_seed_entities'

[15:32:55] [INFO]   |-- 🔧 column: '_validation_candidates'

[15:32:55] [INFO]   |-- 🔧 column: '_validated_entities'

[15:32:55] [INFO]   |-- 🔧 column: '_seed_entities_json'

[15:32:55] [INFO]   |-- 🗂️ column: '_augmented_entities'

[15:32:55] [INFO]   |-- 🔧 column: '_merged_entities'

[15:32:55] [INFO]   |-- 🔧 column: '_detected_entities'

[15:32:55] [DEBUG] NDD workflow 'entity-detection' returned 23 records

[15:32:55] [DEBUG] NDD workflow 'latent-entity-detection' starting with 23 records

[15:32:55] [DEBUG] NDD workflow 'latent-entity-detection': 1 columns ['_latent_entities']

[15:32:55] [INFO] 🎨 Creating Data Designer dataset

[15:32:55] [INFO] ✅ Validation passed

[15:32:55] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:32:55] [INFO] 🩺 Running health checks for models...

[15:32:55] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:32:57] [INFO]   |-- ✅ Passed!

[15:32:57] [INFO] 📂 Dataset path '.anonymizer-artifacts/latent-entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/latent-entity-detection_03-31-2026_153257' instead.

[15:32:57] [INFO] ⏳ Processing batch 1 of 1

[15:32:57] [INFO] 🌱 Sampling 23 records from seed dataset

[15:32:57] [INFO]   |-- seed dataset size: 23 records

[15:32:57] [INFO]   |-- sampling strategy: ordered

[15:32:57] [INFO] 🗂️ llm-structured model config for column '_latent_entities'

[15:32:57] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:32:57] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:32:57] [INFO]   |-- model provider: 'nvidia'

[15:32:57] [INFO]   |-- inference parameters:

[15:32:57] [INFO]   |  |-- generation_type=chat-completion

[15:32:57] [INFO]   |  |-- max_parallel_requests=16

[15:32:57] [INFO]   |  |-- timeout=300

[15:32:57] [INFO]   |  |-- temperature=0.40

[15:32:57] [INFO]   |  |-- top_p=1.00

[15:32:57] [INFO]   |  |-- max_tokens=8192

[15:32:57] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers

[15:32:57] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress every 2 records

[15:33:09] [INFO]   |-- 🚶 llm-structured column '_latent_entities' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.17 rec/s, eta 125.1s

[15:33:14] [INFO]   |-- 🚶 llm-structured column '_latent_entities' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.23 rec/s, eta 81.0s

[15:33:16] [INFO]   |-- 🐴 llm-structured column '_latent_entities' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.31 rec/s, eta 55.1s

[15:33:17] [INFO]   |-- 🐴 llm-structured column '_latent_entities' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.39 rec/s, eta 38.7s

[15:33:19] [INFO]   |-- 🐴 llm-structured column '_latent_entities' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.44 rec/s, eta 29.4s

[15:33:21] [INFO]   |-- 🚗 llm-structured column '_latent_entities' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.49 rec/s, eta 22.6s

[15:33:22] [INFO]   |-- 🚗 llm-structured column '_latent_entities' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.56 rec/s, eta 16.2s

[15:33:27] [INFO]   |-- 🚗 llm-structured column '_latent_entities' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.53 rec/s, eta 13.3s

[15:33:28] [INFO]   |-- ✈️ llm-structured column '_latent_entities' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.58 rec/s, eta 8.6s

[15:33:31] [INFO]   |-- ✈️ llm-structured column '_latent_entities' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.59 rec/s, eta 5.1s

[15:33:37] [INFO]   |-- ✈️ llm-structured column '_latent_entities' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.55 rec/s, eta 1.8s

[15:33:50] [INFO]   |-- 🚀 llm-structured column '_latent_entities' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.43 rec/s, eta 0.0s

[15:33:50] [INFO] 📊 Model usage summary:

[15:33:50] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:33:50] [INFO]   |-- tokens: input=48759, output=108994, total=157753, tps=2934

[15:33:50] [INFO]   |-- requests: success=26, failed=0, total=26, rpm=29

[15:33:50] [INFO] 📐 Measuring dataset column statistics:

[15:33:50] [INFO]   |-- 🗂️ column: '_latent_entities'

[15:33:50] [DEBUG] NDD workflow 'latent-entity-detection' returned 23 records

[15:33:50] [INFO]   |-- 📋 Detection complete — 579 entities found across 23 records (2 failed) [345.5s]

[15:33:50] [INFO]   |-- labels: first_name=147, company_name=62, city=47, occupation=41, state=34, education_level=33, race_ethnicity=29, last_name=25, age=24, religious_belief=24, political_view=22, street_address=21, language=20, county=12, employment_status=10, date_of_birth=9, date=5, university_name=4, institution_name=3, school_name=2, project_name=1, organization_name=1, government_agency=1, gender=1, postcode=1

[15:33:50] [INFO] ✏️ Running rewrite pipeline

[15:33:50] [DEBUG] NDD workflow 'replace-map-generation' starting with 23 records

[15:33:50] [DEBUG] NDD workflow 'replace-map-generation': 1 columns ['_replacement_map']

[15:33:50] [INFO] 🎨 Creating Data Designer dataset

[15:33:50] [INFO] ✅ Validation passed

[15:33:50] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:33:50] [INFO] 🩺 Running health checks for models...

[15:33:50] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:33:51] [INFO]   |-- ✅ Passed!

[15:33:51] [INFO] 📂 Dataset path '.anonymizer-artifacts/replace-map-generation' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/replace-map-generation_03-31-2026_153351' instead.

[15:33:51] [INFO] ⏳ Processing batch 1 of 1

[15:33:51] [INFO] 🌱 Sampling 23 records from seed dataset

[15:33:51] [INFO]   |-- seed dataset size: 23 records

[15:33:51] [INFO]   |-- sampling strategy: ordered

[15:33:51] [INFO] 🗂️ llm-structured model config for column '_replacement_map'

[15:33:51] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:33:51] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:33:51] [INFO]   |-- model provider: 'nvidia'

[15:33:51] [INFO]   |-- inference parameters:

[15:33:51] [INFO]   |  |-- generation_type=chat-completion

[15:33:51] [INFO]   |  |-- max_parallel_requests=2

[15:33:51] [INFO]   |  |-- timeout=300

[15:33:51] [INFO]   |  |-- temperature=0.30

[15:33:51] [INFO]   |  |-- top_p=0.95

[15:33:51] [INFO]   |  |-- max_tokens=16384

[15:33:51] [INFO] ⚡️ Processing llm-structured column '_replacement_map' with 2 concurrent workers

[15:33:51] [INFO] ⏱️ llm-structured column '_replacement_map' will report progress every 2 records

[15:34:02] [INFO]   |-- 🌧️ llm-structured column '_replacement_map' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.18 rec/s, eta 114.4s

[15:34:10] [INFO]   |-- 🌧️ llm-structured column '_replacement_map' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.21 rec/s, eta 91.2s

[15:34:17] [INFO]   |-- 🌦️ llm-structured column '_replacement_map' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.23 rec/s, eta 74.4s

[15:34:27] [INFO]   |-- 🌦️ llm-structured column '_replacement_map' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.22 rec/s, eta 67.3s

[15:34:38] [INFO]   |-- 🌦️ llm-structured column '_replacement_map' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.21 rec/s, eta 60.7s

[15:34:47] [INFO]   |-- ⛅ llm-structured column '_replacement_map' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.21 rec/s, eta 51.2s

[15:34:55] [INFO]   |-- ⛅ llm-structured column '_replacement_map' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.22 rec/s, eta 41.3s

[15:35:05] [INFO]   |-- ⛅ llm-structured column '_replacement_map' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.22 rec/s, eta 32.2s

[15:35:14] [INFO]   |-- 🌤️ llm-structured column '_replacement_map' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.22 rec/s, eta 23.0s

[15:35:22] [INFO]   |-- 🌤️ llm-structured column '_replacement_map' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.22 rec/s, eta 13.7s

[15:35:30] [INFO]   |-- 🌤️ llm-structured column '_replacement_map' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.22 rec/s, eta 4.5s

[15:35:32] [INFO]   |-- ☀️ llm-structured column '_replacement_map' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.23 rec/s, eta 0.0s

[15:35:32] [INFO] 📊 Model usage summary:

[15:35:32] [INFO]   |-- model: openai/gpt-oss-120b

[15:35:32] [INFO]   |-- tokens: input=43004, output=44754, total=87758, tps=865

[15:35:32] [INFO]   |-- requests: success=23, failed=0, total=23, rpm=13

[15:35:32] [INFO] 📐 Measuring dataset column statistics:

[15:35:32] [INFO]   |-- 🗂️ column: '_replacement_map'

[15:35:32] [DEBUG] NDD workflow 'replace-map-generation' returned 23 records

[15:35:32] [DEBUG] Replacement map record 08e0bc93ea49595ea5d9cecdc30e2d34: requested=[('40', 'age'), ('Aria', 'first_name'), ('Bobby', 'first_name'), ('Christian Democrat', 'political_view'), ('Colorado', 'state'), ('Colorado Veterinary Clinic', 'company_name'), ('DVM', 'education_level'), ('Denver', 'city'), ('English', 'language'), ('Jefferson High', 'school_name'), ('Leo', 'first_name'), ('Maya', 'first_name'), ('Mexican', 'race_ethnicity'), ('University of Colorado Boulder', 'institution_name'), ('VCA Animal Hospital', 'company_name'), ('Watford', 'last_name'), ('veterinarian', 'occupation')] raw=[{'original': '40', 'label': 'age', 'synthetic': '45'}, {'original': 'Aria', 'label': 'first_name', 'synthetic': 'Nina'}, {'original': 'Bobby', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Christian Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Colorado', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Colorado Veterinary Clinic', 'label': 'company_name', 'synthetic': 'Willamette Veterinary Hospital'}, {'original': 'DVM', 'label': 'education_level', 'synthetic': 'M.S. in Animal Science'}, {'original': 'Denver', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jefferson High', 'label': 'school_name', 'synthetic': 'Riverdale High School'}, {'original': 'Leo', 'label': 'first_name', 'synthetic': 'Jasper'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Korean'}, {'original': 'University of Colorado Boulder', 'label': 'institution_name', 'synthetic': 'Oregon State University'}, {'original': 'VCA Animal Hospital', 'label': 'company_name', 'synthetic': 'Pacific Pet Clinic'}, {'original': 'Watford', 'label': 'last_name', 'synthetic': 'Kline'}, {'original': 'veterinarian', 'label': 'occupation', 'synthetic': 'animal health researcher'}] filtered=[{'original': '40', 'label': 'age', 'synthetic': '45'}, {'original': 'Aria', 'label': 'first_name', 'synthetic': 'Nina'}, {'original': 'Bobby', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Christian Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Colorado', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Colorado Veterinary Clinic', 'label': 'company_name', 'synthetic': 'Willamette Veterinary Hospital'}, {'original': 'DVM', 'label': 'education_level', 'synthetic': 'M.S. in Animal Science'}, {'original': 'Denver', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jefferson High', 'label': 'school_name', 'synthetic': 'Riverdale High School'}, {'original': 'Leo', 'label': 'first_name', 'synthetic': 'Jasper'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Korean'}, {'original': 'University of Colorado Boulder', 'label': 'institution_name', 'synthetic': 'Oregon State University'}, {'original': 'VCA Animal Hospital', 'label': 'company_name', 'synthetic': 'Pacific Pet Clinic'}, {'original': 'Watford', 'label': 'last_name', 'synthetic': 'Kline'}, {'original': 'veterinarian', 'label': 'occupation', 'synthetic': 'animal health researcher'}]

[15:35:32] [DEBUG] Replacement map record a280a834a8e6573eb1df009fd30503e1: requested=[('37', 'age'), ('Bell', 'last_name'), ('Edison', 'city'), ('Elena', 'first_name'), ('English', 'language'), ('Idilio', 'first_name'), ('Italian', 'race_ethnicity'), ('Lina', 'first_name'), ('Marco', 'first_name'), ('Maya', 'first_name'), ('NASA’s Goddard Space Flight Center', 'company_name'), ('New Jersey', 'state'), ('New\u202fJersey', 'state'), ('New\u202fYork', 'state'), ('November\u202f21,\u202f1988', 'date_of_birth'), ('PhD in astrophysics', 'education_level'), ('Princeton', 'city'), ('SpaceX’s research division', 'company_name'), ('Starlink telescope array', 'project_name'), ('West Roberts Drive', 'street_address'), ('Zara', 'first_name'), ('astronomer', 'occupation'), ('bachelor’s degree', 'education_level'), ('progressive', 'political_view'), ('retired', 'employment_status'), ('secular', 'religious_belief')] raw=[{'original': '37', 'label': 'age', 'synthetic': '38'}, {'original': 'Bell', 'label': 'last_name', 'synthetic': 'Hawthorne'}, {'original': 'Edison', 'label': 'city', 'synthetic': 'Fort Collins'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Claudia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Idilio', 'label': 'first_name', 'synthetic': 'Dario'}, {'original': 'Italian', 'label': 'race_ethnicity', 'synthetic': 'Greek'}, {'original': 'Lina', 'label': 'first_name', 'synthetic': 'Nina'}, {'original': 'Marco', 'label': 'first_name', 'synthetic': 'Gianni'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'NASA’s Goddard Space Flight Center', 'label': 'company_name', 'synthetic': 'European Space Agency’s European Space Research and Technology Centre'}, {'original': 'New Jersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fJersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fYork', 'label': 'state', 'synthetic': 'Utah'}, {'original': 'November\u202f21,\u202f1988', 'label': 'date_of_birth', 'synthetic': 'April\u202f10,\u202f1988'}, {'original': 'PhD in astrophysics', 'label': 'education_level', 'synthetic': 'master’s degree in planetary science'}, {'original': 'Princeton', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'SpaceX’s research division', 'label': 'company_name', 'synthetic': 'Blue Origin’s lunar development unit'}, {'original': 'Starlink telescope array', 'label': 'project_name', 'synthetic': 'LunarNet observation network'}, {'original': 'West Roberts Drive', 'label': 'street_address', 'synthetic': 'East Monroe Avenue'}, {'original': 'Zara', 'label': 'first_name', 'synthetic': 'Mila'}, {'original': 'astronomer', 'label': 'occupation', 'synthetic': 'planetary geologist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'centrist'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'semi‑retired'}, {'original': 'secular', 'label': 'religious_belief', 'synthetic': 'agnostic'}] filtered=[{'original': '37', 'label': 'age', 'synthetic': '38'}, {'original': 'Bell', 'label': 'last_name', 'synthetic': 'Hawthorne'}, {'original': 'Edison', 'label': 'city', 'synthetic': 'Fort Collins'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Claudia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Idilio', 'label': 'first_name', 'synthetic': 'Dario'}, {'original': 'Italian', 'label': 'race_ethnicity', 'synthetic': 'Greek'}, {'original': 'Lina', 'label': 'first_name', 'synthetic': 'Nina'}, {'original': 'Marco', 'label': 'first_name', 'synthetic': 'Gianni'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'NASA’s Goddard Space Flight Center', 'label': 'company_name', 'synthetic': 'European Space Agency’s European Space Research and Technology Centre'}, {'original': 'New Jersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fJersey', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New\u202fYork', 'label': 'state', 'synthetic': 'Utah'}, {'original': 'November\u202f21,\u202f1988', 'label': 'date_of_birth', 'synthetic': 'April\u202f10,\u202f1988'}, {'original': 'PhD in astrophysics', 'label': 'education_level', 'synthetic': 'master’s degree in planetary science'}, {'original': 'Princeton', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'SpaceX’s research division', 'label': 'company_name', 'synthetic': 'Blue Origin’s lunar development unit'}, {'original': 'Starlink telescope array', 'label': 'project_name', 'synthetic': 'LunarNet observation network'}, {'original': 'West Roberts Drive', 'label': 'street_address', 'synthetic': 'East Monroe Avenue'}, {'original': 'Zara', 'label': 'first_name', 'synthetic': 'Mila'}, {'original': 'astronomer', 'label': 'occupation', 'synthetic': 'planetary geologist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'centrist'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'semi‑retired'}, {'original': 'secular', 'label': 'religious_belief', 'synthetic': 'agnostic'}]

[15:35:32] [DEBUG] Replacement map record f73a93b8df4f5fa9aa8decab757b3851: requested=[('204\u202fBluegrass', 'street_address'), ('36', 'age'), ('4', 'age'), ('7', 'age'), ('Alex', 'first_name'), ('Allison', 'last_name'), ('BA', 'education_level'), ('Caucasian', 'race_ethnicity'), ('Clayton', 'city'), ('English', 'language'), ('Ethan', 'first_name'), ('Jodi', 'first_name'), ('Maya', 'first_name'), ('Methodist', 'religious_belief'), ('North\u202fCarolina', 'state'), ('Raleigh', 'city'), ('Southern\u202fPublishing', 'company_name'), ('Venture\u202fMedia', 'company_name'), ('copy chief', 'occupation'), ('editor', 'occupation'), ('moderate Democrat', 'political_view'), ('school counselor', 'occupation')] raw=[{'original': '204\u202fBluegrass', 'label': 'street_address', 'synthetic': '317\u202fMaple'}, {'original': '36', 'label': 'age', 'synthetic': '42'}, {'original': '4', 'label': 'age', 'synthetic': '5'}, {'original': '7', 'label': 'age', 'synthetic': '9'}, {'original': 'Alex', 'label': 'first_name', 'synthetic': 'Darren'}, {'original': 'Allison', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'BA', 'label': 'education_level', 'synthetic': 'BS'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Asian'}, {'original': 'Clayton', 'label': 'city', 'synthetic': 'Eugene'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Noah'}, {'original': 'Jodi', 'label': 'first_name', 'synthetic': 'Leah'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Lila'}, {'original': 'Methodist', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Southern\u202fPublishing', 'label': 'company_name', 'synthetic': 'Pacific Press'}, {'original': 'Venture\u202fMedia', 'label': 'company_name', 'synthetic': 'Summit Studios'}, {'original': 'copy chief', 'label': 'occupation', 'synthetic': 'project manager'}, {'original': 'editor', 'label': 'occupation', 'synthetic': 'graphic designer'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'independent'}, {'original': 'school counselor', 'label': 'occupation', 'synthetic': 'career advisor'}] filtered=[{'original': '204\u202fBluegrass', 'label': 'street_address', 'synthetic': '317\u202fMaple'}, {'original': '36', 'label': 'age', 'synthetic': '42'}, {'original': '4', 'label': 'age', 'synthetic': '5'}, {'original': '7', 'label': 'age', 'synthetic': '9'}, {'original': 'Alex', 'label': 'first_name', 'synthetic': 'Darren'}, {'original': 'Allison', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'BA', 'label': 'education_level', 'synthetic': 'BS'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Asian'}, {'original': 'Clayton', 'label': 'city', 'synthetic': 'Eugene'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Noah'}, {'original': 'Jodi', 'label': 'first_name', 'synthetic': 'Leah'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Lila'}, {'original': 'Methodist', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Southern\u202fPublishing', 'label': 'company_name', 'synthetic': 'Pacific Press'}, {'original': 'Venture\u202fMedia', 'label': 'company_name', 'synthetic': 'Summit Studios'}, {'original': 'copy chief', 'label': 'occupation', 'synthetic': 'project manager'}, {'original': 'editor', 'label': 'occupation', 'synthetic': 'graphic designer'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'independent'}, {'original': 'school counselor', 'label': 'occupation', 'synthetic': 'career advisor'}]

[15:35:32] [DEBUG] Replacement map record 62af6b74f83c5918bc0762dde5d5fecc: requested=[('69', 'age'), ('American Medical Response', 'company_name'), ('Chicago', 'city'), ('Christian', 'religious_belief'), ('Darien', 'city'), ('Democrat', 'political_view'), ('DuPage County', 'county'), ('EMT certification', 'education_level'), ('English', 'language'), ('Illinois', 'state'), ('Irish', 'race_ethnicity'), ('James', 'first_name'), ('Lifeline EMS', 'company_name'), ('Margaret', 'first_name'), ('Mills', 'last_name'), ('University of Illinois at Chicago', 'company_name'), ('paramedic', 'occupation'), ('senior crew member', 'occupation')] raw=[{'original': '69', 'label': 'age', 'synthetic': '74'}, {'original': 'American Medical Response', 'label': 'company_name', 'synthetic': 'Northern Health Transport'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Atlanta'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Darien', 'label': 'city', 'synthetic': 'Savannah'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Republican'}, {'original': 'DuPage County', 'label': 'county', 'synthetic': 'Fulton County'}, {'original': 'EMT certification', 'label': 'education_level', 'synthetic': 'advanced first aid diploma'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Illinois', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Japanese'}, {'original': 'James', 'label': 'first_name', 'synthetic': 'Samuel'}, {'original': 'Lifeline EMS', 'label': 'company_name', 'synthetic': 'Guardian Ambulance Services'}, {'original': 'Margaret', 'label': 'first_name', 'synthetic': 'Eleanor'}, {'original': 'Mills', 'label': 'last_name', 'synthetic': 'Bennett'}, {'original': 'University of Illinois at Chicago', 'label': 'company_name', 'synthetic': 'Georgia State University'}, {'original': 'paramedic', 'label': 'occupation', 'synthetic': 'firefighter'}, {'original': 'senior crew member', 'label': 'occupation', 'synthetic': 'lead rescue technician'}] filtered=[{'original': '69', 'label': 'age', 'synthetic': '74'}, {'original': 'American Medical Response', 'label': 'company_name', 'synthetic': 'Northern Health Transport'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Atlanta'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Darien', 'label': 'city', 'synthetic': 'Savannah'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Republican'}, {'original': 'DuPage County', 'label': 'county', 'synthetic': 'Fulton County'}, {'original': 'EMT certification', 'label': 'education_level', 'synthetic': 'advanced first aid diploma'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Illinois', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Japanese'}, {'original': 'James', 'label': 'first_name', 'synthetic': 'Samuel'}, {'original': 'Lifeline EMS', 'label': 'company_name', 'synthetic': 'Guardian Ambulance Services'}, {'original': 'Margaret', 'label': 'first_name', 'synthetic': 'Eleanor'}, {'original': 'Mills', 'label': 'last_name', 'synthetic': 'Bennett'}, {'original': 'University of Illinois at Chicago', 'label': 'company_name', 'synthetic': 'Georgia State University'}, {'original': 'paramedic', 'label': 'occupation', 'synthetic': 'firefighter'}, {'original': 'senior crew member', 'label': 'occupation', 'synthetic': 'lead rescue technician'}]

[15:35:32] [DEBUG] Replacement map record 1067912d4e555ed6813186743557a587: requested=[('21', 'age'), ('297 Tupelo Trail', 'street_address'), ('Baptist', 'religious_belief'), ('Burton', 'last_name'), ('Christian', 'religious_belief'), ('English', 'language'), ('Jenna', 'first_name'), ('Linda', 'first_name'), ('Mark', 'first_name'), ('May 12, 2004', 'date_of_birth'), ('Nancy', 'first_name'), ('Ogden', 'city'), ('Smith', 'last_name'), ('Target', 'company_name'), ('University of Utah', 'company_name'), ('Utah', 'state'), ('White', 'race_ethnicity'), ('cashier', 'occupation'), ('high school', 'education_level'), ('moderate', 'political_view')] raw=[{'original': '21', 'label': 'age', 'synthetic': '22'}, {'original': '297 Tupelo Trail', 'label': 'street_address', 'synthetic': '842 Pinecrest Lane'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Burton', 'label': 'last_name', 'synthetic': 'Hawkins'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jenna', 'label': 'first_name', 'synthetic': 'Olivia'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Susan'}, {'original': 'Mark', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'May 12, 2004', 'label': 'date_of_birth', 'synthetic': 'June 3, 2003'}, {'original': 'Nancy', 'label': 'first_name', 'synthetic': 'Claire'}, {'original': 'Ogden', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Smith', 'label': 'last_name', 'synthetic': 'Davis'}, {'original': 'Target', 'label': 'company_name', 'synthetic': "Macy's"}, {'original': 'University of Utah', 'label': 'company_name', 'synthetic': 'University of Colorado Boulder'}, {'original': 'Utah', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'White', 'label': 'race_ethnicity', 'synthetic': 'Hispanic'}, {'original': 'cashier', 'label': 'occupation', 'synthetic': 'warehouse worker'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'some college'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'independent'}] filtered=[{'original': '21', 'label': 'age', 'synthetic': '22'}, {'original': '297 Tupelo Trail', 'label': 'street_address', 'synthetic': '842 Pinecrest Lane'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Burton', 'label': 'last_name', 'synthetic': 'Hawkins'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Jenna', 'label': 'first_name', 'synthetic': 'Olivia'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Susan'}, {'original': 'Mark', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'May 12, 2004', 'label': 'date_of_birth', 'synthetic': 'June 3, 2003'}, {'original': 'Nancy', 'label': 'first_name', 'synthetic': 'Claire'}, {'original': 'Ogden', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Smith', 'label': 'last_name', 'synthetic': 'Davis'}, {'original': 'Target', 'label': 'company_name', 'synthetic': "Macy's"}, {'original': 'University of Utah', 'label': 'company_name', 'synthetic': 'University of Colorado Boulder'}, {'original': 'Utah', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'White', 'label': 'race_ethnicity', 'synthetic': 'Hispanic'}, {'original': 'cashier', 'label': 'occupation', 'synthetic': 'warehouse worker'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'some college'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'independent'}]

[15:35:32] [DEBUG] Replacement map record cf301989dce251afa932f6bff10c5698: requested=[('196 Route\u202f417', 'street_address'), ('33', 'age'), ('Cheryl', 'first_name'), ('Chicago', 'city'), ('Clarendon Hills', 'city'), ('DuPage County', 'county'), ('English', 'language'), ('Gray', 'last_name'), ('Illinois', 'state'), ('Irish American', 'race_ethnicity'), ('Linda', 'first_name'), ('Michael', 'first_name'), ('Robert', 'first_name'), ('atheist', 'religious_belief'), ('historian', 'occupation'), ('honors in History', 'education_level'), ('liberal', 'political_view'), ('research assistant', 'occupation')] raw=[{'original': '196 Route\u202f417', 'label': 'street_address', 'synthetic': '8420 Walnut St'}, {'original': '33', 'label': 'age', 'synthetic': '41'}, {'original': 'Cheryl', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Denver'}, {'original': 'Clarendon Hills', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'DuPage County', 'label': 'county', 'synthetic': 'Jefferson County'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Gray', 'label': 'last_name', 'synthetic': 'Hawkins'}, {'original': 'Illinois', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'Irish American', 'label': 'race_ethnicity', 'synthetic': 'Japanese American'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Robert', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'atheist', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'historian', 'label': 'occupation', 'synthetic': 'archaeologist'}, {'original': 'honors in History', 'label': 'education_level', 'synthetic': 'magna cum laude in Anthropology'}, {'original': 'liberal', 'label': 'political_view', 'synthetic': 'conservative'}, {'original': 'research assistant', 'label': 'occupation', 'synthetic': 'field technician'}] filtered=[{'original': '196 Route\u202f417', 'label': 'street_address', 'synthetic': '8420 Walnut St'}, {'original': '33', 'label': 'age', 'synthetic': '41'}, {'original': 'Cheryl', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Denver'}, {'original': 'Clarendon Hills', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'DuPage County', 'label': 'county', 'synthetic': 'Jefferson County'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Gray', 'label': 'last_name', 'synthetic': 'Hawkins'}, {'original': 'Illinois', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'Irish American', 'label': 'race_ethnicity', 'synthetic': 'Japanese American'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Robert', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'atheist', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'historian', 'label': 'occupation', 'synthetic': 'archaeologist'}, {'original': 'honors in History', 'label': 'education_level', 'synthetic': 'magna cum laude in Anthropology'}, {'original': 'liberal', 'label': 'political_view', 'synthetic': 'conservative'}, {'original': 'research assistant', 'label': 'occupation', 'synthetic': 'field technician'}]

[15:35:32] [DEBUG] Replacement map record bcd9305913065e0daeabd7b08e96037c: requested=[('267\u202fMamalahoa\u202fHwy', 'street_address'), ('52', 'age'), ('A24', 'company_name'), ('Apple', 'company_name'), ('BFA in Film Production', 'education_level'), ('California', 'state'), ('Catholic', 'religious_belief'), ('Columbia', 'city'), ('Diego', 'first_name'), ('English', 'language'), ('Harbor Light Pictures', 'company_name'), ('Lucia', 'first_name'), ('MFA', 'education_level'), ('Maya', 'first_name'), ('Mexican', 'race_ethnicity'), ('Netflix', 'company_name'), ('Oscar', 'first_name'), ('Paramount', 'company_name'), ('San Diego', 'city'), ('Spanish', 'language'), ('Sundance', 'city'), ('UCLA', 'company_name'), ('Valenzano', 'last_name'), ('directing commercials', 'occupation'), ('documentary producer', 'occupation'), ('film director', 'occupation'), ('progressive', 'political_view'), ('writers', 'occupation')] raw=[{'original': '267\u202fMamalahoa\u202fHwy', 'label': 'street_address', 'synthetic': '842\u202fCedar\u202fLane'}, {'original': '52', 'label': 'age', 'synthetic': '47'}, {'original': 'A24', 'label': 'company_name', 'synthetic': 'Nebula Studios'}, {'original': 'Apple', 'label': 'company_name', 'synthetic': 'Orion Tech'}, {'original': 'BFA in Film Production', 'label': 'education_level', 'synthetic': 'BA in Visual Arts'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Columbia', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Diego', 'label': 'first_name', 'synthetic': 'Mateo'}, {'original': 'English', 'label': 'language', 'synthetic': 'Mandarin'}, {'original': 'Harbor Light Pictures', 'label': 'company_name', 'synthetic': 'Harbor Dawn Films'}, {'original': 'Lucia', 'label': 'first_name', 'synthetic': 'Isabella'}, {'original': 'MFA', 'label': 'education_level', 'synthetic': 'MA in Creative Writing'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'Netflix', 'label': 'company_name', 'synthetic': 'Streamline Media'}, {'original': 'Oscar', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Paramount', 'label': 'company_name', 'synthetic': 'Crestview Pictures'}, {'original': 'San Diego', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'Sundance', 'label': 'city', 'synthetic': 'Telluride'}, {'original': 'UCLA', 'label': 'company_name', 'synthetic': 'Ridgeview University'}, {'original': 'Valenzano', 'label': 'last_name', 'synthetic': 'Ramos'}, {'original': 'directing commercials', 'label': 'occupation', 'synthetic': 'producing music videos'}, {'original': 'documentary producer', 'label': 'occupation', 'synthetic': 'news anchor'}, {'original': 'film director', 'label': 'occupation', 'synthetic': 'theater playwright'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'Democrat'}, {'original': 'writers', 'label': 'occupation', 'synthetic': 'screenplay editors'}] filtered=[{'original': '267\u202fMamalahoa\u202fHwy', 'label': 'street_address', 'synthetic': '842\u202fCedar\u202fLane'}, {'original': '52', 'label': 'age', 'synthetic': '47'}, {'original': 'A24', 'label': 'company_name', 'synthetic': 'Nebula Studios'}, {'original': 'Apple', 'label': 'company_name', 'synthetic': 'Orion Tech'}, {'original': 'BFA in Film Production', 'label': 'education_level', 'synthetic': 'BA in Visual Arts'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Columbia', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Diego', 'label': 'first_name', 'synthetic': 'Mateo'}, {'original': 'English', 'label': 'language', 'synthetic': 'Mandarin'}, {'original': 'Harbor Light Pictures', 'label': 'company_name', 'synthetic': 'Harbor Dawn Films'}, {'original': 'Lucia', 'label': 'first_name', 'synthetic': 'Isabella'}, {'original': 'MFA', 'label': 'education_level', 'synthetic': 'MA in Creative Writing'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'Netflix', 'label': 'company_name', 'synthetic': 'Streamline Media'}, {'original': 'Oscar', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Paramount', 'label': 'company_name', 'synthetic': 'Crestview Pictures'}, {'original': 'San Diego', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'Sundance', 'label': 'city', 'synthetic': 'Telluride'}, {'original': 'UCLA', 'label': 'company_name', 'synthetic': 'Ridgeview University'}, {'original': 'Valenzano', 'label': 'last_name', 'synthetic': 'Ramos'}, {'original': 'directing commercials', 'label': 'occupation', 'synthetic': 'producing music videos'}, {'original': 'documentary producer', 'label': 'occupation', 'synthetic': 'news anchor'}, {'original': 'film director', 'label': 'occupation', 'synthetic': 'theater playwright'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'Democrat'}, {'original': 'writers', 'label': 'occupation', 'synthetic': 'screenplay editors'}]

[15:35:32] [DEBUG] Replacement map record da2ff626e1f659788bba86e6327e111b: requested=[('13\u202fNE\u202fAztec\u202fBlvd', 'street_address'), ('2019', 'date'), ('33', 'age'), ('Darwin', 'first_name'), ('Elena', 'first_name'), ('English', 'language'), ('John', 'first_name'), ('LDS Builders', 'company_name'), ('Leo', 'first_name'), ('Maria', 'first_name'), ('Maya', 'first_name'), ('Mexican', 'race_ethnicity'), ('Mormon', 'religious_belief'), ('Mountain Timber', 'company_name'), ('Orem', 'city'), ('Santalucia', 'last_name'), ('Santalucia Woodworks', 'company_name'), ('Sara', 'first_name'), ('Spanish', 'language'), ('University of Utah', 'organization_name'), ('Utah', 'state'), ('Utah County', 'county'), ('associate’s degree', 'education_level'), ('carpenter', 'occupation'), ('electrician', 'occupation'), ('fiscally conservative', 'political_view'), ('landscaping business', 'company_name'), ('retired', 'employment_status')] raw=[{'original': '13\u202fNE\u202fAztec\u202fBlvd', 'label': 'street_address', 'synthetic': '27 SW River St'}, {'original': '2019', 'label': 'date', 'synthetic': '2021'}, {'original': '33', 'label': 'age', 'synthetic': '38'}, {'original': 'Darwin', 'label': 'first_name', 'synthetic': 'Diego'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'English', 'label': 'language', 'synthetic': 'German'}, {'original': 'John', 'label': 'first_name', 'synthetic': 'Carlos'}, {'original': 'LDS Builders', 'label': 'company_name', 'synthetic': 'Pioneer Construction'}, {'original': 'Leo', 'label': 'first_name', 'synthetic': 'Nico'}, {'original': 'Maria', 'label': 'first_name', 'synthetic': 'Lucia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Peruvian'}, {'original': 'Mormon', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Mountain Timber', 'label': 'company_name', 'synthetic': 'Riverstone Carpentry'}, {'original': 'Orem', 'label': 'city', 'synthetic': 'Boise'}, {'original': 'Santalucia', 'label': 'last_name', 'synthetic': 'Hernandez'}, {'original': 'Santalucia Woodworks', 'label': 'company_name', 'synthetic': 'Cedarbrook Studios'}, {'original': 'Sara', 'label': 'first_name', 'synthetic': 'Clara'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'University of Utah', 'label': 'organization_name', 'synthetic': 'University of Idaho'}, {'original': 'Utah', 'label': 'state', 'synthetic': 'Idaho'}, {'original': 'Utah County', 'label': 'county', 'synthetic': 'Ada County'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'bachelor’s degree'}, {'original': 'carpenter', 'label': 'occupation', 'synthetic': 'metal fabricator'}, {'original': 'electrician', 'label': 'occupation', 'synthetic': 'plumber'}, {'original': 'fiscally conservative', 'label': 'political_view', 'synthetic': 'socially liberal'}, {'original': 'landscaping business', 'label': 'company_name', 'synthetic': 'Greenfield Gardens'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'part-time'}] filtered=[{'original': '13\u202fNE\u202fAztec\u202fBlvd', 'label': 'street_address', 'synthetic': '27 SW River St'}, {'original': '2019', 'label': 'date', 'synthetic': '2021'}, {'original': '33', 'label': 'age', 'synthetic': '38'}, {'original': 'Darwin', 'label': 'first_name', 'synthetic': 'Diego'}, {'original': 'Elena', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'English', 'label': 'language', 'synthetic': 'German'}, {'original': 'John', 'label': 'first_name', 'synthetic': 'Carlos'}, {'original': 'LDS Builders', 'label': 'company_name', 'synthetic': 'Pioneer Construction'}, {'original': 'Leo', 'label': 'first_name', 'synthetic': 'Nico'}, {'original': 'Maria', 'label': 'first_name', 'synthetic': 'Lucia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Peruvian'}, {'original': 'Mormon', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Mountain Timber', 'label': 'company_name', 'synthetic': 'Riverstone Carpentry'}, {'original': 'Orem', 'label': 'city', 'synthetic': 'Boise'}, {'original': 'Santalucia', 'label': 'last_name', 'synthetic': 'Hernandez'}, {'original': 'Santalucia Woodworks', 'label': 'company_name', 'synthetic': 'Cedarbrook Studios'}, {'original': 'Sara', 'label': 'first_name', 'synthetic': 'Clara'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'University of Utah', 'label': 'organization_name', 'synthetic': 'University of Idaho'}, {'original': 'Utah', 'label': 'state', 'synthetic': 'Idaho'}, {'original': 'Utah County', 'label': 'county', 'synthetic': 'Ada County'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'bachelor’s degree'}, {'original': 'carpenter', 'label': 'occupation', 'synthetic': 'metal fabricator'}, {'original': 'electrician', 'label': 'occupation', 'synthetic': 'plumber'}, {'original': 'fiscally conservative', 'label': 'political_view', 'synthetic': 'socially liberal'}, {'original': 'landscaping business', 'label': 'company_name', 'synthetic': 'Greenfield Gardens'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'part-time'}]

[15:35:32] [DEBUG] Replacement map record 2375392021275733a3439e727073b3c2: requested=[('2012', 'date'), ('43', 'age'), ('500\u202fE\u202fPurdue\u202fDr', 'street_address'), ('BA in History', 'education_level'), ('Bowdoin', 'company_name'), ('Catholic', 'religious_belief'), ('English', 'language'), ('Harbor Books', 'company_name'), ('Hasty', 'last_name'), ('Irish', 'race_ethnicity'), ('Jonah', 'first_name'), ('Kennebunkport', 'city'), ('Lily', 'first_name'), ('MLS', 'education_level'), ('Maya', 'first_name'), ('Portland Regional Library', 'company_name'), ('Richard', 'first_name'), ('Simmons College', 'company_name'), ('University of Maine', 'company_name'), ('York County', 'county'), ('moderate', 'political_view'), ('senior librarian', 'occupation'), ('state historic preservation office', 'government_agency')] raw=[{'original': '2012', 'label': 'date', 'synthetic': '2018'}, {'original': '43', 'label': 'age', 'synthetic': '51'}, {'original': '500\u202fE\u202fPurdue\u202fDr', 'label': 'street_address', 'synthetic': '742\u202fW\u202fElmwood\u202fAve'}, {'original': 'BA in History', 'label': 'education_level', 'synthetic': 'BS in Anthropology'}, {'original': 'Bowdoin', 'label': 'company_name', 'synthetic': 'Dartmouth'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Harbor Books', 'label': 'company_name', 'synthetic': 'Coastal Press'}, {'original': 'Hasty', 'label': 'last_name', 'synthetic': 'Merrick'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Italian'}, {'original': 'Jonah', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Kennebunkport', 'label': 'city', 'synthetic': 'Rockport'}, {'original': 'Lily', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'MLS', 'label': 'education_level', 'synthetic': 'M.Ed.'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Aisha'}, {'original': 'Portland Regional Library', 'label': 'company_name', 'synthetic': 'Seattle Public Library'}, {'original': 'Richard', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'Simmons College', 'label': 'company_name', 'synthetic': 'Boston University'}, {'original': 'University of Maine', 'label': 'company_name', 'synthetic': 'University of Vermont'}, {'original': 'York County', 'label': 'county', 'synthetic': 'Middlesex County'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'libertarian'}, {'original': 'senior librarian', 'label': 'occupation', 'synthetic': 'archival curator'}, {'original': 'state historic preservation office', 'label': 'government_agency', 'synthetic': 'state cultural resources department'}] filtered=[{'original': '2012', 'label': 'date', 'synthetic': '2018'}, {'original': '43', 'label': 'age', 'synthetic': '51'}, {'original': '500\u202fE\u202fPurdue\u202fDr', 'label': 'street_address', 'synthetic': '742\u202fW\u202fElmwood\u202fAve'}, {'original': 'BA in History', 'label': 'education_level', 'synthetic': 'BS in Anthropology'}, {'original': 'Bowdoin', 'label': 'company_name', 'synthetic': 'Dartmouth'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Harbor Books', 'label': 'company_name', 'synthetic': 'Coastal Press'}, {'original': 'Hasty', 'label': 'last_name', 'synthetic': 'Merrick'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Italian'}, {'original': 'Jonah', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'Kennebunkport', 'label': 'city', 'synthetic': 'Rockport'}, {'original': 'Lily', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'MLS', 'label': 'education_level', 'synthetic': 'M.Ed.'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Aisha'}, {'original': 'Portland Regional Library', 'label': 'company_name', 'synthetic': 'Seattle Public Library'}, {'original': 'Richard', 'label': 'first_name', 'synthetic': 'Thomas'}, {'original': 'Simmons College', 'label': 'company_name', 'synthetic': 'Boston University'}, {'original': 'University of Maine', 'label': 'company_name', 'synthetic': 'University of Vermont'}, {'original': 'York County', 'label': 'county', 'synthetic': 'Middlesex County'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'libertarian'}, {'original': 'senior librarian', 'label': 'occupation', 'synthetic': 'archival curator'}, {'original': 'state historic preservation office', 'label': 'government_agency', 'synthetic': 'state cultural resources department'}]

[15:35:32] [DEBUG] Replacement map record 434cdb7884c052cfae3df7218a91fcce: requested=[('2001', 'date_of_birth'), ('25', 'age'), ('481 SW 134\u202fSt.', 'street_address'), ('California', 'state'), ('Carlos', 'first_name'), ('Catholic', 'religious_belief'), ('English', 'language'), ('Gulf Coast Construction', 'company_name'), ('Long Beach', 'city'), ('Long Beach City College', 'school_name'), ('Luis', 'first_name'), ('Maya', 'first_name'), ('Mexican', 'race_ethnicity'), ('Pacific Builders', 'company_name'), ('Rodriguez', 'last_name'), ('Yanely', 'first_name'), ('associate’s degree', 'education_level'), ('career certification', 'education_level'), ('construction worker', 'occupation'), ('contractor', 'employment_status'), ('high school', 'education_level'), ('in civil engineering technology', 'education_level'), ('moderate Democrat', 'political_view')] raw=[{'original': '2001', 'label': 'date_of_birth', 'synthetic': '1998'}, {'original': '25', 'label': 'age', 'synthetic': '28'}, {'original': '481 SW 134\u202fSt.', 'label': 'street_address', 'synthetic': '742 NW 15th Ave.'}, {'original': 'California', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Carlos', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Gulf Coast Construction', 'label': 'company_name', 'synthetic': 'Summit Ridge Development'}, {'original': 'Long Beach', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Long Beach City College', 'label': 'school_name', 'synthetic': 'Portland Community College'}, {'original': 'Luis', 'label': 'first_name', 'synthetic': 'Diego'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'Pacific Builders', 'label': 'company_name', 'synthetic': 'Harborline Projects'}, {'original': 'Rodriguez', 'label': 'last_name', 'synthetic': 'Sanchez'}, {'original': 'Yanely', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'technical diploma'}, {'original': 'career certification', 'label': 'education_level', 'synthetic': 'professional license'}, {'original': 'construction worker', 'label': 'occupation', 'synthetic': 'electrician'}, {'original': 'contractor', 'label': 'employment_status', 'synthetic': 'full-time'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'middle school'}, {'original': 'in civil engineering technology', 'label': 'education_level', 'synthetic': 'in environmental design'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'centrist Independent'}] filtered=[{'original': '2001', 'label': 'date_of_birth', 'synthetic': '1998'}, {'original': '25', 'label': 'age', 'synthetic': '28'}, {'original': '481 SW 134\u202fSt.', 'label': 'street_address', 'synthetic': '742 NW 15th Ave.'}, {'original': 'California', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Carlos', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Gulf Coast Construction', 'label': 'company_name', 'synthetic': 'Summit Ridge Development'}, {'original': 'Long Beach', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Long Beach City College', 'label': 'school_name', 'synthetic': 'Portland Community College'}, {'original': 'Luis', 'label': 'first_name', 'synthetic': 'Diego'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'Mexican', 'label': 'race_ethnicity', 'synthetic': 'Filipino'}, {'original': 'Pacific Builders', 'label': 'company_name', 'synthetic': 'Harborline Projects'}, {'original': 'Rodriguez', 'label': 'last_name', 'synthetic': 'Sanchez'}, {'original': 'Yanely', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'technical diploma'}, {'original': 'career certification', 'label': 'education_level', 'synthetic': 'professional license'}, {'original': 'construction worker', 'label': 'occupation', 'synthetic': 'electrician'}, {'original': 'contractor', 'label': 'employment_status', 'synthetic': 'full-time'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'middle school'}, {'original': 'in civil engineering technology', 'label': 'education_level', 'synthetic': 'in environmental design'}, {'original': 'moderate Democrat', 'label': 'political_view', 'synthetic': 'centrist Independent'}]

[15:35:32] [DEBUG] Replacement map record e81d96e2f9d95cb8ab71c44eb72a09fe: requested=[('2022', 'date'), ('39', 'age'), ('Bradley', 'first_name'), ('Deloitte', 'company_name'), ('Democrat', 'political_view'), ('Durham', 'city'), ('English', 'language'), ('Irish', 'race_ethnicity'), ('Jenna', 'first_name'), ('Kelly', 'last_name'), ('Maya', 'first_name'), ('North Carolina', 'state'), ('October\u202f29, 1986', 'date_of_birth'), ('Ph.D.', 'education_level'), ('Stanford', 'city'), ('agnostic', 'religious_belief'), ('bachelor’s degree', 'education_level'), ('economist', 'occupation'), ('senior economist', 'occupation')] raw=[{'original': '2022', 'label': 'date', 'synthetic': '2023'}, {'original': '39', 'label': 'age', 'synthetic': '42'}, {'original': 'Bradley', 'label': 'first_name', 'synthetic': 'Dominic'}, {'original': 'Deloitte', 'label': 'company_name', 'synthetic': 'GreenTech Solutions'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Durham', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Japanese'}, {'original': 'Jenna', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Kelly', 'label': 'last_name', 'synthetic': 'Hawthorne'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leila'}, {'original': 'North Carolina', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'October\u202f29, 1986', 'label': 'date_of_birth', 'synthetic': 'May\u202f5, 1984'}, {'original': 'Ph.D.', 'label': 'education_level', 'synthetic': 'M.D.'}, {'original': 'Stanford', 'label': 'city', 'synthetic': 'Berkeley'}, {'original': 'agnostic', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'economist', 'label': 'occupation', 'synthetic': 'urban planner'}, {'original': 'senior economist', 'label': 'occupation', 'synthetic': 'lead urban planner'}] filtered=[{'original': '2022', 'label': 'date', 'synthetic': '2023'}, {'original': '39', 'label': 'age', 'synthetic': '42'}, {'original': 'Bradley', 'label': 'first_name', 'synthetic': 'Dominic'}, {'original': 'Deloitte', 'label': 'company_name', 'synthetic': 'GreenTech Solutions'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Durham', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Irish', 'label': 'race_ethnicity', 'synthetic': 'Japanese'}, {'original': 'Jenna', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Kelly', 'label': 'last_name', 'synthetic': 'Hawthorne'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leila'}, {'original': 'North Carolina', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'October\u202f29, 1986', 'label': 'date_of_birth', 'synthetic': 'May\u202f5, 1984'}, {'original': 'Ph.D.', 'label': 'education_level', 'synthetic': 'M.D.'}, {'original': 'Stanford', 'label': 'city', 'synthetic': 'Berkeley'}, {'original': 'agnostic', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'economist', 'label': 'occupation', 'synthetic': 'urban planner'}, {'original': 'senior economist', 'label': 'occupation', 'synthetic': 'lead urban planner'}]

[15:35:32] [DEBUG] Replacement map record 7df562c64e055b0e9f37562d4a4d6660: requested=[('35', 'age'), ('August\u202f9,\u202f1990', 'date_of_birth'), ('Baptist', 'religious_belief'), ('Breton\u202fBlvd', 'street_address'), ('Caucasian', 'race_ethnicity'), ('David', 'first_name'), ('English', 'language'), ('Ethan', 'first_name'), ('Harrell', 'last_name'), ('Lincoln', 'city'), ('Lincoln Electric', 'company_name'), ('Mia', 'first_name'), ('Midwest Power Services', 'company_name'), ('Nebraska', 'state'), ('Sarah', 'first_name'), ('University of Nebraska–Lincoln', 'institution_name'), ('contractor', 'employment_status'), ('degree in electrical engineering technology', 'education_level'), ('electrician', 'occupation'), ('moderate', 'political_view'), ('nurse', 'occupation')] raw=[{'original': '35', 'label': 'age', 'synthetic': '37'}, {'original': 'August\u202f9,\u202f1990', 'label': 'date_of_birth', 'synthetic': 'June\u202f12,\u202f1988'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Breton\u202fBlvd', 'label': 'street_address', 'synthetic': 'Maple St'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Hispanic'}, {'original': 'David', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Noah'}, {'original': 'Harrell', 'label': 'last_name', 'synthetic': 'Klein'}, {'original': 'Lincoln', 'label': 'city', 'synthetic': 'Madison'}, {'original': 'Lincoln Electric', 'label': 'company_name', 'synthetic': 'Midwest Electric Co.'}, {'original': 'Mia', 'label': 'first_name', 'synthetic': 'Olivia'}, {'original': 'Midwest Power Services', 'label': 'company_name', 'synthetic': 'Great Lakes Power Solutions'}, {'original': 'Nebraska', 'label': 'state', 'synthetic': 'Wisconsin'}, {'original': 'Sarah', 'label': 'first_name', 'synthetic': 'Emily'}, {'original': 'University of Nebraska–Lincoln', 'label': 'institution_name', 'synthetic': 'University of Wisconsin–Madison'}, {'original': 'contractor', 'label': 'employment_status', 'synthetic': 'freelance'}, {'original': 'degree in electrical engineering technology', 'label': 'education_level', 'synthetic': "associate's degree in mechanical engineering"}, {'original': 'electrician', 'label': 'occupation', 'synthetic': 'plumber'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'independent'}, {'original': 'nurse', 'label': 'occupation', 'synthetic': 'physical therapist'}] filtered=[{'original': '35', 'label': 'age', 'synthetic': '37'}, {'original': 'August\u202f9,\u202f1990', 'label': 'date_of_birth', 'synthetic': 'June\u202f12,\u202f1988'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Breton\u202fBlvd', 'label': 'street_address', 'synthetic': 'Maple St'}, {'original': 'Caucasian', 'label': 'race_ethnicity', 'synthetic': 'Hispanic'}, {'original': 'David', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Ethan', 'label': 'first_name', 'synthetic': 'Noah'}, {'original': 'Harrell', 'label': 'last_name', 'synthetic': 'Klein'}, {'original': 'Lincoln', 'label': 'city', 'synthetic': 'Madison'}, {'original': 'Lincoln Electric', 'label': 'company_name', 'synthetic': 'Midwest Electric Co.'}, {'original': 'Mia', 'label': 'first_name', 'synthetic': 'Olivia'}, {'original': 'Midwest Power Services', 'label': 'company_name', 'synthetic': 'Great Lakes Power Solutions'}, {'original': 'Nebraska', 'label': 'state', 'synthetic': 'Wisconsin'}, {'original': 'Sarah', 'label': 'first_name', 'synthetic': 'Emily'}, {'original': 'University of Nebraska–Lincoln', 'label': 'institution_name', 'synthetic': 'University of Wisconsin–Madison'}, {'original': 'contractor', 'label': 'employment_status', 'synthetic': 'freelance'}, {'original': 'degree in electrical engineering technology', 'label': 'education_level', 'synthetic': "associate's degree in mechanical engineering"}, {'original': 'electrician', 'label': 'occupation', 'synthetic': 'plumber'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'independent'}, {'original': 'nurse', 'label': 'occupation', 'synthetic': 'physical therapist'}]

[15:35:32] [DEBUG] Replacement map record 03b6aa0e64b7538dad673132b5fe23c6: requested=[('14th\u202fSt\u202fW', 'street_address'), ('42', 'age'), ('Aaron', 'first_name'), ('African', 'race_ethnicity'), ('Blue Ridge Analytics', 'company_name'), ('Christian', 'religious_belief'), ('December\u202f12, 1983', 'date_of_birth'), ('Dick', 'last_name'), ('English', 'language'), ('Honeoye Falls', 'city'), ('Kyndra', 'first_name'), ('Maya', 'first_name'), ('Michael', 'first_name'), ('New York', 'state'), ('New York State Department of Health', 'company_name'), ('Nexis Corp', 'company_name'), ('Rochester', 'city'), ('University of Rochester', 'company_name'), ('data analyst', 'occupation'), ('degree in statistics', 'education_level'), ('politically moderate', 'political_view')] raw=[{'original': '14th\u202fSt\u202fW', 'label': 'street_address', 'synthetic': '22nd\u202fAve\u202fN'}, {'original': '42', 'label': 'age', 'synthetic': '38'}, {'original': 'Aaron', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'African', 'label': 'race_ethnicity', 'synthetic': 'Latino'}, {'original': 'Blue Ridge Analytics', 'label': 'company_name', 'synthetic': 'Summit Data Solutions'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'December\u202f12, 1983', 'label': 'date_of_birth', 'synthetic': 'July\u202f9, 1988'}, {'original': 'Dick', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Honeoye Falls', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Kyndra', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leah'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'David'}, {'original': 'New York', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New York State Department of Health', 'label': 'company_name', 'synthetic': 'Colorado Department of Public Health'}, {'original': 'Nexis Corp', 'label': 'company_name', 'synthetic': 'Pinnacle FinTech'}, {'original': 'Rochester', 'label': 'city', 'synthetic': 'Fort\u202fCollins'}, {'original': 'University of Rochester', 'label': 'company_name', 'synthetic': 'University of Colorado Boulder'}, {'original': 'data analyst', 'label': 'occupation', 'synthetic': 'market researcher'}, {'original': 'degree in statistics', 'label': 'education_level', 'synthetic': 'certificate in data science'}, {'original': 'politically moderate', 'label': 'political_view', 'synthetic': 'conservative'}] filtered=[{'original': '14th\u202fSt\u202fW', 'label': 'street_address', 'synthetic': '22nd\u202fAve\u202fN'}, {'original': '42', 'label': 'age', 'synthetic': '38'}, {'original': 'Aaron', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'African', 'label': 'race_ethnicity', 'synthetic': 'Latino'}, {'original': 'Blue Ridge Analytics', 'label': 'company_name', 'synthetic': 'Summit Data Solutions'}, {'original': 'Christian', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'December\u202f12, 1983', 'label': 'date_of_birth', 'synthetic': 'July\u202f9, 1988'}, {'original': 'Dick', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Honeoye Falls', 'label': 'city', 'synthetic': 'Boulder'}, {'original': 'Kyndra', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leah'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'David'}, {'original': 'New York', 'label': 'state', 'synthetic': 'Colorado'}, {'original': 'New York State Department of Health', 'label': 'company_name', 'synthetic': 'Colorado Department of Public Health'}, {'original': 'Nexis Corp', 'label': 'company_name', 'synthetic': 'Pinnacle FinTech'}, {'original': 'Rochester', 'label': 'city', 'synthetic': 'Fort\u202fCollins'}, {'original': 'University of Rochester', 'label': 'company_name', 'synthetic': 'University of Colorado Boulder'}, {'original': 'data analyst', 'label': 'occupation', 'synthetic': 'market researcher'}, {'original': 'degree in statistics', 'label': 'education_level', 'synthetic': 'certificate in data science'}, {'original': 'politically moderate', 'label': 'political_view', 'synthetic': 'conservative'}]

[15:35:32] [DEBUG] Replacement map record 877010def757546a931b03d8c6859dce: requested=[('61', 'age'), ('7 Mounds Rd', 'street_address'), ('B.S.', 'education_level'), ('Chicago', 'city'), ('Christian church', 'religious_belief'), ('Coopersburg', 'city'), ('Emily', 'first_name'), ('English', 'language'), ('IBM', 'company_name'), ('Irish American', 'race_ethnicity'), ('Linda', 'first_name'), ('London', 'city'), ('Meridian Data Solutions', 'company_name'), ('Michael', 'first_name'), ('Penn State', 'university_name'), ('Pennsylvania', 'state'), ('Pfizer', 'company_name'), ('Ph.D. in statistics', 'education_level'), ('Shane', 'first_name'), ('University of Pennsylvania', 'university_name'), ('Wile', 'last_name'), ('engineer', 'occupation'), ('moderate', 'political_view'), ('statistician', 'occupation'), ('teacher', 'occupation')] raw=[{'original': '61', 'label': 'age', 'synthetic': '58'}, {'original': '7 Mounds Rd', 'label': 'street_address', 'synthetic': '12 Oak Lane'}, {'original': 'B.S.', 'label': 'education_level', 'synthetic': 'B.A.'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Denver'}, {'original': 'Christian church', 'label': 'religious_belief', 'synthetic': 'Buddhist temple'}, {'original': 'Coopersburg', 'label': 'city', 'synthetic': 'Cincinnati'}, {'original': 'Emily', 'label': 'first_name', 'synthetic': 'Sophia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'IBM', 'label': 'company_name', 'synthetic': 'QuantumSoft'}, {'original': 'Irish American', 'label': 'race_ethnicity', 'synthetic': 'Japanese American'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Karen'}, {'original': 'London', 'label': 'city', 'synthetic': 'Sydney'}, {'original': 'Meridian Data Solutions', 'label': 'company_name', 'synthetic': 'Summit Health Analytics'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Daniel'}, {'original': 'Penn State', 'label': 'university_name', 'synthetic': 'Ohio State University'}, {'original': 'Pennsylvania', 'label': 'state', 'synthetic': 'Ohio'}, {'original': 'Pfizer', 'label': 'company_name', 'synthetic': 'GreenTech Energy'}, {'original': 'Ph.D. in statistics', 'label': 'education_level', 'synthetic': 'Ph.D. in epidemiology'}, {'original': 'Shane', 'label': 'first_name', 'synthetic': 'Victor'}, {'original': 'University of Pennsylvania', 'label': 'university_name', 'synthetic': 'University of Michigan'}, {'original': 'Wile', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'engineer', 'label': 'occupation', 'synthetic': 'architect'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'statistician', 'label': 'occupation', 'synthetic': 'urban planner'}, {'original': 'teacher', 'label': 'occupation', 'synthetic': 'librarian'}] filtered=[{'original': '61', 'label': 'age', 'synthetic': '58'}, {'original': '7 Mounds Rd', 'label': 'street_address', 'synthetic': '12 Oak Lane'}, {'original': 'B.S.', 'label': 'education_level', 'synthetic': 'B.A.'}, {'original': 'Chicago', 'label': 'city', 'synthetic': 'Denver'}, {'original': 'Christian church', 'label': 'religious_belief', 'synthetic': 'Buddhist temple'}, {'original': 'Coopersburg', 'label': 'city', 'synthetic': 'Cincinnati'}, {'original': 'Emily', 'label': 'first_name', 'synthetic': 'Sophia'}, {'original': 'English', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'IBM', 'label': 'company_name', 'synthetic': 'QuantumSoft'}, {'original': 'Irish American', 'label': 'race_ethnicity', 'synthetic': 'Japanese American'}, {'original': 'Linda', 'label': 'first_name', 'synthetic': 'Karen'}, {'original': 'London', 'label': 'city', 'synthetic': 'Sydney'}, {'original': 'Meridian Data Solutions', 'label': 'company_name', 'synthetic': 'Summit Health Analytics'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Daniel'}, {'original': 'Penn State', 'label': 'university_name', 'synthetic': 'Ohio State University'}, {'original': 'Pennsylvania', 'label': 'state', 'synthetic': 'Ohio'}, {'original': 'Pfizer', 'label': 'company_name', 'synthetic': 'GreenTech Energy'}, {'original': 'Ph.D. in statistics', 'label': 'education_level', 'synthetic': 'Ph.D. in epidemiology'}, {'original': 'Shane', 'label': 'first_name', 'synthetic': 'Victor'}, {'original': 'University of Pennsylvania', 'label': 'university_name', 'synthetic': 'University of Michigan'}, {'original': 'Wile', 'label': 'last_name', 'synthetic': 'Harper'}, {'original': 'engineer', 'label': 'occupation', 'synthetic': 'architect'}, {'original': 'moderate', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'statistician', 'label': 'occupation', 'synthetic': 'urban planner'}, {'original': 'teacher', 'label': 'occupation', 'synthetic': 'librarian'}]

[15:35:32] [DEBUG] Replacement map record c5f6a9031e3552bea5813793f0386321: requested=[('1986', 'date'), ('57', 'age'), ('68 Bliss\u202fCir', 'street_address'), ('Aiyanna', 'first_name'), ('Alabama', 'state'), ('Alabama Fire Protection Services', 'company_name'), ('Cherokee', 'race_ethnicity'), ('Cherokee Cultural Center', 'company_name'), ('Fosters', 'city'), ('Greene County', 'county'), ('Greene County Fire Department', 'company_name'), ('Lila', 'first_name'), ('Michael', 'first_name'), ('November\u202f30,\u202f1968', 'date_of_birth'), ('Protestant', 'religious_belief'), ('Redbird', 'last_name'), ('Republican', 'political_view'), ('Tom', 'first_name'), ('University of Alabama', 'company_name'), ('degree in fire science', 'education_level'), ('firefighter', 'occupation'), ('senior firefighter', 'occupation')] raw=[{'original': '1986', 'label': 'date', 'synthetic': '1992'}, {'original': '57', 'label': 'age', 'synthetic': '62'}, {'original': '68 Bliss\u202fCir', 'label': 'street_address', 'synthetic': '742 Oakwood Ln'}, {'original': 'Aiyanna', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Alabama', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Alabama Fire Protection Services', 'label': 'company_name', 'synthetic': 'Georgia Fire Safety Solutions'}, {'original': 'Cherokee', 'label': 'race_ethnicity', 'synthetic': 'Navajo'}, {'original': 'Cherokee Cultural Center', 'label': 'company_name', 'synthetic': 'Macon Heritage Museum'}, {'original': 'Fosters', 'label': 'city', 'synthetic': 'Macon'}, {'original': 'Greene County', 'label': 'county', 'synthetic': 'Bibb County'}, {'original': 'Greene County Fire Department', 'label': 'company_name', 'synthetic': 'Bibb County Fire Rescue'}, {'original': 'Lila', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'November\u202f30,\u202f1968', 'label': 'date_of_birth', 'synthetic': 'April\u202f12,\u202f1964'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Redbird', 'label': 'last_name', 'synthetic': 'Stone'}, {'original': 'Republican', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Tom', 'label': 'first_name', 'synthetic': 'David'}, {'original': 'University of Alabama', 'label': 'company_name', 'synthetic': 'University of Georgia'}, {'original': 'degree in fire science', 'label': 'education_level', 'synthetic': "associate's degree in emergency management"}, {'original': 'firefighter', 'label': 'occupation', 'synthetic': 'paramedic'}, {'original': 'senior firefighter', 'label': 'occupation', 'synthetic': 'lead paramedic'}] filtered=[{'original': '1986', 'label': 'date', 'synthetic': '1992'}, {'original': '57', 'label': 'age', 'synthetic': '62'}, {'original': '68 Bliss\u202fCir', 'label': 'street_address', 'synthetic': '742 Oakwood Ln'}, {'original': 'Aiyanna', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Alabama', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Alabama Fire Protection Services', 'label': 'company_name', 'synthetic': 'Georgia Fire Safety Solutions'}, {'original': 'Cherokee', 'label': 'race_ethnicity', 'synthetic': 'Navajo'}, {'original': 'Cherokee Cultural Center', 'label': 'company_name', 'synthetic': 'Macon Heritage Museum'}, {'original': 'Fosters', 'label': 'city', 'synthetic': 'Macon'}, {'original': 'Greene County', 'label': 'county', 'synthetic': 'Bibb County'}, {'original': 'Greene County Fire Department', 'label': 'company_name', 'synthetic': 'Bibb County Fire Rescue'}, {'original': 'Lila', 'label': 'first_name', 'synthetic': 'Grace'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'November\u202f30,\u202f1968', 'label': 'date_of_birth', 'synthetic': 'April\u202f12,\u202f1964'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Redbird', 'label': 'last_name', 'synthetic': 'Stone'}, {'original': 'Republican', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'Tom', 'label': 'first_name', 'synthetic': 'David'}, {'original': 'University of Alabama', 'label': 'company_name', 'synthetic': 'University of Georgia'}, {'original': 'degree in fire science', 'label': 'education_level', 'synthetic': "associate's degree in emergency management"}, {'original': 'firefighter', 'label': 'occupation', 'synthetic': 'paramedic'}, {'original': 'senior firefighter', 'label': 'occupation', 'synthetic': 'lead paramedic'}]

[15:35:32] [DEBUG] Replacement map record 88a6de458b6056e794ad2ecc59b833f9: requested=[('24', 'age'), ('73 North Dent Avenue', 'street_address'), ('Bar', 'education_level'), ('Black Caribbean', 'race_ethnicity'), ('Bowling Green', 'city'), ('Caribbean', 'race_ethnicity'), ('Democrat', 'political_view'), ('Jade', 'first_name'), ('Juris Doctor', 'education_level'), ('Kentucky', 'state'), ('Malik', 'first_name'), ('Marsha', 'first_name'), ('Ohio', 'state'), ('Protestant', 'religious_belief'), ('Smith & Partners', 'company_name'), ('Williams', 'last_name'), ('Wood County', 'county'), ('attorney', 'occupation'), ("bachelor's degree", 'education_level'), ('public defender', 'occupation'), ('reggae', 'language')] raw=[{'original': '24', 'label': 'age', 'synthetic': '31'}, {'original': '73 North Dent Avenue', 'label': 'street_address', 'synthetic': '58 South Main Street'}, {'original': 'Bar', 'label': 'education_level', 'synthetic': 'state certification'}, {'original': 'Black Caribbean', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Bowling Green', 'label': 'city', 'synthetic': 'Grand Rapids'}, {'original': 'Caribbean', 'label': 'race_ethnicity', 'synthetic': 'Latin American'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Independent'}, {'original': 'Jade', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Juris Doctor', 'label': 'education_level', 'synthetic': 'Master of Public Policy'}, {'original': 'Kentucky', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Malik', 'label': 'first_name', 'synthetic': 'Ari'}, {'original': 'Marsha', 'label': 'first_name', 'synthetic': 'Gloria'}, {'original': 'Ohio', 'label': 'state', 'synthetic': 'Michigan'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'Smith & Partners', 'label': 'company_name', 'synthetic': 'Harper & Associates'}, {'original': 'Williams', 'label': 'last_name', 'synthetic': 'Hernandez'}, {'original': 'Wood County', 'label': 'county', 'synthetic': 'Oakland County'}, {'original': 'attorney', 'label': 'occupation', 'synthetic': 'policy analyst'}, {'original': "bachelor's degree", 'label': 'education_level', 'synthetic': "associate's degree"}, {'original': 'public defender', 'label': 'occupation', 'synthetic': 'civil rights advocate'}, {'original': 'reggae', 'label': 'language', 'synthetic': 'bossa nova'}] filtered=[{'original': '24', 'label': 'age', 'synthetic': '31'}, {'original': '73 North Dent Avenue', 'label': 'street_address', 'synthetic': '58 South Main Street'}, {'original': 'Bar', 'label': 'education_level', 'synthetic': 'state certification'}, {'original': 'Black Caribbean', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Bowling Green', 'label': 'city', 'synthetic': 'Grand Rapids'}, {'original': 'Caribbean', 'label': 'race_ethnicity', 'synthetic': 'Latin American'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Independent'}, {'original': 'Jade', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Juris Doctor', 'label': 'education_level', 'synthetic': 'Master of Public Policy'}, {'original': 'Kentucky', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Malik', 'label': 'first_name', 'synthetic': 'Ari'}, {'original': 'Marsha', 'label': 'first_name', 'synthetic': 'Gloria'}, {'original': 'Ohio', 'label': 'state', 'synthetic': 'Michigan'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'Smith & Partners', 'label': 'company_name', 'synthetic': 'Harper & Associates'}, {'original': 'Williams', 'label': 'last_name', 'synthetic': 'Hernandez'}, {'original': 'Wood County', 'label': 'county', 'synthetic': 'Oakland County'}, {'original': 'attorney', 'label': 'occupation', 'synthetic': 'policy analyst'}, {'original': "bachelor's degree", 'label': 'education_level', 'synthetic': "associate's degree"}, {'original': 'public defender', 'label': 'occupation', 'synthetic': 'civil rights advocate'}, {'original': 'reggae', 'label': 'language', 'synthetic': 'bossa nova'}]

[15:35:32] [DEBUG] Replacement map record f15e72bdafb1575fa010c30ded6a987e: requested=[('53 County Road N5578', 'street_address'), ('65', 'age'), ('Amir', 'last_name'), ('Coastal Custom Woodworks', 'company_name'), ('Collier County', 'county'), ('Everglades Carpentry', 'company_name'), ('Florida', 'state'), ('Gulf Coast Builders', 'company_name'), ('Iranian American', 'race_ethnicity'), ('Kian', 'first_name'), ('Laleh', 'first_name'), ('Muslim', 'religious_belief'), ('Naples', 'city'), ('Reza', 'first_name'), ('Sara', 'first_name'), ('Tehran', 'city'), ('University of Florida', 'university_name'), ('associate’s degree', 'education_level'), ('carpenter', 'occupation'), ('progressive', 'political_view')] raw=[{'original': '53 County Road N5578', 'label': 'street_address', 'synthetic': '2125 River Street SE'}, {'original': '65', 'label': 'age', 'synthetic': '58'}, {'original': 'Amir', 'label': 'last_name', 'synthetic': 'Rashidi'}, {'original': 'Coastal Custom Woodworks', 'label': 'company_name', 'synthetic': 'Harbor Artisan Studios'}, {'original': 'Collier County', 'label': 'county', 'synthetic': 'Chatham County'}, {'original': 'Everglades Carpentry', 'label': 'company_name', 'synthetic': 'Mangrove Joinery'}, {'original': 'Florida', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Gulf Coast Builders', 'label': 'company_name', 'synthetic': 'Sunset Bay Constructors'}, {'original': 'Iranian American', 'label': 'race_ethnicity', 'synthetic': 'Korean American'}, {'original': 'Kian', 'label': 'first_name', 'synthetic': 'Rashid'}, {'original': 'Laleh', 'label': 'first_name', 'synthetic': 'Mina'}, {'original': 'Muslim', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Naples', 'label': 'city', 'synthetic': 'Savannah'}, {'original': 'Reza', 'label': 'first_name', 'synthetic': 'Omar'}, {'original': 'Sara', 'label': 'first_name', 'synthetic': 'Leila'}, {'original': 'Tehran', 'label': 'city', 'synthetic': 'Seoul'}, {'original': 'University of Florida', 'label': 'university_name', 'synthetic': 'University of Georgia'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'bachelor’s degree'}, {'original': 'carpenter', 'label': 'occupation', 'synthetic': 'metalworker'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'Democrat'}] filtered=[{'original': '53 County Road N5578', 'label': 'street_address', 'synthetic': '2125 River Street SE'}, {'original': '65', 'label': 'age', 'synthetic': '58'}, {'original': 'Amir', 'label': 'last_name', 'synthetic': 'Rashidi'}, {'original': 'Coastal Custom Woodworks', 'label': 'company_name', 'synthetic': 'Harbor Artisan Studios'}, {'original': 'Collier County', 'label': 'county', 'synthetic': 'Chatham County'}, {'original': 'Everglades Carpentry', 'label': 'company_name', 'synthetic': 'Mangrove Joinery'}, {'original': 'Florida', 'label': 'state', 'synthetic': 'Georgia'}, {'original': 'Gulf Coast Builders', 'label': 'company_name', 'synthetic': 'Sunset Bay Constructors'}, {'original': 'Iranian American', 'label': 'race_ethnicity', 'synthetic': 'Korean American'}, {'original': 'Kian', 'label': 'first_name', 'synthetic': 'Rashid'}, {'original': 'Laleh', 'label': 'first_name', 'synthetic': 'Mina'}, {'original': 'Muslim', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Naples', 'label': 'city', 'synthetic': 'Savannah'}, {'original': 'Reza', 'label': 'first_name', 'synthetic': 'Omar'}, {'original': 'Sara', 'label': 'first_name', 'synthetic': 'Leila'}, {'original': 'Tehran', 'label': 'city', 'synthetic': 'Seoul'}, {'original': 'University of Florida', 'label': 'university_name', 'synthetic': 'University of Georgia'}, {'original': 'associate’s degree', 'label': 'education_level', 'synthetic': 'bachelor’s degree'}, {'original': 'carpenter', 'label': 'occupation', 'synthetic': 'metalworker'}, {'original': 'progressive', 'label': 'political_view', 'synthetic': 'Democrat'}]

[15:35:32] [DEBUG] Replacement map record cef9c0b785d952ca96f6bef61e7f49cb: requested=[('152 Caseys Ranch Road', 'street_address'), ('66', 'age'), ('Alem', 'last_name'), ('Bloomington', 'city'), ('Brown County', 'county'), ('Democrat', 'political_view'), ('Eastern Orthodox', 'religious_belief'), ('Ethiopian', 'race_ethnicity'), ('Freetown', 'city'), ('Hana', 'first_name'), ('Indiana', 'state'), ('Kofi', 'first_name'), ('Lule', 'first_name'), ('Mekonnen', 'first_name'), ('Michigan', 'state'), ('bachelor’s degree', 'education_level'), ('genderqueer', 'gender'), ('master’s', 'education_level'), ('teacher', 'occupation')] raw=[{'original': '152 Caseys Ranch Road', 'label': 'street_address', 'synthetic': '247 Harper Valley Drive'}, {'original': '66', 'label': 'age', 'synthetic': '58'}, {'original': 'Alem', 'label': 'last_name', 'synthetic': 'Khan'}, {'original': 'Bloomington', 'label': 'city', 'synthetic': 'Cincinnati'}, {'original': 'Brown County', 'label': 'county', 'synthetic': 'Franklin County'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Independent'}, {'original': 'Eastern Orthodox', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Ethiopian', 'label': 'race_ethnicity', 'synthetic': 'Kenyan'}, {'original': 'Freetown', 'label': 'city', 'synthetic': 'Dayton'}, {'original': 'Hana', 'label': 'first_name', 'synthetic': 'Maya'}, {'original': 'Indiana', 'label': 'state', 'synthetic': 'Ohio'}, {'original': 'Kofi', 'label': 'first_name', 'synthetic': 'Jabari'}, {'original': 'Lule', 'label': 'first_name', 'synthetic': 'Alemu'}, {'original': 'Mekonnen', 'label': 'first_name', 'synthetic': 'Sisay'}, {'original': 'Michigan', 'label': 'state', 'synthetic': 'Wisconsin'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'genderqueer', 'label': 'gender', 'synthetic': 'agender'}, {'original': 'master’s', 'label': 'education_level', 'synthetic': 'doctoral degree'}, {'original': 'teacher', 'label': 'occupation', 'synthetic': 'librarian'}] filtered=[{'original': '152 Caseys Ranch Road', 'label': 'street_address', 'synthetic': '247 Harper Valley Drive'}, {'original': '66', 'label': 'age', 'synthetic': '58'}, {'original': 'Alem', 'label': 'last_name', 'synthetic': 'Khan'}, {'original': 'Bloomington', 'label': 'city', 'synthetic': 'Cincinnati'}, {'original': 'Brown County', 'label': 'county', 'synthetic': 'Franklin County'}, {'original': 'Democrat', 'label': 'political_view', 'synthetic': 'Independent'}, {'original': 'Eastern Orthodox', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Ethiopian', 'label': 'race_ethnicity', 'synthetic': 'Kenyan'}, {'original': 'Freetown', 'label': 'city', 'synthetic': 'Dayton'}, {'original': 'Hana', 'label': 'first_name', 'synthetic': 'Maya'}, {'original': 'Indiana', 'label': 'state', 'synthetic': 'Ohio'}, {'original': 'Kofi', 'label': 'first_name', 'synthetic': 'Jabari'}, {'original': 'Lule', 'label': 'first_name', 'synthetic': 'Alemu'}, {'original': 'Mekonnen', 'label': 'first_name', 'synthetic': 'Sisay'}, {'original': 'Michigan', 'label': 'state', 'synthetic': 'Wisconsin'}, {'original': 'bachelor’s degree', 'label': 'education_level', 'synthetic': 'associate’s degree'}, {'original': 'genderqueer', 'label': 'gender', 'synthetic': 'agender'}, {'original': 'master’s', 'label': 'education_level', 'synthetic': 'doctoral degree'}, {'original': 'teacher', 'label': 'occupation', 'synthetic': 'librarian'}]

[15:35:32] [DEBUG] Replacement map record 0a952d80230256bb9af001a9d744ea0e: requested=[('248\u202fBeach\u202fLane', 'street_address'), ('57', 'age'), ('Anita', 'first_name'), ('Arjun', 'first_name'), ('Bachelor of Arts in Business', 'education_level'), ('California', 'state'), ('Coldwell\u202fBanker', 'company_name'), ('Hindu', 'religious_belief'), ('Indian', 'race_ethnicity'), ('Indian American', 'race_ethnicity'), ('Keller\u202fWilliams', 'company_name'), ('La\u202fMesa', 'city'), ('Maya', 'first_name'), ('Patel', 'last_name'), ('Raj', 'first_name'), ('Republican', 'political_view'), ('San\u202fDiego County', 'county'), ('San\u202fDiego\u202fState\u202fUniversity', 'university_name'), ('Southern California', 'state'), ('engineer', 'occupation'), ('real estate agent', 'occupation'), ('retired', 'employment_status')] raw=[{'original': '248\u202fBeach\u202fLane', 'label': 'street_address', 'synthetic': '742 Oak Street'}, {'original': '57', 'label': 'age', 'synthetic': '62'}, {'original': 'Anita', 'label': 'first_name', 'synthetic': 'Sunita'}, {'original': 'Arjun', 'label': 'first_name', 'synthetic': 'Kiran'}, {'original': 'Bachelor of Arts in Business', 'label': 'education_level', 'synthetic': 'Master of Science in Marketing'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Coldwell\u202fBanker', 'label': 'company_name', 'synthetic': 'Redfin'}, {'original': 'Hindu', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Indian', 'label': 'race_ethnicity', 'synthetic': 'Korean'}, {'original': 'Indian American', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Keller\u202fWilliams', 'label': 'company_name', 'synthetic': 'Compass'}, {'original': 'La\u202fMesa', 'label': 'city', 'synthetic': 'Plano'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leela'}, {'original': 'Patel', 'label': 'last_name', 'synthetic': 'Shah'}, {'original': 'Raj', 'label': 'first_name', 'synthetic': 'Vikram'}, {'original': 'Republican', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'San\u202fDiego County', 'label': 'county', 'synthetic': 'Collin County'}, {'original': 'San\u202fDiego\u202fState\u202fUniversity', 'label': 'university_name', 'synthetic': 'University of Texas at Dallas'}, {'original': 'Southern California', 'label': 'state', 'synthetic': 'North Texas'}, {'original': 'engineer', 'label': 'occupation', 'synthetic': 'architect'}, {'original': 'real estate agent', 'label': 'occupation', 'synthetic': 'mortgage broker'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'part-time'}] filtered=[{'original': '248\u202fBeach\u202fLane', 'label': 'street_address', 'synthetic': '742 Oak Street'}, {'original': '57', 'label': 'age', 'synthetic': '62'}, {'original': 'Anita', 'label': 'first_name', 'synthetic': 'Sunita'}, {'original': 'Arjun', 'label': 'first_name', 'synthetic': 'Kiran'}, {'original': 'Bachelor of Arts in Business', 'label': 'education_level', 'synthetic': 'Master of Science in Marketing'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Coldwell\u202fBanker', 'label': 'company_name', 'synthetic': 'Redfin'}, {'original': 'Hindu', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'Indian', 'label': 'race_ethnicity', 'synthetic': 'Korean'}, {'original': 'Indian American', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Keller\u202fWilliams', 'label': 'company_name', 'synthetic': 'Compass'}, {'original': 'La\u202fMesa', 'label': 'city', 'synthetic': 'Plano'}, {'original': 'Maya', 'label': 'first_name', 'synthetic': 'Leela'}, {'original': 'Patel', 'label': 'last_name', 'synthetic': 'Shah'}, {'original': 'Raj', 'label': 'first_name', 'synthetic': 'Vikram'}, {'original': 'Republican', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'San\u202fDiego County', 'label': 'county', 'synthetic': 'Collin County'}, {'original': 'San\u202fDiego\u202fState\u202fUniversity', 'label': 'university_name', 'synthetic': 'University of Texas at Dallas'}, {'original': 'Southern California', 'label': 'state', 'synthetic': 'North Texas'}, {'original': 'engineer', 'label': 'occupation', 'synthetic': 'architect'}, {'original': 'real estate agent', 'label': 'occupation', 'synthetic': 'mortgage broker'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'part-time'}]

[15:35:32] [DEBUG] Replacement map record e5b7b47e3bf55ba0af4d43c7fd6ad509: requested=[('157 Newell\u202fRd', 'street_address'), ('45', 'age'), ('American Translators Association', 'company_name'), ('Caldwell County', 'county'), ('Carlos', 'first_name'), ('Carmen', 'first_name'), ('Catholic', 'religious_belief'), ('Charlotte', 'city'), ('Colombian', 'race_ethnicity'), ('Diego', 'first_name'), ('English', 'language'), ('Global Voice\u202fInc.', 'company_name'), ('HarperCollins', 'company_name'), ('Isabel', 'first_name'), ('January\u202f24\u202f1981', 'date_of_birth'), ('Lenoir', 'city'), ('Martínez', 'last_name'), ('North Carolina', 'state'), ('North\u202fCarolina', 'state'), ('Raleigh', 'city'), ('South\u202fAmerican', 'race_ethnicity'), ('Spanish', 'language'), ('TransLingua Solutions', 'company_name'), ('conservative', 'political_view'), ('freelance', 'employment_status'), ('language tutor', 'occupation'), ('master’s', 'education_level'), ('translator', 'occupation')] raw=[{'original': '157 Newell\u202fRd', 'label': 'street_address', 'synthetic': '842 Oakwood St'}, {'original': '45', 'label': 'age', 'synthetic': '47'}, {'original': 'American Translators Association', 'label': 'company_name', 'synthetic': 'International Linguists Guild'}, {'original': 'Caldwell County', 'label': 'county', 'synthetic': 'Harris County'}, {'original': 'Carlos', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Carmen', 'label': 'first_name', 'synthetic': 'Lucia'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Baptist'}, {'original': 'Charlotte', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Colombian', 'label': 'race_ethnicity', 'synthetic': 'Mexican'}, {'original': 'Diego', 'label': 'first_name', 'synthetic': 'Mateo'}, {'original': 'English', 'label': 'language', 'synthetic': 'French'}, {'original': 'Global Voice\u202fInc.', 'label': 'company_name', 'synthetic': 'EchoSphere Corp'}, {'original': 'HarperCollins', 'label': 'company_name', 'synthetic': 'Penguin Random House'}, {'original': 'Isabel', 'label': 'first_name', 'synthetic': 'Mariana'}, {'original': 'January\u202f24\u202f1981', 'label': 'date_of_birth', 'synthetic': 'March\u202f12\u202f1979'}, {'original': 'Lenoir', 'label': 'city', 'synthetic': 'Laredo'}, {'original': 'Martínez', 'label': 'last_name', 'synthetic': 'Gómez'}, {'original': 'North Carolina', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Houston'}, {'original': 'South\u202fAmerican', 'label': 'race_ethnicity', 'synthetic': 'Caribbean'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'TransLingua Solutions', 'label': 'company_name', 'synthetic': 'Lexicon Dynamics'}, {'original': 'conservative', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'freelance', 'label': 'employment_status', 'synthetic': 'contract'}, {'original': 'language tutor', 'label': 'occupation', 'synthetic': 'ESL instructor'}, {'original': 'master’s', 'label': 'education_level', 'synthetic': 'doctorate'}, {'original': 'translator', 'label': 'occupation', 'synthetic': 'interpreter'}] filtered=[{'original': '157 Newell\u202fRd', 'label': 'street_address', 'synthetic': '842 Oakwood St'}, {'original': '45', 'label': 'age', 'synthetic': '47'}, {'original': 'American Translators Association', 'label': 'company_name', 'synthetic': 'International Linguists Guild'}, {'original': 'Caldwell County', 'label': 'county', 'synthetic': 'Harris County'}, {'original': 'Carlos', 'label': 'first_name', 'synthetic': 'Javier'}, {'original': 'Carmen', 'label': 'first_name', 'synthetic': 'Lucia'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Baptist'}, {'original': 'Charlotte', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Colombian', 'label': 'race_ethnicity', 'synthetic': 'Mexican'}, {'original': 'Diego', 'label': 'first_name', 'synthetic': 'Mateo'}, {'original': 'English', 'label': 'language', 'synthetic': 'French'}, {'original': 'Global Voice\u202fInc.', 'label': 'company_name', 'synthetic': 'EchoSphere Corp'}, {'original': 'HarperCollins', 'label': 'company_name', 'synthetic': 'Penguin Random House'}, {'original': 'Isabel', 'label': 'first_name', 'synthetic': 'Mariana'}, {'original': 'January\u202f24\u202f1981', 'label': 'date_of_birth', 'synthetic': 'March\u202f12\u202f1979'}, {'original': 'Lenoir', 'label': 'city', 'synthetic': 'Laredo'}, {'original': 'Martínez', 'label': 'last_name', 'synthetic': 'Gómez'}, {'original': 'North Carolina', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'North\u202fCarolina', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Raleigh', 'label': 'city', 'synthetic': 'Houston'}, {'original': 'South\u202fAmerican', 'label': 'race_ethnicity', 'synthetic': 'Caribbean'}, {'original': 'Spanish', 'label': 'language', 'synthetic': 'Portuguese'}, {'original': 'TransLingua Solutions', 'label': 'company_name', 'synthetic': 'Lexicon Dynamics'}, {'original': 'conservative', 'label': 'political_view', 'synthetic': 'Libertarian'}, {'original': 'freelance', 'label': 'employment_status', 'synthetic': 'contract'}, {'original': 'language tutor', 'label': 'occupation', 'synthetic': 'ESL instructor'}, {'original': 'master’s', 'label': 'education_level', 'synthetic': 'doctorate'}, {'original': 'translator', 'label': 'occupation', 'synthetic': 'interpreter'}]

[15:35:32] [DEBUG] Replacement map record 95633f1f804f56eda7b9fcb8e3877644: requested=[('174 Southside Dr', 'street_address'), ('5th Avenue', 'street_address'), ('62', 'age'), ('Arizona', 'state'), ('Baptist', 'religious_belief'), ('Carl', 'first_name'), ('Denise', 'first_name'), ('Desert Rose Bar', 'company_name'), ('Elixir Lounge', 'company_name'), ('James', 'first_name'), ('Johnson', 'last_name'), ('Mildred', 'first_name'), ('Protestant', 'religious_belief'), ('Sun Dial Bar', 'company_name'), ('Tucson', 'city'), ('University of Arizona', 'institution_name'), ('bartender', 'occupation'), ('high school', 'education_level'), ('off duty', 'employment_status')] raw=[{'original': '174 Southside Dr', 'label': 'street_address', 'synthetic': '182 Oakridge Ln'}, {'original': '5th Avenue', 'label': 'street_address', 'synthetic': '7th Street'}, {'original': '62', 'label': 'age', 'synthetic': '57'}, {'original': 'Arizona', 'label': 'state', 'synthetic': 'New Mexico'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Carl', 'label': 'first_name', 'synthetic': 'Harold'}, {'original': 'Denise', 'label': 'first_name', 'synthetic': 'Sylvia'}, {'original': 'Desert Rose Bar', 'label': 'company_name', 'synthetic': 'Cactus Bloom Pub'}, {'original': 'Elixir Lounge', 'label': 'company_name', 'synthetic': 'Nimbus Club'}, {'original': 'James', 'label': 'first_name', 'synthetic': 'Walter'}, {'original': 'Johnson', 'label': 'last_name', 'synthetic': 'Keller'}, {'original': 'Mildred', 'label': 'first_name', 'synthetic': 'Eleanor'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'Sun Dial Bar', 'label': 'company_name', 'synthetic': 'Moonrise Tavern'}, {'original': 'Tucson', 'label': 'city', 'synthetic': 'Albuquerque'}, {'original': 'University of Arizona', 'label': 'institution_name', 'synthetic': 'University of New Mexico'}, {'original': 'bartender', 'label': 'occupation', 'synthetic': 'wine steward'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'some college'}, {'original': 'off duty', 'label': 'employment_status', 'synthetic': 'on break'}] filtered=[{'original': '174 Southside Dr', 'label': 'street_address', 'synthetic': '182 Oakridge Ln'}, {'original': '5th Avenue', 'label': 'street_address', 'synthetic': '7th Street'}, {'original': '62', 'label': 'age', 'synthetic': '57'}, {'original': 'Arizona', 'label': 'state', 'synthetic': 'New Mexico'}, {'original': 'Baptist', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Carl', 'label': 'first_name', 'synthetic': 'Harold'}, {'original': 'Denise', 'label': 'first_name', 'synthetic': 'Sylvia'}, {'original': 'Desert Rose Bar', 'label': 'company_name', 'synthetic': 'Cactus Bloom Pub'}, {'original': 'Elixir Lounge', 'label': 'company_name', 'synthetic': 'Nimbus Club'}, {'original': 'James', 'label': 'first_name', 'synthetic': 'Walter'}, {'original': 'Johnson', 'label': 'last_name', 'synthetic': 'Keller'}, {'original': 'Mildred', 'label': 'first_name', 'synthetic': 'Eleanor'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Jewish'}, {'original': 'Sun Dial Bar', 'label': 'company_name', 'synthetic': 'Moonrise Tavern'}, {'original': 'Tucson', 'label': 'city', 'synthetic': 'Albuquerque'}, {'original': 'University of Arizona', 'label': 'institution_name', 'synthetic': 'University of New Mexico'}, {'original': 'bartender', 'label': 'occupation', 'synthetic': 'wine steward'}, {'original': 'high school', 'label': 'education_level', 'synthetic': 'some college'}, {'original': 'off duty', 'label': 'employment_status', 'synthetic': 'on break'}]

[15:35:32] [DEBUG] Replacement map record 78602caac5405dacadacc759a7a1b4f5: requested=[('189\u202fSlash\u202fPine\u202fCt', 'street_address'), ('95320', 'postcode'), ('Atsa', 'first_name'), ('CA', 'state'), ('Catholic', 'religious_belief'), ('Escalon', 'city'), ('John', 'first_name'), ('June\u202f3\u202f1953', 'date_of_birth'), ('Lily', 'first_name'), ('Michael', 'first_name'), ('Modesto', 'city'), ('Navajo', 'race_ethnicity'), ('San\u202fJoaquin County', 'county'), ('Sutter Medical Center', 'company_name'), ('Trinity Health', 'company_name'), ('University of California, Davis', 'company_name'), ('Yazzie', 'last_name'), ('Yuba City', 'city'), ('full', 'employment_status'), ('libertarian', 'political_view'), ('nurse', 'occupation'), ('part', 'employment_status'), ('retired', 'employment_status')] raw=[{'original': '189\u202fSlash\u202fPine\u202fCt', 'label': 'street_address', 'synthetic': '742 Willow Brook Ct'}, {'original': '95320', 'label': 'postcode', 'synthetic': '97401'}, {'original': 'Atsa', 'label': 'first_name', 'synthetic': 'Mira'}, {'original': 'CA', 'label': 'state', 'synthetic': 'OR'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Escalon', 'label': 'city', 'synthetic': 'Eugene'}, {'original': 'John', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'June\u202f3\u202f1953', 'label': 'date_of_birth', 'synthetic': 'April\u202f12\u202f1954'}, {'original': 'Lily', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Darius'}, {'original': 'Modesto', 'label': 'city', 'synthetic': 'Salem'}, {'original': 'Navajo', 'label': 'race_ethnicity', 'synthetic': 'Cherokee'}, {'original': 'San\u202fJoaquin County', 'label': 'county', 'synthetic': 'Lane County'}, {'original': 'Sutter Medical Center', 'label': 'company_name', 'synthetic': 'Riverbend Hospital'}, {'original': 'Trinity Health', 'label': 'company_name', 'synthetic': 'Harmony Care'}, {'original': 'University of California, Davis', 'label': 'company_name', 'synthetic': 'Pacific Northwest University'}, {'original': 'Yazzie', 'label': 'last_name', 'synthetic': 'Kaur'}, {'original': 'Yuba City', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'full', 'label': 'employment_status', 'synthetic': 'permanent'}, {'original': 'libertarian', 'label': 'political_view', 'synthetic': 'Conservative'}, {'original': 'nurse', 'label': 'occupation', 'synthetic': 'physical therapist'}, {'original': 'part', 'label': 'employment_status', 'synthetic': 'seasonal'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'emeritus'}] filtered=[{'original': '189\u202fSlash\u202fPine\u202fCt', 'label': 'street_address', 'synthetic': '742 Willow Brook Ct'}, {'original': '95320', 'label': 'postcode', 'synthetic': '97401'}, {'original': 'Atsa', 'label': 'first_name', 'synthetic': 'Mira'}, {'original': 'CA', 'label': 'state', 'synthetic': 'OR'}, {'original': 'Catholic', 'label': 'religious_belief', 'synthetic': 'Methodist'}, {'original': 'Escalon', 'label': 'city', 'synthetic': 'Eugene'}, {'original': 'John', 'label': 'first_name', 'synthetic': 'Ethan'}, {'original': 'June\u202f3\u202f1953', 'label': 'date_of_birth', 'synthetic': 'April\u202f12\u202f1954'}, {'original': 'Lily', 'label': 'first_name', 'synthetic': 'Sofia'}, {'original': 'Michael', 'label': 'first_name', 'synthetic': 'Darius'}, {'original': 'Modesto', 'label': 'city', 'synthetic': 'Salem'}, {'original': 'Navajo', 'label': 'race_ethnicity', 'synthetic': 'Cherokee'}, {'original': 'San\u202fJoaquin County', 'label': 'county', 'synthetic': 'Lane County'}, {'original': 'Sutter Medical Center', 'label': 'company_name', 'synthetic': 'Riverbend Hospital'}, {'original': 'Trinity Health', 'label': 'company_name', 'synthetic': 'Harmony Care'}, {'original': 'University of California, Davis', 'label': 'company_name', 'synthetic': 'Pacific Northwest University'}, {'original': 'Yazzie', 'label': 'last_name', 'synthetic': 'Kaur'}, {'original': 'Yuba City', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'full', 'label': 'employment_status', 'synthetic': 'permanent'}, {'original': 'libertarian', 'label': 'political_view', 'synthetic': 'Conservative'}, {'original': 'nurse', 'label': 'occupation', 'synthetic': 'physical therapist'}, {'original': 'part', 'label': 'employment_status', 'synthetic': 'seasonal'}, {'original': 'retired', 'label': 'employment_status', 'synthetic': 'emeritus'}]

[15:35:32] [DEBUG] Replacement map record 2ffdc696ea8d5950a6203fc1dba23452: requested=[('2020', 'date'), ('34', 'age'), ('745 North Tamarisk Street', 'street_address'), ('BFA in Visual Communications', 'education_level'), ('BrightSide Creative', 'company_name'), ('California', 'state'), ('Corona', 'city'), ('Irvine', 'city'), ('Jinhee', 'first_name'), ('Korean', 'language'), ('Korean American', 'race_ethnicity'), ('Los Angeles', 'city'), ('Lumen Design Agency', 'company_name'), ('Min', 'first_name'), ('Park', 'last_name'), ('PixelWave Studios', 'company_name'), ('Protestant', 'religious_belief'), ('San Diego', 'city'), ('Seoul', 'city'), ('University of California', 'company_name'), ('graphic designer', 'occupation'), ('identified Progressive', 'political_view'), ('jun', 'first_name')] raw=[{'original': '2020', 'label': 'date', 'synthetic': '2019'}, {'original': '34', 'label': 'age', 'synthetic': '35'}, {'original': '745 North Tamarisk Street', 'label': 'street_address', 'synthetic': '832 East Oakwood Avenue'}, {'original': 'BFA in Visual Communications', 'label': 'education_level', 'synthetic': 'MFA in Industrial Design'}, {'original': 'BrightSide Creative', 'label': 'company_name', 'synthetic': 'RiverStone Studios'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Corona', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Irvine', 'label': 'city', 'synthetic': 'Dallas'}, {'original': 'Jinhee', 'label': 'first_name', 'synthetic': 'Maya'}, {'original': 'Korean', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Korean American', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Los Angeles', 'label': 'city', 'synthetic': 'Houston'}, {'original': 'Lumen Design Agency', 'label': 'company_name', 'synthetic': 'Aurora Branding Group'}, {'original': 'Min', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'Park', 'label': 'last_name', 'synthetic': 'Garcia'}, {'original': 'PixelWave Studios', 'label': 'company_name', 'synthetic': 'NimbusForge Labs'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'San Diego', 'label': 'city', 'synthetic': 'San Antonio'}, {'original': 'Seoul', 'label': 'city', 'synthetic': 'Tokyo'}, {'original': 'University of California', 'label': 'company_name', 'synthetic': 'Texas State University'}, {'original': 'graphic designer', 'label': 'occupation', 'synthetic': 'industrial designer'}, {'original': 'identified Progressive', 'label': 'political_view', 'synthetic': 'identified Libertarian'}, {'original': 'jun', 'label': 'first_name', 'synthetic': 'Ethan'}] filtered=[{'original': '2020', 'label': 'date', 'synthetic': '2019'}, {'original': '34', 'label': 'age', 'synthetic': '35'}, {'original': '745 North Tamarisk Street', 'label': 'street_address', 'synthetic': '832 East Oakwood Avenue'}, {'original': 'BFA in Visual Communications', 'label': 'education_level', 'synthetic': 'MFA in Industrial Design'}, {'original': 'BrightSide Creative', 'label': 'company_name', 'synthetic': 'RiverStone Studios'}, {'original': 'California', 'label': 'state', 'synthetic': 'Texas'}, {'original': 'Corona', 'label': 'city', 'synthetic': 'Austin'}, {'original': 'Irvine', 'label': 'city', 'synthetic': 'Dallas'}, {'original': 'Jinhee', 'label': 'first_name', 'synthetic': 'Maya'}, {'original': 'Korean', 'label': 'language', 'synthetic': 'Spanish'}, {'original': 'Korean American', 'label': 'race_ethnicity', 'synthetic': 'Mexican American'}, {'original': 'Los Angeles', 'label': 'city', 'synthetic': 'Houston'}, {'original': 'Lumen Design Agency', 'label': 'company_name', 'synthetic': 'Aurora Branding Group'}, {'original': 'Min', 'label': 'first_name', 'synthetic': 'Liam'}, {'original': 'Park', 'label': 'last_name', 'synthetic': 'Garcia'}, {'original': 'PixelWave Studios', 'label': 'company_name', 'synthetic': 'NimbusForge Labs'}, {'original': 'Protestant', 'label': 'religious_belief', 'synthetic': 'Buddhist'}, {'original': 'San Diego', 'label': 'city', 'synthetic': 'San Antonio'}, {'original': 'Seoul', 'label': 'city', 'synthetic': 'Tokyo'}, {'original': 'University of California', 'label': 'company_name', 'synthetic': 'Texas State University'}, {'original': 'graphic designer', 'label': 'occupation', 'synthetic': 'industrial designer'}, {'original': 'identified Progressive', 'label': 'political_view', 'synthetic': 'identified Libertarian'}, {'original': 'jun', 'label': 'first_name', 'synthetic': 'Ethan'}]

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/replace/llm_replace_workflow.py:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([output_df, passthrough_rows], axis=0)
[15:35:32] [DEBUG] NDD workflow 'rewrite-pipeline' starting with 23 records

[15:35:32] [DEBUG] NDD workflow 'rewrite-pipeline': 12 columns ['_domain', '_domain_supplement', '_sensitivity_disposition', '_sensitivity_disposition_block', '_meaning_units', '_meaning_units_serialized', '_quality_qa', '_privacy_qa', '_rewrite_disposition_block', '_replacement_map_for_prompt', '_full_rewrite', '_rewritten_text']

[15:35:32] [INFO] 🎨 Creating Data Designer dataset

[15:35:32] [INFO] ✅ Validation passed

[15:35:32] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:35:32] [INFO] 🩺 Running health checks for models...

[15:35:32] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:35:33] [INFO]   |-- ✅ Passed!

[15:35:33] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-pipeline' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-pipeline_03-31-2026_153533' instead.

[15:35:33] [INFO] ⏳ Processing batch 1 of 1

[15:35:33] [INFO] 🌱 Sampling 23 records from seed dataset

[15:35:33] [INFO]   |-- seed dataset size: 23 records

[15:35:33] [INFO]   |-- sampling strategy: ordered

[15:35:33] [INFO] 🗂️ llm-structured model config for column '_domain'

[15:35:33] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:35:33] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:35:33] [INFO]   |-- model provider: 'nvidia'

[15:35:33] [INFO]   |-- inference parameters:

[15:35:33] [INFO]   |  |-- generation_type=chat-completion

[15:35:33] [INFO]   |  |-- max_parallel_requests=2

[15:35:33] [INFO]   |  |-- timeout=300

[15:35:33] [INFO]   |  |-- temperature=0.30

[15:35:33] [INFO]   |  |-- top_p=0.95

[15:35:33] [INFO]   |  |-- max_tokens=16384

[15:35:33] [INFO] ⚡️ Processing llm-structured column '_domain' with 2 concurrent workers

[15:35:33] [INFO] ⏱️ llm-structured column '_domain' will report progress every 2 records

[15:35:34] [INFO]   |-- 😴 llm-structured column '_domain' progress: 2/23 (9%) complete, 2 ok, 0 failed, 2.42 rec/s, eta 8.7s

[15:35:34] [INFO]   |-- 😴 llm-structured column '_domain' progress: 4/23 (17%) complete, 4 ok, 0 failed, 2.87 rec/s, eta 6.6s

[15:35:35] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2.90 rec/s, eta 5.9s

[15:35:36] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 8/23 (35%) complete, 8 ok, 0 failed, 3.02 rec/s, eta 5.0s

[15:35:36] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 10/23 (43%) complete, 10 ok, 0 failed, 3.04 rec/s, eta 4.3s

[15:35:37] [INFO]   |-- 😐 llm-structured column '_domain' progress: 12/23 (52%) complete, 12 ok, 0 failed, 3.08 rec/s, eta 3.6s

[15:35:37] [INFO]   |-- 😐 llm-structured column '_domain' progress: 14/23 (61%) complete, 14 ok, 0 failed, 3.12 rec/s, eta 2.9s

[15:35:38] [INFO]   |-- 😐 llm-structured column '_domain' progress: 16/23 (70%) complete, 16 ok, 0 failed, 3.06 rec/s, eta 2.3s

[15:35:39] [INFO]   |-- 😊 llm-structured column '_domain' progress: 18/23 (78%) complete, 18 ok, 0 failed, 3.08 rec/s, eta 1.6s

[15:35:39] [INFO]   |-- 😊 llm-structured column '_domain' progress: 20/23 (87%) complete, 20 ok, 0 failed, 3.05 rec/s, eta 1.0s

[15:35:40] [INFO]   |-- 😊 llm-structured column '_domain' progress: 22/23 (96%) complete, 22 ok, 0 failed, 3.08 rec/s, eta 0.3s

[15:35:40] [INFO]   |-- 🤩 llm-structured column '_domain' progress: 23/23 (100%) complete, 23 ok, 0 failed, 3.14 rec/s, eta 0.0s

[15:35:40] [INFO] 🔧 Custom column config for column '_domain_supplement'

[15:35:40] [INFO]   |-- generator_function: '_enrich_domain'

[15:35:40] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:35:40] [INFO]   |-- required_columns: ['_domain']

[15:35:40] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers

[15:35:40] [INFO] ⏱️ custom column '_domain_supplement' will report progress every 2 records

[15:35:40] [INFO]   |-- 🥚 custom column '_domain_supplement' progress: 2/23 (9%) complete, 2 ok, 0 failed, 1598.61 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🥚 custom column '_domain_supplement' progress: 4/23 (17%) complete, 4 ok, 0 failed, 1769.06 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐣 custom column '_domain_supplement' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2117.40 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐣 custom column '_domain_supplement' progress: 8/23 (35%) complete, 8 ok, 0 failed, 2415.55 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐣 custom column '_domain_supplement' progress: 10/23 (43%) complete, 10 ok, 0 failed, 2678.78 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐥 custom column '_domain_supplement' progress: 12/23 (52%) complete, 12 ok, 0 failed, 2748.22 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐥 custom column '_domain_supplement' progress: 14/23 (61%) complete, 14 ok, 0 failed, 2574.28 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐥 custom column '_domain_supplement' progress: 16/23 (70%) complete, 16 ok, 0 failed, 2557.75 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐤 custom column '_domain_supplement' progress: 18/23 (78%) complete, 18 ok, 0 failed, 2539.83 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐤 custom column '_domain_supplement' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2525.80 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐤 custom column '_domain_supplement' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2609.79 rec/s, eta 0.0s

[15:35:40] [INFO]   |-- 🐔 custom column '_domain_supplement' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2597.77 rec/s, eta 0.0s

[15:35:40] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'

[15:35:40] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:35:40] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:35:40] [INFO]   |-- model provider: 'nvidia'

[15:35:40] [INFO]   |-- inference parameters:

[15:35:40] [INFO]   |  |-- generation_type=chat-completion

[15:35:40] [INFO]   |  |-- max_parallel_requests=2

[15:35:40] [INFO]   |  |-- timeout=300

[15:35:40] [INFO]   |  |-- temperature=0.30

[15:35:40] [INFO]   |  |-- top_p=0.95

[15:35:40] [INFO]   |  |-- max_tokens=16384

[15:35:40] [INFO] ⚡️ Processing llm-structured column '_sensitivity_disposition' with 2 concurrent workers

[15:35:40] [INFO] ⏱️ llm-structured column '_sensitivity_disposition' will report progress every 2 records

[15:36:08] [INFO]   |-- 😴 llm-structured column '_sensitivity_disposition' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.07 rec/s, eta 286.3s

[15:36:32] [INFO]   |-- 😴 llm-structured column '_sensitivity_disposition' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.08 rec/s, eta 247.0s

[15:37:01] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.07 rec/s, eta 228.6s

[15:37:33] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.07 rec/s, eta 211.0s

[15:38:02] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.07 rec/s, eta 184.0s

[15:38:29] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.07 rec/s, eta 154.3s

[15:38:59] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.07 rec/s, eta 127.6s

[15:39:26] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.07 rec/s, eta 98.9s

[15:39:54] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.07 rec/s, eta 70.4s

[15:40:17] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.07 rec/s, eta 41.5s

[15:40:40] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.07 rec/s, eta 13.6s

[15:40:58] [INFO]   |-- 🤩 llm-structured column '_sensitivity_disposition' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.07 rec/s, eta 0.0s

[15:40:58] [INFO] 🔧 Custom column config for column '_sensitivity_disposition_block'

[15:40:58] [INFO]   |-- generator_function: '_format_disposition_block'

[15:40:58] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:40:58] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:40:58] [INFO] ⚡️ Processing custom column '_sensitivity_disposition_block' with 4 concurrent workers

[15:40:58] [INFO] ⏱️ custom column '_sensitivity_disposition_block' will report progress every 2 records

[15:40:58] [INFO]   |-- 🌧️ custom column '_sensitivity_disposition_block' progress: 2/23 (9%) complete, 2 ok, 0 failed, 1035.06 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌧️ custom column '_sensitivity_disposition_block' progress: 4/23 (17%) complete, 4 ok, 0 failed, 1317.14 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 6/23 (26%) complete, 6 ok, 0 failed, 1542.07 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1651.36 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 10/23 (43%) complete, 10 ok, 0 failed, 1728.28 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 12/23 (52%) complete, 12 ok, 0 failed, 1840.81 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 14/23 (61%) complete, 14 ok, 0 failed, 1787.80 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 16/23 (70%) complete, 16 ok, 0 failed, 1915.58 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 18/23 (78%) complete, 18 ok, 0 failed, 1912.82 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 20/23 (87%) complete, 20 ok, 0 failed, 1907.16 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2039.54 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- ☀️ custom column '_sensitivity_disposition_block' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2075.52 rec/s, eta 0.0s

[15:40:58] [INFO] 🔧 Custom column config for column '_privacy_qa'

[15:40:58] [INFO]   |-- generator_function: '_generate_privacy_qa_column'

[15:40:58] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:40:58] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:40:58] [INFO] ⚡️ Processing custom column '_privacy_qa' with 4 concurrent workers

[15:40:58] [INFO] ⏱️ custom column '_privacy_qa' will report progress every 2 records

[15:40:58] [INFO]   |-- 😴 custom column '_privacy_qa' progress: 2/23 (9%) complete, 2 ok, 0 failed, 1919.77 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😴 custom column '_privacy_qa' progress: 4/23 (17%) complete, 4 ok, 0 failed, 2206.95 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🥱 custom column '_privacy_qa' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2163.10 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🥱 custom column '_privacy_qa' progress: 8/23 (35%) complete, 8 ok, 0 failed, 2242.70 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🥱 custom column '_privacy_qa' progress: 10/23 (43%) complete, 10 ok, 0 failed, 2209.54 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😐 custom column '_privacy_qa' progress: 12/23 (52%) complete, 12 ok, 0 failed, 2262.27 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😐 custom column '_privacy_qa' progress: 14/23 (61%) complete, 14 ok, 0 failed, 2360.48 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😐 custom column '_privacy_qa' progress: 16/23 (70%) complete, 16 ok, 0 failed, 2486.24 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😊 custom column '_privacy_qa' progress: 18/23 (78%) complete, 18 ok, 0 failed, 2496.39 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😊 custom column '_privacy_qa' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2623.88 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 😊 custom column '_privacy_qa' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2639.63 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🤩 custom column '_privacy_qa' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2693.81 rec/s, eta 0.0s

[15:40:58] [INFO] 🔧 Custom column config for column '_rewrite_disposition_block'

[15:40:58] [INFO]   |-- generator_function: '_format_rewrite_disposition_block'

[15:40:58] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:40:58] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:40:58] [INFO] ⚡️ Processing custom column '_rewrite_disposition_block' with 4 concurrent workers

[15:40:58] [INFO] ⏱️ custom column '_rewrite_disposition_block' will report progress every 2 records

[15:40:58] [INFO]   |-- 🌑 custom column '_rewrite_disposition_block' progress: 2/23 (9%) complete, 2 ok, 0 failed, 2380.01 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌑 custom column '_rewrite_disposition_block' progress: 4/23 (17%) complete, 4 ok, 0 failed, 2697.24 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌘 custom column '_rewrite_disposition_block' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2922.61 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌘 custom column '_rewrite_disposition_block' progress: 8/23 (35%) complete, 8 ok, 0 failed, 2275.53 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌘 custom column '_rewrite_disposition_block' progress: 10/23 (43%) complete, 10 ok, 0 failed, 2332.84 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌗 custom column '_rewrite_disposition_block' progress: 12/23 (52%) complete, 12 ok, 0 failed, 2400.12 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌗 custom column '_rewrite_disposition_block' progress: 14/23 (61%) complete, 14 ok, 0 failed, 2460.69 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌗 custom column '_rewrite_disposition_block' progress: 16/23 (70%) complete, 16 ok, 0 failed, 2646.82 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌖 custom column '_rewrite_disposition_block' progress: 18/23 (78%) complete, 18 ok, 0 failed, 2738.91 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌖 custom column '_rewrite_disposition_block' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2831.89 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌖 custom column '_rewrite_disposition_block' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2941.06 rec/s, eta 0.0s

[15:40:58] [INFO]   |-- 🌕 custom column '_rewrite_disposition_block' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2966.64 rec/s, eta 0.0s

[15:40:58] [INFO] 🗂️ llm-structured model config for column '_meaning_units'

[15:40:58] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:40:58] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:40:58] [INFO]   |-- model provider: 'nvidia'

[15:40:58] [INFO]   |-- inference parameters:

[15:40:58] [INFO]   |  |-- generation_type=chat-completion

[15:40:58] [INFO]   |  |-- max_parallel_requests=2

[15:40:58] [INFO]   |  |-- timeout=300

[15:40:58] [INFO]   |  |-- temperature=0.30

[15:40:58] [INFO]   |  |-- top_p=0.95

[15:40:58] [INFO]   |  |-- max_tokens=16384

[15:40:58] [INFO] ⚡️ Processing llm-structured column '_meaning_units' with 2 concurrent workers

[15:40:58] [INFO] ⏱️ llm-structured column '_meaning_units' will report progress every 2 records

[15:41:08] [INFO]   |-- 😴 llm-structured column '_meaning_units' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.19 rec/s, eta 111.0s

[15:41:18] [INFO]   |-- 😴 llm-structured column '_meaning_units' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.20 rec/s, eta 95.2s

[15:41:25] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.22 rec/s, eta 78.7s

[15:41:40] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.19 rec/s, eta 79.3s

[15:41:47] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.20 rec/s, eta 63.8s

[15:42:02] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.19 rec/s, eta 58.8s

[15:42:12] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.19 rec/s, eta 47.6s

[15:42:21] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.19 rec/s, eta 36.6s

[15:42:31] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.19 rec/s, eta 26.0s

[15:42:40] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.20 rec/s, eta 15.4s

[15:42:50] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.20 rec/s, eta 5.1s

[15:42:55] [INFO]   |-- 🤩 llm-structured column '_meaning_units' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.20 rec/s, eta 0.0s

[15:42:55] [INFO] 🔧 Custom column config for column '_replacement_map_for_prompt'

[15:42:55] [INFO]   |-- generator_function: '_filter_replacement_map_for_prompt'

[15:42:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:42:55] [INFO]   |-- required_columns: ['_replacement_map', '_rewrite_disposition_block']

[15:42:55] [INFO] ⚡️ Processing custom column '_replacement_map_for_prompt' with 4 concurrent workers

[15:42:55] [INFO] ⏱️ custom column '_replacement_map_for_prompt' will report progress every 2 records

[15:42:55] [INFO]   |-- 😴 custom column '_replacement_map_for_prompt' progress: 2/23 (9%) complete, 2 ok, 0 failed, 845.62 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😴 custom column '_replacement_map_for_prompt' progress: 4/23 (17%) complete, 4 ok, 0 failed, 941.52 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🥱 custom column '_replacement_map_for_prompt' progress: 6/23 (26%) complete, 6 ok, 0 failed, 1130.46 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🥱 custom column '_replacement_map_for_prompt' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1376.02 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🥱 custom column '_replacement_map_for_prompt' progress: 10/23 (43%) complete, 10 ok, 0 failed, 1530.66 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😐 custom column '_replacement_map_for_prompt' progress: 12/23 (52%) complete, 12 ok, 0 failed, 1688.59 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😐 custom column '_replacement_map_for_prompt' progress: 14/23 (61%) complete, 14 ok, 0 failed, 1826.94 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😐 custom column '_replacement_map_for_prompt' progress: 16/23 (70%) complete, 16 ok, 0 failed, 1981.23 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😊 custom column '_replacement_map_for_prompt' progress: 18/23 (78%) complete, 18 ok, 0 failed, 2131.69 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😊 custom column '_replacement_map_for_prompt' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2241.46 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 😊 custom column '_replacement_map_for_prompt' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2375.41 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🤩 custom column '_replacement_map_for_prompt' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2417.64 rec/s, eta 0.0s

[15:42:55] [INFO] 🔧 Custom column config for column '_meaning_units_serialized'

[15:42:55] [INFO]   |-- generator_function: '_serialize_meaning_units'

[15:42:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:42:55] [INFO]   |-- required_columns: ['_meaning_units']

[15:42:55] [INFO] ⚡️ Processing custom column '_meaning_units_serialized' with 4 concurrent workers

[15:42:55] [INFO] ⏱️ custom column '_meaning_units_serialized' will report progress every 2 records

[15:42:55] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 2/23 (9%) complete, 2 ok, 0 failed, 2028.40 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 4/23 (17%) complete, 4 ok, 0 failed, 2505.35 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2673.75 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 8/23 (35%) complete, 8 ok, 0 failed, 3051.93 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 10/23 (43%) complete, 10 ok, 0 failed, 3026.41 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 12/23 (52%) complete, 12 ok, 0 failed, 3280.26 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 14/23 (61%) complete, 14 ok, 0 failed, 3383.11 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 16/23 (70%) complete, 16 ok, 0 failed, 3582.82 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 18/23 (78%) complete, 18 ok, 0 failed, 3771.81 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 20/23 (87%) complete, 20 ok, 0 failed, 3707.05 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 22/23 (96%) complete, 22 ok, 0 failed, 3821.66 rec/s, eta 0.0s

[15:42:55] [INFO]   |-- 🐔 custom column '_meaning_units_serialized' progress: 23/23 (100%) complete, 23 ok, 0 failed, 3771.26 rec/s, eta 0.0s

[15:42:55] [INFO] 🗂️ llm-structured model config for column '_full_rewrite'

[15:42:55] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:42:55] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:42:55] [INFO]   |-- model provider: 'nvidia'

[15:42:55] [INFO]   |-- inference parameters:

[15:42:55] [INFO]   |  |-- generation_type=chat-completion

[15:42:55] [INFO]   |  |-- max_parallel_requests=2

[15:42:55] [INFO]   |  |-- timeout=300

[15:42:55] [INFO]   |  |-- temperature=0.30

[15:42:55] [INFO]   |  |-- top_p=0.95

[15:42:55] [INFO]   |  |-- max_tokens=16384

[15:42:55] [INFO] ⚡️ Processing llm-structured column '_full_rewrite' with 2 concurrent workers

[15:42:55] [INFO] ⏱️ llm-structured column '_full_rewrite' will report progress every 2 records

[15:43:05] [INFO]   |-- 🚶 llm-structured column '_full_rewrite' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.20 rec/s, eta 107.5s

[15:43:12] [INFO]   |-- 🚶 llm-structured column '_full_rewrite' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 79.1s

[15:43:20] [INFO]   |-- 🐴 llm-structured column '_full_rewrite' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.24 rec/s, eta 70.7s

[15:43:30] [INFO]   |-- 🐴 llm-structured column '_full_rewrite' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.23 rec/s, eta 66.6s

[15:43:41] [INFO]   |-- 🐴 llm-structured column '_full_rewrite' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.22 rec/s, eta 59.8s

[15:43:50] [INFO]   |-- 🚗 llm-structured column '_full_rewrite' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.22 rec/s, eta 50.3s

[15:43:57] [INFO]   |-- 🚗 llm-structured column '_full_rewrite' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.23 rec/s, eta 39.7s

[15:44:04] [INFO]   |-- 🚗 llm-structured column '_full_rewrite' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.23 rec/s, eta 30.3s

[15:44:12] [INFO]   |-- ✈️ llm-structured column '_full_rewrite' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.23 rec/s, eta 21.4s

[15:44:18] [INFO]   |-- ✈️ llm-structured column '_full_rewrite' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.24 rec/s, eta 12.5s

[15:44:28] [INFO]   |-- ✈️ llm-structured column '_full_rewrite' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.24 rec/s, eta 4.2s

[15:44:35] [INFO]   |-- 🚀 llm-structured column '_full_rewrite' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.23 rec/s, eta 0.0s

[15:44:35] [INFO] 🗂️ llm-structured model config for column '_quality_qa'

[15:44:35] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:44:35] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:44:35] [INFO]   |-- model provider: 'nvidia'

[15:44:35] [INFO]   |-- inference parameters:

[15:44:35] [INFO]   |  |-- generation_type=chat-completion

[15:44:35] [INFO]   |  |-- max_parallel_requests=2

[15:44:35] [INFO]   |  |-- timeout=300

[15:44:35] [INFO]   |  |-- temperature=0.30

[15:44:35] [INFO]   |  |-- top_p=0.95

[15:44:35] [INFO]   |  |-- max_tokens=16384

[15:44:35] [INFO] ⚡️ Processing llm-structured column '_quality_qa' with 2 concurrent workers

[15:44:35] [INFO] ⏱️ llm-structured column '_quality_qa' will report progress every 2 records

[15:44:43] [INFO]   |-- 🌑 llm-structured column '_quality_qa' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.25 rec/s, eta 85.0s

[15:44:52] [INFO]   |-- 🌑 llm-structured column '_quality_qa' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 80.3s

[15:44:59] [INFO]   |-- 🌘 llm-structured column '_quality_qa' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.26 rec/s, eta 66.4s

[15:45:06] [INFO]   |-- 🌘 llm-structured column '_quality_qa' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.26 rec/s, eta 57.8s

[15:45:14] [INFO]   |-- 🌘 llm-structured column '_quality_qa' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.26 rec/s, eta 49.9s

[15:45:21] [INFO]   |-- 🌗 llm-structured column '_quality_qa' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.26 rec/s, eta 42.2s

[15:45:29] [INFO]   |-- 🌗 llm-structured column '_quality_qa' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.26 rec/s, eta 34.8s

[15:45:36] [INFO]   |-- 🌗 llm-structured column '_quality_qa' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.26 rec/s, eta 26.5s

[15:45:43] [INFO]   |-- 🌖 llm-structured column '_quality_qa' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.27 rec/s, eta 18.8s

[15:45:49] [INFO]   |-- 🌖 llm-structured column '_quality_qa' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.27 rec/s, eta 11.1s

[15:45:55] [INFO]   |-- 🌖 llm-structured column '_quality_qa' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.28 rec/s, eta 3.6s

[15:46:01] [INFO]   |-- 🌕 llm-structured column '_quality_qa' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.27 rec/s, eta 0.0s

[15:46:01] [INFO] 🔧 Custom column config for column '_rewritten_text'

[15:46:01] [INFO]   |-- generator_function: '_extract_rewritten_text'

[15:46:01] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:46:01] [INFO]   |-- required_columns: ['_full_rewrite']

[15:46:01] [INFO] ⚡️ Processing custom column '_rewritten_text' with 4 concurrent workers

[15:46:01] [INFO] ⏱️ custom column '_rewritten_text' will report progress every 2 records

[15:46:01] [INFO]   |-- 🥚 custom column '_rewritten_text' progress: 2/23 (9%) complete, 2 ok, 0 failed, 3006.20 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🥚 custom column '_rewritten_text' progress: 4/23 (17%) complete, 4 ok, 0 failed, 3962.36 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐣 custom column '_rewritten_text' progress: 6/23 (26%) complete, 6 ok, 0 failed, 4737.78 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐣 custom column '_rewritten_text' progress: 8/23 (35%) complete, 8 ok, 0 failed, 5433.24 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐣 custom column '_rewritten_text' progress: 10/23 (43%) complete, 10 ok, 0 failed, 5806.64 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐥 custom column '_rewritten_text' progress: 12/23 (52%) complete, 12 ok, 0 failed, 6107.77 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐥 custom column '_rewritten_text' progress: 14/23 (61%) complete, 14 ok, 0 failed, 6209.34 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐥 custom column '_rewritten_text' progress: 16/23 (70%) complete, 16 ok, 0 failed, 6630.75 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐤 custom column '_rewritten_text' progress: 18/23 (78%) complete, 18 ok, 0 failed, 6531.30 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐤 custom column '_rewritten_text' progress: 20/23 (87%) complete, 20 ok, 0 failed, 6584.63 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐤 custom column '_rewritten_text' progress: 22/23 (96%) complete, 22 ok, 0 failed, 6763.16 rec/s, eta 0.0s

[15:46:01] [INFO]   |-- 🐔 custom column '_rewritten_text' progress: 23/23 (100%) complete, 23 ok, 0 failed, 6634.93 rec/s, eta 0.0s

[15:46:01] [INFO] 📊 Model usage summary:

[15:46:01] [INFO]   |-- model: openai/gpt-oss-120b

[15:46:01] [INFO]   |-- tokens: input=234115, output=249261, total=483376, tps=769

[15:46:01] [INFO]   |-- requests: success=115, failed=0, total=115, rpm=10

[15:46:01] [INFO] 📐 Measuring dataset column statistics:

[15:46:01] [INFO]   |-- 🗂️ column: '_domain'

[15:46:01] [INFO]   |-- 🔧 column: '_domain_supplement'

[15:46:01] [INFO]   |-- 🗂️ column: '_sensitivity_disposition'

[15:46:01] [INFO]   |-- 🔧 column: '_sensitivity_disposition_block'

[15:46:01] [INFO]   |-- 🗂️ column: '_meaning_units'

[15:46:01] [INFO]   |-- 🔧 column: '_meaning_units_serialized'

[15:46:01] [INFO]   |-- 🗂️ column: '_quality_qa'

[15:46:01] [INFO]   |-- 🔧 column: '_privacy_qa'

[15:46:01] [INFO]   |-- 🔧 column: '_rewrite_disposition_block'

[15:46:01] [INFO]   |-- 🔧 column: '_replacement_map_for_prompt'

[15:46:01] [INFO]   |-- 🗂️ column: '_full_rewrite'

[15:46:01] [INFO]   |-- 🔧 column: '_rewritten_text'

[15:46:01] [DEBUG] NDD workflow 'rewrite-pipeline' returned 23 records

[15:46:01] [DEBUG] NDD workflow 'rewrite-evaluate-0' starting with 23 records

[15:46:01] [DEBUG] NDD workflow 'rewrite-evaluate-0': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:46:01] [INFO] 🎨 Creating Data Designer dataset

[15:46:01] [INFO] ✅ Validation passed

[15:46:01] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:46:01] [INFO] 🩺 Running health checks for models...

[15:46:01] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:46:03] [INFO]   |-- ✅ Passed!

[15:46:03] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-0_03-31-2026_154603' instead.

[15:46:03] [INFO] ⏳ Processing batch 1 of 1

[15:46:03] [INFO] 🌱 Sampling 23 records from seed dataset

[15:46:03] [INFO]   |-- seed dataset size: 23 records

[15:46:03] [INFO]   |-- sampling strategy: ordered

[15:46:03] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:46:03] [INFO]   |-- generator_function: '_quality_reanswer'

[15:46:03] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:46:03] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:46:03] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:46:03] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:46:03] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress every 2 records

[15:46:08] [INFO]   |-- 🥚 custom column '_quality_qa_reanswer' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.43 rec/s, eta 48.9s

[15:46:10] [INFO]   |-- 🥚 custom column '_quality_qa_reanswer' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.59 rec/s, eta 32.3s

[15:46:11] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.74 rec/s, eta 23.1s

[15:46:14] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.69 rec/s, eta 21.7s

[15:46:18] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.67 rec/s, eta 19.5s

[15:46:19] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.73 rec/s, eta 15.0s

[15:46:22] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.73 rec/s, eta 12.4s

[15:46:24] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.75 rec/s, eta 9.4s

[15:46:27] [INFO]   |-- 🐤 custom column '_quality_qa_reanswer' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.75 rec/s, eta 6.7s

[15:46:30] [INFO]   |-- 🐤 custom column '_quality_qa_reanswer' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.74 rec/s, eta 4.0s

[15:46:32] [INFO]   |-- 🐤 custom column '_quality_qa_reanswer' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.77 rec/s, eta 1.3s

[15:46:34] [INFO]   |-- 🐔 custom column '_quality_qa_reanswer' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.75 rec/s, eta 0.0s

[15:46:34] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:46:34] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:46:34] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:46:34] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:46:34] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:46:34] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:46:34] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress every 2 records

[15:46:40] [INFO]   |-- 🐱 custom column '_privacy_qa_reanswer' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.34 rec/s, eta 61.6s

[15:46:43] [INFO]   |-- 🐱 custom column '_privacy_qa_reanswer' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.44 rec/s, eta 43.2s

[15:46:49] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.38 rec/s, eta 44.5s

[15:46:50] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.49 rec/s, eta 30.6s

[15:46:54] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.48 rec/s, eta 27.0s

[15:46:56] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.54 rec/s, eta 20.2s

[15:46:58] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.57 rec/s, eta 15.8s

[15:47:00] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.61 rec/s, eta 11.5s

[15:47:01] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.65 rec/s, eta 7.7s

[15:47:07] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.61 rec/s, eta 4.9s

[15:47:09] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.62 rec/s, eta 1.6s

[15:47:39] [INFO]   |-- 🦁 custom column '_privacy_qa_reanswer' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.36 rec/s, eta 0.0s

[15:47:39] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:47:39] [INFO]   |-- generator_function: '_quality_compare'

[15:47:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:47:39] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:47:39] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:47:39] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:47:39] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress every 2 records

[15:47:44] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.36 rec/s, eta 59.0s

[15:47:48] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.42 rec/s, eta 45.4s

[15:47:51] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.50 rec/s, eta 34.1s

[15:47:54] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.51 rec/s, eta 29.2s

[15:47:59] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.49 rec/s, eta 26.7s

[15:48:01] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.53 rec/s, eta 20.6s

[15:48:06] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.52 rec/s, eta 17.4s

[15:48:10] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.50 rec/s, eta 14.0s

[15:48:15] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.50 rec/s, eta 10.0s

[15:48:17] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.51 rec/s, eta 5.8s

[15:48:23] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.50 rec/s, eta 2.0s

[15:48:24] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.51 rec/s, eta 0.0s

[15:48:24] [INFO] 🔧 Custom column config for column 'utility_score'

[15:48:24] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:48:24] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:24] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:48:24] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:48:24] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:48:24] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:48:24] [INFO] ⏱️ custom column 'utility_score' will report progress every 2 records

[15:48:24] [INFO]   |-- 😴 custom column 'utility_score' progress: 2/23 (9%) complete, 2 ok, 0 failed, 936.84 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😴 custom column 'utility_score' progress: 4/23 (17%) complete, 4 ok, 0 failed, 1231.24 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🥱 custom column 'utility_score' progress: 6/23 (26%) complete, 6 ok, 0 failed, 1436.28 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🥱 custom column 'utility_score' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1600.32 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🥱 custom column 'utility_score' progress: 10/23 (43%) complete, 10 ok, 0 failed, 1718.51 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😐 custom column 'utility_score' progress: 12/23 (52%) complete, 12 ok, 0 failed, 1831.19 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😐 custom column 'utility_score' progress: 14/23 (61%) complete, 14 ok, 0 failed, 1833.20 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😐 custom column 'utility_score' progress: 16/23 (70%) complete, 16 ok, 0 failed, 1909.57 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😊 custom column 'utility_score' progress: 18/23 (78%) complete, 18 ok, 0 failed, 1998.32 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😊 custom column 'utility_score' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2060.48 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 😊 custom column 'utility_score' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2120.25 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🤩 custom column 'utility_score' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2117.54 rec/s, eta 0.0s

[15:48:24] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:48:24] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:48:24] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:24] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:48:24] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:48:24] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:48:24] [INFO] ⏱️ custom column '_needs_repair' will report progress every 2 records

[15:48:24] [INFO]   |-- 🌑 custom column '_needs_repair' progress: 2/23 (9%) complete, 2 ok, 0 failed, 2727.58 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌑 custom column '_needs_repair' progress: 4/23 (17%) complete, 4 ok, 0 failed, 3160.18 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌘 custom column '_needs_repair' progress: 6/23 (26%) complete, 6 ok, 0 failed, 3562.15 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌘 custom column '_needs_repair' progress: 8/23 (35%) complete, 8 ok, 0 failed, 3853.18 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌘 custom column '_needs_repair' progress: 10/23 (43%) complete, 10 ok, 0 failed, 3954.65 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 12/23 (52%) complete, 12 ok, 0 failed, 4187.81 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 14/23 (61%) complete, 14 ok, 0 failed, 4369.31 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 16/23 (70%) complete, 16 ok, 0 failed, 4497.22 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌖 custom column '_needs_repair' progress: 18/23 (78%) complete, 18 ok, 0 failed, 4601.23 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌖 custom column '_needs_repair' progress: 20/23 (87%) complete, 20 ok, 0 failed, 4578.54 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌖 custom column '_needs_repair' progress: 22/23 (96%) complete, 22 ok, 0 failed, 4693.33 rec/s, eta 0.0s

[15:48:24] [INFO]   |-- 🌕 custom column '_needs_repair' progress: 23/23 (100%) complete, 23 ok, 0 failed, 4635.62 rec/s, eta 0.0s

[15:48:24] [INFO] 📊 Model usage summary:

[15:48:24] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:48:24] [INFO]   |-- tokens: input=88778, output=110299, total=199077, tps=1408

[15:48:24] [INFO]   |-- requests: success=70, failed=0, total=70, rpm=29

[15:48:24] [INFO] 📐 Measuring dataset column statistics:

[15:48:24] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:48:24] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:48:24] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:48:24] [INFO]   |-- 🔧 column: 'utility_score'

[15:48:24] [INFO]   |-- 🔧 column: '_needs_repair'

[15:48:24] [DEBUG] NDD workflow 'rewrite-evaluate-0' returned 23 records

[15:48:24] [INFO] Evaluate-repair loop iteration 0: 11/23 rows need repair

[15:48:24] [DEBUG] NDD workflow 'rewrite-repair-0' starting with 11 records

[15:48:24] [DEBUG] NDD workflow 'rewrite-repair-0': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:48:24] [INFO] 🎨 Creating Data Designer dataset

[15:48:24] [INFO] ✅ Validation passed

[15:48:24] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:48:24] [INFO] 🩺 Running health checks for models...

[15:48:24] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:48:25] [INFO]   |-- ✅ Passed!

[15:48:25] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-0_03-31-2026_154825' instead.

[15:48:25] [INFO] ⏳ Processing batch 1 of 1

[15:48:25] [INFO] 🌱 Sampling 11 records from seed dataset

[15:48:25] [INFO]   |-- seed dataset size: 11 records

[15:48:25] [INFO]   |-- sampling strategy: ordered

[15:48:25] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:48:25] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:48:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:25] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:48:25] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:48:25] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:48:25] [INFO]   |-- 🌧️ custom column '_leaked_privacy_items' progress: 1/11 (9%) complete, 1 ok, 0 failed, 1448.23 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌧️ custom column '_leaked_privacy_items' progress: 2/11 (18%) complete, 2 ok, 0 failed, 1773.90 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌦️ custom column '_leaked_privacy_items' progress: 3/11 (27%) complete, 3 ok, 0 failed, 1667.32 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌦️ custom column '_leaked_privacy_items' progress: 4/11 (36%) complete, 4 ok, 0 failed, 1460.05 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌦️ custom column '_leaked_privacy_items' progress: 5/11 (45%) complete, 5 ok, 0 failed, 1554.63 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- ⛅ custom column '_leaked_privacy_items' progress: 6/11 (55%) complete, 6 ok, 0 failed, 1549.92 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- ⛅ custom column '_leaked_privacy_items' progress: 7/11 (64%) complete, 7 ok, 0 failed, 1619.00 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- ⛅ custom column '_leaked_privacy_items' progress: 8/11 (73%) complete, 8 ok, 0 failed, 1714.53 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌤️ custom column '_leaked_privacy_items' progress: 9/11 (82%) complete, 9 ok, 0 failed, 1805.21 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- 🌤️ custom column '_leaked_privacy_items' progress: 10/11 (91%) complete, 10 ok, 0 failed, 1877.61 rec/s, eta 0.0s

[15:48:25] [INFO]   |-- ☀️ custom column '_leaked_privacy_items' progress: 11/11 (100%) complete, 11 ok, 0 failed, 1956.67 rec/s, eta 0.0s

[15:48:25] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:48:25] [INFO]   |-- generator_function: '_repair_column'

[15:48:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:25] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:48:25] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:48:25] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All direct identifiers and quasi-identifier combinations (names, locations, employers, dates)\nPRESERVE: Career trajectory, educational background, and professional accomplishments' max_privacy_leak=0.6

[15:48:25] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:48:25] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:48:28] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 1/11 (9%) complete, 1 ok, 0 failed, 0.32 rec/s, eta 30.9s

[15:48:30] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 2/11 (18%) complete, 2 ok, 0 failed, 0.35 rec/s, eta 25.5s

[15:48:30] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 3/11 (27%) complete, 3 ok, 0 failed, 0.52 rec/s, eta 15.3s

[15:48:33] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 4/11 (36%) complete, 4 ok, 0 failed, 0.48 rec/s, eta 14.6s

[15:48:34] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 5/11 (45%) complete, 5 ok, 0 failed, 0.51 rec/s, eta 11.7s

[15:48:35] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 6/11 (55%) complete, 6 ok, 0 failed, 0.58 rec/s, eta 8.6s

[15:48:35] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 7/11 (64%) complete, 7 ok, 0 failed, 0.67 rec/s, eta 6.0s

[15:48:38] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 8/11 (73%) complete, 8 ok, 0 failed, 0.58 rec/s, eta 5.2s

[15:48:39] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 9/11 (82%) complete, 9 ok, 0 failed, 0.62 rec/s, eta 3.3s

[15:48:39] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 10/11 (91%) complete, 10 ok, 0 failed, 0.68 rec/s, eta 1.5s

[15:48:40] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 11/11 (100%) complete, 11 ok, 0 failed, 0.74 rec/s, eta 0.0s

[15:48:40] [INFO] 📊 Model usage summary:

[15:48:40] [INFO]   |-- model: openai/gpt-oss-120b

[15:48:40] [INFO]   |-- tokens: input=19821, output=11699, total=31520, tps=2063

[15:48:40] [INFO]   |-- requests: success=11, failed=0, total=11, rpm=43

[15:48:40] [INFO] 📐 Measuring dataset column statistics:

[15:48:40] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:48:40] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:48:40] [DEBUG] NDD workflow 'rewrite-repair-0' returned 11 records

[15:48:40] [DEBUG] NDD workflow 'rewrite-evaluate-1' starting with 11 records

[15:48:40] [DEBUG] NDD workflow 'rewrite-evaluate-1': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:48:40] [INFO] 🎨 Creating Data Designer dataset

[15:48:40] [INFO] ✅ Validation passed

[15:48:40] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:48:40] [INFO] 🩺 Running health checks for models...

[15:48:40] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:48:41] [INFO]   |-- ✅ Passed!

[15:48:41] [INFO] ⏳ Processing batch 1 of 1

[15:48:41] [INFO] 🌱 Sampling 11 records from seed dataset

[15:48:41] [INFO]   |-- seed dataset size: 11 records

[15:48:41] [INFO]   |-- sampling strategy: ordered

[15:48:41] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:48:41] [INFO]   |-- generator_function: '_quality_reanswer'

[15:48:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:41] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:48:41] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:48:41] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:48:41] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:48:44] [INFO]   |-- 🥚 custom column '_quality_qa_reanswer' progress: 1/11 (9%) complete, 1 ok, 0 failed, 0.32 rec/s, eta 31.5s

[15:48:45] [INFO]   |-- 🥚 custom column '_quality_qa_reanswer' progress: 2/11 (18%) complete, 2 ok, 0 failed, 0.45 rec/s, eta 20.0s

[15:48:47] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 3/11 (27%) complete, 3 ok, 0 failed, 0.50 rec/s, eta 15.9s

[15:48:48] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 4/11 (36%) complete, 4 ok, 0 failed, 0.55 rec/s, eta 12.7s

[15:48:50] [INFO]   |-- 🐣 custom column '_quality_qa_reanswer' progress: 5/11 (45%) complete, 5 ok, 0 failed, 0.55 rec/s, eta 11.0s

[15:48:50] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 6/11 (55%) complete, 6 ok, 0 failed, 0.65 rec/s, eta 7.6s

[15:48:54] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 7/11 (64%) complete, 7 ok, 0 failed, 0.51 rec/s, eta 7.8s

[15:48:55] [INFO]   |-- 🐥 custom column '_quality_qa_reanswer' progress: 8/11 (73%) complete, 8 ok, 0 failed, 0.56 rec/s, eta 5.3s

[15:48:56] [INFO]   |-- 🐤 custom column '_quality_qa_reanswer' progress: 9/11 (82%) complete, 9 ok, 0 failed, 0.60 rec/s, eta 3.3s

[15:48:57] [INFO]   |-- 🐤 custom column '_quality_qa_reanswer' progress: 10/11 (91%) complete, 10 ok, 0 failed, 0.63 rec/s, eta 1.6s

[15:48:57] [INFO]   |-- 🐔 custom column '_quality_qa_reanswer' progress: 11/11 (100%) complete, 11 ok, 0 failed, 0.66 rec/s, eta 0.0s

[15:48:57] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:48:57] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:48:57] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:48:57] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:48:57] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:48:57] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:48:57] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:49:03] [INFO]   |-- 🥚 custom column '_privacy_qa_reanswer' progress: 1/11 (9%) complete, 1 ok, 0 failed, 0.19 rec/s, eta 53.2s

[15:49:03] [WARNING] Evaluator returned malformed privacy answer set; missing=[23] duplicate=[] extra=[]. Applying conservative normalization.

[15:49:03] [INFO]   |-- 🥚 custom column '_privacy_qa_reanswer' progress: 2/11 (18%) complete, 2 ok, 0 failed, 0.34 rec/s, eta 26.8s

[15:49:04] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 3/11 (27%) complete, 3 ok, 0 failed, 0.50 rec/s, eta 16.1s

[15:49:04] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 4/11 (36%) complete, 4 ok, 0 failed, 0.64 rec/s, eta 11.0s

[15:49:07] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 5/11 (45%) complete, 5 ok, 0 failed, 0.51 rec/s, eta 11.9s

[15:49:09] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 6/11 (55%) complete, 6 ok, 0 failed, 0.51 rec/s, eta 9.8s

[15:49:10] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 7/11 (64%) complete, 7 ok, 0 failed, 0.57 rec/s, eta 7.1s

[15:49:11] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 8/11 (73%) complete, 8 ok, 0 failed, 0.60 rec/s, eta 5.0s

[15:49:13] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 9/11 (82%) complete, 9 ok, 0 failed, 0.60 rec/s, eta 3.4s

[15:49:16] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 10/11 (91%) complete, 10 ok, 0 failed, 0.55 rec/s, eta 1.8s

[15:49:19] [INFO]   |-- 🐔 custom column '_privacy_qa_reanswer' progress: 11/11 (100%) complete, 11 ok, 0 failed, 0.51 rec/s, eta 0.0s

[15:49:19] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:49:19] [INFO]   |-- generator_function: '_quality_compare'

[15:49:19] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:19] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:49:19] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:49:19] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:49:19] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:49:24] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 1/11 (9%) complete, 1 ok, 0 failed, 0.19 rec/s, eta 53.5s

[15:49:25] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 2/11 (18%) complete, 2 ok, 0 failed, 0.34 rec/s, eta 26.1s

[15:49:26] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 3/11 (27%) complete, 3 ok, 0 failed, 0.44 rec/s, eta 18.1s

[15:49:29] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 4/11 (36%) complete, 4 ok, 0 failed, 0.40 rec/s, eta 17.3s

[15:49:31] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 5/11 (45%) complete, 5 ok, 0 failed, 0.42 rec/s, eta 14.4s

[15:49:32] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 6/11 (55%) complete, 6 ok, 0 failed, 0.47 rec/s, eta 10.7s

[15:49:32] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 7/11 (64%) complete, 7 ok, 0 failed, 0.54 rec/s, eta 7.4s

[15:49:38] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 8/11 (73%) complete, 8 ok, 0 failed, 0.42 rec/s, eta 7.2s

[15:49:38] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 9/11 (82%) complete, 9 ok, 0 failed, 0.46 rec/s, eta 4.3s

[15:49:38] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 10/11 (91%) complete, 10 ok, 0 failed, 0.52 rec/s, eta 1.9s

[15:49:41] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 11/11 (100%) complete, 11 ok, 0 failed, 0.49 rec/s, eta 0.0s

[15:49:41] [INFO] 🔧 Custom column config for column 'utility_score'

[15:49:41] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:49:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:41] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:49:41] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:49:41] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:49:41] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:49:41] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:49:41] [INFO]   |-- 🥚 custom column 'utility_score' progress: 1/11 (9%) complete, 1 ok, 0 failed, 1033.32 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🥚 custom column 'utility_score' progress: 2/11 (18%) complete, 2 ok, 0 failed, 1256.15 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐣 custom column 'utility_score' progress: 3/11 (27%) complete, 3 ok, 0 failed, 1258.28 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐣 custom column 'utility_score' progress: 4/11 (36%) complete, 4 ok, 0 failed, 1150.91 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐣 custom column 'utility_score' progress: 5/11 (45%) complete, 5 ok, 0 failed, 1074.01 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐥 custom column 'utility_score' progress: 6/11 (55%) complete, 6 ok, 0 failed, 1115.92 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐥 custom column 'utility_score' progress: 7/11 (64%) complete, 7 ok, 0 failed, 1115.90 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐥 custom column 'utility_score' progress: 8/11 (73%) complete, 8 ok, 0 failed, 1160.40 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐤 custom column 'utility_score' progress: 9/11 (82%) complete, 9 ok, 0 failed, 1257.35 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐤 custom column 'utility_score' progress: 10/11 (91%) complete, 10 ok, 0 failed, 1356.90 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🐔 custom column 'utility_score' progress: 11/11 (100%) complete, 11 ok, 0 failed, 1366.85 rec/s, eta 0.0s

[15:49:41] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:49:41] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:49:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:41] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:49:41] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:49:41] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:49:41] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:49:41] [INFO]   |-- 😴 custom column '_needs_repair' progress: 1/11 (9%) complete, 1 ok, 0 failed, 2200.62 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😴 custom column '_needs_repair' progress: 2/11 (18%) complete, 2 ok, 0 failed, 2831.19 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🥱 custom column '_needs_repair' progress: 3/11 (27%) complete, 3 ok, 0 failed, 2877.35 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🥱 custom column '_needs_repair' progress: 4/11 (36%) complete, 4 ok, 0 failed, 3267.97 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🥱 custom column '_needs_repair' progress: 5/11 (45%) complete, 5 ok, 0 failed, 3060.05 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😐 custom column '_needs_repair' progress: 6/11 (55%) complete, 6 ok, 0 failed, 3090.06 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😐 custom column '_needs_repair' progress: 7/11 (64%) complete, 7 ok, 0 failed, 3189.25 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😐 custom column '_needs_repair' progress: 8/11 (73%) complete, 8 ok, 0 failed, 3313.77 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😊 custom column '_needs_repair' progress: 9/11 (82%) complete, 9 ok, 0 failed, 3327.12 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 😊 custom column '_needs_repair' progress: 10/11 (91%) complete, 10 ok, 0 failed, 3384.86 rec/s, eta 0.0s

[15:49:41] [INFO]   |-- 🤩 custom column '_needs_repair' progress: 11/11 (100%) complete, 11 ok, 0 failed, 3507.61 rec/s, eta 0.0s

[15:49:42] [INFO] 📊 Model usage summary:

[15:49:42] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:49:42] [INFO]   |-- tokens: input=42632, output=49422, total=92054, tps=1510

[15:49:42] [INFO]   |-- requests: success=33, failed=0, total=33, rpm=32

[15:49:42] [INFO] 📐 Measuring dataset column statistics:

[15:49:42] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:49:42] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:49:42] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:49:42] [INFO]   |-- 🔧 column: 'utility_score'

[15:49:42] [INFO]   |-- 🔧 column: '_needs_repair'

[15:49:42] [DEBUG] NDD workflow 'rewrite-evaluate-1' returned 11 records

[15:49:42] [INFO] Evaluate-repair loop iteration 1: 6/23 rows need repair

[15:49:42] [DEBUG] NDD workflow 'rewrite-repair-1' starting with 6 records

[15:49:42] [DEBUG] NDD workflow 'rewrite-repair-1': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:49:42] [INFO] 🎨 Creating Data Designer dataset

[15:49:42] [INFO] ✅ Validation passed

[15:49:42] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:49:42] [INFO] 🩺 Running health checks for models...

[15:49:42] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:49:42] [INFO]   |-- ✅ Passed!

[15:49:42] [INFO] ⏳ Processing batch 1 of 1

[15:49:42] [INFO] 🌱 Sampling 6 records from seed dataset

[15:49:42] [INFO]   |-- seed dataset size: 6 records

[15:49:42] [INFO]   |-- sampling strategy: ordered

[15:49:42] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:49:42] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:49:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:42] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:49:42] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:49:42] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:49:42] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 1/6 (17%) complete, 1 ok, 0 failed, 2093.88 rec/s, eta 0.0s

[15:49:42] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 2/6 (33%) complete, 2 ok, 0 failed, 2499.22 rec/s, eta 0.0s

[15:49:42] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 3/6 (50%) complete, 3 ok, 0 failed, 2414.24 rec/s, eta 0.0s

[15:49:42] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 4/6 (67%) complete, 4 ok, 0 failed, 2789.16 rec/s, eta 0.0s

[15:49:42] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 5/6 (83%) complete, 5 ok, 0 failed, 2855.17 rec/s, eta 0.0s

[15:49:42] [INFO]   |-- 🚀 custom column '_leaked_privacy_items' progress: 6/6 (100%) complete, 6 ok, 0 failed, 2889.59 rec/s, eta 0.0s

[15:49:42] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:49:42] [INFO]   |-- generator_function: '_repair_column'

[15:49:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:42] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:49:42] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:49:42] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All direct identifiers and quasi-identifier combinations (names, locations, employers, dates)\nPRESERVE: Career trajectory, educational background, and professional accomplishments' max_privacy_leak=0.6

[15:49:42] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:49:42] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:49:46] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.25 rec/s, eta 20.4s

[15:49:47] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.42 rec/s, eta 9.5s

[15:49:47] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.63 rec/s, eta 4.8s

[15:49:48] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.68 rec/s, eta 2.9s

[15:49:52] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.52 rec/s, eta 1.9s

[15:49:53] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.54 rec/s, eta 0.0s

[15:49:54] [INFO] 📊 Model usage summary:

[15:49:54] [INFO]   |-- model: openai/gpt-oss-120b

[15:49:54] [INFO]   |-- tokens: input=11023, output=6733, total=17756, tps=1561

[15:49:54] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=31

[15:49:54] [INFO] 📐 Measuring dataset column statistics:

[15:49:54] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:49:54] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:49:54] [DEBUG] NDD workflow 'rewrite-repair-1' returned 6 records

[15:49:54] [DEBUG] NDD workflow 'rewrite-evaluate-2' starting with 6 records

[15:49:54] [DEBUG] NDD workflow 'rewrite-evaluate-2': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:49:54] [INFO] 🎨 Creating Data Designer dataset

[15:49:54] [INFO] ✅ Validation passed

[15:49:54] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:49:54] [INFO] 🩺 Running health checks for models...

[15:49:54] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:49:55] [INFO]   |-- ✅ Passed!

[15:49:55] [INFO] ⏳ Processing batch 1 of 1

[15:49:55] [INFO] 🌱 Sampling 6 records from seed dataset

[15:49:55] [INFO]   |-- seed dataset size: 6 records

[15:49:55] [INFO]   |-- sampling strategy: ordered

[15:49:55] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:49:55] [INFO]   |-- generator_function: '_quality_reanswer'

[15:49:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:49:55] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:49:55] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:49:55] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:49:55] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:49:59] [INFO]   |-- 🌑 custom column '_quality_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.25 rec/s, eta 19.7s

[15:49:59] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.50 rec/s, eta 7.9s

[15:50:00] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.58 rec/s, eta 5.2s

[15:50:02] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.55 rec/s, eta 3.7s

[15:50:03] [INFO]   |-- 🌖 custom column '_quality_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.62 rec/s, eta 1.6s

[15:50:05] [INFO]   |-- 🌕 custom column '_quality_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.56 rec/s, eta 0.0s

[15:50:05] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:50:05] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:50:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:05] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:50:05] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:50:05] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:50:05] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:50:12] [INFO]   |-- 😴 custom column '_privacy_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.16 rec/s, eta 31.0s

[15:50:12] [INFO]   |-- 🥱 custom column '_privacy_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.31 rec/s, eta 12.8s

[15:50:13] [WARNING] Evaluator returned malformed privacy answer set; missing=[23] duplicate=[] extra=[]. Applying conservative normalization.

[15:50:13] [INFO]   |-- 😐 custom column '_privacy_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.38 rec/s, eta 8.0s

[15:50:16] [INFO]   |-- 😐 custom column '_privacy_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.37 rec/s, eta 5.5s

[15:50:19] [INFO]   |-- 😊 custom column '_privacy_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.37 rec/s, eta 2.7s

[15:50:20] [INFO]   |-- 🤩 custom column '_privacy_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.42 rec/s, eta 0.0s

[15:50:20] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:50:20] [INFO]   |-- generator_function: '_quality_compare'

[15:50:20] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:20] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:50:20] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:50:20] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:50:20] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:50:25] [INFO]   |-- 🌧️ custom column '_quality_qa_compare' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.20 rec/s, eta 24.9s

[15:50:27] [INFO]   |-- 🌦️ custom column '_quality_qa_compare' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.29 rec/s, eta 13.6s

[15:50:27] [INFO]   |-- ⛅ custom column '_quality_qa_compare' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.44 rec/s, eta 6.9s

[15:50:31] [INFO]   |-- ⛅ custom column '_quality_qa_compare' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.36 rec/s, eta 5.6s

[15:50:31] [INFO]   |-- 🌤️ custom column '_quality_qa_compare' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.44 rec/s, eta 2.3s

[15:50:43] [WARNING] Evaluator returned malformed quality compare set; missing=[10] duplicate=[] extra=[]. Applying conservative normalization.

[15:50:43] [INFO]   |-- ☀️ custom column '_quality_qa_compare' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.25 rec/s, eta 0.0s

[15:50:43] [INFO] 🔧 Custom column config for column 'utility_score'

[15:50:43] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:50:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:43] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:50:43] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:50:43] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:50:43] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:50:43] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:50:43] [INFO]   |-- 🥚 custom column 'utility_score' progress: 1/6 (17%) complete, 1 ok, 0 failed, 965.25 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐣 custom column 'utility_score' progress: 2/6 (33%) complete, 2 ok, 0 failed, 1194.27 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐥 custom column 'utility_score' progress: 3/6 (50%) complete, 3 ok, 0 failed, 1243.24 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐥 custom column 'utility_score' progress: 4/6 (67%) complete, 4 ok, 0 failed, 1465.60 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐤 custom column 'utility_score' progress: 5/6 (83%) complete, 5 ok, 0 failed, 1502.31 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐔 custom column 'utility_score' progress: 6/6 (100%) complete, 6 ok, 0 failed, 1365.78 rec/s, eta 0.0s

[15:50:43] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:50:43] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:50:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:43] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:50:43] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:50:43] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:50:43] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:50:43] [INFO]   |-- 🚶 custom column '_needs_repair' progress: 1/6 (17%) complete, 1 ok, 0 failed, 2071.47 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🐴 custom column '_needs_repair' progress: 2/6 (33%) complete, 2 ok, 0 failed, 2925.58 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 3/6 (50%) complete, 3 ok, 0 failed, 2968.09 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 4/6 (67%) complete, 4 ok, 0 failed, 3274.77 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- ✈️ custom column '_needs_repair' progress: 5/6 (83%) complete, 5 ok, 0 failed, 3093.18 rec/s, eta 0.0s

[15:50:43] [INFO]   |-- 🚀 custom column '_needs_repair' progress: 6/6 (100%) complete, 6 ok, 0 failed, 3101.18 rec/s, eta 0.0s

[15:50:44] [INFO] 📊 Model usage summary:

[15:50:44] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:50:44] [INFO]   |-- tokens: input=23105, output=32198, total=55303, tps=1126

[15:50:44] [INFO]   |-- requests: success=18, failed=0, total=18, rpm=21

[15:50:44] [INFO] 📐 Measuring dataset column statistics:

[15:50:44] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:50:44] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:50:44] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:50:44] [INFO]   |-- 🔧 column: 'utility_score'

[15:50:44] [INFO]   |-- 🔧 column: '_needs_repair'

[15:50:44] [DEBUG] NDD workflow 'rewrite-evaluate-2' returned 6 records

[15:50:44] [INFO] Evaluate-repair loop iteration 2: 6/23 rows need repair

[15:50:44] [DEBUG] NDD workflow 'rewrite-repair-2' starting with 6 records

[15:50:44] [DEBUG] NDD workflow 'rewrite-repair-2': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:50:44] [INFO] 🎨 Creating Data Designer dataset

[15:50:44] [INFO] ✅ Validation passed

[15:50:44] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:50:44] [INFO] 🩺 Running health checks for models...

[15:50:44] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:50:44] [INFO]   |-- ✅ Passed!

[15:50:44] [INFO] ⏳ Processing batch 1 of 1

[15:50:44] [INFO] 🌱 Sampling 6 records from seed dataset

[15:50:44] [INFO]   |-- seed dataset size: 6 records

[15:50:44] [INFO]   |-- sampling strategy: ordered

[15:50:44] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:50:44] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:50:44] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:44] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:50:44] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:50:44] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:50:44] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 1/6 (17%) complete, 1 ok, 0 failed, 1546.89 rec/s, eta 0.0s

[15:50:44] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 2/6 (33%) complete, 2 ok, 0 failed, 2074.96 rec/s, eta 0.0s

[15:50:44] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 3/6 (50%) complete, 3 ok, 0 failed, 2362.20 rec/s, eta 0.0s

[15:50:44] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 4/6 (67%) complete, 4 ok, 0 failed, 2616.30 rec/s, eta 0.0s

[15:50:44] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 5/6 (83%) complete, 5 ok, 0 failed, 2605.52 rec/s, eta 0.0s

[15:50:44] [INFO]   |-- 🚀 custom column '_leaked_privacy_items' progress: 6/6 (100%) complete, 6 ok, 0 failed, 2589.79 rec/s, eta 0.0s

[15:50:44] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:50:44] [INFO]   |-- generator_function: '_repair_column'

[15:50:44] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:44] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:50:44] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:50:44] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All direct identifiers and quasi-identifier combinations (names, locations, employers, dates)\nPRESERVE: Career trajectory, educational background, and professional accomplishments' max_privacy_leak=0.6

[15:50:44] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:50:44] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:50:48] [INFO]   |-- 🌧️ custom column '_rewritten_text__next' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.27 rec/s, eta 18.5s

[15:50:49] [INFO]   |-- 🌦️ custom column '_rewritten_text__next' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.43 rec/s, eta 9.3s

[15:50:50] [INFO]   |-- ⛅ custom column '_rewritten_text__next' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.49 rec/s, eta 6.1s

[15:50:51] [INFO]   |-- ⛅ custom column '_rewritten_text__next' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.61 rec/s, eta 3.3s

[15:50:53] [INFO]   |-- 🌤️ custom column '_rewritten_text__next' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.60 rec/s, eta 1.7s

[15:50:56] [INFO]   |-- ☀️ custom column '_rewritten_text__next' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.53 rec/s, eta 0.0s

[15:50:56] [INFO] 📊 Model usage summary:

[15:50:56] [INFO]   |-- model: openai/gpt-oss-120b

[15:50:56] [INFO]   |-- tokens: input=11014, output=6313, total=17327, tps=1488

[15:50:56] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=30

[15:50:56] [INFO] 📐 Measuring dataset column statistics:

[15:50:56] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:50:56] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:50:56] [DEBUG] NDD workflow 'rewrite-repair-2' returned 6 records

[15:50:56] [DEBUG] NDD workflow 'rewrite-evaluate-3' starting with 6 records

[15:50:56] [DEBUG] NDD workflow 'rewrite-evaluate-3': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:50:56] [INFO] 🎨 Creating Data Designer dataset

[15:50:56] [INFO] ✅ Validation passed

[15:50:56] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:50:56] [INFO] 🩺 Running health checks for models...

[15:50:56] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:50:57] [INFO]   |-- ✅ Passed!

[15:50:57] [INFO] ⏳ Processing batch 1 of 1

[15:50:57] [INFO] 🌱 Sampling 6 records from seed dataset

[15:50:57] [INFO]   |-- seed dataset size: 6 records

[15:50:57] [INFO]   |-- sampling strategy: ordered

[15:50:57] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:50:57] [INFO]   |-- generator_function: '_quality_reanswer'

[15:50:57] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:50:57] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:50:57] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:50:57] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:50:57] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:51:01] [INFO]   |-- 🌑 custom column '_quality_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.24 rec/s, eta 21.2s

[15:51:02] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.42 rec/s, eta 9.6s

[15:51:02] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.57 rec/s, eta 5.3s

[15:51:04] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.58 rec/s, eta 3.5s

[15:51:05] [INFO]   |-- 🌖 custom column '_quality_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.60 rec/s, eta 1.7s

[15:51:06] [INFO]   |-- 🌕 custom column '_quality_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.67 rec/s, eta 0.0s

[15:51:06] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:51:06] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:51:06] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:51:06] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:51:06] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:51:06] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:51:06] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:51:10] [INFO]   |-- 🌧️ custom column '_privacy_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.26 rec/s, eta 19.5s

[15:51:11] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.36 rec/s, eta 11.3s

[15:51:12] [WARNING] Evaluator returned malformed privacy answer set; missing=[23] duplicate=[] extra=[]. Applying conservative normalization.

[15:51:12] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.51 rec/s, eta 5.8s

[15:51:13] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.57 rec/s, eta 3.5s

[15:51:16] [INFO]   |-- 🌤️ custom column '_privacy_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.51 rec/s, eta 2.0s

[15:51:16] [INFO]   |-- ☀️ custom column '_privacy_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.61 rec/s, eta 0.0s

[15:51:16] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:51:16] [INFO]   |-- generator_function: '_quality_compare'

[15:51:16] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:51:16] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:51:16] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:51:16] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:51:16] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:51:21] [INFO]   |-- 🥚 custom column '_quality_qa_compare' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.19 rec/s, eta 26.3s

[15:51:21] [INFO]   |-- 🐣 custom column '_quality_qa_compare' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.36 rec/s, eta 11.2s

[15:51:22] [INFO]   |-- 🐥 custom column '_quality_qa_compare' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.50 rec/s, eta 6.0s

[15:51:27] [INFO]   |-- 🐥 custom column '_quality_qa_compare' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.36 rec/s, eta 5.6s

[15:51:28] [INFO]   |-- 🐤 custom column '_quality_qa_compare' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.40 rec/s, eta 2.5s

[15:51:35] [INFO]   |-- 🐔 custom column '_quality_qa_compare' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.31 rec/s, eta 0.0s

[15:51:35] [INFO] 🔧 Custom column config for column 'utility_score'

[15:51:35] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:51:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:51:35] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:51:35] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:51:35] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:51:35] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:51:35] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:51:35] [INFO]   |-- 🐱 custom column 'utility_score' progress: 1/6 (17%) complete, 1 ok, 0 failed, 755.26 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 😺 custom column 'utility_score' progress: 2/6 (33%) complete, 2 ok, 0 failed, 991.47 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 😸 custom column 'utility_score' progress: 3/6 (50%) complete, 3 ok, 0 failed, 1062.35 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 😸 custom column 'utility_score' progress: 4/6 (67%) complete, 4 ok, 0 failed, 1199.48 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 😼 custom column 'utility_score' progress: 5/6 (83%) complete, 5 ok, 0 failed, 1272.04 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 🦁 custom column 'utility_score' progress: 6/6 (100%) complete, 6 ok, 0 failed, 1430.83 rec/s, eta 0.0s

[15:51:35] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:51:35] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:51:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:51:35] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:51:35] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:51:35] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:51:35] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:51:35] [INFO]   |-- 🚶 custom column '_needs_repair' progress: 1/6 (17%) complete, 1 ok, 0 failed, 2964.80 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 🐴 custom column '_needs_repair' progress: 2/6 (33%) complete, 2 ok, 0 failed, 3466.71 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 3/6 (50%) complete, 3 ok, 0 failed, 3698.19 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 4/6 (67%) complete, 4 ok, 0 failed, 3698.28 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- ✈️ custom column '_needs_repair' progress: 5/6 (83%) complete, 5 ok, 0 failed, 3714.25 rec/s, eta 0.0s

[15:51:35] [INFO]   |-- 🚀 custom column '_needs_repair' progress: 6/6 (100%) complete, 6 ok, 0 failed, 3072.46 rec/s, eta 0.0s

[15:51:35] [INFO] 📊 Model usage summary:

[15:51:35] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:51:35] [INFO]   |-- tokens: input=23107, output=28041, total=51148, tps=1325

[15:51:35] [INFO]   |-- requests: success=18, failed=0, total=18, rpm=27

[15:51:35] [INFO] 📐 Measuring dataset column statistics:

[15:51:35] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:51:35] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:51:35] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:51:35] [INFO]   |-- 🔧 column: 'utility_score'

[15:51:35] [INFO]   |-- 🔧 column: '_needs_repair'

[15:51:35] [DEBUG] NDD workflow 'rewrite-evaluate-3' returned 6 records

[15:51:35] [DEBUG] NDD workflow 'rewrite-final-judge' starting with 23 records

[15:51:35] [DEBUG] NDD workflow 'rewrite-final-judge': 2 columns ['_judge_evaluation', 'needs_human_review']

[15:51:35] [INFO] 🎨 Creating Data Designer dataset

[15:51:35] [INFO] ✅ Validation passed

[15:51:35] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:51:35] [INFO] 🩺 Running health checks for models...

[15:51:35] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:51:37] [INFO]   |-- ✅ Passed!

[15:51:37] [INFO] ⏳ Processing batch 1 of 1

[15:51:37] [INFO] 🌱 Sampling 23 records from seed dataset

[15:51:37] [INFO]   |-- seed dataset size: 23 records

[15:51:37] [INFO]   |-- sampling strategy: ordered

[15:51:37] [INFO] ⚖️ llm-judge model config for column '_judge_evaluation'

[15:51:37] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:51:37] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:51:37] [INFO]   |-- model provider: 'nvidia'

[15:51:37] [INFO]   |-- inference parameters:

[15:51:37] [INFO]   |  |-- generation_type=chat-completion

[15:51:37] [INFO]   |  |-- max_parallel_requests=16

[15:51:37] [INFO]   |  |-- timeout=300

[15:51:37] [INFO]   |  |-- temperature=0.40

[15:51:37] [INFO]   |  |-- top_p=1.00

[15:51:37] [INFO]   |  |-- max_tokens=8192

[15:51:37] [INFO] ⚡️ Processing llm-judge column '_judge_evaluation' with 16 concurrent workers

[15:51:37] [INFO] ⏱️ llm-judge column '_judge_evaluation' will report progress every 2 records

[15:51:42] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.45 rec/s, eta 46.2s

[15:51:42] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.79 rec/s, eta 24.0s

[15:51:44] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.88 rec/s, eta 19.2s

[15:51:45] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1.08 rec/s, eta 13.9s

[15:51:45] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 10/23 (43%) complete, 10 ok, 0 failed, 1.32 rec/s, eta 9.8s

[15:51:45] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 12/23 (52%) complete, 12 ok, 0 failed, 1.51 rec/s, eta 7.3s

[15:51:46] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 14/23 (61%) complete, 14 ok, 0 failed, 1.55 rec/s, eta 5.8s

[15:51:47] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 16/23 (70%) complete, 16 ok, 0 failed, 1.61 rec/s, eta 4.3s

[15:51:48] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 18/23 (78%) complete, 18 ok, 0 failed, 1.65 rec/s, eta 3.0s

[15:51:50] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 20/23 (87%) complete, 20 ok, 0 failed, 1.63 rec/s, eta 1.8s

[15:51:53] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 22/23 (96%) complete, 22 ok, 0 failed, 1.39 rec/s, eta 0.7s

[15:51:53] [INFO]   |-- 🤩 llm-judge column '_judge_evaluation' progress: 23/23 (100%) complete, 23 ok, 0 failed, 1.44 rec/s, eta 0.0s

[15:51:53] [INFO] 🔧 Custom column config for column 'needs_human_review'

[15:51:53] [INFO]   |-- generator_function: '_determine_needs_human_review'

[15:51:53] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:51:53] [INFO]   |-- required_columns: ['_rewritten_text', 'utility_score', 'leakage_mass', 'any_high_leaked']

[15:51:53] [INFO]   |-- generator_params: flag_utility_below=0.5 flag_leakage_mass_above=2.0

[15:51:53] [INFO] ⚡️ Processing custom column 'needs_human_review' with 4 concurrent workers

[15:51:53] [INFO] ⏱️ custom column 'needs_human_review' will report progress every 2 records

[15:51:53] [INFO]   |-- 🚶 custom column 'needs_human_review' progress: 2/23 (9%) complete, 2 ok, 0 failed, 2038.91 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🚶 custom column 'needs_human_review' progress: 4/23 (17%) complete, 4 ok, 0 failed, 2409.40 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🐴 custom column 'needs_human_review' progress: 6/23 (26%) complete, 6 ok, 0 failed, 2747.25 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🐴 custom column 'needs_human_review' progress: 8/23 (35%) complete, 8 ok, 0 failed, 2928.79 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🐴 custom column 'needs_human_review' progress: 10/23 (43%) complete, 10 ok, 0 failed, 2710.46 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🚗 custom column 'needs_human_review' progress: 12/23 (52%) complete, 12 ok, 0 failed, 2955.82 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🚗 custom column 'needs_human_review' progress: 16/23 (70%) complete, 16 ok, 0 failed, 3436.70 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🚗 custom column 'needs_human_review' progress: 17/23 (74%) complete, 17 ok, 0 failed, 3353.69 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- ✈️ custom column 'needs_human_review' progress: 18/23 (78%) complete, 18 ok, 0 failed, 3290.45 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- ✈️ custom column 'needs_human_review' progress: 20/23 (87%) complete, 20 ok, 0 failed, 3381.42 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- ✈️ custom column 'needs_human_review' progress: 22/23 (96%) complete, 22 ok, 0 failed, 3440.59 rec/s, eta 0.0s

[15:51:53] [INFO]   |-- 🚀 custom column 'needs_human_review' progress: 23/23 (100%) complete, 23 ok, 0 failed, 3453.22 rec/s, eta 0.0s

[15:51:54] [INFO] 📊 Model usage summary:

[15:51:54] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:51:54] [INFO]   |-- tokens: input=36603, output=35154, total=71757, tps=4403

[15:51:54] [INFO]   |-- requests: success=23, failed=0, total=23, rpm=84

[15:51:54] [INFO] 📐 Measuring dataset column statistics:

[15:51:54] [INFO]   |-- ⚖️ column: '_judge_evaluation'

[15:51:54] [INFO]   |-- 🔧 column: 'needs_human_review'

[15:51:54] [DEBUG] NDD workflow 'rewrite-final-judge' returned 23 records

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/rewrite/rewrite_workflow.py:86: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(list(parts), ignore_index=True)
[15:51:54] [INFO]   |-- 📋 Rewrite complete (0 failed) [1083.3s]

[15:51:54] [WARNING] 2 record(s) failed during pipeline processing.

[15:51:54] [DEBUG]   14304213725050faa50d174576d500b8 (entity-detection: Record missing from workflow output)

[15:51:54] [DEBUG]   9a1de4a9876c5d6f83ececb70bcbfc04 (entity-detection: Record missing from workflow output)

[15:51:54] [INFO] 🎉 Pipeline complete — 25 records processed, 2 total failures

AnonymizerResult(rows=23, columns=6, trace_columns=45, failed_records=2)

,biography,biography_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
0,"Bobby Watford, a 40‑year‑old Mexican veterinar...","Ethan Kline, a Mexican veterinarian in his 40s...",0.861538,0.0,False,False
1,Idilio Bell is a 37‑year‑old astronomer living...,Dario Hawthorne is an astronomer in his late 3...,0.871429,1.8,False,False
2,"Jodi Allison, 36, lives at 204 Bluegrass in Cl...","Leah Harper, in her late 30s, lives at 317 Map...",0.908333,0.0,False,False
3,James Mills is a 69‑year‑old paramedic who liv...,Samuel Bennett is in his late 60s and works as...,0.681818,0.0,False,False
4,Nancy Burton is a 21‑year‑old cashier who live...,Claire Hawkins is in her early twenties and wo...,0.9,0.0,False,False

In [8]:
result.dataframe[["biography_rewritten", "utility_score", "leakage_mass", "needs_human_review"]].head()

,biography_rewritten,utility_score,leakage_mass,needs_human_review
0,"Ethan Kline, a Mexican veterinarian in his 40s...",0.861538,0.0,False
1,Dario Hawthorne is an astronomer in his late 3...,0.871429,1.8,False
2,"Leah Harper, in her late 30s, lives at 317 Map...",0.908333,0.0,False
3,Samuel Bennett is in his late 60s and works as...,0.681818,0.0,False
4,Claire Hawkins is in her early twenties and wo...,0.9,0.0,False

In [9]:
result.trace_dataframe.columns.tolist()

['biography',
 '_anonymizer_record_id',
 '_raw_detected_entities',
 '_seed_entities',
 '_initial_tagged_text',
 '_seed_entities_json',
 '_tag_notation',
 '_merged_tagged_text',
 '_validation_candidates',
 '_validated_entities',
 '_augmented_entities',
 '_merged_entities',
 '_detected_entities',
 'biography_with_spans',
 '_latent_entities',
 'final_entities',
 '_entities_by_value',
 '_entity_examples',
 '_entities_for_replace',
 '_entities_for_replace_json',
 '_replacement_map',
 '_domain',
 '_domain_supplement',
 '_sensitivity_disposition',
 '_sensitivity_disposition_block',
 '_privacy_qa',
 '_rewrite_disposition_block',
 '_meaning_units',
 '_replacement_map_for_prompt',
 '_meaning_units_serialized',
 '_full_rewrite',
 '_quality_qa',
 'biography_rewritten',
 '_repair_iterations',
 '_quality_qa_reanswer',
 '_privacy_qa_reanswer',
 '_quality_qa_compare',
 'utility_score',
 'leakage_mass',
 'any_high_leaked',
 '_needs_repair',
 '_leaked_privacy_items',
 '_rewritten_text__next',
 '_judge_evaluation',
 'needs_human_review']

## Filter by review flag

Records where automated metrics exceed thresholds are flagged for manual review.

In [10]:
df = result.dataframe
flagged = df[df["needs_human_review"] == True]  # noqa: E712
print(f"{len(flagged)} of {len(df)} records flagged for human review")
flagged.head()

1 of 23 records flagged for human review

,biography,biography_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
6,"Oscar Valenzano, a 52‑year‑old film director l...","Javier Ramos, a film director in his early 50s...",0.87,1.3,True,True