# 🕵️ Rewriting Legal Documents

Rewriting legal text (TAB dataset) with a domain-specific privacy goal
and custom entity labels tailored for legal proceedings.

#### 📚 What you'll learn

- Define domain-specific entity labels for legal text (case numbers, court names, etc.)
- Configure rewrite mode with legal-specific privacy goals
- Preview and run on court decision documents
- Triage flagged records with `needs_human_review`

> **Tip:** First time running notebooks? Start with
> [setup instructions](https://nvidia-nemo.github.io/Anonymizer/latest/tutorials/).

## ⚙️ Setup

- Check if your `NVIDIA_API_KEY` from [build.nvidia.com](https://build.nvidia.com) is registered for model access.
- Import `Detect` (for custom entity labels), `Rewrite`, and its config classes.
- `Anonymizer()` initializes with the default model provider -- no extra config needed.
- `configure_logging(enabled=False)` suppresses pipeline logs for cleaner output.
  Switch to `configure_logging(LoggingConfig.debug())` when troubleshooting.

In [2]:
import getpass
import os

if not os.getenv("NVIDIA_API_KEY"):
    key = getpass.getpass("Enter NVIDIA_API_KEY from build.nvidia.com: ").strip()
    if not key:
        raise RuntimeError("NVIDIA_API_KEY is required to run these notebooks.")
    os.environ["NVIDIA_API_KEY"] = key

In [3]:
from anonymizer import Anonymizer, AnonymizerConfig, AnonymizerInput, Detect, Rewrite, configure_logging, LoggingConfig
from anonymizer.config.rewrite import PrivacyGoal

configure_logging(LoggingConfig.default())

In [4]:
anonymizer = Anonymizer()

[16:41:39] [INFO] 🔧 Anonymizer initialized with 3 model configs
[16:41:39] [INFO]   |-- 🔎 detector:  gliner-pii-detector
[16:41:39] [INFO]   |-- ✅ validator: gpt-oss-120b
[16:41:39] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

## 📦 Input data

- [TAB (Text Anonymization Benchmark)](https://github.com/NorskRegnesentral/text-anonymization-benchmark)
  legal documents -- court decisions containing names, dates, case numbers, and other legal identifiers.
- `LEGAL_ENTITY_LABELS` defines the domain-specific entity types to detect.
  This replaces the default label set with one tailored to legal text.

In [5]:
LEGAL_ENTITY_LABELS = [
    "first_name",
    "last_name",
    "court_name",
    "organization_name",
    "company_name",
    "prison_detention_facility",
    "street_address",
    "city",
    "state",
    "country",
    "date",
    "date_time",
    "time",
    "date_of_birth",
    "age",
    "email",
    "phone_number",
    "ssn",
    "unique_id",
    "legal_role",
    "case_number",
    "application_number",
    "monetary_amount",
    "sentence_duration",
    "nationality",
]

input_data = AnonymizerInput(
    source="../data/TAB_legal_sample25.csv",
    text_column="text",
    data_summary="Legal court decisions containing personal identifiers, case numbers, and institutional references",
)

## 🎛️ Configure

- `Detect(entity_labels=...)` overrides the default entity set with legal-specific labels.
- `PrivacyGoal` tells the rewriter what to **protect** (identifiers, case numbers,
  institutional references) and what to **preserve** (legal reasoning, statutory references,
  ruling structure).

In [6]:
config = AnonymizerConfig(
    detect=Detect(
        entity_labels=LEGAL_ENTITY_LABELS,
    ),
    rewrite=Rewrite(
        privacy_goal=PrivacyGoal(
            protect="All personal identifiers, case numbers, court names, and institutional references that could identify parties",
            preserve="Legal reasoning, procedural facts, statutory references, and the structure of the ruling",
        ),
        risk_tolerance="minimal",
        max_repair_iterations=3,
    ),
)

## 👁️ Preview

- Preview on a few records to check that legal entities are detected
  and the rewrite preserves the ruling's structure.

In [ ]:
preview = anonymizer.preview(
    config=config,
    data=input_data,
    num_records=3,
)

preview.display_record(0)

[16:41:39] [INFO] 📂 Loaded 25 records from ../data/TAB_legal_sample25.csv (column: 'text')
[16:41:39] [INFO] detection labels in scope: ['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id']
[16:41:39] [INFO]   |-- 👀 Preview mode: processing 3 of 25 records
[16:41:39] [INFO] 🔍 Running entity detection on 3 records
[16:43:07] [INFO]   |-- 📋 Detection complete — 141 entities found across 3 records (0 failed) [87.2s]
[16:43:07] [INFO]   |-- labels: date=51, court_name=35, legal_role=10, nationality=7, last_name=7, organization_name=6, country=5, first_name=5, city=5, application_number=3, date_of_birth=3, monetary_amount=2, case_number=1, sentence_duration=1
[16:43:07] [INFO] ✏️ Running rewrite pipeline

In [ ]:
preview.display_record(1)

## 🚀 Full run

- `result.dataframe` has user-facing columns: rewritten text, scores, and the review flag.

In [ ]:
result = anonymizer.run(config=config, data=input_data)

result.dataframe.head()

[14:33:42] [INFO] 📂 Loaded 25 records from ../data/TAB_legal_sample25.csv (column: 'text')

[14:33:42] [INFO] detection labels in scope: ['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id']

[14:33:42] [INFO] 🔍 Running entity detection on 25 records

[14:33:42] [INFO] 🎨 Creating Data Designer dataset

[14:33:42] [INFO] ✅ Validation passed

[14:33:42] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[14:33:42] [INFO] 🩺 Running health checks for models...

[14:33:42] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...

[14:33:43] [INFO]   |-- ✅ Passed!

[14:33:43] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[14:33:43] [INFO]   |-- ✅ Passed!

[14:33:43] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_04-03-2026_143343' instead.

[14:33:43] [INFO] ⏳ Processing batch 1 of 1

[14:33:43] [INFO] 🌱 Sampling 25 records from seed dataset

[14:33:43] [INFO]   |-- seed dataset size: 25 records

[14:33:43] [INFO]   |-- sampling strategy: ordered

[14:33:43] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[14:33:43] [INFO]   |-- model: 'nvidia/gliner-pii'

[14:33:43] [INFO]   |-- model alias: 'gliner-pii-detector'

[14:33:43] [INFO]   |-- model provider: 'nvidia'

[14:33:43] [INFO]   |-- inference parameters:

[14:33:43] [INFO]   |  |-- generation_type=chat-completion

[14:33:43] [INFO]   |  |-- max_parallel_requests=1

[14:33:43] [INFO]   |  |-- timeout=120

[14:33:43] [INFO]   |  |-- extra_body={'labels': ['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[14:33:43] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 1 concurrent workers

[14:33:43] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress every 2 records

[14:33:44] [INFO]   |-- 😴 llm-text column '_raw_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1.44 rec/s, eta 16.0s

[14:33:46] [INFO]   |-- 😴 llm-text column '_raw_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1.39 rec/s, eta 15.1s

[14:33:47] [INFO]   |-- 😴 llm-text column '_raw_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1.54 rec/s, eta 12.4s

[14:33:48] [INFO]   |-- 🥱 llm-text column '_raw_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1.49 rec/s, eta 11.4s

[14:33:49] [INFO]   |-- 🥱 llm-text column '_raw_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1.55 rec/s, eta 9.7s

[14:33:51] [INFO]   |-- 🥱 llm-text column '_raw_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1.56 rec/s, eta 8.3s

[14:33:57] [INFO]   |-- 😐 llm-text column '_raw_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1.01 rec/s, eta 10.8s

[14:33:58] [INFO]   |-- 😐 llm-text column '_raw_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1.04 rec/s, eta 8.7s

[14:34:04] [INFO]   |-- 😐 llm-text column '_raw_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.86 rec/s, eta 8.1s

[14:34:10] [INFO]   |-- 😊 llm-text column '_raw_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.75 rec/s, eta 6.6s

[14:34:13] [INFO]   |-- 😊 llm-text column '_raw_detected_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.73 rec/s, eta 4.1s

[14:34:14] [INFO]   |-- 😊 llm-text column '_raw_detected_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.77 rec/s, eta 1.3s

[14:34:15] [INFO]   |-- 🤩 llm-text column '_raw_detected_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.78 rec/s, eta 0.0s

[14:34:15] [INFO] 🔧 Custom column config for column '_seed_entities'

[14:34:15] [INFO]   |-- generator_function: 'parse_detected_entities'

[14:34:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:34:15] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[14:34:15] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[14:34:15] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[14:34:15] [INFO] ⏱️ custom column '_seed_entities' will report progress every 2 records

[14:34:15] [INFO]   |-- 🚶 custom column '_seed_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 755.03 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚶 custom column '_seed_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 871.17 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚶 custom column '_seed_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 991.11 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1026.55 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1053.48 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1072.07 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 965.41 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1050.43 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 995.27 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- ✈️ custom column '_seed_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1021.62 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- ✈️ custom column '_seed_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 1055.16 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- ✈️ custom column '_seed_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 1104.65 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🚀 custom column '_seed_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 1135.52 rec/s, eta 0.0s

[14:34:15] [INFO] 🔧 Custom column config for column '_validation_candidates'

[14:34:15] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[14:34:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:34:15] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[14:34:15] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[14:34:15] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[14:34:15] [INFO] ⏱️ custom column '_validation_candidates' will report progress every 2 records

[14:34:15] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1965.20 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2231.21 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2256.63 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2523.93 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2408.94 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2324.77 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2368.33 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2551.65 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2599.18 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2545.18 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2588.32 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2675.64 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🦁 custom column '_validation_candidates' progress: 25/25 (100%) complete, 25 ok, 0 failed, 2712.66 rec/s, eta 0.0s

[14:34:15] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[14:34:15] [INFO]   |-- generator_function: 'build_validation_skeleton'

[14:34:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:34:15] [INFO]   |-- required_columns: ['_validation_candidates']

[14:34:15] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[14:34:15] [INFO] ⏱️ custom column '_validation_skeleton' will report progress every 2 records

[14:34:15] [INFO]   |-- 🥚 custom column '_validation_skeleton' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2681.41 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🥚 custom column '_validation_skeleton' progress: 4/25 (16%) complete, 4 ok, 0 failed, 3361.93 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🥚 custom column '_validation_skeleton' progress: 6/25 (24%) complete, 6 ok, 0 failed, 3267.16 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐣 custom column '_validation_skeleton' progress: 8/25 (32%) complete, 8 ok, 0 failed, 3591.74 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐣 custom column '_validation_skeleton' progress: 10/25 (40%) complete, 10 ok, 0 failed, 3455.52 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐣 custom column '_validation_skeleton' progress: 12/25 (48%) complete, 12 ok, 0 failed, 3503.61 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐥 custom column '_validation_skeleton' progress: 14/25 (56%) complete, 14 ok, 0 failed, 3575.42 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐥 custom column '_validation_skeleton' progress: 16/25 (64%) complete, 16 ok, 0 failed, 3781.76 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐥 custom column '_validation_skeleton' progress: 18/25 (72%) complete, 18 ok, 0 failed, 3878.93 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐤 custom column '_validation_skeleton' progress: 20/25 (80%) complete, 20 ok, 0 failed, 3800.29 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐤 custom column '_validation_skeleton' progress: 22/25 (88%) complete, 22 ok, 0 failed, 3930.68 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐤 custom column '_validation_skeleton' progress: 24/25 (96%) complete, 24 ok, 0 failed, 4012.73 rec/s, eta 0.0s

[14:34:15] [INFO]   |-- 🐔 custom column '_validation_skeleton' progress: 25/25 (100%) complete, 25 ok, 0 failed, 4036.30 rec/s, eta 0.0s

[14:34:15] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[14:34:15] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:34:15] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:34:15] [INFO]   |-- model provider: 'nvidia'

[14:34:15] [INFO]   |-- inference parameters:

[14:34:15] [INFO]   |  |-- generation_type=chat-completion

[14:34:15] [INFO]   |  |-- max_parallel_requests=2

[14:34:15] [INFO]   |  |-- timeout=300

[14:34:15] [INFO]   |  |-- temperature=0.30

[14:34:15] [INFO]   |  |-- top_p=0.95

[14:34:15] [INFO]   |  |-- max_tokens=16384

[14:34:15] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 2 concurrent workers

[14:34:15] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress every 2 records

[14:34:36] [INFO]   |-- 🌧️ llm-structured column '_validation_decisions' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.10 rec/s, eta 233.7s

[14:34:59] [INFO]   |-- 🌧️ llm-structured column '_validation_decisions' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.09 rec/s, eta 228.7s

[14:35:19] [INFO]   |-- 🌧️ llm-structured column '_validation_decisions' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.09 rec/s, eta 201.9s

[14:35:47] [INFO]   |-- 🌦️ llm-structured column '_validation_decisions' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.09 rec/s, eta 194.7s

[14:36:14] [INFO]   |-- 🌦️ llm-structured column '_validation_decisions' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.08 rec/s, eta 178.4s

[14:36:54] [INFO]   |-- 🌦️ llm-structured column '_validation_decisions' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.08 rec/s, eta 172.5s

[14:37:18] [INFO]   |-- ⛅ llm-structured column '_validation_decisions' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.08 rec/s, eta 143.6s

[14:37:49] [INFO]   |-- ⛅ llm-structured column '_validation_decisions' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.07 rec/s, eta 120.1s

[14:38:18] [INFO]   |-- ⛅ llm-structured column '_validation_decisions' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.07 rec/s, eta 94.2s

[14:38:40] [INFO]   |-- 🌤️ llm-structured column '_validation_decisions' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.08 rec/s, eta 66.3s

[14:39:06] [INFO]   |-- 🌤️ llm-structured column '_validation_decisions' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.08 rec/s, eta 39.6s

[14:39:31] [INFO]   |-- 🌤️ llm-structured column '_validation_decisions' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.08 rec/s, eta 13.2s

[14:39:48] [INFO]   |-- ☀️ llm-structured column '_validation_decisions' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.08 rec/s, eta 0.0s

[14:39:48] [INFO] 🔧 Custom column config for column '_validated_entities'

[14:39:48] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[14:39:48] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:39:48] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[14:39:48] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[14:39:48] [INFO] ⏱️ custom column '_validated_entities' will report progress every 2 records

[14:39:48] [INFO]   |-- 🚶 custom column '_validated_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1114.21 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚶 custom column '_validated_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1331.48 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚶 custom column '_validated_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1494.97 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🐴 custom column '_validated_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1702.07 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🐴 custom column '_validated_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1775.23 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🐴 custom column '_validated_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1837.19 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚗 custom column '_validated_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1838.23 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚗 custom column '_validated_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1992.73 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚗 custom column '_validated_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2009.87 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- ✈️ custom column '_validated_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2136.93 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- ✈️ custom column '_validated_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2116.07 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- ✈️ custom column '_validated_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2219.99 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🚀 custom column '_validated_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 2242.38 rec/s, eta 0.0s

[14:39:48] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[14:39:48] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[14:39:48] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:39:48] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[14:39:48] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[14:39:48] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[14:39:48] [INFO] ⏱️ custom column '_seed_entities_json' will report progress every 2 records

[14:39:48] [INFO]   |-- 🌑 custom column '_seed_entities_json' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1654.72 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌑 custom column '_seed_entities_json' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1944.82 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌑 custom column '_seed_entities_json' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1959.24 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌘 custom column '_seed_entities_json' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2203.63 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌘 custom column '_seed_entities_json' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1979.81 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌘 custom column '_seed_entities_json' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2133.41 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌗 custom column '_seed_entities_json' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2150.21 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌗 custom column '_seed_entities_json' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2106.45 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌗 custom column '_seed_entities_json' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2156.98 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌖 custom column '_seed_entities_json' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2179.48 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌖 custom column '_seed_entities_json' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2234.10 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌖 custom column '_seed_entities_json' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2311.48 rec/s, eta 0.0s

[14:39:48] [INFO]   |-- 🌕 custom column '_seed_entities_json' progress: 25/25 (100%) complete, 25 ok, 0 failed, 2363.03 rec/s, eta 0.0s

[14:39:48] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[14:39:48] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:39:48] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:39:48] [INFO]   |-- model provider: 'nvidia'

[14:39:48] [INFO]   |-- inference parameters:

[14:39:48] [INFO]   |  |-- generation_type=chat-completion

[14:39:48] [INFO]   |  |-- max_parallel_requests=2

[14:39:48] [INFO]   |  |-- timeout=300

[14:39:48] [INFO]   |  |-- temperature=0.30

[14:39:48] [INFO]   |  |-- top_p=0.95

[14:39:48] [INFO]   |  |-- max_tokens=16384

[14:39:48] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 2 concurrent workers

[14:39:48] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress every 2 records

[14:39:56] [INFO]   |-- 🚶 llm-structured column '_augmented_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.24 rec/s, eta 93.9s

[14:40:01] [INFO]   |-- 🚶 llm-structured column '_augmented_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.31 rec/s, eta 68.1s

[14:40:12] [INFO]   |-- 🚶 llm-structured column '_augmented_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.25 rec/s, eta 74.6s

[14:40:18] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.26 rec/s, eta 64.3s

[14:40:23] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.28 rec/s, eta 52.9s

[14:40:30] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.28 rec/s, eta 45.9s

[14:40:40] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.27 rec/s, eta 41.1s

[14:40:46] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.28 rec/s, eta 32.3s

[14:40:53] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.28 rec/s, eta 25.4s

[14:40:58] [INFO]   |-- ✈️ llm-structured column '_augmented_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.29 rec/s, eta 17.5s

[14:41:05] [INFO]   |-- ✈️ llm-structured column '_augmented_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.28 rec/s, eta 10.5s

[14:41:11] [INFO]   |-- ✈️ llm-structured column '_augmented_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.29 rec/s, eta 3.5s

[14:41:15] [INFO]   |-- 🚀 llm-structured column '_augmented_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.29 rec/s, eta 0.0s

[14:41:15] [INFO] 🔧 Custom column config for column '_merged_entities'

[14:41:15] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[14:41:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:41:15] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[14:41:15] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[14:41:15] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[14:41:15] [INFO] ⏱️ custom column '_merged_entities' will report progress every 2 records

[14:41:15] [INFO]   |-- 🥚 custom column '_merged_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 691.46 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🥚 custom column '_merged_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 743.05 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🥚 custom column '_merged_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 671.81 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐣 custom column '_merged_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 698.62 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐣 custom column '_merged_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 777.94 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐣 custom column '_merged_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 836.39 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐥 custom column '_merged_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 824.82 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐥 custom column '_merged_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 885.37 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐥 custom column '_merged_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 920.79 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐤 custom column '_merged_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 989.75 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐤 custom column '_merged_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 994.40 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐤 custom column '_merged_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 1021.58 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🐔 custom column '_merged_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 1053.77 rec/s, eta 0.0s

[14:41:15] [INFO] 🔧 Custom column config for column '_detected_entities'

[14:41:15] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[14:41:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:41:15] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[14:41:15] [INFO]   |-- side_effect_columns: ['tagged_text']

[14:41:15] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[14:41:15] [INFO] ⏱️ custom column '_detected_entities' will report progress every 2 records

[14:41:15] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 414.65 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 328.26 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🚶 custom column '_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 304.07 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 242.96 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 246.28 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🐴 custom column '_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 220.22 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 208.10 rec/s, eta 0.1s

[14:41:15] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 193.44 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🚗 custom column '_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 206.44 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 193.23 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 193.68 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- ✈️ custom column '_detected_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 200.97 rec/s, eta 0.0s

[14:41:15] [INFO]   |-- 🚀 custom column '_detected_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 208.93 rec/s, eta 0.0s

[14:41:16] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[14:41:16] [INFO] 📊 Model usage summary:

[14:41:16] [INFO]   |-- model: nvidia/gliner-pii

[14:41:16] [INFO]   |-- tokens: input=14164, output=31919, total=46083, tps=101

[14:41:16] [INFO]   |-- requests: success=25, failed=0, total=25, rpm=3

[14:41:16] [INFO]   |--

[14:41:16] [INFO]   |-- model: openai/gpt-oss-120b

[14:41:16] [INFO]   |-- tokens: input=270556, output=167981, total=438537, tps=968

[14:41:16] [INFO]   |-- requests: success=51, failed=0, total=51, rpm=6

[14:41:16] [INFO] 📐 Measuring dataset column statistics:

[14:41:16] [INFO]   |-- 📝 column: '_raw_detected_entities'

[14:41:16] [INFO]   |-- 🔧 column: '_seed_entities'

[14:41:16] [INFO]   |-- 🔧 column: '_validation_candidates'

[14:41:16] [INFO]   |-- 🔧 column: '_validated_entities'

[14:41:16] [INFO]   |-- 🔧 column: '_seed_entities_json'

[14:41:16] [INFO]   |-- 🗂️ column: '_augmented_entities'

[14:41:16] [INFO]   |-- 🔧 column: '_merged_entities'

[14:41:16] [INFO]   |-- 🔧 column: '_detected_entities'

[14:41:16] [INFO] 🎨 Creating Data Designer dataset

[14:41:16] [INFO] ✅ Validation passed

[14:41:16] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[14:41:16] [INFO] 🩺 Running health checks for models...

[14:41:16] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[14:41:17] [INFO]   |-- ✅ Passed!

[14:41:17] [INFO] 📂 Dataset path '.anonymizer-artifacts/latent-entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/latent-entity-detection_04-03-2026_144117' instead.

[14:41:17] [INFO] ⏳ Processing batch 1 of 1

[14:41:17] [INFO] 🌱 Sampling 25 records from seed dataset

[14:41:17] [INFO]   |-- seed dataset size: 25 records

[14:41:17] [INFO]   |-- sampling strategy: ordered

[14:41:17] [INFO] 🗂️ llm-structured model config for column '_latent_entities'

[14:41:17] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[14:41:17] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[14:41:17] [INFO]   |-- model provider: 'nvidia'

[14:41:17] [INFO]   |-- inference parameters:

[14:41:17] [INFO]   |  |-- generation_type=chat-completion

[14:41:17] [INFO]   |  |-- max_parallel_requests=16

[14:41:17] [INFO]   |  |-- timeout=300

[14:41:17] [INFO]   |  |-- temperature=0.40

[14:41:17] [INFO]   |  |-- top_p=1.00

[14:41:17] [INFO]   |  |-- max_tokens=8192

[14:41:17] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers

[14:41:17] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress every 2 records

[14:41:33] [INFO]   |-- 🐱 llm-structured column '_latent_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.12 rec/s, eta 194.0s

[14:41:36] [INFO]   |-- 🐱 llm-structured column '_latent_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.21 rec/s, eta 99.8s

[14:41:38] [INFO]   |-- 🐱 llm-structured column '_latent_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.29 rec/s, eta 66.6s

[14:41:42] [INFO]   |-- 😺 llm-structured column '_latent_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.32 rec/s, eta 53.5s

[14:41:42] [INFO]   |-- 😺 llm-structured column '_latent_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.39 rec/s, eta 38.4s

[14:41:44] [INFO]   |-- 😺 llm-structured column '_latent_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.44 rec/s, eta 29.7s

[14:41:51] [INFO]   |-- 😸 llm-structured column '_latent_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.41 rec/s, eta 26.9s

[14:41:52] [INFO]   |-- 😸 llm-structured column '_latent_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.46 rec/s, eta 19.7s

[14:41:55] [INFO]   |-- 😸 llm-structured column '_latent_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.46 rec/s, eta 15.1s

[14:41:57] [INFO]   |-- 😼 llm-structured column '_latent_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.49 rec/s, eta 10.2s

[14:42:01] [INFO]   |-- 😼 llm-structured column '_latent_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.49 rec/s, eta 6.1s

[14:42:03] [INFO]   |-- 😼 llm-structured column '_latent_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.52 rec/s, eta 1.9s

[14:42:13] [INFO]   |-- 🦁 llm-structured column '_latent_entities' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.44 rec/s, eta 0.0s

[14:42:13] [INFO] 📊 Model usage summary:

[14:42:13] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[14:42:13] [INFO]   |-- tokens: input=68418, output=87269, total=155687, tps=2748

[14:42:13] [INFO]   |-- requests: success=26, failed=0, total=26, rpm=27

[14:42:13] [INFO] 📐 Measuring dataset column statistics:

[14:42:13] [INFO]   |-- 🗂️ column: '_latent_entities'

[14:42:13] [INFO]   |-- 📋 Detection complete — 1278 entities found across 25 records (0 failed) [511.2s]

[14:42:13] [INFO]   |-- labels: date=417, court_name=238, legal_role=168, organization_name=85, last_name=82, nationality=54, first_name=47, city=47, country=43, application_number=26, date_of_birth=24, prison_detention_facility=15, sentence_duration=14, monetary_amount=11, state=3, case_number=1, unique_id=1, age=1, company_name=1

[14:42:13] [INFO] ✏️ Running rewrite pipeline

[14:42:13] [INFO] 🎨 Creating Data Designer dataset

[14:42:13] [INFO] ✅ Validation passed

[14:42:13] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[14:42:13] [INFO] 🩺 Running health checks for models...

[14:42:13] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[14:42:14] [INFO]   |-- ✅ Passed!

[14:42:14] [INFO] 📂 Dataset path '.anonymizer-artifacts/replace-map-generation' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/replace-map-generation_04-03-2026_144214' instead.

[14:42:14] [INFO] ⏳ Processing batch 1 of 1

[14:42:14] [INFO] 🌱 Sampling 25 records from seed dataset

[14:42:14] [INFO]   |-- seed dataset size: 25 records

[14:42:14] [INFO]   |-- sampling strategy: ordered

[14:42:14] [INFO] 🗂️ llm-structured model config for column '_replacement_map'

[14:42:14] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:42:14] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:42:14] [INFO]   |-- model provider: 'nvidia'

[14:42:14] [INFO]   |-- inference parameters:

[14:42:14] [INFO]   |  |-- generation_type=chat-completion

[14:42:14] [INFO]   |  |-- max_parallel_requests=2

[14:42:14] [INFO]   |  |-- timeout=300

[14:42:14] [INFO]   |  |-- temperature=0.30

[14:42:14] [INFO]   |  |-- top_p=0.95

[14:42:14] [INFO]   |  |-- max_tokens=16384

[14:42:14] [INFO] ⚡️ Processing llm-structured column '_replacement_map' with 2 concurrent workers

[14:42:14] [INFO] ⏱️ llm-structured column '_replacement_map' will report progress every 2 records

[14:42:29] [INFO]   |-- 🐱 llm-structured column '_replacement_map' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.13 rec/s, eta 179.2s

[14:42:43] [INFO]   |-- 🐱 llm-structured column '_replacement_map' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.14 rec/s, eta 152.8s

[14:42:59] [INFO]   |-- 🐱 llm-structured column '_replacement_map' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.13 rec/s, eta 141.9s

[14:43:19] [INFO]   |-- 😺 llm-structured column '_replacement_map' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.12 rec/s, eta 138.0s

[14:43:35] [INFO]   |-- 😺 llm-structured column '_replacement_map' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.12 rec/s, eta 122.3s

[14:43:46] [INFO]   |-- 😺 llm-structured column '_replacement_map' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.13 rec/s, eta 100.0s

[14:44:01] [INFO]   |-- 😸 llm-structured column '_replacement_map' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.13 rec/s, eta 84.0s

[14:44:19] [INFO]   |-- 😸 llm-structured column '_replacement_map' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.13 rec/s, eta 70.6s

[14:44:43] [INFO]   |-- 😸 llm-structured column '_replacement_map' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.12 rec/s, eta 57.9s

[14:44:56] [INFO]   |-- 😼 llm-structured column '_replacement_map' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.12 rec/s, eta 40.6s

[14:45:18] [INFO]   |-- 😼 llm-structured column '_replacement_map' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.12 rec/s, eta 25.1s

[14:45:33] [INFO]   |-- 😼 llm-structured column '_replacement_map' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.12 rec/s, eta 8.3s

[14:45:36] [INFO]   |-- 🦁 llm-structured column '_replacement_map' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.12 rec/s, eta 0.0s

[14:45:37] [INFO] 📊 Model usage summary:

[14:45:37] [INFO]   |-- model: openai/gpt-oss-120b

[14:45:37] [INFO]   |-- tokens: input=68628, output=85452, total=154080, tps=759

[14:45:37] [INFO]   |-- requests: success=25, failed=0, total=25, rpm=7

[14:45:37] [INFO] 📐 Measuring dataset column statistics:

[14:45:37] [INFO]   |-- 🗂️ column: '_replacement_map'

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/row_partitioning.py:42: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(list(parts), ignore_index=True)
[14:45:37] [INFO] 🎨 Creating Data Designer dataset

[14:45:37] [INFO] ✅ Validation passed

[14:45:37] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[14:45:37] [INFO] 🩺 Running health checks for models...

[14:45:37] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[14:45:38] [INFO]   |-- ✅ Passed!

[14:45:38] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-pipeline' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-pipeline_04-03-2026_144538' instead.

[14:45:38] [INFO] ⏳ Processing batch 1 of 1

[14:45:38] [INFO] 🌱 Sampling 25 records from seed dataset

[14:45:38] [INFO]   |-- seed dataset size: 25 records

[14:45:38] [INFO]   |-- sampling strategy: ordered

[14:45:38] [INFO] 🗂️ llm-structured model config for column '_domain'

[14:45:38] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:45:38] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:45:38] [INFO]   |-- model provider: 'nvidia'

[14:45:38] [INFO]   |-- inference parameters:

[14:45:38] [INFO]   |  |-- generation_type=chat-completion

[14:45:38] [INFO]   |  |-- max_parallel_requests=2

[14:45:38] [INFO]   |  |-- timeout=300

[14:45:38] [INFO]   |  |-- temperature=0.30

[14:45:38] [INFO]   |  |-- top_p=0.95

[14:45:38] [INFO]   |  |-- max_tokens=16384

[14:45:38] [INFO] ⚡️ Processing llm-structured column '_domain' with 2 concurrent workers

[14:45:38] [INFO] ⏱️ llm-structured column '_domain' will report progress every 2 records

[14:45:39] [INFO]   |-- 😴 llm-structured column '_domain' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1.45 rec/s, eta 15.9s

[14:45:40] [INFO]   |-- 😴 llm-structured column '_domain' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1.50 rec/s, eta 14.0s

[14:45:41] [INFO]   |-- 😴 llm-structured column '_domain' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1.66 rec/s, eta 11.4s

[14:45:42] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1.87 rec/s, eta 9.1s

[14:45:43] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2.01 rec/s, eta 7.5s

[14:45:43] [INFO]   |-- 🥱 llm-structured column '_domain' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2.06 rec/s, eta 6.3s

[14:45:44] [INFO]   |-- 😐 llm-structured column '_domain' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2.12 rec/s, eta 5.2s

[14:45:45] [INFO]   |-- 😐 llm-structured column '_domain' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2.18 rec/s, eta 4.1s

[14:45:46] [INFO]   |-- 😐 llm-structured column '_domain' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2.21 rec/s, eta 3.2s

[14:45:46] [INFO]   |-- 😊 llm-structured column '_domain' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2.26 rec/s, eta 2.2s

[14:45:47] [INFO]   |-- 😊 llm-structured column '_domain' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2.27 rec/s, eta 1.3s

[14:45:48] [INFO]   |-- 😊 llm-structured column '_domain' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2.25 rec/s, eta 0.4s

[14:45:48] [INFO]   |-- 🤩 llm-structured column '_domain' progress: 25/25 (100%) complete, 25 ok, 0 failed, 2.33 rec/s, eta 0.0s

[14:45:48] [INFO] 🔧 Custom column config for column '_domain_supplement'

[14:45:48] [INFO]   |-- generator_function: '_enrich_domain'

[14:45:48] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:45:48] [INFO]   |-- required_columns: ['_domain']

[14:45:48] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers

[14:45:48] [INFO] ⏱️ custom column '_domain_supplement' will report progress every 2 records

[14:45:48] [INFO]   |-- 🌧️ custom column '_domain_supplement' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1339.55 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌧️ custom column '_domain_supplement' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1533.52 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌧️ custom column '_domain_supplement' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1702.89 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌦️ custom column '_domain_supplement' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1949.42 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌦️ custom column '_domain_supplement' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2165.28 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌦️ custom column '_domain_supplement' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2235.90 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- ⛅ custom column '_domain_supplement' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2378.15 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- ⛅ custom column '_domain_supplement' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2476.80 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- ⛅ custom column '_domain_supplement' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2570.31 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌤️ custom column '_domain_supplement' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2672.84 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌤️ custom column '_domain_supplement' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2757.64 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- 🌤️ custom column '_domain_supplement' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2820.68 rec/s, eta 0.0s

[14:45:48] [INFO]   |-- ☀️ custom column '_domain_supplement' progress: 25/25 (100%) complete, 25 ok, 0 failed, 2800.00 rec/s, eta 0.0s

[14:45:48] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'

[14:45:48] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:45:48] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:45:48] [INFO]   |-- model provider: 'nvidia'

[14:45:48] [INFO]   |-- inference parameters:

[14:45:48] [INFO]   |  |-- generation_type=chat-completion

[14:45:48] [INFO]   |  |-- max_parallel_requests=2

[14:45:48] [INFO]   |  |-- timeout=300

[14:45:48] [INFO]   |  |-- temperature=0.30

[14:45:48] [INFO]   |  |-- top_p=0.95

[14:45:48] [INFO]   |  |-- max_tokens=16384

[14:45:48] [INFO] ⚡️ Processing llm-structured column '_sensitivity_disposition' with 2 concurrent workers

[14:45:48] [INFO] ⏱️ llm-structured column '_sensitivity_disposition' will report progress every 2 records

[14:46:34] [INFO]   |-- 🥚 llm-structured column '_sensitivity_disposition' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.04 rec/s, eta 521.9s

[14:47:00] [INFO]   |-- 🥚 llm-structured column '_sensitivity_disposition' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.06 rec/s, eta 376.6s

[14:47:36] [INFO]   |-- 🥚 llm-structured column '_sensitivity_disposition' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.06 rec/s, eta 340.9s

[14:48:17] [INFO]   |-- 🐣 llm-structured column '_sensitivity_disposition' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.05 rec/s, eta 314.9s

[14:48:48] [INFO]   |-- 🐣 llm-structured column '_sensitivity_disposition' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.06 rec/s, eta 269.0s

[14:49:19] [INFO]   |-- 🐣 llm-structured column '_sensitivity_disposition' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.06 rec/s, eta 228.1s

[14:50:32] [INFO]   |-- 🐥 llm-structured column '_sensitivity_disposition' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.05 rec/s, eta 223.2s

[14:51:04] [INFO]   |-- 🐥 llm-structured column '_sensitivity_disposition' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.05 rec/s, eta 177.3s

[14:51:51] [INFO]   |-- 🐥 llm-structured column '_sensitivity_disposition' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.05 rec/s, eta 141.0s

[14:52:23] [INFO]   |-- 🐤 llm-structured column '_sensitivity_disposition' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.05 rec/s, eta 98.7s

[14:52:59] [INFO]   |-- 🐤 llm-structured column '_sensitivity_disposition' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.05 rec/s, eta 58.8s

[14:53:43] [INFO]   |-- 🐤 llm-structured column '_sensitivity_disposition' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.05 rec/s, eta 19.8s

[14:53:49] [INFO]   |-- 🐔 llm-structured column '_sensitivity_disposition' progress: 25/25 (100%) complete, 25 ok, 0 failed, 0.05 rec/s, eta 0.0s

[14:53:49] [INFO] 🔧 Custom column config for column '_sensitivity_disposition_block'

[14:53:49] [INFO]   |-- generator_function: '_format_disposition_block'

[14:53:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:53:49] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[14:53:49] [INFO] ⚡️ Processing custom column '_sensitivity_disposition_block' with 4 concurrent workers

[14:53:49] [INFO] ⏱️ custom column '_sensitivity_disposition_block' will report progress every 2 records

[14:53:49] [INFO]   |-- 🚶 custom column '_sensitivity_disposition_block' progress: 2/25 (8%) complete, 2 ok, 0 failed, 617.98 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🚶 custom column '_sensitivity_disposition_block' progress: 4/25 (16%) complete, 4 ok, 0 failed, 568.73 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🚶 custom column '_sensitivity_disposition_block' progress: 6/25 (24%) complete, 6 ok, 0 failed, 697.57 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐴 custom column '_sensitivity_disposition_block' progress: 8/25 (32%) complete, 8 ok, 0 failed, 852.11 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐴 custom column '_sensitivity_disposition_block' progress: 10/25 (40%) complete, 10 ok, 0 failed, 919.03 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐴 custom column '_sensitivity_disposition_block' progress: 12/25 (48%) complete, 12 ok, 0 failed, 986.45 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🚗 custom column '_sensitivity_disposition_block' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1053.50 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🚗 custom column '_sensitivity_disposition_block' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1155.09 rec/s, eta 0.0s

[14:53:49] [WARNING] ⚠️ Custom generator function '_format_disposition_block' failed for column '_sensitivity_disposition_block'. This record will be skipped.
2 validation errors for SensitivityDispositionSchema
sensitivity_disposition.8
  Value error, Entity 9: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 9, 'source': 'tagg...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
sensitivity_disposition.9
  Value error, Entity 10: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 10, 'source': 'tag...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[14:53:49] [INFO]   |-- 🚗 custom column '_sensitivity_disposition_block' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1222.76 rec/s, eta 0.0s

[14:53:49] [WARNING] ⚠️ Generation for record at index 18 failed. Will omit this record from the dataset.
Custom generator function failed for column '_sensitivity_disposition_block': 2 validation errors for SensitivityDispositionSchema
sensitivity_disposition.8
  Value error, Entity 9: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 9, 'source': 'tagg...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
sensitivity_disposition.9
  Value error, Entity 10: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 10, 'source': 'tag...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[14:53:49] [INFO]   |-- ✈️ custom column '_sensitivity_disposition_block' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1211.31 rec/s, eta 0.0s

[14:53:49] [WARNING] ⚠️ Custom generator function '_format_disposition_block' failed for column '_sensitivity_disposition_block'. This record will be skipped.
1 validation error for SensitivityDispositionSchema
sensitivity_disposition.30
  Value error, Entity 31: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 31, 'source': 'tag...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[14:53:49] [INFO]   |-- ✈️ custom column '_sensitivity_disposition_block' progress: 22/25 (88%) complete, 21 ok, 1 failed, 1211.18 rec/s, eta 0.0s

[14:53:49] [WARNING] ⚠️ Generation for record at index 23 failed. Will omit this record from the dataset.
Custom generator function failed for column '_sensitivity_disposition_block': 1 validation error for SensitivityDispositionSchema
sensitivity_disposition.30
  Value error, Entity 31: needs_protection=True cannot have protection_method_suggestion='leave_as_is' [type=value_error, input_value={'id': 31, 'source': 'tag...ined_risk_level': 'low'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[14:53:49] [INFO]   |-- ✈️ custom column '_sensitivity_disposition_block' progress: 24/25 (96%) complete, 23 ok, 1 failed, 1290.14 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🚀 custom column '_sensitivity_disposition_block' progress: 25/25 (100%) complete, 23 ok, 2 failed, 1312.51 rec/s, eta 0.0s

[14:53:49] [INFO] 🔧 Custom column config for column '_privacy_qa'

[14:53:49] [INFO]   |-- generator_function: '_generate_privacy_qa_column'

[14:53:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:53:49] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[14:53:49] [INFO] ⚡️ Processing custom column '_privacy_qa' with 4 concurrent workers

[14:53:49] [INFO] ⏱️ custom column '_privacy_qa' will report progress every 2 records

[14:53:49] [INFO]   |-- 🐱 custom column '_privacy_qa' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1753.23 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐱 custom column '_privacy_qa' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1961.02 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐱 custom column '_privacy_qa' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1942.85 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😺 custom column '_privacy_qa' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2087.68 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😺 custom column '_privacy_qa' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1983.24 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😺 custom column '_privacy_qa' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2007.61 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😸 custom column '_privacy_qa' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2149.90 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😸 custom column '_privacy_qa' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2129.32 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😸 custom column '_privacy_qa' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2259.13 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😼 custom column '_privacy_qa' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2226.24 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😼 custom column '_privacy_qa' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2314.76 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 😼 custom column '_privacy_qa' progress: 23/25 (92%) complete, 23 ok, 0 failed, 2351.71 rec/s, eta 0.0s

[14:53:49] [INFO] 🔧 Custom column config for column '_rewrite_disposition_block'

[14:53:49] [INFO]   |-- generator_function: '_format_rewrite_disposition_block'

[14:53:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:53:49] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[14:53:49] [INFO] ⚡️ Processing custom column '_rewrite_disposition_block' with 4 concurrent workers

[14:53:49] [INFO] ⏱️ custom column '_rewrite_disposition_block' will report progress every 2 records

[14:53:49] [INFO]   |-- 🥚 custom column '_rewrite_disposition_block' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1838.16 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🥚 custom column '_rewrite_disposition_block' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2012.96 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🥚 custom column '_rewrite_disposition_block' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2074.15 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐣 custom column '_rewrite_disposition_block' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2394.91 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐣 custom column '_rewrite_disposition_block' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2262.61 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐣 custom column '_rewrite_disposition_block' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2342.51 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐥 custom column '_rewrite_disposition_block' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2412.01 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐥 custom column '_rewrite_disposition_block' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2519.73 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐥 custom column '_rewrite_disposition_block' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2507.60 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐤 custom column '_rewrite_disposition_block' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2713.38 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐤 custom column '_rewrite_disposition_block' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2775.09 rec/s, eta 0.0s

[14:53:49] [INFO]   |-- 🐤 custom column '_rewrite_disposition_block' progress: 23/25 (92%) complete, 23 ok, 0 failed, 2826.68 rec/s, eta 0.0s

[14:53:49] [INFO] 🗂️ llm-structured model config for column '_meaning_units'

[14:53:49] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:53:49] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:53:49] [INFO]   |-- model provider: 'nvidia'

[14:53:49] [INFO]   |-- inference parameters:

[14:53:49] [INFO]   |  |-- generation_type=chat-completion

[14:53:49] [INFO]   |  |-- max_parallel_requests=2

[14:53:49] [INFO]   |  |-- timeout=300

[14:53:49] [INFO]   |  |-- temperature=0.30

[14:53:49] [INFO]   |  |-- top_p=0.95

[14:53:49] [INFO]   |  |-- max_tokens=16384

[14:53:49] [INFO] ⚡️ Processing llm-structured column '_meaning_units' with 2 concurrent workers

[14:53:49] [INFO] ⏱️ llm-structured column '_meaning_units' will report progress every 2 records

[14:54:00] [INFO]   |-- 😴 llm-structured column '_meaning_units' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.19 rec/s, eta 121.1s

[14:54:19] [INFO]   |-- 😴 llm-structured column '_meaning_units' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.13 rec/s, eta 155.7s

[14:54:30] [INFO]   |-- 😴 llm-structured column '_meaning_units' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.15 rec/s, eta 129.7s

[14:54:42] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.15 rec/s, eta 112.9s

[14:54:54] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.15 rec/s, eta 97.0s

[14:55:04] [INFO]   |-- 🥱 llm-structured column '_meaning_units' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.16 rec/s, eta 80.6s

[14:55:12] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.17 rec/s, eta 65.0s

[14:55:23] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.17 rec/s, eta 52.5s

[14:55:39] [INFO]   |-- 😐 llm-structured column '_meaning_units' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.16 rec/s, eta 42.6s

[14:55:48] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.17 rec/s, eta 29.7s

[14:55:59] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.17 rec/s, eta 17.7s

[14:56:10] [INFO]   |-- 😊 llm-structured column '_meaning_units' progress: 23/25 (92%) complete, 23 ok, 0 failed, 0.16 rec/s, eta 12.2s

[14:56:10] [INFO] 🔧 Custom column config for column '_replacement_map_for_prompt'

[14:56:10] [INFO]   |-- generator_function: '_filter_replacement_map_for_prompt'

[14:56:10] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:56:10] [INFO]   |-- required_columns: ['_replacement_map', '_rewrite_disposition_block']

[14:56:10] [INFO] ⚡️ Processing custom column '_replacement_map_for_prompt' with 4 concurrent workers

[14:56:10] [INFO] ⏱️ custom column '_replacement_map_for_prompt' will report progress every 2 records

[14:56:10] [INFO]   |-- 🥚 custom column '_replacement_map_for_prompt' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1384.00 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🥚 custom column '_replacement_map_for_prompt' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1652.61 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🥚 custom column '_replacement_map_for_prompt' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1922.82 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_replacement_map_for_prompt' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2064.18 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_replacement_map_for_prompt' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2203.74 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_replacement_map_for_prompt' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2336.66 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_replacement_map_for_prompt' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2289.25 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_replacement_map_for_prompt' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2359.68 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_replacement_map_for_prompt' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2343.24 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_replacement_map_for_prompt' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2355.22 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_replacement_map_for_prompt' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2434.92 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_replacement_map_for_prompt' progress: 23/25 (92%) complete, 23 ok, 0 failed, 2430.99 rec/s, eta 0.0s

[14:56:10] [INFO] 🔧 Custom column config for column '_meaning_units_serialized'

[14:56:10] [INFO]   |-- generator_function: '_serialize_meaning_units'

[14:56:10] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[14:56:10] [INFO]   |-- required_columns: ['_meaning_units']

[14:56:10] [INFO] ⚡️ Processing custom column '_meaning_units_serialized' with 4 concurrent workers

[14:56:10] [INFO] ⏱️ custom column '_meaning_units_serialized' will report progress every 2 records

[14:56:10] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 2/25 (8%) complete, 2 ok, 0 failed, 2265.43 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2761.95 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 6/25 (24%) complete, 6 ok, 0 failed, 3080.94 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 8/25 (32%) complete, 8 ok, 0 failed, 3402.14 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 10/25 (40%) complete, 10 ok, 0 failed, 3534.61 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 12/25 (48%) complete, 12 ok, 0 failed, 3759.20 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 14/25 (56%) complete, 14 ok, 0 failed, 3794.21 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 16/25 (64%) complete, 16 ok, 0 failed, 3940.00 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 18/25 (72%) complete, 18 ok, 0 failed, 3891.30 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 20/25 (80%) complete, 20 ok, 0 failed, 4038.23 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 22/25 (88%) complete, 22 ok, 0 failed, 4078.01 rec/s, eta 0.0s

[14:56:10] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 23/25 (92%) complete, 23 ok, 0 failed, 4062.68 rec/s, eta 0.0s

[14:56:10] [INFO] 🗂️ llm-structured model config for column '_full_rewrite'

[14:56:10] [INFO]   |-- model: 'openai/gpt-oss-120b'

[14:56:10] [INFO]   |-- model alias: 'gpt-oss-120b'

[14:56:10] [INFO]   |-- model provider: 'nvidia'

[14:56:10] [INFO]   |-- inference parameters:

[14:56:10] [INFO]   |  |-- generation_type=chat-completion

[14:56:10] [INFO]   |  |-- max_parallel_requests=2

[14:56:10] [INFO]   |  |-- timeout=300

[14:56:10] [INFO]   |  |-- temperature=0.30

[14:56:10] [INFO]   |  |-- top_p=0.95

[14:56:10] [INFO]   |  |-- max_tokens=16384

[14:56:10] [INFO] ⚡️ Processing llm-structured column '_full_rewrite' with 2 concurrent workers

[14:56:10] [INFO] ⏱️ llm-structured column '_full_rewrite' will report progress every 2 records

[14:56:30] [INFO]   |-- 🌧️ llm-structured column '_full_rewrite' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.10 rec/s, eta 229.8s

[14:56:51] [INFO]   |-- 🌧️ llm-structured column '_full_rewrite' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.10 rec/s, eta 214.9s

[14:57:02] [INFO]   |-- 🌧️ llm-structured column '_full_rewrite' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.12 rec/s, eta 164.6s

[14:57:25] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.11 rec/s, eta 160.8s

[14:57:47] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.10 rec/s, eta 145.7s

[14:58:02] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.11 rec/s, eta 121.4s

[14:58:23] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.10 rec/s, eta 104.8s

[14:58:48] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.10 rec/s, eta 88.8s

[14:59:03] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.10 rec/s, eta 67.6s

[14:59:39] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.10 rec/s, eta 52.3s

[14:59:55] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.10 rec/s, eta 30.8s

[15:00:06] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 23/25 (92%) complete, 23 ok, 0 failed, 0.10 rec/s, eta 20.6s

[15:00:06] [INFO] 🗂️ llm-structured model config for column '_quality_qa'

[15:00:06] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:00:06] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:00:06] [INFO]   |-- model provider: 'nvidia'

[15:00:06] [INFO]   |-- inference parameters:

[15:00:06] [INFO]   |  |-- generation_type=chat-completion

[15:00:06] [INFO]   |  |-- max_parallel_requests=2

[15:00:06] [INFO]   |  |-- timeout=300

[15:00:06] [INFO]   |  |-- temperature=0.30

[15:00:06] [INFO]   |  |-- top_p=0.95

[15:00:06] [INFO]   |  |-- max_tokens=16384

[15:00:06] [INFO] ⚡️ Processing llm-structured column '_quality_qa' with 2 concurrent workers

[15:00:06] [INFO] ⏱️ llm-structured column '_quality_qa' will report progress every 2 records

[15:00:16] [INFO]   |-- 🌧️ llm-structured column '_quality_qa' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.20 rec/s, eta 116.7s

[15:00:27] [INFO]   |-- 🌧️ llm-structured column '_quality_qa' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.19 rec/s, eta 110.1s

[15:00:37] [INFO]   |-- 🌧️ llm-structured column '_quality_qa' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.20 rec/s, eta 97.1s

[15:00:43] [INFO]   |-- 🌦️ llm-structured column '_quality_qa' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.22 rec/s, eta 77.8s

[15:00:51] [INFO]   |-- 🌦️ llm-structured column '_quality_qa' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.22 rec/s, eta 67.4s

[15:01:00] [INFO]   |-- 🌦️ llm-structured column '_quality_qa' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.22 rec/s, eta 58.2s

[15:01:08] [INFO]   |-- ⛅ llm-structured column '_quality_qa' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.22 rec/s, eta 49.0s

[15:01:17] [INFO]   |-- ⛅ llm-structured column '_quality_qa' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.23 rec/s, eta 39.9s

[15:01:29] [INFO]   |-- ⛅ llm-structured column '_quality_qa' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.22 rec/s, eta 32.3s

[15:01:39] [INFO]   |-- 🌤️ llm-structured column '_quality_qa' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.21 rec/s, eta 23.3s

[15:01:50] [INFO]   |-- 🌤️ llm-structured column '_quality_qa' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.21 rec/s, eta 14.2s

[15:01:59] [INFO]   |-- 🌤️ llm-structured column '_quality_qa' progress: 23/25 (92%) complete, 23 ok, 0 failed, 0.20 rec/s, eta 9.8s

[15:01:59] [INFO] 🔧 Custom column config for column '_rewritten_text'

[15:01:59] [INFO]   |-- generator_function: '_extract_rewritten_text'

[15:01:59] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:01:59] [INFO]   |-- required_columns: ['_full_rewrite']

[15:01:59] [INFO] ⚡️ Processing custom column '_rewritten_text' with 4 concurrent workers

[15:01:59] [INFO] ⏱️ custom column '_rewritten_text' will report progress every 2 records

[15:01:59] [INFO]   |-- 🚶 custom column '_rewritten_text' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1766.39 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🚶 custom column '_rewritten_text' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2022.12 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🚶 custom column '_rewritten_text' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2378.32 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🐴 custom column '_rewritten_text' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2703.77 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🐴 custom column '_rewritten_text' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2904.51 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🐴 custom column '_rewritten_text' progress: 12/25 (48%) complete, 12 ok, 0 failed, 3177.16 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🚗 custom column '_rewritten_text' progress: 14/25 (56%) complete, 14 ok, 0 failed, 3176.46 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🚗 custom column '_rewritten_text' progress: 16/25 (64%) complete, 16 ok, 0 failed, 3392.32 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- 🚗 custom column '_rewritten_text' progress: 18/25 (72%) complete, 18 ok, 0 failed, 3421.70 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- ✈️ custom column '_rewritten_text' progress: 20/25 (80%) complete, 20 ok, 0 failed, 3563.26 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- ✈️ custom column '_rewritten_text' progress: 22/25 (88%) complete, 22 ok, 0 failed, 3666.00 rec/s, eta 0.0s

[15:01:59] [INFO]   |-- ✈️ custom column '_rewritten_text' progress: 23/25 (92%) complete, 23 ok, 0 failed, 3647.73 rec/s, eta 0.0s

[15:01:59] [INFO] 📊 Model usage summary:

[15:01:59] [INFO]   |-- model: openai/gpt-oss-120b

[15:01:59] [INFO]   |-- tokens: input=364830, output=398841, total=763671, tps=778

[15:01:59] [INFO]   |-- requests: success=120, failed=0, total=120, rpm=7

[15:01:59] [INFO] 📐 Measuring dataset column statistics:

[15:01:59] [INFO]   |-- 🗂️ column: '_domain'

[15:01:59] [INFO]   |-- 🔧 column: '_domain_supplement'

[15:01:59] [INFO]   |-- 🗂️ column: '_sensitivity_disposition'

[15:01:59] [INFO]   |-- 🔧 column: '_sensitivity_disposition_block'

[15:01:59] [INFO]   |-- 🗂️ column: '_meaning_units'

[15:01:59] [INFO]   |-- 🔧 column: '_meaning_units_serialized'

[15:01:59] [INFO]   |-- 🗂️ column: '_quality_qa'

[15:01:59] [INFO]   |-- 🔧 column: '_privacy_qa'

[15:01:59] [INFO]   |-- 🔧 column: '_rewrite_disposition_block'

[15:01:59] [INFO]   |-- 🔧 column: '_replacement_map_for_prompt'

[15:01:59] [INFO]   |-- 🗂️ column: '_full_rewrite'

[15:01:59] [INFO]   |-- 🔧 column: '_rewritten_text'

[15:01:59] [WARNING] Row count mismatch: target=25, source=23; dropping 2 failed row(s).

[15:01:59] [INFO] 🎨 Creating Data Designer dataset

[15:01:59] [INFO] ✅ Validation passed

[15:01:59] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:01:59] [INFO] 🩺 Running health checks for models...

[15:01:59] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:02:03] [INFO]   |-- ✅ Passed!

[15:02:03] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-0_04-03-2026_150203' instead.

[15:02:03] [INFO] ⏳ Processing batch 1 of 1

[15:02:03] [INFO] 🌱 Sampling 23 records from seed dataset

[15:02:03] [INFO]   |-- seed dataset size: 23 records

[15:02:03] [INFO]   |-- sampling strategy: ordered

[15:02:03] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:02:03] [INFO]   |-- generator_function: '_quality_reanswer'

[15:02:03] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:02:03] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:02:03] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:02:03] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:02:03] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress every 2 records

[15:02:16] [INFO]   |-- 🐱 custom column '_quality_qa_reanswer' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.16 rec/s, eta 135.2s

[15:02:23] [INFO]   |-- 🐱 custom column '_quality_qa_reanswer' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.20 rec/s, eta 94.2s

[15:02:31] [INFO]   |-- 😺 custom column '_quality_qa_reanswer' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.22 rec/s, eta 78.6s

[15:02:40] [INFO]   |-- 😺 custom column '_quality_qa_reanswer' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.22 rec/s, eta 69.6s

[15:02:55] [INFO]   |-- 😺 custom column '_quality_qa_reanswer' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.19 rec/s, eta 68.2s

[15:03:00] [INFO]   |-- 😸 custom column '_quality_qa_reanswer' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.21 rec/s, eta 52.4s

[15:03:08] [INFO]   |-- 😸 custom column '_quality_qa_reanswer' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.21 rec/s, eta 42.1s

[15:03:14] [INFO]   |-- 😸 custom column '_quality_qa_reanswer' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.22 rec/s, eta 31.2s

[15:03:25] [INFO]   |-- 😼 custom column '_quality_qa_reanswer' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.22 rec/s, eta 22.8s

[15:03:34] [INFO]   |-- 😼 custom column '_quality_qa_reanswer' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.22 rec/s, eta 13.6s

[15:03:38] [INFO]   |-- 😼 custom column '_quality_qa_reanswer' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.23 rec/s, eta 4.3s

[15:03:40] [INFO]   |-- 🦁 custom column '_quality_qa_reanswer' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.24 rec/s, eta 0.0s

[15:03:40] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:03:40] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:03:40] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:03:40] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:03:40] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:03:40] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:03:40] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress every 2 records

[15:04:12] [INFO]   |-- 🥚 custom column '_privacy_qa_reanswer' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.06 rec/s, eta 341.6s

[15:04:39] [INFO]   |-- 🥚 custom column '_privacy_qa_reanswer' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.07 rec/s, eta 279.8s

[15:04:53] [WARNING] Evaluator returned malformed privacy answer set; missing=[36] duplicate=[] extra=[]. Applying conservative normalization.

[15:04:53] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.08 rec/s, eta 208.2s

[15:05:05] [WARNING] Evaluator returned malformed privacy answer set; missing=[21] duplicate=[] extra=[]. Applying conservative normalization.

[15:05:05] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.09 rec/s, eta 160.2s

[15:05:29] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.09 rec/s, eta 142.4s

[15:05:33] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.11 rec/s, eta 104.0s

[15:05:49] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.11 rec/s, eta 83.0s

[15:06:07] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.11 rec/s, eta 64.3s

[15:06:20] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.11 rec/s, eta 44.6s

[15:06:44] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.11 rec/s, eta 27.7s

[15:07:00] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.11 rec/s, eta 9.1s

[15:07:01] [INFO]   |-- 🐔 custom column '_privacy_qa_reanswer' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.11 rec/s, eta 0.0s

[15:07:01] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:07:01] [INFO]   |-- generator_function: '_quality_compare'

[15:07:01] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:07:01] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:07:01] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:07:01] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:07:01] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress every 2 records

[15:07:15] [INFO]   |-- 🌑 custom column '_quality_qa_compare' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 139.1s

[15:07:17] [INFO]   |-- 🌑 custom column '_quality_qa_compare' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.25 rec/s, eta 75.2s

[15:07:33] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.19 rec/s, eta 89.9s

[15:07:37] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.22 rec/s, eta 67.0s

[15:07:49] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.21 rec/s, eta 62.3s

[15:08:01] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.20 rec/s, eta 54.8s

[15:08:06] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.22 rec/s, eta 41.5s

[15:08:17] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.21 rec/s, eta 33.0s

[15:08:24] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.22 rec/s, eta 23.0s

[15:08:34] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.22 rec/s, eta 13.9s

[15:08:38] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.23 rec/s, eta 4.4s

[15:08:38] [INFO]   |-- 🌕 custom column '_quality_qa_compare' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.24 rec/s, eta 0.0s

[15:08:38] [INFO] 🔧 Custom column config for column 'utility_score'

[15:08:38] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:08:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:08:38] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:08:38] [INFO]   |-- side_effect_columns: ['leakage_mass', 'weighted_leakage_rate', 'any_high_leaked']

[15:08:38] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:08:38] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:08:38] [INFO] ⏱️ custom column 'utility_score' will report progress every 2 records

[15:08:38] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 2/23 (9%) complete, 2 ok, 0 failed, 1096.27 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 4/23 (17%) complete, 4 ok, 0 failed, 1255.82 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 6/23 (26%) complete, 6 ok, 0 failed, 1459.63 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1575.97 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 10/23 (43%) complete, 10 ok, 0 failed, 1700.38 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- ⛅ custom column 'utility_score' progress: 12/23 (52%) complete, 12 ok, 0 failed, 1802.43 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- ⛅ custom column 'utility_score' progress: 14/23 (61%) complete, 14 ok, 0 failed, 1800.34 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- ⛅ custom column 'utility_score' progress: 16/23 (70%) complete, 16 ok, 0 failed, 1900.68 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 18/23 (78%) complete, 18 ok, 0 failed, 1935.65 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 20/23 (87%) complete, 20 ok, 0 failed, 1928.82 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2014.53 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- ☀️ custom column 'utility_score' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2044.90 rec/s, eta 0.0s

[15:08:38] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:08:38] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:08:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:08:38] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:08:38] [INFO]   |-- generator_params: repair_any_high_leak=True effective_threshold=0.6

[15:08:38] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:08:38] [INFO] ⏱️ custom column '_needs_repair' will report progress every 2 records

[15:08:38] [INFO]   |-- 🥚 custom column '_needs_repair' progress: 2/23 (9%) complete, 2 ok, 0 failed, 3224.72 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🥚 custom column '_needs_repair' progress: 4/23 (17%) complete, 4 ok, 0 failed, 3329.29 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐣 custom column '_needs_repair' progress: 6/23 (26%) complete, 6 ok, 0 failed, 3650.28 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐣 custom column '_needs_repair' progress: 8/23 (35%) complete, 8 ok, 0 failed, 4154.04 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐣 custom column '_needs_repair' progress: 10/23 (43%) complete, 10 ok, 0 failed, 4169.42 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐥 custom column '_needs_repair' progress: 12/23 (52%) complete, 12 ok, 0 failed, 4343.24 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐥 custom column '_needs_repair' progress: 14/23 (61%) complete, 14 ok, 0 failed, 4245.32 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐥 custom column '_needs_repair' progress: 16/23 (70%) complete, 16 ok, 0 failed, 4452.12 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐤 custom column '_needs_repair' progress: 18/23 (78%) complete, 18 ok, 0 failed, 4629.53 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐤 custom column '_needs_repair' progress: 20/23 (87%) complete, 20 ok, 0 failed, 4644.77 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐤 custom column '_needs_repair' progress: 22/23 (96%) complete, 22 ok, 0 failed, 4735.17 rec/s, eta 0.0s

[15:08:38] [INFO]   |-- 🐔 custom column '_needs_repair' progress: 23/23 (100%) complete, 23 ok, 0 failed, 4681.18 rec/s, eta 0.0s

[15:08:38] [INFO] 📊 Model usage summary:

[15:08:38] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:08:38] [INFO]   |-- tokens: input=153394, output=210317, total=363711, tps=920

[15:08:38] [INFO]   |-- requests: success=69, failed=0, total=69, rpm=10

[15:08:38] [INFO] 📐 Measuring dataset column statistics:

[15:08:38] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:08:38] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:08:38] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:08:38] [INFO]   |-- 🔧 column: 'utility_score'

[15:08:38] [INFO]   |-- 🔧 column: '_needs_repair'

[15:08:38] [INFO] Evaluate-repair loop iteration 0: 19/23 rows need repair

[15:08:38] [INFO] 🎨 Creating Data Designer dataset

[15:08:38] [INFO] ✅ Validation passed

[15:08:38] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:08:38] [INFO] 🩺 Running health checks for models...

[15:08:38] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:08:39] [INFO]   |-- ✅ Passed!

[15:08:39] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-0_04-03-2026_150839' instead.

[15:08:39] [INFO] ⏳ Processing batch 1 of 1

[15:08:39] [INFO] 🌱 Sampling 19 records from seed dataset

[15:08:39] [INFO]   |-- seed dataset size: 19 records

[15:08:39] [INFO]   |-- sampling strategy: ordered

[15:08:39] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:08:39] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:08:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:08:39] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:08:39] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:08:39] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:08:39] [INFO]   |-- 🐱 custom column '_leaked_privacy_items' progress: 1/19 (5%) complete, 1 ok, 0 failed, 1140.03 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 🐱 custom column '_leaked_privacy_items' progress: 2/19 (11%) complete, 2 ok, 0 failed, 1481.66 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 🐱 custom column '_leaked_privacy_items' progress: 3/19 (16%) complete, 3 ok, 0 failed, 1599.57 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 🐱 custom column '_leaked_privacy_items' progress: 4/19 (21%) complete, 4 ok, 0 failed, 1727.86 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 5/19 (26%) complete, 5 ok, 0 failed, 1706.63 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 6/19 (32%) complete, 6 ok, 0 failed, 1834.49 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 7/19 (37%) complete, 7 ok, 0 failed, 1839.81 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 8/19 (42%) complete, 8 ok, 0 failed, 1751.65 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 9/19 (47%) complete, 9 ok, 0 failed, 1791.10 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 10/19 (53%) complete, 10 ok, 0 failed, 1853.78 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 11/19 (58%) complete, 11 ok, 0 failed, 1903.98 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 12/19 (63%) complete, 12 ok, 0 failed, 1959.34 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 13/19 (68%) complete, 13 ok, 0 failed, 2000.06 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 14/19 (74%) complete, 14 ok, 0 failed, 2018.26 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😼 custom column '_leaked_privacy_items' progress: 15/19 (79%) complete, 15 ok, 0 failed, 2042.16 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😼 custom column '_leaked_privacy_items' progress: 16/19 (84%) complete, 16 ok, 0 failed, 2075.07 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😼 custom column '_leaked_privacy_items' progress: 17/19 (89%) complete, 17 ok, 0 failed, 2091.13 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 😼 custom column '_leaked_privacy_items' progress: 18/19 (95%) complete, 18 ok, 0 failed, 2167.41 rec/s, eta 0.0s

[15:08:39] [INFO]   |-- 🦁 custom column '_leaked_privacy_items' progress: 19/19 (100%) complete, 19 ok, 0 failed, 2228.30 rec/s, eta 0.0s

[15:08:39] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:08:39] [INFO]   |-- generator_function: '_repair_column'

[15:08:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:08:39] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:08:39] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:08:39] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:08:39] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:08:39] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:08:49] [INFO]   |-- 🥚 custom column '_rewritten_text__next' progress: 1/19 (5%) complete, 1 ok, 0 failed, 0.10 rec/s, eta 185.9s

[15:08:53] [INFO]   |-- 🥚 custom column '_rewritten_text__next' progress: 2/19 (11%) complete, 2 ok, 0 failed, 0.14 rec/s, eta 123.7s

[15:08:54] [INFO]   |-- 🥚 custom column '_rewritten_text__next' progress: 3/19 (16%) complete, 3 ok, 0 failed, 0.20 rec/s, eta 80.2s

[15:08:55] [INFO]   |-- 🥚 custom column '_rewritten_text__next' progress: 4/19 (21%) complete, 4 ok, 0 failed, 0.25 rec/s, eta 61.2s

[15:09:00] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 5/19 (26%) complete, 5 ok, 0 failed, 0.23 rec/s, eta 59.6s

[15:09:02] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 6/19 (32%) complete, 6 ok, 0 failed, 0.25 rec/s, eta 51.0s

[15:09:03] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 7/19 (37%) complete, 7 ok, 0 failed, 0.29 rec/s, eta 41.7s

[15:09:12] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 8/19 (42%) complete, 8 ok, 0 failed, 0.24 rec/s, eta 45.4s

[15:09:14] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 9/19 (47%) complete, 9 ok, 0 failed, 0.26 rec/s, eta 38.8s

[15:09:16] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 10/19 (53%) complete, 10 ok, 0 failed, 0.27 rec/s, eta 33.2s

[15:09:17] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 11/19 (58%) complete, 11 ok, 0 failed, 0.29 rec/s, eta 27.7s

[15:09:26] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 12/19 (63%) complete, 12 ok, 0 failed, 0.26 rec/s, eta 27.3s

[15:09:26] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 13/19 (68%) complete, 13 ok, 0 failed, 0.28 rec/s, eta 21.7s

[15:09:30] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 14/19 (74%) complete, 14 ok, 0 failed, 0.27 rec/s, eta 18.3s

[15:09:32] [INFO]   |-- 🐤 custom column '_rewritten_text__next' progress: 15/19 (79%) complete, 15 ok, 0 failed, 0.28 rec/s, eta 14.0s

[15:09:39] [INFO]   |-- 🐤 custom column '_rewritten_text__next' progress: 16/19 (84%) complete, 16 ok, 0 failed, 0.27 rec/s, eta 11.2s

[15:09:40] [INFO]   |-- 🐤 custom column '_rewritten_text__next' progress: 17/19 (89%) complete, 17 ok, 0 failed, 0.28 rec/s, eta 7.2s

[15:09:42] [INFO]   |-- 🐤 custom column '_rewritten_text__next' progress: 18/19 (95%) complete, 18 ok, 0 failed, 0.29 rec/s, eta 3.5s

[15:09:43] [INFO]   |-- 🐔 custom column '_rewritten_text__next' progress: 19/19 (100%) complete, 19 ok, 0 failed, 0.30 rec/s, eta 0.0s

[15:09:43] [INFO] 📊 Model usage summary:

[15:09:43] [INFO]   |-- model: openai/gpt-oss-120b

[15:09:43] [INFO]   |-- tokens: input=68465, output=47719, total=116184, tps=1800

[15:09:43] [INFO]   |-- requests: success=19, failed=0, total=19, rpm=17

[15:09:43] [INFO] 📐 Measuring dataset column statistics:

[15:09:43] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:09:43] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:09:43] [INFO] 🎨 Creating Data Designer dataset

[15:09:43] [INFO] ✅ Validation passed

[15:09:43] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:09:43] [INFO] 🩺 Running health checks for models...

[15:09:43] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:09:44] [INFO]   |-- ✅ Passed!

[15:09:44] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-1' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-1_04-03-2026_150944' instead.

[15:09:44] [INFO] ⏳ Processing batch 1 of 1

[15:09:44] [INFO] 🌱 Sampling 19 records from seed dataset

[15:09:44] [INFO]   |-- seed dataset size: 19 records

[15:09:44] [INFO]   |-- sampling strategy: ordered

[15:09:44] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:09:44] [INFO]   |-- generator_function: '_quality_reanswer'

[15:09:44] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:09:44] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:09:44] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:09:44] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:09:44] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:09:57] [INFO]   |-- 🌧️ custom column '_quality_qa_reanswer' progress: 1/19 (5%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 234.1s

[15:10:01] [INFO]   |-- 🌧️ custom column '_quality_qa_reanswer' progress: 2/19 (11%) complete, 2 ok, 0 failed, 0.12 rec/s, eta 145.9s

[15:10:02] [INFO]   |-- 🌧️ custom column '_quality_qa_reanswer' progress: 3/19 (16%) complete, 3 ok, 0 failed, 0.17 rec/s, eta 93.8s

[15:10:06] [INFO]   |-- 🌧️ custom column '_quality_qa_reanswer' progress: 4/19 (21%) complete, 4 ok, 0 failed, 0.18 rec/s, eta 84.3s

[15:10:13] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 5/19 (26%) complete, 5 ok, 0 failed, 0.17 rec/s, eta 81.2s

[15:10:16] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 6/19 (32%) complete, 6 ok, 0 failed, 0.19 rec/s, eta 68.5s

[15:10:21] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 7/19 (37%) complete, 7 ok, 0 failed, 0.19 rec/s, eta 62.6s

[15:10:27] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 8/19 (42%) complete, 8 ok, 0 failed, 0.19 rec/s, eta 58.9s

[15:10:29] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 9/19 (47%) complete, 9 ok, 0 failed, 0.20 rec/s, eta 49.8s

[15:10:34] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 10/19 (53%) complete, 10 ok, 0 failed, 0.20 rec/s, eta 45.3s

[15:10:36] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 11/19 (58%) complete, 11 ok, 0 failed, 0.21 rec/s, eta 37.8s

[15:10:38] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 12/19 (63%) complete, 12 ok, 0 failed, 0.22 rec/s, eta 31.7s

[15:10:43] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 13/19 (68%) complete, 13 ok, 0 failed, 0.22 rec/s, eta 27.1s

[15:10:52] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 14/19 (74%) complete, 14 ok, 0 failed, 0.20 rec/s, eta 24.4s

[15:10:56] [INFO]   |-- 🌤️ custom column '_quality_qa_reanswer' progress: 15/19 (79%) complete, 15 ok, 0 failed, 0.21 rec/s, eta 19.2s

[15:10:59] [INFO]   |-- 🌤️ custom column '_quality_qa_reanswer' progress: 16/19 (84%) complete, 16 ok, 0 failed, 0.21 rec/s, eta 14.1s

[15:11:01] [INFO]   |-- 🌤️ custom column '_quality_qa_reanswer' progress: 17/19 (89%) complete, 17 ok, 0 failed, 0.22 rec/s, eta 9.1s

[15:11:07] [INFO]   |-- 🌤️ custom column '_quality_qa_reanswer' progress: 18/19 (95%) complete, 18 ok, 0 failed, 0.22 rec/s, eta 4.6s

[15:11:09] [INFO]   |-- ☀️ custom column '_quality_qa_reanswer' progress: 19/19 (100%) complete, 19 ok, 0 failed, 0.22 rec/s, eta 0.0s

[15:11:09] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:11:09] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:11:09] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:11:09] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:11:09] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:11:09] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:11:09] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:11:20] [INFO]   |-- 🚶 custom column '_privacy_qa_reanswer' progress: 1/19 (5%) complete, 1 ok, 0 failed, 0.09 rec/s, eta 201.0s

[15:11:39] [INFO]   |-- 🚶 custom column '_privacy_qa_reanswer' progress: 2/19 (11%) complete, 2 ok, 0 failed, 0.07 rec/s, eta 259.7s

[15:11:41] [INFO]   |-- 🚶 custom column '_privacy_qa_reanswer' progress: 3/19 (16%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 171.4s

[15:11:56] [INFO]   |-- 🚶 custom column '_privacy_qa_reanswer' progress: 4/19 (21%) complete, 4 ok, 0 failed, 0.08 rec/s, eta 176.9s

[15:12:03] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 5/19 (26%) complete, 5 ok, 0 failed, 0.09 rec/s, eta 151.0s

[15:12:15] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 6/19 (32%) complete, 6 ok, 0 failed, 0.09 rec/s, eta 143.6s

[15:12:21] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 7/19 (37%) complete, 7 ok, 0 failed, 0.10 rec/s, eta 124.4s

[15:12:22] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 8/19 (42%) complete, 8 ok, 0 failed, 0.11 rec/s, eta 101.3s

[15:12:42] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 9/19 (47%) complete, 9 ok, 0 failed, 0.10 rec/s, eta 103.6s

[15:12:50] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 10/19 (53%) complete, 10 ok, 0 failed, 0.10 rec/s, eta 90.9s

[15:12:52] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 11/19 (58%) complete, 11 ok, 0 failed, 0.11 rec/s, eta 75.4s

[15:12:57] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 12/19 (63%) complete, 12 ok, 0 failed, 0.11 rec/s, eta 63.4s

[15:13:18] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 13/19 (68%) complete, 13 ok, 0 failed, 0.10 rec/s, eta 59.4s

[15:13:20] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 14/19 (74%) complete, 14 ok, 0 failed, 0.11 rec/s, eta 46.8s

[15:13:31] [INFO]   |-- ✈️ custom column '_privacy_qa_reanswer' progress: 15/19 (79%) complete, 15 ok, 0 failed, 0.11 rec/s, eta 37.9s

[15:13:31] [INFO]   |-- ✈️ custom column '_privacy_qa_reanswer' progress: 16/19 (84%) complete, 16 ok, 0 failed, 0.11 rec/s, eta 26.7s

[15:13:39] [INFO]   |-- ✈️ custom column '_privacy_qa_reanswer' progress: 17/19 (89%) complete, 17 ok, 0 failed, 0.11 rec/s, eta 17.6s

[15:13:48] [INFO]   |-- ✈️ custom column '_privacy_qa_reanswer' progress: 18/19 (95%) complete, 18 ok, 0 failed, 0.11 rec/s, eta 8.8s

[15:14:03] [INFO]   |-- 🚀 custom column '_privacy_qa_reanswer' progress: 19/19 (100%) complete, 19 ok, 0 failed, 0.11 rec/s, eta 0.0s

[15:14:03] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:14:03] [INFO]   |-- generator_function: '_quality_compare'

[15:14:03] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:14:03] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:14:03] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:14:03] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:14:03] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:14:16] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 1/19 (5%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 217.9s

[15:14:17] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 2/19 (11%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 114.2s

[15:14:17] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 3/19 (16%) complete, 3 ok, 0 failed, 0.22 rec/s, eta 73.9s

[15:14:20] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 4/19 (21%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 63.8s

[15:14:29] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 5/19 (26%) complete, 5 ok, 0 failed, 0.19 rec/s, eta 72.4s

[15:14:34] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 6/19 (32%) complete, 6 ok, 0 failed, 0.20 rec/s, eta 65.7s

[15:14:35] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 7/19 (37%) complete, 7 ok, 0 failed, 0.23 rec/s, eta 53.3s

[15:14:35] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 8/19 (42%) complete, 8 ok, 0 failed, 0.26 rec/s, eta 43.0s

[15:14:43] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 9/19 (47%) complete, 9 ok, 0 failed, 0.23 rec/s, eta 44.3s

[15:14:51] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 10/19 (53%) complete, 10 ok, 0 failed, 0.21 rec/s, eta 42.9s

[15:14:53] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 11/19 (58%) complete, 11 ok, 0 failed, 0.22 rec/s, eta 36.4s

[15:14:56] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 12/19 (63%) complete, 12 ok, 0 failed, 0.23 rec/s, eta 30.9s

[15:15:07] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 13/19 (68%) complete, 13 ok, 0 failed, 0.20 rec/s, eta 29.4s

[15:15:11] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 14/19 (74%) complete, 14 ok, 0 failed, 0.21 rec/s, eta 24.1s

[15:15:11] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 15/19 (79%) complete, 15 ok, 0 failed, 0.22 rec/s, eta 18.0s

[15:15:25] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 16/19 (84%) complete, 16 ok, 0 failed, 0.20 rec/s, eta 15.4s

[15:15:27] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 17/19 (89%) complete, 17 ok, 0 failed, 0.20 rec/s, eta 9.8s

[15:15:30] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 18/19 (95%) complete, 18 ok, 0 failed, 0.21 rec/s, eta 4.8s

[15:15:35] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 19/19 (100%) complete, 19 ok, 0 failed, 0.21 rec/s, eta 0.0s

[15:15:35] [INFO] 🔧 Custom column config for column 'utility_score'

[15:15:35] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:15:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:15:35] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:15:35] [INFO]   |-- side_effect_columns: ['leakage_mass', 'weighted_leakage_rate', 'any_high_leaked']

[15:15:35] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:15:35] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:15:35] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:15:35] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 1/19 (5%) complete, 1 ok, 0 failed, 678.18 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 2/19 (11%) complete, 2 ok, 0 failed, 874.32 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 3/19 (16%) complete, 3 ok, 0 failed, 848.96 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 4/19 (21%) complete, 4 ok, 0 failed, 1032.51 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 5/19 (26%) complete, 5 ok, 0 failed, 1097.74 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 6/19 (32%) complete, 6 ok, 0 failed, 1001.50 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 7/19 (37%) complete, 7 ok, 0 failed, 1103.19 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 8/19 (42%) complete, 8 ok, 0 failed, 1164.23 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 9/19 (47%) complete, 9 ok, 0 failed, 1163.44 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column 'utility_score' progress: 10/19 (53%) complete, 10 ok, 0 failed, 1250.17 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column 'utility_score' progress: 11/19 (58%) complete, 11 ok, 0 failed, 1232.79 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column 'utility_score' progress: 12/19 (63%) complete, 12 ok, 0 failed, 1301.94 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column 'utility_score' progress: 13/19 (68%) complete, 13 ok, 0 failed, 1297.60 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column 'utility_score' progress: 14/19 (74%) complete, 14 ok, 0 failed, 1364.64 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 15/19 (79%) complete, 15 ok, 0 failed, 1399.44 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 16/19 (84%) complete, 16 ok, 0 failed, 1436.32 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 17/19 (89%) complete, 17 ok, 0 failed, 1461.12 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 18/19 (95%) complete, 18 ok, 0 failed, 1502.77 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ☀️ custom column 'utility_score' progress: 19/19 (100%) complete, 19 ok, 0 failed, 1541.68 rec/s, eta 0.0s

[15:15:35] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:15:35] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:15:35] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:15:35] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:15:35] [INFO]   |-- generator_params: repair_any_high_leak=True effective_threshold=0.6

[15:15:35] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:15:35] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:15:35] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 1/19 (5%) complete, 1 ok, 0 failed, 2067.00 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 2/19 (11%) complete, 2 ok, 0 failed, 2350.18 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 3/19 (16%) complete, 3 ok, 0 failed, 2602.85 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 4/19 (21%) complete, 4 ok, 0 failed, 2752.61 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 5/19 (26%) complete, 5 ok, 0 failed, 2604.22 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 6/19 (32%) complete, 6 ok, 0 failed, 2706.77 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 7/19 (37%) complete, 7 ok, 0 failed, 2819.26 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 8/19 (42%) complete, 8 ok, 0 failed, 2868.50 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 9/19 (47%) complete, 9 ok, 0 failed, 2919.98 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 10/19 (53%) complete, 10 ok, 0 failed, 2979.15 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 11/19 (58%) complete, 11 ok, 0 failed, 3028.81 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 12/19 (63%) complete, 12 ok, 0 failed, 3038.97 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 13/19 (68%) complete, 13 ok, 0 failed, 3142.50 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 14/19 (74%) complete, 14 ok, 0 failed, 3140.66 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 15/19 (79%) complete, 15 ok, 0 failed, 3191.91 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 16/19 (84%) complete, 16 ok, 0 failed, 3166.46 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 17/19 (89%) complete, 17 ok, 0 failed, 3224.58 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 18/19 (95%) complete, 18 ok, 0 failed, 3290.40 rec/s, eta 0.0s

[15:15:35] [INFO]   |-- ☀️ custom column '_needs_repair' progress: 19/19 (100%) complete, 19 ok, 0 failed, 3346.27 rec/s, eta 0.0s

[15:15:36] [INFO] 📊 Model usage summary:

[15:15:36] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:15:36] [INFO]   |-- tokens: input=133767, output=178267, total=312034, tps=887

[15:15:36] [INFO]   |-- requests: success=58, failed=0, total=58, rpm=9

[15:15:36] [INFO] 📐 Measuring dataset column statistics:

[15:15:36] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:15:36] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:15:36] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:15:36] [INFO]   |-- 🔧 column: 'utility_score'

[15:15:36] [INFO]   |-- 🔧 column: '_needs_repair'

[15:15:36] [INFO] Evaluate-repair loop iteration 1: 8/23 rows need repair

[15:15:36] [INFO] 🎨 Creating Data Designer dataset

[15:15:36] [INFO] ✅ Validation passed

[15:15:36] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:15:36] [INFO] 🩺 Running health checks for models...

[15:15:36] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:15:36] [INFO]   |-- ✅ Passed!

[15:15:36] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-1' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-1_04-03-2026_151536' instead.

[15:15:36] [INFO] ⏳ Processing batch 1 of 1

[15:15:36] [INFO] 🌱 Sampling 8 records from seed dataset

[15:15:36] [INFO]   |-- seed dataset size: 8 records

[15:15:36] [INFO]   |-- sampling strategy: ordered

[15:15:36] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:15:36] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:15:36] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:15:36] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:15:36] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:15:36] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:15:36] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 1/8 (12%) complete, 1 ok, 0 failed, 1318.46 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 2/8 (25%) complete, 2 ok, 0 failed, 1614.69 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 3/8 (38%) complete, 3 ok, 0 failed, 1714.45 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 4/8 (50%) complete, 4 ok, 0 failed, 1843.42 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 5/8 (62%) complete, 5 ok, 0 failed, 1755.95 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 6/8 (75%) complete, 6 ok, 0 failed, 1936.45 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 7/8 (88%) complete, 7 ok, 0 failed, 1958.70 rec/s, eta 0.0s

[15:15:36] [INFO]   |-- 🚀 custom column '_leaked_privacy_items' progress: 8/8 (100%) complete, 8 ok, 0 failed, 1985.97 rec/s, eta 0.0s

[15:15:36] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:15:36] [INFO]   |-- generator_function: '_repair_column'

[15:15:36] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:15:36] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:15:36] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:15:36] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:15:36] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:15:36] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:15:48] [INFO]   |-- 🐱 custom column '_rewritten_text__next' progress: 1/8 (12%) complete, 1 ok, 0 failed, 0.09 rec/s, eta 79.2s

[15:15:49] [INFO]   |-- 😺 custom column '_rewritten_text__next' progress: 2/8 (25%) complete, 2 ok, 0 failed, 0.16 rec/s, eta 37.4s

[15:15:51] [INFO]   |-- 😺 custom column '_rewritten_text__next' progress: 3/8 (38%) complete, 3 ok, 0 failed, 0.20 rec/s, eta 24.5s

[15:15:53] [INFO]   |-- 😸 custom column '_rewritten_text__next' progress: 4/8 (50%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 16.4s

[15:15:58] [INFO]   |-- 😸 custom column '_rewritten_text__next' progress: 5/8 (62%) complete, 5 ok, 0 failed, 0.23 rec/s, eta 13.3s

[15:16:00] [INFO]   |-- 😼 custom column '_rewritten_text__next' progress: 6/8 (75%) complete, 6 ok, 0 failed, 0.25 rec/s, eta 7.9s

[15:16:01] [INFO]   |-- 😼 custom column '_rewritten_text__next' progress: 7/8 (88%) complete, 7 ok, 0 failed, 0.28 rec/s, eta 3.5s

[15:16:04] [INFO]   |-- 🦁 custom column '_rewritten_text__next' progress: 8/8 (100%) complete, 8 ok, 0 failed, 0.28 rec/s, eta 0.0s

[15:16:05] [INFO] 📊 Model usage summary:

[15:16:05] [INFO]   |-- model: openai/gpt-oss-120b

[15:16:05] [INFO]   |-- tokens: input=30385, output=20359, total=50744, tps=1782

[15:16:05] [INFO]   |-- requests: success=8, failed=0, total=8, rpm=16

[15:16:05] [INFO] 📐 Measuring dataset column statistics:

[15:16:05] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:16:05] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:16:05] [INFO] 🎨 Creating Data Designer dataset

[15:16:05] [INFO] ✅ Validation passed

[15:16:05] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:16:05] [INFO] 🩺 Running health checks for models...

[15:16:05] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:16:06] [INFO]   |-- ✅ Passed!

[15:16:06] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-2' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-2_04-03-2026_151606' instead.

[15:16:06] [INFO] ⏳ Processing batch 1 of 1

[15:16:06] [INFO] 🌱 Sampling 8 records from seed dataset

[15:16:06] [INFO]   |-- seed dataset size: 8 records

[15:16:06] [INFO]   |-- sampling strategy: ordered

[15:16:06] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:16:06] [INFO]   |-- generator_function: '_quality_reanswer'

[15:16:06] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:16:06] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:16:06] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:16:06] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:16:06] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:16:18] [INFO]   |-- 🚶 custom column '_quality_qa_reanswer' progress: 1/8 (12%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 86.7s

[15:16:19] [INFO]   |-- 🐴 custom column '_quality_qa_reanswer' progress: 2/8 (25%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 40.9s

[15:16:22] [INFO]   |-- 🐴 custom column '_quality_qa_reanswer' progress: 3/8 (38%) complete, 3 ok, 0 failed, 0.19 rec/s, eta 26.7s

[15:16:22] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 4/8 (50%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 16.5s

[15:16:35] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 5/8 (62%) complete, 5 ok, 0 failed, 0.17 rec/s, eta 17.3s

[15:16:35] [INFO]   |-- ✈️ custom column '_quality_qa_reanswer' progress: 6/8 (75%) complete, 6 ok, 0 failed, 0.20 rec/s, eta 9.8s

[15:16:38] [INFO]   |-- ✈️ custom column '_quality_qa_reanswer' progress: 7/8 (88%) complete, 7 ok, 0 failed, 0.22 rec/s, eta 4.6s

[15:16:39] [INFO]   |-- 🚀 custom column '_quality_qa_reanswer' progress: 8/8 (100%) complete, 8 ok, 0 failed, 0.24 rec/s, eta 0.0s

[15:16:39] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:16:39] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:16:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:16:39] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:16:39] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:16:39] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:16:39] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:17:10] [INFO]   |-- 🌧️ custom column '_privacy_qa_reanswer' progress: 1/8 (12%) complete, 1 ok, 0 failed, 0.03 rec/s, eta 213.5s

[15:17:10] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 2/8 (25%) complete, 2 ok, 0 failed, 0.07 rec/s, eta 91.8s

[15:17:11] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 3/8 (38%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 53.7s

[15:17:18] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 4/8 (50%) complete, 4 ok, 0 failed, 0.10 rec/s, eta 38.8s

[15:17:43] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 5/8 (62%) complete, 5 ok, 0 failed, 0.08 rec/s, eta 38.2s

[15:17:51] [INFO]   |-- 🌤️ custom column '_privacy_qa_reanswer' progress: 6/8 (75%) complete, 6 ok, 0 failed, 0.08 rec/s, eta 24.0s

[15:17:53] [INFO]   |-- 🌤️ custom column '_privacy_qa_reanswer' progress: 7/8 (88%) complete, 7 ok, 0 failed, 0.09 rec/s, eta 10.6s

[15:18:59] [INFO]   |-- ☀️ custom column '_privacy_qa_reanswer' progress: 8/8 (100%) complete, 8 ok, 0 failed, 0.06 rec/s, eta 0.0s

[15:18:59] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:18:59] [INFO]   |-- generator_function: '_quality_compare'

[15:18:59] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:18:59] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:18:59] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:18:59] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:18:59] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:19:11] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 1/8 (12%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 87.3s

[15:19:13] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 2/8 (25%) complete, 2 ok, 0 failed, 0.14 rec/s, eta 41.9s

[15:19:20] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 3/8 (38%) complete, 3 ok, 0 failed, 0.14 rec/s, eta 36.4s

[15:19:27] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 4/8 (50%) complete, 4 ok, 0 failed, 0.14 rec/s, eta 28.0s

[15:19:28] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 5/8 (62%) complete, 5 ok, 0 failed, 0.17 rec/s, eta 17.3s

[15:19:31] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 6/8 (75%) complete, 6 ok, 0 failed, 0.19 rec/s, eta 10.7s

[15:19:39] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 7/8 (88%) complete, 7 ok, 0 failed, 0.17 rec/s, eta 5.8s

[15:19:52] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 8/8 (100%) complete, 8 ok, 0 failed, 0.15 rec/s, eta 0.0s

[15:19:52] [INFO] 🔧 Custom column config for column 'utility_score'

[15:19:52] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:19:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:19:52] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:19:52] [INFO]   |-- side_effect_columns: ['leakage_mass', 'weighted_leakage_rate', 'any_high_leaked']

[15:19:52] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:19:52] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:19:52] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:19:52] [INFO]   |-- 😴 custom column 'utility_score' progress: 1/8 (12%) complete, 1 ok, 0 failed, 801.39 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🥱 custom column 'utility_score' progress: 2/8 (25%) complete, 2 ok, 0 failed, 915.35 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🥱 custom column 'utility_score' progress: 3/8 (38%) complete, 3 ok, 0 failed, 977.09 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😐 custom column 'utility_score' progress: 4/8 (50%) complete, 4 ok, 0 failed, 1062.57 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😐 custom column 'utility_score' progress: 5/8 (62%) complete, 5 ok, 0 failed, 1030.25 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😊 custom column 'utility_score' progress: 6/8 (75%) complete, 6 ok, 0 failed, 1133.19 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😊 custom column 'utility_score' progress: 7/8 (88%) complete, 7 ok, 0 failed, 1176.64 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🤩 custom column 'utility_score' progress: 8/8 (100%) complete, 8 ok, 0 failed, 1224.13 rec/s, eta 0.0s

[15:19:52] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:19:52] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:19:52] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:19:52] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:19:52] [INFO]   |-- generator_params: repair_any_high_leak=True effective_threshold=0.6

[15:19:52] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:19:52] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:19:52] [INFO]   |-- 😴 custom column '_needs_repair' progress: 1/8 (12%) complete, 1 ok, 0 failed, 1276.26 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🥱 custom column '_needs_repair' progress: 2/8 (25%) complete, 2 ok, 0 failed, 1752.02 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🥱 custom column '_needs_repair' progress: 3/8 (38%) complete, 3 ok, 0 failed, 1786.60 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😐 custom column '_needs_repair' progress: 4/8 (50%) complete, 4 ok, 0 failed, 1977.06 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😐 custom column '_needs_repair' progress: 5/8 (62%) complete, 5 ok, 0 failed, 1962.93 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😊 custom column '_needs_repair' progress: 6/8 (75%) complete, 6 ok, 0 failed, 2086.90 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 😊 custom column '_needs_repair' progress: 7/8 (88%) complete, 7 ok, 0 failed, 2204.70 rec/s, eta 0.0s

[15:19:52] [INFO]   |-- 🤩 custom column '_needs_repair' progress: 8/8 (100%) complete, 8 ok, 0 failed, 2238.41 rec/s, eta 0.0s

[15:19:52] [INFO] 📊 Model usage summary:

[15:19:52] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:19:52] [INFO]   |-- tokens: input=58852, output=88258, total=147110, tps=649

[15:19:52] [INFO]   |-- requests: success=25, failed=0, total=25, rpm=6

[15:19:52] [INFO] 📐 Measuring dataset column statistics:

[15:19:52] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:19:52] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:19:52] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:19:52] [INFO]   |-- 🔧 column: 'utility_score'

[15:19:52] [INFO]   |-- 🔧 column: '_needs_repair'

[15:19:52] [INFO] Evaluate-repair loop iteration 2: 7/23 rows need repair

[15:19:52] [INFO] 🎨 Creating Data Designer dataset

[15:19:52] [INFO] ✅ Validation passed

[15:19:52] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:19:52] [INFO] 🩺 Running health checks for models...

[15:19:52] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:19:53] [INFO]   |-- ✅ Passed!

[15:19:53] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-2' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-2_04-03-2026_151953' instead.

[15:19:53] [INFO] ⏳ Processing batch 1 of 1

[15:19:53] [INFO] 🌱 Sampling 7 records from seed dataset

[15:19:53] [INFO]   |-- seed dataset size: 7 records

[15:19:53] [INFO]   |-- sampling strategy: ordered

[15:19:53] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:19:53] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:19:53] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:19:53] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:19:53] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:19:53] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:19:53] [INFO]   |-- 😴 custom column '_leaked_privacy_items' progress: 1/7 (14%) complete, 1 ok, 0 failed, 1088.68 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 🥱 custom column '_leaked_privacy_items' progress: 2/7 (29%) complete, 2 ok, 0 failed, 1303.92 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 🥱 custom column '_leaked_privacy_items' progress: 3/7 (43%) complete, 3 ok, 0 failed, 1412.15 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 😐 custom column '_leaked_privacy_items' progress: 4/7 (57%) complete, 4 ok, 0 failed, 1464.53 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 😐 custom column '_leaked_privacy_items' progress: 5/7 (71%) complete, 5 ok, 0 failed, 1397.95 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 😊 custom column '_leaked_privacy_items' progress: 6/7 (86%) complete, 6 ok, 0 failed, 1505.80 rec/s, eta 0.0s

[15:19:53] [INFO]   |-- 🤩 custom column '_leaked_privacy_items' progress: 7/7 (100%) complete, 7 ok, 0 failed, 1545.11 rec/s, eta 0.0s

[15:19:53] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:19:53] [INFO]   |-- generator_function: '_repair_column'

[15:19:53] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:19:53] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:19:53] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:19:53] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:19:53] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:19:53] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:20:03] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 1/7 (14%) complete, 1 ok, 0 failed, 0.09 rec/s, eta 63.5s

[15:20:04] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 2/7 (29%) complete, 2 ok, 0 failed, 0.18 rec/s, eta 27.2s

[15:20:05] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 3/7 (43%) complete, 3 ok, 0 failed, 0.25 rec/s, eta 16.1s

[15:20:08] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 4/7 (57%) complete, 4 ok, 0 failed, 0.26 rec/s, eta 11.7s

[15:20:11] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 5/7 (71%) complete, 5 ok, 0 failed, 0.27 rec/s, eta 7.4s

[15:20:13] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 6/7 (86%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 3.3s

[15:20:20] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 7/7 (100%) complete, 7 ok, 0 failed, 0.26 rec/s, eta 0.0s

[15:20:20] [INFO] 📊 Model usage summary:

[15:20:20] [INFO]   |-- model: openai/gpt-oss-120b

[15:20:20] [INFO]   |-- tokens: input=26165, output=15751, total=41916, tps=1536

[15:20:20] [INFO]   |-- requests: success=7, failed=0, total=7, rpm=15

[15:20:20] [INFO] 📐 Measuring dataset column statistics:

[15:20:20] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:20:20] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:20:20] [INFO] 🎨 Creating Data Designer dataset

[15:20:20] [INFO] ✅ Validation passed

[15:20:20] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:20:20] [INFO] 🩺 Running health checks for models...

[15:20:20] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:20:21] [INFO]   |-- ✅ Passed!

[15:20:21] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-3' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-3_04-03-2026_152021' instead.

[15:20:21] [INFO] ⏳ Processing batch 1 of 1

[15:20:21] [INFO] 🌱 Sampling 7 records from seed dataset

[15:20:21] [INFO]   |-- seed dataset size: 7 records

[15:20:21] [INFO]   |-- sampling strategy: ordered

[15:20:21] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:20:21] [INFO]   |-- generator_function: '_quality_reanswer'

[15:20:21] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:20:21] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:20:21] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:20:21] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:20:21] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:20:33] [INFO]   |-- 🌑 custom column '_quality_qa_reanswer' progress: 1/7 (14%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 72.8s

[15:20:35] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 2/7 (29%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 34.3s

[15:20:38] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 3/7 (43%) complete, 3 ok, 0 failed, 0.18 rec/s, eta 22.7s

[15:20:41] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 4/7 (57%) complete, 4 ok, 0 failed, 0.20 rec/s, eta 15.2s

[15:20:49] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 5/7 (71%) complete, 5 ok, 0 failed, 0.18 rec/s, eta 10.9s

[15:20:55] [INFO]   |-- 🌖 custom column '_quality_qa_reanswer' progress: 6/7 (86%) complete, 6 ok, 0 failed, 0.18 rec/s, eta 5.7s

[15:20:55] [INFO]   |-- 🌕 custom column '_quality_qa_reanswer' progress: 7/7 (100%) complete, 7 ok, 0 failed, 0.21 rec/s, eta 0.0s

[15:20:55] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:20:55] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:20:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:20:55] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:20:55] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:20:55] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:20:55] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:21:30] [INFO]   |-- 🌧️ custom column '_privacy_qa_reanswer' progress: 1/7 (14%) complete, 1 ok, 0 failed, 0.03 rec/s, eta 209.8s

[15:21:37] [WARNING] Evaluator returned malformed privacy answer set; missing=[36] duplicate=[] extra=[]. Applying conservative normalization.

[15:21:37] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 2/7 (29%) complete, 2 ok, 0 failed, 0.05 rec/s, eta 104.4s

[15:21:48] [INFO]   |-- 🌦️ custom column '_privacy_qa_reanswer' progress: 3/7 (43%) complete, 3 ok, 0 failed, 0.06 rec/s, eta 70.7s

[15:21:49] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 4/7 (57%) complete, 4 ok, 0 failed, 0.07 rec/s, eta 40.0s

[15:22:14] [INFO]   |-- ⛅ custom column '_privacy_qa_reanswer' progress: 5/7 (71%) complete, 5 ok, 0 failed, 0.06 rec/s, eta 31.3s

[15:22:22] [INFO]   |-- 🌤️ custom column '_privacy_qa_reanswer' progress: 6/7 (86%) complete, 6 ok, 0 failed, 0.07 rec/s, eta 14.4s

[15:22:32] [INFO]   |-- ☀️ custom column '_privacy_qa_reanswer' progress: 7/7 (100%) complete, 7 ok, 0 failed, 0.07 rec/s, eta 0.0s

[15:22:32] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:22:32] [INFO]   |-- generator_function: '_quality_compare'

[15:22:32] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:22:32] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:22:32] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:22:32] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:22:32] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:22:47] [INFO]   |-- 🌑 custom column '_quality_qa_compare' progress: 1/7 (14%) complete, 1 ok, 0 failed, 0.07 rec/s, eta 88.9s

[15:22:48] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 2/7 (29%) complete, 2 ok, 0 failed, 0.13 rec/s, eta 39.9s

[15:22:50] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 3/7 (43%) complete, 3 ok, 0 failed, 0.17 rec/s, eta 24.0s

[15:22:51] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 4/7 (57%) complete, 4 ok, 0 failed, 0.22 rec/s, eta 13.9s

[15:22:59] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 5/7 (71%) complete, 5 ok, 0 failed, 0.18 rec/s, eta 10.9s

[15:23:03] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 6/7 (86%) complete, 6 ok, 0 failed, 0.19 rec/s, eta 5.2s

[15:23:12] [INFO]   |-- 🌕 custom column '_quality_qa_compare' progress: 7/7 (100%) complete, 7 ok, 0 failed, 0.18 rec/s, eta 0.0s

[15:23:12] [INFO] 🔧 Custom column config for column 'utility_score'

[15:23:12] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:23:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:12] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:23:12] [INFO]   |-- side_effect_columns: ['leakage_mass', 'weighted_leakage_rate', 'any_high_leaked']

[15:23:12] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:23:12] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:23:12] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:23:12] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 1/7 (14%) complete, 1 ok, 0 failed, 522.75 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 2/7 (29%) complete, 2 ok, 0 failed, 591.82 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 3/7 (43%) complete, 3 ok, 0 failed, 606.82 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ⛅ custom column 'utility_score' progress: 4/7 (57%) complete, 4 ok, 0 failed, 673.38 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ⛅ custom column 'utility_score' progress: 5/7 (71%) complete, 5 ok, 0 failed, 654.24 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 6/7 (86%) complete, 6 ok, 0 failed, 743.58 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ☀️ custom column 'utility_score' progress: 7/7 (100%) complete, 7 ok, 0 failed, 827.00 rec/s, eta 0.0s

[15:23:12] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:23:12] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:23:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:23:12] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:23:12] [INFO]   |-- generator_params: repair_any_high_leak=True effective_threshold=0.6

[15:23:12] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:23:12] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:23:12] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 1/7 (14%) complete, 1 ok, 0 failed, 2079.54 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 2/7 (29%) complete, 2 ok, 0 failed, 2688.17 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 3/7 (43%) complete, 3 ok, 0 failed, 2538.52 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 4/7 (57%) complete, 4 ok, 0 failed, 2560.89 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 5/7 (71%) complete, 5 ok, 0 failed, 2347.33 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 6/7 (86%) complete, 6 ok, 0 failed, 2321.01 rec/s, eta 0.0s

[15:23:12] [INFO]   |-- ☀️ custom column '_needs_repair' progress: 7/7 (100%) complete, 7 ok, 0 failed, 2171.16 rec/s, eta 0.0s

[15:23:12] [INFO] 📊 Model usage summary:

[15:23:12] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:23:12] [INFO]   |-- tokens: input=48628, output=70153, total=118781, tps=694

[15:23:12] [INFO]   |-- requests: success=21, failed=0, total=21, rpm=7

[15:23:12] [INFO] 📐 Measuring dataset column statistics:

[15:23:12] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:23:12] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:23:12] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:23:12] [INFO]   |-- 🔧 column: 'utility_score'

[15:23:12] [INFO]   |-- 🔧 column: '_needs_repair'

[15:23:12] [INFO] 🎨 Creating Data Designer dataset

[15:23:12] [INFO] ✅ Validation passed

[15:23:12] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:23:12] [INFO] 🩺 Running health checks for models...

[15:23:12] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:23:13] [INFO]   |-- ✅ Passed!

[15:23:13] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-final-judge' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-final-judge_04-03-2026_152313' instead.

[15:23:13] [INFO] ⏳ Processing batch 1 of 1

[15:23:13] [INFO] 🌱 Sampling 23 records from seed dataset

[15:23:13] [INFO]   |-- seed dataset size: 23 records

[15:23:13] [INFO]   |-- sampling strategy: ordered

[15:23:13] [INFO] ⚖️ llm-judge model config for column '_judge_evaluation'

[15:23:13] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:23:13] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:23:13] [INFO]   |-- model provider: 'nvidia'

[15:23:13] [INFO]   |-- inference parameters:

[15:23:13] [INFO]   |  |-- generation_type=chat-completion

[15:23:13] [INFO]   |  |-- max_parallel_requests=16

[15:23:13] [INFO]   |  |-- timeout=300

[15:23:13] [INFO]   |  |-- temperature=0.40

[15:23:13] [INFO]   |  |-- top_p=1.00

[15:23:13] [INFO]   |  |-- max_tokens=8192

[15:23:13] [INFO] ⚡️ Processing llm-judge column '_judge_evaluation' with 16 concurrent workers

[15:23:13] [INFO] ⏱️ llm-judge column '_judge_evaluation' will report progress every 2 records

[15:23:26] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 2/23 (9%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 140.5s

[15:23:31] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 4/23 (17%) complete, 4 ok, 0 failed, 0.23 rec/s, eta 83.4s

[15:23:33] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 6/23 (26%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 55.8s

[15:23:35] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 8/23 (35%) complete, 8 ok, 0 failed, 0.37 rec/s, eta 40.3s

[15:23:36] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 10/23 (43%) complete, 10 ok, 0 failed, 0.43 rec/s, eta 30.4s

[15:23:38] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 12/23 (52%) complete, 12 ok, 0 failed, 0.49 rec/s, eta 22.5s

[15:23:40] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 14/23 (61%) complete, 14 ok, 0 failed, 0.52 rec/s, eta 17.2s

[15:23:49] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 16/23 (70%) complete, 16 ok, 0 failed, 0.45 rec/s, eta 15.7s

[15:23:50] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 18/23 (78%) complete, 18 ok, 0 failed, 0.48 rec/s, eta 10.4s

[15:23:56] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 20/23 (87%) complete, 20 ok, 0 failed, 0.47 rec/s, eta 6.4s

[15:24:04] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 22/23 (96%) complete, 22 ok, 0 failed, 0.43 rec/s, eta 2.3s

[15:24:05] [INFO]   |-- 🤩 llm-judge column '_judge_evaluation' progress: 23/23 (100%) complete, 23 ok, 0 failed, 0.44 rec/s, eta 0.0s

[15:24:05] [INFO] 🔧 Custom column config for column 'needs_human_review'

[15:24:05] [INFO]   |-- generator_function: '_determine_needs_human_review'

[15:24:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:24:05] [INFO]   |-- required_columns: ['_rewritten_text', 'utility_score', 'leakage_mass', 'any_high_leaked']

[15:24:05] [INFO]   |-- generator_params: flag_utility_below=0.6 flag_leakage_above=1.0

[15:24:05] [INFO] ⚡️ Processing custom column 'needs_human_review' with 4 concurrent workers

[15:24:05] [INFO] ⏱️ custom column 'needs_human_review' will report progress every 2 records

[15:24:05] [INFO]   |-- 🌑 custom column 'needs_human_review' progress: 2/23 (9%) complete, 2 ok, 0 failed, 1393.53 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌑 custom column 'needs_human_review' progress: 4/23 (17%) complete, 4 ok, 0 failed, 1596.22 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 6/23 (26%) complete, 6 ok, 0 failed, 1696.69 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 8/23 (35%) complete, 8 ok, 0 failed, 1919.63 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 10/23 (43%) complete, 10 ok, 0 failed, 2106.30 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 12/23 (52%) complete, 12 ok, 0 failed, 2244.02 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 14/23 (61%) complete, 14 ok, 0 failed, 2367.16 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 16/23 (70%) complete, 16 ok, 0 failed, 2496.46 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌖 custom column 'needs_human_review' progress: 18/23 (78%) complete, 18 ok, 0 failed, 2632.99 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌖 custom column 'needs_human_review' progress: 20/23 (87%) complete, 20 ok, 0 failed, 2727.82 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌖 custom column 'needs_human_review' progress: 22/23 (96%) complete, 22 ok, 0 failed, 2806.51 rec/s, eta 0.0s

[15:24:05] [INFO]   |-- 🌕 custom column 'needs_human_review' progress: 23/23 (100%) complete, 23 ok, 0 failed, 2800.85 rec/s, eta 0.0s

[15:24:06] [INFO] 📊 Model usage summary:

[15:24:06] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:24:06] [INFO]   |-- tokens: input=87358, output=68792, total=156150, tps=2966

[15:24:06] [INFO]   |-- requests: success=23, failed=0, total=23, rpm=26

[15:24:06] [INFO] 📐 Measuring dataset column statistics:

[15:24:06] [INFO]   |-- ⚖️ column: '_judge_evaluation'

[15:24:06] [INFO]   |-- 🔧 column: 'needs_human_review'

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/row_partitioning.py:42: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(list(parts), ignore_index=True)
[15:24:06] [INFO]   |-- 📋 Rewrite complete (2 failed) [2512.4s]

[15:24:06] [WARNING] 2 record(s) failed during pipeline processing.

[15:24:06] [INFO] 🎉 Pipeline complete — 25 records processed, 2 total failures

,text,text_rewritten,utility_score,leakage_mass,weighted_leakage_rate,any_high_leaked,needs_human_review
0,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.971429,0.0,0.0,False,False
1,PROCEDURE The case originated in an applicati...,Procedure The case originated in an applicati...,0.822222,0.0,0.0,False,False
2,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.90625,1.7,0.05414,True,True
3,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.928571,0.0,0.0,False,False
4,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.857143,0.0,0.0,False,False

In [ ]:
result.dataframe[["text_rewritten", "utility_score", "leakage_mass", "needs_human_review"]].head()

,text_rewritten,utility_score,leakage_mass,needs_human_review
0,PROCEDURE The case originated in an applicati...,0.971429,0.0,False
1,Procedure The case originated in an applicati...,0.822222,0.0,False
2,PROCEDURE The case originated in an applicati...,0.90625,1.7,True
3,PROCEDURE The case originated in an applicati...,0.928571,0.0,False
4,PROCEDURE The case originated in an applicati...,0.857143,0.0,False

## 🚩 Filter by review flag

- Records where automated metrics exceed thresholds are flagged for manual review.
- Use this to prioritize human attention on the records that need it most.
- See [Working with flagged records](../concepts/rewrite.md#working-with-flagged-records)
  for guidance on diagnosing and resolving flagged records.

In [ ]:
df = result.dataframe
flagged = df[df["needs_human_review"] == True]  # noqa: E712
print(f"{len(flagged)} of {len(df)} records flagged for human review")
flagged.head()

6 of 23 records flagged for human review

,text,text_rewritten,utility_score,leakage_mass,weighted_leakage_rate,any_high_leaked,needs_human_review
2,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.90625,1.7,0.05414,True,True
8,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.96,3.052,0.127167,True,True
11,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,1.0,0.9,0.046392,True,True
12,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.866667,2.97,0.086589,True,True
13,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.981818,3.1,0.133621,True,True

## ⏭️ Next steps

- **[🔍 Inspecting Detected Entities](02_inspecting_detected_entities.ipynb)** --
  debug what the detection pipeline found before rewriting.
- **Try it on your own data!** Swap in your CSV, define entity labels for your
  domain, and set a `PrivacyGoal` that fits -- you've got all the building blocks.