# Rewriting Legal Documents

Rewriting legal text (TAB dataset) with a domain-specific privacy goal
and custom entity labels tailored for legal proceedings.

## Setup

In [1]:
from anonymizer import Anonymizer, AnonymizerConfig, AnonymizerInput, Detect, LoggingConfig, Rewrite, configure_logging
from anonymizer.config.rewrite import EvaluationCriteria, PrivacyGoal, RiskTolerance

configure_logging(LoggingConfig.debug())

In [2]:
anonymizer = Anonymizer()

[15:52:09] [INFO] 🔧 Anonymizer initialized with 3 model configs

[15:52:09] [INFO]   |-- 🔎 detector:  gliner-pii-detector

[15:52:09] [INFO]   |-- ✅ validator: gpt-oss-120b

[15:52:09] [INFO]   |-- 🧩 augmenter: gpt-oss-120b

[15:52:09] [DEBUG] NDD adapter: artifact_path=.anonymizer-artifacts

## Input data

TAB (Text Anonymization Benchmark) legal documents -- court decisions
containing names, dates, case numbers, and other legal identifiers.

In [3]:
LEGAL_ENTITY_LABELS = [
    "first_name", "last_name", "court_name",
    "organization_name", "company_name", "prison_detention_facility",
    "street_address", "city", "state", "country", "date", "date_time", "time",
    "date_of_birth", "age", "email", "phone_number", "ssn", "unique_id", "legal_role",
    "case_number", "application_number", "monetary_amount", "sentence_duration", "nationality",
]

input_data = AnonymizerInput(
    source="../data/TAB_legal_sample25.csv",
    text_column="text",
    data_summary="Legal court decisions containing personal identifiers, case numbers, and institutional references",
)

## Rewrite with legal-specific config

In [4]:
config = AnonymizerConfig(
    detect=Detect(
        entity_labels=LEGAL_ENTITY_LABELS,
    ),
    rewrite=Rewrite(
        privacy_goal=PrivacyGoal(
            protect="All personal identifiers, case numbers, court names, and institutional references that could identify parties",
            preserve="Legal reasoning, procedural facts, statutory references, and the structure of the ruling",
        ),
        evaluation=EvaluationCriteria(
            risk_tolerance=RiskTolerance.strict,
            max_repair_iterations=3,
        ),
    ),
)

preview = anonymizer.preview(
    config=config,
    data=input_data,
    num_records=3,
)

preview.display_record(0)

[15:52:09] [INFO] 📂 Loaded 25 records from ../data/TAB_legal_sample25.csv (column: 'text')

[15:52:09] [DEBUG] input text lengths: min=2312, max=4758, mean=3458 chars (25 records)

[15:52:09] [DEBUG] detection config: threshold=0.30, labels=['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id']

[15:52:09] [INFO]   |-- 👀 Preview mode: processing 3 of 25 records

[15:52:09] [INFO] 🔍 Running entity detection on 3 records

[15:52:09] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[15:52:09] [DEBUG] NDD workflow 'entity-detection' starting with 25 records

[15:52:09] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[15:52:09] [INFO] 🖼️ Preview generation in progress

[15:52:13] [INFO] ✅ Validation passed

[15:52:13] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:52:13] [INFO] 🩺 Running health checks for models...

[15:52:13] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:52:14] [INFO]   |-- ✅ Passed!

[15:52:14] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...

[15:52:15] [INFO]   |-- ✅ Passed!

[15:52:15] [INFO] 🌱 Sampling 3 records from seed dataset

[15:52:15] [INFO]   |-- seed dataset size: 25 records

[15:52:15] [INFO]   |-- sampling strategy: ordered

[15:52:15] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:52:15] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:52:15] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:52:15] [INFO]   |-- model provider: 'nvidia'

[15:52:15] [INFO]   |-- inference parameters:

[15:52:15] [INFO]   |  |-- generation_type=chat-completion

[15:52:15] [INFO]   |  |-- max_parallel_requests=4

[15:52:15] [INFO]   |  |-- timeout=120

[15:52:15] [INFO]   |  |-- extra_body={'labels': ['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:52:15] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 4 concurrent workers

[15:52:15] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record

[15:52:16] [INFO]   |-- 🐣 llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.16 rec/s, eta 1.7s

[15:52:16] [INFO]   |-- 🐥 llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1.54 rec/s, eta 0.6s

[15:52:16] [INFO]   |-- 🐔 llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2.05 rec/s, eta 0.0s

[15:52:16] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:52:16] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:52:16] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:52:16] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:52:16] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:52:16] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:52:16] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record

[15:52:16] [INFO]   |-- 🥱 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 658.47 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 😐 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 714.04 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 🤩 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 702.83 rec/s, eta 0.0s

[15:52:16] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:52:16] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:52:16] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:52:16] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:52:16] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:52:16] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:52:16] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record

[15:52:16] [INFO]   |-- 🐣 custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1192.61 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 🐥 custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1373.86 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 🐔 custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1302.27 rec/s, eta 0.0s

[15:52:16] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:52:16] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:52:16] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:52:16] [INFO]   |-- required_columns: ['_validation_candidates']

[15:52:16] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:52:16] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record

[15:52:16] [INFO]   |-- 🐴 custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1669.45 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 🚗 custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1763.73 rec/s, eta 0.0s

[15:52:16] [INFO]   |-- 🚀 custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1833.60 rec/s, eta 0.0s

[15:52:16] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:52:16] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:52:16] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:52:16] [INFO]   |-- model provider: 'nvidia'

[15:52:16] [INFO]   |-- inference parameters:

[15:52:16] [INFO]   |  |-- generation_type=chat-completion

[15:52:16] [INFO]   |  |-- max_parallel_requests=2

[15:52:16] [INFO]   |  |-- timeout=300

[15:52:16] [INFO]   |  |-- temperature=0.30

[15:52:16] [INFO]   |  |-- top_p=0.95

[15:52:16] [INFO]   |  |-- max_tokens=16384

[15:52:16] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 2 concurrent workers

[15:52:16] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record

[15:52:27] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.09 rec/s, eta 22.1s

[15:52:43] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.08 rec/s, eta 13.2s

[15:52:49] [INFO]   |-- 🚀 llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 0.0s

[15:52:49] [INFO] 🔧 Custom column config for column '_validated_entities'

[15:52:49] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[15:52:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:52:49] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[15:52:49] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[15:52:49] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record

[15:52:49] [INFO]   |-- 😺 custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 591.73 rec/s, eta 0.0s

[15:52:49] [INFO]   |-- 😸 custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 673.06 rec/s, eta 0.0s

[15:52:49] [INFO]   |-- 🦁 custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 516.46 rec/s, eta 0.0s

[15:52:49] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[15:52:49] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[15:52:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:52:49] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[15:52:49] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[15:52:49] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[15:52:49] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record

[15:52:49] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 813.89 rec/s, eta 0.0s

[15:52:49] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 885.49 rec/s, eta 0.0s

[15:52:49] [INFO]   |-- 🐔 custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 918.16 rec/s, eta 0.0s

[15:52:49] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[15:52:49] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:52:49] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:52:49] [INFO]   |-- model provider: 'nvidia'

[15:52:49] [INFO]   |-- inference parameters:

[15:52:49] [INFO]   |  |-- generation_type=chat-completion

[15:52:49] [INFO]   |  |-- max_parallel_requests=2

[15:52:49] [INFO]   |  |-- timeout=300

[15:52:49] [INFO]   |  |-- temperature=0.30

[15:52:49] [INFO]   |  |-- top_p=0.95

[15:52:49] [INFO]   |  |-- max_tokens=16384

[15:52:49] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 2 concurrent workers

[15:52:49] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record

[15:52:53] [INFO]   |-- 🐴 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.25 rec/s, eta 8.0s

[15:52:59] [INFO]   |-- 🚗 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 4.7s

[15:53:00] [INFO]   |-- 🚀 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.28 rec/s, eta 0.0s

[15:53:00] [INFO] 🔧 Custom column config for column '_merged_entities'

[15:53:00] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[15:53:00] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:53:00] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[15:53:00] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:53:00] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[15:53:00] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record

[15:53:00] [INFO]   |-- 😺 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 554.85 rec/s, eta 0.0s

[15:53:00] [INFO]   |-- 😸 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 367.52 rec/s, eta 0.0s

[15:53:00] [INFO]   |-- 🦁 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 324.53 rec/s, eta 0.0s

[15:53:00] [INFO] 🔧 Custom column config for column '_detected_entities'

[15:53:00] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[15:53:00] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:53:00] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[15:53:00] [INFO]   |-- side_effect_columns: ['tagged_text']

[15:53:00] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[15:53:00] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record

[15:53:00] [INFO]   |-- 🥱 custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 116.12 rec/s, eta 0.0s

[15:53:00] [INFO]   |-- 😐 custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 62.76 rec/s, eta 0.0s

[15:53:00] [INFO]   |-- 🤩 custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 92.74 rec/s, eta 0.0s

[15:53:00] [INFO] 📊 Model usage summary:

[15:53:00] [INFO]   |-- model: nvidia/gliner-pii

[15:53:00] [INFO]   |-- tokens: input=1825, output=3741, total=5566, tps=122

[15:53:00] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=3

[15:53:00] [INFO]   |--

[15:53:00] [INFO]   |-- model: openai/gpt-oss-120b

[15:53:00] [INFO]   |-- tokens: input=29152, output=14587, total=43739, tps=962

[15:53:00] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=7

[15:53:00] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[15:53:00] [INFO] 📐 Measuring dataset column statistics:

[15:53:00] [INFO]   |-- 📝 column: '_raw_detected_entities'

[15:53:00] [INFO]   |-- 🔧 column: '_seed_entities'

[15:53:00] [INFO]   |-- 🔧 column: '_validation_candidates'

[15:53:00] [INFO]   |-- 🔧 column: '_validated_entities'

[15:53:00] [INFO]   |-- 🔧 column: '_seed_entities_json'

[15:53:00] [INFO]   |-- 🗂️ column: '_augmented_entities'

[15:53:00] [INFO]   |-- 🔧 column: '_merged_entities'

[15:53:00] [INFO]   |-- 🔧 column: '_detected_entities'

[15:53:00] [INFO] ✅ Preview complete!

[15:53:00] [DEBUG] NDD workflow 'entity-detection' returned 3 records

[15:53:00] [DEBUG] NDD workflow 'latent-entity-detection' starting with 3 records

[15:53:00] [DEBUG] NDD workflow 'latent-entity-detection': 1 columns ['_latent_entities']

[15:53:00] [INFO] 🔭 Preview generation in progress

[15:53:00] [INFO] ✅ Validation passed

[15:53:00] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:53:00] [INFO] 🩺 Running health checks for models...

[15:53:00] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:53:01] [INFO]   |-- ✅ Passed!

[15:53:01] [INFO] 🌱 Sampling 3 records from seed dataset

[15:53:01] [INFO]   |-- seed dataset size: 3 records

[15:53:01] [INFO]   |-- sampling strategy: ordered

[15:53:01] [INFO] 🗂️ llm-structured model config for column '_latent_entities'

[15:53:01] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:53:01] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:53:01] [INFO]   |-- model provider: 'nvidia'

[15:53:01] [INFO]   |-- inference parameters:

[15:53:01] [INFO]   |  |-- generation_type=chat-completion

[15:53:01] [INFO]   |  |-- max_parallel_requests=16

[15:53:01] [INFO]   |  |-- timeout=300

[15:53:01] [INFO]   |  |-- temperature=0.40

[15:53:01] [INFO]   |  |-- top_p=1.00

[15:53:01] [INFO]   |  |-- max_tokens=8192

[15:53:01] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers

[15:53:01] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress after each record

[15:53:19] [INFO]   |-- 🥱 llm-structured column '_latent_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.06 rec/s, eta 36.3s

[15:53:20] [INFO]   |-- 😐 llm-structured column '_latent_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.10 rec/s, eta 9.8s

[15:53:36] [INFO]   |-- 🤩 llm-structured column '_latent_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 0.0s

[15:53:36] [INFO] 📊 Model usage summary:

[15:53:36] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:53:36] [INFO]   |-- tokens: input=7964, output=14670, total=22634, tps=645

[15:53:36] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=5

[15:53:36] [INFO] 📐 Measuring dataset column statistics:

[15:53:36] [INFO]   |-- 🗂️ column: '_latent_entities'

[15:53:36] [INFO] 🥳 Preview complete!

[15:53:36] [DEBUG] NDD workflow 'latent-entity-detection' returned 3 records

[15:53:36] [INFO]   |-- 📋 Detection complete — 139 entities found across 3 records (0 failed) [87.1s]

[15:53:36] [INFO]   |-- labels: date=51, court_name=35, legal_role=10, nationality=7, last_name=7, organization_name=6, country=5, city=5, application_number=3, first_name=3, date_of_birth=3, monetary_amount=2, case_number=1, sentence_duration=1

[15:53:36] [INFO] ✏️ Running rewrite pipeline

[15:53:36] [DEBUG] NDD workflow 'replace-map-generation' starting with 3 records

[15:53:36] [DEBUG] NDD workflow 'replace-map-generation': 1 columns ['_replacement_map']

[15:53:36] [INFO] 🎨 Creating Data Designer dataset

[15:53:36] [INFO] ✅ Validation passed

[15:53:36] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:53:36] [INFO] 🩺 Running health checks for models...

[15:53:36] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:53:37] [INFO]   |-- ✅ Passed!

[15:53:37] [INFO] 📂 Dataset path '.anonymizer-artifacts/replace-map-generation' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/replace-map-generation_03-31-2026_155337' instead.

[15:53:37] [INFO] ⏳ Processing batch 1 of 1

[15:53:37] [INFO] 🌱 Sampling 3 records from seed dataset

[15:53:37] [INFO]   |-- seed dataset size: 3 records

[15:53:37] [INFO]   |-- sampling strategy: ordered

[15:53:37] [INFO] 🗂️ llm-structured model config for column '_replacement_map'

[15:53:37] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:53:37] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:53:37] [INFO]   |-- model provider: 'nvidia'

[15:53:37] [INFO]   |-- inference parameters:

[15:53:37] [INFO]   |  |-- generation_type=chat-completion

[15:53:37] [INFO]   |  |-- max_parallel_requests=2

[15:53:37] [INFO]   |  |-- timeout=300

[15:53:37] [INFO]   |  |-- temperature=0.30

[15:53:37] [INFO]   |  |-- top_p=0.95

[15:53:37] [INFO]   |  |-- max_tokens=16384

[15:53:37] [INFO] ⚡️ Processing llm-structured column '_replacement_map' with 2 concurrent workers

[15:53:37] [INFO] ⏱️ llm-structured column '_replacement_map' will report progress after each record

[15:53:47] [INFO]   |-- 🐣 llm-structured column '_replacement_map' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.10 rec/s, eta 20.0s

[15:53:57] [INFO]   |-- 🐥 llm-structured column '_replacement_map' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.10 rec/s, eta 10.2s

[15:54:05] [INFO]   |-- 🐔 llm-structured column '_replacement_map' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.10 rec/s, eta 0.0s

[15:54:06] [INFO] 📊 Model usage summary:

[15:54:06] [INFO]   |-- model: openai/gpt-oss-120b

[15:54:06] [INFO]   |-- tokens: input=8016, output=9612, total=17628, tps=602

[15:54:06] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=6

[15:54:06] [INFO] 📐 Measuring dataset column statistics:

[15:54:06] [INFO]   |-- 🗂️ column: '_replacement_map'

[15:54:06] [DEBUG] NDD workflow 'replace-map-generation' returned 3 records

[15:54:06] [DEBUG] Replacement map record 4b0aa40e665254958f579ede68e86fcd: requested=[('12 February 1980', 'date'), ('14 June 2005', 'date'), ('14 September 1999', 'date'), ('15 December 2000', 'date'), ('16 November 2000', 'date'), ('1958', 'date'), ('23 October 1992', 'date_of_birth'), ('27 December 1999', 'date'), ('5 April 2000', 'date'), ('74463/01', 'application_number'), ('8 June 2001', 'date'), ('Aydın', 'city'), ('Aydın Civil Court of first-instance', 'court_name'), ('Bahçeyaka', 'last_name'), ('Court of Cassation', 'court_name'), ('Feriştah', 'first_name'), ('German', 'nationality'), ('Germany', 'country'), ('Kuloğlu', 'last_name'), ('Republic of Turkey', 'country'), ('Turkish', 'nationality'), ('Wesel', 'city'), ('lawyer', 'legal_role')] raw=[{'original': '12 February 1980', 'label': 'date', 'synthetic': '23 March 1979'}, {'original': '14 June 2005', 'label': 'date', 'synthetic': '09 July 2006'}, {'original': '14 September 1999', 'label': 'date', 'synthetic': '21 October 2000'}, {'original': '15 December 2000', 'label': 'date', 'synthetic': '02 January 2001'}, {'original': '16 November 2000', 'label': 'date', 'synthetic': '05 December 2001'}, {'original': '1958', 'label': 'date', 'synthetic': '1962'}, {'original': '23 October 1992', 'label': 'date_of_birth', 'synthetic': '11 November 1993'}, {'original': '27 December 1999', 'label': 'date', 'synthetic': '03 January 2000'}, {'original': '5 April 2000', 'label': 'date', 'synthetic': '18 May 2001'}, {'original': '8 June 2001', 'label': 'date', 'synthetic': '12 August 2002'}, {'original': '74463/01', 'label': 'application_number', 'synthetic': '83927/02'}, {'original': 'Aydın', 'label': 'city', 'synthetic': 'Granada'}, {'original': 'Aydın Civil Court of first-instance', 'label': 'court_name', 'synthetic': 'Granada Civil Court of First Instance'}, {'original': 'Bahçeyaka', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Spain'}, {'original': 'Feriştah', 'label': 'first_name', 'synthetic': 'María'}, {'original': 'German', 'label': 'nationality', 'synthetic': 'French'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Kuloğlu', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Wesel', 'label': 'city', 'synthetic': 'Lille'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'notary'}] filtered=[{'original': '12 February 1980', 'label': 'date', 'synthetic': '23 March 1979'}, {'original': '14 June 2005', 'label': 'date', 'synthetic': '09 July 2006'}, {'original': '14 September 1999', 'label': 'date', 'synthetic': '21 October 2000'}, {'original': '15 December 2000', 'label': 'date', 'synthetic': '02 January 2001'}, {'original': '16 November 2000', 'label': 'date', 'synthetic': '05 December 2001'}, {'original': '1958', 'label': 'date', 'synthetic': '1962'}, {'original': '23 October 1992', 'label': 'date_of_birth', 'synthetic': '11 November 1993'}, {'original': '27 December 1999', 'label': 'date', 'synthetic': '03 January 2000'}, {'original': '5 April 2000', 'label': 'date', 'synthetic': '18 May 2001'}, {'original': '8 June 2001', 'label': 'date', 'synthetic': '12 August 2002'}, {'original': '74463/01', 'label': 'application_number', 'synthetic': '83927/02'}, {'original': 'Aydın', 'label': 'city', 'synthetic': 'Granada'}, {'original': 'Aydın Civil Court of first-instance', 'label': 'court_name', 'synthetic': 'Granada Civil Court of First Instance'}, {'original': 'Bahçeyaka', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Spain'}, {'original': 'Feriştah', 'label': 'first_name', 'synthetic': 'María'}, {'original': 'German', 'label': 'nationality', 'synthetic': 'French'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Kuloğlu', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Wesel', 'label': 'city', 'synthetic': 'Lille'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'notary'}]

[15:54:06] [DEBUG] Replacement map record fffc4038297b5cf19b2a149604f8dc42: requested=[('14 February 2002', 'date'), ('14 July 1998', 'date'), ('15 January 2001', 'date'), ('17 June 2004', 'date'), ('17 September 2004', 'date'), ('18 January 2005', 'date'), ('1940', 'date_of_birth'), ('2 January 2006', 'date'), ('200 Polish zlotys', 'monetary_amount'), ('2004', 'date'), ('24 October 2006', 'date'), ('25 October 2004', 'date'), ('25 September 2007', 'date'), ('26 July 2004', 'date'), ('29360/06', 'application_number'), ('3 August 2000', 'date'), ('3 July 1998', 'date'), ('3 July 2006', 'date'), ('30 June 2004', 'date'), ('50 euros', 'monetary_amount'), ('7 November 1997', 'date'), ('8 March 1994', 'date'), ('9 February 1998', 'date'), ('9 May 2006', 'date'), ('9 May 2007', 'date'), ('Agent', 'legal_role'), ('District Court', 'court_name'), ('III SPP 113/04', 'case_number'), ('Jerzak', 'last_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('President of the Fourth Section', 'legal_role'), ('Regional Court', 'court_name'), ('Republic of Poland', 'country'), ('Sulejówek', 'city'), ('Supreme Court', 'organization_name'), ('Sąd Najwyższy', 'court_name'), ('Teresa', 'first_name'), ('Warsaw District Court', 'court_name'), ('Warsaw District Court (Sąd Rejonowy)', 'court_name'), ('Warsaw Regional Court', 'court_name'), ('Warsaw Regional Court (Sąd Okręgowy)', 'court_name'), ('Wołąsiewicz', 'last_name')] raw=[{'original': '14 February 2002', 'label': 'date', 'synthetic': '22 March 2003'}, {'original': '14 July 1998', 'label': 'date', 'synthetic': '19 August 1999'}, {'original': '15 January 2001', 'label': 'date', 'synthetic': '27 February 2002'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '05 May 2005'}, {'original': '17 September 2004', 'label': 'date', 'synthetic': '12 October 2005'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '03 March 2006'}, {'original': '1940', 'label': 'date_of_birth', 'synthetic': '1955'}, {'original': '2 January 2006', 'label': 'date', 'synthetic': '11 February 2007'}, {'original': '200 Polish zlotys', 'label': 'monetary_amount', 'synthetic': '150 Czech korunas'}, {'original': '2004', 'label': 'date', 'synthetic': '2010'}, {'original': '24 October 2006', 'label': 'date', 'synthetic': '08 November 2007'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '14 November 2005'}, {'original': '25 September 2007', 'label': 'date', 'synthetic': '02 October 2008'}, {'original': '26 July 2004', 'label': 'date', 'synthetic': '09 August 2005'}, {'original': '29360/06', 'label': 'application_number', 'synthetic': '37421/09'}, {'original': '3 August 2000', 'label': 'date', 'synthetic': '17 September 2001'}, {'original': '3 July 1998', 'label': 'date', 'synthetic': '21 August 1999'}, {'original': '3 July 2006', 'label': 'date', 'synthetic': '15 August 2007'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '04 July 2005'}, {'original': '50 euros', 'label': 'monetary_amount', 'synthetic': '70 dollars'}, {'original': '7 November 1997', 'label': 'date', 'synthetic': '13 December 1998'}, {'original': '8 March 1994', 'label': 'date', 'synthetic': '16 April 1995'}, {'original': '9 February 1998', 'label': 'date', 'synthetic': '23 March 1999'}, {'original': '9 May 2006', 'label': 'date', 'synthetic': '18 June 2007'}, {'original': '9 May 2007', 'label': 'date', 'synthetic': '20 June 2008'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Representative'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Division'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Czech Local Court'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Czech Provincial Court'}, {'original': 'Warsaw District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Prague Municipal Court (Městský soud)'}, {'original': 'Warsaw District Court', 'label': 'court_name', 'synthetic': 'Prague Municipal Court'}, {'original': 'Warsaw Regional Court (Sąd Okręgowy)', 'label': 'court_name', 'synthetic': 'Prague Regional Court (Krajský soud)'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Prague Regional Court'}, {'original': 'III SPP 113/04', 'label': 'case_number', 'synthetic': 'IV SPP 215/07'}, {'original': 'Jerzak', 'label': 'last_name', 'synthetic': 'Novak'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kral'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Justice'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Czech'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Czechia'}, {'original': 'Sulejówek', 'label': 'city', 'synthetic': 'Prague'}, {'original': 'Supreme Court', 'label': 'organization_name', 'synthetic': 'Constitutional Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Ústavní soud'}, {'original': 'Teresa', 'label': 'first_name', 'synthetic': 'Marta'}] filtered=[{'original': '14 February 2002', 'label': 'date', 'synthetic': '22 March 2003'}, {'original': '14 July 1998', 'label': 'date', 'synthetic': '19 August 1999'}, {'original': '15 January 2001', 'label': 'date', 'synthetic': '27 February 2002'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '05 May 2005'}, {'original': '17 September 2004', 'label': 'date', 'synthetic': '12 October 2005'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '03 March 2006'}, {'original': '1940', 'label': 'date_of_birth', 'synthetic': '1955'}, {'original': '2 January 2006', 'label': 'date', 'synthetic': '11 February 2007'}, {'original': '200 Polish zlotys', 'label': 'monetary_amount', 'synthetic': '150 Czech korunas'}, {'original': '2004', 'label': 'date', 'synthetic': '2010'}, {'original': '24 October 2006', 'label': 'date', 'synthetic': '08 November 2007'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '14 November 2005'}, {'original': '25 September 2007', 'label': 'date', 'synthetic': '02 October 2008'}, {'original': '26 July 2004', 'label': 'date', 'synthetic': '09 August 2005'}, {'original': '29360/06', 'label': 'application_number', 'synthetic': '37421/09'}, {'original': '3 August 2000', 'label': 'date', 'synthetic': '17 September 2001'}, {'original': '3 July 1998', 'label': 'date', 'synthetic': '21 August 1999'}, {'original': '3 July 2006', 'label': 'date', 'synthetic': '15 August 2007'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '04 July 2005'}, {'original': '50 euros', 'label': 'monetary_amount', 'synthetic': '70 dollars'}, {'original': '7 November 1997', 'label': 'date', 'synthetic': '13 December 1998'}, {'original': '8 March 1994', 'label': 'date', 'synthetic': '16 April 1995'}, {'original': '9 February 1998', 'label': 'date', 'synthetic': '23 March 1999'}, {'original': '9 May 2006', 'label': 'date', 'synthetic': '18 June 2007'}, {'original': '9 May 2007', 'label': 'date', 'synthetic': '20 June 2008'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Representative'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Division'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Czech Local Court'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Czech Provincial Court'}, {'original': 'Warsaw District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Prague Municipal Court (Městský soud)'}, {'original': 'Warsaw District Court', 'label': 'court_name', 'synthetic': 'Prague Municipal Court'}, {'original': 'Warsaw Regional Court (Sąd Okręgowy)', 'label': 'court_name', 'synthetic': 'Prague Regional Court (Krajský soud)'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Prague Regional Court'}, {'original': 'III SPP 113/04', 'label': 'case_number', 'synthetic': 'IV SPP 215/07'}, {'original': 'Jerzak', 'label': 'last_name', 'synthetic': 'Novak'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kral'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Justice'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Czech'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Czechia'}, {'original': 'Sulejówek', 'label': 'city', 'synthetic': 'Prague'}, {'original': 'Supreme Court', 'label': 'organization_name', 'synthetic': 'Constitutional Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Ústavní soud'}, {'original': 'Teresa', 'label': 'first_name', 'synthetic': 'Marta'}]

[15:54:06] [DEBUG] Replacement map record 53ab2db826735fb9b51f8432e5107099: requested=[('1 November 1998', 'date'), ('1 November 2004', 'date'), ('10 September 1994', 'date'), ('11 August 2000', 'date'), ('15 April 1999', 'date'), ('16 December 1994', 'date'), ('17 August 1998', 'date'), ('17 July 1998', 'date'), ('17 June 2003', 'date'), ('1968', 'date_of_birth'), ('1997-12-9', 'date'), ('21 July 1998', 'date'), ('21 October and 9 November 1998', 'date'), ('26 April 2001', 'date'), ('28 September 1998', 'date'), ('5 years', 'sentence_duration'), ('51895/99', 'application_number'), ('6 April 1999', 'date'), ('Bogdan', 'first_name'), ('Chamber', 'legal_role'), ('Chełm', 'city'), ('Court', 'court_name'), ('December 1997', 'date'), ('Drzewicki', 'last_name'), ('European Commission of Human Rights', 'organization_name'), ('Jaczewska', 'last_name'), ('Kwiek', 'last_name'), ('Lublin', 'city'), ('Lublin Court of Appeal (Sąd Apelacyjny)', 'court_name'), ('Lublin Regional Court', 'court_name'), ('Lublin Regional Court (Sąd Wojewódzki)', 'court_name'), ('Lublin Regional Prosecutor', 'organization_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('Polish Governmen', 'organization_name'), ('Regional Court', 'court_name'), ('Regional Prosecutor', 'legal_role'), ('Republic of Poland', 'country'), ('beginning of December 1995', 'date'), ('counsel', 'legal_role'), ('defence counsel', 'legal_role'), ('prosecutor', 'legal_role')] raw=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 2002'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2008'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 May 1996'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 October 2002'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 June 2001'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '9 January 1997'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '4 February 2000'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '19 September 1999'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '30 August 2005'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '2003-04-17'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 2000'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '14 September and 22 October 2001'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '13 November 2003'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '6 December 2000'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '74231/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '18 May 2001'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Chamber', 'label': 'legal_role', 'synthetic': 'Panel'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Court', 'label': 'court_name', 'synthetic': 'Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 2001'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Commission on Human Rights'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Varga'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Szeged Court of Appeals (Bíróság)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Szeged District Tribunal'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Szeged District Tribunal (Bíróság)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': 'Szeged District Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Cooperation'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Governmen', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'District Tribunal'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'District Prosecutor'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'early January 2000'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'advocate'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigating magistrate'}] filtered=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 2002'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2008'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 May 1996'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 October 2002'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 June 2001'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '9 January 1997'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '4 February 2000'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '19 September 1999'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '30 August 2005'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '2003-04-17'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 2000'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '14 September and 22 October 2001'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '13 November 2003'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '6 December 2000'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '74231/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '18 May 2001'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Chamber', 'label': 'legal_role', 'synthetic': 'Panel'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Court', 'label': 'court_name', 'synthetic': 'Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 2001'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Commission on Human Rights'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Varga'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Szeged Court of Appeals (Bíróság)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Szeged District Tribunal'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Szeged District Tribunal (Bíróság)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': 'Szeged District Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Cooperation'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Governmen', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'District Tribunal'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'District Prosecutor'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'early January 2000'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'advocate'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigating magistrate'}]

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/replace/llm_replace_workflow.py:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([output_df, passthrough_rows], axis=0)
[15:54:06] [DEBUG] NDD workflow 'rewrite-pipeline' starting with 3 records

[15:54:06] [DEBUG] NDD workflow 'rewrite-pipeline': 12 columns ['_domain', '_domain_supplement', '_sensitivity_disposition', '_sensitivity_disposition_block', '_meaning_units', '_meaning_units_serialized', '_quality_qa', '_privacy_qa', '_rewrite_disposition_block', '_replacement_map_for_prompt', '_full_rewrite', '_rewritten_text']

[15:54:06] [INFO] 🧐 Preview generation in progress

[15:54:06] [INFO] ✅ Validation passed

[15:54:06] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:54:06] [INFO] 🩺 Running health checks for models...

[15:54:06] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:54:06] [INFO]   |-- ✅ Passed!

[15:54:06] [INFO] 🌱 Sampling 3 records from seed dataset

[15:54:06] [INFO]   |-- seed dataset size: 3 records

[15:54:06] [INFO]   |-- sampling strategy: ordered

[15:54:06] [INFO] 🗂️ llm-structured model config for column '_domain'

[15:54:06] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:54:06] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:54:06] [INFO]   |-- model provider: 'nvidia'

[15:54:06] [INFO]   |-- inference parameters:

[15:54:06] [INFO]   |  |-- generation_type=chat-completion

[15:54:06] [INFO]   |  |-- max_parallel_requests=2

[15:54:06] [INFO]   |  |-- timeout=300

[15:54:06] [INFO]   |  |-- temperature=0.30

[15:54:06] [INFO]   |  |-- top_p=0.95

[15:54:06] [INFO]   |  |-- max_tokens=16384

[15:54:06] [INFO] ⚡️ Processing llm-structured column '_domain' with 2 concurrent workers

[15:54:06] [INFO] ⏱️ llm-structured column '_domain' will report progress after each record

[15:54:07] [INFO]   |-- 🐣 llm-structured column '_domain' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.23 rec/s, eta 1.6s

[15:54:07] [INFO]   |-- 🐥 llm-structured column '_domain' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1.88 rec/s, eta 0.5s

[15:54:08] [INFO]   |-- 🐔 llm-structured column '_domain' progress: 3/3 (100%) complete, 3 ok, 0 failed, 2.10 rec/s, eta 0.0s

[15:54:08] [INFO] 🔧 Custom column config for column '_domain_supplement'

[15:54:08] [INFO]   |-- generator_function: '_enrich_domain'

[15:54:08] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:54:08] [INFO]   |-- required_columns: ['_domain']

[15:54:08] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers

[15:54:08] [INFO] ⏱️ custom column '_domain_supplement' will report progress after each record

[15:54:08] [INFO]   |-- 🌘 custom column '_domain_supplement' progress: 1/3 (33%) complete, 1 ok, 0 failed, 915.68 rec/s, eta 0.0s

[15:54:08] [INFO]   |-- 🌗 custom column '_domain_supplement' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1224.96 rec/s, eta 0.0s

[15:54:08] [INFO]   |-- 🌕 custom column '_domain_supplement' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1188.22 rec/s, eta 0.0s

[15:54:08] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'

[15:54:08] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:54:08] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:54:08] [INFO]   |-- model provider: 'nvidia'

[15:54:08] [INFO]   |-- inference parameters:

[15:54:08] [INFO]   |  |-- generation_type=chat-completion

[15:54:08] [INFO]   |  |-- max_parallel_requests=2

[15:54:08] [INFO]   |  |-- timeout=300

[15:54:08] [INFO]   |  |-- temperature=0.30

[15:54:08] [INFO]   |  |-- top_p=0.95

[15:54:08] [INFO]   |  |-- max_tokens=16384

[15:54:08] [INFO] ⚡️ Processing llm-structured column '_sensitivity_disposition' with 2 concurrent workers

[15:54:08] [INFO] ⏱️ llm-structured column '_sensitivity_disposition' will report progress after each record

[15:54:29] [INFO]   |-- 🐴 llm-structured column '_sensitivity_disposition' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.05 rec/s, eta 41.6s

[15:54:47] [INFO]   |-- 🚗 llm-structured column '_sensitivity_disposition' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.05 rec/s, eta 19.7s

[15:55:04] [INFO]   |-- 🚀 llm-structured column '_sensitivity_disposition' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.05 rec/s, eta 0.0s

[15:55:04] [INFO] 🔧 Custom column config for column '_sensitivity_disposition_block'

[15:55:04] [INFO]   |-- generator_function: '_format_disposition_block'

[15:55:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:55:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:55:04] [INFO] ⚡️ Processing custom column '_sensitivity_disposition_block' with 4 concurrent workers

[15:55:04] [INFO] ⏱️ custom column '_sensitivity_disposition_block' will report progress after each record

[15:55:04] [INFO]   |-- 🥱 custom column '_sensitivity_disposition_block' progress: 1/3 (33%) complete, 1 ok, 0 failed, 638.96 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 😐 custom column '_sensitivity_disposition_block' progress: 2/3 (67%) complete, 2 ok, 0 failed, 865.97 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 🤩 custom column '_sensitivity_disposition_block' progress: 3/3 (100%) complete, 3 ok, 0 failed, 899.97 rec/s, eta 0.0s

[15:55:04] [INFO] 🔧 Custom column config for column '_privacy_qa'

[15:55:04] [INFO]   |-- generator_function: '_generate_privacy_qa_column'

[15:55:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:55:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:55:04] [INFO] ⚡️ Processing custom column '_privacy_qa' with 4 concurrent workers

[15:55:04] [INFO] ⏱️ custom column '_privacy_qa' will report progress after each record

[15:55:04] [INFO]   |-- 😺 custom column '_privacy_qa' progress: 1/3 (33%) complete, 1 ok, 0 failed, 954.92 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 😸 custom column '_privacy_qa' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1156.57 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 🦁 custom column '_privacy_qa' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1130.16 rec/s, eta 0.0s

[15:55:04] [INFO] 🔧 Custom column config for column '_rewrite_disposition_block'

[15:55:04] [INFO]   |-- generator_function: '_format_rewrite_disposition_block'

[15:55:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:55:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[15:55:04] [INFO] ⚡️ Processing custom column '_rewrite_disposition_block' with 4 concurrent workers

[15:55:04] [INFO] ⏱️ custom column '_rewrite_disposition_block' will report progress after each record

[15:55:04] [INFO]   |-- 🐣 custom column '_rewrite_disposition_block' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1379.94 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 🐥 custom column '_rewrite_disposition_block' progress: 2/3 (67%) complete, 2 ok, 0 failed, 825.66 rec/s, eta 0.0s

[15:55:04] [INFO]   |-- 🐔 custom column '_rewrite_disposition_block' progress: 3/3 (100%) complete, 3 ok, 0 failed, 937.32 rec/s, eta 0.0s

[15:55:04] [INFO] 🗂️ llm-structured model config for column '_meaning_units'

[15:55:04] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:55:04] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:55:04] [INFO]   |-- model provider: 'nvidia'

[15:55:04] [INFO]   |-- inference parameters:

[15:55:04] [INFO]   |  |-- generation_type=chat-completion

[15:55:04] [INFO]   |  |-- max_parallel_requests=2

[15:55:04] [INFO]   |  |-- timeout=300

[15:55:04] [INFO]   |  |-- temperature=0.30

[15:55:04] [INFO]   |  |-- top_p=0.95

[15:55:04] [INFO]   |  |-- max_tokens=16384

[15:55:04] [INFO] ⚡️ Processing llm-structured column '_meaning_units' with 2 concurrent workers

[15:55:04] [INFO] ⏱️ llm-structured column '_meaning_units' will report progress after each record

[15:55:14] [INFO]   |-- 😺 llm-structured column '_meaning_units' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.10 rec/s, eta 19.9s

[15:55:14] [INFO]   |-- 😸 llm-structured column '_meaning_units' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.19 rec/s, eta 5.3s

[15:55:26] [INFO]   |-- 🦁 llm-structured column '_meaning_units' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.14 rec/s, eta 0.0s

[15:55:26] [INFO] 🔧 Custom column config for column '_replacement_map_for_prompt'

[15:55:26] [INFO]   |-- generator_function: '_filter_replacement_map_for_prompt'

[15:55:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:55:26] [INFO]   |-- required_columns: ['_replacement_map', '_rewrite_disposition_block']

[15:55:26] [INFO] ⚡️ Processing custom column '_replacement_map_for_prompt' with 4 concurrent workers

[15:55:26] [INFO] ⏱️ custom column '_replacement_map_for_prompt' will report progress after each record

[15:55:26] [INFO]   |-- 🐴 custom column '_replacement_map_for_prompt' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1199.40 rec/s, eta 0.0s

[15:55:26] [INFO]   |-- 🚗 custom column '_replacement_map_for_prompt' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1384.08 rec/s, eta 0.0s

[15:55:26] [INFO]   |-- 🚀 custom column '_replacement_map_for_prompt' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1292.04 rec/s, eta 0.0s

[15:55:26] [INFO] 🔧 Custom column config for column '_meaning_units_serialized'

[15:55:26] [INFO]   |-- generator_function: '_serialize_meaning_units'

[15:55:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:55:26] [INFO]   |-- required_columns: ['_meaning_units']

[15:55:26] [INFO] ⚡️ Processing custom column '_meaning_units_serialized' with 4 concurrent workers

[15:55:26] [INFO] ⏱️ custom column '_meaning_units_serialized' will report progress after each record

[15:55:26] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1221.37 rec/s, eta 0.0s

[15:55:26] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1449.41 rec/s, eta 0.0s

[15:55:26] [INFO]   |-- 🐔 custom column '_meaning_units_serialized' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1250.39 rec/s, eta 0.0s

[15:55:26] [INFO] 🗂️ llm-structured model config for column '_full_rewrite'

[15:55:26] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:55:26] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:55:26] [INFO]   |-- model provider: 'nvidia'

[15:55:26] [INFO]   |-- inference parameters:

[15:55:26] [INFO]   |  |-- generation_type=chat-completion

[15:55:26] [INFO]   |  |-- max_parallel_requests=2

[15:55:26] [INFO]   |  |-- timeout=300

[15:55:26] [INFO]   |  |-- temperature=0.30

[15:55:26] [INFO]   |  |-- top_p=0.95

[15:55:26] [INFO]   |  |-- max_tokens=16384

[15:55:26] [INFO] ⚡️ Processing llm-structured column '_full_rewrite' with 2 concurrent workers

[15:55:26] [INFO] ⏱️ llm-structured column '_full_rewrite' will report progress after each record

[15:55:38] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 25.0s

[15:55:39] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 6.6s

[15:55:58] [INFO]   |-- ☀️ llm-structured column '_full_rewrite' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.09 rec/s, eta 0.0s

[15:55:58] [INFO] 🗂️ llm-structured model config for column '_quality_qa'

[15:55:58] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:55:58] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:55:58] [INFO]   |-- model provider: 'nvidia'

[15:55:58] [INFO]   |-- inference parameters:

[15:55:58] [INFO]   |  |-- generation_type=chat-completion

[15:55:58] [INFO]   |  |-- max_parallel_requests=2

[15:55:58] [INFO]   |  |-- timeout=300

[15:55:58] [INFO]   |  |-- temperature=0.30

[15:55:58] [INFO]   |  |-- top_p=0.95

[15:55:58] [INFO]   |  |-- max_tokens=16384

[15:55:58] [INFO] ⚡️ Processing llm-structured column '_quality_qa' with 2 concurrent workers

[15:55:58] [INFO] ⏱️ llm-structured column '_quality_qa' will report progress after each record

[15:56:06] [INFO]   |-- 🌘 llm-structured column '_quality_qa' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.12 rec/s, eta 16.8s

[15:56:07] [INFO]   |-- 🌗 llm-structured column '_quality_qa' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 4.4s

[15:56:15] [INFO]   |-- 🌕 llm-structured column '_quality_qa' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.17 rec/s, eta 0.0s

[15:56:15] [INFO] 🔧 Custom column config for column '_rewritten_text'

[15:56:15] [INFO]   |-- generator_function: '_extract_rewritten_text'

[15:56:15] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:15] [INFO]   |-- required_columns: ['_full_rewrite']

[15:56:15] [INFO] ⚡️ Processing custom column '_rewritten_text' with 4 concurrent workers

[15:56:15] [INFO] ⏱️ custom column '_rewritten_text' will report progress after each record

[15:56:15] [INFO]   |-- 😺 custom column '_rewritten_text' progress: 1/3 (33%) complete, 1 ok, 0 failed, 817.83 rec/s, eta 0.0s

[15:56:15] [INFO]   |-- 😸 custom column '_rewritten_text' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1075.63 rec/s, eta 0.0s

[15:56:15] [INFO]   |-- 🦁 custom column '_rewritten_text' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1133.86 rec/s, eta 0.0s

[15:56:16] [INFO] 📊 Model usage summary:

[15:56:16] [INFO]   |-- model: openai/gpt-oss-120b

[15:56:16] [INFO]   |-- tokens: input=43737, output=41268, total=85005, tps=657

[15:56:16] [INFO]   |-- requests: success=15, failed=0, total=15, rpm=6

[15:56:16] [INFO] 📐 Measuring dataset column statistics:

[15:56:16] [INFO]   |-- 🗂️ column: '_domain'

[15:56:16] [INFO]   |-- 🔧 column: '_domain_supplement'

[15:56:16] [INFO]   |-- 🗂️ column: '_sensitivity_disposition'

[15:56:16] [INFO]   |-- 🔧 column: '_sensitivity_disposition_block'

[15:56:16] [INFO]   |-- 🗂️ column: '_meaning_units'

[15:56:16] [INFO]   |-- 🔧 column: '_meaning_units_serialized'

[15:56:16] [INFO]   |-- 🗂️ column: '_quality_qa'

[15:56:16] [INFO]   |-- 🔧 column: '_privacy_qa'

[15:56:16] [INFO]   |-- 🔧 column: '_rewrite_disposition_block'

[15:56:16] [INFO]   |-- 🔧 column: '_replacement_map_for_prompt'

[15:56:16] [INFO]   |-- 🗂️ column: '_full_rewrite'

[15:56:16] [INFO]   |-- 🔧 column: '_rewritten_text'

[15:56:16] [INFO] ☀️ Preview complete!

[15:56:16] [DEBUG] NDD workflow 'rewrite-pipeline' returned 3 records

[15:56:16] [DEBUG] NDD workflow 'rewrite-evaluate-0' starting with 3 records

[15:56:16] [DEBUG] NDD workflow 'rewrite-evaluate-0': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:56:16] [INFO] 🕵️ Preview generation in progress

[15:56:16] [INFO] ✅ Validation passed

[15:56:16] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:56:16] [INFO] 🩺 Running health checks for models...

[15:56:16] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:56:17] [INFO]   |-- ✅ Passed!

[15:56:17] [INFO] 🌱 Sampling 3 records from seed dataset

[15:56:17] [INFO]   |-- seed dataset size: 3 records

[15:56:17] [INFO]   |-- sampling strategy: ordered

[15:56:17] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:56:17] [INFO]   |-- generator_function: '_quality_reanswer'

[15:56:17] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:17] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:56:17] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:56:17] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:56:17] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:56:24] [INFO]   |-- 🌦️ custom column '_quality_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.13 rec/s, eta 15.8s

[15:56:25] [INFO]   |-- ⛅ custom column '_quality_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.25 rec/s, eta 4.1s

[15:56:25] [INFO]   |-- ☀️ custom column '_quality_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.35 rec/s, eta 0.0s

[15:56:25] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:56:25] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:56:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:25] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:56:25] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:56:25] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:56:25] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:56:33] [INFO]   |-- 🌘 custom column '_privacy_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.13 rec/s, eta 15.6s

[15:56:33] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.26 rec/s, eta 3.9s

[15:56:33] [INFO]   |-- 🌕 custom column '_privacy_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.36 rec/s, eta 0.0s

[15:56:33] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:56:33] [INFO]   |-- generator_function: '_quality_compare'

[15:56:33] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:33] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:56:33] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:56:33] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:56:33] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:56:42] [INFO]   |-- 🌦️ custom column '_quality_qa_compare' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.11 rec/s, eta 17.9s

[15:56:43] [INFO]   |-- ⛅ custom column '_quality_qa_compare' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 4.7s

[15:56:48] [INFO]   |-- ☀️ custom column '_quality_qa_compare' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.21 rec/s, eta 0.0s

[15:56:48] [INFO] 🔧 Custom column config for column 'utility_score'

[15:56:48] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:56:48] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:48] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:56:48] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:56:48] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:56:48] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:56:48] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:56:48] [INFO]   |-- 😺 custom column 'utility_score' progress: 1/3 (33%) complete, 1 ok, 0 failed, 550.12 rec/s, eta 0.0s

[15:56:48] [INFO]   |-- 😸 custom column 'utility_score' progress: 2/3 (67%) complete, 2 ok, 0 failed, 799.89 rec/s, eta 0.0s

[15:56:48] [INFO]   |-- 🦁 custom column 'utility_score' progress: 3/3 (100%) complete, 3 ok, 0 failed, 827.59 rec/s, eta 0.0s

[15:56:48] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:56:48] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:56:48] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:48] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:56:48] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:56:48] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:56:48] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:56:48] [INFO]   |-- 🐴 custom column '_needs_repair' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1217.90 rec/s, eta 0.0s

[15:56:48] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1622.88 rec/s, eta 0.0s

[15:56:48] [INFO]   |-- 🚀 custom column '_needs_repair' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1609.80 rec/s, eta 0.0s

[15:56:48] [INFO] 📊 Model usage summary:

[15:56:48] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:56:48] [INFO]   |-- tokens: input=17792, output=21060, total=38852, tps=1231

[15:56:48] [INFO]   |-- requests: success=9, failed=0, total=9, rpm=17

[15:56:48] [INFO] 📐 Measuring dataset column statistics:

[15:56:48] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:56:48] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:56:48] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:56:48] [INFO]   |-- 🔧 column: 'utility_score'

[15:56:48] [INFO]   |-- 🔧 column: '_needs_repair'

[15:56:48] [INFO] ☀️ Preview complete!

[15:56:48] [DEBUG] NDD workflow 'rewrite-evaluate-0' returned 3 records

[15:56:48] [INFO] Evaluate-repair loop iteration 0: 3/3 rows need repair

[15:56:48] [DEBUG] NDD workflow 'rewrite-repair-0' starting with 3 records

[15:56:48] [DEBUG] NDD workflow 'rewrite-repair-0': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:56:48] [INFO] 📸 Preview generation in progress

[15:56:48] [INFO] ✅ Validation passed

[15:56:48] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:56:48] [INFO] 🩺 Running health checks for models...

[15:56:48] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:56:49] [INFO]   |-- ✅ Passed!

[15:56:49] [INFO] 🌱 Sampling 3 records from seed dataset

[15:56:49] [INFO]   |-- seed dataset size: 3 records

[15:56:49] [INFO]   |-- sampling strategy: ordered

[15:56:49] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:56:49] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:56:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:49] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:56:49] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:56:49] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:56:49] [INFO]   |-- 😺 custom column '_leaked_privacy_items' progress: 1/3 (33%) complete, 1 ok, 0 failed, 962.35 rec/s, eta 0.0s

[15:56:49] [INFO]   |-- 😸 custom column '_leaked_privacy_items' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1189.12 rec/s, eta 0.0s

[15:56:49] [INFO]   |-- 🦁 custom column '_leaked_privacy_items' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1221.48 rec/s, eta 0.0s

[15:56:49] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:56:49] [INFO]   |-- generator_function: '_repair_column'

[15:56:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:56:49] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:56:49] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:56:49] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:56:49] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:56:49] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:56:57] [INFO]   |-- 🌦️ custom column '_rewritten_text__next' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.12 rec/s, eta 17.3s

[15:56:58] [INFO]   |-- ⛅ custom column '_rewritten_text__next' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.22 rec/s, eta 4.5s

[15:57:02] [INFO]   |-- ☀️ custom column '_rewritten_text__next' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.22 rec/s, eta 0.0s

[15:57:02] [INFO] 📊 Model usage summary:

[15:57:02] [INFO]   |-- model: openai/gpt-oss-120b

[15:57:02] [INFO]   |-- tokens: input=9107, output=6525, total=15632, tps=1142

[15:57:02] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=13

[15:57:02] [INFO] 📐 Measuring dataset column statistics:

[15:57:02] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:57:02] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:57:02] [INFO] ✅ Preview complete!

[15:57:02] [DEBUG] NDD workflow 'rewrite-repair-0' returned 3 records

[15:57:02] [DEBUG] NDD workflow 'rewrite-evaluate-1' starting with 3 records

[15:57:02] [DEBUG] NDD workflow 'rewrite-evaluate-1': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:57:02] [INFO] 🎥 Preview generation in progress

[15:57:02] [INFO] ✅ Validation passed

[15:57:02] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:57:02] [INFO] 🩺 Running health checks for models...

[15:57:02] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:57:04] [INFO]   |-- ✅ Passed!

[15:57:04] [INFO] 🌱 Sampling 3 records from seed dataset

[15:57:04] [INFO]   |-- seed dataset size: 3 records

[15:57:04] [INFO]   |-- sampling strategy: ordered

[15:57:04] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:57:04] [INFO]   |-- generator_function: '_quality_reanswer'

[15:57:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:04] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:57:04] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:57:04] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:57:04] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:57:11] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.15 rec/s, eta 13.6s

[15:57:11] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.28 rec/s, eta 3.6s

[15:57:19] [INFO]   |-- 🌕 custom column '_quality_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.20 rec/s, eta 0.0s

[15:57:19] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:57:19] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:57:19] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:19] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:57:19] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:57:19] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:57:19] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:57:22] [INFO]   |-- 🐴 custom column '_privacy_qa_reanswer' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.29 rec/s, eta 7.0s

[15:57:26] [INFO]   |-- 🚗 custom column '_privacy_qa_reanswer' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.27 rec/s, eta 3.7s

[15:57:27] [INFO]   |-- 🚀 custom column '_privacy_qa_reanswer' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.36 rec/s, eta 0.0s

[15:57:27] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:57:27] [INFO]   |-- generator_function: '_quality_compare'

[15:57:27] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:27] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:57:27] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:57:27] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:57:27] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:57:35] [INFO]   |-- 🥱 custom column '_quality_qa_compare' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.12 rec/s, eta 16.6s

[15:57:38] [INFO]   |-- 😐 custom column '_quality_qa_compare' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.19 rec/s, eta 5.3s

[15:57:40] [INFO]   |-- 🤩 custom column '_quality_qa_compare' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.23 rec/s, eta 0.0s

[15:57:40] [INFO] 🔧 Custom column config for column 'utility_score'

[15:57:40] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:57:40] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:40] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:57:40] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:57:40] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:57:40] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:57:40] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:57:40] [INFO]   |-- 🐴 custom column 'utility_score' progress: 1/3 (33%) complete, 1 ok, 0 failed, 666.46 rec/s, eta 0.0s

[15:57:40] [INFO]   |-- 🚗 custom column 'utility_score' progress: 2/3 (67%) complete, 2 ok, 0 failed, 805.46 rec/s, eta 0.0s

[15:57:40] [INFO]   |-- 🚀 custom column 'utility_score' progress: 3/3 (100%) complete, 3 ok, 0 failed, 820.20 rec/s, eta 0.0s

[15:57:40] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:57:40] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:57:40] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:40] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:57:40] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:57:40] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:57:40] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:57:40] [INFO]   |-- 🌘 custom column '_needs_repair' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1250.59 rec/s, eta 0.0s

[15:57:40] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1665.74 rec/s, eta 0.0s

[15:57:40] [INFO]   |-- 🌕 custom column '_needs_repair' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1608.69 rec/s, eta 0.0s

[15:57:40] [INFO] 📊 Model usage summary:

[15:57:40] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:57:40] [INFO]   |-- tokens: input=17737, output=18367, total=36104, tps=982

[15:57:40] [INFO]   |-- requests: success=9, failed=0, total=9, rpm=14

[15:57:40] [INFO] 📐 Measuring dataset column statistics:

[15:57:40] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:57:40] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:57:40] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:57:40] [INFO]   |-- 🔧 column: 'utility_score'

[15:57:40] [INFO]   |-- 🔧 column: '_needs_repair'

[15:57:40] [INFO] 🏆 Preview complete!

[15:57:40] [DEBUG] NDD workflow 'rewrite-evaluate-1' returned 3 records

[15:57:40] [INFO] Evaluate-repair loop iteration 1: 1/3 rows need repair

[15:57:40] [DEBUG] NDD workflow 'rewrite-repair-1' starting with 1 records

[15:57:40] [DEBUG] NDD workflow 'rewrite-repair-1': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:57:40] [INFO] 🔭 Preview generation in progress

[15:57:41] [INFO] ✅ Validation passed

[15:57:41] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:57:41] [INFO] 🩺 Running health checks for models...

[15:57:41] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:57:41] [INFO]   |-- ✅ Passed!

[15:57:41] [INFO] 🌱 Sampling 1 records from seed dataset

[15:57:41] [INFO]   |-- seed dataset size: 1 records

[15:57:41] [INFO]   |-- sampling strategy: ordered

[15:57:41] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:57:41] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:57:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:41] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:57:41] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:57:41] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:57:41] [INFO]   |-- 🚀 custom column '_leaked_privacy_items' progress: 1/1 (100%) complete, 1 ok, 0 failed, 917.68 rec/s, eta 0.0s

[15:57:41] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:57:41] [INFO]   |-- generator_function: '_repair_column'

[15:57:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:41] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:57:41] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:57:41] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:57:41] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:57:41] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:57:54] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 0.0s

[15:57:54] [INFO] 📊 Model usage summary:

[15:57:54] [INFO]   |-- model: openai/gpt-oss-120b

[15:57:54] [INFO]   |-- tokens: input=3497, output=2840, total=6337, tps=482

[15:57:54] [INFO]   |-- requests: success=1, failed=0, total=1, rpm=4

[15:57:54] [INFO] 📐 Measuring dataset column statistics:

[15:57:54] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:57:54] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:57:54] [INFO] 🏆 Preview complete!

[15:57:54] [DEBUG] NDD workflow 'rewrite-repair-1' returned 1 records

[15:57:54] [DEBUG] NDD workflow 'rewrite-evaluate-2' starting with 1 records

[15:57:54] [DEBUG] NDD workflow 'rewrite-evaluate-2': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:57:54] [INFO] 🎥 Preview generation in progress

[15:57:54] [INFO] ✅ Validation passed

[15:57:54] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:57:54] [INFO] 🩺 Running health checks for models...

[15:57:54] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:57:55] [INFO]   |-- ✅ Passed!

[15:57:56] [INFO] 🌱 Sampling 1 records from seed dataset

[15:57:56] [INFO]   |-- seed dataset size: 1 records

[15:57:56] [INFO]   |-- sampling strategy: ordered

[15:57:56] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:57:56] [INFO]   |-- generator_function: '_quality_reanswer'

[15:57:56] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:57:56] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:57:56] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:57:56] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:57:56] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:58:02] [INFO]   |-- 🚀 custom column '_quality_qa_reanswer' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.15 rec/s, eta 0.0s

[15:58:02] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:58:02] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:58:02] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:02] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:58:02] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:58:02] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:58:02] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:58:12] [INFO]   |-- 🚀 custom column '_privacy_qa_reanswer' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.11 rec/s, eta 0.0s

[15:58:12] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:58:12] [INFO]   |-- generator_function: '_quality_compare'

[15:58:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:12] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:58:12] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:58:12] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:58:12] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:58:25] [INFO]   |-- 🦁 custom column '_quality_qa_compare' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.07 rec/s, eta 0.0s

[15:58:25] [INFO] 🔧 Custom column config for column 'utility_score'

[15:58:25] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:58:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:25] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:58:25] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:58:25] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:58:25] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:58:25] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:58:25] [INFO]   |-- 🚀 custom column 'utility_score' progress: 1/1 (100%) complete, 1 ok, 0 failed, 706.42 rec/s, eta 0.0s

[15:58:25] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:58:25] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:58:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:25] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:58:25] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:58:25] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:58:25] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:58:25] [INFO]   |-- 🐔 custom column '_needs_repair' progress: 1/1 (100%) complete, 1 ok, 0 failed, 1148.82 rec/s, eta 0.0s

[15:58:25] [INFO] 📊 Model usage summary:

[15:58:25] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:58:25] [INFO]   |-- tokens: input=6220, output=7449, total=13669, tps=456

[15:58:25] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=6

[15:58:25] [INFO] 📐 Measuring dataset column statistics:

[15:58:25] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:58:25] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:58:25] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:58:25] [INFO]   |-- 🔧 column: 'utility_score'

[15:58:25] [INFO]   |-- 🔧 column: '_needs_repair'

[15:58:25] [INFO] 🍾 Preview complete!

[15:58:26] [DEBUG] NDD workflow 'rewrite-evaluate-2' returned 1 records

[15:58:26] [INFO] Evaluate-repair loop iteration 2: 1/3 rows need repair

[15:58:26] [DEBUG] NDD workflow 'rewrite-repair-2' starting with 1 records

[15:58:26] [DEBUG] NDD workflow 'rewrite-repair-2': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[15:58:26] [INFO] 👁️ Preview generation in progress

[15:58:26] [INFO] ✅ Validation passed

[15:58:26] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:58:26] [INFO] 🩺 Running health checks for models...

[15:58:26] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:58:26] [INFO]   |-- ✅ Passed!

[15:58:26] [INFO] 🌱 Sampling 1 records from seed dataset

[15:58:26] [INFO]   |-- seed dataset size: 1 records

[15:58:26] [INFO]   |-- sampling strategy: ordered

[15:58:26] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[15:58:26] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[15:58:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:26] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[15:58:26] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[15:58:26] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[15:58:26] [INFO]   |-- 🌕 custom column '_leaked_privacy_items' progress: 1/1 (100%) complete, 1 ok, 0 failed, 855.89 rec/s, eta 0.0s

[15:58:26] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[15:58:26] [INFO]   |-- generator_function: '_repair_column'

[15:58:26] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:26] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[15:58:26] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[15:58:26] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[15:58:26] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[15:58:26] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[15:58:39] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 0.0s

[15:58:39] [INFO] 📊 Model usage summary:

[15:58:39] [INFO]   |-- model: openai/gpt-oss-120b

[15:58:39] [INFO]   |-- tokens: input=3469, output=2362, total=5831, tps=433

[15:58:39] [INFO]   |-- requests: success=1, failed=0, total=1, rpm=4

[15:58:39] [INFO] 📐 Measuring dataset column statistics:

[15:58:39] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[15:58:39] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[15:58:39] [INFO] 🥳 Preview complete!

[15:58:39] [DEBUG] NDD workflow 'rewrite-repair-2' returned 1 records

[15:58:39] [DEBUG] NDD workflow 'rewrite-evaluate-3' starting with 1 records

[15:58:39] [DEBUG] NDD workflow 'rewrite-evaluate-3': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[15:58:39] [INFO] 🕵️ Preview generation in progress

[15:58:39] [INFO] ✅ Validation passed

[15:58:39] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:58:39] [INFO] 🩺 Running health checks for models...

[15:58:39] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:58:41] [INFO]   |-- ✅ Passed!

[15:58:41] [INFO] 🌱 Sampling 1 records from seed dataset

[15:58:41] [INFO]   |-- seed dataset size: 1 records

[15:58:41] [INFO]   |-- sampling strategy: ordered

[15:58:41] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[15:58:41] [INFO]   |-- generator_function: '_quality_reanswer'

[15:58:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:41] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[15:58:41] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:58:41] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[15:58:41] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[15:58:47] [INFO]   |-- 🦁 custom column '_quality_qa_reanswer' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.17 rec/s, eta 0.0s

[15:58:47] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[15:58:47] [INFO]   |-- generator_function: '_privacy_reanswer'

[15:58:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:58:47] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[15:58:47] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:58:47] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[15:58:47] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[15:59:03] [INFO]   |-- 🦁 custom column '_privacy_qa_reanswer' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.06 rec/s, eta 0.0s

[15:59:03] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[15:59:03] [INFO]   |-- generator_function: '_quality_compare'

[15:59:03] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:03] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[15:59:03] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[15:59:03] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[15:59:03] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[15:59:14] [INFO]   |-- 🦁 custom column '_quality_qa_compare' progress: 1/1 (100%) complete, 1 ok, 0 failed, 0.10 rec/s, eta 0.0s

[15:59:14] [INFO] 🔧 Custom column config for column 'utility_score'

[15:59:14] [INFO]   |-- generator_function: '_compute_metrics_columns'

[15:59:14] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:14] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[15:59:14] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[15:59:14] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[15:59:14] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[15:59:14] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[15:59:14] [INFO]   |-- 🐔 custom column 'utility_score' progress: 1/1 (100%) complete, 1 ok, 0 failed, 552.40 rec/s, eta 0.0s

[15:59:14] [INFO] 🔧 Custom column config for column '_needs_repair'

[15:59:14] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[15:59:14] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:14] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[15:59:14] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[15:59:14] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[15:59:14] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[15:59:14] [INFO]   |-- 🐔 custom column '_needs_repair' progress: 1/1 (100%) complete, 1 ok, 0 failed, 1002.84 rec/s, eta 0.0s

[15:59:14] [INFO] 📊 Model usage summary:

[15:59:14] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:59:14] [INFO]   |-- tokens: input=6225, output=7607, total=13832, tps=424

[15:59:14] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=5

[15:59:14] [INFO] 📐 Measuring dataset column statistics:

[15:59:14] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[15:59:14] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[15:59:14] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[15:59:14] [INFO]   |-- 🔧 column: 'utility_score'

[15:59:14] [INFO]   |-- 🔧 column: '_needs_repair'

[15:59:14] [INFO] 🥳 Preview complete!

[15:59:14] [DEBUG] NDD workflow 'rewrite-evaluate-3' returned 1 records

[15:59:14] [DEBUG] NDD workflow 'rewrite-final-judge' starting with 3 records

[15:59:14] [DEBUG] NDD workflow 'rewrite-final-judge': 2 columns ['_judge_evaluation', 'needs_human_review']

[15:59:14] [INFO] 👀 Preview generation in progress

[15:59:14] [INFO] ✅ Validation passed

[15:59:14] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:59:14] [INFO] 🩺 Running health checks for models...

[15:59:14] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[15:59:14] [INFO]   |-- ✅ Passed!

[15:59:14] [INFO] 🌱 Sampling 3 records from seed dataset

[15:59:14] [INFO]   |-- seed dataset size: 3 records

[15:59:14] [INFO]   |-- sampling strategy: ordered

[15:59:14] [INFO] ⚖️ llm-judge model config for column '_judge_evaluation'

[15:59:14] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[15:59:14] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[15:59:14] [INFO]   |-- model provider: 'nvidia'

[15:59:14] [INFO]   |-- inference parameters:

[15:59:14] [INFO]   |  |-- generation_type=chat-completion

[15:59:14] [INFO]   |  |-- max_parallel_requests=16

[15:59:14] [INFO]   |  |-- timeout=300

[15:59:14] [INFO]   |  |-- temperature=0.40

[15:59:14] [INFO]   |  |-- top_p=1.00

[15:59:14] [INFO]   |  |-- max_tokens=8192

[15:59:14] [INFO] ⚡️ Processing llm-judge column '_judge_evaluation' with 16 concurrent workers

[15:59:14] [INFO] ⏱️ llm-judge column '_judge_evaluation' will report progress after each record

[15:59:20] [INFO]   |-- 🌘 llm-judge column '_judge_evaluation' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.19 rec/s, eta 10.6s

[15:59:20] [INFO]   |-- 🌗 llm-judge column '_judge_evaluation' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.34 rec/s, eta 2.9s

[15:59:24] [INFO]   |-- 🌕 llm-judge column '_judge_evaluation' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.30 rec/s, eta 0.0s

[15:59:24] [INFO] 🔧 Custom column config for column 'needs_human_review'

[15:59:24] [INFO]   |-- generator_function: '_determine_needs_human_review'

[15:59:24] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:24] [INFO]   |-- required_columns: ['_rewritten_text', 'utility_score', 'leakage_mass', 'any_high_leaked']

[15:59:24] [INFO]   |-- generator_params: flag_utility_below=0.5 flag_leakage_mass_above=2.0

[15:59:24] [INFO] ⚡️ Processing custom column 'needs_human_review' with 4 concurrent workers

[15:59:24] [INFO] ⏱️ custom column 'needs_human_review' will report progress after each record

[15:59:24] [INFO]   |-- 🥱 custom column 'needs_human_review' progress: 1/3 (33%) complete, 1 ok, 0 failed, 896.09 rec/s, eta 0.0s

[15:59:24] [INFO]   |-- 😐 custom column 'needs_human_review' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1045.68 rec/s, eta 0.0s

[15:59:24] [INFO]   |-- 🤩 custom column 'needs_human_review' progress: 3/3 (100%) complete, 3 ok, 0 failed, 951.75 rec/s, eta 0.0s

[15:59:25] [INFO] 📊 Model usage summary:

[15:59:25] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[15:59:25] [INFO]   |-- tokens: input=8397, output=5287, total=13684, tps=1312

[15:59:25] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=17

[15:59:25] [INFO] 📐 Measuring dataset column statistics:

[15:59:25] [INFO]   |-- ⚖️ column: '_judge_evaluation'

[15:59:25] [INFO]   |-- 🔧 column: 'needs_human_review'

[15:59:25] [INFO] 🎉 Preview complete!

[15:59:25] [DEBUG] NDD workflow 'rewrite-final-judge' returned 3 records

[15:59:25] [INFO]   |-- 📋 Rewrite complete (0 failed) [349.0s]

[15:59:25] [INFO] 🎉 Pipeline complete — 3 records processed, 0 total failures

In [5]:
preview.display_record(1)

## Inspect the results

In [6]:
result = anonymizer.run(config=config, data=input_data)

print(result)
result.dataframe.head()

[15:59:25] [INFO] 📂 Loaded 25 records from ../data/TAB_legal_sample25.csv (column: 'text')

[15:59:25] [DEBUG] input text lengths: min=2312, max=4758, mean=3458 chars (25 records)

[15:59:25] [DEBUG] detection config: threshold=0.30, labels=['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id']

[15:59:25] [INFO] 🔍 Running entity detection on 25 records

[15:59:25] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[15:59:25] [DEBUG] NDD workflow 'entity-detection' starting with 25 records

[15:59:25] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']

[15:59:25] [INFO] 🎨 Creating Data Designer dataset

[15:59:25] [INFO] ✅ Validation passed

[15:59:25] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[15:59:25] [INFO] 🩺 Running health checks for models...

[15:59:25] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[15:59:26] [INFO]   |-- ✅ Passed!

[15:59:26] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...

[15:59:27] [INFO]   |-- ✅ Passed!

[15:59:27] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-31-2026_155927' instead.

[15:59:27] [INFO] ⏳ Processing batch 1 of 1

[15:59:27] [INFO] 🌱 Sampling 25 records from seed dataset

[15:59:27] [INFO]   |-- seed dataset size: 25 records

[15:59:27] [INFO]   |-- sampling strategy: ordered

[15:59:27] [INFO] 📝 llm-text model config for column '_raw_detected_entities'

[15:59:27] [INFO]   |-- model: 'nvidia/gliner-pii'

[15:59:27] [INFO]   |-- model alias: 'gliner-pii-detector'

[15:59:27] [INFO]   |-- model provider: 'nvidia'

[15:59:27] [INFO]   |-- inference parameters:

[15:59:27] [INFO]   |  |-- generation_type=chat-completion

[15:59:27] [INFO]   |  |-- max_parallel_requests=4

[15:59:27] [INFO]   |  |-- timeout=120

[15:59:27] [INFO]   |  |-- extra_body={'labels': ['age', 'application_number', 'case_number', 'city', 'company_name', 'country', 'court_name', 'date', 'date_of_birth', 'date_time', 'email', 'first_name', 'last_name', 'legal_role', 'monetary_amount', 'nationality', 'organization_name', 'phone_number', 'prison_detention_facility', 'sentence_duration', 'ssn', 'state', 'street_address', 'time', 'unique_id'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}

[15:59:27] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 4 concurrent workers

[15:59:27] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress every 2 records

[15:59:29] [INFO]   |-- 🚶 llm-text column '_raw_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1.01 rec/s, eta 22.8s

[15:59:29] [INFO]   |-- 🚶 llm-text column '_raw_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1.75 rec/s, eta 12.0s

[15:59:29] [INFO]   |-- 🚶 llm-text column '_raw_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2.42 rec/s, eta 7.9s

[15:59:30] [INFO]   |-- 🐴 llm-text column '_raw_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2.67 rec/s, eta 6.4s

[15:59:31] [INFO]   |-- 🐴 llm-text column '_raw_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2.34 rec/s, eta 6.4s

[15:59:33] [INFO]   |-- 🐴 llm-text column '_raw_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1.97 rec/s, eta 6.6s

[15:59:35] [INFO]   |-- 🚗 llm-text column '_raw_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1.69 rec/s, eta 6.5s

[15:59:36] [INFO]   |-- 🚗 llm-text column '_raw_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1.70 rec/s, eta 5.3s

[15:59:37] [INFO]   |-- 🚗 llm-text column '_raw_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1.72 rec/s, eta 4.1s

[15:59:39] [INFO]   |-- ✈️ llm-text column '_raw_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 1.64 rec/s, eta 3.1s

[15:59:41] [INFO]   |-- ✈️ llm-text column '_raw_detected_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 1.55 rec/s, eta 1.9s

[15:59:43] [INFO]   |-- ✈️ llm-text column '_raw_detected_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 1.45 rec/s, eta 0.7s

[15:59:47] [WARNING] ⚠️ Generation for record at index 9 failed. Will omit this record from the dataset.
  |----------
  | Cause: You have exceeded the rate limit for model 'nvidia/gliner-pii' while running generation for column '_raw_detected_entities'.
  | Solution: Wait and try again in a few moments.
  |----------

[15:59:47] [INFO]   |-- 🚀 llm-text column '_raw_detected_entities' progress: 25/25 (100%) complete, 24 ok, 1 failed, 1.22 rec/s, eta 0.0s

[15:59:47] [INFO] 🔧 Custom column config for column '_seed_entities'

[15:59:47] [INFO]   |-- generator_function: 'parse_detected_entities'

[15:59:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:47] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']

[15:59:47] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']

[15:59:47] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers

[15:59:47] [INFO] ⏱️ custom column '_seed_entities' will report progress every 2 records

[15:59:47] [INFO]   |-- 🥚 custom column '_seed_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 643.60 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🥚 custom column '_seed_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 609.46 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🥚 custom column '_seed_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 685.47 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐣 custom column '_seed_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 727.18 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐣 custom column '_seed_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 758.07 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐣 custom column '_seed_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 794.72 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐥 custom column '_seed_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 766.35 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐥 custom column '_seed_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 797.18 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐥 custom column '_seed_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 814.89 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐤 custom column '_seed_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 838.47 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐤 custom column '_seed_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 888.43 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐤 custom column '_seed_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 929.75 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐤 custom column '_seed_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 917.56 rec/s, eta 0.0s

[15:59:47] [INFO] 🔧 Custom column config for column '_validation_candidates'

[15:59:47] [INFO]   |-- generator_function: 'prepare_validation_inputs'

[15:59:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:47] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']

[15:59:47] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[15:59:47] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers

[15:59:47] [INFO] ⏱️ custom column '_validation_candidates' will report progress every 2 records

[15:59:47] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1847.79 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1986.22 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2173.13 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2239.54 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2021.12 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2066.81 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2156.57 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2283.69 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2284.72 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2275.36 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2306.59 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2446.28 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2369.37 rec/s, eta 0.0s

[15:59:47] [INFO] 🔧 Custom column config for column '_validation_skeleton'

[15:59:47] [INFO]   |-- generator_function: 'build_validation_skeleton'

[15:59:47] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[15:59:47] [INFO]   |-- required_columns: ['_validation_candidates']

[15:59:47] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers

[15:59:47] [INFO] ⏱️ custom column '_validation_skeleton' will report progress every 2 records

[15:59:47] [INFO]   |-- 🚶 custom column '_validation_skeleton' progress: 2/25 (8%) complete, 2 ok, 0 failed, 3116.08 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🚶 custom column '_validation_skeleton' progress: 4/25 (16%) complete, 4 ok, 0 failed, 3444.69 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🚶 custom column '_validation_skeleton' progress: 6/25 (24%) complete, 6 ok, 0 failed, 3401.60 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐴 custom column '_validation_skeleton' progress: 8/25 (32%) complete, 8 ok, 0 failed, 3833.33 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐴 custom column '_validation_skeleton' progress: 10/25 (40%) complete, 10 ok, 0 failed, 3559.67 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🐴 custom column '_validation_skeleton' progress: 12/25 (48%) complete, 12 ok, 0 failed, 3682.20 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🚗 custom column '_validation_skeleton' progress: 14/25 (56%) complete, 14 ok, 0 failed, 3660.45 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🚗 custom column '_validation_skeleton' progress: 16/25 (64%) complete, 16 ok, 0 failed, 3756.90 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- 🚗 custom column '_validation_skeleton' progress: 18/25 (72%) complete, 18 ok, 0 failed, 3875.93 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- ✈️ custom column '_validation_skeleton' progress: 20/25 (80%) complete, 20 ok, 0 failed, 3913.89 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- ✈️ custom column '_validation_skeleton' progress: 22/25 (88%) complete, 22 ok, 0 failed, 3896.77 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- ✈️ custom column '_validation_skeleton' progress: 24/25 (96%) complete, 24 ok, 0 failed, 4082.67 rec/s, eta 0.0s

[15:59:47] [INFO]   |-- ✈️ custom column '_validation_skeleton' progress: 24/25 (96%) complete, 24 ok, 0 failed, 3964.65 rec/s, eta 0.0s

[15:59:47] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'

[15:59:47] [INFO]   |-- model: 'openai/gpt-oss-120b'

[15:59:47] [INFO]   |-- model alias: 'gpt-oss-120b'

[15:59:47] [INFO]   |-- model provider: 'nvidia'

[15:59:47] [INFO]   |-- inference parameters:

[15:59:47] [INFO]   |  |-- generation_type=chat-completion

[15:59:47] [INFO]   |  |-- max_parallel_requests=2

[15:59:47] [INFO]   |  |-- timeout=300

[15:59:47] [INFO]   |  |-- temperature=0.30

[15:59:47] [INFO]   |  |-- top_p=0.95

[15:59:47] [INFO]   |  |-- max_tokens=16384

[15:59:47] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 2 concurrent workers

[15:59:47] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress every 2 records

[16:00:28] [INFO]   |-- 🚶 llm-structured column '_validation_decisions' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.05 rec/s, eta 471.7s

[16:00:54] [INFO]   |-- 🚶 llm-structured column '_validation_decisions' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.06 rec/s, eta 353.2s

[16:01:11] [INFO]   |-- 🚶 llm-structured column '_validation_decisions' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.07 rec/s, eta 265.3s

[16:01:37] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.07 rec/s, eta 234.4s

[16:02:00] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.07 rec/s, eta 200.1s

[16:02:39] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.07 rec/s, eta 186.3s

[16:03:08] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.07 rec/s, eta 157.9s

[16:03:20] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.08 rec/s, eta 119.8s

[16:03:42] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.08 rec/s, eta 91.3s

[16:04:00] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.08 rec/s, eta 63.2s

[16:04:40] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.08 rec/s, eta 40.0s

[16:05:12] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.07 rec/s, eta 13.5s

[16:05:12] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.07 rec/s, eta 13.5s

[16:05:12] [INFO] 🔧 Custom column config for column '_validated_entities'

[16:05:12] [INFO]   |-- generator_function: 'enrich_validation_decisions'

[16:05:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:05:12] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']

[16:05:12] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers

[16:05:12] [INFO] ⏱️ custom column '_validated_entities' will report progress every 2 records

[16:05:12] [INFO]   |-- 🌑 custom column '_validated_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1179.48 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌑 custom column '_validated_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 1332.17 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌑 custom column '_validated_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 1493.31 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌘 custom column '_validated_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 1716.03 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌘 custom column '_validated_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 1768.10 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌘 custom column '_validated_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 1730.98 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌗 custom column '_validated_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 1872.60 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌗 custom column '_validated_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 1959.83 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌗 custom column '_validated_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 1987.70 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌖 custom column '_validated_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2035.84 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌖 custom column '_validated_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2078.76 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌖 custom column '_validated_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2218.17 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🌖 custom column '_validated_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2159.01 rec/s, eta 0.0s

[16:05:12] [INFO] 🔧 Custom column config for column '_seed_entities_json'

[16:05:12] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'

[16:05:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:05:12] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']

[16:05:12] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']

[16:05:12] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers

[16:05:12] [INFO] ⏱️ custom column '_seed_entities_json' will report progress every 2 records

[16:05:12] [INFO]   |-- 🥚 custom column '_seed_entities_json' progress: 2/25 (8%) complete, 2 ok, 0 failed, 1824.82 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🥚 custom column '_seed_entities_json' progress: 4/25 (16%) complete, 4 ok, 0 failed, 2078.96 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🥚 custom column '_seed_entities_json' progress: 6/25 (24%) complete, 6 ok, 0 failed, 2044.99 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 8/25 (32%) complete, 8 ok, 0 failed, 2311.05 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 10/25 (40%) complete, 10 ok, 0 failed, 2191.10 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 12/25 (48%) complete, 12 ok, 0 failed, 2081.62 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 14/25 (56%) complete, 14 ok, 0 failed, 2151.49 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 16/25 (64%) complete, 16 ok, 0 failed, 2189.57 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 18/25 (72%) complete, 18 ok, 0 failed, 2241.77 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 20/25 (80%) complete, 20 ok, 0 failed, 2298.05 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 22/25 (88%) complete, 22 ok, 0 failed, 2294.50 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2424.53 rec/s, eta 0.0s

[16:05:12] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 24/25 (96%) complete, 24 ok, 0 failed, 2374.22 rec/s, eta 0.0s

[16:05:12] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'

[16:05:12] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:05:12] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:05:12] [INFO]   |-- model provider: 'nvidia'

[16:05:12] [INFO]   |-- inference parameters:

[16:05:12] [INFO]   |  |-- generation_type=chat-completion

[16:05:12] [INFO]   |  |-- max_parallel_requests=2

[16:05:12] [INFO]   |  |-- timeout=300

[16:05:12] [INFO]   |  |-- temperature=0.30

[16:05:12] [INFO]   |  |-- top_p=0.95

[16:05:12] [INFO]   |  |-- max_tokens=16384

[16:05:12] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 2 concurrent workers

[16:05:12] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress every 2 records

[16:05:20] [INFO]   |-- 🐱 llm-structured column '_augmented_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 98.2s

[16:05:27] [INFO]   |-- 🐱 llm-structured column '_augmented_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 0.27 rec/s, eta 79.0s

[16:05:38] [INFO]   |-- 🐱 llm-structured column '_augmented_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 0.23 rec/s, eta 81.3s

[16:05:50] [INFO]   |-- 😺 llm-structured column '_augmented_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 0.21 rec/s, eta 80.3s

[16:05:57] [INFO]   |-- 😺 llm-structured column '_augmented_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 0.22 rec/s, eta 68.1s

[16:06:03] [INFO]   |-- 😺 llm-structured column '_augmented_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 0.24 rec/s, eta 55.3s

[16:06:12] [INFO]   |-- 😸 llm-structured column '_augmented_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 0.23 rec/s, eta 47.0s

[16:06:18] [INFO]   |-- 😸 llm-structured column '_augmented_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 0.24 rec/s, eta 37.3s

[16:06:23] [INFO]   |-- 😸 llm-structured column '_augmented_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 0.25 rec/s, eta 27.6s

[16:06:32] [INFO]   |-- 😼 llm-structured column '_augmented_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 0.25 rec/s, eta 20.0s

[16:06:41] [INFO]   |-- 😼 llm-structured column '_augmented_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 0.25 rec/s, eta 12.1s

[16:06:49] [INFO]   |-- 😼 llm-structured column '_augmented_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.25 rec/s, eta 4.0s

[16:06:49] [INFO]   |-- 😼 llm-structured column '_augmented_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 0.25 rec/s, eta 4.0s

[16:06:49] [INFO] 🔧 Custom column config for column '_merged_entities'

[16:06:49] [INFO]   |-- generator_function: 'merge_and_build_candidates'

[16:06:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:06:49] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']

[16:06:49] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']

[16:06:49] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers

[16:06:49] [INFO] ⏱️ custom column '_merged_entities' will report progress every 2 records

[16:06:49] [INFO]   |-- 🌑 custom column '_merged_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 692.79 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌑 custom column '_merged_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 681.96 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌑 custom column '_merged_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 628.85 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌘 custom column '_merged_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 664.59 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌘 custom column '_merged_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 658.15 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌘 custom column '_merged_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 713.79 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌗 custom column '_merged_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 770.92 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌗 custom column '_merged_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 821.90 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌗 custom column '_merged_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 854.95 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌖 custom column '_merged_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 898.19 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌖 custom column '_merged_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 921.22 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌖 custom column '_merged_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 995.53 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌖 custom column '_merged_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 984.34 rec/s, eta 0.0s

[16:06:49] [INFO] 🔧 Custom column config for column '_detected_entities'

[16:06:49] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

[16:06:49] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:06:49] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']

[16:06:49] [INFO]   |-- side_effect_columns: ['tagged_text']

[16:06:49] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers

[16:06:49] [INFO] ⏱️ custom column '_detected_entities' will report progress every 2 records

[16:06:49] [INFO]   |-- 🌧️ custom column '_detected_entities' progress: 2/25 (8%) complete, 2 ok, 0 failed, 413.52 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- 🌧️ custom column '_detected_entities' progress: 4/25 (16%) complete, 4 ok, 0 failed, 310.08 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- 🌧️ custom column '_detected_entities' progress: 6/25 (24%) complete, 6 ok, 0 failed, 286.88 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- 🌦️ custom column '_detected_entities' progress: 8/25 (32%) complete, 8 ok, 0 failed, 215.01 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- 🌦️ custom column '_detected_entities' progress: 10/25 (40%) complete, 10 ok, 0 failed, 211.27 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- 🌦️ custom column '_detected_entities' progress: 12/25 (48%) complete, 12 ok, 0 failed, 204.87 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- ⛅ custom column '_detected_entities' progress: 14/25 (56%) complete, 14 ok, 0 failed, 195.84 rec/s, eta 0.1s

[16:06:49] [INFO]   |-- ⛅ custom column '_detected_entities' progress: 16/25 (64%) complete, 16 ok, 0 failed, 197.87 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- ⛅ custom column '_detected_entities' progress: 18/25 (72%) complete, 18 ok, 0 failed, 191.74 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌤️ custom column '_detected_entities' progress: 20/25 (80%) complete, 20 ok, 0 failed, 190.58 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌤️ custom column '_detected_entities' progress: 22/25 (88%) complete, 22 ok, 0 failed, 197.64 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌤️ custom column '_detected_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 204.76 rec/s, eta 0.0s

[16:06:49] [INFO]   |-- 🌤️ custom column '_detected_entities' progress: 24/25 (96%) complete, 24 ok, 0 failed, 204.40 rec/s, eta 0.0s

[16:06:49] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']

[16:06:49] [INFO] 📊 Model usage summary:

[16:06:49] [INFO]   |-- model: nvidia/gliner-pii

[16:06:49] [INFO]   |-- tokens: input=13695, output=30808, total=44503, tps=100

[16:06:49] [INFO]   |-- requests: success=24, failed=0, total=24, rpm=3

[16:06:49] [INFO]   |--

[16:06:49] [INFO]   |-- model: openai/gpt-oss-120b

[16:06:49] [INFO]   |-- tokens: input=272460, output=169002, total=441462, tps=997

[16:06:49] [INFO]   |-- requests: success=51, failed=0, total=51, rpm=6

[16:06:49] [INFO] 📐 Measuring dataset column statistics:

[16:06:49] [INFO]   |-- 📝 column: '_raw_detected_entities'

[16:06:49] [INFO]   |-- 🔧 column: '_seed_entities'

[16:06:49] [INFO]   |-- 🔧 column: '_validation_candidates'

[16:06:49] [INFO]   |-- 🔧 column: '_validated_entities'

[16:06:49] [INFO]   |-- 🔧 column: '_seed_entities_json'

[16:06:49] [INFO]   |-- 🗂️ column: '_augmented_entities'

[16:06:49] [INFO]   |-- 🔧 column: '_merged_entities'

[16:06:50] [INFO]   |-- 🔧 column: '_detected_entities'

[16:06:50] [DEBUG] NDD workflow 'entity-detection' returned 24 records

[16:06:50] [DEBUG] NDD workflow 'latent-entity-detection' starting with 24 records

[16:06:50] [DEBUG] NDD workflow 'latent-entity-detection': 1 columns ['_latent_entities']

[16:06:50] [INFO] 🎨 Creating Data Designer dataset

[16:06:50] [INFO] ✅ Validation passed

[16:06:50] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:06:50] [INFO] 🩺 Running health checks for models...

[16:06:50] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:06:50] [INFO]   |-- ✅ Passed!

[16:06:50] [INFO] 📂 Dataset path '.anonymizer-artifacts/latent-entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/latent-entity-detection_03-31-2026_160650' instead.

[16:06:50] [INFO] ⏳ Processing batch 1 of 1

[16:06:50] [INFO] 🌱 Sampling 24 records from seed dataset

[16:06:50] [INFO]   |-- seed dataset size: 24 records

[16:06:50] [INFO]   |-- sampling strategy: ordered

[16:06:50] [INFO] 🗂️ llm-structured model config for column '_latent_entities'

[16:06:50] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:06:50] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[16:06:50] [INFO]   |-- model provider: 'nvidia'

[16:06:50] [INFO]   |-- inference parameters:

[16:06:50] [INFO]   |  |-- generation_type=chat-completion

[16:06:50] [INFO]   |  |-- max_parallel_requests=16

[16:06:50] [INFO]   |  |-- timeout=300

[16:06:50] [INFO]   |  |-- temperature=0.40

[16:06:50] [INFO]   |  |-- top_p=1.00

[16:06:50] [INFO]   |  |-- max_tokens=8192

[16:06:50] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers

[16:06:50] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress every 2 records

[16:06:59] [INFO]   |-- 🥚 llm-structured column '_latent_entities' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 102.7s

[16:07:01] [INFO]   |-- 🥚 llm-structured column '_latent_entities' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.38 rec/s, eta 53.1s

[16:07:03] [INFO]   |-- 🐣 llm-structured column '_latent_entities' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.47 rec/s, eta 38.7s

[16:07:04] [INFO]   |-- 🐣 llm-structured column '_latent_entities' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.59 rec/s, eta 27.0s

[16:07:04] [INFO]   |-- 🐣 llm-structured column '_latent_entities' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.70 rec/s, eta 19.9s

[16:07:05] [INFO]   |-- 🐥 llm-structured column '_latent_entities' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.78 rec/s, eta 15.5s

[16:07:07] [INFO]   |-- 🐥 llm-structured column '_latent_entities' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.81 rec/s, eta 12.4s

[16:07:10] [INFO]   |-- 🐥 llm-structured column '_latent_entities' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.81 rec/s, eta 9.9s

[16:07:13] [INFO]   |-- 🐤 llm-structured column '_latent_entities' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.79 rec/s, eta 7.6s

[16:07:15] [INFO]   |-- 🐤 llm-structured column '_latent_entities' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.80 rec/s, eta 5.0s

[16:07:16] [INFO]   |-- 🐤 llm-structured column '_latent_entities' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.84 rec/s, eta 2.4s

[16:07:29] [INFO]   |-- 🐔 llm-structured column '_latent_entities' progress: 24/24 (100%) complete, 24 ok, 0 failed, 0.61 rec/s, eta 0.0s

[16:07:29] [INFO] 📊 Model usage summary:

[16:07:29] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:07:29] [INFO]   |-- tokens: input=63707, output=79459, total=143166, tps=3626

[16:07:29] [INFO]   |-- requests: success=24, failed=0, total=24, rpm=36

[16:07:29] [INFO] 📐 Measuring dataset column statistics:

[16:07:29] [INFO]   |-- 🗂️ column: '_latent_entities'

[16:07:30] [DEBUG] NDD workflow 'latent-entity-detection' returned 24 records

[16:07:30] [INFO]   |-- 📋 Detection complete — 1245 entities found across 24 records (1 failed) [484.6s]

[16:07:30] [INFO]   |-- labels: date=406, court_name=238, legal_role=155, last_name=81, organization_name=75, first_name=60, nationality=49, city=44, country=41, application_number=24, date_of_birth=23, prison_detention_facility=18, sentence_duration=13, monetary_amount=10, state=5, case_number=1, age=1, company_name=1

[16:07:30] [INFO] ✏️ Running rewrite pipeline

[16:07:30] [DEBUG] NDD workflow 'replace-map-generation' starting with 24 records

[16:07:30] [DEBUG] NDD workflow 'replace-map-generation': 1 columns ['_replacement_map']

[16:07:30] [INFO] 🎨 Creating Data Designer dataset

[16:07:30] [INFO] ✅ Validation passed

[16:07:30] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:07:30] [INFO] 🩺 Running health checks for models...

[16:07:30] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[16:07:30] [INFO]   |-- ✅ Passed!

[16:07:30] [INFO] 📂 Dataset path '.anonymizer-artifacts/replace-map-generation' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/replace-map-generation_03-31-2026_160730' instead.

[16:07:30] [INFO] ⏳ Processing batch 1 of 1

[16:07:30] [INFO] 🌱 Sampling 24 records from seed dataset

[16:07:30] [INFO]   |-- seed dataset size: 24 records

[16:07:30] [INFO]   |-- sampling strategy: ordered

[16:07:30] [INFO] 🗂️ llm-structured model config for column '_replacement_map'

[16:07:30] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:07:30] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:07:30] [INFO]   |-- model provider: 'nvidia'

[16:07:30] [INFO]   |-- inference parameters:

[16:07:30] [INFO]   |  |-- generation_type=chat-completion

[16:07:30] [INFO]   |  |-- max_parallel_requests=2

[16:07:30] [INFO]   |  |-- timeout=300

[16:07:30] [INFO]   |  |-- temperature=0.30

[16:07:30] [INFO]   |  |-- top_p=0.95

[16:07:30] [INFO]   |  |-- max_tokens=16384

[16:07:30] [INFO] ⚡️ Processing llm-structured column '_replacement_map' with 2 concurrent workers

[16:07:30] [INFO] ⏱️ llm-structured column '_replacement_map' will report progress every 2 records

[16:07:51] [INFO]   |-- 🌑 llm-structured column '_replacement_map' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.09 rec/s, eta 234.5s

[16:08:03] [INFO]   |-- 🌑 llm-structured column '_replacement_map' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.12 rec/s, eta 165.2s

[16:08:19] [INFO]   |-- 🌘 llm-structured column '_replacement_map' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.12 rec/s, eta 146.5s

[16:08:37] [INFO]   |-- 🌘 llm-structured column '_replacement_map' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.12 rec/s, eta 133.8s

[16:09:01] [INFO]   |-- 🌘 llm-structured column '_replacement_map' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.11 rec/s, eta 127.3s

[16:09:25] [INFO]   |-- 🌗 llm-structured column '_replacement_map' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.10 rec/s, eta 115.0s

[16:09:45] [INFO]   |-- 🌗 llm-structured column '_replacement_map' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.10 rec/s, eta 96.1s

[16:09:56] [INFO]   |-- 🌗 llm-structured column '_replacement_map' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.11 rec/s, eta 73.0s

[16:10:14] [INFO]   |-- 🌖 llm-structured column '_replacement_map' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.11 rec/s, eta 54.6s

[16:10:31] [INFO]   |-- 🌖 llm-structured column '_replacement_map' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.11 rec/s, eta 36.2s

[16:11:02] [INFO]   |-- 🌖 llm-structured column '_replacement_map' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.10 rec/s, eta 19.2s

[16:12:26] [INFO]   |-- 🌕 llm-structured column '_replacement_map' progress: 24/24 (100%) complete, 24 ok, 0 failed, 0.08 rec/s, eta 0.0s

[16:12:26] [INFO] 📊 Model usage summary:

[16:12:26] [INFO]   |-- model: openai/gpt-oss-120b

[16:12:26] [INFO]   |-- tokens: input=67752, output=105939, total=173691, tps=586

[16:12:26] [INFO]   |-- requests: success=25, failed=0, total=25, rpm=5

[16:12:26] [INFO] 📐 Measuring dataset column statistics:

[16:12:26] [INFO]   |-- 🗂️ column: '_replacement_map'

[16:12:26] [DEBUG] NDD workflow 'replace-map-generation' returned 24 records

[16:12:26] [DEBUG] Replacement map record 4b0aa40e665254958f579ede68e86fcd: requested=[('12 February 1980', 'date'), ('14 June 2005', 'date'), ('14 September 1999', 'date'), ('15 December 2000', 'date'), ('16 November 2000', 'date'), ('1958', 'date_of_birth'), ('23 October 1992', 'date_of_birth'), ('27 December 1999', 'date'), ('5 April 2000', 'date'), ('74463/01', 'application_number'), ('8 June 2001', 'date'), ('Aydın', 'city'), ('Aydın Civil Court of first-instance', 'court_name'), ('Bahçeyaka', 'last_name'), ('Court of Cassation', 'court_name'), ('Feriştah', 'first_name'), ('German', 'nationality'), ('Germany', 'country'), ('Kuloğlu', 'last_name'), ('Republic of Turkey', 'country'), ('Turkish', 'nationality'), ('Wesel', 'city'), ('lawyer', 'legal_role')] raw=[{'original': '12 February 1980', 'label': 'date', 'synthetic': '15 March 1981'}, {'original': '14 June 2005', 'label': 'date', 'synthetic': '22 July 2006'}, {'original': '14 September 1999', 'label': 'date', 'synthetic': '03 October 2000'}, {'original': '15 December 2000', 'label': 'date', 'synthetic': '08 January 2002'}, {'original': '16 November 2000', 'label': 'date', 'synthetic': '27 December 2001'}, {'original': '1958', 'label': 'date_of_birth', 'synthetic': '1960'}, {'original': '23 October 1992', 'label': 'date_of_birth', 'synthetic': '15 July 1993'}, {'original': '27 December 1999', 'label': 'date', 'synthetic': '09 January 2000'}, {'original': '5 April 2000', 'label': 'date', 'synthetic': '12 May 2001'}, {'original': '74463/01', 'label': 'application_number', 'synthetic': '83927/02'}, {'original': '8 June 2001', 'label': 'date', 'synthetic': '19 July 2002'}, {'original': 'Aydın', 'label': 'city', 'synthetic': 'Seville'}, {'original': 'Aydın Civil Court of first-instance', 'label': 'court_name', 'synthetic': 'Seville Civil Court of First Instance'}, {'original': 'Bahçeyaka', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Spain'}, {'original': 'Feriştah', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'German', 'label': 'nationality', 'synthetic': 'French'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Kuloğlu', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Wesel', 'label': 'city', 'synthetic': 'Lyon'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'notary'}] filtered=[{'original': '12 February 1980', 'label': 'date', 'synthetic': '15 March 1981'}, {'original': '14 June 2005', 'label': 'date', 'synthetic': '22 July 2006'}, {'original': '14 September 1999', 'label': 'date', 'synthetic': '03 October 2000'}, {'original': '15 December 2000', 'label': 'date', 'synthetic': '08 January 2002'}, {'original': '16 November 2000', 'label': 'date', 'synthetic': '27 December 2001'}, {'original': '1958', 'label': 'date_of_birth', 'synthetic': '1960'}, {'original': '23 October 1992', 'label': 'date_of_birth', 'synthetic': '15 July 1993'}, {'original': '27 December 1999', 'label': 'date', 'synthetic': '09 January 2000'}, {'original': '5 April 2000', 'label': 'date', 'synthetic': '12 May 2001'}, {'original': '74463/01', 'label': 'application_number', 'synthetic': '83927/02'}, {'original': '8 June 2001', 'label': 'date', 'synthetic': '19 July 2002'}, {'original': 'Aydın', 'label': 'city', 'synthetic': 'Seville'}, {'original': 'Aydın Civil Court of first-instance', 'label': 'court_name', 'synthetic': 'Seville Civil Court of First Instance'}, {'original': 'Bahçeyaka', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Spain'}, {'original': 'Feriştah', 'label': 'first_name', 'synthetic': 'Isabel'}, {'original': 'German', 'label': 'nationality', 'synthetic': 'French'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Kuloğlu', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Wesel', 'label': 'city', 'synthetic': 'Lyon'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'notary'}]

[16:12:26] [DEBUG] Replacement map record fffc4038297b5cf19b2a149604f8dc42: requested=[('14 February 2002', 'date'), ('14 July 1998', 'date'), ('15 January 2001', 'date'), ('17 June 2004', 'date'), ('17 September 2004', 'date'), ('18 January 2005', 'date'), ('1940', 'date'), ('2 January 2006', 'date'), ('200 Polish zlotys', 'monetary_amount'), ('2004', 'date'), ('24 October 2006', 'date'), ('25 October 2004', 'date'), ('25 September 2007', 'date'), ('26 July 2004', 'date'), ('29360/06', 'application_number'), ('3 August 2000', 'date'), ('3 July 1998', 'date'), ('3 July 2006', 'date'), ('30 June 2004', 'date'), ('7 November 1997', 'date'), ('8 March 1994', 'date'), ('9 February 1998', 'date'), ('9 May 2006', 'date'), ('9 May 2007', 'date'), ('Agent', 'legal_role'), ('District Court', 'court_name'), ('III SPP 113/04', 'case_number'), ('Jerzak', 'last_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('President of the Fourth Section', 'legal_role'), ('Regional Court', 'court_name'), ('Republic of Poland', 'country'), ('Sulejówek', 'city'), ('Supreme Court', 'organization_name'), ('Sąd Najwyższy', 'court_name'), ('Teresa', 'first_name'), ('Warsaw District Court', 'court_name'), ('Warsaw District Court (Sąd Rejonowy)', 'court_name'), ('Warsaw Regional Court', 'court_name'), ('Warsaw Regional Court (Sąd Okręgowy)', 'court_name'), ('Wołąsiewicz', 'last_name')] raw=[{'original': '14 February 2002', 'label': 'date', 'synthetic': '22 March 2002'}, {'original': '14 July 1998', 'label': 'date', 'synthetic': '19 August 1998'}, {'original': '15 January 2001', 'label': 'date', 'synthetic': '27 February 2001'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '23 July 2004'}, {'original': '17 September 2004', 'label': 'date', 'synthetic': '5 October 2004'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '30 January 2005'}, {'original': '1940', 'label': 'date', 'synthetic': '1938'}, {'original': '2 January 2006', 'label': 'date', 'synthetic': '9 February 2006'}, {'original': '200 Polish zlotys', 'label': 'monetary_amount', 'synthetic': '180 Czech korunas'}, {'original': '2004', 'label': 'date', 'synthetic': '2005'}, {'original': '24 October 2006', 'label': 'date', 'synthetic': '12 November 2006'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '25 September 2007', 'label': 'date', 'synthetic': '2 October 2007'}, {'original': '26 July 2004', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '29360/06', 'label': 'application_number', 'synthetic': '41728/09'}, {'original': '3 August 2000', 'label': 'date', 'synthetic': '15 September 2000'}, {'original': '3 July 1998', 'label': 'date', 'synthetic': '10 August 1998'}, {'original': '3 July 2006', 'label': 'date', 'synthetic': '11 August 2006'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '8 July 2004'}, {'original': '7 November 1997', 'label': 'date', 'synthetic': '15 December 1997'}, {'original': '8 March 1994', 'label': 'date', 'synthetic': '16 April 1994'}, {'original': '9 February 1998', 'label': 'date', 'synthetic': '20 March 1998'}, {'original': '9 May 2006', 'label': 'date', 'synthetic': '17 June 2006'}, {'original': '9 May 2007', 'label': 'date', 'synthetic': '18 June 2007'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Delegate'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'III SPP 113/04', 'label': 'case_number', 'synthetic': 'IV SPP 227/07'}, {'original': 'Jerzak', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Justice'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Chamber'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Budapest Regional Court'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Sulejówek', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Supreme Court', 'label': 'organization_name', 'synthetic': 'Constitutional Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Kúria'}, {'original': 'Teresa', 'label': 'first_name', 'synthetic': 'Anna'}, {'original': 'Warsaw District Court', 'label': 'court_name', 'synthetic': 'Debrecen District Court'}, {'original': 'Warsaw District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Debrecen District Court (Törvényszék)'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}, {'original': 'Warsaw Regional Court (Sąd Okręgowy)', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court (Fellebbviteli Bíróság)'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}] filtered=[{'original': '14 February 2002', 'label': 'date', 'synthetic': '22 March 2002'}, {'original': '14 July 1998', 'label': 'date', 'synthetic': '19 August 1998'}, {'original': '15 January 2001', 'label': 'date', 'synthetic': '27 February 2001'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '23 July 2004'}, {'original': '17 September 2004', 'label': 'date', 'synthetic': '5 October 2004'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '30 January 2005'}, {'original': '1940', 'label': 'date', 'synthetic': '1938'}, {'original': '2 January 2006', 'label': 'date', 'synthetic': '9 February 2006'}, {'original': '200 Polish zlotys', 'label': 'monetary_amount', 'synthetic': '180 Czech korunas'}, {'original': '2004', 'label': 'date', 'synthetic': '2005'}, {'original': '24 October 2006', 'label': 'date', 'synthetic': '12 November 2006'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '25 September 2007', 'label': 'date', 'synthetic': '2 October 2007'}, {'original': '26 July 2004', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '29360/06', 'label': 'application_number', 'synthetic': '41728/09'}, {'original': '3 August 2000', 'label': 'date', 'synthetic': '15 September 2000'}, {'original': '3 July 1998', 'label': 'date', 'synthetic': '10 August 1998'}, {'original': '3 July 2006', 'label': 'date', 'synthetic': '11 August 2006'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '8 July 2004'}, {'original': '7 November 1997', 'label': 'date', 'synthetic': '15 December 1997'}, {'original': '8 March 1994', 'label': 'date', 'synthetic': '16 April 1994'}, {'original': '9 February 1998', 'label': 'date', 'synthetic': '20 March 1998'}, {'original': '9 May 2006', 'label': 'date', 'synthetic': '17 June 2006'}, {'original': '9 May 2007', 'label': 'date', 'synthetic': '18 June 2007'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Delegate'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'III SPP 113/04', 'label': 'case_number', 'synthetic': 'IV SPP 227/07'}, {'original': 'Jerzak', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Justice'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Chamber'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Budapest Regional Court'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Sulejówek', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Supreme Court', 'label': 'organization_name', 'synthetic': 'Constitutional Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Kúria'}, {'original': 'Teresa', 'label': 'first_name', 'synthetic': 'Anna'}, {'original': 'Warsaw District Court', 'label': 'court_name', 'synthetic': 'Debrecen District Court'}, {'original': 'Warsaw District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Debrecen District Court (Törvényszék)'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}, {'original': 'Warsaw Regional Court (Sąd Okręgowy)', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court (Fellebbviteli Bíróság)'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}]

[16:12:26] [DEBUG] Replacement map record 53ab2db826735fb9b51f8432e5107099: requested=[('1 November 1998', 'date'), ('1 November 2004', 'date'), ('10 September 1994', 'date'), ('11 August 2000', 'date'), ('15 April 1999', 'date'), ('16 December 1994', 'date'), ('17 August 1998', 'date'), ('17 July 1998', 'date'), ('17 June 2003', 'date'), ('1968', 'date_of_birth'), ('1997-12-9', 'date'), ('21 July 1998', 'date'), ('21 October and 9 November 1998', 'date'), ('26 April 2001', 'date'), ('28 September 1998', 'date'), ('5 years', 'sentence_duration'), ('51895/99', 'application_number'), ('6 April 1999', 'date'), ('Bogdan', 'first_name'), ('Chełm', 'city'), ('Constitutional Court', 'court_name'), ('December 1997', 'date'), ('Drzewicki', 'last_name'), ('European Commission of Human Rights', 'organization_name'), ('Jaczewska', 'last_name'), ('Kwiek', 'last_name'), ('Lublin', 'city'), ('Lublin Court of Appeal (Sąd Apelacyjny)', 'court_name'), ('Lublin Regional Court', 'court_name'), ('Lublin Regional Court (Sąd Wojewódzki)', 'court_name'), ('Lublin Regional Prosecutor', 'organization_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('O.K.', 'first_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('Regional Court', 'court_name'), ('Regional Prosecutor', 'legal_role'), ('Republic of Poland', 'country'), ('Supreme Court (Sąd Najwyzszy)', 'court_name'), ('beginning of December 1995', 'date'), ('counsel', 'legal_role'), ('defence counsel', 'legal_role'), ('prosecutor', 'legal_role')] raw=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 2002'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2008'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 August 1993'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 September 2001'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 May 2000'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '9 January 1995'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '23 September 1999'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '2 October 1998'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '30 August 2004'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1970'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '1998-01-15'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 1998'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '14 September and 2 October 2002'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '11 May 2002'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '6 November 1999'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '62431/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '19 May 2000'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Rafael'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Fortaleza'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'Federal Constitutional Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 1998'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Almeida'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Commission on Human Rights'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Pereira'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'São Paulo'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'São Paulo Court of Appeals (Tribunal de Apelações)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'São Paulo State Court'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'São Paulo State Court (Tribunal de Justiça)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': "São Paulo Regional Prosecutor's Office"}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of International Relations'}, {'original': 'O.K.', 'label': 'first_name', 'synthetic': 'J.S.'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Brazil'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Brazilian'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'State Tribunal'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Brazil'}, {'original': 'Supreme Court (Sąd Najwyzszy)', 'label': 'court_name', 'synthetic': 'Brazilian Supreme Court (Supremo Tribunal Federal)'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'beginning of January 1996'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal adviser'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'court-appointed advocate'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}] filtered=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 2002'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2008'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 August 1993'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 September 2001'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 May 2000'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '9 January 1995'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '23 September 1999'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '2 October 1998'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '30 August 2004'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1970'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '1998-01-15'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 1998'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '14 September and 2 October 2002'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '11 May 2002'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '6 November 1999'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '62431/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '19 May 2000'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Rafael'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Fortaleza'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'Federal Constitutional Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 1998'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Almeida'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Commission on Human Rights'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Pereira'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'São Paulo'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'São Paulo Court of Appeals (Tribunal de Apelações)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'São Paulo State Court'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'São Paulo State Court (Tribunal de Justiça)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': "São Paulo Regional Prosecutor's Office"}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of International Relations'}, {'original': 'O.K.', 'label': 'first_name', 'synthetic': 'J.S.'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Brazil'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Brazilian'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'State Tribunal'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Brazil'}, {'original': 'Supreme Court (Sąd Najwyzszy)', 'label': 'court_name', 'synthetic': 'Brazilian Supreme Court (Supremo Tribunal Federal)'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'beginning of January 1996'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal adviser'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'court-appointed advocate'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}]

[16:12:26] [DEBUG] Replacement map record f8c0cf17594b514da4e47d9665801aef: requested=[('11 April 2012', 'date'), ('12 January 2012', 'date'), ('13 June 2012', 'date'), ('14 July 2012', 'date'), ('14 October 2011', 'date'), ('16 May 2012', 'date'), ('1989', 'date_of_birth'), ('30 August 2012', 'date'), ('57292/12', 'application_number'), ('7 July 2014', 'date'), ('Agent', 'legal_role'), ('Chrzanowska', 'last_name'), ('Jakub', 'first_name'), ('Kotuła', 'last_name'), ('Lublin', 'city'), ('Lublin Regional Court', 'court_name'), ('Lublin Remand Centre', 'organization_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('October 2011', 'date'), ('Opole Lubelskie Prison', 'prison_detention_facility'), ('Paluch', 'last_name'), ('Penitentiary Commission', 'court_name'), ('Polish', 'nationality'), ('Polish Government', 'organization_name'), ('Republic of Poland', 'country'), ('cell', 'prison_detention_facility'), ('lawyer', 'legal_role'), ('leader', 'legal_role'), ('penitentiary commission', 'court_name'), ('prison employee', 'legal_role')] raw=[{'original': '11 April 2012', 'label': 'date', 'synthetic': '23 March 2013'}, {'original': '12 January 2012', 'label': 'date', 'synthetic': '05 February 2013'}, {'original': '13 June 2012', 'label': 'date', 'synthetic': '19 July 2013'}, {'original': '14 July 2012', 'label': 'date', 'synthetic': '02 August 2013'}, {'original': '14 October 2011', 'label': 'date', 'synthetic': '09 November 2010'}, {'original': '16 May 2012', 'label': 'date', 'synthetic': '27 April 2013'}, {'original': '1989', 'label': 'date_of_birth', 'synthetic': '1992'}, {'original': '30 August 2012', 'label': 'date', 'synthetic': '15 September 2013'}, {'original': '57292/12', 'label': 'application_number', 'synthetic': '48317/09'}, {'original': '7 July 2014', 'label': 'date', 'synthetic': '22 August 2015'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'liaison'}, {'original': 'Chrzanowska', 'label': 'last_name', 'synthetic': 'Farkas'}, {'original': 'Jakub', 'label': 'first_name', 'synthetic': 'Mihai'}, {'original': 'Kotuła', 'label': 'last_name', 'synthetic': 'Dobre'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Cluj-Napoca'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Cluj-Napoca Regional Court'}, {'original': 'Lublin Remand Centre', 'label': 'organization_name', 'synthetic': 'Cluj-Napoca Remand Centre'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'October 2011', 'label': 'date', 'synthetic': 'November 2010'}, {'original': 'Opole Lubelskie Prison', 'label': 'prison_detention_facility', 'synthetic': 'Szeged Detention Center'}, {'original': 'Paluch', 'label': 'last_name', 'synthetic': 'Varga'}, {'original': 'Penitentiary Commission', 'label': 'court_name', 'synthetic': 'Detention Review Board'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'cell', 'label': 'prison_detention_facility', 'synthetic': 'block'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'leader', 'label': 'legal_role', 'synthetic': 'coordinator'}, {'original': 'penitentiary commission', 'label': 'court_name', 'synthetic': 'detention review board'}, {'original': 'prison employee', 'label': 'legal_role', 'synthetic': 'correctional officer'}] filtered=[{'original': '11 April 2012', 'label': 'date', 'synthetic': '23 March 2013'}, {'original': '12 January 2012', 'label': 'date', 'synthetic': '05 February 2013'}, {'original': '13 June 2012', 'label': 'date', 'synthetic': '19 July 2013'}, {'original': '14 July 2012', 'label': 'date', 'synthetic': '02 August 2013'}, {'original': '14 October 2011', 'label': 'date', 'synthetic': '09 November 2010'}, {'original': '16 May 2012', 'label': 'date', 'synthetic': '27 April 2013'}, {'original': '1989', 'label': 'date_of_birth', 'synthetic': '1992'}, {'original': '30 August 2012', 'label': 'date', 'synthetic': '15 September 2013'}, {'original': '57292/12', 'label': 'application_number', 'synthetic': '48317/09'}, {'original': '7 July 2014', 'label': 'date', 'synthetic': '22 August 2015'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'liaison'}, {'original': 'Chrzanowska', 'label': 'last_name', 'synthetic': 'Farkas'}, {'original': 'Jakub', 'label': 'first_name', 'synthetic': 'Mihai'}, {'original': 'Kotuła', 'label': 'last_name', 'synthetic': 'Dobre'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Cluj-Napoca'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Cluj-Napoca Regional Court'}, {'original': 'Lublin Remand Centre', 'label': 'organization_name', 'synthetic': 'Cluj-Napoca Remand Centre'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'October 2011', 'label': 'date', 'synthetic': 'November 2010'}, {'original': 'Opole Lubelskie Prison', 'label': 'prison_detention_facility', 'synthetic': 'Szeged Detention Center'}, {'original': 'Paluch', 'label': 'last_name', 'synthetic': 'Varga'}, {'original': 'Penitentiary Commission', 'label': 'court_name', 'synthetic': 'Detention Review Board'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'cell', 'label': 'prison_detention_facility', 'synthetic': 'block'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'leader', 'label': 'legal_role', 'synthetic': 'coordinator'}, {'original': 'penitentiary commission', 'label': 'court_name', 'synthetic': 'detention review board'}, {'original': 'prison employee', 'label': 'legal_role', 'synthetic': 'correctional officer'}]

[16:12:26] [DEBUG] Replacement map record ae49f2f624fb51e2992e01360e501730: requested=[('1 August 2005', 'date'), ('10 November 2005', 'date'), ('11 March 2004', 'date'), ('18 October 2000', 'date'), ('1961', 'date_of_birth'), ('20 April 2005', 'date'), ('26 February 2008', 'date'), ('30 March 2004', 'date'), ('37291/04', 'application_number'), ('5 September 2000', 'date'), ('6 November 2000', 'date'), ('7 May 2008', 'date'), ('8 September 2000', 'date'), ('Agent', 'legal_role'), ('Court of Cassation', 'court_name'), ('Fırat', 'last_name'), ('Gümrükçüoğlu', 'last_name'), ('Istanbul', 'city'), ('Istanbul Assize Court', 'court_name'), ('Istanbul State Security Court', 'court_name'), ('Mehmet', 'first_name'), ('President', 'legal_role'), ('Republic of Turkey', 'country'), ('Second Section', 'organization_name'), ('Trabzon', 'city'), ('Turkish', 'nationality'), ('Turkish Government', 'organization_name'), ('lawyer', 'legal_role'), ('public prosecutor', 'legal_role'), ('twelve years, eight months and fifteen days', 'sentence_duration')] raw=[{'original': '1 August 2005', 'label': 'date', 'synthetic': '3 September 2005'}, {'original': '10 November 2005', 'label': 'date', 'synthetic': '12 December 2005'}, {'original': '11 March 2004', 'label': 'date', 'synthetic': '14 April 2004'}, {'original': '18 October 2000', 'label': 'date', 'synthetic': '22 November 2000'}, {'original': '1961', 'label': 'date_of_birth', 'synthetic': '1963'}, {'original': '20 April 2005', 'label': 'date', 'synthetic': '25 May 2005'}, {'original': '26 February 2008', 'label': 'date', 'synthetic': '2 March 2008'}, {'original': '30 March 2004', 'label': 'date', 'synthetic': '5 May 2004'}, {'original': '5 September 2000', 'label': 'date', 'synthetic': '9 October 2000'}, {'original': '6 November 2000', 'label': 'date', 'synthetic': '10 December 2000'}, {'original': '7 May 2008', 'label': 'date', 'synthetic': '15 June 2008'}, {'original': '8 September 2000', 'label': 'date', 'synthetic': '13 October 2000'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Representative'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Tribunal'}, {'original': 'Fırat', 'label': 'last_name', 'synthetic': 'Papadopoulos'}, {'original': 'Gümrükçüoğlu', 'label': 'last_name', 'synthetic': 'Kostopoulos'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Athens'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Athens Assize Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Athens State Security Court'}, {'original': 'Mehmet', 'label': 'first_name', 'synthetic': 'Nikos'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'Second Section', 'label': 'organization_name', 'synthetic': 'Third Division'}, {'original': 'Trabzon', 'label': 'city', 'synthetic': 'Thessaloniki'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Turkish Government', 'label': 'organization_name', 'synthetic': 'Greek Government'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}, {'original': 'twelve years, eight months and fifteen days', 'label': 'sentence_duration', 'synthetic': 'nine years, three months and six days'}, {'original': '37291/04', 'label': 'application_number', 'synthetic': '48312/07'}] filtered=[{'original': '1 August 2005', 'label': 'date', 'synthetic': '3 September 2005'}, {'original': '10 November 2005', 'label': 'date', 'synthetic': '12 December 2005'}, {'original': '11 March 2004', 'label': 'date', 'synthetic': '14 April 2004'}, {'original': '18 October 2000', 'label': 'date', 'synthetic': '22 November 2000'}, {'original': '1961', 'label': 'date_of_birth', 'synthetic': '1963'}, {'original': '20 April 2005', 'label': 'date', 'synthetic': '25 May 2005'}, {'original': '26 February 2008', 'label': 'date', 'synthetic': '2 March 2008'}, {'original': '30 March 2004', 'label': 'date', 'synthetic': '5 May 2004'}, {'original': '5 September 2000', 'label': 'date', 'synthetic': '9 October 2000'}, {'original': '6 November 2000', 'label': 'date', 'synthetic': '10 December 2000'}, {'original': '7 May 2008', 'label': 'date', 'synthetic': '15 June 2008'}, {'original': '8 September 2000', 'label': 'date', 'synthetic': '13 October 2000'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Representative'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Tribunal'}, {'original': 'Fırat', 'label': 'last_name', 'synthetic': 'Papadopoulos'}, {'original': 'Gümrükçüoğlu', 'label': 'last_name', 'synthetic': 'Kostopoulos'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Athens'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Athens Assize Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Athens State Security Court'}, {'original': 'Mehmet', 'label': 'first_name', 'synthetic': 'Nikos'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'Second Section', 'label': 'organization_name', 'synthetic': 'Third Division'}, {'original': 'Trabzon', 'label': 'city', 'synthetic': 'Thessaloniki'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Turkish Government', 'label': 'organization_name', 'synthetic': 'Greek Government'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}, {'original': 'twelve years, eight months and fifteen days', 'label': 'sentence_duration', 'synthetic': 'nine years, three months and six days'}, {'original': '37291/04', 'label': 'application_number', 'synthetic': '48312/07'}]

[16:12:26] [DEBUG] Replacement map record 16021cc952735cc58f26402bd7859274: requested=[('16 June 2004', 'date'), ('1976', 'date_of_birth'), ('20 August 1996', 'date'), ('20 May 2002', 'date'), ('28 August 2008', 'date'), ('3 September 1996', 'date'), ('30 June 2004', 'date'), ('30 September 2003', 'date'), ('31 August 2004', 'date'), ('31 March 2006', 'date'), ('35257/04', 'application_number'), ('6 December 1996', 'date'), ('Agent', 'legal_role'), ('Bahçeli', 'last_name'), ('Convention for the Protection of Human Rights and Fundamental Freedoms', 'organization_name'), ('Court of Cassation', 'court_name'), ('Istanbul', 'city'), ('Istanbul', 'state'), ('Istanbul Assize Court', 'court_name'), ('Istanbul State Security Court', 'court_name'), ('K.T.', 'first_name'), ('Murat', 'first_name'), ('Official Gazette', 'organization_name'), ('Republic of Turkey', 'country'), ('State Security Courts', 'court_name'), ('Sürek', 'last_name'), ('Turkish', 'nationality'), ('Turkish Government', 'organization_name'), ('death', 'sentence_duration'), ('first-instance court', 'court_name'), ('lawyer', 'legal_role'), ('life imprisonment', 'sentence_duration'), ('public prosecutor', 'legal_role')] raw=[{'original': '16 June 2004', 'label': 'date', 'synthetic': '22 July 2005'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1982'}, {'original': '20 August 1996', 'label': 'date', 'synthetic': '15 September 1997'}, {'original': '20 May 2002', 'label': 'date', 'synthetic': '12 June 2003'}, {'original': '28 August 2008', 'label': 'date', 'synthetic': '5 September 2009'}, {'original': '3 September 1996', 'label': 'date', 'synthetic': '10 October 1997'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '14 July 2005'}, {'original': '30 September 2003', 'label': 'date', 'synthetic': '2 November 2004'}, {'original': '31 August 2004', 'label': 'date', 'synthetic': '9 September 2005'}, {'original': '31 March 2006', 'label': 'date', 'synthetic': '18 April 2007'}, {'original': '35257/04', 'label': 'application_number', 'synthetic': '46789/07'}, {'original': '6 December 1996', 'label': 'date', 'synthetic': '8 January 1998'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'delegate'}, {'original': 'Bahçeli', 'label': 'last_name', 'synthetic': 'Yılmaz'}, {'original': 'Convention for the Protection of Human Rights and Fundamental Freedoms', 'label': 'organization_name', 'synthetic': 'Charter for the Safeguarding of Civil Liberties and Democratic Principles'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Appeals Tribunal'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Portland District Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Portland Anti‑Terrorism Tribunal'}, {'original': 'K.T.', 'label': 'first_name', 'synthetic': 'A.R.'}, {'original': 'Murat', 'label': 'first_name', 'synthetic': 'Kemal'}, {'original': 'Official Gazette', 'label': 'organization_name', 'synthetic': 'Public Bulletin'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'State Security Courts', 'label': 'court_name', 'synthetic': 'Special Anti‑Terror Courts'}, {'original': 'Sürek', 'label': 'last_name', 'synthetic': 'Demir'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Turkish Government', 'label': 'organization_name', 'synthetic': 'Greek Government'}, {'original': 'death', 'label': 'sentence_duration', 'synthetic': '30 years imprisonment'}, {'original': 'first-instance court', 'label': 'court_name', 'synthetic': 'initial trial court'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': '25-year fixed term'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}] filtered=[{'original': '16 June 2004', 'label': 'date', 'synthetic': '22 July 2005'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1982'}, {'original': '20 August 1996', 'label': 'date', 'synthetic': '15 September 1997'}, {'original': '20 May 2002', 'label': 'date', 'synthetic': '12 June 2003'}, {'original': '28 August 2008', 'label': 'date', 'synthetic': '5 September 2009'}, {'original': '3 September 1996', 'label': 'date', 'synthetic': '10 October 1997'}, {'original': '30 June 2004', 'label': 'date', 'synthetic': '14 July 2005'}, {'original': '30 September 2003', 'label': 'date', 'synthetic': '2 November 2004'}, {'original': '31 August 2004', 'label': 'date', 'synthetic': '9 September 2005'}, {'original': '31 March 2006', 'label': 'date', 'synthetic': '18 April 2007'}, {'original': '35257/04', 'label': 'application_number', 'synthetic': '46789/07'}, {'original': '6 December 1996', 'label': 'date', 'synthetic': '8 January 1998'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'delegate'}, {'original': 'Bahçeli', 'label': 'last_name', 'synthetic': 'Yılmaz'}, {'original': 'Convention for the Protection of Human Rights and Fundamental Freedoms', 'label': 'organization_name', 'synthetic': 'Charter for the Safeguarding of Civil Liberties and Democratic Principles'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Appeals Tribunal'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Portland'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Oregon'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Portland District Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Portland Anti‑Terrorism Tribunal'}, {'original': 'K.T.', 'label': 'first_name', 'synthetic': 'A.R.'}, {'original': 'Murat', 'label': 'first_name', 'synthetic': 'Kemal'}, {'original': 'Official Gazette', 'label': 'organization_name', 'synthetic': 'Public Bulletin'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'State Security Courts', 'label': 'court_name', 'synthetic': 'Special Anti‑Terror Courts'}, {'original': 'Sürek', 'label': 'last_name', 'synthetic': 'Demir'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Turkish Government', 'label': 'organization_name', 'synthetic': 'Greek Government'}, {'original': 'death', 'label': 'sentence_duration', 'synthetic': '30 years imprisonment'}, {'original': 'first-instance court', 'label': 'court_name', 'synthetic': 'initial trial court'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': '25-year fixed term'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'investigative magistrate'}]

[16:12:26] [DEBUG] Replacement map record 7d722a539c43571c928e7e3b5ab0ec32: requested=[('1 November 2004', 'date'), ('14 April 2000', 'date'), ('14 October 2000', 'date'), ('15 December 1997', 'date'), ('18 December 1997', 'date'), ('19 December 1997', 'date'), ('1960', 'date_of_birth'), ('23 December 1997', 'date'), ('23 June 1998', 'date'), ('28 May 2002', 'date'), ('30 November 2004', 'date'), ('4 June 1998', 'date'), ('66689/01', 'application_number'), ('Anti-Terrorist Branch', 'organization_name'), ('Chamber', 'court_name'), ('Court of Cassation', 'organization_name'), ('Court of Cassation.\n\nOn 20 September 1999 the Court of Cassation', 'court_name'), ('Public Prosecutor', 'legal_role'), ('Republic of Turkey', 'country'), ('Revolutionary Communists’ Union of Turkey', 'organization_name'), ('Second Section', 'court_name'), ('State Security Court', 'court_name'), ('TIKB', 'organization_name'), ('Turkish', 'nationality'), ('Türkiye İhtilalci Komünistler Birliği', 'organization_name'), ('Uşak', 'city'), ('Yıldız', 'first_name'), ('Yılmaz', 'last_name'), ('Z.', 'first_name'), ('judge', 'legal_role'), ('lawyer', 'legal_role'), ('three years and nine months', 'sentence_duration'), ('Özdoğan', 'last_name'), ('İzmir', 'city'), ('İzmir Police Headquarters', 'organization_name'), ('İzmir State Security Court', 'court_name')] raw=[{'original': '66689/01', 'label': 'application_number', 'synthetic': '74231/07'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '2 December 2005'}, {'original': '14 April 2000', 'label': 'date', 'synthetic': '16 May 2001'}, {'original': '14 October 2000', 'label': 'date', 'synthetic': '18 November 2001'}, {'original': '15 December 1997', 'label': 'date', 'synthetic': '17 January 1998'}, {'original': '18 December 1997', 'label': 'date', 'synthetic': '20 February 1998'}, {'original': '19 December 1997', 'label': 'date', 'synthetic': '22 March 1998'}, {'original': '1960', 'label': 'date_of_birth', 'synthetic': '1955'}, {'original': '23 December 1997', 'label': 'date', 'synthetic': '25 April 1998'}, {'original': '23 June 1998', 'label': 'date', 'synthetic': '27 July 1999'}, {'original': '28 May 2002', 'label': 'date', 'synthetic': '30 June 2003'}, {'original': '30 November 2004', 'label': 'date', 'synthetic': '5 January 2006'}, {'original': '4 June 1998', 'label': 'date', 'synthetic': '9 July 1999'}, {'original': 'Anti-Terrorist Branch', 'label': 'organization_name', 'synthetic': 'Cybercrime Unit'}, {'original': 'Chamber', 'label': 'court_name', 'synthetic': 'Panel'}, {'original': 'Court of Cassation', 'label': 'organization_name', 'synthetic': 'Supreme Court'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court'}, {'original': 'Public Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Portugal'}, {'original': 'Revolutionary Communists’ Union of Turkey', 'label': 'organization_name', 'synthetic': 'Environmental Activists Alliance of Portugal'}, {'original': 'Second Section', 'label': 'court_name', 'synthetic': 'Third Division'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'National Security Tribunal'}, {'original': 'TIKB', 'label': 'organization_name', 'synthetic': 'EAA'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Portuguese'}, {'original': 'Türkiye İhtilalci Komünistler Birliği', 'label': 'organization_name', 'synthetic': 'Federação dos Ambientalistas de Portugal'}, {'original': 'Uşak', 'label': 'city', 'synthetic': 'Coimbra'}, {'original': 'Yıldız', 'label': 'first_name', 'synthetic': 'Rui'}, {'original': 'Yılmaz', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Z.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'adjudicator'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal scholar'}, {'original': 'three years and nine months', 'label': 'sentence_duration', 'synthetic': 'four years and two months'}, {'original': 'Özdoğan', 'label': 'last_name', 'synthetic': 'Martins'}, {'original': 'İzmir', 'label': 'city', 'synthetic': 'Porto'}, {'original': 'İzmir Police Headquarters', 'label': 'organization_name', 'synthetic': 'Porto Police Headquarters'}, {'original': 'İzmir State Security Court', 'label': 'court_name', 'synthetic': 'Porto National Security Tribunal'}] filtered=[{'original': '66689/01', 'label': 'application_number', 'synthetic': '74231/07'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '2 December 2005'}, {'original': '14 April 2000', 'label': 'date', 'synthetic': '16 May 2001'}, {'original': '14 October 2000', 'label': 'date', 'synthetic': '18 November 2001'}, {'original': '15 December 1997', 'label': 'date', 'synthetic': '17 January 1998'}, {'original': '18 December 1997', 'label': 'date', 'synthetic': '20 February 1998'}, {'original': '19 December 1997', 'label': 'date', 'synthetic': '22 March 1998'}, {'original': '1960', 'label': 'date_of_birth', 'synthetic': '1955'}, {'original': '23 December 1997', 'label': 'date', 'synthetic': '25 April 1998'}, {'original': '23 June 1998', 'label': 'date', 'synthetic': '27 July 1999'}, {'original': '28 May 2002', 'label': 'date', 'synthetic': '30 June 2003'}, {'original': '30 November 2004', 'label': 'date', 'synthetic': '5 January 2006'}, {'original': '4 June 1998', 'label': 'date', 'synthetic': '9 July 1999'}, {'original': 'Anti-Terrorist Branch', 'label': 'organization_name', 'synthetic': 'Cybercrime Unit'}, {'original': 'Chamber', 'label': 'court_name', 'synthetic': 'Panel'}, {'original': 'Court of Cassation', 'label': 'organization_name', 'synthetic': 'Supreme Court'}, {'original': 'Public Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Portugal'}, {'original': 'Revolutionary Communists’ Union of Turkey', 'label': 'organization_name', 'synthetic': 'Environmental Activists Alliance of Portugal'}, {'original': 'Second Section', 'label': 'court_name', 'synthetic': 'Third Division'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'National Security Tribunal'}, {'original': 'TIKB', 'label': 'organization_name', 'synthetic': 'EAA'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Portuguese'}, {'original': 'Türkiye İhtilalci Komünistler Birliği', 'label': 'organization_name', 'synthetic': 'Federação dos Ambientalistas de Portugal'}, {'original': 'Uşak', 'label': 'city', 'synthetic': 'Coimbra'}, {'original': 'Yıldız', 'label': 'first_name', 'synthetic': 'Rui'}, {'original': 'Yılmaz', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Z.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'adjudicator'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal scholar'}, {'original': 'three years and nine months', 'label': 'sentence_duration', 'synthetic': 'four years and two months'}, {'original': 'Özdoğan', 'label': 'last_name', 'synthetic': 'Martins'}, {'original': 'İzmir', 'label': 'city', 'synthetic': 'Porto'}, {'original': 'İzmir Police Headquarters', 'label': 'organization_name', 'synthetic': 'Porto Police Headquarters'}, {'original': 'İzmir State Security Court', 'label': 'court_name', 'synthetic': 'Porto National Security Tribunal'}]

[16:12:26] [DEBUG] Replacement map record 2a9ddd0b91dc56cfbf8fc1ae4944ce98: requested=[('12 June 2003', 'date'), ('17 December 2002', 'date'), ('1976', 'date_of_birth'), ('2 December 2002', 'date'), ('2 October', 'date'), ('21 May 2004', 'date'), ('21 October 2002', 'date'), ('22 November 2002', 'date'), ('24 October 2002', 'date'), ('25 November 2002', 'date'), ('28 May 2003', 'date'), ('28 November 2002', 'date'), ('29 November 2006', 'date'), ('3 December', 'date'), ('3 October 2002', 'date'), ('30 December 2003', 'date'), ('30 June 2003', 'date'), ('31 October 2002', 'date'), ('38007/02', 'application_number'), ('4 December', 'date'), ('4 December 2002', 'date'), ('6 April 2002', 'date'), ('Agent', 'legal_role'), ('Amnesty International', 'organization_name'), ('Artur', 'first_name'), ('Bytów', 'city'), ('European Court of Human Rights', 'organization_name'), ('Gdańsk Court of Appeal', 'court_name'), ('J.', 'first_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('President', 'legal_role'), ('President of the Fourth Section of the Court', 'legal_role'), ('Republic of Poland', 'country'), ('Słupsk Detention Centre', 'prison_detention_facility'), ('Słupsk Regional Court', 'court_name'), ('Transparency International - Polska', 'organization_name'), ('Warsiński', 'last_name'), ('Wołąsiewicz', 'last_name'), ('three years', 'sentence_duration'), ('two years and four months', 'sentence_duration')] raw=[{'original': '12 June 2003', 'label': 'date', 'synthetic': '15 July 2008'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '22 January 2009'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1982'}, {'original': '2 December 2002', 'label': 'date', 'synthetic': '5 January 2009'}, {'original': '2 October', 'label': 'date', 'synthetic': '7 November'}, {'original': '21 May 2004', 'label': 'date', 'synthetic': '30 June 2009'}, {'original': '21 October 2002', 'label': 'date', 'synthetic': '18 November 2008'}, {'original': '22 November 2002', 'label': 'date', 'synthetic': '25 December 2008'}, {'original': '24 October 2002', 'label': 'date', 'synthetic': '27 November 2008'}, {'original': '25 November 2002', 'label': 'date', 'synthetic': '28 December 2008'}, {'original': '28 May 2003', 'label': 'date', 'synthetic': '3 July 2008'}, {'original': '28 November 2002', 'label': 'date', 'synthetic': '2 January 2009'}, {'original': '29 November 2006', 'label': 'date', 'synthetic': '14 February 2011'}, {'original': '3 December', 'label': 'date', 'synthetic': '9 January'}, {'original': '3 October 2002', 'label': 'date', 'synthetic': '6 November 2008'}, {'original': '30 December 2003', 'label': 'date', 'synthetic': '12 February 2009'}, {'original': '30 June 2003', 'label': 'date', 'synthetic': '4 August 2008'}, {'original': '31 October 2002', 'label': 'date', 'synthetic': '4 December 2008'}, {'original': '4 December', 'label': 'date', 'synthetic': '10 January'}, {'original': '4 December 2002', 'label': 'date', 'synthetic': '8 January 2009'}, {'original': '6 April 2002', 'label': 'date', 'synthetic': '10 May 2008'}, {'original': '38007/02', 'label': 'application_number', 'synthetic': '45219/05'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Counsel'}, {'original': 'Amnesty International', 'label': 'organization_name', 'synthetic': 'Human Rights Watch'}, {'original': 'Artur', 'label': 'first_name', 'synthetic': 'Gábor'}, {'original': 'Bytów', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'European Court of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Court of Human Rights'}, {'original': 'Gdańsk Court of Appeal', 'label': 'court_name', 'synthetic': 'Warsaw Court of Appeal'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'President of the Fourth Section of the Court', 'label': 'legal_role', 'synthetic': 'Chief Judge of the Fourth Chamber'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Słupsk Detention Centre', 'label': 'prison_detention_facility', 'synthetic': 'Budapest Detention Center'}, {'original': 'Słupsk Regional Court', 'label': 'court_name', 'synthetic': 'Kraków Regional Court'}, {'original': 'Transparency International - Polska', 'label': 'organization_name', 'synthetic': 'Global Integrity Initiative'}, {'original': 'Warsiński', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'three years', 'label': 'sentence_duration', 'synthetic': 'five years'}, {'original': 'two years and four months', 'label': 'sentence_duration', 'synthetic': 'one year and nine months'}] filtered=[{'original': '12 June 2003', 'label': 'date', 'synthetic': '15 July 2008'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '22 January 2009'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1982'}, {'original': '2 December 2002', 'label': 'date', 'synthetic': '5 January 2009'}, {'original': '2 October', 'label': 'date', 'synthetic': '7 November'}, {'original': '21 May 2004', 'label': 'date', 'synthetic': '30 June 2009'}, {'original': '21 October 2002', 'label': 'date', 'synthetic': '18 November 2008'}, {'original': '22 November 2002', 'label': 'date', 'synthetic': '25 December 2008'}, {'original': '24 October 2002', 'label': 'date', 'synthetic': '27 November 2008'}, {'original': '25 November 2002', 'label': 'date', 'synthetic': '28 December 2008'}, {'original': '28 May 2003', 'label': 'date', 'synthetic': '3 July 2008'}, {'original': '28 November 2002', 'label': 'date', 'synthetic': '2 January 2009'}, {'original': '29 November 2006', 'label': 'date', 'synthetic': '14 February 2011'}, {'original': '3 December', 'label': 'date', 'synthetic': '9 January'}, {'original': '3 October 2002', 'label': 'date', 'synthetic': '6 November 2008'}, {'original': '30 December 2003', 'label': 'date', 'synthetic': '12 February 2009'}, {'original': '30 June 2003', 'label': 'date', 'synthetic': '4 August 2008'}, {'original': '31 October 2002', 'label': 'date', 'synthetic': '4 December 2008'}, {'original': '4 December', 'label': 'date', 'synthetic': '10 January'}, {'original': '4 December 2002', 'label': 'date', 'synthetic': '8 January 2009'}, {'original': '6 April 2002', 'label': 'date', 'synthetic': '10 May 2008'}, {'original': '38007/02', 'label': 'application_number', 'synthetic': '45219/05'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Counsel'}, {'original': 'Amnesty International', 'label': 'organization_name', 'synthetic': 'Human Rights Watch'}, {'original': 'Artur', 'label': 'first_name', 'synthetic': 'Gábor'}, {'original': 'Bytów', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'European Court of Human Rights', 'label': 'organization_name', 'synthetic': 'Inter-American Court of Human Rights'}, {'original': 'Gdańsk Court of Appeal', 'label': 'court_name', 'synthetic': 'Warsaw Court of Appeal'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'President of the Fourth Section of the Court', 'label': 'legal_role', 'synthetic': 'Chief Judge of the Fourth Chamber'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Słupsk Detention Centre', 'label': 'prison_detention_facility', 'synthetic': 'Budapest Detention Center'}, {'original': 'Słupsk Regional Court', 'label': 'court_name', 'synthetic': 'Kraków Regional Court'}, {'original': 'Transparency International - Polska', 'label': 'organization_name', 'synthetic': 'Global Integrity Initiative'}, {'original': 'Warsiński', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'three years', 'label': 'sentence_duration', 'synthetic': 'five years'}, {'original': 'two years and four months', 'label': 'sentence_duration', 'synthetic': 'one year and nine months'}]

[16:12:26] [DEBUG] Replacement map record 3ef40e2e6bfa585b974d5a7247d60e60: requested=[('1 January 2004', 'date'), ('10 August 2004', 'date'), ('10 June 2005', 'date'), ('17 October 1996', 'date'), ('19 March 2002', 'date'), ('1958', 'date_of_birth'), ('2 April 2008', 'date'), ('2 July 2004', 'date'), ('23 January 2003', 'date'), ('25 February 2005', 'date'), ('26 April 2004', 'date'), ('26 October 2004', 'date'), ('27 November 1997', 'date'), ('27 October 1996', 'date'), ('27577/04', 'application_number'), ('29 June 2001', 'date'), ('31 March 2004', 'date'), ('358,071,000 Turkish liras (TRL)', 'monetary_amount'), ('4 November 1996', 'date'), ('5 August 2002', 'date'), ('Agent', 'legal_role'), ('August 2005', 'date'), ('Bener', 'last_name'), ('Bursa', 'city'), ('Bursa Assize Court', 'court_name'), ('Bursa Enforcement Court', 'court_name'), ('Bursa Enforcement Office', 'court_name'), ('Court of Cassation', 'court_name'), ('Enforcement Court', 'court_name'), ('Hasan', 'first_name'), ('Karacabey', 'city'), ('President of the Second Section', 'legal_role'), ('Republic of Turkey', 'country'), ('TRL 479,450,000', 'monetary_amount'), ('TRL 5,727,000,000', 'monetary_amount'), ('TRL 6,022,015,000', 'monetary_amount'), ('Treasury', 'organization_name'), ('Turkish', 'nationality'), ('lawyer', 'legal_role'), ('public prosecutor', 'legal_role'), ('Şentürk', 'last_name')] raw=[{'original': '1 January 2004', 'label': 'date', 'synthetic': '12 February 2005'}, {'original': '10 August 2004', 'label': 'date', 'synthetic': '22 September 2004'}, {'original': '10 June 2005', 'label': 'date', 'synthetic': '15 July 2005'}, {'original': '17 October 1996', 'label': 'date', 'synthetic': '3 November 1996'}, {'original': '19 March 2002', 'label': 'date', 'synthetic': '25 April 2002'}, {'original': '1958', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '2 April 2008', 'label': 'date', 'synthetic': '5 May 2008'}, {'original': '2 July 2004', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '23 January 2003', 'label': 'date', 'synthetic': '28 February 2003'}, {'original': '25 February 2005', 'label': 'date', 'synthetic': '9 March 2005'}, {'original': '26 April 2004', 'label': 'date', 'synthetic': '11 May 2004'}, {'original': '26 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '27 November 1997', 'label': 'date', 'synthetic': '5 December 1997'}, {'original': '27 October 1996', 'label': 'date', 'synthetic': '9 November 1996'}, {'original': '27577/04', 'label': 'application_number', 'synthetic': '38291/07'}, {'original': '29 June 2001', 'label': 'date', 'synthetic': '15 July 2001'}, {'original': '31 March 2004', 'label': 'date', 'synthetic': '20 April 2004'}, {'original': '358,071,000 Turkish liras (TRL)', 'label': 'monetary_amount', 'synthetic': '362,845,000 Turkish liras (TRL)'}, {'original': '4 November 1996', 'label': 'date', 'synthetic': '18 December 1996'}, {'original': '5 August 2002', 'label': 'date', 'synthetic': '19 September 2002'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Representative'}, {'original': 'August 2005', 'label': 'date', 'synthetic': 'September 2005'}, {'original': 'Bener', 'label': 'last_name', 'synthetic': 'Kara'}, {'original': 'Bursa', 'label': 'city', 'synthetic': 'Izmir'}, {'original': 'Bursa Assize Court', 'label': 'court_name', 'synthetic': 'Izmir Regional Court'}, {'original': 'Bursa Enforcement Court', 'label': 'court_name', 'synthetic': 'Izmir Enforcement Tribunal'}, {'original': 'Bursa Enforcement Office', 'label': 'court_name', 'synthetic': 'Izmir Enforcement Office'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Enforcement Court', 'label': 'court_name', 'synthetic': 'Execution Tribunal'}, {'original': 'Hasan', 'label': 'first_name', 'synthetic': 'Mehmet'}, {'original': 'Karacabey', 'label': 'city', 'synthetic': 'Balıkesir'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'TRL 479,450,000', 'label': 'monetary_amount', 'synthetic': 'TRL 482,300,000'}, {'original': 'TRL 5,727,000,000', 'label': 'monetary_amount', 'synthetic': 'TRL 5,800,000,000'}, {'original': 'TRL 6,022,015,000', 'label': 'monetary_amount', 'synthetic': 'TRL 6,150,000,000'}, {'original': 'Treasury', 'label': 'organization_name', 'synthetic': 'Ministry of Finance'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'Jurist'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'State Attorney'}, {'original': 'Şentürk', 'label': 'last_name', 'synthetic': 'Yılmaz'}] filtered=[{'original': '1 January 2004', 'label': 'date', 'synthetic': '12 February 2005'}, {'original': '10 August 2004', 'label': 'date', 'synthetic': '22 September 2004'}, {'original': '10 June 2005', 'label': 'date', 'synthetic': '15 July 2005'}, {'original': '17 October 1996', 'label': 'date', 'synthetic': '3 November 1996'}, {'original': '19 March 2002', 'label': 'date', 'synthetic': '25 April 2002'}, {'original': '1958', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '2 April 2008', 'label': 'date', 'synthetic': '5 May 2008'}, {'original': '2 July 2004', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '23 January 2003', 'label': 'date', 'synthetic': '28 February 2003'}, {'original': '25 February 2005', 'label': 'date', 'synthetic': '9 March 2005'}, {'original': '26 April 2004', 'label': 'date', 'synthetic': '11 May 2004'}, {'original': '26 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '27 November 1997', 'label': 'date', 'synthetic': '5 December 1997'}, {'original': '27 October 1996', 'label': 'date', 'synthetic': '9 November 1996'}, {'original': '27577/04', 'label': 'application_number', 'synthetic': '38291/07'}, {'original': '29 June 2001', 'label': 'date', 'synthetic': '15 July 2001'}, {'original': '31 March 2004', 'label': 'date', 'synthetic': '20 April 2004'}, {'original': '358,071,000 Turkish liras (TRL)', 'label': 'monetary_amount', 'synthetic': '362,845,000 Turkish liras (TRL)'}, {'original': '4 November 1996', 'label': 'date', 'synthetic': '18 December 1996'}, {'original': '5 August 2002', 'label': 'date', 'synthetic': '19 September 2002'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Representative'}, {'original': 'August 2005', 'label': 'date', 'synthetic': 'September 2005'}, {'original': 'Bener', 'label': 'last_name', 'synthetic': 'Kara'}, {'original': 'Bursa', 'label': 'city', 'synthetic': 'Izmir'}, {'original': 'Bursa Assize Court', 'label': 'court_name', 'synthetic': 'Izmir Regional Court'}, {'original': 'Bursa Enforcement Court', 'label': 'court_name', 'synthetic': 'Izmir Enforcement Tribunal'}, {'original': 'Bursa Enforcement Office', 'label': 'court_name', 'synthetic': 'Izmir Enforcement Office'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Enforcement Court', 'label': 'court_name', 'synthetic': 'Execution Tribunal'}, {'original': 'Hasan', 'label': 'first_name', 'synthetic': 'Mehmet'}, {'original': 'Karacabey', 'label': 'city', 'synthetic': 'Balıkesir'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'TRL 479,450,000', 'label': 'monetary_amount', 'synthetic': 'TRL 482,300,000'}, {'original': 'TRL 5,727,000,000', 'label': 'monetary_amount', 'synthetic': 'TRL 5,800,000,000'}, {'original': 'TRL 6,022,015,000', 'label': 'monetary_amount', 'synthetic': 'TRL 6,150,000,000'}, {'original': 'Treasury', 'label': 'organization_name', 'synthetic': 'Ministry of Finance'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'Jurist'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'State Attorney'}, {'original': 'Şentürk', 'label': 'last_name', 'synthetic': 'Yılmaz'}]

[16:12:26] [DEBUG] Replacement map record e3546bc099e45cc5b2e63adf65160e89: requested=[('10 June 2002', 'date'), ('13 November 1995', 'date'), ('14 October 1993', 'date'), ('14 October 2002', 'date'), ('17 December 2002', 'date'), ('17 March 1997', 'date'), ('17 September 1998', 'date'), ('18 August 1995', 'date'), ('1940', 'date_of_birth'), ('20 April 1999', 'date'), ('20 August 1998', 'date'), ('24 September 2003', 'date'), ('28 December 1995', 'date'), ('29 April 2004', 'date'), ('29 March 1996', 'date'), ('30 June 2002', 'date'), ('30 November 1999', 'date'), ('38049/02', 'application_number'), ('7 June 2000', 'date'), ('8 January 2002', 'date'), ('Andreas', 'first_name'), ('Board of Appeal', 'court_name'), ('Drzewicki', 'last_name'), ('Germany', 'country'), ('Jaczewska', 'last_name'), ('K', 'first_name'), ('Kaniewski', 'last_name'), ('Köln', 'city'), ('Mayor', 'legal_role'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('Prezydent Warszawy', 'organization_name'), ('Republic of Poland', 'country'), ('S', 'first_name'), ('Samorządowe Kolegium Odwoławcze', 'court_name'), ('Self-Government Board of Appeal', 'court_name'), ('Urząd Gminy Warszawa Centrum', 'organization_name'), ('Urząd Gminy Warszawa Śródmieście', 'organization_name'), ('Warsaw', 'city'), ('Warsaw Municipality', 'organization_name'), ('Warsaw Śródmieście Municipality', 'organization_name')] raw=[{'original': '10 June 2002', 'label': 'date', 'synthetic': '12 July 2003'}, {'original': '13 November 1995', 'label': 'date', 'synthetic': '15 December 1996'}, {'original': '14 October 1993', 'label': 'date', 'synthetic': '16 September 1994'}, {'original': '14 October 2002', 'label': 'date', 'synthetic': '18 November 2003'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '20 January 2004'}, {'original': '17 March 1997', 'label': 'date', 'synthetic': '22 April 1998'}, {'original': '17 September 1998', 'label': 'date', 'synthetic': '19 October 1999'}, {'original': '18 August 1995', 'label': 'date', 'synthetic': '21 September 1996'}, {'original': '1940', 'label': 'date_of_birth', 'synthetic': '1935'}, {'original': '20 April 1999', 'label': 'date', 'synthetic': '23 May 2000'}, {'original': '20 August 1998', 'label': 'date', 'synthetic': '22 September 1999'}, {'original': '24 September 2003', 'label': 'date', 'synthetic': '27 October 2004'}, {'original': '28 December 1995', 'label': 'date', 'synthetic': '30 January 1997'}, {'original': '29 April 2004', 'label': 'date', 'synthetic': '02 May 2005'}, {'original': '29 March 1996', 'label': 'date', 'synthetic': '31 May 1997'}, {'original': '30 June 2002', 'label': 'date', 'synthetic': '02 August 2003'}, {'original': '30 November 1999', 'label': 'date', 'synthetic': '02 January 2001'}, {'original': '7 June 2000', 'label': 'date', 'synthetic': '09 July 2001'}, {'original': '8 January 2002', 'label': 'date', 'synthetic': '10 February 2003'}, {'original': '38049/02', 'label': 'application_number', 'synthetic': '45231/07'}, {'original': 'Andreas', 'label': 'first_name', 'synthetic': 'Mihály'}, {'original': 'Board of Appeal', 'label': 'court_name', 'synthetic': 'Tribunal of Review'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Szabó'}, {'original': 'K', 'label': 'first_name', 'synthetic': 'L'}, {'original': 'Kaniewski', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Köln', 'label': 'city', 'synthetic': 'Lyon'}, {'original': 'Mayor', 'label': 'legal_role', 'synthetic': 'City Council President'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Prezydent Warszawy', 'label': 'organization_name', 'synthetic': 'Budapest City Hall'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'S', 'label': 'first_name', 'synthetic': 'E'}, {'original': 'Samorządowe Kolegium Odwoławcze', 'label': 'court_name', 'synthetic': 'Központi Fellebbviteli Testület'}, {'original': 'Self-Government Board of Appeal', 'label': 'court_name', 'synthetic': 'Municipal Oversight Tribunal'}, {'original': 'Urząd Gminy Warszawa Centrum', 'label': 'organization_name', 'synthetic': 'Budapest Central Office'}, {'original': 'Urząd Gminy Warszawa Śródmieście', 'label': 'organization_name', 'synthetic': 'Budapest District I Office'}, {'original': 'Warsaw', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Warsaw Municipality', 'label': 'organization_name', 'synthetic': 'Budapest Municipality'}, {'original': 'Warsaw Śródmieście Municipality', 'label': 'organization_name', 'synthetic': 'Budapest District I Municipality'}] filtered=[{'original': '10 June 2002', 'label': 'date', 'synthetic': '12 July 2003'}, {'original': '13 November 1995', 'label': 'date', 'synthetic': '15 December 1996'}, {'original': '14 October 1993', 'label': 'date', 'synthetic': '16 September 1994'}, {'original': '14 October 2002', 'label': 'date', 'synthetic': '18 November 2003'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '20 January 2004'}, {'original': '17 March 1997', 'label': 'date', 'synthetic': '22 April 1998'}, {'original': '17 September 1998', 'label': 'date', 'synthetic': '19 October 1999'}, {'original': '18 August 1995', 'label': 'date', 'synthetic': '21 September 1996'}, {'original': '1940', 'label': 'date_of_birth', 'synthetic': '1935'}, {'original': '20 April 1999', 'label': 'date', 'synthetic': '23 May 2000'}, {'original': '20 August 1998', 'label': 'date', 'synthetic': '22 September 1999'}, {'original': '24 September 2003', 'label': 'date', 'synthetic': '27 October 2004'}, {'original': '28 December 1995', 'label': 'date', 'synthetic': '30 January 1997'}, {'original': '29 April 2004', 'label': 'date', 'synthetic': '02 May 2005'}, {'original': '29 March 1996', 'label': 'date', 'synthetic': '31 May 1997'}, {'original': '30 June 2002', 'label': 'date', 'synthetic': '02 August 2003'}, {'original': '30 November 1999', 'label': 'date', 'synthetic': '02 January 2001'}, {'original': '7 June 2000', 'label': 'date', 'synthetic': '09 July 2001'}, {'original': '8 January 2002', 'label': 'date', 'synthetic': '10 February 2003'}, {'original': '38049/02', 'label': 'application_number', 'synthetic': '45231/07'}, {'original': 'Andreas', 'label': 'first_name', 'synthetic': 'Mihály'}, {'original': 'Board of Appeal', 'label': 'court_name', 'synthetic': 'Tribunal of Review'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovács'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'France'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Szabó'}, {'original': 'K', 'label': 'first_name', 'synthetic': 'L'}, {'original': 'Kaniewski', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Köln', 'label': 'city', 'synthetic': 'Lyon'}, {'original': 'Mayor', 'label': 'legal_role', 'synthetic': 'City Council President'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Prezydent Warszawy', 'label': 'organization_name', 'synthetic': 'Budapest City Hall'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'S', 'label': 'first_name', 'synthetic': 'E'}, {'original': 'Samorządowe Kolegium Odwoławcze', 'label': 'court_name', 'synthetic': 'Központi Fellebbviteli Testület'}, {'original': 'Self-Government Board of Appeal', 'label': 'court_name', 'synthetic': 'Municipal Oversight Tribunal'}, {'original': 'Urząd Gminy Warszawa Centrum', 'label': 'organization_name', 'synthetic': 'Budapest Central Office'}, {'original': 'Urząd Gminy Warszawa Śródmieście', 'label': 'organization_name', 'synthetic': 'Budapest District I Office'}, {'original': 'Warsaw', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Warsaw Municipality', 'label': 'organization_name', 'synthetic': 'Budapest Municipality'}, {'original': 'Warsaw Śródmieście Municipality', 'label': 'organization_name', 'synthetic': 'Budapest District I Municipality'}]

[16:12:26] [DEBUG] Replacement map record c129775ad59755d881992d0b76ae51bd: requested=[('12 May 1998', 'date'), ('12 November 2002', 'date'), ('13 December 2001', 'date'), ('13 March 1998', 'date'), ('13 May 2008', 'date'), ('13 November 2003', 'date'), ('14 May 1998', 'date'), ('15 March 1998', 'date'), ('1978', 'date_of_birth'), ('2 June 2003', 'date'), ('20 March 1998', 'date'), ('25 May 1998', 'date'), ('38114/03', 'application_number'), ('5 May 2003', 'date'), ('7 May 1998', 'date'), ('8 July 2002', 'date'), ('Agent', 'legal_role'), ('Court of Cassation', 'court_name'), ('Edirne prison', 'prison_detention_facility'), ('Istanbul', 'state'), ('Istanbul State Security Court', 'court_name'), ('Kırdök', 'last_name'), ('Mehmet', 'first_name'), ('Republic of Turkey', 'country'), ('Turkish', 'nationality'), ('Zeki Doğan', 'last_name'), ('fifteen years, seven months and fifteen days', 'sentence_duration'), ('investigating judge', 'legal_role'), ('lawyer', 'legal_role'), ('lawyers', 'legal_role'), ('life imprisonment', 'sentence_duration'), ('member of an illegal organisation', 'legal_role'), ('public prosecutor', 'legal_role')] raw=[{'original': '12 May 1998', 'label': 'date', 'synthetic': '09 April 1999'}, {'original': '12 November 2002', 'label': 'date', 'synthetic': '23 October 2003'}, {'original': '13 December 2001', 'label': 'date', 'synthetic': '05 January 2002'}, {'original': '13 March 1998', 'label': 'date', 'synthetic': '27 February 1999'}, {'original': '13 May 2008', 'label': 'date', 'synthetic': '02 June 2009'}, {'original': '13 November 2003', 'label': 'date', 'synthetic': '18 December 2004'}, {'original': '14 May 1998', 'label': 'date', 'synthetic': '03 June 1999'}, {'original': '15 March 1998', 'label': 'date', 'synthetic': '22 April 1999'}, {'original': '1978', 'label': 'date_of_birth', 'synthetic': '1975'}, {'original': '2 June 2003', 'label': 'date', 'synthetic': '15 July 2004'}, {'original': '20 March 1998', 'label': 'date', 'synthetic': '11 May 1999'}, {'original': '25 May 1998', 'label': 'date', 'synthetic': '30 June 1999'}, {'original': '5 May 2003', 'label': 'date', 'synthetic': '12 August 2004'}, {'original': '7 May 1998', 'label': 'date', 'synthetic': '14 September 1999'}, {'original': '8 July 2002', 'label': 'date', 'synthetic': '19 August 2003'}, {'original': '38114/03', 'label': 'application_number', 'synthetic': '49287/07'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'delegate'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Edirne prison', 'label': 'prison_detention_facility', 'synthetic': 'Ankara Central Prison'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Ankara'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Ankara State Security Tribunal'}, {'original': 'Kırdök', 'label': 'last_name', 'synthetic': 'Acar'}, {'original': 'Mehmet', 'label': 'first_name', 'synthetic': 'Emir'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Zeki Doğan', 'label': 'last_name', 'synthetic': 'Kaya Demir'}, {'original': 'fifteen years, seven months and fifteen days', 'label': 'sentence_duration', 'synthetic': 'ten years, two months and nine days'}, {'original': 'investigating judge', 'label': 'legal_role', 'synthetic': 'reviewing magistrate'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'paralegals'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': 'twenty-three years and six months'}, {'original': 'member of an illegal organisation', 'label': 'legal_role', 'synthetic': 'affiliated with a prohibited association'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'district attorney'}] filtered=[{'original': '12 May 1998', 'label': 'date', 'synthetic': '09 April 1999'}, {'original': '12 November 2002', 'label': 'date', 'synthetic': '23 October 2003'}, {'original': '13 December 2001', 'label': 'date', 'synthetic': '05 January 2002'}, {'original': '13 March 1998', 'label': 'date', 'synthetic': '27 February 1999'}, {'original': '13 May 2008', 'label': 'date', 'synthetic': '02 June 2009'}, {'original': '13 November 2003', 'label': 'date', 'synthetic': '18 December 2004'}, {'original': '14 May 1998', 'label': 'date', 'synthetic': '03 June 1999'}, {'original': '15 March 1998', 'label': 'date', 'synthetic': '22 April 1999'}, {'original': '1978', 'label': 'date_of_birth', 'synthetic': '1975'}, {'original': '2 June 2003', 'label': 'date', 'synthetic': '15 July 2004'}, {'original': '20 March 1998', 'label': 'date', 'synthetic': '11 May 1999'}, {'original': '25 May 1998', 'label': 'date', 'synthetic': '30 June 1999'}, {'original': '5 May 2003', 'label': 'date', 'synthetic': '12 August 2004'}, {'original': '7 May 1998', 'label': 'date', 'synthetic': '14 September 1999'}, {'original': '8 July 2002', 'label': 'date', 'synthetic': '19 August 2003'}, {'original': '38114/03', 'label': 'application_number', 'synthetic': '49287/07'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'delegate'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Edirne prison', 'label': 'prison_detention_facility', 'synthetic': 'Ankara Central Prison'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Ankara'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Ankara State Security Tribunal'}, {'original': 'Kırdök', 'label': 'last_name', 'synthetic': 'Acar'}, {'original': 'Mehmet', 'label': 'first_name', 'synthetic': 'Emir'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Zeki Doğan', 'label': 'last_name', 'synthetic': 'Kaya Demir'}, {'original': 'fifteen years, seven months and fifteen days', 'label': 'sentence_duration', 'synthetic': 'ten years, two months and nine days'}, {'original': 'investigating judge', 'label': 'legal_role', 'synthetic': 'reviewing magistrate'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'paralegals'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': 'twenty-three years and six months'}, {'original': 'member of an illegal organisation', 'label': 'legal_role', 'synthetic': 'affiliated with a prohibited association'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'district attorney'}]

[16:12:26] [DEBUG] Replacement map record 27657937a83a5acfa7a2a8029e09b766: requested=[('1 February 1995', 'date'), ('1 June 1999', 'date'), ('10 April 1997', 'date'), ('10 September 1998', 'date'), ('11 March', 'date'), ('11 September', 'date'), ('16 April 1999', 'date'), ('17 July 2002', 'date'), ('17 June 1994', 'date'), ('18 June 1994', 'date'), ('1976', 'date_of_birth'), ('2 December 1998', 'date'), ('2 February', 'date'), ('21 November 1995', 'date'), ('22 November 1995', 'date'), ('23 January 2002', 'date'), ('24 August 1994', 'date'), ('26 February 1997', 'date'), ('27 February 1997', 'date'), ('27 November 1996', 'date'), ('27833/02', 'application_number'), ('28 January 1999', 'date'), ('5 June 2003', 'date'), ('5 March', 'date'), ('800,000,000 old zlotys', 'monetary_amount'), ('9 April 1997', 'date'), ('9 October 1998', 'date'), ('Agents', 'legal_role'), ('Artur', 'first_name'), ('December 1993', 'date'), ('J.', 'first_name'), ('Jaczewska', 'last_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Nowak', 'last_name'), ('Piotrków Regional Court (Sąd Wojewódzki)', 'court_name'), ('Piotrków Trybunalski', 'city'), ('Piotrków Trybunalski Regional Court', 'court_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('Powszechny Zakład Ubezpieczeń', 'organization_name'), ('President of the Fourth Section', 'legal_role'), ('R.Z.', 'last_name'), ('Republic of Poland', 'country'), ('Supreme Court', 'court_name'), ('Sąd Najwyższy', 'court_name'), ('Wołąsiewicz', 'last_name'), ('counsel', 'legal_role'), ('expert witness', 'legal_role'), ('intervener', 'legal_role'), ('seventeen', 'age'), ('trial court', 'court_name'), ('Łódź Court of Appeal (Sąd Apelacyjny)', 'court_name')] raw=[{'original': '1 February 1995', 'label': 'date', 'synthetic': '4 March 1995'}, {'original': '1 June 1999', 'label': 'date', 'synthetic': '12 July 1999'}, {'original': '10 April 1997', 'label': 'date', 'synthetic': '22 May 1997'}, {'original': '10 September 1998', 'label': 'date', 'synthetic': '15 October 1998'}, {'original': '11 March', 'label': 'date', 'synthetic': '14 April'}, {'original': '11 September', 'label': 'date', 'synthetic': '13 October'}, {'original': '16 April 1999', 'label': 'date', 'synthetic': '23 May 1999'}, {'original': '17 July 2002', 'label': 'date', 'synthetic': '19 August 2002'}, {'original': '17 June 1994', 'label': 'date', 'synthetic': '20 July 1994'}, {'original': '18 June 1994', 'label': 'date', 'synthetic': '22 July 1994'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1978'}, {'original': '2 December 1998', 'label': 'date', 'synthetic': '5 January 1999'}, {'original': '2 February', 'label': 'date', 'synthetic': '5 March'}, {'original': '21 November 1995', 'label': 'date', 'synthetic': '24 December 1995'}, {'original': '22 November 1995', 'label': 'date', 'synthetic': '25 December 1995'}, {'original': '23 January 2002', 'label': 'date', 'synthetic': '27 February 2002'}, {'original': '24 August 1994', 'label': 'date', 'synthetic': '30 September 1994'}, {'original': '26 February 1997', 'label': 'date', 'synthetic': '1 April 1997'}, {'original': '27 February 1997', 'label': 'date', 'synthetic': '2 April 1997'}, {'original': '27 November 1996', 'label': 'date', 'synthetic': '1 January 1997'}, {'original': '27833/02', 'label': 'application_number', 'synthetic': '31547/09'}, {'original': '28 January 1999', 'label': 'date', 'synthetic': '3 March 1999'}, {'original': '5 June 2003', 'label': 'date', 'synthetic': '10 July 2003'}, {'original': '5 March', 'label': 'date', 'synthetic': '8 April'}, {'original': '800,000,000 old zlotys', 'label': 'monetary_amount', 'synthetic': '650,000,000 old francs'}, {'original': '9 April 1997', 'label': 'date', 'synthetic': '12 May 1997'}, {'original': '9 October 1998', 'label': 'date', 'synthetic': '12 November 1998'}, {'original': 'Agents', 'label': 'legal_role', 'synthetic': 'delegates'}, {'original': 'Artur', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'December 1993', 'label': 'date', 'synthetic': 'January 1994'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nowicka'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Nowak', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'Piotrków Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Dresden Regional Court (Landgericht)'}, {'original': 'Piotrków Trybunalski', 'label': 'city', 'synthetic': 'Dresden'}, {'original': 'Piotrków Trybunalski Regional Court', 'label': 'court_name', 'synthetic': 'Dresden Higher Regional Court (Oberlandesgericht)'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Germany'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'German'}, {'original': 'Powszechny Zakład Ubezpieczeń', 'label': 'organization_name', 'synthetic': 'Allgemeine Versicherungsgesellschaft'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Division'}, {'original': 'R.Z.', 'label': 'last_name', 'synthetic': 'K.L.'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Federal Republic of Germany'}, {'original': 'Supreme Court', 'label': 'court_name', 'synthetic': 'Federal Supreme Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Bundesgerichtshof'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Zieliński'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'advocate'}, {'original': 'expert witness', 'label': 'legal_role', 'synthetic': 'technical consultant'}, {'original': 'intervener', 'label': 'legal_role', 'synthetic': 'third‑party participant'}, {'original': 'seventeen', 'label': 'age', 'synthetic': 'twenty'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'first-instance court'}, {'original': 'Łódź Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Munich Court of Appeal (Oberlandesgericht)'}] filtered=[{'original': '1 February 1995', 'label': 'date', 'synthetic': '4 March 1995'}, {'original': '1 June 1999', 'label': 'date', 'synthetic': '12 July 1999'}, {'original': '10 April 1997', 'label': 'date', 'synthetic': '22 May 1997'}, {'original': '10 September 1998', 'label': 'date', 'synthetic': '15 October 1998'}, {'original': '11 March', 'label': 'date', 'synthetic': '14 April'}, {'original': '11 September', 'label': 'date', 'synthetic': '13 October'}, {'original': '16 April 1999', 'label': 'date', 'synthetic': '23 May 1999'}, {'original': '17 July 2002', 'label': 'date', 'synthetic': '19 August 2002'}, {'original': '17 June 1994', 'label': 'date', 'synthetic': '20 July 1994'}, {'original': '18 June 1994', 'label': 'date', 'synthetic': '22 July 1994'}, {'original': '1976', 'label': 'date_of_birth', 'synthetic': '1978'}, {'original': '2 December 1998', 'label': 'date', 'synthetic': '5 January 1999'}, {'original': '2 February', 'label': 'date', 'synthetic': '5 March'}, {'original': '21 November 1995', 'label': 'date', 'synthetic': '24 December 1995'}, {'original': '22 November 1995', 'label': 'date', 'synthetic': '25 December 1995'}, {'original': '23 January 2002', 'label': 'date', 'synthetic': '27 February 2002'}, {'original': '24 August 1994', 'label': 'date', 'synthetic': '30 September 1994'}, {'original': '26 February 1997', 'label': 'date', 'synthetic': '1 April 1997'}, {'original': '27 February 1997', 'label': 'date', 'synthetic': '2 April 1997'}, {'original': '27 November 1996', 'label': 'date', 'synthetic': '1 January 1997'}, {'original': '27833/02', 'label': 'application_number', 'synthetic': '31547/09'}, {'original': '28 January 1999', 'label': 'date', 'synthetic': '3 March 1999'}, {'original': '5 June 2003', 'label': 'date', 'synthetic': '10 July 2003'}, {'original': '5 March', 'label': 'date', 'synthetic': '8 April'}, {'original': '800,000,000 old zlotys', 'label': 'monetary_amount', 'synthetic': '650,000,000 old francs'}, {'original': '9 April 1997', 'label': 'date', 'synthetic': '12 May 1997'}, {'original': '9 October 1998', 'label': 'date', 'synthetic': '12 November 1998'}, {'original': 'Agents', 'label': 'legal_role', 'synthetic': 'delegates'}, {'original': 'Artur', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'December 1993', 'label': 'date', 'synthetic': 'January 1994'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nowicka'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Nowak', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'Piotrków Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Dresden Regional Court (Landgericht)'}, {'original': 'Piotrków Trybunalski', 'label': 'city', 'synthetic': 'Dresden'}, {'original': 'Piotrków Trybunalski Regional Court', 'label': 'court_name', 'synthetic': 'Dresden Higher Regional Court (Oberlandesgericht)'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Germany'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'German'}, {'original': 'Powszechny Zakład Ubezpieczeń', 'label': 'organization_name', 'synthetic': 'Allgemeine Versicherungsgesellschaft'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Division'}, {'original': 'R.Z.', 'label': 'last_name', 'synthetic': 'K.L.'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Federal Republic of Germany'}, {'original': 'Supreme Court', 'label': 'court_name', 'synthetic': 'Federal Supreme Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Bundesgerichtshof'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Zieliński'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'advocate'}, {'original': 'expert witness', 'label': 'legal_role', 'synthetic': 'technical consultant'}, {'original': 'intervener', 'label': 'legal_role', 'synthetic': 'third‑party participant'}, {'original': 'seventeen', 'label': 'age', 'synthetic': 'twenty'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'first-instance court'}, {'original': 'Łódź Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Munich Court of Appeal (Oberlandesgericht)'}]

[16:12:26] [DEBUG] Replacement map record 06e98d09960b51f0bc1a104d2f7150fd: requested=[('13 February 2008', 'date'), ('17 June 2004', 'date'), ('19 June 2000', 'date'), ('19 October 2006', 'date'), ('1950', 'date_of_birth'), ('20 February 2001', 'date'), ('20 July 2005', 'date'), ('2001', 'date'), ('2002', 'date'), ('2003', 'date'), ('2004', 'date'), ('2005', 'date'), ('23 June 2008', 'date'), ('30 March 2004', 'date'), ('30279/07', 'application_number'), ('31 January 2007', 'date'), ('31 May 2005', 'date'), ('4 July 2007', 'date'), ('Adam', 'first_name'), ('Agent', 'legal_role'), ('Court of Appeal', 'court_name'), ('July 2005', 'date'), ('Katowice Court of Appeal', 'court_name'), ('Katowice District Court', 'court_name'), ('Katowice District Prosecutor', 'court_name'), ('Katowice Regional Court', 'court_name'), ('Kraków', 'city'), ('Matoń', 'last_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('PLN 10,000', 'monetary_amount'), ('Polish', 'nationality'), ('Polish Government', 'organization_name'), ('President of the Fourth Section', 'legal_role'), ('Republic of Poland', 'country'), ('Wołąsiewicz', 'last_name'), ('assessors', 'legal_role'), ('defence lawyers', 'legal_role'), ('experts', 'legal_role'), ('judge', 'legal_role'), ('judges', 'legal_role')] raw=[{'original': '13 February 2008', 'label': 'date', 'synthetic': '14 March 2009'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '22 August 2005'}, {'original': '19 June 2000', 'label': 'date', 'synthetic': '5 May 1999'}, {'original': '19 October 2006', 'label': 'date', 'synthetic': '2 November 2007'}, {'original': '1950', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '20 February 2001', 'label': 'date', 'synthetic': '12 January 2002'}, {'original': '20 July 2005', 'label': 'date', 'synthetic': '15 August 2006'}, {'original': '2001', 'label': 'date', 'synthetic': '2006'}, {'original': '2002', 'label': 'date', 'synthetic': '2007'}, {'original': '2003', 'label': 'date', 'synthetic': '2008'}, {'original': '2004', 'label': 'date', 'synthetic': '2009'}, {'original': '2005', 'label': 'date', 'synthetic': '2010'}, {'original': '23 June 2008', 'label': 'date', 'synthetic': '30 July 2009'}, {'original': '30 March 2004', 'label': 'date', 'synthetic': '18 April 2005'}, {'original': '30279/07', 'label': 'application_number', 'synthetic': '41584/09'}, {'original': '31 January 2007', 'label': 'date', 'synthetic': '9 February 2008'}, {'original': '31 May 2005', 'label': 'date', 'synthetic': '12 June 2006'}, {'original': '4 July 2007', 'label': 'date', 'synthetic': '11 August 2008'}, {'original': 'Adam', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Liaison'}, {'original': 'Court of Appeal', 'label': 'court_name', 'synthetic': 'Supreme Court of Justice'}, {'original': 'July 2005', 'label': 'date', 'synthetic': 'August 2006'}, {'original': 'Katowice Court of Appeal', 'label': 'court_name', 'synthetic': 'Wrocław Court of Appeal'}, {'original': 'Katowice District Court', 'label': 'court_name', 'synthetic': 'Gdańsk District Court'}, {'original': 'Katowice District Prosecutor', 'label': 'court_name', 'synthetic': 'Łódź District Prosecutor'}, {'original': 'Katowice Regional Court', 'label': 'court_name', 'synthetic': 'Poznań Regional Court'}, {'original': 'Kraków', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Matoń', 'label': 'last_name', 'synthetic': 'Nowak'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'PLN 10,000', 'label': 'monetary_amount', 'synthetic': 'EUR 12,500'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kowalczyk'}, {'original': 'assessors', 'label': 'legal_role', 'synthetic': 'consultants'}, {'original': 'defence lawyers', 'label': 'legal_role', 'synthetic': 'prosecutorial attorneys'}, {'original': 'experts', 'label': 'legal_role', 'synthetic': 'specialists'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'magistrate'}, {'original': 'judges', 'label': 'legal_role', 'synthetic': 'tribunal members'}] filtered=[{'original': '13 February 2008', 'label': 'date', 'synthetic': '14 March 2009'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '22 August 2005'}, {'original': '19 June 2000', 'label': 'date', 'synthetic': '5 May 1999'}, {'original': '19 October 2006', 'label': 'date', 'synthetic': '2 November 2007'}, {'original': '1950', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '20 February 2001', 'label': 'date', 'synthetic': '12 January 2002'}, {'original': '20 July 2005', 'label': 'date', 'synthetic': '15 August 2006'}, {'original': '2001', 'label': 'date', 'synthetic': '2006'}, {'original': '2002', 'label': 'date', 'synthetic': '2007'}, {'original': '2003', 'label': 'date', 'synthetic': '2008'}, {'original': '2004', 'label': 'date', 'synthetic': '2009'}, {'original': '2005', 'label': 'date', 'synthetic': '2010'}, {'original': '23 June 2008', 'label': 'date', 'synthetic': '30 July 2009'}, {'original': '30 March 2004', 'label': 'date', 'synthetic': '18 April 2005'}, {'original': '30279/07', 'label': 'application_number', 'synthetic': '41584/09'}, {'original': '31 January 2007', 'label': 'date', 'synthetic': '9 February 2008'}, {'original': '31 May 2005', 'label': 'date', 'synthetic': '12 June 2006'}, {'original': '4 July 2007', 'label': 'date', 'synthetic': '11 August 2008'}, {'original': 'Adam', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Liaison'}, {'original': 'Court of Appeal', 'label': 'court_name', 'synthetic': 'Supreme Court of Justice'}, {'original': 'July 2005', 'label': 'date', 'synthetic': 'August 2006'}, {'original': 'Katowice Court of Appeal', 'label': 'court_name', 'synthetic': 'Wrocław Court of Appeal'}, {'original': 'Katowice District Court', 'label': 'court_name', 'synthetic': 'Gdańsk District Court'}, {'original': 'Katowice District Prosecutor', 'label': 'court_name', 'synthetic': 'Łódź District Prosecutor'}, {'original': 'Katowice Regional Court', 'label': 'court_name', 'synthetic': 'Poznań Regional Court'}, {'original': 'Kraków', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Matoń', 'label': 'last_name', 'synthetic': 'Nowak'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'PLN 10,000', 'label': 'monetary_amount', 'synthetic': 'EUR 12,500'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kowalczyk'}, {'original': 'assessors', 'label': 'legal_role', 'synthetic': 'consultants'}, {'original': 'defence lawyers', 'label': 'legal_role', 'synthetic': 'prosecutorial attorneys'}, {'original': 'experts', 'label': 'legal_role', 'synthetic': 'specialists'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'magistrate'}, {'original': 'judges', 'label': 'legal_role', 'synthetic': 'tribunal members'}]

[16:12:26] [DEBUG] Replacement map record bdc2d7967ebc56ee9d5575a0d9d89f97: requested=[('1 May 1993', 'date'), ('10 September 2002', 'date'), ('15 February 1991', 'date'), ('16 October 1978', 'date'), ('19 July 1966', 'date'), ('19 July 1993', 'date'), ('19 September 1997', 'date'), ('1919', 'date_of_birth'), ('1982', 'date'), ('2 December 1990', 'date'), ('2 October 1996', 'date'), ('20 December 2000', 'date'), ('21 January 2001', 'date'), ('23 October 1995', 'date'), ('25 June 2001', 'date'), ('27 January 2000', 'date'), ('28 April 1999', 'date'), ('29 January 2002', 'date'), ('29 May 1995', 'date'), ('30 May 1979', 'date'), ('4 February 1998', 'date'), ('5 January 1994', 'date'), ('5 June 1997', 'date'), ('5 November 1975', 'date'), ('6 September', 'date'), ('6214/02', 'application_number'), ('A.', 'first_name'), ('Agents', 'legal_role'), ('Bydgoszcz', 'city'), ('Bydgoszcz District Court', 'court_name'), ('Bydgoszcz District Court (Sąd Rejonowy)', 'court_name'), ('Bydgoszcz Regional Court', 'court_name'), ('Bydgoszcz Regional Court (Sąd Wojewódzki)', 'court_name'), ('District Court', 'court_name'), ('Drzewicki', 'last_name'), ('E.H.', 'first_name'), ('Edmund', 'first_name'), ('H.', 'last_name'), ('J.', 'first_name'), ('K.', 'first_name'), ('Kranz', 'last_name'), ('Minister of Justice', 'legal_role'), ('Ministry of Foreign Affairs', 'organization_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('President', 'legal_role'), ('Republic of Poland', 'country'), ('S.', 'last_name'), ('Supreme Court', 'court_name'), ('Sąd Najwyższy', 'court_name'), ('Sąd Okręgowy', 'court_name'), ('Wołąsiewicz', 'last_name'), ('presiding judge', 'legal_role')] raw=[{'original': '1 May 1993', 'label': 'date', 'synthetic': '3 June 1994'}, {'original': '10 September 2002', 'label': 'date', 'synthetic': '12 August 2003'}, {'original': '15 February 1991', 'label': 'date', 'synthetic': '18 March 1992'}, {'original': '16 October 1978', 'label': 'date', 'synthetic': '20 November 1979'}, {'original': '19 July 1966', 'label': 'date', 'synthetic': '22 August 1967'}, {'original': '19 July 1993', 'label': 'date', 'synthetic': '21 August 1994'}, {'original': '19 September 1997', 'label': 'date', 'synthetic': '23 October 1998'}, {'original': '1919', 'label': 'date_of_birth', 'synthetic': '1925'}, {'original': '1982', 'label': 'date', 'synthetic': '1985'}, {'original': '2 December 1990', 'label': 'date', 'synthetic': '5 January 1991'}, {'original': '2 October 1996', 'label': 'date', 'synthetic': '4 November 1997'}, {'original': '20 December 2000', 'label': 'date', 'synthetic': '22 January 2001'}, {'original': '21 January 2001', 'label': 'date', 'synthetic': '24 February 2002'}, {'original': '23 October 1995', 'label': 'date', 'synthetic': '25 November 1996'}, {'original': '25 June 2001', 'label': 'date', 'synthetic': '27 July 2002'}, {'original': '27 January 2000', 'label': 'date', 'synthetic': '30 March 2001'}, {'original': '28 April 1999', 'label': 'date', 'synthetic': '30 May 2000'}, {'original': '29 January 2002', 'label': 'date', 'synthetic': '31 March 2003'}, {'original': '29 May 1995', 'label': 'date', 'synthetic': '31 July 1996'}, {'original': '30 May 1979', 'label': 'date', 'synthetic': '1 July 1980'}, {'original': '4 February 1998', 'label': 'date', 'synthetic': '6 March 1999'}, {'original': '5 January 1994', 'label': 'date', 'synthetic': '7 February 1995'}, {'original': '5 June 1997', 'label': 'date', 'synthetic': '8 July 1998'}, {'original': '5 November 1975', 'label': 'date', 'synthetic': '7 December 1976'}, {'original': '6 September', 'label': 'date', 'synthetic': '8 October'}, {'original': '6214/02', 'label': 'application_number', 'synthetic': '7345/03'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'L.'}, {'original': 'Agents', 'label': 'legal_role', 'synthetic': 'Envoys'}, {'original': 'Bydgoszcz', 'label': 'city', 'synthetic': 'Brno'}, {'original': 'Bydgoszcz District Court', 'label': 'court_name', 'synthetic': 'Brno District Court'}, {'original': 'Bydgoszcz District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Brno District Court (Sąd Rejonowy)'}, {'original': 'Bydgoszcz Regional Court', 'label': 'court_name', 'synthetic': 'Brno Regional Court'}, {'original': 'Bydgoszcz Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Brno Regional Court (Sąd Wojewódzki)'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Lower Court'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'E.H.', 'label': 'first_name', 'synthetic': 'T.G.'}, {'original': 'Edmund', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'H.', 'label': 'last_name', 'synthetic': 'M.'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'P.'}, {'original': 'K.', 'label': 'first_name', 'synthetic': 'V.'}, {'original': 'Kranz', 'label': 'last_name', 'synthetic': 'Novak'}, {'original': 'Minister of Justice', 'label': 'legal_role', 'synthetic': 'Chief Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of International Relations'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Czech Republic'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Czech'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Czechia'}, {'original': 'S.', 'label': 'last_name', 'synthetic': 'R.'}, {'original': 'Supreme Court', 'label': 'court_name', 'synthetic': 'High Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Sąd Vysoký'}, {'original': 'Sąd Okręgowy', 'label': 'court_name', 'synthetic': 'Sąd Okresowy'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nowakowski'}, {'original': 'presiding judge', 'label': 'legal_role', 'synthetic': 'lead magistrate'}] filtered=[{'original': '1 May 1993', 'label': 'date', 'synthetic': '3 June 1994'}, {'original': '10 September 2002', 'label': 'date', 'synthetic': '12 August 2003'}, {'original': '15 February 1991', 'label': 'date', 'synthetic': '18 March 1992'}, {'original': '16 October 1978', 'label': 'date', 'synthetic': '20 November 1979'}, {'original': '19 July 1966', 'label': 'date', 'synthetic': '22 August 1967'}, {'original': '19 July 1993', 'label': 'date', 'synthetic': '21 August 1994'}, {'original': '19 September 1997', 'label': 'date', 'synthetic': '23 October 1998'}, {'original': '1919', 'label': 'date_of_birth', 'synthetic': '1925'}, {'original': '1982', 'label': 'date', 'synthetic': '1985'}, {'original': '2 December 1990', 'label': 'date', 'synthetic': '5 January 1991'}, {'original': '2 October 1996', 'label': 'date', 'synthetic': '4 November 1997'}, {'original': '20 December 2000', 'label': 'date', 'synthetic': '22 January 2001'}, {'original': '21 January 2001', 'label': 'date', 'synthetic': '24 February 2002'}, {'original': '23 October 1995', 'label': 'date', 'synthetic': '25 November 1996'}, {'original': '25 June 2001', 'label': 'date', 'synthetic': '27 July 2002'}, {'original': '27 January 2000', 'label': 'date', 'synthetic': '30 March 2001'}, {'original': '28 April 1999', 'label': 'date', 'synthetic': '30 May 2000'}, {'original': '29 January 2002', 'label': 'date', 'synthetic': '31 March 2003'}, {'original': '29 May 1995', 'label': 'date', 'synthetic': '31 July 1996'}, {'original': '30 May 1979', 'label': 'date', 'synthetic': '1 July 1980'}, {'original': '4 February 1998', 'label': 'date', 'synthetic': '6 March 1999'}, {'original': '5 January 1994', 'label': 'date', 'synthetic': '7 February 1995'}, {'original': '5 June 1997', 'label': 'date', 'synthetic': '8 July 1998'}, {'original': '5 November 1975', 'label': 'date', 'synthetic': '7 December 1976'}, {'original': '6 September', 'label': 'date', 'synthetic': '8 October'}, {'original': '6214/02', 'label': 'application_number', 'synthetic': '7345/03'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'L.'}, {'original': 'Agents', 'label': 'legal_role', 'synthetic': 'Envoys'}, {'original': 'Bydgoszcz', 'label': 'city', 'synthetic': 'Brno'}, {'original': 'Bydgoszcz District Court', 'label': 'court_name', 'synthetic': 'Brno District Court'}, {'original': 'Bydgoszcz District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Brno District Court (Sąd Rejonowy)'}, {'original': 'Bydgoszcz Regional Court', 'label': 'court_name', 'synthetic': 'Brno Regional Court'}, {'original': 'Bydgoszcz Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Brno Regional Court (Sąd Wojewódzki)'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Lower Court'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'E.H.', 'label': 'first_name', 'synthetic': 'T.G.'}, {'original': 'Edmund', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'H.', 'label': 'last_name', 'synthetic': 'M.'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'P.'}, {'original': 'K.', 'label': 'first_name', 'synthetic': 'V.'}, {'original': 'Kranz', 'label': 'last_name', 'synthetic': 'Novak'}, {'original': 'Minister of Justice', 'label': 'legal_role', 'synthetic': 'Chief Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of International Relations'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Czech Republic'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Czech'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Czechia'}, {'original': 'S.', 'label': 'last_name', 'synthetic': 'R.'}, {'original': 'Supreme Court', 'label': 'court_name', 'synthetic': 'High Court'}, {'original': 'Sąd Najwyższy', 'label': 'court_name', 'synthetic': 'Sąd Vysoký'}, {'original': 'Sąd Okręgowy', 'label': 'court_name', 'synthetic': 'Sąd Okresowy'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nowakowski'}, {'original': 'presiding judge', 'label': 'legal_role', 'synthetic': 'lead magistrate'}]

[16:12:26] [DEBUG] Replacement map record 404e7238c6ff5f3bb5963db133da8f50: requested=[('10 August 2000', 'date'), ('10 July 2003', 'date'), ('11 June 2002', 'date'), ('13 December 2002', 'date'), ('14 November 1997', 'date'), ('15 April 2002', 'date'), ('18 June 2004', 'date'), ('1948', 'date_of_birth'), ('2001', 'date'), ('21 November 1997', 'date'), ('22 December 2003', 'date'), ('245,000 euros (EUR)', 'monetary_amount'), ('28 March 2008', 'date'), ('3 December 2001', 'date'), ('3 October 1997', 'date'), ('41721/04', 'application_number'), ('5 February 1996', 'date'), ('5 June 2001', 'date'), ('7 July 1988', 'date'), ('Agent', 'legal_role'), ('Armen', 'first_name'), ('Bakar', 'last_name'), ('Court of Cassation', 'court_name'), ('Deryan', 'last_name'), ('Diran', 'first_name'), ('EUR 45,000', 'monetary_amount'), ('Greece', 'country'), ('Greek', 'nationality'), ('Greek Government', 'organization_name'), ('Gövderelioğlu', 'last_name'), ('Istanbul', 'city'), ('Istanbul Bankruptcy Office', 'court_name'), ('Kallithea-Attaki', 'city'), ('President of the Second Section', 'legal_role'), ('Republic of Turkey', 'country'), ('Serkis', 'first_name'), ('Turkish', 'nationality'), ('applicant', 'legal_role'), ('experts', 'legal_role'), ('lawyer', 'legal_role'), ('Şişli Court', 'court_name'), ('Şişli Court of First Instance', 'court_name')] raw=[{'original': '10 August 2000', 'label': 'date', 'synthetic': '12 September 2001'}, {'original': '10 July 2003', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '11 June 2002', 'label': 'date', 'synthetic': '15 July 2003'}, {'original': '13 December 2002', 'label': 'date', 'synthetic': '17 January 2004'}, {'original': '14 November 1997', 'label': 'date', 'synthetic': '19 December 1998'}, {'original': '15 April 2002', 'label': 'date', 'synthetic': '20 May 2003'}, {'original': '18 June 2004', 'label': 'date', 'synthetic': '22 July 2005'}, {'original': '1948', 'label': 'date_of_birth', 'synthetic': '1952'}, {'original': '2001', 'label': 'date', 'synthetic': '2005'}, {'original': '21 November 1997', 'label': 'date', 'synthetic': '25 December 1998'}, {'original': '22 December 2003', 'label': 'date', 'synthetic': '26 January 2005'}, {'original': '245,000 euros (EUR)', 'label': 'monetary_amount', 'synthetic': '312,500 dollars (USD)'}, {'original': '28 March 2008', 'label': 'date', 'synthetic': '02 April 2009'}, {'original': '3 December 2001', 'label': 'date', 'synthetic': '07 January 2003'}, {'original': '3 October 1997', 'label': 'date', 'synthetic': '08 November 1998'}, {'original': '41721/04', 'label': 'application_number', 'synthetic': '52834/07'}, {'original': '5 February 1996', 'label': 'date', 'synthetic': '10 March 1997'}, {'original': '5 June 2001', 'label': 'date', 'synthetic': '11 July 2002'}, {'original': '7 July 1988', 'label': 'date', 'synthetic': '13 August 1989'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Envoy'}, {'original': 'Armen', 'label': 'first_name', 'synthetic': 'Nikolas'}, {'original': 'Bakar', 'label': 'last_name', 'synthetic': 'Marinos'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'High Tribunal'}, {'original': 'Deryan', 'label': 'last_name', 'synthetic': 'Papadakis'}, {'original': 'Diran', 'label': 'first_name', 'synthetic': 'Milanos'}, {'original': 'EUR 45,000', 'label': 'monetary_amount', 'synthetic': 'USD 62,000'}, {'original': 'Greece', 'label': 'country', 'synthetic': 'Italy'}, {'original': 'Greek', 'label': 'nationality', 'synthetic': 'Italian'}, {'original': 'Greek Government', 'label': 'organization_name', 'synthetic': 'Italian Government'}, {'original': 'Gövderelioğlu', 'label': 'last_name', 'synthetic': 'Yilmaz'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Ankara'}, {'original': 'Istanbul Bankruptcy Office', 'label': 'court_name', 'synthetic': 'Ankara Insolvency Office'}, {'original': 'Kallithea-Attaki', 'label': 'city', 'synthetic': 'Bari'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Serkis', 'label': 'first_name', 'synthetic': 'Andreas'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'applicant', 'label': 'legal_role', 'synthetic': 'claimant'}, {'original': 'experts', 'label': 'legal_role', 'synthetic': 'consultants'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'Şişli Court', 'label': 'court_name', 'synthetic': 'Kadıköy Tribunal'}, {'original': 'Şişli Court of First Instance', 'label': 'court_name', 'synthetic': 'Kadıköy Tribunal of First Instance'}] filtered=[{'original': '10 August 2000', 'label': 'date', 'synthetic': '12 September 2001'}, {'original': '10 July 2003', 'label': 'date', 'synthetic': '14 August 2004'}, {'original': '11 June 2002', 'label': 'date', 'synthetic': '15 July 2003'}, {'original': '13 December 2002', 'label': 'date', 'synthetic': '17 January 2004'}, {'original': '14 November 1997', 'label': 'date', 'synthetic': '19 December 1998'}, {'original': '15 April 2002', 'label': 'date', 'synthetic': '20 May 2003'}, {'original': '18 June 2004', 'label': 'date', 'synthetic': '22 July 2005'}, {'original': '1948', 'label': 'date_of_birth', 'synthetic': '1952'}, {'original': '2001', 'label': 'date', 'synthetic': '2005'}, {'original': '21 November 1997', 'label': 'date', 'synthetic': '25 December 1998'}, {'original': '22 December 2003', 'label': 'date', 'synthetic': '26 January 2005'}, {'original': '245,000 euros (EUR)', 'label': 'monetary_amount', 'synthetic': '312,500 dollars (USD)'}, {'original': '28 March 2008', 'label': 'date', 'synthetic': '02 April 2009'}, {'original': '3 December 2001', 'label': 'date', 'synthetic': '07 January 2003'}, {'original': '3 October 1997', 'label': 'date', 'synthetic': '08 November 1998'}, {'original': '41721/04', 'label': 'application_number', 'synthetic': '52834/07'}, {'original': '5 February 1996', 'label': 'date', 'synthetic': '10 March 1997'}, {'original': '5 June 2001', 'label': 'date', 'synthetic': '11 July 2002'}, {'original': '7 July 1988', 'label': 'date', 'synthetic': '13 August 1989'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Envoy'}, {'original': 'Armen', 'label': 'first_name', 'synthetic': 'Nikolas'}, {'original': 'Bakar', 'label': 'last_name', 'synthetic': 'Marinos'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'High Tribunal'}, {'original': 'Deryan', 'label': 'last_name', 'synthetic': 'Papadakis'}, {'original': 'Diran', 'label': 'first_name', 'synthetic': 'Milanos'}, {'original': 'EUR 45,000', 'label': 'monetary_amount', 'synthetic': 'USD 62,000'}, {'original': 'Greece', 'label': 'country', 'synthetic': 'Italy'}, {'original': 'Greek', 'label': 'nationality', 'synthetic': 'Italian'}, {'original': 'Greek Government', 'label': 'organization_name', 'synthetic': 'Italian Government'}, {'original': 'Gövderelioğlu', 'label': 'last_name', 'synthetic': 'Yilmaz'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Ankara'}, {'original': 'Istanbul Bankruptcy Office', 'label': 'court_name', 'synthetic': 'Ankara Insolvency Office'}, {'original': 'Kallithea-Attaki', 'label': 'city', 'synthetic': 'Bari'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Kingdom of Spain'}, {'original': 'Serkis', 'label': 'first_name', 'synthetic': 'Andreas'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'applicant', 'label': 'legal_role', 'synthetic': 'claimant'}, {'original': 'experts', 'label': 'legal_role', 'synthetic': 'consultants'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'Şişli Court', 'label': 'court_name', 'synthetic': 'Kadıköy Tribunal'}, {'original': 'Şişli Court of First Instance', 'label': 'court_name', 'synthetic': 'Kadıköy Tribunal of First Instance'}]

[16:12:26] [DEBUG] Replacement map record 89e17073c59a5caaabec974dbc64aaac: requested=[('10 April 1995', 'date'), ('12 March 1995', 'date'), ('13 April 1995', 'date'), ('1965', 'date_of_birth'), ('21 February 2000', 'date'), ('28 October 2000', 'date'), ('3 June 1999', 'date'), ('4 June 1999', 'date'), ('5 May 2000', 'date'), ('71354/01', 'application_number'), ('8 July 2005', 'date'), ('Court of Cassation', 'court_name'), ('Diyarbakır', 'city'), ('Diyarbakır Prison', 'prison_detention_facility'), ('Diyarbakır State Security Court', 'court_name'), ('Fehmi', 'first_name'), ('Gümüş', 'last_name'), ('Koç', 'last_name'), ('Republic of Turkey', 'country'), ('State Security Court', 'court_name'), ('Turkish', 'nationality'), ('chief public prosecutor', 'legal_role'), ('civilian judges', 'legal_role'), ('judge', 'legal_role'), ('lawyer', 'legal_role'), ('military judge', 'legal_role')] raw=[{'original': '10 April 1995', 'label': 'date', 'synthetic': '15 May 1996'}, {'original': '12 March 1995', 'label': 'date', 'synthetic': '22 February 1996'}, {'original': '13 April 1995', 'label': 'date', 'synthetic': '18 June 1996'}, {'original': '1965', 'label': 'date_of_birth', 'synthetic': '1968'}, {'original': '21 February 2000', 'label': 'date', 'synthetic': '30 March 2001'}, {'original': '28 October 2000', 'label': 'date', 'synthetic': '5 November 2001'}, {'original': '3 June 1999', 'label': 'date', 'synthetic': '12 July 2000'}, {'original': '4 June 1999', 'label': 'date', 'synthetic': '14 August 2000'}, {'original': '5 May 2000', 'label': 'date', 'synthetic': '22 September 2001'}, {'original': '8 July 2005', 'label': 'date', 'synthetic': '19 August 2006'}, {'original': '71354/01', 'label': 'application_number', 'synthetic': '84219/03'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Diyarbakır', 'label': 'city', 'synthetic': 'Bursa'}, {'original': 'Diyarbakır Prison', 'label': 'prison_detention_facility', 'synthetic': 'Bursa Detention Center'}, {'original': 'Diyarbakır State Security Court', 'label': 'court_name', 'synthetic': 'Bursa Regional Security Tribunal'}, {'original': 'Fehmi', 'label': 'first_name', 'synthetic': 'Kemal'}, {'original': 'Gümüş', 'label': 'last_name', 'synthetic': 'Demir'}, {'original': 'Koç', 'label': 'last_name', 'synthetic': 'Yılmaz'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'Regional Security Tribunal'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'chief public prosecutor', 'label': 'legal_role', 'synthetic': 'senior investigative officer'}, {'original': 'civilian judges', 'label': 'legal_role', 'synthetic': 'civilian adjudicators'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'tribunal officer'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'military judge', 'label': 'legal_role', 'synthetic': 'military tribunal officer'}] filtered=[{'original': '10 April 1995', 'label': 'date', 'synthetic': '15 May 1996'}, {'original': '12 March 1995', 'label': 'date', 'synthetic': '22 February 1996'}, {'original': '13 April 1995', 'label': 'date', 'synthetic': '18 June 1996'}, {'original': '1965', 'label': 'date_of_birth', 'synthetic': '1968'}, {'original': '21 February 2000', 'label': 'date', 'synthetic': '30 March 2001'}, {'original': '28 October 2000', 'label': 'date', 'synthetic': '5 November 2001'}, {'original': '3 June 1999', 'label': 'date', 'synthetic': '12 July 2000'}, {'original': '4 June 1999', 'label': 'date', 'synthetic': '14 August 2000'}, {'original': '5 May 2000', 'label': 'date', 'synthetic': '22 September 2001'}, {'original': '8 July 2005', 'label': 'date', 'synthetic': '19 August 2006'}, {'original': '71354/01', 'label': 'application_number', 'synthetic': '84219/03'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Diyarbakır', 'label': 'city', 'synthetic': 'Bursa'}, {'original': 'Diyarbakır Prison', 'label': 'prison_detention_facility', 'synthetic': 'Bursa Detention Center'}, {'original': 'Diyarbakır State Security Court', 'label': 'court_name', 'synthetic': 'Bursa Regional Security Tribunal'}, {'original': 'Fehmi', 'label': 'first_name', 'synthetic': 'Kemal'}, {'original': 'Gümüş', 'label': 'last_name', 'synthetic': 'Demir'}, {'original': 'Koç', 'label': 'last_name', 'synthetic': 'Yılmaz'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Greece'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'Regional Security Tribunal'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'chief public prosecutor', 'label': 'legal_role', 'synthetic': 'senior investigative officer'}, {'original': 'civilian judges', 'label': 'legal_role', 'synthetic': 'civilian adjudicators'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'tribunal officer'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'military judge', 'label': 'legal_role', 'synthetic': 'military tribunal officer'}]

[16:12:26] [DEBUG] Replacement map record 586e6e3c37c659ac9717f4d72403306c: requested=[('10 June 2010', 'date'), ('14 January 2011', 'date'), ('18152/11', 'application_number'), ('1972', 'date_of_birth'), ('2000', 'date'), ('23 October 2009', 'date'), ('24 January 2008', 'date'), ('24 July 2010', 'date'), ('25 September 2014', 'date'), ('26 April 2010', 'date'), ('27 July 2010', 'date'), ('28 January 2009', 'date'), ('3 April 2009', 'date'), ('3 March 2009', 'date'), ('8 April 2010', 'date'), ('A.', 'first_name'), ('Adana Assize Court', 'court_name'), ('Agent', 'legal_role'), ('Cerkessk City Court', 'court_name'), ('Chechen', 'nationality'), ('Chechnya', 'state'), ('Erkenov', 'last_name'), ('Gaziantep', 'city'), ('Gaziantep Assize Court', 'court_name'), ('Gaziantep Foreigners’ Removal Centre', 'prison_detention_facility'), ('Gaziantep H-Type Prison', 'prison_detention_facility'), ('Gaziantep Magistrate’s Court', 'court_name'), ('Gaziantep Removal Centre', 'prison_detention_facility'), ('Gaziantep Security Directorate', 'organization_name'), ('Istanbul', 'city'), ('Ministry', 'organization_name'), ('Ministry of the Interior', 'organization_name'), ('Ramazan', 'first_name'), ('Republic of Turkey', 'country'), ('Russia', 'country'), ('Russian', 'nationality'), ('Russian Federation', 'country'), ('Turkey', 'country'), ('Turkish', 'nationality'), ('Yılmaz', 'last_name'), ('al-Qaeda', 'organization_name'), ('governor’s office', 'legal_role'), ('lawyer', 'legal_role'), ('lawyers', 'legal_role')] raw=[{'original': '10 June 2010', 'label': 'date', 'synthetic': '15 August 2012'}, {'original': '14 January 2011', 'label': 'date', 'synthetic': '22 February 2013'}, {'original': '18152/11', 'label': 'application_number', 'synthetic': '27493/22'}, {'original': '1972', 'label': 'date_of_birth', 'synthetic': '1965'}, {'original': '2000', 'label': 'date', 'synthetic': '1998'}, {'original': '23 October 2009', 'label': 'date', 'synthetic': '11 November 2010'}, {'original': '24 January 2008', 'label': 'date', 'synthetic': '05 March 2009'}, {'original': '24 July 2010', 'label': 'date', 'synthetic': '30 September 2011'}, {'original': '25 September 2014', 'label': 'date', 'synthetic': '12 December 2015'}, {'original': '26 April 2010', 'label': 'date', 'synthetic': '03 May 2011'}, {'original': '27 July 2010', 'label': 'date', 'synthetic': '19 August 2012'}, {'original': '28 January 2009', 'label': 'date', 'synthetic': '14 February 2010'}, {'original': '3 April 2009', 'label': 'date', 'synthetic': '9 May 2009'}, {'original': '3 March 2009', 'label': 'date', 'synthetic': '17 April 2009'}, {'original': '8 April 2010', 'label': 'date', 'synthetic': '21 June 2010'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'K.'}, {'original': 'Adana Assize Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Assize Court'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'liaison'}, {'original': 'Cerkessk City Court', 'label': 'court_name', 'synthetic': 'Krakow City Court'}, {'original': 'Chechen', 'label': 'nationality', 'synthetic': 'Silesian'}, {'original': 'Chechnya', 'label': 'state', 'synthetic': 'Silesia'}, {'original': 'Erkenov', 'label': 'last_name', 'synthetic': 'Petrov'}, {'original': 'Gaziantep', 'label': 'city', 'synthetic': 'Thessaloniki'}, {'original': 'Gaziantep Assize Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Assize Court'}, {'original': 'Gaziantep Foreigners’ Removal Centre', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki Foreigners’ Removal Centre'}, {'original': 'Gaziantep H-Type Prison', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki H-Type Prison'}, {'original': 'Gaziantep Magistrate’s Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Magistrate Court'}, {'original': 'Gaziantep Removal Centre', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki Removal Centre'}, {'original': 'Gaziantep Security Directorate', 'label': 'organization_name', 'synthetic': 'Thessaloniki Security Directorate'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Athens'}, {'original': 'Ministry', 'label': 'organization_name', 'synthetic': 'Department'}, {'original': 'Ministry of the Interior', 'label': 'organization_name', 'synthetic': 'Department of the Interior'}, {'original': 'Ramazan', 'label': 'first_name', 'synthetic': 'Dmitri'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Hellenic Republic'}, {'original': 'Russia', 'label': 'country', 'synthetic': 'Poland'}, {'original': 'Russian', 'label': 'nationality', 'synthetic': 'Polish'}, {'original': 'Russian Federation', 'label': 'country', 'synthetic': 'Poland'}, {'original': 'Turkey', 'label': 'country', 'synthetic': 'Greece'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Yılmaz', 'label': 'last_name', 'synthetic': 'Kara'}, {'original': 'al-Qaeda', 'label': 'organization_name', 'synthetic': 'Boko Haram'}, {'original': 'governor’s office', 'label': 'legal_role', 'synthetic': 'provincial administration'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'legal practitioners'}] filtered=[{'original': '10 June 2010', 'label': 'date', 'synthetic': '15 August 2012'}, {'original': '14 January 2011', 'label': 'date', 'synthetic': '22 February 2013'}, {'original': '18152/11', 'label': 'application_number', 'synthetic': '27493/22'}, {'original': '1972', 'label': 'date_of_birth', 'synthetic': '1965'}, {'original': '2000', 'label': 'date', 'synthetic': '1998'}, {'original': '23 October 2009', 'label': 'date', 'synthetic': '11 November 2010'}, {'original': '24 January 2008', 'label': 'date', 'synthetic': '05 March 2009'}, {'original': '24 July 2010', 'label': 'date', 'synthetic': '30 September 2011'}, {'original': '25 September 2014', 'label': 'date', 'synthetic': '12 December 2015'}, {'original': '26 April 2010', 'label': 'date', 'synthetic': '03 May 2011'}, {'original': '27 July 2010', 'label': 'date', 'synthetic': '19 August 2012'}, {'original': '28 January 2009', 'label': 'date', 'synthetic': '14 February 2010'}, {'original': '3 April 2009', 'label': 'date', 'synthetic': '9 May 2009'}, {'original': '3 March 2009', 'label': 'date', 'synthetic': '17 April 2009'}, {'original': '8 April 2010', 'label': 'date', 'synthetic': '21 June 2010'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'K.'}, {'original': 'Adana Assize Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Assize Court'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'liaison'}, {'original': 'Cerkessk City Court', 'label': 'court_name', 'synthetic': 'Krakow City Court'}, {'original': 'Chechen', 'label': 'nationality', 'synthetic': 'Silesian'}, {'original': 'Chechnya', 'label': 'state', 'synthetic': 'Silesia'}, {'original': 'Erkenov', 'label': 'last_name', 'synthetic': 'Petrov'}, {'original': 'Gaziantep', 'label': 'city', 'synthetic': 'Thessaloniki'}, {'original': 'Gaziantep Assize Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Assize Court'}, {'original': 'Gaziantep Foreigners’ Removal Centre', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki Foreigners’ Removal Centre'}, {'original': 'Gaziantep H-Type Prison', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki H-Type Prison'}, {'original': 'Gaziantep Magistrate’s Court', 'label': 'court_name', 'synthetic': 'Thessaloniki Magistrate Court'}, {'original': 'Gaziantep Removal Centre', 'label': 'prison_detention_facility', 'synthetic': 'Thessaloniki Removal Centre'}, {'original': 'Gaziantep Security Directorate', 'label': 'organization_name', 'synthetic': 'Thessaloniki Security Directorate'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Athens'}, {'original': 'Ministry', 'label': 'organization_name', 'synthetic': 'Department'}, {'original': 'Ministry of the Interior', 'label': 'organization_name', 'synthetic': 'Department of the Interior'}, {'original': 'Ramazan', 'label': 'first_name', 'synthetic': 'Dmitri'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Hellenic Republic'}, {'original': 'Russia', 'label': 'country', 'synthetic': 'Poland'}, {'original': 'Russian', 'label': 'nationality', 'synthetic': 'Polish'}, {'original': 'Russian Federation', 'label': 'country', 'synthetic': 'Poland'}, {'original': 'Turkey', 'label': 'country', 'synthetic': 'Greece'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Yılmaz', 'label': 'last_name', 'synthetic': 'Kara'}, {'original': 'al-Qaeda', 'label': 'organization_name', 'synthetic': 'Boko Haram'}, {'original': 'governor’s office', 'label': 'legal_role', 'synthetic': 'provincial administration'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'jurist'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'legal practitioners'}]

[16:12:26] [DEBUG] Replacement map record e211c340951a5e60ae0555787a92c707: requested=[('1 March 2010', 'date'), ('10 April 2009', 'date'), ('15 February 2008', 'date'), ('15 June 1994', 'date'), ('16 July 2009', 'date'), ('17 June 2004', 'date'), ('18 January 2005', 'date'), ('1928', 'date_of_birth'), ('1999', 'date'), ('2004', 'date'), ('24 April 2006', 'date'), ('25 January 2000', 'date'), ('25 October 2004', 'date'), ('27 August 2007', 'date'), ('30 November 1995', 'date'), ('40748/09', 'application_number'), ('5 July 2006', 'date'), ('6 June 2001', 'date'), ('7 December 2007', 'date'), ('7 May 2009', 'date'), ('Agent', 'legal_role'), ('Brwinów', 'city'), ('Cichocki', 'last_name'), ('District Court', 'court_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('Polish Government', 'organization_name'), ('President', 'legal_role'), ('President of the Fourth Section', 'legal_role'), ('Regional Court', 'court_name'), ('Republic of Poland', 'country'), ('Ryszard', 'first_name'), ('Warsaw Regional Court', 'court_name'), ('Wołąsiewicz', 'last_name')] raw=[{'original': '1 March 2010', 'label': 'date', 'synthetic': '12 April 2011'}, {'original': '10 April 2009', 'label': 'date', 'synthetic': '22 May 2008'}, {'original': '15 February 2008', 'label': 'date', 'synthetic': '3 March 2009'}, {'original': '15 June 1994', 'label': 'date', 'synthetic': '27 July 1995'}, {'original': '16 July 2009', 'label': 'date', 'synthetic': '9 August 2010'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '5 July 2005'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '30 January 2006'}, {'original': '1928', 'label': 'date_of_birth', 'synthetic': '1932'}, {'original': '1999', 'label': 'date', 'synthetic': '2001'}, {'original': '2004', 'label': 'date', 'synthetic': '2006'}, {'original': '24 April 2006', 'label': 'date', 'synthetic': '13 May 2007'}, {'original': '25 January 2000', 'label': 'date', 'synthetic': '14 February 2001'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '2 November 2005'}, {'original': '27 August 2007', 'label': 'date', 'synthetic': '15 September 2008'}, {'original': '30 November 1995', 'label': 'date', 'synthetic': '8 December 1996'}, {'original': '5 July 2006', 'label': 'date', 'synthetic': '19 August 2007'}, {'original': '6 June 2001', 'label': 'date', 'synthetic': '21 July 2002'}, {'original': '7 December 2007', 'label': 'date', 'synthetic': '11 January 2009'}, {'original': '7 May 2009', 'label': 'date', 'synthetic': '18 June 2010'}, {'original': '40748/09', 'label': 'application_number', 'synthetic': '51234/12'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Counsel'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chair of the Fourth Chamber'}, {'original': 'Brwinów', 'label': 'city', 'synthetic': 'Kraków'}, {'original': 'Cichocki', 'label': 'last_name', 'synthetic': 'Nowakowski'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kowalczyk'}, {'original': 'Ryszard', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Trade'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Szeged Regional Court'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}] filtered=[{'original': '1 March 2010', 'label': 'date', 'synthetic': '12 April 2011'}, {'original': '10 April 2009', 'label': 'date', 'synthetic': '22 May 2008'}, {'original': '15 February 2008', 'label': 'date', 'synthetic': '3 March 2009'}, {'original': '15 June 1994', 'label': 'date', 'synthetic': '27 July 1995'}, {'original': '16 July 2009', 'label': 'date', 'synthetic': '9 August 2010'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '5 July 2005'}, {'original': '18 January 2005', 'label': 'date', 'synthetic': '30 January 2006'}, {'original': '1928', 'label': 'date_of_birth', 'synthetic': '1932'}, {'original': '1999', 'label': 'date', 'synthetic': '2001'}, {'original': '2004', 'label': 'date', 'synthetic': '2006'}, {'original': '24 April 2006', 'label': 'date', 'synthetic': '13 May 2007'}, {'original': '25 January 2000', 'label': 'date', 'synthetic': '14 February 2001'}, {'original': '25 October 2004', 'label': 'date', 'synthetic': '2 November 2005'}, {'original': '27 August 2007', 'label': 'date', 'synthetic': '15 September 2008'}, {'original': '30 November 1995', 'label': 'date', 'synthetic': '8 December 1996'}, {'original': '5 July 2006', 'label': 'date', 'synthetic': '19 August 2007'}, {'original': '6 June 2001', 'label': 'date', 'synthetic': '21 July 2002'}, {'original': '7 December 2007', 'label': 'date', 'synthetic': '11 January 2009'}, {'original': '7 May 2009', 'label': 'date', 'synthetic': '18 June 2010'}, {'original': '40748/09', 'label': 'application_number', 'synthetic': '51234/12'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Counsel'}, {'original': 'President', 'label': 'legal_role', 'synthetic': 'Chairperson'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chair of the Fourth Chamber'}, {'original': 'Brwinów', 'label': 'city', 'synthetic': 'Kraków'}, {'original': 'Cichocki', 'label': 'last_name', 'synthetic': 'Nowakowski'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kowalczyk'}, {'original': 'Ryszard', 'label': 'first_name', 'synthetic': 'Marek'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Trade'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'Szeged Regional Court'}, {'original': 'Warsaw Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}]

[16:12:26] [DEBUG] Replacement map record 3d74f9a49e9252c18b504a950a10aaeb: requested=[('12 June 2000', 'date'), ('14 March 1995', 'date'), ('15 May 2001', 'date'), ('17 June 2002', 'date'), ('18 February 2002', 'date'), ('1966', 'date_of_birth'), ('23 January 1994', 'date'), ('27561/02', 'application_number'), ('29 June 2005', 'date'), ('31 January 2005', 'date'), ('31 March 1994', 'date'), ('7 February 1994', 'date'), ('7 May 2004', 'date'), ('8 February 2002', 'date'), ('Altay', 'last_name'), ('Ankara', 'city'), ('Anti-Terrorist Branch', 'organization_name'), ('Court of Cassation', 'court_name'), ('Istanbul', 'city'), ('Istanbul', 'state'), ('Istanbul Assize Court', 'court_name'), ('Istanbul State Security Court', 'court_name'), ('Karakuş', 'last_name'), ('Republic of Turkey', 'country'), ('Sami', 'first_name'), ('Security Headquarters', 'organization_name'), ('Solmaz', 'last_name'), ('State Security Court', 'court_name'), ('State Security Courts', 'court_name'), ('TKP/ML', 'organization_name'), ('TKP/ML (Türkiye Komünist Partisi/Marksist Leninist', 'organization_name'), ('Turkish', 'nationality'), ('Turkish Communist Party / Marxist Leninist', 'organization_name'), ('Yolcu', 'last_name'), ('investigating judge', 'legal_role'), ('lawyer', 'legal_role'), ('lawyers', 'legal_role'), ('life imprisonment', 'sentence_duration'), ('public prosecutor', 'legal_role')] raw=[{'original': '12 June 2000', 'label': 'date', 'synthetic': '15 July 2001'}, {'original': '14 March 1995', 'label': 'date', 'synthetic': '22 April 1996'}, {'original': '15 May 2001', 'label': 'date', 'synthetic': '18 June 2002'}, {'original': '17 June 2002', 'label': 'date', 'synthetic': '20 July 2003'}, {'original': '18 February 2002', 'label': 'date', 'synthetic': '25 March 2003'}, {'original': '1966', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '23 January 1994', 'label': 'date', 'synthetic': '28 January 1995'}, {'original': '27561/02', 'label': 'application_number', 'synthetic': '48392/07'}, {'original': '29 June 2005', 'label': 'date', 'synthetic': '5 August 2006'}, {'original': '31 January 2005', 'label': 'date', 'synthetic': '12 February 2006'}, {'original': '31 March 1994', 'label': 'date', 'synthetic': '10 April 1995'}, {'original': '7 February 1994', 'label': 'date', 'synthetic': '14 March 1995'}, {'original': '7 May 2004', 'label': 'date', 'synthetic': '9 June 2005'}, {'original': '8 February 2002', 'label': 'date', 'synthetic': '16 March 2003'}, {'original': 'Altay', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Ankara', 'label': 'city', 'synthetic': 'Madrid'}, {'original': 'Anti-Terrorist Branch', 'label': 'organization_name', 'synthetic': 'Organized Crime Unit'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Barcelona'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Catalonia'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Barcelona Criminal Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Barcelona Regional Security Tribunal'}, {'original': 'Karakuş', 'label': 'last_name', 'synthetic': 'Martínez'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Spain'}, {'original': 'Sami', 'label': 'first_name', 'synthetic': 'Carlos'}, {'original': 'Security Headquarters', 'label': 'organization_name', 'synthetic': 'Intelligence Command Center'}, {'original': 'Solmaz', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'Regional Security Tribunal'}, {'original': 'State Security Courts', 'label': 'court_name', 'synthetic': 'Regional Security Tribunals'}, {'original': 'TKP/ML', 'label': 'organization_name', 'synthetic': 'ABC/XY'}, {'original': 'TKP/ML (Türkiye Komünist Partisi/Marksist Leninist', 'label': 'organization_name', 'synthetic': 'XYZ/AB (Example Party/Some Ideology'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Turkish Communist Party / Marxist Leninist', 'label': 'organization_name', 'synthetic': 'Spanish Socialist Party / Democratic'}, {'original': 'Yolcu', 'label': 'last_name', 'synthetic': 'Sánchez'}, {'original': 'investigating judge', 'label': 'legal_role', 'synthetic': 'inquiry magistrate'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'legal consultants'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': '30 years of incarceration'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'government counsel'}] filtered=[{'original': '12 June 2000', 'label': 'date', 'synthetic': '15 July 2001'}, {'original': '14 March 1995', 'label': 'date', 'synthetic': '22 April 1996'}, {'original': '15 May 2001', 'label': 'date', 'synthetic': '18 June 2002'}, {'original': '17 June 2002', 'label': 'date', 'synthetic': '20 July 2003'}, {'original': '18 February 2002', 'label': 'date', 'synthetic': '25 March 2003'}, {'original': '1966', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '23 January 1994', 'label': 'date', 'synthetic': '28 January 1995'}, {'original': '27561/02', 'label': 'application_number', 'synthetic': '48392/07'}, {'original': '29 June 2005', 'label': 'date', 'synthetic': '5 August 2006'}, {'original': '31 January 2005', 'label': 'date', 'synthetic': '12 February 2006'}, {'original': '31 March 1994', 'label': 'date', 'synthetic': '10 April 1995'}, {'original': '7 February 1994', 'label': 'date', 'synthetic': '14 March 1995'}, {'original': '7 May 2004', 'label': 'date', 'synthetic': '9 June 2005'}, {'original': '8 February 2002', 'label': 'date', 'synthetic': '16 March 2003'}, {'original': 'Altay', 'label': 'last_name', 'synthetic': 'López'}, {'original': 'Ankara', 'label': 'city', 'synthetic': 'Madrid'}, {'original': 'Anti-Terrorist Branch', 'label': 'organization_name', 'synthetic': 'Organized Crime Unit'}, {'original': 'Court of Cassation', 'label': 'court_name', 'synthetic': 'Supreme Court of Appeals'}, {'original': 'Istanbul', 'label': 'city', 'synthetic': 'Barcelona'}, {'original': 'Istanbul', 'label': 'state', 'synthetic': 'Catalonia'}, {'original': 'Istanbul Assize Court', 'label': 'court_name', 'synthetic': 'Barcelona Criminal Court'}, {'original': 'Istanbul State Security Court', 'label': 'court_name', 'synthetic': 'Barcelona Regional Security Tribunal'}, {'original': 'Karakuş', 'label': 'last_name', 'synthetic': 'Martínez'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Republic of Spain'}, {'original': 'Sami', 'label': 'first_name', 'synthetic': 'Carlos'}, {'original': 'Security Headquarters', 'label': 'organization_name', 'synthetic': 'Intelligence Command Center'}, {'original': 'Solmaz', 'label': 'last_name', 'synthetic': 'García'}, {'original': 'State Security Court', 'label': 'court_name', 'synthetic': 'Regional Security Tribunal'}, {'original': 'State Security Courts', 'label': 'court_name', 'synthetic': 'Regional Security Tribunals'}, {'original': 'TKP/ML', 'label': 'organization_name', 'synthetic': 'ABC/XY'}, {'original': 'TKP/ML (Türkiye Komünist Partisi/Marksist Leninist', 'label': 'organization_name', 'synthetic': 'XYZ/AB (Example Party/Some Ideology'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Spanish'}, {'original': 'Turkish Communist Party / Marxist Leninist', 'label': 'organization_name', 'synthetic': 'Spanish Socialist Party / Democratic'}, {'original': 'Yolcu', 'label': 'last_name', 'synthetic': 'Sánchez'}, {'original': 'investigating judge', 'label': 'legal_role', 'synthetic': 'inquiry magistrate'}, {'original': 'lawyer', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'lawyers', 'label': 'legal_role', 'synthetic': 'legal consultants'}, {'original': 'life imprisonment', 'label': 'sentence_duration', 'synthetic': '30 years of incarceration'}, {'original': 'public prosecutor', 'label': 'legal_role', 'synthetic': 'government counsel'}]

[16:12:26] [DEBUG] Replacement map record 5d29b1535cec5d219d1a9b5b00a66811: requested=[('10 November 2006', 'date'), ('17 June 2004', 'date'), ('17 October 2006', 'date'), ('18 May and 17 August 2006', 'date'), ('1972', 'date_of_birth'), ('2 September', 'date'), ('20 November 2006', 'date'), ('2004', 'date'), ('21 January 2005', 'date'), ('26 October 2004', 'date'), ('3 November 2006', 'date'), ('30 August 2007', 'date'), ('4 August 2006', 'date'), ('4 November 2004', 'date'), ('48247/06', 'application_number'), ('8 June 2004', 'date'), ('9 June 2004', 'date'), ('Agent', 'legal_role'), ('District Court', 'court_name'), ('Dublas', 'last_name'), ('Gdańsk Court of Appeal', 'court_name'), ('Gdańsk Court of Appeal (Sąd Apelacyjny)', 'court_name'), ('Gdańsk District Court', 'court_name'), ('Gdańsk District Court (Sąd Rejonowy)', 'court_name'), ('Gdańsk Regional Court', 'court_name'), ('Grzegorz', 'first_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Polish', 'nationality'), ('Polish Government', 'organization_name'), ('President of the Fourth Section', 'legal_role'), ('Pruszcz Gdański', 'city'), ('Republic of Poland', 'country'), ('Wołąsiewicz', 'last_name'), ('trial court', 'court_name'), ('two years', 'sentence_duration')] raw=[{'original': '10 November 2006', 'label': 'date', 'synthetic': '14 December 2006'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '22 July 2004'}, {'original': '17 October 2006', 'label': 'date', 'synthetic': '23 November 2006'}, {'original': '18 May and 17 August 2006', 'label': 'date', 'synthetic': '12 March and 05 July 2006'}, {'original': '1972', 'label': 'date_of_birth', 'synthetic': '1968'}, {'original': '2 September', 'label': 'date', 'synthetic': '15 September'}, {'original': '20 November 2006', 'label': 'date', 'synthetic': '27 December 2006'}, {'original': '2004', 'label': 'date', 'synthetic': '2010'}, {'original': '21 January 2005', 'label': 'date', 'synthetic': '28 February 2005'}, {'original': '26 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '3 November 2006', 'label': 'date', 'synthetic': '9 December 2006'}, {'original': '30 August 2007', 'label': 'date', 'synthetic': '5 September 2007'}, {'original': '4 August 2006', 'label': 'date', 'synthetic': '11 September 2006'}, {'original': '4 November 2004', 'label': 'date', 'synthetic': '12 December 2004'}, {'original': '48247/06', 'label': 'application_number', 'synthetic': '59312/09'}, {'original': '8 June 2004', 'label': 'date', 'synthetic': '14 July 2004'}, {'original': '9 June 2004', 'label': 'date', 'synthetic': '15 July 2004'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Representative'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'County Court'}, {'original': 'Dublas', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'Gdańsk Court of Appeal', 'label': 'court_name', 'synthetic': 'Budapest Court of Appeal'}, {'original': 'Gdańsk Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Budapest Court of Appeal (Fellebbvitel Bíróság)'}, {'original': 'Gdańsk District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'Gdańsk District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Budapest District Court (Kerületi Bíróság)'}, {'original': 'Gdańsk Regional Court', 'label': 'court_name', 'synthetic': 'Budapest Regional Court'}, {'original': 'Grzegorz', 'label': 'first_name', 'synthetic': 'László'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Hungarian Ministry of International Cooperation'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Pruszcz Gdański', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'Budapest Trial Court'}, {'original': 'two years', 'label': 'sentence_duration', 'synthetic': 'three years'}] filtered=[{'original': '10 November 2006', 'label': 'date', 'synthetic': '14 December 2006'}, {'original': '17 June 2004', 'label': 'date', 'synthetic': '22 July 2004'}, {'original': '17 October 2006', 'label': 'date', 'synthetic': '23 November 2006'}, {'original': '18 May and 17 August 2006', 'label': 'date', 'synthetic': '12 March and 05 July 2006'}, {'original': '1972', 'label': 'date_of_birth', 'synthetic': '1968'}, {'original': '2 September', 'label': 'date', 'synthetic': '15 September'}, {'original': '20 November 2006', 'label': 'date', 'synthetic': '27 December 2006'}, {'original': '2004', 'label': 'date', 'synthetic': '2010'}, {'original': '21 January 2005', 'label': 'date', 'synthetic': '28 February 2005'}, {'original': '26 October 2004', 'label': 'date', 'synthetic': '3 November 2004'}, {'original': '3 November 2006', 'label': 'date', 'synthetic': '9 December 2006'}, {'original': '30 August 2007', 'label': 'date', 'synthetic': '5 September 2007'}, {'original': '4 August 2006', 'label': 'date', 'synthetic': '11 September 2006'}, {'original': '4 November 2004', 'label': 'date', 'synthetic': '12 December 2004'}, {'original': '48247/06', 'label': 'application_number', 'synthetic': '59312/09'}, {'original': '8 June 2004', 'label': 'date', 'synthetic': '14 July 2004'}, {'original': '9 June 2004', 'label': 'date', 'synthetic': '15 July 2004'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Representative'}, {'original': 'District Court', 'label': 'court_name', 'synthetic': 'County Court'}, {'original': 'Dublas', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'Gdańsk Court of Appeal', 'label': 'court_name', 'synthetic': 'Budapest Court of Appeal'}, {'original': 'Gdańsk Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Budapest Court of Appeal (Fellebbvitel Bíróság)'}, {'original': 'Gdańsk District Court', 'label': 'court_name', 'synthetic': 'Budapest District Court'}, {'original': 'Gdańsk District Court (Sąd Rejonowy)', 'label': 'court_name', 'synthetic': 'Budapest District Court (Kerületi Bíróság)'}, {'original': 'Gdańsk Regional Court', 'label': 'court_name', 'synthetic': 'Budapest Regional Court'}, {'original': 'Grzegorz', 'label': 'first_name', 'synthetic': 'László'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Hungarian Ministry of International Cooperation'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Hungarian Government'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Pruszcz Gdański', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'Budapest Trial Court'}, {'original': 'two years', 'label': 'sentence_duration', 'synthetic': 'three years'}]

[16:12:26] [DEBUG] Replacement map record d7539447a21c5e108ef0b9c0ebbc6cc6: requested=[('11 January 2008', 'date'), ('12 February 2008', 'date'), ('12 November 2007', 'date'), ('19 December 2007', 'date'), ('19 March 2008', 'date'), ('1949', 'date_of_birth'), ('1989', 'date'), ('2 July 2008', 'date'), ('2005', 'date'), ('21 December 2007', 'date'), ('23 July 2007', 'date'), ('24 October 2007', 'date'), ('28 December 2007', 'date'), ('30 January 2007', 'date'), ('30 November 2010', 'date'), ('32602/08', 'application_number'), ('7 September 2009', 'date'), ('A.', 'first_name'), ('Agent', 'legal_role'), ('Boruc', 'last_name'), ('Constitutional Court', 'court_name'), ('Counsel', 'legal_role'), ('December 2006', 'date'), ('Germany', 'country'), ('Gutowski', 'last_name'), ('Henryk', 'first_name'), ('J.', 'first_name'), ('M.', 'first_name'), ('Majewski', 'last_name'), ('Minister of Justice', 'organization_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('Naumann', 'last_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('Poznań', 'city'), ('President of the Fourth Section', 'legal_role'), ('R.', 'first_name'), ('Reichelt', 'last_name'), ('Republic of Poland', 'country'), ('Stokłosa', 'last_name'), ('Warsaw', 'city'), ('Warsaw-Praga Północ District Court', 'court_name'), ('Warsaw-Praga Regional Court', 'court_name'), ('Warsaw-Praga Regional Prosecutor', 'legal_role'), ('Warsaw‑Praga Północ District Court', 'court_name'), ('Wołąsiewicz', 'last_name'), ('Z.', 'last_name'), ('assessor', 'legal_role'), ('assessors', 'legal_role'), ('businessman', 'legal_role'), ('counsel', 'legal_role'), ('defence counsel', 'legal_role'), ('judge', 'legal_role'), ('judge of the administrative court', 'legal_role'), ('junior judge', 'legal_role'), ('member of the Senate', 'legal_role'), ('osoba nieuprawniona', 'legal_role'), ('third counsel', 'legal_role'), ('Śmiłowo', 'city')] raw=[{'original': '11 January 2008', 'label': 'date', 'synthetic': '14 February 2011'}, {'original': '12 February 2008', 'label': 'date', 'synthetic': '23 March 2012'}, {'original': '12 November 2007', 'label': 'date', 'synthetic': '05 December 2010'}, {'original': '19 December 2007', 'label': 'date', 'synthetic': '02 January 2011'}, {'original': '19 March 2008', 'label': 'date', 'synthetic': '27 April 2012'}, {'original': '1949', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '1989', 'label': 'date', 'synthetic': '1995'}, {'original': '2 July 2008', 'label': 'date', 'synthetic': '9 August 2013'}, {'original': '2005', 'label': 'date', 'synthetic': '2011'}, {'original': '21 December 2007', 'label': 'date', 'synthetic': '30 January 2012'}, {'original': '23 July 2007', 'label': 'date', 'synthetic': '11 September 2010'}, {'original': '24 October 2007', 'label': 'date', 'synthetic': '02 November 2010'}, {'original': '28 December 2007', 'label': 'date', 'synthetic': '15 January 2012'}, {'original': '30 January 2007', 'label': 'date', 'synthetic': '18 February 2010'}, {'original': '30 November 2010', 'label': 'date', 'synthetic': '22 December 2015'}, {'original': '32602/08', 'label': 'application_number', 'synthetic': '45213/12'}, {'original': '7 September 2009', 'label': 'date', 'synthetic': '13 October 2014'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Envoy'}, {'original': 'Boruc', 'label': 'last_name', 'synthetic': 'Szymczak'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'Supreme Constitutional Tribunal'}, {'original': 'Counsel', 'label': 'legal_role', 'synthetic': 'Legal Advisor'}, {'original': 'December 2006', 'label': 'date', 'synthetic': 'January 2010'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'Austria'}, {'original': 'Gutowski', 'label': 'last_name', 'synthetic': 'Wojcik'}, {'original': 'Henryk', 'label': 'first_name', 'synthetic': 'Krzysztof'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'L.'}, {'original': 'M.', 'label': 'first_name', 'synthetic': 'P.'}, {'original': 'Majewski', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'Minister of Justice', 'label': 'organization_name', 'synthetic': 'Minister of Legal Affairs'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Naumann', 'label': 'last_name', 'synthetic': 'Klein'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Poznań', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Division'}, {'original': 'R.', 'label': 'first_name', 'synthetic': 'V.'}, {'original': 'Reichelt', 'label': 'last_name', 'synthetic': 'Zieliński'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Stokłosa', 'label': 'last_name', 'synthetic': 'Nowak'}, {'original': 'Warsaw', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Warsaw-Praga Północ District Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda District Court'}, {'original': 'Warsaw-Praga Regional Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda Regional Court'}, {'original': 'Warsaw-Praga Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Budapest-Óbuda Regional Prosecutor'}, {'original': 'Warsaw‑Praga Północ District Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda District Court'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kaczmarek'}, {'original': 'Z.', 'label': 'last_name', 'synthetic': 'M.'}, {'original': 'assessor', 'label': 'legal_role', 'synthetic': 'reviewer'}, {'original': 'assessors', 'label': 'legal_role', 'synthetic': 'reviewers'}, {'original': 'businessman', 'label': 'legal_role', 'synthetic': 'industrialist'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'defence attorney'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'magistrate'}, {'original': 'judge of the administrative court', 'label': 'legal_role', 'synthetic': 'administrative tribunal magistrate'}, {'original': 'junior judge', 'label': 'legal_role', 'synthetic': 'associate magistrate'}, {'original': 'member of the Senate', 'label': 'legal_role', 'synthetic': 'senatorial delegate'}, {'original': 'osoba nieuprawniona', 'label': 'legal_role', 'synthetic': 'osoba niekompetentna'}, {'original': 'third counsel', 'label': 'legal_role', 'synthetic': 'additional attorney'}, {'original': 'Śmiłowo', 'label': 'city', 'synthetic': 'Szeged'}] filtered=[{'original': '11 January 2008', 'label': 'date', 'synthetic': '14 February 2011'}, {'original': '12 February 2008', 'label': 'date', 'synthetic': '23 March 2012'}, {'original': '12 November 2007', 'label': 'date', 'synthetic': '05 December 2010'}, {'original': '19 December 2007', 'label': 'date', 'synthetic': '02 January 2011'}, {'original': '19 March 2008', 'label': 'date', 'synthetic': '27 April 2012'}, {'original': '1949', 'label': 'date_of_birth', 'synthetic': '1962'}, {'original': '1989', 'label': 'date', 'synthetic': '1995'}, {'original': '2 July 2008', 'label': 'date', 'synthetic': '9 August 2013'}, {'original': '2005', 'label': 'date', 'synthetic': '2011'}, {'original': '21 December 2007', 'label': 'date', 'synthetic': '30 January 2012'}, {'original': '23 July 2007', 'label': 'date', 'synthetic': '11 September 2010'}, {'original': '24 October 2007', 'label': 'date', 'synthetic': '02 November 2010'}, {'original': '28 December 2007', 'label': 'date', 'synthetic': '15 January 2012'}, {'original': '30 January 2007', 'label': 'date', 'synthetic': '18 February 2010'}, {'original': '30 November 2010', 'label': 'date', 'synthetic': '22 December 2015'}, {'original': '32602/08', 'label': 'application_number', 'synthetic': '45213/12'}, {'original': '7 September 2009', 'label': 'date', 'synthetic': '13 October 2014'}, {'original': 'A.', 'label': 'first_name', 'synthetic': 'M.'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Envoy'}, {'original': 'Boruc', 'label': 'last_name', 'synthetic': 'Szymczak'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'Supreme Constitutional Tribunal'}, {'original': 'Counsel', 'label': 'legal_role', 'synthetic': 'Legal Advisor'}, {'original': 'December 2006', 'label': 'date', 'synthetic': 'January 2010'}, {'original': 'Germany', 'label': 'country', 'synthetic': 'Austria'}, {'original': 'Gutowski', 'label': 'last_name', 'synthetic': 'Wojcik'}, {'original': 'Henryk', 'label': 'first_name', 'synthetic': 'Krzysztof'}, {'original': 'J.', 'label': 'first_name', 'synthetic': 'L.'}, {'original': 'M.', 'label': 'first_name', 'synthetic': 'P.'}, {'original': 'Majewski', 'label': 'last_name', 'synthetic': 'Kowalski'}, {'original': 'Minister of Justice', 'label': 'organization_name', 'synthetic': 'Minister of Legal Affairs'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of International Relations'}, {'original': 'Naumann', 'label': 'last_name', 'synthetic': 'Klein'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Poznań', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'President of the Fourth Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Fifth Division'}, {'original': 'R.', 'label': 'first_name', 'synthetic': 'V.'}, {'original': 'Reichelt', 'label': 'last_name', 'synthetic': 'Zieliński'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Stokłosa', 'label': 'last_name', 'synthetic': 'Nowak'}, {'original': 'Warsaw', 'label': 'city', 'synthetic': 'Budapest'}, {'original': 'Warsaw-Praga Północ District Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda District Court'}, {'original': 'Warsaw-Praga Regional Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda Regional Court'}, {'original': 'Warsaw-Praga Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Budapest-Óbuda Regional Prosecutor'}, {'original': 'Warsaw‑Praga Północ District Court', 'label': 'court_name', 'synthetic': 'Budapest-Óbuda District Court'}, {'original': 'Wołąsiewicz', 'label': 'last_name', 'synthetic': 'Kaczmarek'}, {'original': 'Z.', 'label': 'last_name', 'synthetic': 'M.'}, {'original': 'assessor', 'label': 'legal_role', 'synthetic': 'reviewer'}, {'original': 'assessors', 'label': 'legal_role', 'synthetic': 'reviewers'}, {'original': 'businessman', 'label': 'legal_role', 'synthetic': 'industrialist'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal consultant'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'defence attorney'}, {'original': 'judge', 'label': 'legal_role', 'synthetic': 'magistrate'}, {'original': 'judge of the administrative court', 'label': 'legal_role', 'synthetic': 'administrative tribunal magistrate'}, {'original': 'junior judge', 'label': 'legal_role', 'synthetic': 'associate magistrate'}, {'original': 'member of the Senate', 'label': 'legal_role', 'synthetic': 'senatorial delegate'}, {'original': 'osoba nieuprawniona', 'label': 'legal_role', 'synthetic': 'osoba niekompetentna'}, {'original': 'third counsel', 'label': 'legal_role', 'synthetic': 'additional attorney'}, {'original': 'Śmiłowo', 'label': 'city', 'synthetic': 'Szeged'}]

[16:12:26] [DEBUG] Replacement map record ce3b11d1c54c569e9d6981ec16741339: requested=[('11 July 2003', 'date'), ('15 January 1977', 'date'), ('16 June 1992', 'date'), ('17 November 1998', 'date'), ('18 June 2003', 'date'), ('1940', 'date'), ('1977', 'date'), ('21 August 1991', 'date'), ('21 July 1998', 'date'), ('21 November 2008', 'date'), ('22 February 1994', 'date'), ('29 March 2002', 'date'), ('3 May 1994', 'date'), ('3738/04', 'application_number'), ('4 February 2003', 'date'), ('4 September 2000', 'date'), ('5 November 1991', 'date'), ('7 January 2004', 'date'), ('Agent', 'legal_role'), ('Aktar', 'last_name'), ('Ankara', 'state'), ('Bozcaada', 'city'), ('Bozcaada Cadastral Court', 'court_name'), ('Court of Cassation', 'organization_name'), ('Naim', 'first_name'), ('President of the Second Section', 'legal_role'), ('Republic of Turkey', 'country'), ('Treasury', 'organization_name'), ('Turkish', 'nationality'), ('Çanakkale', 'city')] raw=[{'original': '11 July 2003', 'label': 'date', 'synthetic': '14 August 2003'}, {'original': '15 January 1977', 'label': 'date', 'synthetic': '22 February 1977'}, {'original': '16 June 1992', 'label': 'date', 'synthetic': '09 July 1992'}, {'original': '17 November 1998', 'label': 'date', 'synthetic': '03 December 1998'}, {'original': '18 June 2003', 'label': 'date', 'synthetic': '25 June 2003'}, {'original': '1940', 'label': 'date', 'synthetic': '1952'}, {'original': '1977', 'label': 'date', 'synthetic': '1983'}, {'original': '21 August 1991', 'label': 'date', 'synthetic': '14 September 1991'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '05 August 1998'}, {'original': '21 November 2008', 'label': 'date', 'synthetic': '30 December 2008'}, {'original': '22 February 1994', 'label': 'date', 'synthetic': '10 March 1994'}, {'original': '29 March 2002', 'label': 'date', 'synthetic': '12 April 2002'}, {'original': '3 May 1994', 'label': 'date', 'synthetic': '27 June 1994'}, {'original': '3738/04', 'label': 'application_number', 'synthetic': '4821/07'}, {'original': '4 February 2003', 'label': 'date', 'synthetic': '19 February 2003'}, {'original': '4 September 2000', 'label': 'date', 'synthetic': '15 October 2000'}, {'original': '5 November 1991', 'label': 'date', 'synthetic': '23 November 1991'}, {'original': '7 January 2004', 'label': 'date', 'synthetic': '13 February 2004'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Attaché'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Naim', 'label': 'first_name', 'synthetic': 'Dimitris'}, {'original': 'Aktar', 'label': 'last_name', 'synthetic': 'Papadopoulos'}, {'original': 'Ankara', 'label': 'state', 'synthetic': 'Thessaloniki'}, {'original': 'Bozcaada', 'label': 'city', 'synthetic': 'Syros'}, {'original': 'Çanakkale', 'label': 'city', 'synthetic': 'Naxos'}, {'original': 'Bozcaada Cadastral Court', 'label': 'court_name', 'synthetic': 'Macedonia Land Registry Court'}, {'original': 'Court of Cassation', 'label': 'organization_name', 'synthetic': 'Supreme Judicial Council'}, {'original': 'Treasury', 'label': 'organization_name', 'synthetic': 'National Revenue Agency'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Hellenic Republic'}] filtered=[{'original': '11 July 2003', 'label': 'date', 'synthetic': '14 August 2003'}, {'original': '15 January 1977', 'label': 'date', 'synthetic': '22 February 1977'}, {'original': '16 June 1992', 'label': 'date', 'synthetic': '09 July 1992'}, {'original': '17 November 1998', 'label': 'date', 'synthetic': '03 December 1998'}, {'original': '18 June 2003', 'label': 'date', 'synthetic': '25 June 2003'}, {'original': '1940', 'label': 'date', 'synthetic': '1952'}, {'original': '1977', 'label': 'date', 'synthetic': '1983'}, {'original': '21 August 1991', 'label': 'date', 'synthetic': '14 September 1991'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '05 August 1998'}, {'original': '21 November 2008', 'label': 'date', 'synthetic': '30 December 2008'}, {'original': '22 February 1994', 'label': 'date', 'synthetic': '10 March 1994'}, {'original': '29 March 2002', 'label': 'date', 'synthetic': '12 April 2002'}, {'original': '3 May 1994', 'label': 'date', 'synthetic': '27 June 1994'}, {'original': '3738/04', 'label': 'application_number', 'synthetic': '4821/07'}, {'original': '4 February 2003', 'label': 'date', 'synthetic': '19 February 2003'}, {'original': '4 September 2000', 'label': 'date', 'synthetic': '15 October 2000'}, {'original': '5 November 1991', 'label': 'date', 'synthetic': '23 November 1991'}, {'original': '7 January 2004', 'label': 'date', 'synthetic': '13 February 2004'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Legal Attaché'}, {'original': 'President of the Second Section', 'label': 'legal_role', 'synthetic': 'Chairperson of the Third Chamber'}, {'original': 'Naim', 'label': 'first_name', 'synthetic': 'Dimitris'}, {'original': 'Aktar', 'label': 'last_name', 'synthetic': 'Papadopoulos'}, {'original': 'Ankara', 'label': 'state', 'synthetic': 'Thessaloniki'}, {'original': 'Bozcaada', 'label': 'city', 'synthetic': 'Syros'}, {'original': 'Çanakkale', 'label': 'city', 'synthetic': 'Naxos'}, {'original': 'Bozcaada Cadastral Court', 'label': 'court_name', 'synthetic': 'Macedonia Land Registry Court'}, {'original': 'Court of Cassation', 'label': 'organization_name', 'synthetic': 'Supreme Judicial Council'}, {'original': 'Treasury', 'label': 'organization_name', 'synthetic': 'National Revenue Agency'}, {'original': 'Turkish', 'label': 'nationality', 'synthetic': 'Greek'}, {'original': 'Republic of Turkey', 'label': 'country', 'synthetic': 'Hellenic Republic'}]

[16:12:26] [DEBUG] Replacement map record 837d3b2295fa566a9d9b710a17418a74: requested=[('10 April 2001', 'date'), ('12 January', 'date'), ('13 December 2000', 'date'), ('14 June 2000', 'date'), ('15 December 1997', 'date'), ('15 November', 'date'), ('17 December 2002', 'date'), ('18 May 1999', 'date'), ('1966', 'date_of_birth'), ('1998', 'date'), ('20 June 2001', 'date'), ('20 March 2002', 'date'), ('22072/02', 'application_number'), ('23 October 1997', 'date'), ('24 May 2002', 'date'), ('24 November 1998', 'date'), ('25 May 1999', 'date'), ('25 May 2002', 'date'), ('27 September 2002', 'date'), ('30 September 2002', 'date'), ('31 January 2002', 'date'), ('4 April 2003', 'date'), ('7 September 1999', 'date'), ('8 December 1998', 'date'), ('8 September 1999', 'date'), ('Agent', 'legal_role'), ('August 1997', 'date'), ('Court of Appeal', 'court_name'), ('Częstochowa', 'city'), ('Częstochowa Regional Court', 'court_name'), ('December 1997', 'date'), ('Drzewicki', 'last_name'), ('Fourth Section', 'court_name'), ('June 1995', 'date'), ('Katowice', 'city'), ('Małasiewicz', 'last_name'), ('Ministry of the Foreign Affairs', 'organization_name'), ('PLN 85,000', 'monetary_amount'), ('Poland', 'country'), ('Polish', 'nationality'), ('Polish Government', 'organization_name'), ('Republic of Poland', 'country'), ('Social Security Board', 'organization_name'), ('Sąd Wojewódzki w Częstochowie', 'court_name'), ('Sławomir', 'first_name'), ('Zakład Ubezpieczeń Społecznych', 'organization_name'), ('defendant', 'legal_role'), ('intervener', 'legal_role'), ('trial court', 'court_name'), ('“S” assurance company', 'company_name')] raw=[{'original': '10 April 2001', 'label': 'date', 'synthetic': '22 March 2001'}, {'original': '12 January', 'label': 'date', 'synthetic': '23 February'}, {'original': '13 December 2000', 'label': 'date', 'synthetic': '05 November 2000'}, {'original': '14 June 2000', 'label': 'date', 'synthetic': '27 July 2000'}, {'original': '15 December 1997', 'label': 'date', 'synthetic': '09 October 1997'}, {'original': '15 November', 'label': 'date', 'synthetic': '02 August'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '03 January 2002'}, {'original': '18 May 1999', 'label': 'date', 'synthetic': '30 June 1999'}, {'original': '1966', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1998', 'label': 'date', 'synthetic': '2001'}, {'original': '20 June 2001', 'label': 'date', 'synthetic': '11 July 2001'}, {'original': '20 March 2002', 'label': 'date', 'synthetic': '14 April 2002'}, {'original': '22072/02', 'label': 'application_number', 'synthetic': '33184/03'}, {'original': '23 October 1997', 'label': 'date', 'synthetic': '02 September 1997'}, {'original': '24 May 2002', 'label': 'date', 'synthetic': '11 June 2002'}, {'original': '24 November 1998', 'label': 'date', 'synthetic': '05 December 1998'}, {'original': '25 May 1999', 'label': 'date', 'synthetic': '18 June 1999'}, {'original': '25 May 2002', 'label': 'date', 'synthetic': '09 July 2002'}, {'original': '27 September 2002', 'label': 'date', 'synthetic': '15 October 2002'}, {'original': '30 September 2002', 'label': 'date', 'synthetic': '08 October 2002'}, {'original': '31 January 2002', 'label': 'date', 'synthetic': '22 February 2002'}, {'original': '4 April 2003', 'label': 'date', 'synthetic': '19 May 2003'}, {'original': '7 September 1999', 'label': 'date', 'synthetic': '14 October 1999'}, {'original': '8 December 1998', 'label': 'date', 'synthetic': '21 January 1999'}, {'original': '8 September 1999', 'label': 'date', 'synthetic': '16 October 1999'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Delegate'}, {'original': 'August 1997', 'label': 'date', 'synthetic': 'July 1997'}, {'original': 'Court of Appeal', 'label': 'court_name', 'synthetic': 'Supreme Tribunal'}, {'original': 'Częstochowa', 'label': 'city', 'synthetic': 'Porto'}, {'original': 'Częstochowa Regional Court', 'label': 'court_name', 'synthetic': 'Porto Regional Court'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'November 1997'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Costa'}, {'original': 'Fourth Section', 'label': 'court_name', 'synthetic': 'Second Chamber'}, {'original': 'June 1995', 'label': 'date', 'synthetic': 'May 1995'}, {'original': 'Katowice', 'label': 'city', 'synthetic': 'Lisbon'}, {'original': 'Małasiewicz', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Ministry of the Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of Global Partnerships'}, {'original': 'PLN 85,000', 'label': 'monetary_amount', 'synthetic': 'EUR 92,500'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Portugal'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Portuguese'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Portuguese Government'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Portugal'}, {'original': 'Social Security Board', 'label': 'organization_name', 'synthetic': 'National Retirement Agency'}, {'original': 'Sąd Wojewódzki w Częstochowie', 'label': 'court_name', 'synthetic': 'Tribunal da Comarca do Porto'}, {'original': 'Sławomir', 'label': 'first_name', 'synthetic': 'Tiago'}, {'original': 'Zakład Ubezpieczeń Społecznych', 'label': 'organization_name', 'synthetic': 'Instituto de Previdência Nacional'}, {'original': 'defendant', 'label': 'legal_role', 'synthetic': 'accused'}, {'original': 'intervener', 'label': 'legal_role', 'synthetic': 'third-party participant'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'Regional Tribunal'}, {'original': '“S” assurance company', 'label': 'company_name', 'synthetic': '“T” liability corporation'}] filtered=[{'original': '10 April 2001', 'label': 'date', 'synthetic': '22 March 2001'}, {'original': '12 January', 'label': 'date', 'synthetic': '23 February'}, {'original': '13 December 2000', 'label': 'date', 'synthetic': '05 November 2000'}, {'original': '14 June 2000', 'label': 'date', 'synthetic': '27 July 2000'}, {'original': '15 December 1997', 'label': 'date', 'synthetic': '09 October 1997'}, {'original': '15 November', 'label': 'date', 'synthetic': '02 August'}, {'original': '17 December 2002', 'label': 'date', 'synthetic': '03 January 2002'}, {'original': '18 May 1999', 'label': 'date', 'synthetic': '30 June 1999'}, {'original': '1966', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1998', 'label': 'date', 'synthetic': '2001'}, {'original': '20 June 2001', 'label': 'date', 'synthetic': '11 July 2001'}, {'original': '20 March 2002', 'label': 'date', 'synthetic': '14 April 2002'}, {'original': '22072/02', 'label': 'application_number', 'synthetic': '33184/03'}, {'original': '23 October 1997', 'label': 'date', 'synthetic': '02 September 1997'}, {'original': '24 May 2002', 'label': 'date', 'synthetic': '11 June 2002'}, {'original': '24 November 1998', 'label': 'date', 'synthetic': '05 December 1998'}, {'original': '25 May 1999', 'label': 'date', 'synthetic': '18 June 1999'}, {'original': '25 May 2002', 'label': 'date', 'synthetic': '09 July 2002'}, {'original': '27 September 2002', 'label': 'date', 'synthetic': '15 October 2002'}, {'original': '30 September 2002', 'label': 'date', 'synthetic': '08 October 2002'}, {'original': '31 January 2002', 'label': 'date', 'synthetic': '22 February 2002'}, {'original': '4 April 2003', 'label': 'date', 'synthetic': '19 May 2003'}, {'original': '7 September 1999', 'label': 'date', 'synthetic': '14 October 1999'}, {'original': '8 December 1998', 'label': 'date', 'synthetic': '21 January 1999'}, {'original': '8 September 1999', 'label': 'date', 'synthetic': '16 October 1999'}, {'original': 'Agent', 'label': 'legal_role', 'synthetic': 'Delegate'}, {'original': 'August 1997', 'label': 'date', 'synthetic': 'July 1997'}, {'original': 'Court of Appeal', 'label': 'court_name', 'synthetic': 'Supreme Tribunal'}, {'original': 'Częstochowa', 'label': 'city', 'synthetic': 'Porto'}, {'original': 'Częstochowa Regional Court', 'label': 'court_name', 'synthetic': 'Porto Regional Court'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'November 1997'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Costa'}, {'original': 'Fourth Section', 'label': 'court_name', 'synthetic': 'Second Chamber'}, {'original': 'June 1995', 'label': 'date', 'synthetic': 'May 1995'}, {'original': 'Katowice', 'label': 'city', 'synthetic': 'Lisbon'}, {'original': 'Małasiewicz', 'label': 'last_name', 'synthetic': 'Silva'}, {'original': 'Ministry of the Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Department of Global Partnerships'}, {'original': 'PLN 85,000', 'label': 'monetary_amount', 'synthetic': 'EUR 92,500'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Portugal'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Portuguese'}, {'original': 'Polish Government', 'label': 'organization_name', 'synthetic': 'Portuguese Government'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Portugal'}, {'original': 'Social Security Board', 'label': 'organization_name', 'synthetic': 'National Retirement Agency'}, {'original': 'Sąd Wojewódzki w Częstochowie', 'label': 'court_name', 'synthetic': 'Tribunal da Comarca do Porto'}, {'original': 'Sławomir', 'label': 'first_name', 'synthetic': 'Tiago'}, {'original': 'Zakład Ubezpieczeń Społecznych', 'label': 'organization_name', 'synthetic': 'Instituto de Previdência Nacional'}, {'original': 'defendant', 'label': 'legal_role', 'synthetic': 'accused'}, {'original': 'intervener', 'label': 'legal_role', 'synthetic': 'third-party participant'}, {'original': 'trial court', 'label': 'court_name', 'synthetic': 'Regional Tribunal'}, {'original': '“S” assurance company', 'label': 'company_name', 'synthetic': '“T” liability corporation'}]

[16:12:26] [DEBUG] Replacement map record 46e1a5989f27571893c1167cf94e9bb1: requested=[('1 November 1998', 'date'), ('1 November 2004', 'date'), ('10 September 1994', 'date'), ('11 August 2000', 'date'), ('15 April 1999', 'date'), ('16 December 1994', 'date'), ('17 August 1998', 'date'), ('17 July 1998', 'date'), ('17 June 2003', 'date'), ('1968', 'date_of_birth'), ('1997-12-9', 'date'), ('21 July 1998', 'date'), ('21 October and 9 November 1998', 'date'), ('26 April 2001', 'date'), ('28 September 1998', 'date'), ('5 years', 'sentence_duration'), ('51895/99', 'application_number'), ('6 April 1999', 'date'), ('Bogdan', 'first_name'), ('Chamber', 'legal_role'), ('Chełm', 'city'), ('Constitutional Court', 'court_name'), ('Court', 'court_name'), ('December 1997', 'date'), ('Drzewicki', 'last_name'), ('European Commission of Human Rights', 'organization_name'), ('Jaczewska', 'last_name'), ('Kwiek', 'last_name'), ('Lublin', 'city'), ('Lublin Court of Appeal (Sąd Apelacyjny)', 'court_name'), ('Lublin Regional Court', 'court_name'), ('Lublin Regional Court (Sąd Wojewódzki)', 'court_name'), ('Lublin Regional Prosecutor', 'organization_name'), ('Ministry of Foreign Affairs', 'organization_name'), ('O.K.', 'first_name'), ('Poland', 'country'), ('Polish', 'nationality'), ('Regional Court', 'court_name'), ('Regional Prosecutor', 'legal_role'), ('Republic of Poland', 'country'), ('Supreme Court (Sąd Najwyzszy)', 'court_name'), ('beginning of December 1995', 'date'), ('counsel', 'legal_role'), ('defence counsel', 'legal_role'), ('prosecutor', 'legal_role')] raw=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 1999'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2005'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 October 1994'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 September 2000'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 May 1999'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '8 January 1995'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '30 September 1998'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '2 August 1998'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '9 August 2003'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '2002-05-14'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 1998'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '12 March and 4 April 2000'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '15 June 2001'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '10 November 1998'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '62784/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '18 May 1999'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Mihai'}, {'original': 'Chamber', 'label': 'legal_role', 'synthetic': 'Division'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'High Constitutional Tribunal'}, {'original': 'Court', 'label': 'court_name', 'synthetic': 'Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 2000'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'European Committee on Civil Liberties'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Farkas'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Debrecen Court of Appeal (Fellebbviteli Bíróság)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court (Törvényszék)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': 'Debrecen District Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'O.K.', 'label': 'first_name', 'synthetic': 'M.L.'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'District Court'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Supreme Court (Sąd Najwyzszy)', 'label': 'court_name', 'synthetic': 'High Court (Főbíróság)'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'mid-January 1996'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal aide'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigative officer'}] filtered=[{'original': '1 November 1998', 'label': 'date', 'synthetic': '3 March 1999'}, {'original': '1 November 2004', 'label': 'date', 'synthetic': '12 July 2005'}, {'original': '10 September 1994', 'label': 'date', 'synthetic': '22 October 1994'}, {'original': '11 August 2000', 'label': 'date', 'synthetic': '5 September 2000'}, {'original': '15 April 1999', 'label': 'date', 'synthetic': '27 May 1999'}, {'original': '16 December 1994', 'label': 'date', 'synthetic': '8 January 1995'}, {'original': '17 August 1998', 'label': 'date', 'synthetic': '30 September 1998'}, {'original': '17 July 1998', 'label': 'date', 'synthetic': '2 August 1998'}, {'original': '17 June 2003', 'label': 'date', 'synthetic': '9 August 2003'}, {'original': '1968', 'label': 'date_of_birth', 'synthetic': '1972'}, {'original': '1997-12-9', 'label': 'date', 'synthetic': '2002-05-14'}, {'original': '21 July 1998', 'label': 'date', 'synthetic': '14 August 1998'}, {'original': '21 October and 9 November 1998', 'label': 'date', 'synthetic': '12 March and 4 April 2000'}, {'original': '26 April 2001', 'label': 'date', 'synthetic': '15 June 2001'}, {'original': '28 September 1998', 'label': 'date', 'synthetic': '10 November 1998'}, {'original': '5 years', 'label': 'sentence_duration', 'synthetic': '7 years'}, {'original': '51895/99', 'label': 'application_number', 'synthetic': '62784/07'}, {'original': '6 April 1999', 'label': 'date', 'synthetic': '18 May 1999'}, {'original': 'Bogdan', 'label': 'first_name', 'synthetic': 'Mihai'}, {'original': 'Chamber', 'label': 'legal_role', 'synthetic': 'Division'}, {'original': 'Chełm', 'label': 'city', 'synthetic': 'Szeged'}, {'original': 'Constitutional Court', 'label': 'court_name', 'synthetic': 'High Constitutional Tribunal'}, {'original': 'Court', 'label': 'court_name', 'synthetic': 'Tribunal'}, {'original': 'December 1997', 'label': 'date', 'synthetic': 'January 2000'}, {'original': 'Drzewicki', 'label': 'last_name', 'synthetic': 'Kovacs'}, {'original': 'European Commission of Human Rights', 'label': 'organization_name', 'synthetic': 'European Committee on Civil Liberties'}, {'original': 'Jaczewska', 'label': 'last_name', 'synthetic': 'Nagy'}, {'original': 'Kwiek', 'label': 'last_name', 'synthetic': 'Farkas'}, {'original': 'Lublin', 'label': 'city', 'synthetic': 'Debrecen'}, {'original': 'Lublin Court of Appeal (Sąd Apelacyjny)', 'label': 'court_name', 'synthetic': 'Debrecen Court of Appeal (Fellebbviteli Bíróság)'}, {'original': 'Lublin Regional Court', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court'}, {'original': 'Lublin Regional Court (Sąd Wojewódzki)', 'label': 'court_name', 'synthetic': 'Debrecen Regional Court (Törvényszék)'}, {'original': 'Lublin Regional Prosecutor', 'label': 'organization_name', 'synthetic': 'Debrecen District Prosecutor'}, {'original': 'Ministry of Foreign Affairs', 'label': 'organization_name', 'synthetic': 'Ministry of Interior'}, {'original': 'O.K.', 'label': 'first_name', 'synthetic': 'M.L.'}, {'original': 'Poland', 'label': 'country', 'synthetic': 'Hungary'}, {'original': 'Polish', 'label': 'nationality', 'synthetic': 'Hungarian'}, {'original': 'Regional Court', 'label': 'court_name', 'synthetic': 'District Court'}, {'original': 'Regional Prosecutor', 'label': 'legal_role', 'synthetic': 'Chief Investigator'}, {'original': 'Republic of Poland', 'label': 'country', 'synthetic': 'Republic of Hungary'}, {'original': 'Supreme Court (Sąd Najwyzszy)', 'label': 'court_name', 'synthetic': 'High Court (Főbíróság)'}, {'original': 'beginning of December 1995', 'label': 'date', 'synthetic': 'mid-January 1996'}, {'original': 'counsel', 'label': 'legal_role', 'synthetic': 'legal aide'}, {'original': 'defence counsel', 'label': 'legal_role', 'synthetic': 'legal representative'}, {'original': 'prosecutor', 'label': 'legal_role', 'synthetic': 'investigative officer'}]

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/replace/llm_replace_workflow.py:108: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([output_df, passthrough_rows], axis=0)
[16:12:26] [DEBUG] NDD workflow 'rewrite-pipeline' starting with 24 records

[16:12:26] [DEBUG] NDD workflow 'rewrite-pipeline': 12 columns ['_domain', '_domain_supplement', '_sensitivity_disposition', '_sensitivity_disposition_block', '_meaning_units', '_meaning_units_serialized', '_quality_qa', '_privacy_qa', '_rewrite_disposition_block', '_replacement_map_for_prompt', '_full_rewrite', '_rewritten_text']

[16:12:26] [INFO] 🎨 Creating Data Designer dataset

[16:12:26] [INFO] ✅ Validation passed

[16:12:26] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:12:26] [INFO] 🩺 Running health checks for models...

[16:12:26] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[16:12:27] [INFO]   |-- ✅ Passed!

[16:12:27] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-pipeline' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-pipeline_03-31-2026_161227' instead.

[16:12:27] [INFO] ⏳ Processing batch 1 of 1

[16:12:27] [INFO] 🌱 Sampling 24 records from seed dataset

[16:12:27] [INFO]   |-- seed dataset size: 24 records

[16:12:27] [INFO]   |-- sampling strategy: ordered

[16:12:27] [INFO] 🗂️ llm-structured model config for column '_domain'

[16:12:27] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:12:27] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:12:27] [INFO]   |-- model provider: 'nvidia'

[16:12:27] [INFO]   |-- inference parameters:

[16:12:27] [INFO]   |  |-- generation_type=chat-completion

[16:12:27] [INFO]   |  |-- max_parallel_requests=2

[16:12:27] [INFO]   |  |-- timeout=300

[16:12:27] [INFO]   |  |-- temperature=0.30

[16:12:27] [INFO]   |  |-- top_p=0.95

[16:12:27] [INFO]   |  |-- max_tokens=16384

[16:12:27] [INFO] ⚡️ Processing llm-structured column '_domain' with 2 concurrent workers

[16:12:27] [INFO] ⏱️ llm-structured column '_domain' will report progress every 2 records

[16:12:28] [INFO]   |-- 🌧️ llm-structured column '_domain' progress: 2/24 (8%) complete, 2 ok, 0 failed, 2.24 rec/s, eta 9.8s

[16:12:29] [INFO]   |-- 🌧️ llm-structured column '_domain' progress: 4/24 (17%) complete, 4 ok, 0 failed, 2.36 rec/s, eta 8.5s

[16:12:29] [INFO]   |-- 🌦️ llm-structured column '_domain' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2.34 rec/s, eta 7.7s

[16:12:30] [INFO]   |-- 🌦️ llm-structured column '_domain' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2.48 rec/s, eta 6.4s

[16:12:31] [INFO]   |-- 🌦️ llm-structured column '_domain' progress: 10/24 (42%) complete, 10 ok, 0 failed, 2.53 rec/s, eta 5.5s

[16:12:31] [INFO]   |-- ⛅ llm-structured column '_domain' progress: 12/24 (50%) complete, 12 ok, 0 failed, 2.58 rec/s, eta 4.6s

[16:12:32] [INFO]   |-- ⛅ llm-structured column '_domain' progress: 14/24 (58%) complete, 14 ok, 0 failed, 2.59 rec/s, eta 3.9s

[16:12:33] [INFO]   |-- ⛅ llm-structured column '_domain' progress: 16/24 (67%) complete, 16 ok, 0 failed, 2.62 rec/s, eta 3.1s

[16:12:34] [INFO]   |-- 🌤️ llm-structured column '_domain' progress: 18/24 (75%) complete, 18 ok, 0 failed, 2.64 rec/s, eta 2.3s

[16:12:34] [INFO]   |-- 🌤️ llm-structured column '_domain' progress: 20/24 (83%) complete, 20 ok, 0 failed, 2.63 rec/s, eta 1.5s

[16:12:35] [INFO]   |-- 🌤️ llm-structured column '_domain' progress: 22/24 (92%) complete, 22 ok, 0 failed, 2.61 rec/s, eta 0.8s

[16:12:36] [INFO]   |-- ☀️ llm-structured column '_domain' progress: 24/24 (100%) complete, 24 ok, 0 failed, 2.55 rec/s, eta 0.0s

[16:12:36] [INFO] 🔧 Custom column config for column '_domain_supplement'

[16:12:36] [INFO]   |-- generator_function: '_enrich_domain'

[16:12:36] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:12:36] [INFO]   |-- required_columns: ['_domain']

[16:12:36] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers

[16:12:36] [INFO] ⏱️ custom column '_domain_supplement' will report progress every 2 records

[16:12:36] [INFO]   |-- 🌑 custom column '_domain_supplement' progress: 2/24 (8%) complete, 2 ok, 0 failed, 1422.52 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌑 custom column '_domain_supplement' progress: 4/24 (17%) complete, 4 ok, 0 failed, 1677.68 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌘 custom column '_domain_supplement' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2002.92 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌘 custom column '_domain_supplement' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2254.66 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌘 custom column '_domain_supplement' progress: 10/24 (42%) complete, 10 ok, 0 failed, 2416.72 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌗 custom column '_domain_supplement' progress: 12/24 (50%) complete, 12 ok, 0 failed, 2469.41 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌗 custom column '_domain_supplement' progress: 14/24 (58%) complete, 14 ok, 0 failed, 2637.78 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌗 custom column '_domain_supplement' progress: 16/24 (67%) complete, 16 ok, 0 failed, 2708.80 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌖 custom column '_domain_supplement' progress: 18/24 (75%) complete, 18 ok, 0 failed, 2840.37 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌖 custom column '_domain_supplement' progress: 20/24 (83%) complete, 20 ok, 0 failed, 2907.59 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌖 custom column '_domain_supplement' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3011.53 rec/s, eta 0.0s

[16:12:36] [INFO]   |-- 🌕 custom column '_domain_supplement' progress: 24/24 (100%) complete, 24 ok, 0 failed, 3098.76 rec/s, eta 0.0s

[16:12:36] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'

[16:12:36] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:12:36] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:12:36] [INFO]   |-- model provider: 'nvidia'

[16:12:36] [INFO]   |-- inference parameters:

[16:12:36] [INFO]   |  |-- generation_type=chat-completion

[16:12:36] [INFO]   |  |-- max_parallel_requests=2

[16:12:36] [INFO]   |  |-- timeout=300

[16:12:36] [INFO]   |  |-- temperature=0.30

[16:12:36] [INFO]   |  |-- top_p=0.95

[16:12:36] [INFO]   |  |-- max_tokens=16384

[16:12:36] [INFO] ⚡️ Processing llm-structured column '_sensitivity_disposition' with 2 concurrent workers

[16:12:36] [INFO] ⏱️ llm-structured column '_sensitivity_disposition' will report progress every 2 records

[16:13:20] [INFO]   |-- 😴 llm-structured column '_sensitivity_disposition' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.05 rec/s, eta 480.5s

[16:14:18] [INFO]   |-- 😴 llm-structured column '_sensitivity_disposition' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.04 rec/s, eta 508.9s

[16:14:49] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.05 rec/s, eta 399.5s

[16:15:33] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.05 rec/s, eta 354.2s

[16:16:36] [INFO]   |-- 🥱 llm-structured column '_sensitivity_disposition' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.04 rec/s, eta 335.8s

[16:17:22] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.04 rec/s, eta 286.1s

[16:18:00] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.04 rec/s, eta 231.0s

[16:18:36] [INFO]   |-- 😐 llm-structured column '_sensitivity_disposition' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.04 rec/s, eta 180.0s

[16:19:12] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.05 rec/s, eta 131.8s

[16:19:42] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.05 rec/s, eta 85.2s

[16:20:07] [INFO]   |-- 😊 llm-structured column '_sensitivity_disposition' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.05 rec/s, eta 40.9s

[16:21:04] [INFO]   |-- 🤩 llm-structured column '_sensitivity_disposition' progress: 24/24 (100%) complete, 24 ok, 0 failed, 0.05 rec/s, eta 0.0s

[16:21:04] [INFO] 🔧 Custom column config for column '_sensitivity_disposition_block'

[16:21:04] [INFO]   |-- generator_function: '_format_disposition_block'

[16:21:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:21:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[16:21:04] [INFO] ⚡️ Processing custom column '_sensitivity_disposition_block' with 4 concurrent workers

[16:21:04] [INFO] ⏱️ custom column '_sensitivity_disposition_block' will report progress every 2 records

[16:21:04] [INFO]   |-- 🌧️ custom column '_sensitivity_disposition_block' progress: 2/24 (8%) complete, 2 ok, 0 failed, 1214.08 rec/s, eta 0.0s

[16:21:04] [WARNING] ⚠️ Custom generator function '_format_disposition_block' failed for column '_sensitivity_disposition_block'. This record will be skipped.
1 validation error for SensitivityDispositionSchema
sensitivity_disposition.39
  Value error, Entity 40: needs_protection=True cannot have protection_method_suggestion='left_as_is' [type=value_error, input_value={'id': 40, 'source': 'tag...d_risk_level': 'medium'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[16:21:04] [INFO]   |-- 🌧️ custom column '_sensitivity_disposition_block' progress: 4/24 (17%) complete, 4 ok, 0 failed, 1032.61 rec/s, eta 0.0s

[16:21:04] [WARNING] ⚠️ Generation for record at index 2 failed. Will omit this record from the dataset.
Custom generator function failed for column '_sensitivity_disposition_block': 1 validation error for SensitivityDispositionSchema
sensitivity_disposition.39
  Value error, Entity 40: needs_protection=True cannot have protection_method_suggestion='left_as_is' [type=value_error, input_value={'id': 40, 'source': 'tag...d_risk_level': 'medium'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[16:21:04] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 6/24 (25%) complete, 6 ok, 0 failed, 1166.10 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 8/24 (33%) complete, 8 ok, 0 failed, 1284.01 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌦️ custom column '_sensitivity_disposition_block' progress: 10/24 (42%) complete, 9 ok, 1 failed, 1343.54 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 12/24 (50%) complete, 11 ok, 1 failed, 1435.69 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 14/24 (58%) complete, 13 ok, 1 failed, 1539.17 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- ⛅ custom column '_sensitivity_disposition_block' progress: 16/24 (67%) complete, 15 ok, 1 failed, 1624.67 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 18/24 (75%) complete, 17 ok, 1 failed, 1700.95 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 20/24 (83%) complete, 19 ok, 1 failed, 1746.92 rec/s, eta 0.0s

[16:21:04] [WARNING] ⚠️ Custom generator function '_format_disposition_block' failed for column '_sensitivity_disposition_block'. This record will be skipped.
1 validation error for SensitivityDispositionSchema
sensitivity_disposition.26
  Value error, Entity 27: needs_protection=True cannot have protection_method_suggestion='left_as_is' [type=value_error, input_value={'id': 27, 'source': 'tag...d_risk_level': 'medium'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[16:21:04] [INFO]   |-- 🌤️ custom column '_sensitivity_disposition_block' progress: 22/24 (92%) complete, 21 ok, 1 failed, 1757.64 rec/s, eta 0.0s

[16:21:04] [WARNING] ⚠️ Generation for record at index 22 failed. Will omit this record from the dataset.
Custom generator function failed for column '_sensitivity_disposition_block': 1 validation error for SensitivityDispositionSchema
sensitivity_disposition.26
  Value error, Entity 27: needs_protection=True cannot have protection_method_suggestion='left_as_is' [type=value_error, input_value={'id': 27, 'source': 'tag...d_risk_level': 'medium'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error

[16:21:04] [INFO]   |-- ☀️ custom column '_sensitivity_disposition_block' progress: 24/24 (100%) complete, 22 ok, 2 failed, 1816.82 rec/s, eta 0.0s

[16:21:04] [INFO] 🔧 Custom column config for column '_privacy_qa'

[16:21:04] [INFO]   |-- generator_function: '_generate_privacy_qa_column'

[16:21:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:21:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[16:21:04] [INFO] ⚡️ Processing custom column '_privacy_qa' with 4 concurrent workers

[16:21:04] [INFO] ⏱️ custom column '_privacy_qa' will report progress every 2 records

[16:21:04] [INFO]   |-- 🌑 custom column '_privacy_qa' progress: 2/24 (8%) complete, 2 ok, 0 failed, 2301.50 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌑 custom column '_privacy_qa' progress: 4/24 (17%) complete, 4 ok, 0 failed, 2521.27 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌘 custom column '_privacy_qa' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2302.19 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌘 custom column '_privacy_qa' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2625.50 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌘 custom column '_privacy_qa' progress: 10/24 (42%) complete, 10 ok, 0 failed, 2363.11 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌗 custom column '_privacy_qa' progress: 12/24 (50%) complete, 12 ok, 0 failed, 2242.27 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌗 custom column '_privacy_qa' progress: 14/24 (58%) complete, 14 ok, 0 failed, 2329.34 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌗 custom column '_privacy_qa' progress: 16/24 (67%) complete, 16 ok, 0 failed, 2370.34 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌖 custom column '_privacy_qa' progress: 18/24 (75%) complete, 18 ok, 0 failed, 2391.74 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌖 custom column '_privacy_qa' progress: 20/24 (83%) complete, 20 ok, 0 failed, 2441.56 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌖 custom column '_privacy_qa' progress: 22/24 (92%) complete, 22 ok, 0 failed, 2612.31 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🌖 custom column '_privacy_qa' progress: 22/24 (92%) complete, 22 ok, 0 failed, 2553.44 rec/s, eta 0.0s

[16:21:04] [INFO] 🔧 Custom column config for column '_rewrite_disposition_block'

[16:21:04] [INFO]   |-- generator_function: '_format_rewrite_disposition_block'

[16:21:04] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:21:04] [INFO]   |-- required_columns: ['_sensitivity_disposition']

[16:21:04] [INFO] ⚡️ Processing custom column '_rewrite_disposition_block' with 4 concurrent workers

[16:21:04] [INFO] ⏱️ custom column '_rewrite_disposition_block' will report progress every 2 records

[16:21:04] [INFO]   |-- 🐱 custom column '_rewrite_disposition_block' progress: 2/24 (8%) complete, 2 ok, 0 failed, 2453.86 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 🐱 custom column '_rewrite_disposition_block' progress: 4/24 (17%) complete, 4 ok, 0 failed, 2824.69 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😺 custom column '_rewrite_disposition_block' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2462.68 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😺 custom column '_rewrite_disposition_block' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2829.69 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😺 custom column '_rewrite_disposition_block' progress: 10/24 (42%) complete, 10 ok, 0 failed, 2514.33 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😸 custom column '_rewrite_disposition_block' progress: 12/24 (50%) complete, 12 ok, 0 failed, 2706.26 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😸 custom column '_rewrite_disposition_block' progress: 14/24 (58%) complete, 14 ok, 0 failed, 2607.70 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😸 custom column '_rewrite_disposition_block' progress: 16/24 (67%) complete, 16 ok, 0 failed, 2785.21 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😼 custom column '_rewrite_disposition_block' progress: 18/24 (75%) complete, 18 ok, 0 failed, 2831.58 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😼 custom column '_rewrite_disposition_block' progress: 20/24 (83%) complete, 20 ok, 0 failed, 2973.59 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😼 custom column '_rewrite_disposition_block' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3074.76 rec/s, eta 0.0s

[16:21:04] [INFO]   |-- 😼 custom column '_rewrite_disposition_block' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3003.69 rec/s, eta 0.0s

[16:21:04] [INFO] 🗂️ llm-structured model config for column '_meaning_units'

[16:21:04] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:21:04] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:21:04] [INFO]   |-- model provider: 'nvidia'

[16:21:04] [INFO]   |-- inference parameters:

[16:21:04] [INFO]   |  |-- generation_type=chat-completion

[16:21:04] [INFO]   |  |-- max_parallel_requests=2

[16:21:04] [INFO]   |  |-- timeout=300

[16:21:04] [INFO]   |  |-- temperature=0.30

[16:21:04] [INFO]   |  |-- top_p=0.95

[16:21:04] [INFO]   |  |-- max_tokens=16384

[16:21:04] [INFO] ⚡️ Processing llm-structured column '_meaning_units' with 2 concurrent workers

[16:21:04] [INFO] ⏱️ llm-structured column '_meaning_units' will report progress every 2 records

[16:21:16] [INFO]   |-- 🚶 llm-structured column '_meaning_units' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.17 rec/s, eta 128.1s

[16:21:24] [INFO]   |-- 🚶 llm-structured column '_meaning_units' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.20 rec/s, eta 99.9s

[16:21:37] [INFO]   |-- 🐴 llm-structured column '_meaning_units' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.18 rec/s, eta 99.5s

[16:21:48] [INFO]   |-- 🐴 llm-structured column '_meaning_units' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.18 rec/s, eta 87.6s

[16:22:01] [INFO]   |-- 🐴 llm-structured column '_meaning_units' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.18 rec/s, eta 79.7s

[16:22:11] [INFO]   |-- 🚗 llm-structured column '_meaning_units' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.18 rec/s, eta 67.3s

[16:22:27] [INFO]   |-- 🚗 llm-structured column '_meaning_units' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.17 rec/s, eta 59.4s

[16:22:39] [INFO]   |-- 🚗 llm-structured column '_meaning_units' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.17 rec/s, eta 47.6s

[16:22:52] [INFO]   |-- ✈️ llm-structured column '_meaning_units' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.17 rec/s, eta 36.0s

[16:23:04] [INFO]   |-- ✈️ llm-structured column '_meaning_units' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.17 rec/s, eta 24.0s

[16:23:25] [INFO]   |-- ✈️ llm-structured column '_meaning_units' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.16 rec/s, eta 12.8s

[16:23:25] [INFO]   |-- ✈️ llm-structured column '_meaning_units' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.16 rec/s, eta 12.8s

[16:23:25] [INFO] 🔧 Custom column config for column '_replacement_map_for_prompt'

[16:23:25] [INFO]   |-- generator_function: '_filter_replacement_map_for_prompt'

[16:23:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:23:25] [INFO]   |-- required_columns: ['_replacement_map', '_rewrite_disposition_block']

[16:23:25] [INFO] ⚡️ Processing custom column '_replacement_map_for_prompt' with 4 concurrent workers

[16:23:25] [INFO] ⏱️ custom column '_replacement_map_for_prompt' will report progress every 2 records

[16:23:25] [INFO]   |-- 🌑 custom column '_replacement_map_for_prompt' progress: 2/24 (8%) complete, 2 ok, 0 failed, 1375.67 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌑 custom column '_replacement_map_for_prompt' progress: 4/24 (17%) complete, 4 ok, 0 failed, 1617.58 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌘 custom column '_replacement_map_for_prompt' progress: 6/24 (25%) complete, 6 ok, 0 failed, 1834.25 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌘 custom column '_replacement_map_for_prompt' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2018.84 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌘 custom column '_replacement_map_for_prompt' progress: 10/24 (42%) complete, 10 ok, 0 failed, 2045.09 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌗 custom column '_replacement_map_for_prompt' progress: 12/24 (50%) complete, 12 ok, 0 failed, 2146.18 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌗 custom column '_replacement_map_for_prompt' progress: 14/24 (58%) complete, 14 ok, 0 failed, 2133.01 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌗 custom column '_replacement_map_for_prompt' progress: 16/24 (67%) complete, 16 ok, 0 failed, 2261.87 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌖 custom column '_replacement_map_for_prompt' progress: 18/24 (75%) complete, 18 ok, 0 failed, 2339.83 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌖 custom column '_replacement_map_for_prompt' progress: 20/24 (83%) complete, 20 ok, 0 failed, 2383.97 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌖 custom column '_replacement_map_for_prompt' progress: 22/24 (92%) complete, 22 ok, 0 failed, 2481.16 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🌖 custom column '_replacement_map_for_prompt' progress: 22/24 (92%) complete, 22 ok, 0 failed, 2399.14 rec/s, eta 0.0s

[16:23:25] [INFO] 🔧 Custom column config for column '_meaning_units_serialized'

[16:23:25] [INFO]   |-- generator_function: '_serialize_meaning_units'

[16:23:25] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:23:25] [INFO]   |-- required_columns: ['_meaning_units']

[16:23:25] [INFO] ⚡️ Processing custom column '_meaning_units_serialized' with 4 concurrent workers

[16:23:25] [INFO] ⏱️ custom column '_meaning_units_serialized' will report progress every 2 records

[16:23:25] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 2/24 (8%) complete, 2 ok, 0 failed, 2482.54 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🥚 custom column '_meaning_units_serialized' progress: 4/24 (17%) complete, 4 ok, 0 failed, 2873.39 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2897.27 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 8/24 (33%) complete, 8 ok, 0 failed, 3091.39 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐣 custom column '_meaning_units_serialized' progress: 10/24 (42%) complete, 10 ok, 0 failed, 3072.24 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 12/24 (50%) complete, 12 ok, 0 failed, 3153.54 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 14/24 (58%) complete, 14 ok, 0 failed, 3283.14 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐥 custom column '_meaning_units_serialized' progress: 16/24 (67%) complete, 16 ok, 0 failed, 3467.11 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 18/24 (75%) complete, 18 ok, 0 failed, 3569.01 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 20/24 (83%) complete, 20 ok, 0 failed, 3751.35 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3895.82 rec/s, eta 0.0s

[16:23:25] [INFO]   |-- 🐤 custom column '_meaning_units_serialized' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3727.00 rec/s, eta 0.0s

[16:23:25] [INFO] 🗂️ llm-structured model config for column '_full_rewrite'

[16:23:25] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:23:25] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:23:25] [INFO]   |-- model provider: 'nvidia'

[16:23:25] [INFO]   |-- inference parameters:

[16:23:25] [INFO]   |  |-- generation_type=chat-completion

[16:23:25] [INFO]   |  |-- max_parallel_requests=2

[16:23:25] [INFO]   |  |-- timeout=300

[16:23:25] [INFO]   |  |-- temperature=0.30

[16:23:25] [INFO]   |  |-- top_p=0.95

[16:23:25] [INFO]   |  |-- max_tokens=16384

[16:23:25] [INFO] ⚡️ Processing llm-structured column '_full_rewrite' with 2 concurrent workers

[16:23:25] [INFO] ⏱️ llm-structured column '_full_rewrite' will report progress every 2 records

[16:23:53] [INFO]   |-- 🌧️ llm-structured column '_full_rewrite' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.07 rec/s, eta 304.7s

[16:24:07] [INFO]   |-- 🌧️ llm-structured column '_full_rewrite' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.10 rec/s, eta 207.3s

[16:24:24] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.10 rec/s, eta 175.7s

[16:24:35] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.12 rec/s, eta 138.5s

[16:24:54] [INFO]   |-- 🌦️ llm-structured column '_full_rewrite' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.11 rec/s, eta 123.7s

[16:25:14] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.11 rec/s, eta 108.3s

[16:25:37] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.11 rec/s, eta 93.9s

[16:25:58] [INFO]   |-- ⛅ llm-structured column '_full_rewrite' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.10 rec/s, eta 76.4s

[16:26:19] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.10 rec/s, eta 57.8s

[16:26:45] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.10 rec/s, eta 39.9s

[16:27:13] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.10 rec/s, eta 20.7s

[16:27:13] [INFO]   |-- 🌤️ llm-structured column '_full_rewrite' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.10 rec/s, eta 20.7s

[16:27:13] [INFO] 🗂️ llm-structured model config for column '_quality_qa'

[16:27:13] [INFO]   |-- model: 'openai/gpt-oss-120b'

[16:27:13] [INFO]   |-- model alias: 'gpt-oss-120b'

[16:27:13] [INFO]   |-- model provider: 'nvidia'

[16:27:13] [INFO]   |-- inference parameters:

[16:27:13] [INFO]   |  |-- generation_type=chat-completion

[16:27:13] [INFO]   |  |-- max_parallel_requests=2

[16:27:13] [INFO]   |  |-- timeout=300

[16:27:13] [INFO]   |  |-- temperature=0.30

[16:27:13] [INFO]   |  |-- top_p=0.95

[16:27:13] [INFO]   |  |-- max_tokens=16384

[16:27:13] [INFO] ⚡️ Processing llm-structured column '_quality_qa' with 2 concurrent workers

[16:27:13] [INFO] ⏱️ llm-structured column '_quality_qa' will report progress every 2 records

[16:27:23] [INFO]   |-- 🥚 llm-structured column '_quality_qa' progress: 2/24 (8%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 104.5s

[16:27:32] [INFO]   |-- 🥚 llm-structured column '_quality_qa' progress: 4/24 (17%) complete, 4 ok, 0 failed, 0.22 rec/s, eta 91.9s

[16:27:42] [INFO]   |-- 🐣 llm-structured column '_quality_qa' progress: 6/24 (25%) complete, 6 ok, 0 failed, 0.21 rec/s, eta 87.3s

[16:27:51] [INFO]   |-- 🐣 llm-structured column '_quality_qa' progress: 8/24 (33%) complete, 8 ok, 0 failed, 0.21 rec/s, eta 75.0s

[16:28:02] [INFO]   |-- 🐣 llm-structured column '_quality_qa' progress: 10/24 (42%) complete, 10 ok, 0 failed, 0.20 rec/s, eta 68.6s

[16:28:14] [INFO]   |-- 🐥 llm-structured column '_quality_qa' progress: 12/24 (50%) complete, 12 ok, 0 failed, 0.20 rec/s, eta 60.3s

[16:28:26] [INFO]   |-- 🐥 llm-structured column '_quality_qa' progress: 14/24 (58%) complete, 14 ok, 0 failed, 0.19 rec/s, eta 51.9s

[16:28:35] [INFO]   |-- 🐥 llm-structured column '_quality_qa' progress: 16/24 (67%) complete, 16 ok, 0 failed, 0.20 rec/s, eta 40.9s

[16:28:44] [INFO]   |-- 🐤 llm-structured column '_quality_qa' progress: 18/24 (75%) complete, 18 ok, 0 failed, 0.20 rec/s, eta 30.2s

[16:29:01] [INFO]   |-- 🐤 llm-structured column '_quality_qa' progress: 20/24 (83%) complete, 20 ok, 0 failed, 0.19 rec/s, eta 21.5s

[16:29:14] [INFO]   |-- 🐤 llm-structured column '_quality_qa' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.18 rec/s, eta 11.0s

[16:29:14] [INFO]   |-- 🐤 llm-structured column '_quality_qa' progress: 22/24 (92%) complete, 22 ok, 0 failed, 0.18 rec/s, eta 11.0s

[16:29:14] [INFO] 🔧 Custom column config for column '_rewritten_text'

[16:29:14] [INFO]   |-- generator_function: '_extract_rewritten_text'

[16:29:14] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:29:14] [INFO]   |-- required_columns: ['_full_rewrite']

[16:29:14] [INFO] ⚡️ Processing custom column '_rewritten_text' with 4 concurrent workers

[16:29:14] [INFO] ⏱️ custom column '_rewritten_text' will report progress every 2 records

[16:29:14] [INFO]   |-- 😴 custom column '_rewritten_text' progress: 2/24 (8%) complete, 2 ok, 0 failed, 1913.57 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😴 custom column '_rewritten_text' progress: 4/24 (17%) complete, 4 ok, 0 failed, 2256.91 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 🥱 custom column '_rewritten_text' progress: 6/24 (25%) complete, 6 ok, 0 failed, 2594.41 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 🥱 custom column '_rewritten_text' progress: 8/24 (33%) complete, 8 ok, 0 failed, 2957.08 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 🥱 custom column '_rewritten_text' progress: 10/24 (42%) complete, 10 ok, 0 failed, 3139.88 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😐 custom column '_rewritten_text' progress: 12/24 (50%) complete, 12 ok, 0 failed, 3294.33 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😐 custom column '_rewritten_text' progress: 14/24 (58%) complete, 14 ok, 0 failed, 3492.83 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😐 custom column '_rewritten_text' progress: 16/24 (67%) complete, 16 ok, 0 failed, 3603.23 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😊 custom column '_rewritten_text' progress: 18/24 (75%) complete, 18 ok, 0 failed, 3733.47 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😊 custom column '_rewritten_text' progress: 20/24 (83%) complete, 20 ok, 0 failed, 3754.43 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😊 custom column '_rewritten_text' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3890.25 rec/s, eta 0.0s

[16:29:14] [INFO]   |-- 😊 custom column '_rewritten_text' progress: 22/24 (92%) complete, 22 ok, 0 failed, 3698.18 rec/s, eta 0.0s

[16:29:15] [INFO] 📊 Model usage summary:

[16:29:15] [INFO]   |-- model: openai/gpt-oss-120b

[16:29:15] [INFO]   |-- tokens: input=340416, output=379512, total=719928, tps=714

[16:29:15] [INFO]   |-- requests: success=115, failed=0, total=115, rpm=6

[16:29:15] [INFO] 📐 Measuring dataset column statistics:

[16:29:15] [INFO]   |-- 🗂️ column: '_domain'

[16:29:15] [INFO]   |-- 🔧 column: '_domain_supplement'

[16:29:15] [INFO]   |-- 🗂️ column: '_sensitivity_disposition'

[16:29:15] [INFO]   |-- 🔧 column: '_sensitivity_disposition_block'

[16:29:15] [INFO]   |-- 🗂️ column: '_meaning_units'

[16:29:15] [INFO]   |-- 🔧 column: '_meaning_units_serialized'

[16:29:15] [INFO]   |-- 🗂️ column: '_quality_qa'

[16:29:15] [INFO]   |-- 🔧 column: '_privacy_qa'

[16:29:15] [INFO]   |-- 🔧 column: '_rewrite_disposition_block'

[16:29:15] [INFO]   |-- 🔧 column: '_replacement_map_for_prompt'

[16:29:15] [INFO]   |-- 🗂️ column: '_full_rewrite'

[16:29:15] [INFO]   |-- 🔧 column: '_rewritten_text'

[16:29:15] [DEBUG] NDD workflow 'rewrite-pipeline' returned 22 records

[16:29:15] [WARNING] Row count mismatch: target=24, source=22; dropping 2 failed row(s).

[16:29:15] [DEBUG] NDD workflow 'rewrite-evaluate-0' starting with 22 records

[16:29:15] [DEBUG] NDD workflow 'rewrite-evaluate-0': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[16:29:15] [INFO] 🎨 Creating Data Designer dataset

[16:29:15] [INFO] ✅ Validation passed

[16:29:15] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:29:15] [INFO] 🩺 Running health checks for models...

[16:29:15] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:29:17] [INFO]   |-- ✅ Passed!

[16:29:17] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-0_03-31-2026_162917' instead.

[16:29:17] [INFO] ⏳ Processing batch 1 of 1

[16:29:17] [INFO] 🌱 Sampling 22 records from seed dataset

[16:29:17] [INFO]   |-- seed dataset size: 22 records

[16:29:17] [INFO]   |-- sampling strategy: ordered

[16:29:17] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[16:29:17] [INFO]   |-- generator_function: '_quality_reanswer'

[16:29:17] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:29:17] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[16:29:17] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:29:17] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[16:29:17] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress every 2 records

[16:29:25] [INFO]   |-- 🌑 custom column '_quality_qa_reanswer' progress: 2/22 (9%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 87.2s

[16:29:28] [WARNING] Evaluator returned malformed quality answer set; missing=[14] duplicate=[] extra=[]. Applying conservative normalization.

[16:29:28] [INFO]   |-- 🌑 custom column '_quality_qa_reanswer' progress: 4/22 (18%) complete, 4 ok, 0 failed, 0.34 rec/s, eta 52.5s

[16:29:35] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 6/22 (27%) complete, 6 ok, 0 failed, 0.33 rec/s, eta 48.4s

[16:29:41] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 8/22 (36%) complete, 8 ok, 0 failed, 0.33 rec/s, eta 42.1s

[16:29:43] [INFO]   |-- 🌘 custom column '_quality_qa_reanswer' progress: 10/22 (45%) complete, 10 ok, 0 failed, 0.37 rec/s, eta 32.0s

[16:29:46] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 12/22 (55%) complete, 12 ok, 0 failed, 0.40 rec/s, eta 24.9s

[16:29:51] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 14/22 (64%) complete, 14 ok, 0 failed, 0.41 rec/s, eta 19.4s

[16:29:54] [INFO]   |-- 🌗 custom column '_quality_qa_reanswer' progress: 16/22 (73%) complete, 16 ok, 0 failed, 0.43 rec/s, eta 13.9s

[16:29:57] [INFO]   |-- 🌖 custom column '_quality_qa_reanswer' progress: 18/22 (82%) complete, 18 ok, 0 failed, 0.45 rec/s, eta 9.0s

[16:30:02] [INFO]   |-- 🌖 custom column '_quality_qa_reanswer' progress: 20/22 (91%) complete, 20 ok, 0 failed, 0.44 rec/s, eta 4.5s

[16:30:11] [INFO]   |-- 🌕 custom column '_quality_qa_reanswer' progress: 22/22 (100%) complete, 22 ok, 0 failed, 0.40 rec/s, eta 0.0s

[16:30:11] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[16:30:11] [INFO]   |-- generator_function: '_privacy_reanswer'

[16:30:11] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:30:11] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[16:30:11] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:30:11] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[16:30:11] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress every 2 records

[16:30:16] [INFO]   |-- 🌑 custom column '_privacy_qa_reanswer' progress: 2/22 (9%) complete, 2 ok, 0 failed, 0.37 rec/s, eta 54.5s

[16:30:19] [INFO]   |-- 🌑 custom column '_privacy_qa_reanswer' progress: 4/22 (18%) complete, 4 ok, 0 failed, 0.52 rec/s, eta 34.7s

[16:30:21] [INFO]   |-- 🌘 custom column '_privacy_qa_reanswer' progress: 6/22 (27%) complete, 6 ok, 0 failed, 0.60 rec/s, eta 26.5s

[16:30:27] [INFO]   |-- 🌘 custom column '_privacy_qa_reanswer' progress: 8/22 (36%) complete, 8 ok, 0 failed, 0.50 rec/s, eta 27.9s

[16:30:32] [INFO]   |-- 🌘 custom column '_privacy_qa_reanswer' progress: 10/22 (45%) complete, 10 ok, 0 failed, 0.47 rec/s, eta 25.6s

[16:30:40] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 12/22 (55%) complete, 12 ok, 0 failed, 0.41 rec/s, eta 24.2s

[16:30:43] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 14/22 (64%) complete, 14 ok, 0 failed, 0.43 rec/s, eta 18.4s

[16:30:46] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 16/22 (73%) complete, 16 ok, 0 failed, 0.45 rec/s, eta 13.2s

[16:30:52] [INFO]   |-- 🌖 custom column '_privacy_qa_reanswer' progress: 18/22 (82%) complete, 18 ok, 0 failed, 0.44 rec/s, eta 9.2s

[16:30:55] [INFO]   |-- 🌖 custom column '_privacy_qa_reanswer' progress: 20/22 (91%) complete, 20 ok, 0 failed, 0.45 rec/s, eta 4.4s

[16:31:02] [INFO]   |-- 🌕 custom column '_privacy_qa_reanswer' progress: 22/22 (100%) complete, 22 ok, 0 failed, 0.43 rec/s, eta 0.0s

[16:31:02] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[16:31:02] [INFO]   |-- generator_function: '_quality_compare'

[16:31:02] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:31:02] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[16:31:02] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:31:02] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[16:31:02] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress every 2 records

[16:31:12] [INFO]   |-- 🌑 custom column '_quality_qa_compare' progress: 2/22 (9%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 95.2s

[16:31:14] [INFO]   |-- 🌑 custom column '_quality_qa_compare' progress: 4/22 (18%) complete, 4 ok, 0 failed, 0.34 rec/s, eta 52.9s

[16:31:20] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 6/22 (27%) complete, 6 ok, 0 failed, 0.35 rec/s, eta 46.3s

[16:31:23] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 8/22 (36%) complete, 8 ok, 0 failed, 0.38 rec/s, eta 36.4s

[16:31:30] [INFO]   |-- 🌘 custom column '_quality_qa_compare' progress: 10/22 (45%) complete, 10 ok, 0 failed, 0.36 rec/s, eta 33.0s

[16:31:30] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 12/22 (55%) complete, 12 ok, 0 failed, 0.43 rec/s, eta 23.2s

[16:31:36] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 14/22 (64%) complete, 14 ok, 0 failed, 0.41 rec/s, eta 19.3s

[16:31:42] [INFO]   |-- 🌗 custom column '_quality_qa_compare' progress: 16/22 (73%) complete, 16 ok, 0 failed, 0.41 rec/s, eta 14.8s

[16:31:43] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 18/22 (82%) complete, 18 ok, 0 failed, 0.44 rec/s, eta 9.0s

[16:31:49] [INFO]   |-- 🌖 custom column '_quality_qa_compare' progress: 20/22 (91%) complete, 20 ok, 0 failed, 0.42 rec/s, eta 4.7s

[16:31:53] [INFO]   |-- 🌕 custom column '_quality_qa_compare' progress: 22/22 (100%) complete, 22 ok, 0 failed, 0.44 rec/s, eta 0.0s

[16:31:53] [INFO] 🔧 Custom column config for column 'utility_score'

[16:31:53] [INFO]   |-- generator_function: '_compute_metrics_columns'

[16:31:53] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:31:53] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[16:31:53] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[16:31:53] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[16:31:53] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[16:31:53] [INFO] ⏱️ custom column 'utility_score' will report progress every 2 records

[16:31:53] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 2/22 (9%) complete, 2 ok, 0 failed, 1422.90 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌧️ custom column 'utility_score' progress: 4/22 (18%) complete, 4 ok, 0 failed, 1398.70 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 6/22 (27%) complete, 6 ok, 0 failed, 1525.78 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 8/22 (36%) complete, 8 ok, 0 failed, 1663.78 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column 'utility_score' progress: 10/22 (45%) complete, 10 ok, 0 failed, 1570.81 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column 'utility_score' progress: 12/22 (55%) complete, 12 ok, 0 failed, 1678.67 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column 'utility_score' progress: 14/22 (64%) complete, 14 ok, 0 failed, 1725.59 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column 'utility_score' progress: 16/22 (73%) complete, 16 ok, 0 failed, 1767.20 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 18/22 (82%) complete, 18 ok, 0 failed, 1808.84 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌤️ custom column 'utility_score' progress: 20/22 (91%) complete, 20 ok, 0 failed, 1877.49 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ☀️ custom column 'utility_score' progress: 22/22 (100%) complete, 22 ok, 0 failed, 1965.28 rec/s, eta 0.0s

[16:31:53] [INFO] 🔧 Custom column config for column '_needs_repair'

[16:31:53] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[16:31:53] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:31:53] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[16:31:53] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[16:31:53] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[16:31:53] [INFO] ⏱️ custom column '_needs_repair' will report progress every 2 records

[16:31:53] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 2/22 (9%) complete, 2 ok, 0 failed, 2604.31 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 4/22 (18%) complete, 4 ok, 0 failed, 3030.78 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 6/22 (27%) complete, 6 ok, 0 failed, 3266.79 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 8/22 (36%) complete, 8 ok, 0 failed, 3624.49 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 10/22 (45%) complete, 10 ok, 0 failed, 3699.59 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 12/22 (55%) complete, 12 ok, 0 failed, 3928.04 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 14/22 (64%) complete, 14 ok, 0 failed, 4153.22 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 16/22 (73%) complete, 16 ok, 0 failed, 4331.30 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 18/22 (82%) complete, 18 ok, 0 failed, 4512.22 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 20/22 (91%) complete, 20 ok, 0 failed, 4653.82 rec/s, eta 0.0s

[16:31:53] [INFO]   |-- ☀️ custom column '_needs_repair' progress: 22/22 (100%) complete, 22 ok, 0 failed, 4835.70 rec/s, eta 0.0s

[16:31:53] [INFO] 📊 Model usage summary:

[16:31:53] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:31:53] [INFO]   |-- tokens: input=127061, output=144423, total=271484, tps=1735

[16:31:53] [INFO]   |-- requests: success=66, failed=0, total=66, rpm=25

[16:31:53] [INFO] 📐 Measuring dataset column statistics:

[16:31:53] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[16:31:53] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[16:31:53] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[16:31:53] [INFO]   |-- 🔧 column: 'utility_score'

[16:31:53] [INFO]   |-- 🔧 column: '_needs_repair'

[16:31:53] [DEBUG] NDD workflow 'rewrite-evaluate-0' returned 22 records

[16:31:53] [INFO] Evaluate-repair loop iteration 0: 14/22 rows need repair

[16:31:53] [DEBUG] NDD workflow 'rewrite-repair-0' starting with 14 records

[16:31:53] [DEBUG] NDD workflow 'rewrite-repair-0': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[16:31:53] [INFO] 🎨 Creating Data Designer dataset

[16:31:53] [INFO] ✅ Validation passed

[16:31:53] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:31:53] [INFO] 🩺 Running health checks for models...

[16:31:53] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[16:31:54] [INFO]   |-- ✅ Passed!

[16:31:54] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-0' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-0_03-31-2026_163154' instead.

[16:31:54] [INFO] ⏳ Processing batch 1 of 1

[16:31:54] [INFO] 🌱 Sampling 14 records from seed dataset

[16:31:54] [INFO]   |-- seed dataset size: 14 records

[16:31:54] [INFO]   |-- sampling strategy: ordered

[16:31:54] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[16:31:54] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[16:31:54] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:31:54] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[16:31:54] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[16:31:54] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[16:31:54] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 1/14 (7%) complete, 1 ok, 0 failed, 1298.56 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 2/14 (14%) complete, 2 ok, 0 failed, 1826.35 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚶 custom column '_leaked_privacy_items' progress: 3/14 (21%) complete, 3 ok, 0 failed, 1886.25 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 4/14 (29%) complete, 4 ok, 0 failed, 2020.29 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 5/14 (36%) complete, 5 ok, 0 failed, 1850.62 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🐴 custom column '_leaked_privacy_items' progress: 6/14 (43%) complete, 6 ok, 0 failed, 1969.23 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 7/14 (50%) complete, 7 ok, 0 failed, 2164.25 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 8/14 (57%) complete, 8 ok, 0 failed, 2027.67 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 9/14 (64%) complete, 9 ok, 0 failed, 1983.14 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚗 custom column '_leaked_privacy_items' progress: 10/14 (71%) complete, 10 ok, 0 failed, 2039.20 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 11/14 (79%) complete, 11 ok, 0 failed, 2102.80 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 12/14 (86%) complete, 12 ok, 0 failed, 2171.83 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- ✈️ custom column '_leaked_privacy_items' progress: 13/14 (93%) complete, 13 ok, 0 failed, 2236.99 rec/s, eta 0.0s

[16:31:54] [INFO]   |-- 🚀 custom column '_leaked_privacy_items' progress: 14/14 (100%) complete, 14 ok, 0 failed, 2291.54 rec/s, eta 0.0s

[16:31:54] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[16:31:54] [INFO]   |-- generator_function: '_repair_column'

[16:31:54] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:31:54] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[16:31:54] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[16:31:54] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[16:31:54] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[16:31:54] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[16:32:00] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 1/14 (7%) complete, 1 ok, 0 failed, 0.16 rec/s, eta 79.6s

[16:32:03] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 2/14 (14%) complete, 2 ok, 0 failed, 0.22 rec/s, eta 55.6s

[16:32:05] [INFO]   |-- 🌑 custom column '_rewritten_text__next' progress: 3/14 (21%) complete, 3 ok, 0 failed, 0.27 rec/s, eta 40.1s

[16:32:05] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 4/14 (29%) complete, 4 ok, 0 failed, 0.35 rec/s, eta 28.5s

[16:32:11] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 5/14 (36%) complete, 5 ok, 0 failed, 0.28 rec/s, eta 32.0s

[16:32:14] [INFO]   |-- 🌘 custom column '_rewritten_text__next' progress: 6/14 (43%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 26.7s

[16:32:14] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 7/14 (50%) complete, 7 ok, 0 failed, 0.34 rec/s, eta 20.9s

[16:32:17] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 8/14 (57%) complete, 8 ok, 0 failed, 0.34 rec/s, eta 17.5s

[16:32:19] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 9/14 (64%) complete, 9 ok, 0 failed, 0.35 rec/s, eta 14.3s

[16:32:24] [INFO]   |-- 🌗 custom column '_rewritten_text__next' progress: 10/14 (71%) complete, 10 ok, 0 failed, 0.33 rec/s, eta 12.1s

[16:32:28] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 11/14 (79%) complete, 11 ok, 0 failed, 0.32 rec/s, eta 9.4s

[16:32:30] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 12/14 (86%) complete, 12 ok, 0 failed, 0.33 rec/s, eta 6.0s

[16:32:31] [INFO]   |-- 🌖 custom column '_rewritten_text__next' progress: 13/14 (93%) complete, 13 ok, 0 failed, 0.35 rec/s, eta 2.9s

[16:32:37] [INFO]   |-- 🌕 custom column '_rewritten_text__next' progress: 14/14 (100%) complete, 14 ok, 0 failed, 0.32 rec/s, eta 0.0s

[16:32:37] [INFO] 📊 Model usage summary:

[16:32:37] [INFO]   |-- model: openai/gpt-oss-120b

[16:32:37] [INFO]   |-- tokens: input=43641, output=28231, total=71872, tps=1644

[16:32:37] [INFO]   |-- requests: success=14, failed=0, total=14, rpm=19

[16:32:37] [INFO] 📐 Measuring dataset column statistics:

[16:32:37] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[16:32:37] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[16:32:37] [DEBUG] NDD workflow 'rewrite-repair-0' returned 14 records

[16:32:37] [DEBUG] NDD workflow 'rewrite-evaluate-1' starting with 14 records

[16:32:37] [DEBUG] NDD workflow 'rewrite-evaluate-1': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[16:32:37] [INFO] 🎨 Creating Data Designer dataset

[16:32:37] [INFO] ✅ Validation passed

[16:32:37] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:32:37] [INFO] 🩺 Running health checks for models...

[16:32:37] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:32:38] [INFO]   |-- ✅ Passed!

[16:32:38] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-1' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-1_03-31-2026_163238' instead.

[16:32:38] [INFO] ⏳ Processing batch 1 of 1

[16:32:38] [INFO] 🌱 Sampling 14 records from seed dataset

[16:32:38] [INFO]   |-- seed dataset size: 14 records

[16:32:38] [INFO]   |-- sampling strategy: ordered

[16:32:38] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[16:32:38] [INFO]   |-- generator_function: '_quality_reanswer'

[16:32:38] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:32:38] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[16:32:38] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:32:38] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[16:32:38] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[16:32:46] [INFO]   |-- 🚶 custom column '_quality_qa_reanswer' progress: 1/14 (7%) complete, 1 ok, 0 failed, 0.13 rec/s, eta 96.9s

[16:32:47] [INFO]   |-- 🚶 custom column '_quality_qa_reanswer' progress: 2/14 (14%) complete, 2 ok, 0 failed, 0.22 rec/s, eta 54.3s

[16:32:49] [WARNING] Evaluator returned malformed quality answer set; missing=[16] duplicate=[] extra=[]. Applying conservative normalization.

[16:32:49] [INFO]   |-- 🚶 custom column '_quality_qa_reanswer' progress: 3/14 (21%) complete, 3 ok, 0 failed, 0.28 rec/s, eta 39.2s

[16:32:50] [INFO]   |-- 🐴 custom column '_quality_qa_reanswer' progress: 4/14 (29%) complete, 4 ok, 0 failed, 0.32 rec/s, eta 30.8s

[16:32:55] [INFO]   |-- 🐴 custom column '_quality_qa_reanswer' progress: 5/14 (36%) complete, 5 ok, 0 failed, 0.29 rec/s, eta 30.9s

[16:32:56] [INFO]   |-- 🐴 custom column '_quality_qa_reanswer' progress: 6/14 (43%) complete, 6 ok, 0 failed, 0.34 rec/s, eta 23.4s

[16:32:57] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 7/14 (50%) complete, 7 ok, 0 failed, 0.38 rec/s, eta 18.6s

[16:33:02] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 8/14 (57%) complete, 8 ok, 0 failed, 0.34 rec/s, eta 17.6s

[16:33:02] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 9/14 (64%) complete, 9 ok, 0 failed, 0.38 rec/s, eta 13.1s

[16:33:09] [INFO]   |-- 🚗 custom column '_quality_qa_reanswer' progress: 10/14 (71%) complete, 10 ok, 0 failed, 0.33 rec/s, eta 12.3s

[16:33:09] [INFO]   |-- ✈️ custom column '_quality_qa_reanswer' progress: 11/14 (79%) complete, 11 ok, 0 failed, 0.35 rec/s, eta 8.5s

[16:33:09] [INFO]   |-- ✈️ custom column '_quality_qa_reanswer' progress: 12/14 (86%) complete, 12 ok, 0 failed, 0.38 rec/s, eta 5.2s

[16:33:09] [INFO]   |-- ✈️ custom column '_quality_qa_reanswer' progress: 13/14 (93%) complete, 13 ok, 0 failed, 0.41 rec/s, eta 2.4s

[16:33:18] [INFO]   |-- 🚀 custom column '_quality_qa_reanswer' progress: 14/14 (100%) complete, 14 ok, 0 failed, 0.35 rec/s, eta 0.0s

[16:33:18] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[16:33:18] [INFO]   |-- generator_function: '_privacy_reanswer'

[16:33:18] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:33:18] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[16:33:18] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:33:18] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[16:33:18] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[16:33:22] [INFO]   |-- 🐱 custom column '_privacy_qa_reanswer' progress: 1/14 (7%) complete, 1 ok, 0 failed, 0.23 rec/s, eta 55.4s

[16:33:27] [INFO]   |-- 🐱 custom column '_privacy_qa_reanswer' progress: 2/14 (14%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 58.3s

[16:33:28] [INFO]   |-- 🐱 custom column '_privacy_qa_reanswer' progress: 3/14 (21%) complete, 3 ok, 0 failed, 0.29 rec/s, eta 37.5s

[16:33:30] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 4/14 (29%) complete, 4 ok, 0 failed, 0.34 rec/s, eta 29.4s

[16:33:38] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 5/14 (36%) complete, 5 ok, 0 failed, 0.24 rec/s, eta 36.9s

[16:33:42] [INFO]   |-- 😺 custom column '_privacy_qa_reanswer' progress: 6/14 (43%) complete, 6 ok, 0 failed, 0.25 rec/s, eta 32.3s

[16:33:45] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 7/14 (50%) complete, 7 ok, 0 failed, 0.26 rec/s, eta 26.8s

[16:33:45] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 8/14 (57%) complete, 8 ok, 0 failed, 0.29 rec/s, eta 20.6s

[16:33:55] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 9/14 (64%) complete, 9 ok, 0 failed, 0.24 rec/s, eta 20.7s

[16:33:56] [INFO]   |-- 😸 custom column '_privacy_qa_reanswer' progress: 10/14 (71%) complete, 10 ok, 0 failed, 0.26 rec/s, eta 15.2s

[16:33:59] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 11/14 (79%) complete, 11 ok, 0 failed, 0.26 rec/s, eta 11.3s

[16:34:03] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 12/14 (86%) complete, 12 ok, 0 failed, 0.26 rec/s, eta 7.6s

[16:34:08] [INFO]   |-- 😼 custom column '_privacy_qa_reanswer' progress: 13/14 (93%) complete, 13 ok, 0 failed, 0.26 rec/s, eta 3.8s

[16:34:12] [INFO]   |-- 🦁 custom column '_privacy_qa_reanswer' progress: 14/14 (100%) complete, 14 ok, 0 failed, 0.26 rec/s, eta 0.0s

[16:34:12] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[16:34:12] [INFO]   |-- generator_function: '_quality_compare'

[16:34:12] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:34:12] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[16:34:12] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:34:12] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[16:34:12] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[16:34:21] [INFO]   |-- 🐱 custom column '_quality_qa_compare' progress: 1/14 (7%) complete, 1 ok, 0 failed, 0.11 rec/s, eta 121.9s

[16:34:23] [INFO]   |-- 🐱 custom column '_quality_qa_compare' progress: 2/14 (14%) complete, 2 ok, 0 failed, 0.18 rec/s, eta 65.8s

[16:34:26] [INFO]   |-- 🐱 custom column '_quality_qa_compare' progress: 3/14 (21%) complete, 3 ok, 0 failed, 0.22 rec/s, eta 49.8s

[16:34:28] [INFO]   |-- 😺 custom column '_quality_qa_compare' progress: 4/14 (29%) complete, 4 ok, 0 failed, 0.25 rec/s, eta 40.3s

[16:34:32] [INFO]   |-- 😺 custom column '_quality_qa_compare' progress: 5/14 (36%) complete, 5 ok, 0 failed, 0.25 rec/s, eta 35.3s

[16:34:32] [INFO]   |-- 😺 custom column '_quality_qa_compare' progress: 6/14 (43%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 26.7s

[16:34:34] [INFO]   |-- 😸 custom column '_quality_qa_compare' progress: 7/14 (50%) complete, 7 ok, 0 failed, 0.33 rec/s, eta 21.5s

[16:34:35] [INFO]   |-- 😸 custom column '_quality_qa_compare' progress: 8/14 (57%) complete, 8 ok, 0 failed, 0.35 rec/s, eta 17.2s

[16:34:38] [INFO]   |-- 😸 custom column '_quality_qa_compare' progress: 9/14 (64%) complete, 9 ok, 0 failed, 0.35 rec/s, eta 14.1s

[16:34:44] [INFO]   |-- 😸 custom column '_quality_qa_compare' progress: 10/14 (71%) complete, 10 ok, 0 failed, 0.31 rec/s, eta 12.7s

[16:34:45] [INFO]   |-- 😼 custom column '_quality_qa_compare' progress: 11/14 (79%) complete, 11 ok, 0 failed, 0.33 rec/s, eta 9.0s

[16:34:47] [INFO]   |-- 😼 custom column '_quality_qa_compare' progress: 12/14 (86%) complete, 12 ok, 0 failed, 0.35 rec/s, eta 5.7s

[16:34:48] [INFO]   |-- 😼 custom column '_quality_qa_compare' progress: 13/14 (93%) complete, 13 ok, 0 failed, 0.36 rec/s, eta 2.8s

[16:34:55] [INFO]   |-- 🦁 custom column '_quality_qa_compare' progress: 14/14 (100%) complete, 14 ok, 0 failed, 0.33 rec/s, eta 0.0s

[16:34:55] [INFO] 🔧 Custom column config for column 'utility_score'

[16:34:55] [INFO]   |-- generator_function: '_compute_metrics_columns'

[16:34:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:34:55] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[16:34:55] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[16:34:55] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[16:34:55] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[16:34:55] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[16:34:55] [INFO]   |-- 😴 custom column 'utility_score' progress: 1/14 (7%) complete, 1 ok, 0 failed, 683.68 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😴 custom column 'utility_score' progress: 2/14 (14%) complete, 2 ok, 0 failed, 911.63 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😴 custom column 'utility_score' progress: 3/14 (21%) complete, 3 ok, 0 failed, 1015.29 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🥱 custom column 'utility_score' progress: 4/14 (29%) complete, 4 ok, 0 failed, 1089.91 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🥱 custom column 'utility_score' progress: 5/14 (36%) complete, 5 ok, 0 failed, 1015.54 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🥱 custom column 'utility_score' progress: 6/14 (43%) complete, 6 ok, 0 failed, 1109.35 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😐 custom column 'utility_score' progress: 7/14 (50%) complete, 7 ok, 0 failed, 1216.80 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😐 custom column 'utility_score' progress: 8/14 (57%) complete, 8 ok, 0 failed, 1152.92 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😐 custom column 'utility_score' progress: 9/14 (64%) complete, 9 ok, 0 failed, 1194.82 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😐 custom column 'utility_score' progress: 10/14 (71%) complete, 10 ok, 0 failed, 1240.94 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😊 custom column 'utility_score' progress: 11/14 (79%) complete, 11 ok, 0 failed, 1292.96 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😊 custom column 'utility_score' progress: 12/14 (86%) complete, 12 ok, 0 failed, 1322.51 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 😊 custom column 'utility_score' progress: 13/14 (93%) complete, 13 ok, 0 failed, 1389.14 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🤩 custom column 'utility_score' progress: 14/14 (100%) complete, 14 ok, 0 failed, 1441.13 rec/s, eta 0.0s

[16:34:55] [INFO] 🔧 Custom column config for column '_needs_repair'

[16:34:55] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[16:34:55] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:34:55] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[16:34:55] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[16:34:55] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[16:34:55] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[16:34:55] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 1/14 (7%) complete, 1 ok, 0 failed, 1966.57 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 2/14 (14%) complete, 2 ok, 0 failed, 2242.78 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌧️ custom column '_needs_repair' progress: 3/14 (21%) complete, 3 ok, 0 failed, 2380.56 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 4/14 (29%) complete, 4 ok, 0 failed, 2489.17 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 5/14 (36%) complete, 5 ok, 0 failed, 2505.11 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌦️ custom column '_needs_repair' progress: 6/14 (43%) complete, 6 ok, 0 failed, 2541.65 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 7/14 (50%) complete, 7 ok, 0 failed, 2544.07 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 8/14 (57%) complete, 8 ok, 0 failed, 2534.22 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 9/14 (64%) complete, 9 ok, 0 failed, 2638.88 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- ⛅ custom column '_needs_repair' progress: 10/14 (71%) complete, 10 ok, 0 failed, 2736.29 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 11/14 (79%) complete, 11 ok, 0 failed, 2826.31 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 12/14 (86%) complete, 12 ok, 0 failed, 2890.20 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- 🌤️ custom column '_needs_repair' progress: 13/14 (93%) complete, 13 ok, 0 failed, 2978.92 rec/s, eta 0.0s

[16:34:55] [INFO]   |-- ☀️ custom column '_needs_repair' progress: 14/14 (100%) complete, 14 ok, 0 failed, 3004.43 rec/s, eta 0.0s

[16:34:55] [INFO] 📊 Model usage summary:

[16:34:55] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:34:55] [INFO]   |-- tokens: input=86130, output=112996, total=199126, tps=1453

[16:34:55] [INFO]   |-- requests: success=43, failed=0, total=43, rpm=18

[16:34:55] [INFO] 📐 Measuring dataset column statistics:

[16:34:55] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[16:34:55] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[16:34:55] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[16:34:55] [INFO]   |-- 🔧 column: 'utility_score'

[16:34:55] [INFO]   |-- 🔧 column: '_needs_repair'

[16:34:55] [DEBUG] NDD workflow 'rewrite-evaluate-1' returned 14 records

[16:34:55] [INFO] Evaluate-repair loop iteration 1: 6/22 rows need repair

[16:34:55] [DEBUG] NDD workflow 'rewrite-repair-1' starting with 6 records

[16:34:55] [DEBUG] NDD workflow 'rewrite-repair-1': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[16:34:55] [INFO] 🎨 Creating Data Designer dataset

[16:34:55] [INFO] ✅ Validation passed

[16:34:55] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:34:55] [INFO] 🩺 Running health checks for models...

[16:34:55] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[16:34:56] [INFO]   |-- ✅ Passed!

[16:34:56] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-1' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-1_03-31-2026_163456' instead.

[16:34:56] [INFO] ⏳ Processing batch 1 of 1

[16:34:56] [INFO] 🌱 Sampling 6 records from seed dataset

[16:34:56] [INFO]   |-- seed dataset size: 6 records

[16:34:56] [INFO]   |-- sampling strategy: ordered

[16:34:56] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[16:34:56] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[16:34:56] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:34:56] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[16:34:56] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[16:34:56] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[16:34:56] [INFO]   |-- 🥚 custom column '_leaked_privacy_items' progress: 1/6 (17%) complete, 1 ok, 0 failed, 1228.19 rec/s, eta 0.0s

[16:34:56] [INFO]   |-- 🐣 custom column '_leaked_privacy_items' progress: 2/6 (33%) complete, 2 ok, 0 failed, 1534.48 rec/s, eta 0.0s

[16:34:56] [INFO]   |-- 🐥 custom column '_leaked_privacy_items' progress: 3/6 (50%) complete, 3 ok, 0 failed, 1627.41 rec/s, eta 0.0s

[16:34:56] [INFO]   |-- 🐥 custom column '_leaked_privacy_items' progress: 4/6 (67%) complete, 4 ok, 0 failed, 1711.99 rec/s, eta 0.0s

[16:34:56] [INFO]   |-- 🐤 custom column '_leaked_privacy_items' progress: 5/6 (83%) complete, 5 ok, 0 failed, 1615.38 rec/s, eta 0.0s

[16:34:56] [INFO]   |-- 🐔 custom column '_leaked_privacy_items' progress: 6/6 (100%) complete, 6 ok, 0 failed, 1631.60 rec/s, eta 0.0s

[16:34:56] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[16:34:56] [INFO]   |-- generator_function: '_repair_column'

[16:34:56] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:34:56] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[16:34:56] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[16:34:56] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[16:34:56] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[16:34:56] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[16:35:01] [INFO]   |-- 🥚 custom column '_rewritten_text__next' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.19 rec/s, eta 26.9s

[16:35:02] [INFO]   |-- 🐣 custom column '_rewritten_text__next' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.33 rec/s, eta 12.0s

[16:35:06] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.29 rec/s, eta 10.4s

[16:35:09] [INFO]   |-- 🐥 custom column '_rewritten_text__next' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.29 rec/s, eta 6.9s

[16:35:12] [INFO]   |-- 🐤 custom column '_rewritten_text__next' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.31 rec/s, eta 3.2s

[16:35:15] [INFO]   |-- 🐔 custom column '_rewritten_text__next' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 0.0s

[16:35:16] [INFO] 📊 Model usage summary:

[16:35:16] [INFO]   |-- model: openai/gpt-oss-120b

[16:35:16] [INFO]   |-- tokens: input=17694, output=10793, total=28487, tps=1412

[16:35:16] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=17

[16:35:16] [INFO] 📐 Measuring dataset column statistics:

[16:35:16] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[16:35:16] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[16:35:16] [DEBUG] NDD workflow 'rewrite-repair-1' returned 6 records

[16:35:16] [DEBUG] NDD workflow 'rewrite-evaluate-2' starting with 6 records

[16:35:16] [DEBUG] NDD workflow 'rewrite-evaluate-2': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[16:35:16] [INFO] 🎨 Creating Data Designer dataset

[16:35:16] [INFO] ✅ Validation passed

[16:35:16] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:35:16] [INFO] 🩺 Running health checks for models...

[16:35:16] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:35:17] [INFO]   |-- ✅ Passed!

[16:35:17] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-2' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-2_03-31-2026_163517' instead.

[16:35:17] [INFO] ⏳ Processing batch 1 of 1

[16:35:17] [INFO] 🌱 Sampling 6 records from seed dataset

[16:35:17] [INFO]   |-- seed dataset size: 6 records

[16:35:17] [INFO]   |-- sampling strategy: ordered

[16:35:17] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[16:35:17] [INFO]   |-- generator_function: '_quality_reanswer'

[16:35:17] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:35:17] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[16:35:17] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:35:17] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[16:35:17] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[16:35:22] [INFO]   |-- 😴 custom column '_quality_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.24 rec/s, eta 20.9s

[16:35:23] [INFO]   |-- 🥱 custom column '_quality_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.35 rec/s, eta 11.3s

[16:35:26] [INFO]   |-- 😐 custom column '_quality_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.33 rec/s, eta 9.0s

[16:35:27] [INFO]   |-- 😐 custom column '_quality_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.42 rec/s, eta 4.7s

[16:35:29] [INFO]   |-- 😊 custom column '_quality_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.43 rec/s, eta 2.3s

[16:35:31] [INFO]   |-- 🤩 custom column '_quality_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.45 rec/s, eta 0.0s

[16:35:31] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[16:35:31] [INFO]   |-- generator_function: '_privacy_reanswer'

[16:35:31] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:35:31] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[16:35:31] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:35:31] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[16:35:31] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[16:35:36] [INFO]   |-- 🥚 custom column '_privacy_qa_reanswer' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.21 rec/s, eta 24.2s

[16:35:37] [INFO]   |-- 🐣 custom column '_privacy_qa_reanswer' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.30 rec/s, eta 13.5s

[16:35:40] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.32 rec/s, eta 9.3s

[16:35:40] [INFO]   |-- 🐥 custom column '_privacy_qa_reanswer' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.42 rec/s, eta 4.7s

[16:35:44] [INFO]   |-- 🐤 custom column '_privacy_qa_reanswer' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.38 rec/s, eta 2.6s

[16:35:51] [INFO]   |-- 🐔 custom column '_privacy_qa_reanswer' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.30 rec/s, eta 0.0s

[16:35:51] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[16:35:51] [INFO]   |-- generator_function: '_quality_compare'

[16:35:51] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:35:51] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[16:35:51] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:35:51] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[16:35:51] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[16:35:59] [INFO]   |-- 🚶 custom column '_quality_qa_compare' progress: 1/6 (17%) complete, 1 ok, 0 failed, 0.12 rec/s, eta 41.7s

[16:36:01] [INFO]   |-- 🐴 custom column '_quality_qa_compare' progress: 2/6 (33%) complete, 2 ok, 0 failed, 0.20 rec/s, eta 20.0s

[16:36:03] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 3/6 (50%) complete, 3 ok, 0 failed, 0.24 rec/s, eta 12.6s

[16:36:04] [INFO]   |-- 🚗 custom column '_quality_qa_compare' progress: 4/6 (67%) complete, 4 ok, 0 failed, 0.31 rec/s, eta 6.5s

[16:36:07] [INFO]   |-- ✈️ custom column '_quality_qa_compare' progress: 5/6 (83%) complete, 5 ok, 0 failed, 0.30 rec/s, eta 3.3s

[16:36:09] [INFO]   |-- 🚀 custom column '_quality_qa_compare' progress: 6/6 (100%) complete, 6 ok, 0 failed, 0.34 rec/s, eta 0.0s

[16:36:09] [INFO] 🔧 Custom column config for column 'utility_score'

[16:36:09] [INFO]   |-- generator_function: '_compute_metrics_columns'

[16:36:09] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:09] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[16:36:09] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[16:36:09] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[16:36:09] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[16:36:09] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[16:36:09] [INFO]   |-- 😴 custom column 'utility_score' progress: 1/6 (17%) complete, 1 ok, 0 failed, 963.47 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🥱 custom column 'utility_score' progress: 2/6 (33%) complete, 2 ok, 0 failed, 1195.40 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 😐 custom column 'utility_score' progress: 3/6 (50%) complete, 3 ok, 0 failed, 1227.14 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 😐 custom column 'utility_score' progress: 4/6 (67%) complete, 4 ok, 0 failed, 1303.34 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 😊 custom column 'utility_score' progress: 5/6 (83%) complete, 5 ok, 0 failed, 1264.44 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🤩 custom column 'utility_score' progress: 6/6 (100%) complete, 6 ok, 0 failed, 1301.82 rec/s, eta 0.0s

[16:36:09] [INFO] 🔧 Custom column config for column '_needs_repair'

[16:36:09] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[16:36:09] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:09] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[16:36:09] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[16:36:09] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[16:36:09] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[16:36:09] [INFO]   |-- 🌑 custom column '_needs_repair' progress: 1/6 (17%) complete, 1 ok, 0 failed, 1541.72 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🌘 custom column '_needs_repair' progress: 2/6 (33%) complete, 2 ok, 0 failed, 2055.32 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 3/6 (50%) complete, 3 ok, 0 failed, 2000.72 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🌗 custom column '_needs_repair' progress: 4/6 (67%) complete, 4 ok, 0 failed, 2133.76 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🌖 custom column '_needs_repair' progress: 5/6 (83%) complete, 5 ok, 0 failed, 2140.95 rec/s, eta 0.0s

[16:36:09] [INFO]   |-- 🌕 custom column '_needs_repair' progress: 6/6 (100%) complete, 6 ok, 0 failed, 2084.66 rec/s, eta 0.0s

[16:36:09] [INFO] 📊 Model usage summary:

[16:36:09] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:36:09] [INFO]   |-- tokens: input=34580, output=41285, total=75865, tps=1471

[16:36:09] [INFO]   |-- requests: success=18, failed=0, total=18, rpm=20

[16:36:09] [INFO] 📐 Measuring dataset column statistics:

[16:36:09] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[16:36:09] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[16:36:09] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[16:36:09] [INFO]   |-- 🔧 column: 'utility_score'

[16:36:09] [INFO]   |-- 🔧 column: '_needs_repair'

[16:36:09] [DEBUG] NDD workflow 'rewrite-evaluate-2' returned 6 records

[16:36:09] [INFO] Evaluate-repair loop iteration 2: 5/22 rows need repair

[16:36:09] [DEBUG] NDD workflow 'rewrite-repair-2' starting with 5 records

[16:36:09] [DEBUG] NDD workflow 'rewrite-repair-2': 2 columns ['_leaked_privacy_items', '_rewritten_text__next']

[16:36:09] [INFO] 🎨 Creating Data Designer dataset

[16:36:09] [INFO] ✅ Validation passed

[16:36:09] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:36:09] [INFO] 🩺 Running health checks for models...

[16:36:09] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...

[16:36:10] [INFO]   |-- ✅ Passed!

[16:36:10] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-repair-2' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-repair-2_03-31-2026_163610' instead.

[16:36:10] [INFO] ⏳ Processing batch 1 of 1

[16:36:10] [INFO] 🌱 Sampling 5 records from seed dataset

[16:36:10] [INFO]   |-- seed dataset size: 5 records

[16:36:10] [INFO]   |-- sampling strategy: ordered

[16:36:10] [INFO] 🔧 Custom column config for column '_leaked_privacy_items'

[16:36:10] [INFO]   |-- generator_function: '_inject_leaked_items_column'

[16:36:10] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:10] [INFO]   |-- required_columns: ['_privacy_qa_reanswer', '_privacy_qa']

[16:36:10] [INFO] ⚡️ Processing custom column '_leaked_privacy_items' with 4 concurrent workers

[16:36:10] [INFO] ⏱️ custom column '_leaked_privacy_items' will report progress after each record

[16:36:10] [INFO]   |-- 🌧️ custom column '_leaked_privacy_items' progress: 1/5 (20%) complete, 1 ok, 0 failed, 1376.46 rec/s, eta 0.0s

[16:36:10] [INFO]   |-- 🌦️ custom column '_leaked_privacy_items' progress: 2/5 (40%) complete, 2 ok, 0 failed, 1762.83 rec/s, eta 0.0s

[16:36:10] [INFO]   |-- ⛅ custom column '_leaked_privacy_items' progress: 3/5 (60%) complete, 3 ok, 0 failed, 1908.70 rec/s, eta 0.0s

[16:36:10] [INFO]   |-- 🌤️ custom column '_leaked_privacy_items' progress: 4/5 (80%) complete, 4 ok, 0 failed, 2066.74 rec/s, eta 0.0s

[16:36:10] [INFO]   |-- ☀️ custom column '_leaked_privacy_items' progress: 5/5 (100%) complete, 5 ok, 0 failed, 2121.64 rec/s, eta 0.0s

[16:36:10] [INFO] 🔧 Custom column config for column '_rewritten_text__next'

[16:36:10] [INFO]   |-- generator_function: '_repair_column'

[16:36:10] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:10] [INFO]   |-- required_columns: ['_leaked_privacy_items', '_rewritten_text', '_sensitivity_disposition', '__nemo_anonymizer_text_input__', '_replacement_map_for_prompt', 'leakage_mass', 'any_high_leaked', 'utility_score']

[16:36:10] [INFO]   |-- model_aliases: ['gpt-oss-120b']

[16:36:10] [INFO]   |-- generator_params: privacy_goal_str='PROTECT: All personal identifiers, case numbers, court names, and institutional references that could identify parties\nPRESERVE: Legal reasoning, procedural facts, statutory references, and the structure of the ruling' max_privacy_leak=0.6

[16:36:10] [INFO] ⚡️ Processing custom column '_rewritten_text__next' with 4 concurrent workers

[16:36:10] [INFO] ⏱️ custom column '_rewritten_text__next' will report progress after each record

[16:36:14] [INFO]   |-- 🌧️ custom column '_rewritten_text__next' progress: 1/5 (20%) complete, 1 ok, 0 failed, 0.23 rec/s, eta 17.1s

[16:36:16] [INFO]   |-- 🌦️ custom column '_rewritten_text__next' progress: 2/5 (40%) complete, 2 ok, 0 failed, 0.31 rec/s, eta 9.6s

[16:36:16] [INFO]   |-- ⛅ custom column '_rewritten_text__next' progress: 3/5 (60%) complete, 3 ok, 0 failed, 0.44 rec/s, eta 4.6s

[16:36:22] [INFO]   |-- 🌤️ custom column '_rewritten_text__next' progress: 4/5 (80%) complete, 4 ok, 0 failed, 0.33 rec/s, eta 3.0s

[16:36:26] [INFO]   |-- ☀️ custom column '_rewritten_text__next' progress: 5/5 (100%) complete, 5 ok, 0 failed, 0.30 rec/s, eta 0.0s

[16:36:26] [INFO] 📊 Model usage summary:

[16:36:26] [INFO]   |-- model: openai/gpt-oss-120b

[16:36:26] [INFO]   |-- tokens: input=14057, output=8932, total=22989, tps=1358

[16:36:26] [INFO]   |-- requests: success=5, failed=0, total=5, rpm=17

[16:36:26] [INFO] 📐 Measuring dataset column statistics:

[16:36:26] [INFO]   |-- 🔧 column: '_leaked_privacy_items'

[16:36:26] [INFO]   |-- 🔧 column: '_rewritten_text__next'

[16:36:26] [DEBUG] NDD workflow 'rewrite-repair-2' returned 5 records

[16:36:26] [DEBUG] NDD workflow 'rewrite-evaluate-3' starting with 5 records

[16:36:26] [DEBUG] NDD workflow 'rewrite-evaluate-3': 5 columns ['_quality_qa_reanswer', '_privacy_qa_reanswer', '_quality_qa_compare', 'utility_score', '_needs_repair']

[16:36:26] [INFO] 🎨 Creating Data Designer dataset

[16:36:26] [INFO] ✅ Validation passed

[16:36:26] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:36:26] [INFO] 🩺 Running health checks for models...

[16:36:26] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:36:28] [INFO]   |-- ✅ Passed!

[16:36:28] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-evaluate-3' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-evaluate-3_03-31-2026_163628' instead.

[16:36:28] [INFO] ⏳ Processing batch 1 of 1

[16:36:28] [INFO] 🌱 Sampling 5 records from seed dataset

[16:36:28] [INFO]   |-- seed dataset size: 5 records

[16:36:28] [INFO]   |-- sampling strategy: ordered

[16:36:28] [INFO] 🔧 Custom column config for column '_quality_qa_reanswer'

[16:36:28] [INFO]   |-- generator_function: '_quality_reanswer'

[16:36:28] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:28] [INFO]   |-- required_columns: ['_quality_qa', '_rewritten_text']

[16:36:28] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:36:28] [INFO] ⚡️ Processing custom column '_quality_qa_reanswer' with 4 concurrent workers

[16:36:28] [INFO] ⏱️ custom column '_quality_qa_reanswer' will report progress after each record

[16:36:34] [INFO]   |-- 😴 custom column '_quality_qa_reanswer' progress: 1/5 (20%) complete, 1 ok, 0 failed, 0.17 rec/s, eta 23.1s

[16:36:35] [INFO]   |-- 🥱 custom column '_quality_qa_reanswer' progress: 2/5 (40%) complete, 2 ok, 0 failed, 0.27 rec/s, eta 10.9s

[16:36:36] [INFO]   |-- 😐 custom column '_quality_qa_reanswer' progress: 3/5 (60%) complete, 3 ok, 0 failed, 0.38 rec/s, eta 5.2s

[16:36:40] [INFO]   |-- 😊 custom column '_quality_qa_reanswer' progress: 4/5 (80%) complete, 4 ok, 0 failed, 0.34 rec/s, eta 2.9s

[16:36:41] [INFO]   |-- 🤩 custom column '_quality_qa_reanswer' progress: 5/5 (100%) complete, 5 ok, 0 failed, 0.38 rec/s, eta 0.0s

[16:36:41] [INFO] 🔧 Custom column config for column '_privacy_qa_reanswer'

[16:36:41] [INFO]   |-- generator_function: '_privacy_reanswer'

[16:36:41] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:41] [INFO]   |-- required_columns: ['_privacy_qa', '_rewritten_text']

[16:36:41] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:36:41] [INFO] ⚡️ Processing custom column '_privacy_qa_reanswer' with 4 concurrent workers

[16:36:41] [INFO] ⏱️ custom column '_privacy_qa_reanswer' will report progress after each record

[16:36:46] [INFO]   |-- 🌑 custom column '_privacy_qa_reanswer' progress: 1/5 (20%) complete, 1 ok, 0 failed, 0.20 rec/s, eta 20.3s

[16:36:50] [INFO]   |-- 🌘 custom column '_privacy_qa_reanswer' progress: 2/5 (40%) complete, 2 ok, 0 failed, 0.23 rec/s, eta 12.9s

[16:36:51] [INFO]   |-- 🌗 custom column '_privacy_qa_reanswer' progress: 3/5 (60%) complete, 3 ok, 0 failed, 0.30 rec/s, eta 6.7s

[16:36:52] [INFO]   |-- 🌖 custom column '_privacy_qa_reanswer' progress: 4/5 (80%) complete, 4 ok, 0 failed, 0.38 rec/s, eta 2.6s

[16:36:54] [INFO]   |-- 🌕 custom column '_privacy_qa_reanswer' progress: 5/5 (100%) complete, 5 ok, 0 failed, 0.39 rec/s, eta 0.0s

[16:36:54] [INFO] 🔧 Custom column config for column '_quality_qa_compare'

[16:36:54] [INFO]   |-- generator_function: '_quality_compare'

[16:36:54] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:36:54] [INFO]   |-- required_columns: ['_quality_qa', '_quality_qa_reanswer']

[16:36:54] [INFO]   |-- model_aliases: ['nemotron-30b-thinking']

[16:36:54] [INFO] ⚡️ Processing custom column '_quality_qa_compare' with 4 concurrent workers

[16:36:54] [INFO] ⏱️ custom column '_quality_qa_compare' will report progress after each record

[16:37:00] [INFO]   |-- 🐱 custom column '_quality_qa_compare' progress: 1/5 (20%) complete, 1 ok, 0 failed, 0.16 rec/s, eta 24.3s

[16:37:03] [INFO]   |-- 😺 custom column '_quality_qa_compare' progress: 2/5 (40%) complete, 2 ok, 0 failed, 0.21 rec/s, eta 14.3s

[16:37:03] [INFO]   |-- 😸 custom column '_quality_qa_compare' progress: 3/5 (60%) complete, 3 ok, 0 failed, 0.32 rec/s, eta 6.3s

[16:37:07] [INFO]   |-- 😼 custom column '_quality_qa_compare' progress: 4/5 (80%) complete, 4 ok, 0 failed, 0.31 rec/s, eta 3.3s

[16:37:07] [INFO]   |-- 🦁 custom column '_quality_qa_compare' progress: 5/5 (100%) complete, 5 ok, 0 failed, 0.38 rec/s, eta 0.0s

[16:37:07] [INFO] 🔧 Custom column config for column 'utility_score'

[16:37:07] [INFO]   |-- generator_function: '_compute_metrics_columns'

[16:37:07] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:37:07] [INFO]   |-- required_columns: ['_quality_qa_compare', '_privacy_qa_reanswer', '_privacy_qa', '_quality_qa']

[16:37:07] [INFO]   |-- side_effect_columns: ['leakage_mass', 'any_high_leaked']

[16:37:07] [INFO]   |-- generator_params: sensitivity_weights={'high': 1.0, 'medium': 0.6, 'low': 0.3}

[16:37:07] [INFO] ⚡️ Processing custom column 'utility_score' with 4 concurrent workers

[16:37:07] [INFO] ⏱️ custom column 'utility_score' will report progress after each record

[16:37:07] [INFO]   |-- 🐱 custom column 'utility_score' progress: 1/5 (20%) complete, 1 ok, 0 failed, 669.94 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 😺 custom column 'utility_score' progress: 2/5 (40%) complete, 2 ok, 0 failed, 925.28 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 😸 custom column 'utility_score' progress: 3/5 (60%) complete, 3 ok, 0 failed, 1051.85 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 😼 custom column 'utility_score' progress: 4/5 (80%) complete, 4 ok, 0 failed, 1184.61 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 🦁 custom column 'utility_score' progress: 5/5 (100%) complete, 5 ok, 0 failed, 1264.26 rec/s, eta 0.0s

[16:37:07] [INFO] 🔧 Custom column config for column '_needs_repair'

[16:37:07] [INFO]   |-- generator_function: '_determine_repair_needs_column'

[16:37:07] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:37:07] [INFO]   |-- required_columns: ['any_high_leaked', 'leakage_mass']

[16:37:07] [INFO]   |-- generator_params: auto_repair_privacy=True repair_any_high_leak=True effective_threshold=0.6

[16:37:07] [INFO] ⚡️ Processing custom column '_needs_repair' with 4 concurrent workers

[16:37:07] [INFO] ⏱️ custom column '_needs_repair' will report progress after each record

[16:37:07] [INFO]   |-- 🚶 custom column '_needs_repair' progress: 1/5 (20%) complete, 1 ok, 0 failed, 1456.49 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 🐴 custom column '_needs_repair' progress: 2/5 (40%) complete, 2 ok, 0 failed, 1913.42 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 🚗 custom column '_needs_repair' progress: 3/5 (60%) complete, 3 ok, 0 failed, 2026.46 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- ✈️ custom column '_needs_repair' progress: 4/5 (80%) complete, 4 ok, 0 failed, 2264.69 rec/s, eta 0.0s

[16:37:07] [INFO]   |-- 🚀 custom column '_needs_repair' progress: 5/5 (100%) complete, 5 ok, 0 failed, 2288.46 rec/s, eta 0.0s

[16:37:08] [INFO] 📊 Model usage summary:

[16:37:08] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:37:08] [INFO]   |-- tokens: input=28500, output=32960, total=61460, tps=1553

[16:37:08] [INFO]   |-- requests: success=15, failed=0, total=15, rpm=22

[16:37:08] [INFO] 📐 Measuring dataset column statistics:

[16:37:08] [INFO]   |-- 🔧 column: '_quality_qa_reanswer'

[16:37:08] [INFO]   |-- 🔧 column: '_privacy_qa_reanswer'

[16:37:08] [INFO]   |-- 🔧 column: '_quality_qa_compare'

[16:37:08] [INFO]   |-- 🔧 column: 'utility_score'

[16:37:08] [INFO]   |-- 🔧 column: '_needs_repair'

[16:37:08] [DEBUG] NDD workflow 'rewrite-evaluate-3' returned 5 records

[16:37:08] [DEBUG] NDD workflow 'rewrite-final-judge' starting with 22 records

[16:37:08] [DEBUG] NDD workflow 'rewrite-final-judge': 2 columns ['_judge_evaluation', 'needs_human_review']

[16:37:08] [INFO] 🎨 Creating Data Designer dataset

[16:37:08] [INFO] ✅ Validation passed

[16:37:08] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:37:08] [INFO] 🩺 Running health checks for models...

[16:37:08] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...

[16:37:09] [INFO]   |-- ✅ Passed!

[16:37:09] [INFO] 📂 Dataset path '.anonymizer-artifacts/rewrite-final-judge' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/rewrite-final-judge_03-31-2026_163709' instead.

[16:37:10] [INFO] ⏳ Processing batch 1 of 1

[16:37:10] [INFO] 🌱 Sampling 22 records from seed dataset

[16:37:10] [INFO]   |-- seed dataset size: 22 records

[16:37:10] [INFO]   |-- sampling strategy: ordered

[16:37:10] [INFO] ⚖️ llm-judge model config for column '_judge_evaluation'

[16:37:10] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:37:10] [INFO]   |-- model alias: 'nemotron-30b-thinking'

[16:37:10] [INFO]   |-- model provider: 'nvidia'

[16:37:10] [INFO]   |-- inference parameters:

[16:37:10] [INFO]   |  |-- generation_type=chat-completion

[16:37:10] [INFO]   |  |-- max_parallel_requests=16

[16:37:10] [INFO]   |  |-- timeout=300

[16:37:10] [INFO]   |  |-- temperature=0.40

[16:37:10] [INFO]   |  |-- top_p=1.00

[16:37:10] [INFO]   |  |-- max_tokens=8192

[16:37:10] [INFO] ⚡️ Processing llm-judge column '_judge_evaluation' with 16 concurrent workers

[16:37:10] [INFO] ⏱️ llm-judge column '_judge_evaluation' will report progress every 2 records

[16:37:14] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 2/22 (9%) complete, 2 ok, 0 failed, 0.44 rec/s, eta 45.5s

[16:37:14] [INFO]   |-- 😴 llm-judge column '_judge_evaluation' progress: 4/22 (18%) complete, 4 ok, 0 failed, 0.85 rec/s, eta 21.2s

[16:37:15] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 6/22 (27%) complete, 6 ok, 0 failed, 1.20 rec/s, eta 13.4s

[16:37:15] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 8/22 (36%) complete, 8 ok, 0 failed, 1.34 rec/s, eta 10.4s

[16:37:16] [INFO]   |-- 🥱 llm-judge column '_judge_evaluation' progress: 10/22 (45%) complete, 10 ok, 0 failed, 1.63 rec/s, eta 7.4s

[16:37:17] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 12/22 (55%) complete, 12 ok, 0 failed, 1.57 rec/s, eta 6.4s

[16:37:18] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 14/22 (64%) complete, 14 ok, 0 failed, 1.72 rec/s, eta 4.7s

[16:37:19] [INFO]   |-- 😐 llm-judge column '_judge_evaluation' progress: 16/22 (73%) complete, 16 ok, 0 failed, 1.73 rec/s, eta 3.5s

[16:37:19] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 18/22 (82%) complete, 18 ok, 0 failed, 1.89 rec/s, eta 2.1s

[16:37:21] [INFO]   |-- 😊 llm-judge column '_judge_evaluation' progress: 20/22 (91%) complete, 20 ok, 0 failed, 1.75 rec/s, eta 1.1s

[16:38:01] [INFO]   |-- 🤩 llm-judge column '_judge_evaluation' progress: 22/22 (100%) complete, 22 ok, 0 failed, 0.42 rec/s, eta 0.0s

[16:38:01] [INFO] 🔧 Custom column config for column 'needs_human_review'

[16:38:01] [INFO]   |-- generator_function: '_determine_needs_human_review'

[16:38:01] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>

[16:38:01] [INFO]   |-- required_columns: ['_rewritten_text', 'utility_score', 'leakage_mass', 'any_high_leaked']

[16:38:01] [INFO]   |-- generator_params: flag_utility_below=0.5 flag_leakage_mass_above=2.0

[16:38:01] [INFO] ⚡️ Processing custom column 'needs_human_review' with 4 concurrent workers

[16:38:01] [INFO] ⏱️ custom column 'needs_human_review' will report progress every 2 records

[16:38:01] [INFO]   |-- 🌑 custom column 'needs_human_review' progress: 2/22 (9%) complete, 2 ok, 0 failed, 1745.01 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌑 custom column 'needs_human_review' progress: 4/22 (18%) complete, 4 ok, 0 failed, 1965.92 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 6/22 (27%) complete, 6 ok, 0 failed, 2149.51 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 8/22 (36%) complete, 8 ok, 0 failed, 2378.65 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌘 custom column 'needs_human_review' progress: 10/22 (45%) complete, 10 ok, 0 failed, 2444.64 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 12/22 (55%) complete, 12 ok, 0 failed, 2535.37 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 14/22 (64%) complete, 14 ok, 0 failed, 2728.20 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌗 custom column 'needs_human_review' progress: 16/22 (73%) complete, 16 ok, 0 failed, 2836.36 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌖 custom column 'needs_human_review' progress: 18/22 (82%) complete, 18 ok, 0 failed, 2919.25 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌖 custom column 'needs_human_review' progress: 20/22 (91%) complete, 20 ok, 0 failed, 2984.83 rec/s, eta 0.0s

[16:38:01] [INFO]   |-- 🌕 custom column 'needs_human_review' progress: 22/22 (100%) complete, 22 ok, 0 failed, 3065.45 rec/s, eta 0.0s

[16:38:02] [INFO] 📊 Model usage summary:

[16:38:02] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:38:02] [INFO]   |-- tokens: input=64353, output=47087, total=111440, tps=2132

[16:38:02] [INFO]   |-- requests: success=24, failed=0, total=24, rpm=27

[16:38:02] [INFO] 📐 Measuring dataset column statistics:

[16:38:02] [INFO]   |-- ⚖️ column: '_judge_evaluation'

[16:38:02] [INFO]   |-- 🔧 column: 'needs_human_review'

[16:38:02] [DEBUG] NDD workflow 'rewrite-final-judge' returned 22 records

/Users/lramaswamy/Documents/github/Anonymizer/src/anonymizer/engine/rewrite/rewrite_workflow.py:86: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(list(parts), ignore_index=True)
[16:38:02] [INFO]   |-- 📋 Rewrite complete (2 failed) [1832.3s]

[16:38:02] [WARNING] 3 record(s) failed during pipeline processing.

[16:38:02] [DEBUG]   704b4c6865a458fe8cdd799f633bdb08 (entity-detection: Record missing from workflow output)

[16:38:02] [DEBUG]   53ab2db826735fb9b51f8432e5107099 (rewrite-pipeline: Record missing from workflow output)

[16:38:02] [DEBUG]   837d3b2295fa566a9d9b710a17418a74 (rewrite-pipeline: Record missing from workflow output)

[16:38:02] [INFO] 🎉 Pipeline complete — 25 records processed, 3 total failures

AnonymizerResult(rows=22, columns=6, trace_columns=45, failed_records=3)

,text,text_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
0,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,1.0,1.6,True,True
1,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.946667,0.6,False,False
2,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.918182,1.0,True,True
3,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.992857,0.0,False,False
4,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.264286,0.0,False,True

In [7]:
result.dataframe[["text_rewritten", "utility_score", "leakage_mass", "needs_human_review"]].head()

,text_rewritten,utility_score,leakage_mass,needs_human_review
0,PROCEDURE The case originated in an applicati...,1.0,1.6,True
1,PROCEDURE The case originated in an applicati...,0.946667,0.6,False
2,PROCEDURE The case originated in an applicati...,0.918182,1.0,True
3,PROCEDURE The case originated in an applicati...,0.992857,0.0,False
4,PROCEDURE The case originated in an applicati...,0.264286,0.0,True

## Filter by review flag

In [8]:
df = result.dataframe
flagged = df[df["needs_human_review"] == True]  # noqa: E712
print(f"{len(flagged)} of {len(df)} records flagged for human review")
flagged.head()

5 of 22 records flagged for human review

,text,text_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
0,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,1.0,1.6,True,True
2,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.918182,1.0,True,True
4,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.264286,0.0,False,True
14,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,0.971429,6.8,True,True
15,PROCEDURE The case originated in an applicati...,PROCEDURE The case originated in an applicati...,1.0,1.0,True,True