# Rewrite Mode

Instead of replacing entities with tokens, rewrite mode generates a
privacy-safe paraphrase of the entire text. The pipeline:

1. Detects entities (same as replace mode)
2. Classifies the domain and assigns sensitivity dispositions
3. Generates a rewritten version that obscures sensitive entities
4. Evaluates quality (utility) and privacy (leakage) with an automated repair loop
5. Runs a final LLM judge for informational scores

The result includes **utility_score**, **leakage_mass**, and a
**needs_human_review** flag so you can triage records that need attention.

## Setup

In [1]:
from pathlib import Path

try:
    NOTEBOOK_SOURCE_DIR = Path(__file__).resolve().parent
except NameError:
    NOTEBOOK_SOURCE_DIR = Path.cwd().parent / "notebook_source"

from anonymizer import Anonymizer, AnonymizerConfig, AnonymizerInput, LoggingConfig, Rewrite, configure_logging

configure_logging(LoggingConfig.debug())

In [2]:
anonymizer = Anonymizer()

[12:08:14] [INFO] 🔧 Anonymizer initialized with 3 model configs
[12:08:14] [INFO]   |-- 🔎 detector:  gliner-pii-detector
[12:08:14] [INFO]   |-- ✅ validator: gpt-oss-120b
[12:08:14] [INFO]   |-- 🧩 augmenter: gpt-oss-120b
[12:08:14] [DEBUG] NDD adapter: artifact_path=.anonymizer-artifacts

## Input data

In [3]:
input_data = AnonymizerInput(
    source=str(NOTEBOOK_SOURCE_DIR / "data" / "synth_bios_sample10.csv"),
    text_column="bio",
    data_summary="Biographical profiles",
)

## Basic rewrite

`Rewrite()` with no arguments uses sensible defaults:
conservative risk tolerance, up to 2 repair iterations, and an
auto-populated privacy goal.

In [4]:
config = AnonymizerConfig(rewrite=Rewrite())

preview = anonymizer.preview(
    config=config,
    data=input_data,
    num_records=10,
)

preview.display_record(0)

[12:08:25] [INFO] 📂 Loaded 10 records from /Users/lramaswamy/Documents/github/Anonymizer/docs/notebook_source/data/synth_bios_sample10.csv (column: 'bio')
[12:08:25] [DEBUG] input text lengths: min=1529, max=1843, mean=1661 chars (10 records)
[12:08:25] [DEBUG] detection config: threshold=0.30, labels=(default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)
[12:08:25] [INFO]   |-- 👀 Preview mode: processing 10 of 10 records
[12:08:25] [INFO] 🔍 Running entity detection on 10 records
[12:08:25] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b

[12:08:25] [DEBUG] NDD workflow 'entity-detection' starting with 10 records
[12:08:25] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']
[12:08:25] [INFO] 🖼️ Preview generation in progress
[12:08:32] [INFO] ✅ Validation passed
[12:08:32] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[12:08:32] [INFO] 🩺 Running health checks for models...
[12:08:32] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...
[12:08:34] [INFO]   |-- ✅ Passed!
[12:08:34] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...
[12:08:34] [INFO]   |-- ✅ Passed!
[12:08:34] [INFO] 🌱 Sampling 10 records from seed dataset
[12:08:34] [INFO]   |-- seed dataset size: 10 records
[12:08:34] [INFO]   |-- sampling strategy: ordered
[12:08:34] [INFO] 📝 llm-text model config for column '_raw_detected_entities'
[12:08:34] [INFO]   |-- model: 'nvidia/gliner-pii'
[12:08:34] [INFO]   |-- model alias: 'gliner-pii-detector'
[12:08:34] [INFO]   |-- model provider: 'nvidia'
[12:08:34] [INFO]   |-- inference parameters:
[12:08:34] [INFO]   |  |-- generation_type=chat-completion
[12:08:34] [INFO]   |  |-- max_parallel_requests=16
[12:08:34] [INFO]   |  |-- timeout=120
[12:08:34] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}
[12:08:34] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers
[12:08:34] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record
[12:08:35] [INFO]   |-- 🥚 llm-text column '_raw_detected_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 2.25 rec/s, eta 4.0s
[12:08:36] [INFO]   |-- 🥚 llm-text column '_raw_detected_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 1.32 rec/s, eta 6.1s
[12:08:36] [INFO]   |-- 🐣 llm-text column '_raw_detected_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 1.79 rec/s, eta 3.9s
[12:08:36] [INFO]   |-- 🐣 llm-text column '_raw_detected_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 2.18 rec/s, eta 2.8s
[12:08:36] [INFO]   |-- 🐥 llm-text column '_raw_detected_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 2.48 rec/s, eta 2.0s
[12:08:36] [INFO]   |-- 🐥 llm-text column '_raw_detected_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 2.97 rec/s, eta 1.3s
[12:08:37] [INFO]   |-- 🐥 llm-text column '_raw_detected_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 3.45 rec/s, eta 0.9s
[12:08:37] [INFO]   |-- 🐤 llm-text column '_raw_detected_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 3.94 rec/s, eta 0.5s
[12:08:37] [INFO]   |-- 🐤 llm-text column '_raw_detected_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 3.20 rec/s, eta 0.3s
[12:08:39] [INFO]   |-- 🐔 llm-text column '_raw_detected_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 2.12 rec/s, eta 0.0s
[12:08:39] [INFO] 🔧 Custom column config for column '_seed_entities'
[12:08:39] [INFO]   |-- generator_function: 'parse_detected_entities'
[12:08:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:08:39] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']
[12:08:39] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']
[12:08:39] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers
[12:08:39] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record
[12:08:39] [INFO]   |-- 🌑 custom column '_seed_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 531.01 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌑 custom column '_seed_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 676.46 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌘 custom column '_seed_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 757.61 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌘 custom column '_seed_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 735.89 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌗 custom column '_seed_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 734.26 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌗 custom column '_seed_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 812.90 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌗 custom column '_seed_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 794.12 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌖 custom column '_seed_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 723.12 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌖 custom column '_seed_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 590.38 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🌕 custom column '_seed_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 628.68 rec/s, eta 0.0s
[12:08:39] [INFO] 🔧 Custom column config for column '_validation_candidates'
[12:08:39] [INFO]   |-- generator_function: 'prepare_validation_inputs'
[12:08:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:08:39] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']
[12:08:39] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[12:08:39] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers
[12:08:39] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record
[12:08:39] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 1/10 (10%) complete, 1 ok, 0 failed, 1229.26 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 2/10 (20%) complete, 2 ok, 0 failed, 1642.49 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 3/10 (30%) complete, 3 ok, 0 failed, 1165.14 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1343.00 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 5/10 (50%) complete, 5 ok, 0 failed, 1341.71 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1445.72 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1611.05 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1583.01 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1706.61 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🦁 custom column '_validation_candidates' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1794.70 rec/s, eta 0.0s
[12:08:39] [INFO] 🔧 Custom column config for column '_validation_skeleton'
[12:08:39] [INFO]   |-- generator_function: 'build_validation_skeleton'
[12:08:39] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:08:39] [INFO]   |-- required_columns: ['_validation_candidates']
[12:08:39] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers
[12:08:39] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record
[12:08:39] [INFO]   |-- 😴 custom column '_validation_skeleton' progress: 1/10 (10%) complete, 1 ok, 0 failed, 2059.73 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😴 custom column '_validation_skeleton' progress: 2/10 (20%) complete, 2 ok, 0 failed, 2806.69 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🥱 custom column '_validation_skeleton' progress: 3/10 (30%) complete, 3 ok, 0 failed, 2338.65 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🥱 custom column '_validation_skeleton' progress: 4/10 (40%) complete, 4 ok, 0 failed, 2496.03 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😐 custom column '_validation_skeleton' progress: 5/10 (50%) complete, 5 ok, 0 failed, 2731.93 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😐 custom column '_validation_skeleton' progress: 6/10 (60%) complete, 6 ok, 0 failed, 2281.51 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😐 custom column '_validation_skeleton' progress: 7/10 (70%) complete, 7 ok, 0 failed, 2310.58 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😊 custom column '_validation_skeleton' progress: 8/10 (80%) complete, 8 ok, 0 failed, 2496.36 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 😊 custom column '_validation_skeleton' progress: 9/10 (90%) complete, 9 ok, 0 failed, 2603.79 rec/s, eta 0.0s
[12:08:39] [INFO]   |-- 🤩 custom column '_validation_skeleton' progress: 10/10 (100%) complete, 10 ok, 0 failed, 2763.77 rec/s, eta 0.0s
[12:08:39] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'
[12:08:39] [INFO]   |-- model: 'openai/gpt-oss-120b'
[12:08:39] [INFO]   |-- model alias: 'gpt-oss-120b'
[12:08:39] [INFO]   |-- model provider: 'nvidia'
[12:08:39] [INFO]   |-- inference parameters:
[12:08:39] [INFO]   |  |-- generation_type=chat-completion
[12:08:39] [INFO]   |  |-- max_parallel_requests=16
[12:08:39] [INFO]   |  |-- timeout=300
[12:08:39] [INFO]   |  |-- temperature=0.30
[12:08:39] [INFO]   |  |-- top_p=0.95
[12:08:39] [INFO]   |  |-- max_tokens=16384
[12:08:39] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers
[12:08:39] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record
[12:08:52] [INFO]   |-- 🚶 llm-structured column '_validation_decisions' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 117.0s
[12:08:53] [INFO]   |-- 🚶 llm-structured column '_validation_decisions' progress: 2/10 (20%) complete, 2 ok, 0 failed, 0.15 rec/s, eta 54.7s
[12:08:56] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 3/10 (30%) complete, 3 ok, 0 failed, 0.18 rec/s, eta 39.1s
[12:08:56] [INFO]   |-- 🐴 llm-structured column '_validation_decisions' progress: 4/10 (40%) complete, 4 ok, 0 failed, 0.24 rec/s, eta 25.3s
[12:08:57] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 5/10 (50%) complete, 5 ok, 0 failed, 0.28 rec/s, eta 17.7s
[12:08:57] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 6/10 (60%) complete, 6 ok, 0 failed, 0.33 rec/s, eta 12.0s
[12:08:57] [INFO]   |-- 🚗 llm-structured column '_validation_decisions' progress: 7/10 (70%) complete, 7 ok, 0 failed, 0.38 rec/s, eta 7.8s
[12:08:59] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 8/10 (80%) complete, 8 ok, 0 failed, 0.41 rec/s, eta 4.9s
[12:08:59] [INFO]   |-- ✈️ llm-structured column '_validation_decisions' progress: 9/10 (90%) complete, 9 ok, 0 failed, 0.46 rec/s, eta 2.2s
[12:08:59] [INFO]   |-- 🚀 llm-structured column '_validation_decisions' progress: 10/10 (100%) complete, 10 ok, 0 failed, 0.50 rec/s, eta 0.0s
[12:08:59] [INFO] 🔧 Custom column config for column '_validated_entities'
[12:08:59] [INFO]   |-- generator_function: 'enrich_validation_decisions'
[12:08:59] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:08:59] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']
[12:08:59] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers
[12:08:59] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record
[12:08:59] [INFO]   |-- 🥚 custom column '_validated_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 486.08 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🥚 custom column '_validated_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 639.60 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐣 custom column '_validated_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 751.14 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐣 custom column '_validated_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 876.96 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 690.52 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 750.99 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 781.66 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐤 custom column '_validated_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 795.65 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐤 custom column '_validated_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 867.52 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐔 custom column '_validated_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 912.09 rec/s, eta 0.0s
[12:08:59] [INFO] 🔧 Custom column config for column '_seed_entities_json'
[12:08:59] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'
[12:08:59] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:08:59] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']
[12:08:59] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']
[12:08:59] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers
[12:08:59] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record
[12:08:59] [INFO]   |-- 🐱 custom column '_seed_entities_json' progress: 1/10 (10%) complete, 1 ok, 0 failed, 628.26 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🐱 custom column '_seed_entities_json' progress: 2/10 (20%) complete, 2 ok, 0 failed, 694.89 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😺 custom column '_seed_entities_json' progress: 3/10 (30%) complete, 3 ok, 0 failed, 706.56 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😺 custom column '_seed_entities_json' progress: 4/10 (40%) complete, 4 ok, 0 failed, 736.90 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😸 custom column '_seed_entities_json' progress: 5/10 (50%) complete, 5 ok, 0 failed, 768.93 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😸 custom column '_seed_entities_json' progress: 6/10 (60%) complete, 6 ok, 0 failed, 884.58 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😸 custom column '_seed_entities_json' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1004.29 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😼 custom column '_seed_entities_json' progress: 8/10 (80%) complete, 8 ok, 0 failed, 880.76 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 😼 custom column '_seed_entities_json' progress: 9/10 (90%) complete, 9 ok, 0 failed, 944.47 rec/s, eta 0.0s
[12:08:59] [INFO]   |-- 🦁 custom column '_seed_entities_json' progress: 10/10 (100%) complete, 10 ok, 0 failed, 984.51 rec/s, eta 0.0s
[12:08:59] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'
[12:08:59] [INFO]   |-- model: 'openai/gpt-oss-120b'
[12:08:59] [INFO]   |-- model alias: 'gpt-oss-120b'
[12:08:59] [INFO]   |-- model provider: 'nvidia'
[12:08:59] [INFO]   |-- inference parameters:
[12:08:59] [INFO]   |  |-- generation_type=chat-completion
[12:08:59] [INFO]   |  |-- max_parallel_requests=16
[12:08:59] [INFO]   |  |-- timeout=300
[12:08:59] [INFO]   |  |-- temperature=0.30
[12:08:59] [INFO]   |  |-- top_p=0.95
[12:08:59] [INFO]   |  |-- max_tokens=16384
[12:08:59] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers
[12:08:59] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record
[12:09:02] [INFO]   |-- 🌑 llm-structured column '_augmented_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.39 rec/s, eta 23.2s
[12:09:02] [INFO]   |-- 🌑 llm-structured column '_augmented_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 0.64 rec/s, eta 12.6s
[12:09:02] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 0.88 rec/s, eta 8.0s
[12:09:03] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1.09 rec/s, eta 5.5s
[12:09:03] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 1.32 rec/s, eta 3.8s
[12:09:03] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1.41 rec/s, eta 2.8s
[12:09:04] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1.52 rec/s, eta 2.0s
[12:09:04] [INFO]   |-- 🌖 llm-structured column '_augmented_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1.63 rec/s, eta 1.2s
[12:09:04] [INFO]   |-- 🌖 llm-structured column '_augmented_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1.67 rec/s, eta 0.6s
[12:09:05] [INFO]   |-- 🌕 llm-structured column '_augmented_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1.80 rec/s, eta 0.0s
[12:09:05] [INFO] 🔧 Custom column config for column '_merged_entities'
[12:09:05] [INFO]   |-- generator_function: 'merge_and_build_candidates'
[12:09:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[12:09:05] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']
[12:09:05] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[12:09:05] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers
[12:09:05] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record
[12:09:05] [INFO]   |-- 🌧️ custom column '_merged_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 561.88 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- 🌧️ custom column '_merged_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 358.37 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- 🌦️ custom column '_merged_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 420.91 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- 🌦️ custom column '_merged_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 471.52 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- ⛅ custom column '_merged_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 436.68 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- ⛅ custom column '_merged_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 506.76 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- ⛅ custom column '_merged_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 546.04 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- 🌤️ custom column '_merged_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 485.22 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- 🌤️ custom column '_merged_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 527.17 rec/s, eta 0.0s
[12:09:05] [INFO]   |-- ☀️ custom column '_merged_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 573.55 rec/s, eta 0.0s
[12:09:05] [INFO] 🔧 Custom column config for column '_detected_entities'
[12:09:05] [INFO]   |-- generator_function: 'apply_validation_and_finalize'

In [5]:
preview.display_record(1)

IndexError: Record index 1 is out of bounds for 1 records.

In [ ]:
# preview.trace_dataframe.to_csv("temp_results_rewrite.csv")

In [ ]:
preview

PreviewResult(rows=2, columns=6, trace_columns=43, failed_records=0, preview_num_records=2)

## Inspect the results

`result.dataframe` has user-facing columns only.
`result.trace_dataframe` has every intermediate column for debugging.

In [ ]:
config = AnonymizerConfig(rewrite=Rewrite())
result = anonymizer.run(config=config, data=input_data)

print(result)
result.dataframe.head()

[02:14:56] [INFO] 📂 Loaded 10 records from /Users/lramaswamy/Documents/github/Anonymizer/docs/notebook_source/data/synth_bios_sample10.csv (column: 'bio')
[02:14:56] [DEBUG] input text lengths: min=1529, max=1843, mean=1661 chars (10 records)
[02:14:56] [DEBUG] detection config: threshold=0.30, labels=(default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)
[02:14:56] [INFO] 🔍 Running entity detection on 10 records
[02:14:56] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b
[02:14:56] [DEBUG] NDD workflow 'entity-detection' starting with 10 records
[02:14:56] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']
[02:14:56] [INFO] 🎨 Creating Data Designer dataset
[02:14:56] [INFO] ✅ Validation passed
[02:14:56] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[02:14:56] [INFO] 🩺 Running health checks for models...
[02:14:56] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...
[02:14:57] [INFO]   |-- ✅ Passed!
[02:14:57] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...
[02:14:57] [INFO]   |-- ✅ Passed!
[02:14:57] [INFO] 📂 Dataset path '.anonymizer-artifacts/entity-detection' already exists. Dataset from this session
		     will be saved to '.anonymizer-artifacts/entity-detection_03-26-2026_021457' instead.
[02:14:57] [INFO] ⏳ Processing batch 1 of 1
[02:14:57] [INFO] 🌱 Sampling 10 records from seed dataset
[02:14:57] [INFO]   |-- seed dataset size: 10 records
[02:14:57] [INFO]   |-- sampling strategy: ordered
[02:14:57] [INFO] 📝 llm-text model config for column '_raw_detected_entities'
[02:14:57] [INFO]   |-- model: 'nvidia/gliner-pii'
[02:14:57] [INFO]   |-- model alias: 'gliner-pii-detector'
[02:14:57] [INFO]   |-- model provider: 'nvidia'
[02:14:57] [INFO]   |-- inference parameters:
[02:14:57] [INFO]   |  |-- generation_type=chat-completion
[02:14:57] [INFO]   |  |-- max_parallel_requests=16
[02:14:57] [INFO]   |  |-- timeout=120
[02:14:57] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}
[02:14:57] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers
[02:14:57] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record
[02:14:58] [INFO]   |-- 🐱 llm-text column '_raw_detected_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 2.21 rec/s, eta 4.1s
[02:14:59] [INFO]   |-- 🐱 llm-text column '_raw_detected_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 1.03 rec/s, eta 7.7s
[02:14:59] [INFO]   |-- 😺 llm-text column '_raw_detected_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 1.54 rec/s, eta 4.5s
[02:14:59] [INFO]   |-- 😺 llm-text column '_raw_detected_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1.90 rec/s, eta 3.2s
[02:14:59] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 2.37 rec/s, eta 2.1s
[02:14:59] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 2.62 rec/s, eta 1.5s
[02:15:00] [INFO]   |-- 😸 llm-text column '_raw_detected_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 3.05 rec/s, eta 1.0s
[02:15:00] [INFO]   |-- 😼 llm-text column '_raw_detected_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 3.26 rec/s, eta 0.6s
[02:15:00] [INFO]   |-- 😼 llm-text column '_raw_detected_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 3.66 rec/s, eta 0.3s
[02:15:00] [INFO]   |-- 🦁 llm-text column '_raw_detected_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 4.05 rec/s, eta 0.0s
[02:15:00] [INFO] 🔧 Custom column config for column '_seed_entities'
[02:15:00] [INFO]   |-- generator_function: 'parse_detected_entities'
[02:15:00] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:00] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']
[02:15:00] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']
[02:15:00] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers
[02:15:00] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record
[02:15:00] [INFO]   |-- 🚶 custom column '_seed_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 368.11 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🚶 custom column '_seed_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 457.92 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 535.60 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🐴 custom column '_seed_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 611.27 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 604.36 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 696.02 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🚗 custom column '_seed_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 741.68 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- ✈️ custom column '_seed_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 716.47 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- ✈️ custom column '_seed_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 759.82 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🚀 custom column '_seed_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 803.54 rec/s, eta 0.0s
[02:15:00] [INFO] 🔧 Custom column config for column '_validation_candidates'
[02:15:00] [INFO]   |-- generator_function: 'prepare_validation_inputs'
[02:15:00] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:00] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']
[02:15:00] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[02:15:00] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers
[02:15:00] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record
[02:15:00] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 1/10 (10%) complete, 1 ok, 0 failed, 579.96 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🐱 custom column '_validation_candidates' progress: 2/10 (20%) complete, 2 ok, 0 failed, 859.72 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 3/10 (30%) complete, 3 ok, 0 failed, 909.53 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😺 custom column '_validation_candidates' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1015.15 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 5/10 (50%) complete, 5 ok, 0 failed, 1000.36 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1110.43 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😸 custom column '_validation_candidates' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1140.33 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1172.37 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 😼 custom column '_validation_candidates' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1266.85 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🦁 custom column '_validation_candidates' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1345.19 rec/s, eta 0.0s
[02:15:00] [INFO] 🔧 Custom column config for column '_validation_skeleton'
[02:15:00] [INFO]   |-- generator_function: 'build_validation_skeleton'
[02:15:00] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:00] [INFO]   |-- required_columns: ['_validation_candidates']
[02:15:00] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers
[02:15:00] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record
[02:15:00] [INFO]   |-- 🌑 custom column '_validation_skeleton' progress: 1/10 (10%) complete, 1 ok, 0 failed, 782.88 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌑 custom column '_validation_skeleton' progress: 2/10 (20%) complete, 2 ok, 0 failed, 244.51 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌘 custom column '_validation_skeleton' progress: 3/10 (30%) complete, 3 ok, 0 failed, 333.79 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌘 custom column '_validation_skeleton' progress: 4/10 (40%) complete, 4 ok, 0 failed, 404.97 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 5/10 (50%) complete, 5 ok, 0 failed, 461.69 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 6/10 (60%) complete, 6 ok, 0 failed, 249.27 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌗 custom column '_validation_skeleton' progress: 7/10 (70%) complete, 7 ok, 0 failed, 249.04 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌖 custom column '_validation_skeleton' progress: 8/10 (80%) complete, 8 ok, 0 failed, 273.53 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌖 custom column '_validation_skeleton' progress: 9/10 (90%) complete, 9 ok, 0 failed, 303.38 rec/s, eta 0.0s
[02:15:00] [INFO]   |-- 🌕 custom column '_validation_skeleton' progress: 10/10 (100%) complete, 10 ok, 0 failed, 320.20 rec/s, eta 0.0s
[02:15:00] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'
[02:15:00] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:15:00] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:15:00] [INFO]   |-- model provider: 'nvidia'
[02:15:00] [INFO]   |-- inference parameters:
[02:15:00] [INFO]   |  |-- generation_type=chat-completion
[02:15:00] [INFO]   |  |-- max_parallel_requests=16
[02:15:00] [INFO]   |  |-- timeout=300
[02:15:00] [INFO]   |  |-- temperature=0.30
[02:15:00] [INFO]   |  |-- top_p=0.95
[02:15:00] [INFO]   |  |-- max_tokens=16384
[02:15:00] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers
[02:15:00] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record
[02:15:13] [INFO]   |-- 🥚 llm-structured column '_validation_decisions' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.08 rec/s, eta 114.6s
[02:15:16] [INFO]   |-- 🥚 llm-structured column '_validation_decisions' progress: 2/10 (20%) complete, 2 ok, 0 failed, 0.12 rec/s, eta 66.6s
[02:15:17] [INFO]   |-- 🐣 llm-structured column '_validation_decisions' progress: 3/10 (30%) complete, 3 ok, 0 failed, 0.17 rec/s, eta 40.5s
[02:15:17] [INFO]   |-- 🐣 llm-structured column '_validation_decisions' progress: 4/10 (40%) complete, 4 ok, 0 failed, 0.23 rec/s, eta 26.3s
[02:15:19] [INFO]   |-- 🐥 llm-structured column '_validation_decisions' progress: 5/10 (50%) complete, 5 ok, 0 failed, 0.26 rec/s, eta 19.1s
[02:15:19] [INFO]   |-- 🐥 llm-structured column '_validation_decisions' progress: 6/10 (60%) complete, 6 ok, 0 failed, 0.31 rec/s, eta 13.0s
[02:15:20] [INFO]   |-- 🐥 llm-structured column '_validation_decisions' progress: 7/10 (70%) complete, 7 ok, 0 failed, 0.35 rec/s, eta 8.7s
[02:15:22] [INFO]   |-- 🐤 llm-structured column '_validation_decisions' progress: 8/10 (80%) complete, 8 ok, 0 failed, 0.36 rec/s, eta 5.6s
[02:15:24] [INFO]   |-- 🐤 llm-structured column '_validation_decisions' progress: 9/10 (90%) complete, 9 ok, 0 failed, 0.37 rec/s, eta 2.7s
[02:15:43] [INFO]   |-- 🐔 llm-structured column '_validation_decisions' progress: 10/10 (100%) complete, 10 ok, 0 failed, 0.23 rec/s, eta 0.0s
[02:15:43] [INFO] 🔧 Custom column config for column '_validated_entities'
[02:15:43] [INFO]   |-- generator_function: 'enrich_validation_decisions'
[02:15:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:43] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']
[02:15:43] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers
[02:15:43] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record
[02:15:43] [INFO]   |-- 🥚 custom column '_validated_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 285.92 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🥚 custom column '_validated_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 453.52 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐣 custom column '_validated_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 432.94 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐣 custom column '_validated_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 491.85 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 526.59 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 578.40 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_validated_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 601.39 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐤 custom column '_validated_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 579.74 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐤 custom column '_validated_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 633.73 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐔 custom column '_validated_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 685.42 rec/s, eta 0.0s
[02:15:43] [INFO] 🔧 Custom column config for column '_seed_entities_json'
[02:15:43] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'
[02:15:43] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:43] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']
[02:15:43] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']
[02:15:43] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers
[02:15:43] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record
[02:15:43] [INFO]   |-- 🥚 custom column '_seed_entities_json' progress: 1/10 (10%) complete, 1 ok, 0 failed, 554.16 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🥚 custom column '_seed_entities_json' progress: 2/10 (20%) complete, 2 ok, 0 failed, 668.65 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 3/10 (30%) complete, 3 ok, 0 failed, 616.73 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐣 custom column '_seed_entities_json' progress: 4/10 (40%) complete, 4 ok, 0 failed, 653.99 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 5/10 (50%) complete, 5 ok, 0 failed, 504.14 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 6/10 (60%) complete, 6 ok, 0 failed, 553.65 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐥 custom column '_seed_entities_json' progress: 7/10 (70%) complete, 7 ok, 0 failed, 580.99 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 8/10 (80%) complete, 8 ok, 0 failed, 617.88 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐤 custom column '_seed_entities_json' progress: 9/10 (90%) complete, 9 ok, 0 failed, 650.72 rec/s, eta 0.0s
[02:15:43] [INFO]   |-- 🐔 custom column '_seed_entities_json' progress: 10/10 (100%) complete, 10 ok, 0 failed, 691.05 rec/s, eta 0.0s
[02:15:43] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'
[02:15:43] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:15:43] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:15:43] [INFO]   |-- model provider: 'nvidia'
[02:15:43] [INFO]   |-- inference parameters:
[02:15:43] [INFO]   |  |-- generation_type=chat-completion
[02:15:43] [INFO]   |  |-- max_parallel_requests=16
[02:15:43] [INFO]   |  |-- timeout=300
[02:15:43] [INFO]   |  |-- temperature=0.30
[02:15:43] [INFO]   |  |-- top_p=0.95
[02:15:43] [INFO]   |  |-- max_tokens=16384
[02:15:43] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers
[02:15:43] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record
[02:15:47] [INFO]   |-- 🌧️ llm-structured column '_augmented_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.29 rec/s, eta 31.6s
[02:15:48] [INFO]   |-- 🌧️ llm-structured column '_augmented_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 0.47 rec/s, eta 16.9s
[02:15:48] [INFO]   |-- 🌦️ llm-structured column '_augmented_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 0.62 rec/s, eta 11.4s
[02:15:48] [INFO]   |-- 🌦️ llm-structured column '_augmented_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 0.78 rec/s, eta 7.7s
[02:15:49] [INFO]   |-- ⛅ llm-structured column '_augmented_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 0.93 rec/s, eta 5.4s
[02:15:49] [INFO]   |-- ⛅ llm-structured column '_augmented_entities' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1.08 rec/s, eta 3.7s
[02:15:49] [INFO]   |-- ⛅ llm-structured column '_augmented_entities' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1.17 rec/s, eta 2.6s
[02:15:49] [INFO]   |-- 🌤️ llm-structured column '_augmented_entities' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1.33 rec/s, eta 1.5s
[02:15:49] [INFO]   |-- 🌤️ llm-structured column '_augmented_entities' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1.46 rec/s, eta 0.7s
[02:15:50] [INFO]   |-- ☀️ llm-structured column '_augmented_entities' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1.50 rec/s, eta 0.0s
[02:15:50] [INFO] 🔧 Custom column config for column '_merged_entities'
[02:15:50] [INFO]   |-- generator_function: 'merge_and_build_candidates'
[02:15:50] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:15:50] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']
[02:15:50] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[02:15:50] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers
[02:15:50] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record
[02:15:50] [INFO]   |-- 🐱 custom column '_merged_entities' progress: 1/10 (10%) complete, 1 ok, 0 failed, 492.18 rec/s, eta 0.0s
[02:15:50] [INFO]   |-- 🐱 custom column '_merged_entities' progress: 2/10 (20%) complete, 2 ok, 0 failed, 521.02 rec/s, eta 0.0s
[02:15:50] [INFO]   |-- 😺 custom column '_merged_entities' progress: 3/10 (30%) complete, 3 ok, 0 failed, 632.38 rec/s, eta 0.0s
[02:15:50] [INFO]   |-- 😺 custom column '_merged_entities' progress: 4/10 (40%) complete, 4 ok, 0 failed, 586.17 rec/s, eta 0.0s
[02:15:50] [INFO]   |-- 😸 custom column '_merged_entities' progress: 5/10 (50%) complete, 5 ok, 0 failed, 617.97 rec/s, eta 0.0s

AnonymizerResult(rows=10, columns=6, trace_columns=43, failed_records=0)

,bio,bio_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
0,"Mara Delgado, a 34‑year‑old bartender, has bec...","Elena Khan, a bartender in her mid‑30s, has be...",0.89,0.0,False,False
1,"Dr. Maya Patel, 38, is a pediatric cardiologis...","Dr. Anika Shah, in her late 30s, is a pediatri...",0.961538,0.6,False,False
2,"Mira Alvarez, 38, is an independent film direc...","Elena Khan, in their late 30s, is a filmmaker ...",0.95,0.6,False,False
3,"James “Jim” Alvarez, 34, has been soaring the ...","Ethan “Rex” Kumar, in their mid‑30s, has been ...",0.914286,0.9,False,False
4,"Lena Torres, 31, is a senior game designer at ...","Sofia Khan, in her early 30s, is a senior game...",0.84,0.0,False,False

In [ ]:
result.dataframe

,bio,bio_rewritten,utility_score,leakage_mass,any_high_leaked,needs_human_review
0,"Mara Delgado, a 34‑year‑old bartender, has bec...","Elena Khan, a bartender in her mid‑30s, has be...",0.89,0.0,False,False
1,"Dr. Maya Patel, 38, is a pediatric cardiologis...","Dr. Anika Shah, in her late 30s, is a pediatri...",0.961538,0.6,False,False
2,"Mira Alvarez, 38, is an independent film direc...","Elena Khan, in their late 30s, is a filmmaker ...",0.95,0.6,False,False
3,"James “Jim” Alvarez, 34, has been soaring the ...","Ethan “Rex” Kumar, in their mid‑30s, has been ...",0.914286,0.9,False,False
4,"Lena Torres, 31, is a senior game designer at ...","Sofia Khan, in her early 30s, is a senior game...",0.84,0.0,False,False
5,"Maya Patel, 42, is a tenured professor of Earl...","Sofia Khan, in her early 40s, is a tenured pro...",0.896429,0.6,False,False
6,Maya Patel is a 34‑year‑old lead gameplay prog...,Priya Shah is a lead gameplay programmer in he...,0.954545,0.6,False,False
7,Maya Torres is a 34‑year‑old bartender who has...,Nina Garcia is a bartender in her mid‑30s who ...,1.0,0.0,False,False
8,Megan “Megs” Alvarez is a 38‑year‑old executiv...,Sofia “Sofi” Khan is in her late 30s and works...,0.93,0.0,False,False
9,"Elena Morales, 42, is a senior economist at th...","Isabel Vargas, in her early 40s, is a senior e...",0.954545,0.6,False,False

In [ ]:
result.trace_dataframe.final_entities[0]

{'entities': [{'id': 'first_name_0_4',
   'value': 'Mara',
   'label': 'first_name',
   'start_position': 0,
   'end_position': 4,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'last_name_5_12',
   'value': 'Delgado',
   'label': 'last_name',
   'start_position': 5,
   'end_position': 12,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'age_16_18',
   'value': '34',
   'label': 'age',
   'start_position': 16,
   'end_position': 18,
   'score': 0.996,
   'source': 'detector'},
  {'id': 'occupation_28_37',
   'value': 'bartender',
   'label': 'occupation',
   'start_position': 28,
   'end_position': 37,
   'score': 0.999,
   'source': 'detector'},
  {'id': 'company_name_102_113',
   'value': 'The Lantern',
   'label': 'company_name',
   'start_position': 102,
   'end_position': 113,
   'score': 1.0,
   'source': 'augmenter'},
  {'id': 'city_184_193',
   'value': 'Asheville',
   'label': 'city',
   'start_position': 184,
   'end_position': 193,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'state_195_209',
   'value': 'North Carolina',
   'label': 'state',
   'start_position': 195,
   'end_position': 209,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'city_254_261',
   'value': 'Raleigh',
   'label': 'city',
   'start_position': 254,
   'end_position': 261,
   'score': 0.995,
   'source': 'detector'},
  {'id': 'city_276_285',
   'value': 'Asheville',
   'label': 'city',
   'start_position': 276,
   'end_position': 285,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'education_level_310_342',
   'value': 'degree in hospitality management',
   'label': 'education_level',
   'start_position': 310,
   'end_position': 342,
   'score': 0.81,
   'source': 'detector'},
  {'id': 'first_name_435_439',
   'value': 'Mara',
   'label': 'first_name',
   'start_position': 435,
   'end_position': 439,
   'score': 0.997,
   'source': 'detector'},
  {'id': 'company_name_688_699',
   'value': 'The Lantern',
   'label': 'company_name',
   'start_position': 688,
   'end_position': 699,
   'score': 1.0,
   'source': 'augmenter'},
  {'id': 'first_name_967_971',
   'value': 'Mara',
   'label': 'first_name',
   'start_position': 967,
   'end_position': 971,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'first_name_1074_1078',
   'value': 'Luis',
   'label': 'first_name',
   'start_position': 1074,
   'end_position': 1078,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'occupation_1082_1090',
   'value': 'mechanic',
   'label': 'occupation',
   'start_position': 1082,
   'end_position': 1090,
   'score': 0.999,
   'source': 'detector'},
  {'id': 'first_name_1143_1147',
   'value': 'Rosa',
   'label': 'first_name',
   'start_position': 1143,
   'end_position': 1147,
   'score': 0.999,
   'source': 'detector'},
  {'id': 'first_name_1268_1272',
   'value': 'Rosa',
   'label': 'first_name',
   'start_position': 1268,
   'end_position': 1272,
   'score': 0.999,
   'source': 'detector'},
  {'id': 'first_name_1325_1329',
   'value': 'Mara',
   'label': 'first_name',
   'start_position': 1325,
   'end_position': 1329,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'first_name_1376_1380',
   'value': 'Mara',
   'label': 'first_name',
   'start_position': 1376,
   'end_position': 1380,
   'score': 1.0,
   'source': 'detector'},
  {'id': 'city_1535_1544',
   'value': 'Asheville',
   'label': 'city',
   'start_position': 1535,
   'end_position': 1544,
   'score': 0.992,
   'source': 'detector'},
  {'id': 'occupation_1629_1638',
   'value': 'bartender',
   'label': 'occupation',
   'start_position': 1629,
   'end_position': 1638,
   'score': 0.993,
   'source': 'detector'}]}

## Custom privacy goal

For domain-specific data you can spell out exactly what to protect
and what to preserve.

In [ ]:
from anonymizer.config.rewrite import EvaluationCriteria, PrivacyGoal, RiskTolerance

custom_config = AnonymizerConfig(
    rewrite=Rewrite(
        privacy_goal=PrivacyGoal(
            protect="All direct identifiers, quasi-identifier combinations, and medical record numbers",
            preserve="Clinical meaning, temporal relationships, and treatment outcomes",
        ),
        evaluation=EvaluationCriteria(
            risk_tolerance=RiskTolerance.strict,
            max_repair_iterations=3,
        ),
    ),
)

custom_preview = anonymizer.preview(
    config=custom_config,
    data=input_data,
    num_records=3,
)

custom_preview.display_record(0)

[02:22:40] [INFO] 📂 Loaded 10 records from /Users/lramaswamy/Documents/github/Anonymizer/docs/notebook_source/data/synth_bios_sample10.csv (column: 'bio')
[02:22:40] [DEBUG] input text lengths: min=1529, max=1843, mean=1661 chars (10 records)
[02:22:40] [DEBUG] detection config: threshold=0.30, labels=(default: 55 labels; see anonymizer.DEFAULT_ENTITY_LABELS for list)
[02:22:40] [INFO]   |-- 👀 Preview mode: processing 3 of 10 records
[02:22:40] [INFO] 🔍 Running entity detection on 3 records
[02:22:40] [DEBUG] detection aliases: detector=gliner-pii-detector, validator=gpt-oss-120b, augmenter=gpt-oss-120b
[02:22:40] [DEBUG] NDD workflow 'entity-detection' starting with 10 records
[02:22:40] [DEBUG] NDD workflow 'entity-detection': 10 columns ['_raw_detected_entities', '_seed_entities', '_validation_candidates', '_validation_skeleton', '_validation_decisions', '_validated_entities', '_seed_entities_json', '_augmented_entities', '_merged_entities', '_detected_entities']
[02:22:40] [INFO] 👀 Preview generation in progress
[02:22:40] [INFO] ✅ Validation passed
[02:22:40] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[02:22:40] [INFO] 🩺 Running health checks for models...
[02:22:40] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...
[02:22:40] [INFO]   |-- ✅ Passed!
[02:22:40] [INFO]   |-- 👀 Checking 'nvidia/gliner-pii' in provider named 'nvidia' for model alias 'gliner-pii-detector'...
[02:22:41] [INFO]   |-- ✅ Passed!
[02:22:41] [INFO] 🌱 Sampling 3 records from seed dataset
[02:22:41] [INFO]   |-- seed dataset size: 10 records
[02:22:41] [INFO]   |-- sampling strategy: ordered
[02:22:41] [INFO] 📝 llm-text model config for column '_raw_detected_entities'
[02:22:41] [INFO]   |-- model: 'nvidia/gliner-pii'
[02:22:41] [INFO]   |-- model alias: 'gliner-pii-detector'
[02:22:41] [INFO]   |-- model provider: 'nvidia'
[02:22:41] [INFO]   |-- inference parameters:
[02:22:41] [INFO]   |  |-- generation_type=chat-completion
[02:22:41] [INFO]   |  |-- max_parallel_requests=16
[02:22:41] [INFO]   |  |-- timeout=120
[02:22:41] [INFO]   |  |-- extra_body={'labels': ['occupation', 'certificate_license_number', 'first_name', 'date_of_birth', 'ssn', 'medical_record_number', 'password', 'unique_id', 'phone_number', 'national_id', 'swift_bic', 'company_name', 'country', 'license_plate', 'tax_id', 'employee_id', 'pin', 'state', 'email', 'date_time', 'api_key', 'biometric_identifier', 'credit_debit_card', 'coordinate', 'device_identifier', 'city', 'postcode', 'bank_routing_number', 'vehicle_identifier', 'health_plan_beneficiary_number', 'url', 'ipv4', 'last_name', 'cvv', 'customer_id', 'date', 'user_name', 'street_address', 'ipv6', 'account_number', 'time', 'age', 'fax_number', 'county', 'gender', 'sexuality', 'political_view', 'race_ethnicity', 'religious_belief', 'language', 'blood_type', 'mac_address', 'http_cookie', 'employment_status', 'education_level'], 'threshold': 0.3, 'chunk_length': 384, 'overlap': 128, 'flat_ner': False}
[02:22:41] [INFO] ⚡️ Processing llm-text column '_raw_detected_entities' with 16 concurrent workers
[02:22:41] [INFO] ⏱️ llm-text column '_raw_detected_entities' will report progress after each record
[02:22:41] [INFO]   |-- 🐣 llm-text column '_raw_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 2.28 rec/s, eta 0.9s
[02:22:42] [INFO]   |-- 🐥 llm-text column '_raw_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.67 rec/s, eta 0.4s
[02:22:42] [INFO]   |-- 🐔 llm-text column '_raw_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 3.25 rec/s, eta 0.0s
[02:22:42] [INFO] 🔧 Custom column config for column '_seed_entities'
[02:22:42] [INFO]   |-- generator_function: 'parse_detected_entities'
[02:22:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:22:42] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_raw_detected_entities']
[02:22:42] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json', '_tag_notation']
[02:22:42] [INFO] ⚡️ Processing custom column '_seed_entities' with 4 concurrent workers
[02:22:42] [INFO] ⏱️ custom column '_seed_entities' will report progress after each record
[02:22:42] [INFO]   |-- 🌘 custom column '_seed_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 372.09 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 🌗 custom column '_seed_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 462.93 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 🌕 custom column '_seed_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 469.97 rec/s, eta 0.0s
[02:22:42] [INFO] 🔧 Custom column config for column '_validation_candidates'
[02:22:42] [INFO]   |-- generator_function: 'prepare_validation_inputs'
[02:22:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:22:42] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities']
[02:22:42] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[02:22:42] [INFO] ⚡️ Processing custom column '_validation_candidates' with 4 concurrent workers
[02:22:42] [INFO] ⏱️ custom column '_validation_candidates' will report progress after each record
[02:22:42] [INFO]   |-- 🌘 custom column '_validation_candidates' progress: 1/3 (33%) complete, 1 ok, 0 failed, 577.52 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 🌗 custom column '_validation_candidates' progress: 2/3 (67%) complete, 2 ok, 0 failed, 727.86 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 🌕 custom column '_validation_candidates' progress: 3/3 (100%) complete, 3 ok, 0 failed, 698.29 rec/s, eta 0.0s
[02:22:42] [INFO] 🔧 Custom column config for column '_validation_skeleton'
[02:22:42] [INFO]   |-- generator_function: 'build_validation_skeleton'
[02:22:42] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:22:42] [INFO]   |-- required_columns: ['_validation_candidates']
[02:22:42] [INFO] ⚡️ Processing custom column '_validation_skeleton' with 4 concurrent workers
[02:22:42] [INFO] ⏱️ custom column '_validation_skeleton' will report progress after each record
[02:22:42] [INFO]   |-- 😺 custom column '_validation_skeleton' progress: 1/3 (33%) complete, 1 ok, 0 failed, 706.40 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 😸 custom column '_validation_skeleton' progress: 2/3 (67%) complete, 2 ok, 0 failed, 815.91 rec/s, eta 0.0s
[02:22:42] [INFO]   |-- 🦁 custom column '_validation_skeleton' progress: 3/3 (100%) complete, 3 ok, 0 failed, 782.01 rec/s, eta 0.0s
[02:22:42] [INFO] 🗂️ llm-structured model config for column '_validation_decisions'
[02:22:42] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:22:42] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:22:42] [INFO]   |-- model provider: 'nvidia'
[02:22:42] [INFO]   |-- inference parameters:
[02:22:42] [INFO]   |  |-- generation_type=chat-completion
[02:22:42] [INFO]   |  |-- max_parallel_requests=16
[02:22:42] [INFO]   |  |-- timeout=300
[02:22:42] [INFO]   |  |-- temperature=0.30
[02:22:42] [INFO]   |  |-- top_p=0.95
[02:22:42] [INFO]   |  |-- max_tokens=16384
[02:22:42] [INFO] ⚡️ Processing llm-structured column '_validation_decisions' with 16 concurrent workers
[02:22:42] [INFO] ⏱️ llm-structured column '_validation_decisions' will report progress after each record
[02:22:57] [INFO]   |-- 🌦️ llm-structured column '_validation_decisions' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.07 rec/s, eta 29.8s
[02:22:57] [INFO]   |-- ⛅ llm-structured column '_validation_decisions' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.13 rec/s, eta 7.8s
[02:22:58] [INFO]   |-- ☀️ llm-structured column '_validation_decisions' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.19 rec/s, eta 0.0s
[02:22:58] [INFO] 🔧 Custom column config for column '_validated_entities'
[02:22:58] [INFO]   |-- generator_function: 'enrich_validation_decisions'
[02:22:58] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:22:58] [INFO]   |-- required_columns: ['_validation_decisions', '_validation_candidates']
[02:22:58] [INFO] ⚡️ Processing custom column '_validated_entities' with 4 concurrent workers
[02:22:58] [INFO] ⏱️ custom column '_validated_entities' will report progress after each record
[02:22:58] [INFO]   |-- 🌦️ custom column '_validated_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 492.68 rec/s, eta 0.0s
[02:22:58] [INFO]   |-- ⛅ custom column '_validated_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 578.42 rec/s, eta 0.0s
[02:22:58] [INFO]   |-- ☀️ custom column '_validated_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 682.79 rec/s, eta 0.0s
[02:22:58] [INFO] 🔧 Custom column config for column '_seed_entities_json'
[02:22:58] [INFO]   |-- generator_function: 'apply_validation_to_seed_entities'
[02:22:58] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:22:58] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_validated_entities']
[02:22:58] [INFO]   |-- side_effect_columns: ['_initial_tagged_text', '_seed_entities_json']
[02:22:58] [INFO] ⚡️ Processing custom column '_seed_entities_json' with 4 concurrent workers
[02:22:58] [INFO] ⏱️ custom column '_seed_entities_json' will report progress after each record
[02:22:58] [INFO]   |-- 🥱 custom column '_seed_entities_json' progress: 1/3 (33%) complete, 1 ok, 0 failed, 514.84 rec/s, eta 0.0s
[02:22:58] [INFO]   |-- 😐 custom column '_seed_entities_json' progress: 2/3 (67%) complete, 2 ok, 0 failed, 718.69 rec/s, eta 0.0s
[02:22:58] [INFO]   |-- 🤩 custom column '_seed_entities_json' progress: 3/3 (100%) complete, 3 ok, 0 failed, 616.76 rec/s, eta 0.0s
[02:22:58] [INFO] 🗂️ llm-structured model config for column '_augmented_entities'
[02:22:58] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:22:58] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:22:58] [INFO]   |-- model provider: 'nvidia'
[02:22:58] [INFO]   |-- inference parameters:
[02:22:58] [INFO]   |  |-- generation_type=chat-completion
[02:22:58] [INFO]   |  |-- max_parallel_requests=16
[02:22:58] [INFO]   |  |-- timeout=300
[02:22:58] [INFO]   |  |-- temperature=0.30
[02:22:58] [INFO]   |  |-- top_p=0.95
[02:22:58] [INFO]   |  |-- max_tokens=16384
[02:22:58] [INFO] ⚡️ Processing llm-structured column '_augmented_entities' with 16 concurrent workers
[02:22:58] [INFO] ⏱️ llm-structured column '_augmented_entities' will report progress after each record
[02:23:00] [INFO]   |-- 🌘 llm-structured column '_augmented_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.47 rec/s, eta 4.2s
[02:23:03] [INFO]   |-- 🌗 llm-structured column '_augmented_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.45 rec/s, eta 2.2s
[02:23:05] [INFO]   |-- 🌕 llm-structured column '_augmented_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.46 rec/s, eta 0.0s
[02:23:05] [INFO] 🔧 Custom column config for column '_merged_entities'
[02:23:05] [INFO]   |-- generator_function: 'merge_and_build_candidates'
[02:23:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:23:05] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_seed_entities', '_augmented_entities']
[02:23:05] [INFO]   |-- side_effect_columns: ['_merged_tagged_text', '_validation_candidates']
[02:23:05] [INFO] ⚡️ Processing custom column '_merged_entities' with 4 concurrent workers
[02:23:05] [INFO] ⏱️ custom column '_merged_entities' will report progress after each record
[02:23:05] [INFO]   |-- 🌘 custom column '_merged_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 410.77 rec/s, eta 0.0s
[02:23:05] [INFO]   |-- 🌗 custom column '_merged_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 409.16 rec/s, eta 0.0s
[02:23:05] [INFO]   |-- 🌕 custom column '_merged_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 356.86 rec/s, eta 0.0s
[02:23:05] [INFO] 🔧 Custom column config for column '_detected_entities'
[02:23:05] [INFO]   |-- generator_function: 'apply_validation_and_finalize'
[02:23:05] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:23:05] [INFO]   |-- required_columns: ['__nemo_anonymizer_text_input__', '_merged_entities', '_validated_entities']
[02:23:05] [INFO]   |-- side_effect_columns: ['tagged_text']
[02:23:05] [INFO] ⚡️ Processing custom column '_detected_entities' with 4 concurrent workers
[02:23:05] [INFO] ⏱️ custom column '_detected_entities' will report progress after each record
[02:23:05] [INFO]   |-- 🌦️ custom column '_detected_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 379.67 rec/s, eta 0.0s
[02:23:05] [INFO]   |-- ⛅ custom column '_detected_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 385.54 rec/s, eta 0.0s
[02:23:05] [INFO]   |-- ☀️ custom column '_detected_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 394.73 rec/s, eta 0.0s
[02:23:05] [INFO] 📊 Model usage summary:
[02:23:05] [INFO]   |-- model: openai/gpt-oss-120b
[02:23:05] [INFO]   |-- tokens: input=23603, output=11816, total=35419, tps=1475
[02:23:05] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=14
[02:23:05] [INFO]   |--
[02:23:05] [INFO]   |-- model: nvidia/gliner-pii
[02:23:05] [INFO]   |-- tokens: input=786, output=1889, total=2675, tps=111
[02:23:05] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=7
[02:23:05] [INFO] 🙈 Dropping columns: ['_validation_skeleton', '_validation_decisions']
[02:23:05] [INFO] 📐 Measuring dataset column statistics:
[02:23:05] [INFO]   |-- 📝 column: '_raw_detected_entities'
[02:23:05] [INFO]   |-- 🔧 column: '_seed_entities'
[02:23:05] [INFO]   |-- 🔧 column: '_validation_candidates'
[02:23:05] [INFO]   |-- 🔧 column: '_validated_entities'
[02:23:05] [INFO]   |-- 🔧 column: '_seed_entities_json'
[02:23:05] [INFO]   |-- 🗂️ column: '_augmented_entities'
[02:23:05] [INFO]   |-- 🔧 column: '_merged_entities'
[02:23:05] [INFO]   |-- 🔧 column: '_detected_entities'
[02:23:05] [INFO] 🎉 Preview complete!
[02:23:05] [DEBUG] NDD workflow 'entity-detection' returned 3 records
[02:23:05] [DEBUG] NDD workflow 'latent-entity-detection' starting with 3 records
[02:23:05] [DEBUG] NDD workflow 'latent-entity-detection': 1 columns ['_latent_entities']
[02:23:05] [INFO] 📸 Preview generation in progress
[02:23:05] [INFO] ✅ Validation passed
[02:23:05] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[02:23:05] [INFO] 🩺 Running health checks for models...
[02:23:05] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-30b-thinking'...
[02:23:06] [INFO]   |-- ✅ Passed!
[02:23:06] [INFO] 🌱 Sampling 3 records from seed dataset
[02:23:06] [INFO]   |-- seed dataset size: 3 records
[02:23:06] [INFO]   |-- sampling strategy: ordered
[02:23:06] [INFO] 🗂️ llm-structured model config for column '_latent_entities'
[02:23:06] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'
[02:23:06] [INFO]   |-- model alias: 'nemotron-30b-thinking'
[02:23:06] [INFO]   |-- model provider: 'nvidia'
[02:23:06] [INFO]   |-- inference parameters:
[02:23:06] [INFO]   |  |-- generation_type=chat-completion
[02:23:06] [INFO]   |  |-- max_parallel_requests=16
[02:23:06] [INFO]   |  |-- timeout=300
[02:23:06] [INFO]   |  |-- temperature=0.40
[02:23:06] [INFO]   |  |-- top_p=1.00
[02:23:06] [INFO]   |  |-- max_tokens=8192
[02:23:06] [INFO] ⚡️ Processing llm-structured column '_latent_entities' with 16 concurrent workers
[02:23:06] [INFO] ⏱️ llm-structured column '_latent_entities' will report progress after each record
[02:23:22] [INFO]   |-- 🐴 llm-structured column '_latent_entities' progress: 1/3 (33%) complete, 1 ok, 0 failed, 0.06 rec/s, eta 31.8s
[02:23:31] [INFO]   |-- 🚗 llm-structured column '_latent_entities' progress: 2/3 (67%) complete, 2 ok, 0 failed, 0.08 rec/s, eta 12.7s
[02:23:31] [INFO]   |-- 🚀 llm-structured column '_latent_entities' progress: 3/3 (100%) complete, 3 ok, 0 failed, 0.12 rec/s, eta 0.0s
[02:23:32] [INFO] 📊 Model usage summary:
[02:23:32] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b
[02:23:32] [INFO]   |-- tokens: input=5864, output=11288, total=17152, tps=661
[02:23:32] [INFO]   |-- requests: success=3, failed=0, total=3, rpm=6
[02:23:32] [INFO] 📐 Measuring dataset column statistics:
[02:23:32] [INFO]   |-- 🗂️ column: '_latent_entities'
[02:23:32] [INFO] 🥳 Preview complete!
[02:23:32] [DEBUG] NDD workflow 'latent-entity-detection' returned 3 records
[02:23:32] [INFO]   |-- 📋 Detection complete — 74 entities found across 3 records (0 failed) [52.2s]
[02:23:32] [INFO]   |-- labels: first_name=27, occupation=13, city=10, age=5, company_name=5, state=4, education_level=4, last_name=2, full_name=2, employment_status=1, street_address=1
[02:23:32] [INFO] ✏️ Running rewrite pipeline
[02:23:32] [DEBUG] NDD workflow 'rewrite-pre-generation' starting with 3 records
[02:23:32] [DEBUG] NDD workflow 'rewrite-pre-generation': 8 columns ['_domain', '_domain_supplement', '_sensitivity_disposition', '_sensitivity_disposition_block', '_meaning_units', '_meaning_units_serialized', '_quality_qa', '_privacy_qa']
[02:23:32] [INFO] 🕵️ Preview generation in progress
[02:23:32] [INFO] ✅ Validation passed
[02:23:32] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph
[02:23:32] [INFO] 🩺 Running health checks for models...
[02:23:32] [INFO]   |-- 👀 Checking 'openai/gpt-oss-120b' in provider named 'nvidia' for model alias 'gpt-oss-120b'...
[02:23:32] [INFO]   |-- ✅ Passed!
[02:23:32] [INFO] 🌱 Sampling 3 records from seed dataset
[02:23:32] [INFO]   |-- seed dataset size: 3 records
[02:23:32] [INFO]   |-- sampling strategy: ordered
[02:23:32] [INFO] 🗂️ llm-structured model config for column '_domain'
[02:23:32] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:23:32] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:23:32] [INFO]   |-- model provider: 'nvidia'
[02:23:32] [INFO]   |-- inference parameters:
[02:23:32] [INFO]   |  |-- generation_type=chat-completion
[02:23:32] [INFO]   |  |-- max_parallel_requests=16
[02:23:32] [INFO]   |  |-- timeout=300
[02:23:32] [INFO]   |  |-- temperature=0.30
[02:23:32] [INFO]   |  |-- top_p=0.95
[02:23:32] [INFO]   |  |-- max_tokens=16384
[02:23:32] [INFO] ⚡️ Processing llm-structured column '_domain' with 16 concurrent workers
[02:23:32] [INFO] ⏱️ llm-structured column '_domain' will report progress after each record
[02:23:33] [INFO]   |-- 🐣 llm-structured column '_domain' progress: 1/3 (33%) complete, 1 ok, 0 failed, 1.32 rec/s, eta 1.5s
[02:23:33] [INFO]   |-- 🐥 llm-structured column '_domain' progress: 2/3 (67%) complete, 2 ok, 0 failed, 2.32 rec/s, eta 0.4s
[02:23:33] [INFO]   |-- 🐔 llm-structured column '_domain' progress: 3/3 (100%) complete, 3 ok, 0 failed, 3.13 rec/s, eta 0.0s
[02:23:33] [INFO] 🔧 Custom column config for column '_domain_supplement'
[02:23:33] [INFO]   |-- generator_function: '_enrich_domain'
[02:23:33] [INFO]   |-- generation_strategy: <GenerationStrategy.CELL_BY_CELL: 'cell_by_cell'>
[02:23:33] [INFO]   |-- required_columns: ['_domain']
[02:23:33] [INFO] ⚡️ Processing custom column '_domain_supplement' with 4 concurrent workers
[02:23:33] [INFO] ⏱️ custom column '_domain_supplement' will report progress after each record
[02:23:33] [INFO]   |-- 😺 custom column '_domain_supplement' progress: 1/3 (33%) complete, 1 ok, 0 failed, 960.42 rec/s, eta 0.0s
[02:23:33] [INFO]   |-- 😸 custom column '_domain_supplement' progress: 2/3 (67%) complete, 2 ok, 0 failed, 1268.53 rec/s, eta 0.0s
[02:23:33] [INFO]   |-- 🦁 custom column '_domain_supplement' progress: 3/3 (100%) complete, 3 ok, 0 failed, 1015.59 rec/s, eta 0.0s
[02:23:33] [INFO] 🗂️ llm-structured model config for column '_sensitivity_disposition'
[02:23:33] [INFO]   |-- model: 'openai/gpt-oss-120b'
[02:23:33] [INFO]   |-- model alias: 'gpt-oss-120b'
[02:23:33] [INFO]   |-- model provider: 'nvidia'
[02:23:33] [INFO]   |-- inference parameters:
[02:23:33] [INFO]   |  |-- generation_type=chat-completion

## Filter by review flag

Records where automated metrics exceed thresholds are flagged for manual review.

In [ ]:
df = result.dataframe
flagged = df[df["needs_human_review"] == True]  # noqa: E712
print(f"{len(flagged)} of {len(df)} records flagged for human review")
flagged.head()

0 of 10 records flagged for human review

Empty DataFrame
Columns: [bio, bio_rewritten, utility_score, leakage_mass, any_high_leaked, needs_human_review]
Index: []